========================================================================================================================

gene_id            %id    %sim   %cov   %t5   %gap  %t3   start..stop      pep sz ref sz ref id            definition
NC_006312.1.1      100.0  100.0  99.6   0.0   0.0   0.4   1..723           241    242    Seg6prot1A        CM1 | CM1 protein
                                                          957..957                                         
                    missing exon 2

CLUSTAL 2.1 multiple sequence alignment


predicted       MAHEILIAETEAFLKNVAPETRTAIISAITGGKSACKSAAKLIKNEHLPLMSGEATTMHI
reference       MAHEILIAETEAFLKNVAPETRTAIISAITGGKSACKSAAKLIKNEHLPLMSGEATTMHI
                ************************************************************

predicted       VMRCLYPEIKPWKKASDMLNKATSSLKKSEGRDIRKQMKAAGDFLGVESMMKMRAFRDDQ
reference       VMRCLYPEIKPWKKASDMLNKATSSLKKSEGRDIRKQMKAAGDFLGVESMMKMRAFRDDQ
                ************************************************************

predicted       IMEMVEEVYDHPDDYTPDIRIGTITAWLRCKNKKSERYRSNVSESGRTALKIHEVRKAST
reference       IMEMVEEVYDHPDDYTPDIRIGTITAWLRCKNKKSERYRSNVSESGRTALKIHEVRKAST
                ************************************************************

predicted       AMNEIAGITGLGEEALSLQRQTESLAILCNHTFGSNIMRPHLEKAIKGVEGRVGEMGRMA
reference       AMNEIAGITGLGEEALSLQRQTESLAILCNHTFGSNIMRPHLEKAIKGVEGRVGEMGRMA
                ************************************************************

predicted       M-
reference       MK
                *

>NC_006312.1.1	1	957
ATGGCACATGAAATACTGATTGCTGAAACAGAGGCATTTCTAAAAAATGTTGCTCCTGAG
ACCAGGACAGCAATAATTTCAGCAATAACAGGAGGAAAATCAGCCTGCAAATCAGCAGCT
AAACTGATTAAGAATGAACATCTTCCCCTAATGTCTGGAGAAGCCACCACAATGCACATC
GTTATGAGGTGCTTATATCCTGAAATAAAACCATGGAAAAAGGCAAGCGACATGCTGAAT
AAAGCAACTTCTAGTTTGAAAAAATCAGAAGGAAGAGACATAAGAAAGCAAATGAAAGCA
GCTGGAGACTTCTTGGGAGTGGAGTCAATGATGAAAATGAGGGCCTTCAGAGATGACCAA
ATAATGGAAATGGTTGAAGAAGTATATGATCACCCAGACGACTACACACCAGACATCCGA
ATAGGAACAATCACAGCTTGGTTGAGATGCAAAAACAAGAAAAGTGAAAGATACAGGAGT
AATGTCTCAGAAAGTGGAAGAACAGCTTTAAAAATTCATGAAGTAAGAAAAGCCAGCACA
GCAATGAACGAGATTGCTGGTATTACTGGCCTTGGAGAAGAAGCACTATCTCTCCAAAGA
CAAACAGAAAGTTTGGCCATATTATGTAATCACACTTTTGGAAGTAATATAATGAGACCC
CACTTGGAAAAAGCAATAAAAGGAGTTGAAGGCAGAGTTGGAGAGATGGGACGAATGGCA
ATGaaatggttagttgttataatatgtttctctataacaagtcaacctgcttctgcttgc
aatctaaagacctgtctaaaactatttaacaatactgatgcggtaactgttcattgtttt
aatgaaaaccaaggatacatgctaacattagcctctttgggattagggataattactatg
ttgtatttattagtaaaaatcataattgaacttgtcaatggttttgtgctcggcagAtgg
gagagatggtgtggagatataaagaccacaattatgcctgaaattgactcgatggaaaaa
gatattgccctttctagggagagacttgacctgggagaggatgctcctgacgaaaccgac
aactcaccaattcctttttccaatgatggtatttttgaaatttaa

Length = 242

Score =   567 bits (1232), Expect = e-166
Identities = 242/242 (100%), Positives = 242/242 (100%)
Frame = +1

Query: 1   MAHEILIAETEAFLKNVAPETRTAIISAITGGKSACKSAAKLIKNEHLPLMSGEATTMHI 180
           MAHEILIAETEAFLKNVAPETRTAIISAITGGKSACKSAAKLIKNEHLPLMSGEATTMHI
Sbjct: 1   MAHEILIAETEAFLKNVAPETRTAIISAITGGKSACKSAAKLIKNEHLPLMSGEATTMHI 60

Query: 181 VMRCLYPEIKPWKKASDMLNKATSSLKKSEGRDIRKQMKAAGDFLGVESMMKMRAFRDDQ 360
           VMRCLYPEIKPWKKASDMLNKATSSLKKSEGRDIRKQMKAAGDFLGVESMMKMRAFRDDQ
Sbjct: 61  VMRCLYPEIKPWKKASDMLNKATSSLKKSEGRDIRKQMKAAGDFLGVESMMKMRAFRDDQ 120

Query: 361 IMEMVEEVYDHPDDYTPDIRIGTITAWLRCKNKKSERYRSNVSESGRTALKIHEVRKAST 540
           IMEMVEEVYDHPDDYTPDIRIGTITAWLRCKNKKSERYRSNVSESGRTALKIHEVRKAST
Sbjct: 121 IMEMVEEVYDHPDDYTPDIRIGTITAWLRCKNKKSERYRSNVSESGRTALKIHEVRKAST 180

Query: 541 AMNEIAGITGLGEEALSLQRQTESLAILCNHTFGSNIMRPHLEKAIKGVEGRVGEMGRMA 720
           AMNEIAGITGLGEEALSLQRQTESLAILCNHTFGSNIMRPHLEKAIKGVEGRVGEMGRMA
Sbjct: 181 AMNEIAGITGLGEEALSLQRQTESLAILCNHTFGSNIMRPHLEKAIKGVEGRVGEMGRMA 240

Query: 721 MK 726
           MK
Sbjct: 241 MK 242


========================================================================================================================

gene_id            %id    %sim   %cov   %t5   %gap  %t3   start..stop      pep sz ref sz ref id            definition
LC123860.1.1       99.6   100.0  99.6   0.0   0.0   0.4   1..723           241    242    Seg6prot1A        CM1 | CM1 protein
                                                          957..957                                         
                    missing exon 2

CLUSTAL 2.1 multiple sequence alignment


predicted       MAHEILIAETEAFLKNVAPETRTAIISAITGGKSACKSAAKLIKNEHLPLMSGEATTMHI
reference       MAHEILIAETEAFLKNVAPETRTAIISAITGGKSACKSAAKLIKNEHLPLMSGEATTMHI
                ************************************************************

predicted       VMRCLYPEIKPWKKASDMLNKATSSLKKSEGRDIRKQMKAAGDFLGVESMMKMRAFRDDQ
reference       VMRCLYPEIKPWKKASDMLNKATSSLKKSEGRDIRKQMKAAGDFLGVESMMKMRAFRDDQ
                ************************************************************

predicted       IMEMVEEVYDHPDDYTPDIRIGTITAWLRCKNKKSERYRSNVSESGRTALKIHEVRKAST
reference       IMEMVEEVYDHPDDYTPDIRIGTITAWLRCKNKKSERYRSNVSESGRTALKIHEVRKAST
                ************************************************************

predicted       AMNEIAGIAGLGEEALSLQRQTESLAILCNHTFGSNIMRPHLEKAIKGVEGRVGEMGRMA
reference       AMNEIAGITGLGEEALSLQRQTESLAILCNHTFGSNIMRPHLEKAIKGVEGRVGEMGRMA
                ********:***************************************************

predicted       M-
reference       MK
                *

>LC123860.1.1	1	957
ATGGCACATGAAATATTGATTGCTGAAACAGAGGCATTTCTAAAAAATGTTGCTCCTGAG
ACCAGGACAGCAATAATTTCAGCAATAACAGGTGGAAAATCAGCCTGCAAATCAGCAGCT
AAACTGATCAAGAATGAGCATCTTCCCTTAATGTCTGGGGAAGCCACCACAATGCACATT
GTTATGAGGTGCCTATATCCTGAAATAAAACCATGGAAAAAGGCAAGCGACATGCTGAAT
AAAGCAACTTCTAGTTTGAAAAAATCAGAAGGAAGAGACATCAGAAAGCAAATGAAAGCA
GCTGGAGACTTTTTAGGAGTGGAGTCAATGATGAAAATGAGGGCCTTCAGAGATGACCAA
ATAATGGAAATGGTTGAAGAAGTATATGATCACCCAGACGACTACACACCAGACATCCGA
ATAGGAACAATCACAGCTTGGTTGAGATGCAAAAACAAGAAAAGTGAAAGATACAGGAGT
AATGTCTCAGAAAGTGGAAGAACAGCTTTAAAAATTCATGAAGTAAGAAAAGCCAGTACA
GCAATGAACGAAATTGCTGGTATTGCTGGCCTTGGAGAAGAAGCACTATCTCTCCAAAGA
CAAACAGAAAGTTTAGCCATATTATGCAATCACACTTTTGGAAGTAATATAATGAGACCC
CACTTGGAAAAAGCAATAAAAGGAGTTGAAGGCAGAGTTGGAGAGATGGGACGAATGGCG
ATGaaatggttagttgctataatatgtttctctataataagtcaacctgcttctgcttgc
aatctaaagacctgtctaaacctatttaacaatactgatgcagtaactgttcattgcttt
aatgaaaaccaaggatacatgctaacattagcatctttgggattagggataattactatg
ttgtatttattagtaaaaatcataattgaacttgtcaatggttttgtgctcggcagAtgg
gagagatggtgtggagatataaagaccacaattatgcctgaaattgactcgatggagaaa
gatattgccctttctagggagagacttgacctgggagaggatgcccctgacgaaaccgac
aactcaccaattcccttttccaatgatggtatttttgaaatttaa

Length = 242

Score =   565 bits (1227), Expect = e-165
Identities = 241/242 (99%), Positives = 241/242 (99%)
Frame = +1

Query: 1   MAHEILIAETEAFLKNVAPETRTAIISAITGGKSACKSAAKLIKNEHLPLMSGEATTMHI 180
           MAHEILIAETEAFLKNVAPETRTAIISAITGGKSACKSAAKLIKNEHLPLMSGEATTMHI
Sbjct: 1   MAHEILIAETEAFLKNVAPETRTAIISAITGGKSACKSAAKLIKNEHLPLMSGEATTMHI 60

Query: 181 VMRCLYPEIKPWKKASDMLNKATSSLKKSEGRDIRKQMKAAGDFLGVESMMKMRAFRDDQ 360
           VMRCLYPEIKPWKKASDMLNKATSSLKKSEGRDIRKQMKAAGDFLGVESMMKMRAFRDDQ
Sbjct: 61  VMRCLYPEIKPWKKASDMLNKATSSLKKSEGRDIRKQMKAAGDFLGVESMMKMRAFRDDQ 120

Query: 361 IMEMVEEVYDHPDDYTPDIRIGTITAWLRCKNKKSERYRSNVSESGRTALKIHEVRKAST 540
           IMEMVEEVYDHPDDYTPDIRIGTITAWLRCKNKKSERYRSNVSESGRTALKIHEVRKAST
Sbjct: 121 IMEMVEEVYDHPDDYTPDIRIGTITAWLRCKNKKSERYRSNVSESGRTALKIHEVRKAST 180

Query: 541 AMNEIAGIAGLGEEALSLQRQTESLAILCNHTFGSNIMRPHLEKAIKGVEGRVGEMGRMA 720
           AMNEIAGI GLGEEALSLQRQTESLAILCNHTFGSNIMRPHLEKAIKGVEGRVGEMGRMA
Sbjct: 181 AMNEIAGITGLGEEALSLQRQTESLAILCNHTFGSNIMRPHLEKAIKGVEGRVGEMGRMA 240

Query: 721 MK 726
           MK
Sbjct: 241 MK 242


========================================================================================================================

gene_id            %id    %sim   %cov   %t5   %gap  %t3   start..stop      pep sz ref sz ref id            definition
LC123880.1.1       99.2   100.0  99.6   0.0   0.0   0.4   1..723           241    242    Seg6prot1A        CM1 | CM1 protein
                                                          957..957                                         
                    missing exon 2

CLUSTAL 2.1 multiple sequence alignment


predicted       MAHEILIAETEAFLKNVAPETRTAIISAITGGKSACKSAAKLIKNEHLPLMSGEATTMHI
reference       MAHEILIAETEAFLKNVAPETRTAIISAITGGKSACKSAAKLIKNEHLPLMSGEATTMHI
                ************************************************************

predicted       VMRCLYPEIKPWKKASDMLNKATSSLKKSEGRDIRRQMKAAGDFLGVESMMKMRAFRDDQ
reference       VMRCLYPEIKPWKKASDMLNKATSSLKKSEGRDIRKQMKAAGDFLGVESMMKMRAFRDDQ
                ***********************************:************************

predicted       IMEMVEEVYDHPDDYTPDIRIGTITAWLRCKNKKSERYRSNVSESGRTALKIHEVRKAST
reference       IMEMVEEVYDHPDDYTPDIRIGTITAWLRCKNKKSERYRSNVSESGRTALKIHEVRKAST
                ************************************************************

predicted       AMNEIAGIAGLGEEALSLQRQTESLAILCNHTFGSNIMRPHLEKAIKGVEGRVGEMGRMA
reference       AMNEIAGITGLGEEALSLQRQTESLAILCNHTFGSNIMRPHLEKAIKGVEGRVGEMGRMA
                ********:***************************************************

predicted       M-
reference       MK
                *

>LC123880.1.1	1	957
ATGGCACATGAAATATTGATTGCTGAAACAGAGGCATTTCTAAAAAATGTTGCTCCTGAG
ACCAGGACAGCAATAATTTCAGCAATAACAGGTGGAAAATCAGCCTGCAAATCAGCAGCT
AAACTGATCAAGAATGAGCATCTTCCCTTAATGTCTGGAGAAGCCACCACAATGCACATT
GTTATGAGGTGCCTATATCCTGAAATAAAACCATGGAAAAAGGCAAGCGACATGCTGAAT
AAAGCAACTTCTAGTTTGAAAAAATCAGAAGGAAGAGACATTAGAAGGCAAATGAAAGCA
GCTGGAGACTTTTTGGGAGTGGAGTCAATGATGAAAATGAGGGCCTTCAGAGATGACCAA
ATAATGGAAATGGTTGAAGAAGTATATGATCACCCAGACGACTACACACCAGACATCCGA
ATAGGAACAATCACAGCTTGGTTGAGATGCAAAAACAAGAAAAGTGAAAGATACAGGAGT
AATGTCTCAGAAAGTGGAAGAACAGCTTTAAAAATTCATGAAGTAAGAAAAGCCAGCACA
GCAATGAACGAAATTGCTGGTATTGCTGGTCTTGGAGAAGAAGCACTATCTCTCCAAAGA
CAAACAGAAAGTTTGGCCATATTATGCAATCACACTTTTGGAAGTAATATAATGAGACCC
CACTTGGAAAAAGCAATAAAAGGAGTTGAAGGCAGAGTTGGAGAGATGGGACGAATGGCG
ATGaaatggttagttgttataatgtgtttctctataataagtcaacctgcttctgcttgc
aatctaaagacctgtctaaacctatttaacaatactgatgcagtaactgttcattgcttt
aatgaaaaccaaggatacatgctaacattagcatctttgggattagggataattactatg
ttgtatttattagtaaaaatcataattgaacttgtcaatggttttgtgctcggcagAtgg
gagagatggtgtggagatataaagaccacaattatgcctgaaattgactcgatggagaaa
gatattgccctttctagggagagacttgacctgggagaggatgcccctgacgaaaccgac
aactcaccaattcccttttccaatgatggcatttttgaaatttaa

Length = 242

Score =   563 bits (1224), Expect = e-165
Identities = 240/242 (99%), Positives = 241/242 (99%)
Frame = +1

Query: 1   MAHEILIAETEAFLKNVAPETRTAIISAITGGKSACKSAAKLIKNEHLPLMSGEATTMHI 180
           MAHEILIAETEAFLKNVAPETRTAIISAITGGKSACKSAAKLIKNEHLPLMSGEATTMHI
Sbjct: 1   MAHEILIAETEAFLKNVAPETRTAIISAITGGKSACKSAAKLIKNEHLPLMSGEATTMHI 60

Query: 181 VMRCLYPEIKPWKKASDMLNKATSSLKKSEGRDIRRQMKAAGDFLGVESMMKMRAFRDDQ 360
           VMRCLYPEIKPWKKASDMLNKATSSLKKSEGRDIR+QMKAAGDFLGVESMMKMRAFRDDQ
Sbjct: 61  VMRCLYPEIKPWKKASDMLNKATSSLKKSEGRDIRKQMKAAGDFLGVESMMKMRAFRDDQ 120

Query: 361 IMEMVEEVYDHPDDYTPDIRIGTITAWLRCKNKKSERYRSNVSESGRTALKIHEVRKAST 540
           IMEMVEEVYDHPDDYTPDIRIGTITAWLRCKNKKSERYRSNVSESGRTALKIHEVRKAST
Sbjct: 121 IMEMVEEVYDHPDDYTPDIRIGTITAWLRCKNKKSERYRSNVSESGRTALKIHEVRKAST 180

Query: 541 AMNEIAGIAGLGEEALSLQRQTESLAILCNHTFGSNIMRPHLEKAIKGVEGRVGEMGRMA 720
           AMNEIAGI GLGEEALSLQRQTESLAILCNHTFGSNIMRPHLEKAIKGVEGRVGEMGRMA
Sbjct: 181 AMNEIAGITGLGEEALSLQRQTESLAILCNHTFGSNIMRPHLEKAIKGVEGRVGEMGRMA 240

Query: 721 MK 726
           MK
Sbjct: 241 MK 242


========================================================================================================================

gene_id            %id    %sim   %cov   %t5   %gap  %t3   start..stop      pep sz ref sz ref id            definition
AB000720.1.1       99.6   100.0  99.6   0.0   0.0   0.4   4..726           241    242    Seg6prot1A        CM1 | CM1 protein
                                                          960..960                                         
                    missing exon 2

CLUSTAL 2.1 multiple sequence alignment


predicted       MAHEILIAETEAFLKNVAPETRTAIISAITGGKSACKSAAKLIKNEHLPLMSGEATTMHI
reference       MAHEILIAETEAFLKNVAPETRTAIISAITGGKSACKSAAKLIKNEHLPLMSGEATTMHI
                ************************************************************

predicted       VIRCLYPEIKPWKKASDMLNKATSSLKKSEGRDIRKQMKAAGDFLGVESMMKMRAFRDDQ
reference       VMRCLYPEIKPWKKASDMLNKATSSLKKSEGRDIRKQMKAAGDFLGVESMMKMRAFRDDQ
                *:**********************************************************

predicted       IMEMVEEVYDHPDDYTPDIRIGTITAWLRCKNKKSERYRSNVSESGRTALKIHEVRKAST
reference       IMEMVEEVYDHPDDYTPDIRIGTITAWLRCKNKKSERYRSNVSESGRTALKIHEVRKAST
                ************************************************************

predicted       AMNEIAGITGLGEEALSLQRQTESLAILCNHTFGSNIMRPHLEKAIKGVEGRVGEMGRMA
reference       AMNEIAGITGLGEEALSLQRQTESLAILCNHTFGSNIMRPHLEKAIKGVEGRVGEMGRMA
                ************************************************************

predicted       M-
reference       MK
                *

>AB000720.1.1	4	960
acaATGGCACATGAAATATTGATTGCTGAAACAGAGGCATTTCTAAAAAATGTTGCTCCT
GAGACCAGGACAGCAATAATTTCAGCAATAACAGGAGGGAAATCAGCCTGCAAATCAGCA
GCTAAACTGATTAAGAATGAACATCTTCCCCTAATGTCTGGAGAAGCCACCACAATGCAC
ATCGTTATAAGGTGCTTATATCCTGAAATAAAACCATGGAAAAAGGCAAGCGACATGCTG
AATAAAGCAACTTCTAGTTTGAAAAAATCAGAAGGAAGAGACATCAGAAAGCAAATGAAA
GCAGCTGGAGACTTCTTAGGAGTGGAGTCAATGATGAAAATGAGGGCCTTTAGAGATGAC
CAAATAATGGAAATGGTTGAAGAAGTATATGATCACCCAGACGACTACACACCAGACATC
CGAATAGGAACAATCACAGCTTGGTTGAGATGCAAAAACAAGAAAAGTGAAAGATACAGG
AGTAATGTCTCAGAAAGTGGAAGAACAGCTTTAAAGATTCATGAAGTAAGAAAAGCCAGC
ACAGCAATGAACGAAATTGCTGGTATTACTGGCCTTGGAGAAGAAGCACTATCTCTCCAA
AGACAAACAGAAAGTTTGGCCATATTATGTAATCACACTTTTGGAAGTAATATAATGAGA
CCCCACTTGGAAAAAGCAATAAAAGGAGTTGAAGGCAGAGTTGGAGAGATGGGACGAATG
GCAATGaaatggttagttgttataatatatttctctataacaagtcaacctgcttctgct
tgcaatctaaaaacctgtctaaaactatttaacaatactgatgcagtaactgttcattgt
tttaatgaaaaccaaggatacatgctaacattagcctctttaggactagggataattact
atgttgtatttattagtaaaaatcataattgaacttgtcaatggttttgtgctcggcagA
tgggagagatggtgtggagatataaagaccacaattatgcctgaaattgactcgatggaa
aaagatattgccctctctagggagagacttgacctgggagaggatgcccctgacgaaacc
gacaactcaccaattcctttttccaatgatggtatttttgaaatttaattaccttg

Length = 242

Score =   565 bits (1228), Expect = e-166
Identities = 241/242 (99%), Positives = 242/242 (100%)
Frame = +1

Query: 4   MAHEILIAETEAFLKNVAPETRTAIISAITGGKSACKSAAKLIKNEHLPLMSGEATTMHI 183
           MAHEILIAETEAFLKNVAPETRTAIISAITGGKSACKSAAKLIKNEHLPLMSGEATTMHI
Sbjct: 1   MAHEILIAETEAFLKNVAPETRTAIISAITGGKSACKSAAKLIKNEHLPLMSGEATTMHI 60

Query: 184 VIRCLYPEIKPWKKASDMLNKATSSLKKSEGRDIRKQMKAAGDFLGVESMMKMRAFRDDQ 363
           V+RCLYPEIKPWKKASDMLNKATSSLKKSEGRDIRKQMKAAGDFLGVESMMKMRAFRDDQ
Sbjct: 61  VMRCLYPEIKPWKKASDMLNKATSSLKKSEGRDIRKQMKAAGDFLGVESMMKMRAFRDDQ 120

Query: 364 IMEMVEEVYDHPDDYTPDIRIGTITAWLRCKNKKSERYRSNVSESGRTALKIHEVRKAST 543
           IMEMVEEVYDHPDDYTPDIRIGTITAWLRCKNKKSERYRSNVSESGRTALKIHEVRKAST
Sbjct: 121 IMEMVEEVYDHPDDYTPDIRIGTITAWLRCKNKKSERYRSNVSESGRTALKIHEVRKAST 180

Query: 544 AMNEIAGITGLGEEALSLQRQTESLAILCNHTFGSNIMRPHLEKAIKGVEGRVGEMGRMA 723
           AMNEIAGITGLGEEALSLQRQTESLAILCNHTFGSNIMRPHLEKAIKGVEGRVGEMGRMA
Sbjct: 181 AMNEIAGITGLGEEALSLQRQTESLAILCNHTFGSNIMRPHLEKAIKGVEGRVGEMGRMA 240

Query: 724 MK 729
           MK
Sbjct: 241 MK 242


========================================================================================================================

gene_id            %id    %sim   %cov   %t5   %gap  %t3   start..stop      pep sz ref sz ref id            definition
AB000727.1.1       100.0  100.0  99.6   0.0   0.0   0.4   5..727           241    242    Seg6prot1A        CM1 | CM1 protein
                                                          961..961                                         
                    missing exon 2

CLUSTAL 2.1 multiple sequence alignment


predicted       MAHEILIAETEAFLKNVAPETRTAIISAITGGKSACKSAAKLIKNEHLPLMSGEATTMHI
reference       MAHEILIAETEAFLKNVAPETRTAIISAITGGKSACKSAAKLIKNEHLPLMSGEATTMHI
                ************************************************************

predicted       VMRCLYPEIKPWKKASDMLNKATSSLKKSEGRDIRKQMKAAGDFLGVESMMKMRAFRDDQ
reference       VMRCLYPEIKPWKKASDMLNKATSSLKKSEGRDIRKQMKAAGDFLGVESMMKMRAFRDDQ
                ************************************************************

predicted       IMEMVEEVYDHPDDYTPDIRIGTITAWLRCKNKKSERYRSNVSESGRTALKIHEVRKAST
reference       IMEMVEEVYDHPDDYTPDIRIGTITAWLRCKNKKSERYRSNVSESGRTALKIHEVRKAST
                ************************************************************

predicted       AMNEIAGITGLGEEALSLQRQTESLAILCNHTFGSNIMRPHLEKAIKGVEGRVGEMGRMA
reference       AMNEIAGITGLGEEALSLQRQTESLAILCNHTFGSNIMRPHLEKAIKGVEGRVGEMGRMA
                ************************************************************

predicted       M-
reference       MK
                *

>AB000727.1.1	5	961
aacaATGGCACATGAAATATTAATTGCCGAAACAGAGGCATTTCTAAAAAATGTTGCTCC
TGAGACCAGGACAGCAATAATTTCAGCAATAACAGGTGGAAAATCAGCCTGCAAATCAGC
AGCTAAACTGATTAAGAATGAACATCTTCCCTTAATGTCTGGAGAAGCCACCACAATGCA
CATTGTTATGAGGTGCTTATATCCTGAAATAAAACCATGGAAAAAGGCAAGCGACATGCT
GAATAAAGCAACTTCTAGTTTGAAAAAATCAGAAGGAAGAGACATCAGAAAGCAAATGAA
AGCAGCTGGAGACTTTTTGGGAGTGGAGTCAATGATGAAAATGAGGGCCTTCAGAGATGA
CCAAATAATGGAAATGGTTGAAGAAGTATATGATCATCCAGACGACTACACACCAGACAT
CCGAATAGGAACAATCACAGCTTGGTTGAGATGCAAAAACAAGAAAAGTGAAAGATACAG
GAGCAATGTCTCAGAAAGTGGAAGAACAGCTTTAAAAATTCATGAAGTAAGAAAAGCCAG
CACAGCAATGAACGAAATTGCTGGTATTACTGGCCTTGGAGAAGAAGCACTATCTCTCCA
AAGACAAACAGAAAGTTTGGCCATATTATGCAATCACACTTTTGGAAGTAATATAATGAG
ACCCCACTTGGAAAAAGCAATAAAAGGAGTTGAAGGCAGAGTTGGAGAGATGGGACGAAT
GGCAATGaaatggttagttgttataatatatttctctataacaagtcaacctgcttctgc
ttgcaatctaaagacctgtctaaacctatttaacaatactgatgcagtaactgttcattg
ttttaatgaaaaccaaggatacatgctaacattagcctctttgggattagggataattac
tatgttgtatttattagtaaaaatcataattgaacttgtcaatggttttgtgctcggcag
Atgggagagatggtgtggagatataaagaccacaattatgcctgaaattgactcgatgga
aaaagatattgccctctctagggagagacttgacctgggagaggatgcccctgacgaaac
cgacaactcaccaattcctttttccaatgatggtatttttgaaatttaattaccttg

Length = 242

Score =   567 bits (1232), Expect = e-166
Identities = 242/242 (100%), Positives = 242/242 (100%)
Frame = +2

Query: 5   MAHEILIAETEAFLKNVAPETRTAIISAITGGKSACKSAAKLIKNEHLPLMSGEATTMHI 184
           MAHEILIAETEAFLKNVAPETRTAIISAITGGKSACKSAAKLIKNEHLPLMSGEATTMHI
Sbjct: 1   MAHEILIAETEAFLKNVAPETRTAIISAITGGKSACKSAAKLIKNEHLPLMSGEATTMHI 60

Query: 185 VMRCLYPEIKPWKKASDMLNKATSSLKKSEGRDIRKQMKAAGDFLGVESMMKMRAFRDDQ 364
           VMRCLYPEIKPWKKASDMLNKATSSLKKSEGRDIRKQMKAAGDFLGVESMMKMRAFRDDQ
Sbjct: 61  VMRCLYPEIKPWKKASDMLNKATSSLKKSEGRDIRKQMKAAGDFLGVESMMKMRAFRDDQ 120

Query: 365 IMEMVEEVYDHPDDYTPDIRIGTITAWLRCKNKKSERYRSNVSESGRTALKIHEVRKAST 544
           IMEMVEEVYDHPDDYTPDIRIGTITAWLRCKNKKSERYRSNVSESGRTALKIHEVRKAST
Sbjct: 121 IMEMVEEVYDHPDDYTPDIRIGTITAWLRCKNKKSERYRSNVSESGRTALKIHEVRKAST 180

Query: 545 AMNEIAGITGLGEEALSLQRQTESLAILCNHTFGSNIMRPHLEKAIKGVEGRVGEMGRMA 724
           AMNEIAGITGLGEEALSLQRQTESLAILCNHTFGSNIMRPHLEKAIKGVEGRVGEMGRMA
Sbjct: 181 AMNEIAGITGLGEEALSLQRQTESLAILCNHTFGSNIMRPHLEKAIKGVEGRVGEMGRMA 240

Query: 725 MK 730
           MK
Sbjct: 241 MK 242


========================================================================================================================

gene_id            %id    %sim   %cov   %t5   %gap  %t3   start..stop      pep sz ref sz ref id            definition
D16259.1.1         100.0  100.0  99.6   0.0   0.0   0.4   14..736          241    242    Seg6prot1A        CM1 | CM1 protein
                                                          970..970                                         
                    missing exon 2

CLUSTAL 2.1 multiple sequence alignment


predicted       MAHEILIAETEAFLKNVAPETRTAIISAITGGKSACKSAAKLIKNEHLPLMSGEATTMHI
reference       MAHEILIAETEAFLKNVAPETRTAIISAITGGKSACKSAAKLIKNEHLPLMSGEATTMHI
                ************************************************************

predicted       VMRCLYPEIKPWKKASDMLNKATSSLKKSEGRDIRKQMKAAGDFLGVESMMKMRAFRDDQ
reference       VMRCLYPEIKPWKKASDMLNKATSSLKKSEGRDIRKQMKAAGDFLGVESMMKMRAFRDDQ
                ************************************************************

predicted       IMEMVEEVYDHPDDYTPDIRIGTITAWLRCKNKKSERYRSNVSESGRTALKIHEVRKAST
reference       IMEMVEEVYDHPDDYTPDIRIGTITAWLRCKNKKSERYRSNVSESGRTALKIHEVRKAST
                ************************************************************

predicted       AMNEIAGITGLGEEALSLQRQTESLAILCNHTFGSNIMRPHLEKAIKGVEGRVGEMGRMA
reference       AMNEIAGITGLGEEALSLQRQTESLAILCNHTFGSNIMRPHLEKAIKGVEGRVGEMGRMA
                ************************************************************

predicted       M-
reference       MK
                *

>D16259.1.1	14	970
ggatttcaaaacaATGGCACATGAAATACTGATTGCTGAAACAGAAGCATTTCTAAAAAA
TGTTGCTCCTGAGACCAGGACAGCAATAATTTCAGCAATAACAGGAGGAAAATCAGCCTG
CAAATCAGCAGCTAAACTTATTAAGAATGAACATCTTCCCTTAATGTCTGGAGAGGCCAC
CACAATGCACATTGTTATGAGGTGCTTATATCCTGAAATAAAACCATGGAAAAAGGCAAG
CGACATGCTGAATAAAGCAACTTCTAGTTTGAAAAAATCAGAAGGAAGAGACATCAGAAA
GCAAATGAAAGCAGCTGGAGACTTCTTGGGAGTGGAGTCAATGATGAAAATGAGGGCCTT
CAGAGATGACCAAATAATGGAAATGGTTGAAGAAGTATATGATCACCCAGACGACTACAC
ACCAGACATCCGAATAGGAACAATTACAGCTTGGTTGAGATGCAAAAACAAGAAAAGTGA
AAGATACAGGAGTAATGTCTCAGAAAGTGGAAGAACAGCTTTAAAAATTCATGAAGTAAG
AAAAGCCAGCACAGCAATGAACGAGATTGCTGGTATTACTGGCCTTGGAGAAGAAGCACT
ATCTCTTCAAAGACAAACAGAAAGTTTGGCCATATTATGTAATCACACTTTTGGAAGTAA
TATAATGAGACCCCACTTGGAAAAGGCAATAAAAGGAGTTGAAGGCAGAGTTGGAGAGAT
GGGACGAATGGCAATGaaatggtttgttgttataatatatttctctataacaagtcaacc
tgcttctgcttgcaatttaaagacctgtctaaaactatttaacaatactgatgcggtaac
tgttcattgttttaatgaaaaccaaggatacatgctaacattagcctctttgggattagg
gataattactatgttgtatttattagtaaaaatcataattgaacttgtcaatggttttgt
actcggcagAtgggagagatggtgcggagatataaagaccacaattatgcctgaaattga
ctcgatggaaaaagatattgccctctctagggagagacttgacctgggagaggatgcccc
tgacgaaaccgacaactcaccaattcctttttccaatgatggtatttttgaaatttaatt
accttgaaaaaat

Length = 242

Score =   567 bits (1232), Expect = e-166
Identities = 242/242 (100%), Positives = 242/242 (100%)
Frame = +2

Query: 14  MAHEILIAETEAFLKNVAPETRTAIISAITGGKSACKSAAKLIKNEHLPLMSGEATTMHI 193
           MAHEILIAETEAFLKNVAPETRTAIISAITGGKSACKSAAKLIKNEHLPLMSGEATTMHI
Sbjct: 1   MAHEILIAETEAFLKNVAPETRTAIISAITGGKSACKSAAKLIKNEHLPLMSGEATTMHI 60

Query: 194 VMRCLYPEIKPWKKASDMLNKATSSLKKSEGRDIRKQMKAAGDFLGVESMMKMRAFRDDQ 373
           VMRCLYPEIKPWKKASDMLNKATSSLKKSEGRDIRKQMKAAGDFLGVESMMKMRAFRDDQ
Sbjct: 61  VMRCLYPEIKPWKKASDMLNKATSSLKKSEGRDIRKQMKAAGDFLGVESMMKMRAFRDDQ 120

Query: 374 IMEMVEEVYDHPDDYTPDIRIGTITAWLRCKNKKSERYRSNVSESGRTALKIHEVRKAST 553
           IMEMVEEVYDHPDDYTPDIRIGTITAWLRCKNKKSERYRSNVSESGRTALKIHEVRKAST
Sbjct: 121 IMEMVEEVYDHPDDYTPDIRIGTITAWLRCKNKKSERYRSNVSESGRTALKIHEVRKAST 180

Query: 554 AMNEIAGITGLGEEALSLQRQTESLAILCNHTFGSNIMRPHLEKAIKGVEGRVGEMGRMA 733
           AMNEIAGITGLGEEALSLQRQTESLAILCNHTFGSNIMRPHLEKAIKGVEGRVGEMGRMA
Sbjct: 181 AMNEIAGITGLGEEALSLQRQTESLAILCNHTFGSNIMRPHLEKAIKGVEGRVGEMGRMA 240

Query: 734 MK 739
           MK
Sbjct: 241 MK 242


