========================================================================================================================

gene_id            %id    %sim   %cov   %t5   %gap  %t3   start..stop      pep sz ref sz ref id            definition
37.17              85.7   98.6   33.2   66.8  0.0   0.0   <26221..26433    70     211    NP_040866.1       L4-3 | putative splicing factor, C-terminal
                    missing exon 1

CLUSTAL 2.1 multiple sequence alignment


predicted       ------------------------------------------------------------
reference       MPPKGNKHPIAQRQSQQKLQKQWDEEETWDDSQAEEVSDEEAEEQMESWDSLDEEDLEDV
                                                                            

predicted       ------------------------------------------------------------
reference       EEETIASDKAPSFKKPVRSQPPKTIPPLPPQPCSLKASRRWDTVSIAGSPTAPAAPTKRL
                                                                            

predicted       ---------------------TRELRNRIFPTLYAIFQQSRGQEHELKIKNRSLRSLTRS
reference       EKTPRVRKTSSAIATRQDSPATQELRKRIFPTLYAIFQQSRGQQLELKVKNRSLRSLTRS
                                     *:***:****************: ***:***********

predicted       CLYHKSEDQLQRTLEDAEALFNKYCALTLKE
reference       CLYHRSEDQLQRTLEDAEALFNKYCSVSLKD
                ****:********************:::**:

>37.19	26221	26433
gcccctactatagccagcaaatcccggcagtctcgacagaaaaagacagcggcggcgacc
tccaacagaaaaccagcagcggcagttaaaaaatacacaacaagtgcagcaacaggagga
ttaaagattacagccaacgagccagcgcaaACCCGAGAGCTAAGAAATCGGATCTTTCCA
ACCCTGTATGCCATCTTCCAGCAGAGTCGGGGCCAAGAGCATGAACTGAAAATAAAAAAC
CGATCTTTGCGTTCGCTCACCAGAAGTTGTTTGTATCACAAGAGCGAAGATCAACTTCAG
CGCACTCTTGAGGACGCCGAGGCTCTCTTCAACAAGTACTGCGCGCTGACTCTTAAAGAG
TAGgcagcgaccgcgcttattcaaaaaaggcgggaattacatcatcctcgtcatgagtaa
agaaattcccacgccttacatgtggagttatcagccccaaatgggattggcggcaggcgc
ctcccaggactactccacccgcatgaattggct

Length = 211

Score =   152 bits (326), Expect = 9e-42
Identities = 65/101 (64%), Positives = 77/101 (76%)
Frame = +1

Query: 26128 TSNRKPAAAVKKYTTSAATGGLKITANEPAQTRELRNRIFPTLYAIFQQSRGQEHELKIK 26307
             T+   P   ++K      T     T  +   T+ELR RIFPTLYAIFQQSRGQ+ ELK+K
Sbjct: 111   TAPAAPTKRLEKTPRVRKTSSAIATRQDSPATQELRKRIFPTLYAIFQQSRGQQLELKVK 170

Query: 26308 NRSLRSLTRSCLYHKSEDQLQRTLEDAEALFNKYCALTLKE 26430
             NRSLRSLTRSCLYH+SEDQLQRTLEDAEALFNKYC+++LK+
Sbjct: 171   NRSLRSLTRSCLYHRSEDQLQRTLEDAEALFNKYCSVSLKD 211


========================================================================================================================

gene_id            %id    %sim   %cov   %t5   %gap  %t3   start..stop      pep sz ref sz ref id            definition
47.18              41.7   48.7   100.0  0.0   0.0   0.0   26234..26365     114    211    NP_040866.1       L4-3 | splicing factor
                                                          26910..27122                                     
                    invalid splicing for intron  at 26366..26909

CLUSTAL 2.1 multiple sequence alignment


predicted       MAPK-KKLQLPPPPPT-------DEEEYWD-SQAEEVLDEE-EEMMEDWDSLDE------
reference       MPPKGNKHPIAQRQSQQKLQKQWDEEETWDDSQAEEVSDEEAEEQMESWDSLDEEDLEDV
                *.** :*  :.   .        **** ** ****** *** ** **.******      

predicted       ------------------------------------------------------------
reference       EEETIASDKAPSFKKPVRSQPPKTIPPLPPQPCSLKASRRWDTVSIAGSPTAPAAPTKRL
                                                                            

predicted       ---------------------TRELRNRIFPTLYAIFQQSRGQEQELKIKNRSLRSLTRS
reference       EKTPRVRKTSSAIATRQDSPATQELRKRIFPTLYAIFQQSRGQQLELKVKNRSLRSLTRS
                                     *:***:****************: ***:***********

predicted       CLYHKSEDQLRRTLEDAEALFSKYCALTLKD
reference       CLYHRSEDQLQRTLEDAEALFNKYCSVSLKD
                ****:*****:**********.***:::***

>47.19	26234	27122
gccaattgcaagccatcaacaaagcccgccaagagtttctgctacgaaagggacgggggg
tttacctggacccccagtccggcgaggagctcaacccaatccccccgccgccgcagccct
atcagcagccgcgggcccttgcttcccaggATGGCACCCAAAAAGAAGCTGCAGCTGCCG
CCGCCGCCACCCACGGACGAGGAGGAATACTGGGACAGTCAGGCAGAGGAGGTTTTGGAC
GAGGAGGAGGAGATGATGGAAGACTGGGACAGCCTAGACGAAgcttccgaggccgaagag
gtgtcagacgaaacaccgtcaccctcggtcgcattcccctcgccggcgccccagaaattg
gcaaccgttcccagcatcgctacaacctccgctcctcaggcgccgccggcactgcctgtt
cgccgacccaaccgtagatgggacaccactggaaccagggccggtaagtctaagcagccg
ccgccgttagcccaagagcaacaacagcgccaaggctaccgctcgtggcgcgggcacaag
aacgccatagttgcttgcttgcaagactgtgggggcaacatctccttcgcccgccgcttt
cttctctaccatcacggcgtggccttcccccgtaacatcctgcattactaccgtcatctc
tacagcccctactgcaccggcggcagcggcagcggcagcaacagcagcgatcacacagaa
gcaaaggcgaccggatagcaagactctgacaaagcccaagaaatccacagcggcggcagc
agcaggaggaggagcgctgcgtctggcgcccaacgaacccgtatcgACCCGCGAGCTTAG
AAACAGGATTTTTCCCACTCTGTATGCTATATTTCAACAAAGCAGGGGCCAAGAACAAGA
GCTGAAAATAAAAAACAGGTCTCTGCGCTCCCTCACCCGCAGCTGCCTGTATCACAAAAG
CGAAGATCAGCTTCGGCGCACGCTGGAAGACGCGGAGGCTCTCTTCAGCAAATACTGCGC
GCTGACTCTTAAGGACTAGtttcgcgccctttctcaaatttaagcgcgaaaactacgtca
tctccagcggccacacccggcgccagcacctgtcgtcagcgccattatgagcaaggaaat
tcccacgccctacatgtggagttaccagccacaaatgggacttgcggct

Length = 211

Score =  34.8 bits (70), Expect = 5e-06
Identities = 17/40 (42%), Positives = 24/40 (60%)
Frame = +2

Query: 26279 DEEEYWDSQAEEVLDEEEEMMEDWDSLDEASEAEEVSDET 26398
             +EE + DSQAEEV DEE E   +     +  + E+V +ET
Sbjct: 25    EEETWDDSQAEEVSDEEAEEQMESWDSLDEEDLEDVEEET 64

Score =  20.3 bits (38), Expect(4) = 1e-44
Identities = 8/13 (61%), Positives = 10/13 (76%)
Frame = +3

Query: 26730 TTVISTAPTAPAA 26768
             T  I+ +PTAPAA
Sbjct: 103   TVSIAGSPTAPAA 115

Score =   146 bits (314), Expect(4) = 1e-44
Identities = 59/71 (83%), Positives = 69/71 (97%)
Frame = +3

Query: 26907 STRELRNRIFPTLYAIFQQSRGQEQELKIKNRSLRSLTRSCLYHKSEDQLRRTLEDAEAL 27086
             +T+ELR RIFPTLYAIFQQSRGQ+ ELK+KNRSLRSLTRSCLYH+SEDQL+RTLEDAEAL
Sbjct: 141   ATQELRKRIFPTLYAIFQQSRGQQLELKVKNRSLRSLTRSCLYHRSEDQLQRTLEDAEAL 200

Query: 27087 FSKYCALTLKD 27119
             F+KYC+++LKD
Sbjct: 201   FNKYCSVSLKD 211


========================================================================================================================

gene_id            %id    %sim   %cov   %t5   %gap  %t3   start..stop      pep sz ref sz ref id            definition
64.7               73.4   89.7   97.6   2.4   0.0   0.0   11769..13445     558    576    NP_040856.1       L1 | IIIa capsid protein
                    could not find valid start codon

CLUSTAL 2.1 multiple sequence alignment


predicted       --------------DPAIRAALQSQPSGLA-SDDWEAAMQRIMALTTRNPESFRQQPQAN
reference       MLRSTAVADGSQQVNPAMLAALQSQPSGVTPSDDWAAAMDRILALTTRNPEAFRQQPQAN
                              :**: *********:: **** ***:**:********:********

predicted       RLSAILEAVVPSRTNPTHEKVLAIVNALAENKAIRPDEAGLVYNALLERVGRYNSTNVQS
reference       RFSAILEAVVPSRTNPTHEKVLAIVNALVESKAIRKDEAGLIYNALLERVARYNSTNVQA
                *:**************************.*.**** *****:********.********:

predicted       NLDRLVTDVREAVAQRERFKNE-GLGSLVALNAFLATQPANVPRGQDDYTNFISALRLMV
reference       NLDRLTTDVREAVAQRERFMHDVNLGSQVALNAFLSTLPANVPRGQEDYVSFISALRLLV
                *****.************* :: .*** *******:* ********:**..*******:*

predicted       TEVPQSEVYQSGPDYFFQTSRQGLQTVNLSQAFKNLRGLWGVQAPVGDRSTVSSLLTPNS
reference       AEVPQSEVYQSGPDYFFQTSRQGLQTVNLTQAFKNLQGMWGVRAPVGDRATISSLLTPNT
                :****************************:******:*:***:******:*:*******:

predicted       RLLLLLIAPFTDSGSVNRNSYLGHLLTLYREAIGQAQVDEQTFQEITSVSRALGQNDTDS
reference       RLLLLLIAPFTNSSTISRDSYLGHLITLYQEAIGQTQVDEQTFQEITSVSRALGQQDTSS
                ***********:*.::.*:******:***:*****:*******************:**.*

predicted       LRATLNFLLTNRQQKIPAQYALSAEEERILRYVQQSVGLFLMQEGATPSAALDMTARNME
reference       LEATLNFLLTNRRQKIPSQFTLNSEEERILRYVQQSVSLYLMREGATASSALDMTARNME
                *.**********:****:*::*.:*************.*:**:****.*:**********

predicted       PSMYAANRPFINKLMDYLHRAASMNSDYFTNAILNPHWLPPPGFYTGEYDMPDPNDGFLW
reference       PSLYSSNRPFINRLMDYLHRAAAMNSEYFTNAILNPHWMPPSGFYTGEFDVPEGDDGFLW
                **:*::******:*********:***:***********:**.******:*:*: :*****

predicted       DDVDSAVFSPTLQKRQE-AVRTPAS--EGAV-GRSPFPSLGSLHSLPGSVNSGRVSRPRL
reference       DDVSESIFEPMRSRKKEGGDELPLSLVEAASRGQTPVPSLPSLTSS----SSGRVFRPRL
                ***..::*.*  .:::* . . * *  *.*  *::*.*** ** *     .**** ****

predicted       LGEDEYLNDSLLQPPRVKNAMVNNGIESLVDKLNRWKTYAQDHREP-APAPRRQRHDRQR
reference       PGELDYLSDPLLRPARKKN-FPNNGVESLVDKMNRWKTYAQEQREERQPRPLTGTFSRWR
                 ** :**.*.**:*.* ** : ***:******:********::**   * *    ..* *

predicted       GLVWDDEDSADDSSVLDLGGSGGAN-PFAHLQPR--LGRRMF
reference       RREEDAYDSADDSSVLDLGGTGAASDPFAHLRPQGQLG-RLY
                    *  *************:*.*. *****:*:  ** *::

>64.9	11769	13445
gggcggacctgcattggcagccgagccgacgcgccttggaggccgcctacggtccagagg
acttggatgaggaagaggaagaggaggaggatgcacccgttgcggggtactgacgcctcc
gtgatgtgtttttagatgcagcaagccccgGACCCCGCCATAAGGGCGGCGCTGCAAAGC
CAGCCGTCCGGTCTAGCATCGGACGACTGGGAGGCCGCGATGCAACGCATCATGGCCCTG
ACGACCCGCAACCCCGAGTCCTTTAGACAACAGCCGCAGGCCAACAGACTCTCGGCCATT
CTGGAGGCGGTGGTTCCTTCTCGGACCAACCCCACGCACGAGAAGGTGCTGGCGATCGTG
AACGCGCTGGCGGAGAACAAGGCCATCCGTCCCGACGAGGCCGGGCTAGTGTACAACGCC
CTGCTGGAGCGCGTGGGCCGCTACAACAGCACAAACGTGCAGTCCAACCTGGACCGGCTG
GTGACGGACGTGCGCGAGGCCGTGGCGCAGCGCGAGCGGTTCAAGAACGAGGGCCTGGGT
TCGCTGGTGGCGCTGAACGCCTTCCTGGCGACGCAGCCGGCGAACGTGCCGCGCGGGCAG
GATGATTATACCAACTTTATAAGCGCGCTGCGGCTGATGGTGACCGAGGTGCCCCAGAGC
GAGGTGTACCAGTCGGGCCCGGACTACTTTTTCCAGACGAGCAGACAGGGCCTGCAGACG
GTGAACCTGAGTCAGGCTTTCAAGAACCTGCGCGGGCTGTGGGGCGTGCAGGCGCCCGTG
GGCGACCGGTCGACGGTGAGCAGCTTGCTGACGCCCAACTCGCGGCTGCTGCTGCTGCTG
ATCGCGCCCTTCACCGACAGTGGCAGCGTGAACCGCAACTCGTACCTGGGTCACCTGCTG
ACGCTGTACCGCGAGGCCATAGGCCAGGCGCAGGTGGATGAGCAGACCTTCCAGGAGATC
ACTAGCGTGAGCCGCGCGCTGGGTCAGAACGACACCGACAGTCTGAGGGCCACCCTGAAC
TTCTTGCTGACCAATAGACAGCAGAAGATCCCGGCGCAGTACGCGCTGTCGGCCGAGGAG
GAGCGCATCCTGAGATATGTGCAGCAGAGCGTAGGGCTGTTCCTGATGCAGGAGGGGGCC
ACCCCCAGCGCCGCGCTGGACATGACCGCGCGCAACATGGAACCTAGCATGTACGCCGCC
AACCGGCCGTTTATTAATAAGCTGATGGACTACCTGCACCGCGCGGCGTCCATGAACTCG
GACTACTTTACCAATGCCATCTTGAACCCGCACTGGCTCCCGCCGCCGGGGTTCTACACG
GGCGAGTACGACATGCCTGACCCCAACGACGGGTTTTTGTGGGACGACGTGGACAGCGCG
GTGTTCTCACCGACCTTGCAAAAGCGCCAGGAGGCGGTGCGCACGCCCGCGAGCGAGGGC
GCGGTGGGTCGGAGCCCCTTTCCTAGCTTAGGGAGTTTGCATAGCTTGCCGGGCTCGGTG
AACAGCGGCAGGGTGAGCCGGCCGCGCTTGCTGGGCGAGGACGAGTACCTGAACGACTCG
CTGCTGCAGCCGCCGCGGGTCAAGAACGCCATGGTCAATAACGGGATAGAGAGTCTGGTG
GACAAACTGAACCGCTGGAAAACCTACGCTCAGGACCATAGGGAACCTGCGCCCGCGCCG
CGGCGACAGCGTCACGACCGGCAGCGGGGCCTGGTGTGGGACGACGAGGACTCGGCCGAC
GATAGCAGCGTGTTGGACTTGGGCGGGAGCGGTGGGGCCAACCCGTTCGCGCATCTGCAG
CCCAGACTGGGGCGACGGATGTTTTGAatgcaaaataaaactcaccaaggccatagcgtg
cgttctcttccttgttagagatgaggcgcgcggtggtgtcttcctctcctcctccctcgt
acgagagcgtgatggcgcaggcgaccctggaggttccgtttgtgcctccgcggtata

Length = 576

Score =  31.8 bits (63), Expect(7) = 0.0
Identities = 15/26 (57%), Positives = 18/26 (69%)
Frame = +3

Query: 11760 QAPDPAIRAALQSQPSGLASDDWEAA 11837
             Q  +PA+ AALQSQPSG+   D  AA
Sbjct: 12    QQVNPAMLAALQSQPSGVTPSDDWAA 37

Score =   226 bits (487), Expect(7) = 0.0
Identities = 96/111 (86%), Positives = 103/111 (92%)
Frame = +3

Query: 11817 SDDWEAAMQRIMALTTRNPESFRQQPQANRLSAILEAVVPSRTNPTHEKVLAIVNALAEN 11996
             SDDW AAM RI+ALTTRNPE+FRQQPQANR SAILEAVVPSRTNPTHEKVLAIVNAL E+
Sbjct: 32    SDDWAAAMDRILALTTRNPEAFRQQPQANRFSAILEAVVPSRTNPTHEKVLAIVNALVES 91

Query: 11997 KAIRPDEAGLVYNALLERVGRYNSTNVQSNLDRLVTDVREAVAQRERFKNE 12149
             KAIR DEAGL+YNALLERV RYNSTNVQ+NLDRL TDVREAVAQRERF ++
Sbjct: 92    KAIRKDEAGLIYNALLERVARYNSTNVQANLDRLTTDVREAVAQRERFMHD 142

Score =   576 bits (1252), Expect(7) = 0.0
Identities = 231/293 (78%), Positives = 273/293 (93%)
Frame = +3

Query: 12153 LGSLVALNAFLATQPANVPRGQDDYTNFISALRLMVTEVPQSEVYQSGPDYFFQTSRQGL 12332
             LGS VALNAFL+T PANVPRGQ+DY +FISALRL+V EVPQSEVYQSGPDYFFQTSRQGL
Sbjct: 145   LGSQVALNAFLSTLPANVPRGQEDYVSFISALRLLVAEVPQSEVYQSGPDYFFQTSRQGL 204

Query: 12333 QTVNLSQAFKNLRGLWGVQAPVGDRSTVSSLLTPNSRLLLLLIAPFTDSGSVNRNSYLGH 12512
             QTVNL+QAFKNL+G+WGV+APVGDR+T+SSLLTPN+RLLLLLIAPFT+S +++R+SYLGH
Sbjct: 205   QTVNLTQAFKNLQGMWGVRAPVGDRATISSLLTPNTRLLLLLIAPFTNSSTISRDSYLGH 264

Query: 12513 LLTLYREAIGQAQVDEQTFQEITSVSRALGQNDTDSLRATLNFLLTNRQQKIPAQYALSA 12692
             L+TLY+EAIGQ QVDEQTFQEITSVSRALGQ DT SL ATLNFLLTNR+QKIP+Q+ L++
Sbjct: 265   LITLYQEAIGQTQVDEQTFQEITSVSRALGQQDTSSLEATLNFLLTNRRQKIPSQFTLNS 324

Query: 12693 EEERILRYVQQSVGLFLMQEGATPSAALDMTARNMEPSMYAANRPFINKLMDYLHRAASM 12872
             EEERILRYVQQSV L+LM+EGAT S+ALDMTARNMEPS+Y++NRPFIN+LMDYLHRAA+M
Sbjct: 325   EEERILRYVQQSVSLYLMREGATASSALDMTARNMEPSLYSSNRPFINRLMDYLHRAAAM 384

Query: 12873 NSDYFTNAILNPHWLPPPGFYTGEYDMPDPNDGFLWDDVDSAVFSPTLQKRQE 13031
             NS+YFTNAILNPHW+PP GFYTGE+D+P+ +DGFLWDDV  ++F P   +++E
Sbjct: 385   NSEYFTNAILNPHWMPPSGFYTGEFDVPEGDDGFLWDDVSESIFEPMRSRKKE 437

Score =  45.5 bits (93), Expect(7) = 0.0
Identities = 20/31 (64%), Positives = 24/31 (77%)
Frame = +3

Query: 13113 SVNSGRVSRPRLLGEDEYLNDSLLQPPRVKN 13205
             S +SGRV RPRL GE +YL+D LL+P R KN
Sbjct: 465   SSSSGRVFRPRLPGELDYLSDPLLRPARKKN 495

Score =  55.6 bits (115), Expect(7) = 0.0
Identities = 21/31 (67%), Positives = 24/31 (77%)
Frame = +3

Query: 13191 PRVKNAMVNNGIESLVDKLNRWKTYAQDHRE 13283
             P  K    NNG+ESLVDK+NRWKTYAQ+ RE
Sbjct: 490   PARKKNFPNNGVESLVDKMNRWKTYAQEQRE 520

Score =  42.8 bits (87), Expect(7) = 0.0
Identities = 21/44 (47%), Positives = 24/44 (54%)
Frame = +3

Query: 13269 QDHREPAPAPRRQRHDRQRGLVWDDEDSADDSSVLDLGGSGGAN 13400
             +   E  P P      R R    D  DSADDSSVLDLGG+G A+
Sbjct: 517   EQREERQPRPLTGTFSRWRRREEDAYDSADDSSVLDLGGTGAAS 560

Score =  23.1 bits (44), Expect(7) = 0.0
Identities = 7/15 (46%), Positives = 11/15 (73%)
Frame = +3

Query: 13380 GGSGGANPFAHLQPR 13424
             G    ++PFAHL+P+
Sbjct: 555   GTGAASDPFAHLRPQ 569


========================================================================================================================

gene_id            %id    %sim   %cov   %t5   %gap  %t3   start..stop      pep sz ref sz ref id            definition
gi_61602086.18     73.5   87.2   100.0  0.0   0.0   0.0   22456..24681     741    770    NP_040865.1       L4 | hexon-assembly protein
                    could not find valid start codon

CLUSTAL 2.1 multiple sequence alignment


predicted       VEQDPGYVTPPEDLEGPD----------RRDASERQENE----------KE------EAC
reference       MEEDLKLQPDSETLTTPNSEVGAVELVKHEEENEQVEQDPGYVTPPEDGKEPVAALSEPN
                :*:*    . .* *  *:          :.: .*: *::          **      *. 

predicted       YLL-EGDVLLKHFARQSTIVKEALQDRSEVPLDVAALSQAYEANLFSPRVPPKRQPNGTC
reference       YLGGEDDVLLKHIARQSTIVREALKECTQTPLTVEELSRAYEANLFSPRVPPKKQPNGTC
                **  *.******:*******:***:: ::.** *  **:**************:******

predicted       EPNPRLNFYPVFAVPEALATYHIFFKNQRIPLSCRANRTAADRNLRLKNGANIPDITSLE
reference       ETNPRLNFYPVFAVPEALATYHIFFKNQRIPLSCRANRTRGDGLLHLKAGAHIPEIVSLE
                *.************************************* .*  *:** **:**:*.***

predicted       EVPKIFEGLGRDEKRAANALQKEQKESQNVLVELEGDNARLAVLKRCIEVSHFAYPALNL
reference       EVPKIFEGLGKDEKRAANALQKNETENQNVLVELEGDNARLAVLKRTIEVSHFAYPALNL
                **********:***********::.*.******************* *************

predicted       PPKVMKSVMDQLLIKRAEPLDPDHPEAENSEDGKPVVSDEELERWLETRDPQQLQERRKM
reference       PPKVMRSVMDQVLIKRAEPIDPQQPDL-NSEDGQPVVSDDELARWLGTQDPSELQERRKM
                *****:*****:*******:**::*:  *****:*****:** *** *:**.:*******

predicted       MMAAVLVTVELECLQRFFSDVETLRKIGESLHYTFRQGYVRQACKISNVELSNLVSYMGI
reference       MMAAVLVTVELECLQRFFANPQTLRKVEESLHYAFRHGYVRQACKISNVELSNLISYMGI
                ******************:: :****: *****:**:*****************:*****

predicted       LHENRLGQSVLHCTLQGEARRDYVRDCIYLFLTLTWQTAMGVWQQCLEERNLKELDKLLC
reference       LHENRLGQNVLHCTLQGEARRDYVRDCIYLFLILTWQTAMGVWQQCLEEQNLQELNKLLV
                ********.*********************** ****************:**:**:*** 

predicted       RQRRALWSGFSERTVASALADIIFPERLMKTLQNGLPDFISQSILQNFRSFVLERSGILP
reference       RARRELWTSFDERTVARQLANLIFPERLMQTLQNGLPDFVSQSILQNFRSFVLERSGILP
                * ** **:.*.*****  **::*******:*********:********************

predicted       AMSCALPSDFVPLSYRECPPPLWSHCYLFQLANFLAYHSDLMEDVSGEGLLECHCRCNLC
reference       AMSCALPSDFVPLCYRECPPPLWSHCYLLRLANYLAHHSDLMEDSSGDGLLECHCRCNLC
                *************.**************::***:**:******* **:************

predicted       TPHRSLACNTELLSETQVIGTFEIQGPQQQEGASGLKLTPALWTSAYLRKFVAEDYHAHK
reference       TPHRSLVCNTELLSETQVIGTFEIQGPEQQEGASSLKLTPALWTSAYLRKFIPEDYHAHQ
                ******.********************:******.****************:.******:

predicted       IQFYEDQSRPPKAPLTACVITQSKILAQLQSINQARRDFLLKKGRGVYLDPQTGEELNPS
reference       IKFYEDQSRPPKVPLTACVITQSQILAQLQAIQQARQEFLLKKGHGVYLDPQTGEELNTP
                *:**********.**********:******:*:***::******:*************..

predicted       TLSVEAAP--PRHAAQGNRQAADRSAESEEARAAPAAGGGRGRDVG-QPGRGGVR--GRG
reference       SLSAAASCRSQKHATQG-KQASHR-ATAIPAETTKAVG--RGGDVGRQPGRGSFRRGGGG
                :**. *:    :**:** :**:.* * :  *.:: *.*  ** *** *****..*  * *

predicted       GDGKLGQPRRGGGRAFRGRGDR-RKTTCIQRAFSEPTAEA-PAPDAPGRLTQSQP
reference       ADGELGQPRRGGPRGRGGRNHRQRQGTIFQKTRSEPTSENYPAPATATMFTESQP
                .**:******** *.  **..* *: * :*:: ****:*  *** :.  :*:***

>gi_61602086.18	22456	24681
gctcggggctcatctcccgcaagtagggggtaatggagctgcctgcttggttctgacggt
tggccattgtatcctaggcagaaagacatggagcttatgcgcgaggaaactttaaccgcc
ccgtcccccgtcagcgacgaagatgtcatcGTCGAACAGGACCCGGGCTACGTTACGCCG
CCCGAGGATCTGGAGGGGCCTGACCGGCGCGACGCTAGTGAGCGGCAGGAAAATGAGAAA
GAGGAGGCCTGCTACCTCCTGGAAGGCGACGTTTTGCTAAAGCATTTCGCCAGGCAGAGC
ACCATAGTTAAGGAGGCCTTGCAAGACCGCTCCGAGGTGCCCTTGGACGTCGCCGCGCTC
TCCCAGGCCTACGAGGCGAACCTTTTCTCGCCTCGAGTGCCTCCGAAGAGACAGCCCAAC
GGCACCTGCGAGCCCAACCCGCGACTCAACTTCTACCCCGTGTTCGCCGTACCAGAGGCG
CTGGCCACCTATCACATTTTTTTCAAAAACCAACGCATCCCCCTATCGTGCCGGGCCAAC
CGCACCGCGGCCGATAGGAATCTCAGGCTTAAAAACGGAGCCAACATACCTGATATCACG
TCGCTGGAGGAAGTGCCCAAGATTTTCGAGGGTCTGGGTCGAGATGAGAAGCGGGCGGCG
AACGCTCTGCAGAAAGAACAGAAAGAGAGTCAGAACGTGCTGGTGGAGCTGGAGGGGGAC
AACGCGCGTCTGGCCGTCCTCAAACGCTGCATAGAAGTCTCCCACTTCGCCTACCCCGCC
CTCAACTTGCCACCCAAAGTTATGAAATCGGTCATGGATCAGCTGCTCATCAAGAGAGCT
GAGCCCCTGGATCCCGACCACCCCGAGGCGGAAAACTCAGAGGACGGAAAGCCCGTCGTC
AGCGACGAGGAGCTCGAGCGGTGGCTGGAAACCAGGGACCCCCAACAGTTGCAAGAGAGG
CGCAAGATGATGATGGCGGCCGTGCTGGTCACCGTGGAGCTGGAATGCCTGCAACGGTTT
TTCAGCGACGTGGAGACGCTACGCAAAATCGGGGAATCCCTGCACTACACCTTCCGCCAG
GGCTACGTCCGCCAGGCCTGCAAGATCTCCAACGTGGAGCTCAGCAACCTGGTCTCCTAC
ATGGGCATCCTCCACGAGAACCGGCTGGGGCAGAGCGTGCTGCACTGCACCTTGCAAGGC
GAGGCGCGGCGGGACTACGTGCGAGACTGCATCTACCTCTTCCTCACCCTCACCTGGCAG
ACCGCCATGGGCGTCTGGCAGCAGTGCTTGGAAGAGAGAAACCTCAAAGAGCTAGACAAA
CTCCTCTGCCGCCAGCGGCGCGCCCTGTGGTCCGGTTTCAGCGAGCGCACGGTCGCCAGC
GCTCTGGCGGACATCATCTTCCCGGAGCGCCTGATGAAAACCTTGCAAAACGGCCTGCCG
GATTTCATCAGTCAAAGCATTTTGCAAAACTTCCGCTCTTTTGTCCTGGAACGCTCCGGG
ATCTTGCCCGCCATGAGCTGCGCGCTACCTTCTGACTTTGTCCCCCTCTCCTACCGCGAG
TGCCCTCCCCCACTGTGGAGCCACTGCTACCTCTTCCAACTGGCCAACTTTCTGGCCTAC
CACTCCGACCTCATGGAAGACGTAAGCGGAGAGGGTTTACTGGAGTGCCACTGCCGCTGC
AACCTGTGCACCCCCCACAGATCGCTGGCCTGCAACACCGAGCTACTCAGCGAAACCCAG
GTCATAGGTACCTTCGAGATCCAGGGGCCCCAGCAGCAAGAGGGTGCTTCCGGCTTGAAG
CTCACTCCGGCGCTGTGGACCTCGGCTTACTTACGCAAATTTGTAGCCGAGGACTACCAC
GCCCACAAAATTCAGTTTTACGAAGACCAATCTCGACCACCGAAAGCCCCCCTCACGGCC
TGCGTCATCACCCAGAGCAAGATCCTGGCCCAATTGCAATCCATCAACCAAGCGCGCCGC
GATTTCCTTTTGAAAAAGGGTCGGGGGGTGTACCTGGACCCCCAGACCGGCGAGGAACTC
AACCCGTCCACACTCTCCGTCGAAGCAGCCCCCCCGAGACATGCCGCCCAAGGGAACCGC
CAAGCAGCTGATCGCTCGGCAGAGAGCGAAGAAGCAAGAGCTGCTCCAGCAGCAGGTGGA
GGACGAGGAAGAGATGTGGGACAGCCAGGCAGAGGAGGTGTCAGAGGACGAGGAGGAGAT
GGAAAGCTGGGACAGCCTAGACGAGGAGGAGGACGAGCTTTCAGAGGAAGAGGCGACCGA
AGAAAAACCACCTGCATCCAGCGCGCCTTCTCTGAGCCGACAGCCGAAGCCCCGGCCCCC
GACGCCCCCGGCCGGCTCACTCAAAGCCAGCCGTAGgtgggacgccaccgaatctccagc
ggcagcggcaacggcagcgggtaaggccaaacgcgagcggcgggggtattgctcctggcg
ggcccacaaaagcagtattgtgaactgcttgcaacactgcgggggaaacatctcctttgc
ccgacg

Length = 770

Score =  39.1 bits (79), Expect(4) = 0.0
Identities = 15/22 (68%), Positives = 18/22 (81%)
Frame = +1

Query: 22441 DEDVIVEQDPGYVTPPEDLEGP 22506
             +E+  VEQDPGYVTPPED + P
Sbjct: 31    EENEQVEQDPGYVTPPEDGKEP 52

Score =   400 bits (868), Expect(2) = e-119
Identities = 169/216 (78%), Positives = 187/216 (86%)
Frame = +1

Query: 22567 EGDVLLKHFARQSTIVKEALQDRSEVPLDVAALSQAYEANLFSPRVPPKRQPNGTCEPNP 22746
             E DVLLKH ARQSTIV+EAL++ ++ PL V  LS+AYEANLFSPRVPPK+QPNGTCE NP
Sbjct: 65    EDDVLLKHIARQSTIVREALKECTQTPLTVEELSRAYEANLFSPRVPPKKQPNGTCETNP 124

Query: 22747 RLNFYPVFAVPEALATYHIFFKNQRIPLSCRANRTAADRNLRLKNGANIPDITSLEEVPK 22926
             RLNFYPVFAVPEALATYHIFFKNQRIPLSCRANRT  D  L LK GA+IP+I SLEEVPK
Sbjct: 125   RLNFYPVFAVPEALATYHIFFKNQRIPLSCRANRTRGDGLLHLKAGAHIPEIVSLEEVPK 184

Query: 22927 IFEGLGRDEKRAANALQKEQKESQNVLVELEGDNARLAVLKRCIEVSHFAYPALNLPPKV 23106
             IFEGLG+DEKRAANALQK + E+QNVLVELEGDNARLAVLKR IEVSHFAYPALNLPPKV
Sbjct: 185   IFEGLGKDEKRAANALQKNETENQNVLVELEGDNARLAVLKRTIEVSHFAYPALNLPPKV 244

Query: 23107 MKSVMDQLLIKRAEPLDPDHPEAENSEDGKPVVSDE 23214
             M+SVMDQ+LIKRAEP+DP  P+  + +    V  DE
Sbjct: 245   MRSVMDQVLIKRAEPIDPQQPDLNSEDGQPVVSDDE 280

Score =   843 bits (1835), Expect(4) = 0.0
Identities = 345/430 (80%), Positives = 379/430 (88%)
Frame = +1

Query: 23179 NSEDGKPVVSDEELERWLETRDPQQLQERRKMMMAAVLVTVELECLQRFFSDVETLRKIG 23358
             NSEDG+PVVSD+EL RWL T+DP +LQERRKMMMAAVLVTVELECLQRFF++ +TLRK+ 
Sbjct: 268   NSEDGQPVVSDDELARWLGTQDPSELQERRKMMMAAVLVTVELECLQRFFANPQTLRKVE 327

Query: 23359 ESLHYTFRQGYVRQACKISNVELSNLVSYMGILHENRLGQSVLHCTLQGEARRDYVRDCI 23538
             ESLHY FR GYVRQACKISNVELSNL+SYMGILHENRLGQ+VLHCTLQGEARRDYVRDCI
Sbjct: 328   ESLHYAFRHGYVRQACKISNVELSNLISYMGILHENRLGQNVLHCTLQGEARRDYVRDCI 387

Query: 23539 YLFLTLTWQTAMGVWQQCLEERNLKELDKLLCRQRRALWSGFSERTVASALADIIFPERL 23718
             YLFL LTWQTAMGVWQQCLEE+NL+EL+KLL R RR LW+ F ERTVA  LA++IFPERL
Sbjct: 388   YLFLILTWQTAMGVWQQCLEEQNLQELNKLLVRARRELWTSFDERTVARQLANLIFPERL 447

Query: 23719 MKTLQNGLPDFISQSILQNFRSFVLERSGILPAMSCALPSDFVPLSYRECPPPLWSHCYL 23898
             M+TLQNGLPDF+SQSILQNFRSFVLERSGILPAMSCALPSDFVPL YRECPPPLWSHCYL
Sbjct: 448   MQTLQNGLPDFVSQSILQNFRSFVLERSGILPAMSCALPSDFVPLCYRECPPPLWSHCYL 507

Query: 23899 FQLANFLAYHSDLMEDVSGEGLLECHCRCNLCTPHRSLACNTELLSETQVIGTFEIQGPQ 24078
              +LAN+LA+HSDLMED SG+GLLECHCRCNLCTPHRSL CNTELLSETQVIGTFEIQGP+
Sbjct: 508   LRLANYLAHHSDLMEDSSGDGLLECHCRCNLCTPHRSLVCNTELLSETQVIGTFEIQGPE 567

Query: 24079 QQEGASGLKLTPALWTSAYLRKFVAEDYHAHKIQFYEDQSRPPKAPLTACVITQSKILAQ 24258
             QQEGAS LKLTPALWTSAYLRKF+ EDYHAH+I+FYEDQSRPPK PLTACVITQS+ILAQ
Sbjct: 568   QQEGASSLKLTPALWTSAYLRKFIPEDYHAHQIKFYEDQSRPPKVPLTACVITQSQILAQ 627

Query: 24259 LQSINQARRDFLLKKGRGVYLDPQTGEELNPSTLSVEAAPPRHAAQGNRQAADRSAESEE 24438
             LQ+I QAR++FLLKKG GVYLDPQTGEELN  +LS  A+          + A   A +  
Sbjct: 628   LQAIQQARQEFLLKKGHGVYLDPQTGEELNTPSLSAAASCRSQKHATQGKQASHRATAIP 687

Query: 24439 ARAAPAAGGG 24468
             A    A G G
Sbjct: 688   AETTKAVGRG 697

Score =  40.9 bits (83), Expect(2) = e-119
Identities = 16/27 (59%), Positives = 19/27 (70%)
Frame = +1

Query: 24511 GRGGDGKLGQPRRGGGRAFRGRGDRRK 24591
             G G DG+LGQPRRGG R   GR  R++
Sbjct: 713   GGGADGELGQPRRGGPRGRGGRNHRQR 739

Score =  22.1 bits (42), Expect(4) = 0.0
Identities = 12/41 (29%), Positives = 16/41 (39%)
Frame = +1

Query: 24556 GRAFRGRGDRRKTTCIQRAFSEPTAEAPAPDAPGRLTQSQP 24678
             GR  R    R+ T   +      +   PAP      T+SQP
Sbjct: 730   GRGGRNHRQRQGTIFQKTRSEPTSENYPAPATATMFTESQP 770


