========================================================================================================================

gene_id            %id    %sim   %cov   %t5   %gap  %t3   start..stop      pep sz ref sz ref id            definition
37.21              44.4   51.0   100.0  0.0   0.0   0.0   25584..25727     122    205    AP_000125.1       L4-3 | splicing factor
                                                          26209..26433                                     
                    invalid splicing for intron  at 25728..26208

CLUSTAL 2.1 multiple sequence alignment


predicted       MS-----QRRESKKLKVQPPPPEDMEED-WDSQAEEAEEDSLE------DSLEEDSLEEE
reference       MSPKAAKQAIAQQRSKKQQQRQEIWEEESWESQAEDEVEDLEEWEEEEADSLDEDPEEEE
                **     *   .:: * *    *  **: *:****:  **  *      ***:**. ***

predicted       E------------------------------------------------------PA---
reference       EGSKDGATAAKPSLSTKPSPMKPAVSKSQKANRRWDTIETSAANLAPLKSSTRNRPATAK
                *                                                      **   

predicted       --------------QTRELRNRIFPTLYAIFQQSRGQEHELKIKNRSLRSLTRSCLYHKS
reference       RPTRIGNSSNKESPEARELRKRIFPTLYAIFQQSRGQEHELKIKNRSLRSLTRSCLYLKS
                              ::****:************************************ **

predicted       EDQLQRTLEDAEALFNKYCALTLKE
reference       EDQLQRTLQDAEALFNKYCSLSLKE
                ********:**********:*:***

>37.21	25584	26433
aactttcggcctgcgtcatcacccagggggcaattctagcccaattgcaagccatccaaa
aatcccgccaagaatttctactgaaaaagggtaagggggtctaccttgacccccagaccg
gcgaggaactcaacacaaggttccctcaggATGTCCCAACGACGAGAAAGCAAGAAGTTG
AAGGTGCAGCCGCCGCCCCCAGAAGATATGGAGGAAGATTGGGACAGTCAGGCAGAGGAA
GCGGAGGAGGACAGTCTGGAGGACAGTCTGGAGGAAGACAGTTTGGAGGAGGAAaacgag
gaggcagaggaggtggaagaagtaaccgccggcaaacagttatccccggctgcggagaca
agcaacagcgctatcatctccgctccgagtcgaggaacgcggcggcgtcccagcagtaga
tgggacgagaccggacgcttcccaaacccaaccaccgcttccaaaaccggtaagaaggat
cggcagggatacaagtcctggcgggggcataagaatgccatcatctcctgcttgcatgag
tgcgggggaaacatatccttcacgcgacgctacttgctattccaccatggggtgaacttt
ccgcgcaatgttttgcattactaccgtcacctccacagcccctactatagccagcaaatc
ccggcagtctcgacagaaaaagacagcggcggcgacctccaacagaaaaccagcagcggc
agttaaaaaatacacaacaagtgcagcaacaggaggattaaagattacagccaacGAGCC
AGCGCAAACCCGAGAGCTAAGAAATCGGATCTTTCCAACCCTGTATGCCATCTTCCAGCA
GAGTCGGGGCCAAGAGCATGAACTGAAAATAAAAAACCGATCTTTGCGTTCGCTCACCAG
AAGTTGTTTGTATCACAAGAGCGAAGATCAACTTCAGCGCACTCTTGAGGACGCCGAGGC
TCTCTTCAACAAGTACTGCGCGCTGACTCTTAAAGAGTAGgcagcgaccgcgcttattca
aaaaaggcgggaattacatcatcctcgtcatgagtaaagaaattcccacgccttacatgt
ggagttatcagccccaaatgggattggcggcaggcgcctcccaggactactccacccgca
tgaattggct

Length = 205

Score =  38.2 bits (77), Expect(2) = 1e-46
Identities = 21/64 (32%), Positives = 29/64 (45%)
Frame = +3

Query: 25644 EEDWDSQAEEAEEDSLEDSLEEDSLEEENEEAEEVEEVTAGKQLSPAAETSNSAIISAPS 25823
             EE W+SQAE+  ED  E   EE    +E+ E EE           P+  T  S +  A S
Sbjct: 27    EESWESQAEDEVEDLEEWEEEEADSLDEDPEEEEEGSKDGATAAKPSLSTKPSPMKPAVS 86

Query: 25824 RGTR 25835
             +  +
Sbjct: 87    KSQK 90

Score =   154 bits (331), Expect(2) = 1e-46
Identities = 65/74 (87%), Positives = 69/74 (93%)
Frame = +1

Query: 26209 EPAQTRELRNRIFPTLYAIFQQSRGQEHELKIKNRSLRSLTRSCLYHKSEDQLQRTLEDA 26388
             E  + RELR RIFPTLYAIFQQSRGQEHELKIKNRSLRSLTRSCLY KSEDQLQRTL+DA
Sbjct: 132   ESPEARELRKRIFPTLYAIFQQSRGQEHELKIKNRSLRSLTRSCLYLKSEDQLQRTLQDA 191

Query: 26389 EALFNKYCALTLKE 26430
             EALFNKYC+L+LKE
Sbjct: 192   EALFNKYCSLSLKE 205


========================================================================================================================

gene_id            %id    %sim   %cov   %t5   %gap  %t3   start..stop      pep sz ref sz ref id            definition
47.19              87.0   98.2   33.7   66.3  0.0   0.0   <26913..27122    69     205    AP_000125.1       L4-3 | putative splicing factor, C-terminal
                    missing exon 1

CLUSTAL 2.1 multiple sequence alignment


predicted       ------------------------------------------------------------
reference       MSPKAAKQAIAQQRSKKQQQRQEIWEEESWESQAEDEVEDLEEWEEEEADSLDEDPEEEE
                                                                            

predicted       ------------------------------------------------------------
reference       EGSKDGATAAKPSLSTKPSPMKPAVSKSQKANRRWDTIETSAANLAPLKSSTRNRPATAK
                                                                            

predicted       ----------------RELRNRIFPTLYAIFQQSRGQEQELKIKNRSLRSLTRSCLYHKS
reference       RPTRIGNSSNKESPEARELRKRIFPTLYAIFQQSRGQEHELKIKNRSLRSLTRSCLYLKS
                                ****:*****************:****************** **

predicted       EDQLRRTLEDAEALFSKYCALTLKD
reference       EDQLQRTLQDAEALFNKYCSLSLKE
                ****:***:******.***:*:**:

>47.20	26913	27122
gcggcagcggcagcggcagcaacagcagcgatcacacagaagcaaaggcgaccggatagc
aagactctgacaaagcccaagaaatccacagcggcggcagcagcaggaggaggagcgctg
cgtctggcgcccaacgaacccgtatcgaccCGCGAGCTTAGAAACAGGATTTTTCCCACT
CTGTATGCTATATTTCAACAAAGCAGGGGCCAAGAACAAGAGCTGAAAATAAAAAACAGG
TCTCTGCGCTCCCTCACCCGCAGCTGCCTGTATCACAAAAGCGAAGATCAGCTTCGGCGC
ACGCTGGAAGACGCGGAGGCTCTCTTCAGCAAATACTGCGCGCTGACTCTTAAGGACTAG
tttcgcgccctttctcaaatttaagcgcgaaaactacgtcatctccagcggccacacccg
gcgccagcacctgtcgtcagcgccattatgagcaaggaaattcccacgccctacatgtgg
agttaccagccacaaatgggacttgcggct

Length = 205

Score =   144 bits (308), Expect = 3e-39
Identities = 61/74 (82%), Positives = 67/74 (90%)
Frame = +3

Query: 26898 EPVSTRELRNRIFPTLYAIFQQSRGQEQELKIKNRSLRSLTRSCLYHKSEDQLRRTLEDA 27077
             E    RELR RIFPTLYAIFQQSRGQE ELKIKNRSLRSLTRSCLY KSEDQL+RTL+DA
Sbjct: 132   ESPEARELRKRIFPTLYAIFQQSRGQEHELKIKNRSLRSLTRSCLYLKSEDQLQRTLQDA 191

Query: 27078 EALFSKYCALTLKD 27119
             EALF+KYC+L+LK+
Sbjct: 192   EALFNKYCSLSLKE 205


========================================================================================================================

gene_id            %id    %sim   %cov   %t5   %gap  %t3   start..stop      pep sz ref sz ref id            definition
64.6               74.8   89.8   97.6   2.4   0.0   0.0   11769..13445     558    582    AP_000115.1       L1 | IIIa capsid protein
                    could not find valid start codon

CLUSTAL 2.1 multiple sequence alignment


predicted       --------------DPAIRAALQSQPSGL-ASDDWEAAMQRIMALTTRNPESFRQQPQAN
reference       MQRPAIIAERAPNLDPAVLAAMQSQPSGVTASDDWTAAMDRIMALTARSPDAFRQQPQAN
                              ***: **:******: ***** ***:******:*.*::********

predicted       RLSAILEAVVPSRTNPTHEKVLAIVNALAENKAIRPDEAGLVYNALLERVGRYNSTNVQS
reference       RFSAILEAVVPSRTNPTHEKVLTIVNALLDSKAIRKDEAGLIYNALLERVARYNSTNVQA
                *:********************:***** :.**** *****:********.********:

predicted       NLDRLVTDVREAVAQRERFKNEG-LGSLVALNAFLATQPANVPRGQDDYTNFISALRLMV
reference       NLDRMGTDVKEALAQRERFHRDGNLGSLVALNAFLSTQPANVPRGQEDYTNFISALRLMV
                ****: ***:**:******:.:* ***********:**********:*************

predicted       TEVPQSEVYQSGPDYFFQTSRQGLQTVNLSQAFKNLRGLWGVQAPVGDRSTVSSLLTPNS
reference       TEVPQSEVYQSGPDYFFQTSRQGLQTVNLTQAFKNLQGLWGVRAPVGDRSTLSSLLTPNS
                *****************************:******:*****:********:********

predicted       RLLLLLIAPFTDSGSVNRNSYLGHLLTLYREAIGQAQVDEQTFQEITSVSRALGQNDTDS
reference       RLLLLLIAPFTNTNSLSRDSYLGHLVTLYREAIGQAQVDEQTYQEITSVSRALGQEDTGS
                ***********::.*:.*:******:****************:************:**.*

predicted       LRATLNFLLTNRQQKIPAQYALSAEEERILRYVQQSVGLFLMQEGATPSAALDMTARNME
reference       LEATLNFLLTNRRQQVPPQYTLNAEEERILRYVQQSVSLYLMREGATPSAALDMTARNME
                *.**********:*::*.**:*.**************.*:**:*****************

predicted       PSMYAANRPFINKLMDYLHRAASMNSDYFTNAILNPHWLPPPGFYTGEYDMPDPNDGFLW
reference       PSFYASNRAFINRLMDYLHRAAAMNGEYFTNAILNPHWLPPPGFYTGEFDLPEGNDGFLW
                **:**:**.***:*********:**.:*********************:*:*: ******

predicted       DDVDSAVFSPTLQKRQEAVRTPASEG----AVGRSPFPSLGSLHSLPGSVNSGRVSRPRL
reference       DDVTDSLFSPAVIG-HHGKKEAGDEGPLLDSRASSPFP---SLTSLPASVNSGRTTRPRL
                *** .::***::   :.. : ...**    : . ****   ** ***.******.:****

predicted       LGEDEYLNDSLLQPPRVKNAMVNNGIESLVDKLNRWKTYAQDHR-----EPAPA-PRRQR
reference       TGESEYLNDPILFPVRDKN-FPNNGIESLVDKMSRWKTYAQERREWEERQPRPVRPPRQR
                 **.*****.:* * * ** : **********:.*******::*     :* *. * ***

predicted       HDR-QRGLVWDDE---DSADDSSVLDLGGSGGANPFAHLQPR--LGRRMF
reference       WQRRKKGAHAGDEGSDDSADDSSVLDLGGSG--NPFAHLRPQGCIG-SLY
                 :* ::*   .**   ***************  ******:*:  :*  ::

>64.10	11769	13445
gggcggacctgcattggcagccgagccgacgcgccttggaggccgcctacggtccagagg
acttggatgaggaagaggaagaggaggaggatgcacccgttgcggggtactgacgcctcc
gtgatgtgtttttagatgcagcaagccccgGACCCCGCCATAAGGGCGGCGCTGCAAAGC
CAGCCGTCCGGTCTAGCATCGGACGACTGGGAGGCCGCGATGCAACGCATCATGGCCCTG
ACGACCCGCAACCCCGAGTCCTTTAGACAACAGCCGCAGGCCAACAGACTCTCGGCCATT
CTGGAGGCGGTGGTTCCTTCTCGGACCAACCCCACGCACGAGAAGGTGCTGGCGATCGTG
AACGCGCTGGCGGAGAACAAGGCCATCCGTCCCGACGAGGCCGGGCTAGTGTACAACGCC
CTGCTGGAGCGCGTGGGCCGCTACAACAGCACAAACGTGCAGTCCAACCTGGACCGGCTG
GTGACGGACGTGCGCGAGGCCGTGGCGCAGCGCGAGCGGTTCAAGAACGAGGGCCTGGGT
TCGCTGGTGGCGCTGAACGCCTTCCTGGCGACGCAGCCGGCGAACGTGCCGCGCGGGCAG
GATGATTATACCAACTTTATAAGCGCGCTGCGGCTGATGGTGACCGAGGTGCCCCAGAGC
GAGGTGTACCAGTCGGGCCCGGACTACTTTTTCCAGACGAGCAGACAGGGCCTGCAGACG
GTGAACCTGAGTCAGGCTTTCAAGAACCTGCGCGGGCTGTGGGGCGTGCAGGCGCCCGTG
GGCGACCGGTCGACGGTGAGCAGCTTGCTGACGCCCAACTCGCGGCTGCTGCTGCTGCTG
ATCGCGCCCTTCACCGACAGTGGCAGCGTGAACCGCAACTCGTACCTGGGTCACCTGCTG
ACGCTGTACCGCGAGGCCATAGGCCAGGCGCAGGTGGATGAGCAGACCTTCCAGGAGATC
ACTAGCGTGAGCCGCGCGCTGGGTCAGAACGACACCGACAGTCTGAGGGCCACCCTGAAC
TTCTTGCTGACCAATAGACAGCAGAAGATCCCGGCGCAGTACGCGCTGTCGGCCGAGGAG
GAGCGCATCCTGAGATATGTGCAGCAGAGCGTAGGGCTGTTCCTGATGCAGGAGGGGGCC
ACCCCCAGCGCCGCGCTGGACATGACCGCGCGCAACATGGAACCTAGCATGTACGCCGCC
AACCGGCCGTTTATTAATAAGCTGATGGACTACCTGCACCGCGCGGCGTCCATGAACTCG
GACTACTTTACCAATGCCATCTTGAACCCGCACTGGCTCCCGCCGCCGGGGTTCTACACG
GGCGAGTACGACATGCCTGACCCCAACGACGGGTTTTTGTGGGACGACGTGGACAGCGCG
GTGTTCTCACCGACCTTGCAAAAGCGCCAGGAGGCGGTGCGCACGCCCGCGAGCGAGGGC
GCGGTGGGTCGGAGCCCCTTTCCTAGCTTAGGGAGTTTGCATAGCTTGCCGGGCTCGGTG
AACAGCGGCAGGGTGAGCCGGCCGCGCTTGCTGGGCGAGGACGAGTACCTGAACGACTCG
CTGCTGCAGCCGCCGCGGGTCAAGAACGCCATGGTCAATAACGGGATAGAGAGTCTGGTG
GACAAACTGAACCGCTGGAAAACCTACGCTCAGGACCATAGGGAACCTGCGCCCGCGCCG
CGGCGACAGCGTCACGACCGGCAGCGGGGCCTGGTGTGGGACGACGAGGACTCGGCCGAC
GATAGCAGCGTGTTGGACTTGGGCGGGAGCGGTGGGGCCAACCCGTTCGCGCATCTGCAG
CCCAGACTGGGGCGACGGATGTTTTGAatgcaaaataaaactcaccaaggccatagcgtg
cgttctcttccttgttagagatgaggcgcgcggtggtgtcttcctctcctcctccctcgt
acgagagcgtgatggcgcaggcgaccctggaggttccgtttgtgcctccgcggtata

Length = 582

Score =  33.6 bits (67), Expect(9) = 0.0
Identities = 12/19 (63%), Positives = 16/19 (84%)
Frame = +3

Query: 11769 DPAIRAALQSQPSGLASDD 11825
             DPA+ AA+QSQPSG+ + D
Sbjct: 15    DPAVLAAMQSQPSGVTASD 33

Score =   216 bits (467), Expect(9) = 0.0
Identities = 91/113 (80%), Positives = 102/113 (90%)
Frame = +3

Query: 11814 ASDDWEAAMQRIMALTTRNPESFRQQPQANRLSAILEAVVPSRTNPTHEKVLAIVNALAE 11993
             ASDDW AAM RIMALT R+P++FRQQPQANR SAILEAVVPSRTNPTHEKVL IVNAL +
Sbjct: 31    ASDDWTAAMDRIMALTARSPDAFRQQPQANRFSAILEAVVPSRTNPTHEKVLTIVNALLD 90

Query: 11994 NKAIRPDEAGLVYNALLERVGRYNSTNVQSNLDRLVTDVREAVAQRERFKNEG 12152
             +KAIR DEAGL+YNALLERV RYNSTNVQ+NLDR+ TDV+EA+AQRERF  +G
Sbjct: 91    SKAIRKDEAGLIYNALLERVARYNSTNVQANLDRMGTDVKEALAQRERFHRDG 143

Score =   599 bits (1302), Expect(9) = 0.0
Identities = 245/292 (83%), Positives = 276/292 (94%)
Frame = +3

Query: 12141 KNEGLGSLVALNAFLATQPANVPRGQDDYTNFISALRLMVTEVPQSEVYQSGPDYFFQTS 12320
             ++  LGSLVALNAFL+TQPANVPRGQ+DYTNFISALRLMVTEVPQSEVYQSGPDYFFQTS
Sbjct: 141   RDGNLGSLVALNAFLSTQPANVPRGQEDYTNFISALRLMVTEVPQSEVYQSGPDYFFQTS 200

Query: 12321 RQGLQTVNLSQAFKNLRGLWGVQAPVGDRSTVSSLLTPNSRLLLLLIAPFTDSGSVNRNS 12500
             RQGLQTVNL+QAFKNL+GLWGV+APVGDRST+SSLLTPNSRLLLLLIAPFT++ S++R+S
Sbjct: 201   RQGLQTVNLTQAFKNLQGLWGVRAPVGDRSTLSSLLTPNSRLLLLLIAPFTNTNSLSRDS 260

Query: 12501 YLGHLLTLYREAIGQAQVDEQTFQEITSVSRALGQNDTDSLRATLNFLLTNRQQKIPAQY 12680
             YLGHL+TLYREAIGQAQVDEQT+QEITSVSRALGQ DT SL ATLNFLLTNR+Q++P QY
Sbjct: 261   YLGHLVTLYREAIGQAQVDEQTYQEITSVSRALGQEDTGSLEATLNFLLTNRRQQVPPQY 320

Query: 12681 ALSAEEERILRYVQQSVGLFLMQEGATPSAALDMTARNMEPSMYAANRPFINKLMDYLHR 12860
              L+AEEERILRYVQQSV L+LM+EGATPSAALDMTARNMEPS YA+NR FIN+LMDYLHR
Sbjct: 321   TLNAEEERILRYVQQSVSLYLMREGATPSAALDMTARNMEPSFYASNRAFINRLMDYLHR 380

Query: 12861 AASMNSDYFTNAILNPHWLPPPGFYTGEYDMPDPNDGFLWDDVDSAVFSPTL 13016
             AA+MN +YFTNAILNPHWLPPPGFYTGE+D+P+ NDGFLWDDV  ++FSP +
Sbjct: 381   AAAMNGEYFTNAILNPHWLPPPGFYTGEFDLPEGNDGFLWDDVTDSLFSPAV 432

Score =  62.5 bits (130), Expect(9) = 0.0
Identities = 27/38 (71%), Positives = 29/38 (76%)
Frame = +3

Query: 13092 SLHSLPGSVNSGRVSRPRLLGEDEYLNDSLLQPPRVKN 13205
             SL SLP SVNSGR +RPRL GE EYLND +L P R KN
Sbjct: 458   SLTSLPASVNSGRTTRPRLTGESEYLNDPILFPVRDKN 495

Score =  51.9 bits (107), Expect(9) = 0.0
Identities = 19/23 (82%), Positives = 22/23 (95%)
Frame = +3

Query: 13215 NNGIESLVDKLNRWKTYAQDHRE 13283
             NNGIESLVDK++RWKTYAQ+ RE
Sbjct: 498   NNGIESLVDKMSRWKTYAQERRE 520

Score =  19.9 bits (37), Expect(9) = 0.0
Identities = 8/24 (33%), Positives = 14/24 (58%)
Frame = +3

Query: 13296 PRRQRHDRQRGLVWDDEDSADDSS 13367
             P RQR  R++      ++ +DDS+
Sbjct: 531   PPRQRWQRRKKGAHAGDEGSDDSA 554

Score =  37.7 bits (76), Expect(9) = 0.0
Identities = 15/16 (93%), Positives = 16/16 (100%)
Frame = +3

Query: 13344 EDSADDSSVLDLGGSG 13391
             +DSADDSSVLDLGGSG
Sbjct: 551   DDSADDSSVLDLGGSG 566

Score =  25.8 bits (50), Expect(9) = 0.0
Identities = 8/12 (66%), Positives = 10/12 (83%)
Frame = +3

Query: 13389 GGANPFAHLQPR 13424
             G  NPFAHL+P+
Sbjct: 564   GSGNPFAHLRPQ 575


========================================================================================================================

gene_id            %id    %sim   %cov   %t5   %gap  %t3   start..stop      pep sz ref sz ref id            definition
gi_51527264.6      78.6   90.1   99.5   0.5   0.0   0.0   <10323..8404     639    641    AP_000113.1       pTP | putative DNA terminal protein, C-terminal
                    missing exon 1

CLUSTAL 2.1 multiple sequence alignment


predicted       ---SINDCARLTGQTVPTMNYFLPLRNIWNRVREFPRASTTAAGITWMSRYIYGYHRTML
reference       MALSIQDCARLTGQSVATIERFLPLRNIWNRAREFMRATTTAAGITWMSRYIYEYHRLML
                   **:********:*.*:: **********.*** **:************** *** **

predicted       EDLAPGAPATERWPLYRQPPPHFLIGYQYLVRTCNDYIFDSRAYSRLKYHELARPGHQTV
reference       EDLAPGAAATLGWPLYREPPPHFLVGYQYLVRTCNDYVFDSRAYSRLRYTETVQPGTQTV
                *******.**  *****:******:************:*********:* * .:** ***

predicted       NWSVMANCSYTINTGAYHRFVDFDDFQTTLTQIQQAILAERVVADLALVQPQRGFGLTRM
reference       NWSVMTNCSYTINAGAYHRFVDVDDFATTLTQIQQAVLAERVVADLALLQPLQGYGSTHM
                *****:*******:********.*** *********:***********:** :*:* *:*

predicted       HGRAGEEEVPVERLMQDYYKDLARCQDHAWGMADRLRIQQAGPKDLVLLATIRRLRTAYF
reference       ADR-GNREVEVERLMQDYYKDLGRCQSDVWGMADRLRIQQAGPKDVVLLKTIRGLKTAYF
                 .* *:.** ************.***...****************:*** *** *:****

predicted       NFITSSIAPAHTPPPPEETVLSLPCDCDWLEAFVQRFSDPVDLETLRSLRGVPTGQLIRC
reference       NYIISSIA--QLPGTLEETKLSLPCDCDWLDAFLERFSDPVDMQTLSSLRGVPTQQIIKC
                *:* ****  : * . *** **********:**::*******::** ******* *:*:*

predicted       IVSALSLPNGDPPG------HLEMRGGVFTLRPREDGRAVTETMRRRRGETIERFIDRLP
reference       IISAVSLPNAPRNASFPILHETELRGGVFELRPRENGRAVTETMRRRRGEMIERFVDRLP
                *:**:****.   .      . *:***** *****:************** ****:****

predicted       VRRRRRRPPPPPPPPEEEVEEMLVDEEEEVEELPGAFEREVRATIAELIRLLEEDLTVSA
reference       VRRRRRRQPPPP-VVEEEIMEV---EEEEQEIVPGAFQQEVRETVAELIRLLEEELTVAA
                ******* ****   ***: *:   **** * :****::*** *:*********:***:*

predicted       RNSQFFNFAVDFYEAMERLEALGDVSEMPLRRWIMYFFVTEHIATTLNYLYQRLCNYAVF
reference       RNSQFFNFAVDFYEAMERLEALGDINELTLRRWILYFFVSEHVATTLNYLFQRLRNYGVF
                ************************:.*:.*****:****:**:*******:*** **.**

predicted       ARHVELNLAQVVMRARDPEGAVVYSRVWNEAGMNAFSQLMGRISNDLAATVERAGRGDLQ
reference       ARLVELNLAQVVMRARDSEGGVVYSRVWNEIGLNAFSQLMSRISNDLAATIERAGHGDLQ
                ** **************.**.********* *:*******.*********:****:****

predicted       EEEIEQFMTEIAYQDNSGDVQEILRQAAVNDTEIDSVELSFRFKLTGPVAFTQRRQIQDV
reference       EEEIDQLMAEIAYQDNSGDVQEILRQAAVNDTEIDSVELSFRFKTTGPVVFTQRRQIQDI
                ****:*:*:*********************************** ****.*********:

predicted       NRRVVAHASLLRAQYQNLPARGADVPLPPLPPGPEPPLPPGARPRRRF
reference       NRRVVAHASQLRAQHLPLPERQADIPLPPLPAGPEPPLPPGARPRRRF
                ********* ****:  ** * **:******.****************

>gi_51527264.7	10323	8404
tcgagacgggagtgccagtaccacgttagctgcggctccagcctgattcgagattcgaac
cggggtacacgcgcagcccaacccgttcgcttagcctccaggccacggagtcgagccgct
gaccgctttcgtttttgcccgtatgtctagAGCATCAACGACTGCGCGCGCCTCACGGGC
CAGACCGTGCCCACCATGAACTACTTCCTGCCGCTGCGCAACATCTGGAACCGCGTCCGC
GAGTTCCCTCGCGCCTCCACCACCGCCGCCGGCATCACCTGGATGTCAAGGTACATCTAC
GGCTACCACCGCACCATGCTCGAGGACCTAGCGCCCGGCGCCCCCGCCACCGAGCGATGG
CCGCTCTACCGCCAGCCGCCGCCGCACTTCCTCATCGGCTACCAGTACCTGGTGCGCACC
TGCAACGACTACATCTTCGACTCGCGCGCCTACTCGCGCCTCAAGTACCACGAGCTCGCG
CGGCCCGGTCACCAGACTGTCAACTGGTCCGTCATGGCCAACTGCTCCTACACCATTAAC
ACCGGAGCCTACCACCGCTTCGTCGACTTTGACGACTTCCAGACCACCCTCACCCAGATC
CAGCAGGCCATCCTCGCCGAGCGCGTCGTCGCTGACCTGGCGCTCGTCCAGCCGCAGCGC
GGGTTTGGGCTCACGCGTATGCACGGCCGCGCGGGCGAGGAGGAGGTGCCCGTGGAGCGG
CTCATGCAGGACTACTACAAGGACCTGGCCAGGTGTCAGGACCACGCCTGGGGCATGGCC
GACCGTCTGCGCATCCAGCAAGCCGGGCCCAAAGACCTGGTGCTCCTCGCCACCATCCGC
CGTCTCAGAACCGCCTATTTCAACTTCATCACCAGCAGCATCGCCCCCGCCCACACCCCA
CCGCCGCCAGAAGAAACCGTGCTCAGCCTACCTTGCGACTGCGACTGGCTCGAAGCCTTC
GTTCAACGGTTTTCAGATCCCGTGGATCTAGAGACGCTTAGGTCCTTGCGCGGAGTCCCT
ACGGGGCAATTGATAAGATGCATCGTCAGCGCACTCTCCCTGCCCAACGGGGACCCCCCG
GGCCACCTGGAGATGCGCGGCGGCGTCTTTACGCTGCGACCCCGCGAGGACGGGCGCGCC
GTCACCGAGACCATGCGACGCCGGCGCGGCGAGACCATCGAGCGTTTCATCGACCGTCTG
CCCGTGCGCCGCCGGCGACGCAGGCCCCCTCCCCCGCCACCACCGCCTGAGGAGGAAGTA
GAAGAGATGTTAGTGGATGAAGAGGAGGAAGTGGAGGAACTCCCGGGAGCCTTCGAGCGC
GAGGTGCGCGCCACCATCGCCGAGCTCATCCGTCTTCTGGAGGAGGACTTGACCGTATCT
GCACGCAACTCCCAGTTTTTCAACTTCGCCGTGGACTTTTACGAGGCCATGGAGCGCTTG
GAAGCCCTGGGCGACGTCAGCGAAATGCCGCTCCGCCGCTGGATTATGTACTTCTTTGTC
ACTGAGCACATTGCCACCACGCTCAACTACCTCTACCAGCGCCTCTGCAACTACGCGGTT
TTTGCGCGCCACGTGGAGCTCAACCTCGCCCAGGTGGTCATGCGCGCCCGCGATCCCGAG
GGCGCCGTGGTTTACAGCCGCGTCTGGAACGAGGCGGGCATGAACGCCTTCTCGCAGCTC
ATGGGCCGCATCTCCAACGACCTCGCGGCCACCGTGGAGCGCGCCGGCCGCGGAGACCTT
CAGGAGGAGGAGATCGAGCAGTTCATGACCGAGATTGCCTACCAGGACAACTCGGGCGAC
GTGCAAGAGATTCTGCGGCAGGCCGCCGTCAATGATACCGAGATTGATTCTGTCGAACTG
TCTTTCAGGTTCAAACTCACGGGTCCCGTGGCCTTCACCCAGAGGCGTCAGATCCAGGAC
GTCAACCGTCGCGTCGTCGCTCACGCCAGTCTTCTCCGGGCGCAGTACCAGAACCTGCCC
GCGCGCGGCGCCGACGTGCCCCTGCCACCACTGCCTCCGGGTCCCGAGCCGCCCCTACCG
CCCGGCGCGCGTCCTCGCCGCCGCTTTTAAccatggaagccaaaccgcttccgcccgcca
agaagaaacgggggacggtggtcactccccaggggcacgggacactgcaagccatcgacg
tcgccaccaacggcgcggtggagatcaagtaccatctggacctcccgcgcgcccttgaaa

Length = 641

Score =   362 bits (785), Expect(3) = 0.0
Identities = 145/184 (78%), Positives = 157/184 (85%)
Frame = -1

Query: 10323 SINDCARLTGQTVPTMNYFLPLRNIWNRVREFPRASTTAAGITWMSRYIYGYHRTMLEDL 10144
             SI DCARLTGQ+V T+  FLPLRNIWNR REF RA+TTAAGITWMSRYIY YHR MLEDL
Sbjct: 4     SIQDCARLTGQSVATIERFLPLRNIWNRAREFMRATTTAAGITWMSRYIYEYHRLMLEDL 63

Query: 10143 APGAPATERWPLYRQPPPHFLIGYQYLVRTCNDYIFDSRAYSRLKYHELARPGHQTVNWS 9964
             APGA AT  WPLYR+PPPHFL+GYQYLVRTCNDY+FDSRAYSRL+Y E  +PG QTVNWS
Sbjct: 64    APGAAATLGWPLYREPPPHFLVGYQYLVRTCNDYVFDSRAYSRLRYTETVQPGTQTVNWS 123

Query: 9963  VMANCSYTINTGAYHRFVDFDDFQTTLTQIQQAILAERVVADLALVQPQRGFGLTRMHGR 9784
             VM NCSYTIN GAYHRFVD DDF TTLTQIQQA+LAERVVADLAL+QP +G+G T M  R
Sbjct: 124   VMTNCSYTINAGAYHRFVDVDDFATTLTQIQQAVLAERVVADLALLQPLQGYGSTHMADR 183

Query: 9783  AGEE 9772
                E
Sbjct: 184   GNRE 187

Score =   123 bits (264), Expect(3) = 0.0
Identities = 54/82 (65%), Positives = 58/82 (70%)
Frame = -1

Query: 9780  GEEEVPVERLMQDYYKDLARCQDHAWGMADRLRIQQAGPKDLVLLATIRRLRTAYFNFIT 9601
             G  EV VERLMQDYYKDL RCQ   WGMADRLRIQQAGPKD+VLL TIR L+TAYFN+I 
Sbjct: 184   GNREVEVERLMQDYYKDLGRCQSDVWGMADRLRIQQAGPKDVVLLKTIRGLKTAYFNYII 243

Query: 9600  SSIAPAHTPPPPEETVLSLPCD 9535
             SSIA         +  L   CD
Sbjct: 244   SSIAQLPGTLEETKLSLPCDCD 265

Score =   111 bits (238), Expect(2) = 1e-56
Identities = 43/60 (71%), Positives = 52/60 (86%)
Frame = -1

Query: 9585  AHTPPPPEETVLSLPCDCDWLEAFVQRFSDPVDLETLRSLRGVPTGQLIRCIVSALSLPN 9406
             A  P   EET LSLPCDCDWL+AF++RFSDPVD++TL SLRGVPT Q+I+CI+SA+SLPN
Sbjct: 247   AQLPGTLEETKLSLPCDCDWLDAFLERFSDPVDMQTLSSLRGVPTQQIIKCIISAVSLPN 306

Score =   114 bits (243), Expect(2) = 1e-56
Identities = 47/58 (81%), Positives = 51/58 (87%)
Frame = -1

Query: 9384  EMRGGVFTLRPREDGRAVTETMRRRRGETIERFIDRLPVRRRRRRPPPPPPPPEEEVE 9211
             E+RGGVF LRPRE+GRAVTETMRRRRGE IERF+DRLPVRRRRRR PPPP   EE +E
Sbjct: 320   ELRGGVFELRPRENGRAVTETMRRRRGEMIERFVDRLPVRRRRRRQPPPPVVEEEIME 377

Score =   541 bits (1175), Expect(3) = 0.0
Identities = 232/293 (79%), Positives = 254/293 (86%)
Frame = -1

Query: 9285  IDRLPVRRRRRRPPPPPPPPEEEVEEMLVDEEEEVEELPGAFEREVRATIAELIRLLEED 9106
             I+R   R   RR     PPP    EE++  EEEE E +PGAF++EVR T+AELIRLLEE+
Sbjct: 349   IERFVDRLPVRRRRRRQPPPPVVEEEIMEVEEEEQEIVPGAFQQEVRETVAELIRLLEEE 408

Query: 9105  LTVSARNSQFFNFAVDFYEAMERLEALGDVSEMPLRRWIMYFFVTEHIATTLNYLYQRLC 8926
             LTV+ARNSQFFNFAVDFYEAMERLEALGD++E+ LRRWI+YFFV+EH+ATTLNYL+QRL 
Sbjct: 409   LTVAARNSQFFNFAVDFYEAMERLEALGDINELTLRRWILYFFVSEHVATTLNYLFQRLR 468

Query: 8925  NYAVFARHVELNLAQVVMRARDPEGAVVYSRVWNEAGMNAFSQLMGRISNDLAATVERAG 8746
             NY VFAR VELNLAQVVMRARD EG VVYSRVWNE G+NAFSQLM RISNDLAAT+ERAG
Sbjct: 469   NYGVFARLVELNLAQVVMRARDSEGGVVYSRVWNEIGLNAFSQLMSRISNDLAATIERAG 528

Query: 8745  RGDLQEEEIEQFMTEIAYQDNSGDVQEILRQAAVNDTEIDSVELSFRFKLTGPVAFTQRR 8566
              GDLQEEEI+Q M EIAYQDNSGDVQEILRQAAVNDTEIDSVELSFRFK TGPV FTQRR
Sbjct: 529   HGDLQEEEIDQLMAEIAYQDNSGDVQEILRQAAVNDTEIDSVELSFRFKTTGPVVFTQRR 588

Query: 8565  QIQDVNRRVVAHASLLRAQYQNLPARGADVPLPPLPPGPEPPLPPGARPRRRF 8407
             QIQD+NRRVVAHAS LRAQ+  LP R AD+PLPPLP GPEPPLPPGARPRRRF
Sbjct: 589   QIQDINRRVVAHASQLRAQHLPLPERQADIPLPPLPAGPEPPLPPGARPRRRF 641


========================================================================================================================

gene_id            %id    %sim   %cov   %t5   %gap  %t3   start..stop      pep sz ref sz ref id            definition
gi_51527264.18     85.1   98.0   36.1   63.9  0.0   0.0   <26028..26252    74     205    AP_000125.1       L4-3 | putative splicing factor, C-terminal
                    missing exon 1

CLUSTAL 2.1 multiple sequence alignment


predicted       ------------------------------------------------------------
reference       MSPKAAKQAIAQQRSKKQQQRQEIWEEESWESQAEDEVEDLEEWEEEEADSLDEDPEEEE
                                                                            

predicted       ------------------------------------------------------------
reference       EGSKDGATAAKPSLSTKPSPMKPAVSKSQKANRRWDTIETSAANLAPLKSSTRNRPATAK
                                                                            

predicted       -----------EPAQTRELRNRIFPTLYAIFQQSRGQEQELKVKNRSLRSLTRSCLYHKS
reference       RPTRIGNSSNKESPEARELRKRIFPTLYAIFQQSRGQEHELKIKNRSLRSLTRSCLYLKS
                           *..::****:*****************:***:************** **

predicted       EDQLQRTLEDAEALFNKYCALTLKE
reference       EDQLQRTLQDAEALFNKYCSLSLKE
                ********:**********:*:***

>gi_51527264.19	26028	26252
gcggggtgaacttcccccgcaacatcttgcattactaccgtcacctccacagcccctact
acttccaagaagaggcagaaaaagacaaaaccagcagctagaaaatccacagcggcggcg
gcggcaggtggactgaggatcgcggcgaacGAGCCGGCGCAGACCCGGGAACTGAGGAAC
CGGATCTTTCCCACCCTCTATGCCATCTTCCAGCAGAGTCGGGGGCAGGAGCAGGAACTG
AAAGTCAAGAACCGTTCTCTGCGCTCGCTCACCCGCAGTTGTCTGTATCACAAGAGCGAA
GACCAACTTCAGCGCACGCTTGAGGACGCCGAGGCTCTCTTCAACAAGTACTGCGCACTC
ACTCTTAAAGAGTAGcccgcgcccgcccacacacggaaaaaggcgggaattacgtcacct
gtgcacccccacccagcaccgctatgagcaaagaaattcccacgccttacatgtggagct
accagccccagatgggcctggccgccggcgccgcccaggactact

Length = 205

Score =   150 bits (322), Expect = 3e-41
Identities = 63/74 (85%), Positives = 68/74 (91%)
Frame = +3

Query: 26028 EPAQTRELRNRIFPTLYAIFQQSRGQEQELKVKNRSLRSLTRSCLYHKSEDQLQRTLEDA 26207
             E  + RELR RIFPTLYAIFQQSRGQE ELK+KNRSLRSLTRSCLY KSEDQLQRTL+DA
Sbjct: 132   ESPEARELRKRIFPTLYAIFQQSRGQEHELKIKNRSLRSLTRSCLYLKSEDQLQRTLQDA 191

Query: 26208 EALFNKYCALTLKE 26249
             EALFNKYC+L+LKE
Sbjct: 192   EALFNKYCSLSLKE 205


========================================================================================================================

gene_id            %id    %sim   %cov   %t5   %gap  %t3   start..stop      pep sz ref sz ref id            definition
gi_61602086.5      71.2   90.9   36.6   2.1   0.0   61.3  7486..>7641      52     142    NP_040916.2       L1-3 | putative L1 13.6 kDa protein, N-terminal
                    could not find valid start codon and missing exon 2

CLUSTAL 2.1 multiple sequence alignment


predicted       ---DREEADLLPPVGGMGVDVVKVEVPPAHRAFVLMFVKATAVVAALHALYLLNE-----
reference       MRTDWEKVDLLPPVGRMAVDVMKVEISSADRAFMLMFVKACAVFASLHGLYLLNEVYLAA
                   * *:.******* *.***:***:..*.***:****** **.*:**.******     

predicted       ------------------------------------------------------------
reference       SHQKADGKINTTWQLPFVLFLFCCIATTVWILESENGEGDGAPRPACPDFSTRGAETGNQ
                                                                            

predicted       ----------------------
reference       GVQPGAVHGISQREKHELRARS

>gi_61602086.6	7486	7641
cagctcgcaggcttgacgaacgagggtctcctcgcccgagacgtgcatgaccagcatgaa
gggtaccaactgtttcccgaacgagcccatccatgtgtaggtttctacgtcgtaggtgac
aaagagccgctgggtgcgcgcgtgggagccGATCGGGAAGAAGCTGATCTCCTGCCACCA
GTTGGAGGAATGGGTGTTGATGTGGTGAAAGTAGAAGTCCCGCCGGCGCACAGAGCATTC
GTGCTGATGTTTGTAAAAGCGACCGCAGTAGTCGCAGCGCTGCACGCTCTGTATCTCCTG
AATGAGatgcgcttttcgcccgcgcaccagaaaccggagggggaagttgagacgggggct
tggtggggcggcatccccttcgccttggcggtgggagtctgcgtctgcgccctccttctc
tgggtggacgacggtggggacgacgacgccccgggt

Length = 142

Score =   100 bits (214), Expect = 1e-26
Identities = 42/68 (61%), Positives = 53/68 (77%)
Frame = +1

Query: 7486 DREEADLLPPVGGMGVDVVKVEVPPAHRAFVLMFVKATAVVAALHALYLLNEMRFSPAHQ 7665
            D E+ DLLPPVG M VDV+KVE+  A RAF+LMFVKA AV A+LH LYLLNE+  + +HQ
Sbjct: 4    DWEKVDLLPPVGRMAVDVMKVEISSADRAFMLMFVKACAVFASLHGLYLLNEVYLAASHQ 63

Query: 7666 KPEGEVET 7689
            K +G++ T
Sbjct: 64   KADGKINT 71


