========================================================================================================================

gene_id            %id    %sim   %cov   %t5   %gap  %t3   start..stop      pep sz ref sz ref id            definition
gi_399605605.2     95.7   98.0   95.9   0.0   4.1   0.0   1710..2369       219    219    AAA46833.1        C' | C' protein
                    stop codon embedded in CDS at 2151..2153
                    translation exception 1710..1712:M

CLUSTAL 2.1 multiple sequence alignment


predicted       MDTSASKTLLPEWIRMPSFLRGILRPKERHHENKNHSQMSSDSLTSSYPTSPPKLEKTEA
reference       MDTPASKTLLPEWIRMPSFLRGILKPKERHHENKNHSQMSSDSLTSSYPTSPPKLEKTEA
                ***.********************:***********************************

predicted       GSIVSSTTQKKTSHHANLTITIKTEQSRRRPKIIDQVRRVESLGEQVSQKQRHMLESLIN
reference       GSMVSSTTQKKTSHHAKPTITTKTEQSQRRPKIIDQVRRVESLGEQVSQKQRHMLESLIN
                **:*************: *** *****:********************************

predicted       KVYTGPLGEELVQTLYLRIWAMKETPEXRKILQMREDIRDQYLRXXXXXXXXXLIRGKKT
reference       KVYTGPLGEELVQTLYLRIWAMKETPESTKILQMREDIRDQYLRMKTERWLRTLIRGKKT
                ***************************  ***************         *******

predicted       KLRDFQKRYEEVHPYLMMERVEQIIMEEAWKLAAHIVQE
reference       KLRDFQKRYEEVHPYLMMERVEQIIMEEAWKLAAHIVQE
                ***************************************

>gi_399605605.2	1710	2369
gatgctacagcggctgcagggataggaggaatttaacaggataattggacagtagaaacc
agatcaaaagtaagaaaaacttagggtgaatggcaattcacagatcagctcaaccagaca
tcatcagcatacacgaaaccaaccttcacaGTGGATACCTCAGCATCCAAAACTCTCCTT
CCCGAATGGATCAGGATGCCTTCTTTTTTGAGAGGGATCCTGAGGCCGAAGGAGAGGCAC
CACGAAAACAAGAATCACTCTCAGATGTCATCGGACTCCTTGACGTCGTCCTATCCTACA
AGCCCACCGAAATTGGAGAAGACAGAAGCTGGCTCCATAGTATCATCGACAACCCAAAAG
AAAACAAGTCATCATGCAAATCTGACGATAACGATAAAGACAGAGCAATCTCGACGTCGA
CCCAAGATCATAGATCAAGTGAGGAGAGTAGAGTCTCTAGGAGAACAGGTGAGTCAAAAA
CAGAGACACATGCTAGAATCCTTGATCAACAAGGTGTACACAGGGCCTCTAGGCGAGGAA
CTAGTCCAAACCCTCTACCTGAGAATATGGGCAATGAAAGAAACACCAGAATAGAGGAAG
ATCCTTCAAATGAGAGAAGACATCAGAGATCAGTATCTACGGNNNNNNNNNNNNNNNNNN
NNNNNNNNTTTAATAAGAGGGAAGAAGACCAAGTTGAGGGATTTCCAGAAGAGGTACGAG
GAAGTACATCCTTATCTGATGATGGAGAGAGTAGAACAAATAATAATGGAAGAAGCATGG
AAACTAGCAGCACACATAGTACAAGAATAActgatgtcattaccaacccaagtccagagc
ttgaagatgccgttctacaaaggaataaaagacggccgacgaccatcaagcgtaaccaaa
caagatcagagagaacacagaactcagaactccacaaatcaacaagtggagacagctcca

Length = 219

Score =   466 bits (1012), Expect = e-136
Identities = 200/219 (91%), Positives = 204/219 (93%)
Frame = +3

Query: 1710 VDTSASKTLLPEWIRMPSFLRGILRPKERHHENKNHSQMSSDSLTSSYPTSPPKLEKTEA 1889
            +DT ASKTLLPEWIRMPSFLRGIL+PKERHHENKNHSQMSSDSLTSSYPTSPPKLEKTEA
Sbjct: 1    MDTPASKTLLPEWIRMPSFLRGILKPKERHHENKNHSQMSSDSLTSSYPTSPPKLEKTEA 60

Query: 1890 GSIVSSTTQKKTSHHANLTITIKTEQSRRRPKIIDQVRRVESLGEQVSQKQRHMLESLIN 2069
            GS+VSSTTQKKTSHHA  TIT KTEQS+RRPKIIDQVRRVESLGEQVSQKQRHMLESLIN
Sbjct: 61   GSMVSSTTQKKTSHHAKPTITTKTEQSQRRPKIIDQVRRVESLGEQVSQKQRHMLESLIN 120

Query: 2070 KVYTGPLGEELVQTLYLRIWAMKETPE*RKILQMREDIRDQYLRXXXXXXXXXLIRGKKT 2249
            KVYTGPLGEELVQTLYLRIWAMKETPE  KILQMREDIRDQYLR         LIRGKKT
Sbjct: 121  KVYTGPLGEELVQTLYLRIWAMKETPESTKILQMREDIRDQYLRMKTERWLRTLIRGKKT 180

Query: 2250 KLRDFQKRYEEVHPYLMMERVEQIIMEEAWKLAAHIVQE 2366
            KLRDFQKRYEEVHPYLMMERVEQIIMEEAWKLAAHIVQE
Sbjct: 181  KLRDFQKRYEEVHPYLMMERVEQIIMEEAWKLAAHIVQE 219


========================================================================================================================

gene_id            %id    %sim   %cov   %t5   %gap  %t3   start..stop      pep sz ref sz ref id            definition
gi_399605605.4     97.4   98.5   95.6   0.0   4.4   0.0   1755..2369       204    204    sp_P32535_C_PI1HE C | C protein
                    stop codon embedded in CDS at 2151..2153

CLUSTAL 2.1 multiple sequence alignment


predicted       MPSFLRGILRPKERHHENKNHSQMSSDSLTSSYPTSPPKLEKTEAGSIVSSTTQKKTSHH
reference       MPSFLRGILRPKERHHENKNHSQMSSDSLTSSYPTSPPKLEKTEAGSIISSTTQKKTSHH
                ************************************************:***********

predicted       ANLTITIKTEQSRRRPKIIDQVRRVESLGEQVSQKQRHMLESLINKVYTGPLGEELVQTL
reference       ANLTITTKTEQSQRRPKIIDQVRRVESLGEQVSQKQRHMLESLINKVYTGPLGEELVQTL
                ****** *****:***********************************************

predicted       YLRIWAMKETPEXRKILQMREDIRDQYLRXXXXXXXXXLIRGKKTKLRDFQKRYEEVHPY
reference       YLRIWAMKETPESTKILQMREDIRDQYLRMKTERWLRTLIRGKKTKLRDFQKRYEEVHPY
                ************  ***************         **********************

predicted       LMMERVEQIIMEEAWKLAAHIVQE
reference       LMMERVEQIIMEEAWKLAAHIVQE
                ************************

>gi_399605605.4	1755	2369
tggacagtagaaaccagatcaaaagtaagaaaaacttagggtgaatggcaattcacagat
cagctcaaccagacatcatcagcatacacgaaaccaaccttcacagtggatacctcagca
tccaaaactctccttcccgaatggatcaggATGCCTTCTTTTTTGAGAGGGATCCTGAGG
CCGAAGGAGAGGCACCACGAAAACAAGAATCACTCTCAGATGTCATCGGACTCCTTGACG
TCGTCCTATCCTACAAGCCCACCGAAATTGGAGAAGACAGAAGCTGGCTCCATAGTATCA
TCGACAACCCAAAAGAAAACAAGTCATCATGCAAATCTGACGATAACGATAAAGACAGAG
CAATCTCGACGTCGACCCAAGATCATAGATCAAGTGAGGAGAGTAGAGTCTCTAGGAGAA
CAGGTGAGTCAAAAACAGAGACACATGCTAGAATCCTTGATCAACAAGGTGTACACAGGG
CCTCTAGGCGAGGAACTAGTCCAAACCCTCTACCTGAGAATATGGGCAATGAAAGAAACA
CCAGAATAGAGGAAGATCCTTCAAATGAGAGAAGACATCAGAGATCAGTATCTACGGNNN
NNNNNNNNNNNNNNNNNNNNNNNTTTAATAAGAGGGAAGAAGACCAAGTTGAGGGATTTC
CAGAAGAGGTACGAGGAAGTACATCCTTATCTGATGATGGAGAGAGTAGAACAAATAATA
ATGGAAGAAGCATGGAAACTAGCAGCACACATAGTACAAGAATAActgatgtcattacca
acccaagtccagagcttgaagatgccgttctacaaaggaataaaagacggccgacgacca
tcaagcgtaaccaaacaagatcagagagaacacagaactcagaactccacaaatcaacaa
gtggagacagctcca

Length = 204

Score =   443 bits (961), Expect = e-129
Identities = 190/204 (93%), Positives = 192/204 (94%)
Frame = +3

Query: 1755 MPSFLRGILRPKERHHENKNHSQMSSDSLTSSYPTSPPKLEKTEAGSIVSSTTQKKTSHH 1934
            MPSFLRGILRPKERHHENKNHSQMSSDSLTSSYPTSPPKLEKTEAGSI+SSTTQKKTSHH
Sbjct: 1    MPSFLRGILRPKERHHENKNHSQMSSDSLTSSYPTSPPKLEKTEAGSIISSTTQKKTSHH 60

Query: 1935 ANLTITIKTEQSRRRPKIIDQVRRVESLGEQVSQKQRHMLESLINKVYTGPLGEELVQTL 2114
            ANLTIT KTEQS+RRPKIIDQVRRVESLGEQVSQKQRHMLESLINKVYTGPLGEELVQTL
Sbjct: 61   ANLTITTKTEQSQRRPKIIDQVRRVESLGEQVSQKQRHMLESLINKVYTGPLGEELVQTL 120

Query: 2115 YLRIWAMKETPE*RKILQMREDIRDQYLRXXXXXXXXXLIRGKKTKLRDFQKRYEEVHPY 2294
            YLRIWAMKETPE  KILQMREDIRDQYLR         LIRGKKTKLRDFQKRYEEVHPY
Sbjct: 121  YLRIWAMKETPESTKILQMREDIRDQYLRMKTERWLRTLIRGKKTKLRDFQKRYEEVHPY 180

Query: 2295 LMMERVEQIIMEEAWKLAAHIVQE 2366
            LMMERVEQIIMEEAWKLAAHIVQE
Sbjct: 181  LMMERVEQIIMEEAWKLAAHIVQE 204


========================================================================================================================

gene_id            %id    %sim   %cov   %t5   %gap  %t3   start..stop      pep sz ref sz ref id            definition
gi_399605605.5     97.1   98.3   95.0   0.0   5.0   0.0   1824..2369       181    181    AAA46832.1        Y1 | Y1 protein
                    stop codon embedded in CDS at 2151..2153

CLUSTAL 2.1 multiple sequence alignment


predicted       MSSDSLTSSYPTSPPKLEKTEAGSIVSSTTQKKTSHHANLTITIKTEQSRRRPKIIDQVR
reference       MSSDSLTSSYPTSPPKLEKTEAGSIISSTTQKKTSHHANLTITTKTEQSQRRPKIIDQVR
                *************************:***************** *****:**********

predicted       RVESLGEQVSQKQRHMLESLINKVYTGPLGEELVQTLYLRIWAMKETPEXRKILQMREDI
reference       RVESLGEQVSQKQRHMLESLINKVYTGPLGEELVQTLYLRIWAMKETPESTKILQMREDI
                *************************************************  *********

predicted       RDQYLRXXXXXXXXXLIRGKKTKLRDFQKRYEEVHPYLMMERVEQIIMEEAWKLAAHIVQ
reference       RDQYLRMKTERWLRTLIRGKKTKLRDFQKRYEEVHPYLMMERVEQIIMEEAWKLAAHIVQ
                ******         *********************************************

predicted       E
reference       E
                *

>gi_399605605.5	1824	2369
cagacatcatcagcatacacgaaaccaaccttcacagtggatacctcagcatccaaaact
ctccttcccgaatggatcaggatgccttcttttttgagagggatcctgaggccgaaggag
aggcaccacgaaaacaagaatcactctcagATGTCATCGGACTCCTTGACGTCGTCCTAT
CCTACAAGCCCACCGAAATTGGAGAAGACAGAAGCTGGCTCCATAGTATCATCGACAACC
CAAAAGAAAACAAGTCATCATGCAAATCTGACGATAACGATAAAGACAGAGCAATCTCGA
CGTCGACCCAAGATCATAGATCAAGTGAGGAGAGTAGAGTCTCTAGGAGAACAGGTGAGT
CAAAAACAGAGACACATGCTAGAATCCTTGATCAACAAGGTGTACACAGGGCCTCTAGGC
GAGGAACTAGTCCAAACCCTCTACCTGAGAATATGGGCAATGAAAGAAACACCAGAATAG
AGGAAGATCCTTCAAATGAGAGAAGACATCAGAGATCAGTATCTACGGNNNNNNNNNNNN
NNNNNNNNNNNNNNTTTAATAAGAGGGAAGAAGACCAAGTTGAGGGATTTCCAGAAGAGG
TACGAGGAAGTACATCCTTATCTGATGATGGAGAGAGTAGAACAAATAATAATGGAAGAA
GCATGGAAACTAGCAGCACACATAGTACAAGAATAActgatgtcattaccaacccaagtc
cagagcttgaagatgccgttctacaaaggaataaaagacggccgacgaccatcaagcgta
accaaacaagatcagagagaacacagaactcagaactccacaaatcaacaagtggagaca
gctcca

Length = 181

Score =   385 bits (834), Expect = e-111
Identities = 167/181 (92%), Positives = 169/181 (93%)
Frame = +3

Query: 1824 MSSDSLTSSYPTSPPKLEKTEAGSIVSSTTQKKTSHHANLTITIKTEQSRRRPKIIDQVR 2003
            MSSDSLTSSYPTSPPKLEKTEAGSI+SSTTQKKTSHHANLTIT KTEQS+RRPKIIDQVR
Sbjct: 1    MSSDSLTSSYPTSPPKLEKTEAGSIISSTTQKKTSHHANLTITTKTEQSQRRPKIIDQVR 60

Query: 2004 RVESLGEQVSQKQRHMLESLINKVYTGPLGEELVQTLYLRIWAMKETPE*RKILQMREDI 2183
            RVESLGEQVSQKQRHMLESLINKVYTGPLGEELVQTLYLRIWAMKETPE  KILQMREDI
Sbjct: 61   RVESLGEQVSQKQRHMLESLINKVYTGPLGEELVQTLYLRIWAMKETPESTKILQMREDI 120

Query: 2184 RDQYLRXXXXXXXXXLIRGKKTKLRDFQKRYEEVHPYLMMERVEQIIMEEAWKLAAHIVQ 2363
            RDQYLR         LIRGKKTKLRDFQKRYEEVHPYLMMERVEQIIMEEAWKLAAHIVQ
Sbjct: 121  RDQYLRMKTERWLRTLIRGKKTKLRDFQKRYEEVHPYLMMERVEQIIMEEAWKLAAHIVQ 180

Query: 2364 E 2366
            E
Sbjct: 181  E 181


========================================================================================================================

gene_id            %id    %sim   %cov   %t5   %gap  %t3   start..stop      pep sz ref sz ref id            definition
gi_399605605.6     94.6   96.4   94.9   0.0   5.1   0.0   1842..2369       175    175    tr_Q8QT28_9PARA   Y2 | putative Y2 protein
                    stop codon embedded in CDS at 2151..2153
                    translation exception 1842..1844:M

CLUSTAL 2.1 multiple sequence alignment


predicted       MSSYPTSPPKLEKTEAGSIVSSTTQKKTSHHANLTITIKTEQSRRRPKIIDQVRRVESLG
reference       MSSYPTSPQKLEKTEAGSMVSSTTQKKTSHHAKPTITTKTEQSQRRPKIIDQVRGVESLG
                ******** *********:*************: *** *****:********** *****

predicted       EQVSQKQRHMLESLINKVYTGPLGEELVQTLYLRIWAMKETPEXRKILQMREDIRDQYLR
reference       EQVSQKQRHMLESLINKVYTGPLGEELVQTLYLRIWAMKETPESTKILQMREDIRDQYLR
                *******************************************  ***************

predicted       XXXXXXXXXLIRGKKTKLRDFQKRYEEVHPYLMMERVEQIIMEEAWKLAAHIVQE
reference       MKTERWLRTLIRGKKTKLRDFQKRYEEVHPYLMMERVEQIIMEEAWKLAAHIVQE
                         **********************************************

>gi_399605605.6	1842	2369
acgaaaccaaccttcacagtggatacctcagcatccaaaactctccttcccgaatggatc
aggatgccttcttttttgagagggatcctgaggccgaaggagaggcaccacgaaaacaag
aatcactctcagatgtcatcggactccttgACGTCGTCCTATCCTACAAGCCCACCGAAA
TTGGAGAAGACAGAAGCTGGCTCCATAGTATCATCGACAACCCAAAAGAAAACAAGTCAT
CATGCAAATCTGACGATAACGATAAAGACAGAGCAATCTCGACGTCGACCCAAGATCATA
GATCAAGTGAGGAGAGTAGAGTCTCTAGGAGAACAGGTGAGTCAAAAACAGAGACACATG
CTAGAATCCTTGATCAACAAGGTGTACACAGGGCCTCTAGGCGAGGAACTAGTCCAAACC
CTCTACCTGAGAATATGGGCAATGAAAGAAACACCAGAATAGAGGAAGATCCTTCAAATG
AGAGAAGACATCAGAGATCAGTATCTACGGNNNNNNNNNNNNNNNNNNNNNNNNNNTTTA
ATAAGAGGGAAGAAGACCAAGTTGAGGGATTTCCAGAAGAGGTACGAGGAAGTACATCCT
TATCTGATGATGGAGAGAGTAGAACAAATAATAATGGAAGAAGCATGGAAACTAGCAGCA
CACATAGTACAAGAATAActgatgtcattaccaacccaagtccagagcttgaagatgccg
ttctacaaaggaataaaagacggccgacgaccatcaagcgtaaccaaacaagatcagaga
gaacacagaactcagaactccacaaatcaacaagtggagacagctcca

Length = 175

Score =   356 bits (772), Expect = e-103
Identities = 156/174 (89%), Positives = 158/174 (90%)
Frame = +3

Query: 1845 SSYPTSPPKLEKTEAGSIVSSTTQKKTSHHANLTITIKTEQSRRRPKIIDQVRRVESLGE 2024
            SSYPTSP KLEKTEAGS+VSSTTQKKTSHHA  TIT KTEQS+RRPKIIDQVR VESLGE
Sbjct: 2    SSYPTSPQKLEKTEAGSMVSSTTQKKTSHHAKPTITTKTEQSQRRPKIIDQVRGVESLGE 61

Query: 2025 QVSQKQRHMLESLINKVYTGPLGEELVQTLYLRIWAMKETPE*RKILQMREDIRDQYLRX 2204
            QVSQKQRHMLESLINKVYTGPLGEELVQTLYLRIWAMKETPE  KILQMREDIRDQYLR 
Sbjct: 62   QVSQKQRHMLESLINKVYTGPLGEELVQTLYLRIWAMKETPESTKILQMREDIRDQYLRM 121

Query: 2205 XXXXXXXXLIRGKKTKLRDFQKRYEEVHPYLMMERVEQIIMEEAWKLAAHIVQE 2366
                    LIRGKKTKLRDFQKRYEEVHPYLMMERVEQIIMEEAWKLAAHIVQE
Sbjct: 122  KTERWLRTLIRGKKTKLRDFQKRYEEVHPYLMMERVEQIIMEEAWKLAAHIVQE 175


