>gi_298354674.1 pseudogene location=26..748,982..982 codon_start=1 gene="CM1" product="CM1 protein" ref_db="fluc_db" ref_id="Seg6prot1A"
MAHEILIAETEAFLKNVAPETRTAIISAITGGKSACKSAAKLIKNEHLPLMSGEATTMHI
VMRCLYPEIKPWKKASDMLNKATSSLKKSEGRDIRKQMKAAGDFLGVESMMKMRAFRDDQ
IMEMVEEVYDHPDDYTPDIRIGTITAWLRCKNKKSERYRSNVSESGRTALKIHEVRKAST
AMNEIAGITGLGEEALSLQRQTESLAILCNHTFGSNIMRPHLEKAIKGVEGRVGEMGRMA
M
>gi_298354674.2 location=731..1150 codon_start=1 gene="CM2 protein" product="CM2 protein" ref_db="fluc_db" ref_id="Seg6prot2A"
MGRMAMKWLVVIICFSITSQPASACNLKTCLKLFNNTDAVTVHCFNENQGYMLTLASLGL
GIITMLYLLVKIIIELVNGFVLGRWERWCGDIKTTIMPEIDSMEKDIALSRERLDLGEDA
PDETDNSPIPFSNDGIFEI*
