========================================================================================================================

gene_id            %id    %sim   %cov   %t5   %gap  %t3   start..stop      pep sz ref sz ref id            definition
gi_298354674.1     100.0  100.0  99.6   0.0   0.0   0.4   26..748          241    242    Seg6prot1A        CM1 | CM1 protein
                                                          982..982                                         
                    missing exon 2

CLUSTAL 2.1 multiple sequence alignment


predicted       MAHEILIAETEAFLKNVAPETRTAIISAITGGKSACKSAAKLIKNEHLPLMSGEATTMHI
reference       MAHEILIAETEAFLKNVAPETRTAIISAITGGKSACKSAAKLIKNEHLPLMSGEATTMHI
                ************************************************************

predicted       VMRCLYPEIKPWKKASDMLNKATSSLKKSEGRDIRKQMKAAGDFLGVESMMKMRAFRDDQ
reference       VMRCLYPEIKPWKKASDMLNKATSSLKKSEGRDIRKQMKAAGDFLGVESMMKMRAFRDDQ
                ************************************************************

predicted       IMEMVEEVYDHPDDYTPDIRIGTITAWLRCKNKKSERYRSNVSESGRTALKIHEVRKAST
reference       IMEMVEEVYDHPDDYTPDIRIGTITAWLRCKNKKSERYRSNVSESGRTALKIHEVRKAST
                ************************************************************

predicted       AMNEIAGITGLGEEALSLQRQTESLAILCNHTFGSNIMRPHLEKAIKGVEGRVGEMGRMA
reference       AMNEIAGITGLGEEALSLQRQTESLAILCNHTFGSNIMRPHLEKAIKGVEGRVGEMGRMA
                ************************************************************

predicted       M-
reference       MK
                *

>gi_298354674.1	26	982
agcagaagcaggggatttcaaaacaATGGCACATGAAATACTGATTGCTGAAACAGAGGC
ATTTCTAAAAAATGTTGCTCCTGAGACCAGGACAGCAATAATTTCAGCAATAACAGGAGG
AAAATCAGCCTGCAAATCAGCAGCTAAACTGATTAAGAATGAACATCTTCCCCTAATGTC
TGGAGAAGCCACCACAATGCACATCGTTATGAGGTGCTTATATCCTGAAATAAAACCATG
GAAAAAGGCAAGCGACATGCTGAATAAAGCAACTTCTAGTTTGAAAAAATCAGAAGGAAG
AGACATAAGAAAGCAAATGAAAGCAGCTGGAGACTTCTTGGGAGTGGAGTCAATGATGAA
AATGAGGGCCTTCAGAGATGACCAAATAATGGAAATGGTTGAAGAAGTATATGATCACCC
AGACGACTACACACCAGACATCCGAATAGGAACAATCACAGCTTGGTTGAGATGCAAAAA
CAAGAAAAGTGAAAGATACAGGAGTAATGTCTCAGAAAGTGGAAGAACAGCTTTAAAAAT
TCATGAAGTAAGAAAAGCCAGCACAGCAATGAACGAGATTGCTGGTATTACTGGCCTTGG
AGAAGAAGCACTATCTCTCCAAAGACAAACAGAAAGTTTGGCCATATTATGTAATCACAC
TTTTGGAAGTAATATAATGAGACCCCACTTGGAAAAAGCAATAAAAGGAGTTGAAGGCAG
AGTTGGAGAGATGGGACGAATGGCAATGaaatggttagttgttataatatgtttctctat
aacaagtcaacctgcttctgcttgcaatctaaagacctgtctaaaactatttaacaatac
tgatgcggtaactgttcattgttttaatgaaaaccaaggatacatgctaacattagcctc
tttgggattagggataattactatgttgtatttattagtaaaaatcataattgaacttgt
caatggttttgtgctcggcagAtgggagagatggtgtggagatataaagaccacaattat
gcctgaaattgactcgatggaaaaagatattgccctttctagggagagacttgacctggg
agaggatgctcctgacgaaaccgacaactcaccaattcctttttccaatgatggtatttt
tgaaatttaattaccttgaaaaaatccccttgctactgct

Length = 242

Score =   567 bits (1232), Expect = e-166
Identities = 242/242 (100%), Positives = 242/242 (100%)
Frame = +2

Query: 26  MAHEILIAETEAFLKNVAPETRTAIISAITGGKSACKSAAKLIKNEHLPLMSGEATTMHI 205
           MAHEILIAETEAFLKNVAPETRTAIISAITGGKSACKSAAKLIKNEHLPLMSGEATTMHI
Sbjct: 1   MAHEILIAETEAFLKNVAPETRTAIISAITGGKSACKSAAKLIKNEHLPLMSGEATTMHI 60

Query: 206 VMRCLYPEIKPWKKASDMLNKATSSLKKSEGRDIRKQMKAAGDFLGVESMMKMRAFRDDQ 385
           VMRCLYPEIKPWKKASDMLNKATSSLKKSEGRDIRKQMKAAGDFLGVESMMKMRAFRDDQ
Sbjct: 61  VMRCLYPEIKPWKKASDMLNKATSSLKKSEGRDIRKQMKAAGDFLGVESMMKMRAFRDDQ 120

Query: 386 IMEMVEEVYDHPDDYTPDIRIGTITAWLRCKNKKSERYRSNVSESGRTALKIHEVRKAST 565
           IMEMVEEVYDHPDDYTPDIRIGTITAWLRCKNKKSERYRSNVSESGRTALKIHEVRKAST
Sbjct: 121 IMEMVEEVYDHPDDYTPDIRIGTITAWLRCKNKKSERYRSNVSESGRTALKIHEVRKAST 180

Query: 566 AMNEIAGITGLGEEALSLQRQTESLAILCNHTFGSNIMRPHLEKAIKGVEGRVGEMGRMA 745
           AMNEIAGITGLGEEALSLQRQTESLAILCNHTFGSNIMRPHLEKAIKGVEGRVGEMGRMA
Sbjct: 181 AMNEIAGITGLGEEALSLQRQTESLAILCNHTFGSNIMRPHLEKAIKGVEGRVGEMGRMA 240

Query: 746 MK 751
           MK
Sbjct: 241 MK 242


