========================================================================================================================

gene_id            %id    %sim   %cov   %t5   %gap  %t3   start..stop      pep sz ref sz ref id            definition
37.34              81.7   96.3   93.8   6.3   0.0   0.0   31977..31795     60     64     AAT97515.1        E4-7 | E4 7.4 kDa protein
                    could not find valid start codon

CLUSTAL 2.1 multiple sequence alignment


predicted       ----PDGFLSITDPRLARSETVWNVESKTMSISNGIQMFKAVRGERLVYSVKWEGGGKIT
reference       MQECPEGFISLTDPRLSRSETVWNVEIKTMSITNSIQMFKAVRGERIVYSMRWEGGGKIT
                    *:**:*:*****:********* *****:*.***********:***::********

predicted       TRSL
reference       TRIL
                ** *

>37.37	31977	31795
acagcggctgcttgtgggtttgatgagacacaatcgcccgatcccgttttcggattatga
ttcccatcgttcttcttccagatgaccgtgatccagactccggagtcgcatccgcagcag
ttggactgtgaaagcgctttaaaagactatCCCGATGGATTTTTATCTATCACTGACCCC
AGATTGGCTCGCTCTGAAACTGTTTGGAATGTGGAATCTAAAACCATGTCTATCTCTAAT
GGTATCCAAATGTTTAAAGCTGTGCGTGGGGAGAGATTGGTATATTCTGTTAAATGGGAA
GGGGGAGGCAAAATAACTACTCGAAGTTTGTGAattgattttcaaataaacaagttaaac
tttatttgtcagtcgtcttctctgatgtagtaaaaggtaaatggggaggtaactagggtt
gtagcagaggtttgcccctctggggcatctcctgtgttccaggaccaagttatacgaata
caa

Length = 64

Score =   127 bits (271), Expect = 8e-35
Identities = 49/64 (76%), Positives = 60/64 (93%)
Frame = -3

Query: 31989 LKDYPDGFLSITDPRLARSETVWNVESKTMSISNGIQMFKAVRGERLVYSVKWEGGGKIT 31810
             +++ P+GF+S+TDPRL+RSETVWNVE KTMSI+N IQMFKAVRGER+VYS++WEGGGKIT
Sbjct: 1     MQECPEGFISLTDPRLSRSETVWNVEIKTMSITNSIQMFKAVRGERIVYSMRWEGGGKIT 60

Query: 31809 TRSL 31798
             TR L
Sbjct: 61    TRIL 64


========================================================================================================================

gene_id            %id    %sim   %cov   %t5   %gap  %t3   start..stop      pep sz ref sz ref id            definition
57.6               70.6   83.1   96.2   3.8   0.0   0.0   5968..6276       102    106    ABR27497.1        HYP-5 | hypothetical protein
                    could not find valid start codon

CLUSTAL 2.1 multiple sequence alignment


predicted       ----VWFLSLSARSFAAILSCTYSRAMHFQVGKTVVRSSGNNRRRHPRLCSVTKSTLVTT
reference       MERMVWFFSLSARSLAAMLSCTYSRATHFHSGKTVVSSSGTILTCQPRLCRVMRSTLVAT
                    ***:******:**:******** **: ***** ***.    :**** * :****:*

predicted       SPRKLSLVQAKRPPFREQKGGRTSSWFSSGGSASTVKMPGHKILSK
reference       SPRRGSLVQQRRPPLREQKGGRGSSISSSGGSASMVKMPGRRSGSK
                ***: **** :***:******* **  ******* *****::  **

>57.8	5968	6276
gatgaggatttgatgtgcaaacggcccgctgcaatttcttttatgagcccctcttccatt
tgatcagaaaaaacaatttttttgttatctaattttgtagcaaaggatccgtacagggcg
tttgaaagtaacttggctatagatcttagcGTTTGGTTTTTGTCCCTGTCTGCCCGTTCT
TTTGCGGCGATATTGAGTTGTACATATTCACGAGCAATGCATTTCCAAGTGGGAAAAACG
GTGGTACGTTCGTCTGGTAATAATCGCAGACGCCACCCGCGATTATGCAGTGTAACTAAG
TCTACACTGGTGACCACTTCGCCGCGCAAGCTCTCATTAGTCCAGGCTAAACGACCGCCT
TTTCGAGAGCAAAAAGGAGGAAGAACATCCAGCTGGTTTTCGTCTGGAGGATCAGCATCC
ACAGTAAAAATGCCAGGACATAAAATTTTATCAAAATAAtcaattttggaagtaagattt
tcaagtgccacctgccactgccgtacggctaatgctcgttcgtaagggttaagaggagga
ccccaaggcatagggtgtgtaagggctgatgcatacatgccacaaatatcatatacatat
atgggttcc

Length = 106

Score =   158 bits (339), Expect = 8e-44
Identities = 72/102 (70%), Positives = 77/102 (75%)
Frame = +1

Query: 5968 VWFLSLSARSFAAILSCTYSRAMHFQVGKTVVRSSGNNRRRHPRLCSVTKSTLVTTSPRK 6147
            VWF SLSARS AA+LSCTYSRA HF  GKTVV SSG      PRLC V +STLV TSPR+
Sbjct: 5    VWFFSLSARSLAAMLSCTYSRATHFHSGKTVVSSSGTILTCQPRLCRVMRSTLVATSPRR 64

Query: 6148 LSLVQAKRPPFREQKGGRTSSWFSSGGSASTVKMPGHKILSK 6273
             SLVQ +RPP REQKGGR SS  SSGGSAS VKMPG +  SK
Sbjct: 65   GSLVQQRRPPLREQKGGRGSSISSSGGSASMVKMPGRRSGSK 106


========================================================================================================================

gene_id            %id    %sim   %cov   %t5   %gap  %t3   start..stop      pep sz ref sz ref id            definition
57.8               74.6   89.5   99.5   0.5   0.0   0.0   <10117..8222     631    647    AAS10397.1        pTP | putative DNA terminal protein, C-terminal
                    missing exon 1

CLUSTAL 2.1 multiple sequence alignment


predicted       ---SIQDCARLTGQSVPTIERFLPLRNIWNQVRQFARATTTAAGITWMSRYIYEYHRLML
reference       MALSIHDCARLTGQTAATMNYFLPLRNIWNRVREFPRASTTAAGITWMSRYIYGYHRLML
                   **:********:..*:: *********:**:*.**:************** ******

predicted       EDLAPGAAATLRWPLYQEPPPHFLVGYQYLVRACNDYVFDSRAYSRIRYTETIQPGVHTV
reference       EDLAPGAPATERWPLYRQPPPHFLVGYQYLVRACNDYIFDTRAYSRLKYHELVRPGHQTV
                *******.** *****::*******************:**:*****::* * ::** :**

predicted       NWSVMTNCSYTINTGAYHRFVDMDDFENTLTQIQQAVLAERVVADLALLQPLQGYGATHM
reference       NWSVMANCSYTINTGAYHRFVDFDDFQTTLTQIQQAILTERVVADLALVQPQRGFGLTRM
                *****:****************:***:.********:*:*********:** :*:* *:*

predicted       ADRQ-DREIPVERLMHDYYKDLGRCQSSVWGMADRLRVQQAGPKDVVLLKTIRRLKTAYF
reference       HGRAGEEEVPVERLMQDYYKDLARCQDHAWGMADRLRIQQAGPKDLVLLATIRRLRTAYF
                 .*  :.*:******:******.***. .********:*******:*** *****:****

predicted       NYMISNIVQHPGD----SQQTKLSLPCDCDWIDAFLERFSDPVDMQSLRSWRGVSTQQII
reference       NFITSSIARPPPDQIPEEQETGLSLPCDCDWLEAFVQRFSDPVDLETLRSLRGVPTGQLI
                *:: *.*.: * *    .*:* *********::**::*******:::*** ***.* *:*

predicted       KCIVSAVSLPN-APRNAFPTLQLRGGLFELRPRENGRAVTETMRRRRGEMIERFVDRLPV
reference       RCIVSALSLPNGDPPGGH--LEMRGGVFMLRPREDGRAVTETMRRRRGETIERFIDRLPV
                :*****:****  * ...  *::***:* *****:************** ****:*****

predicted       RRRRRRLPSPPAVQEE---TMEVEEEQE--EEEAPEAFALEVRHTVAEIIRLLEEELTVA
reference       RRRRRRAPPPPPPPEEEVEEMLVEEEEEEMEEEPPGAFEREVRATIAELIRLLEEELTVS
                ****** *.**.  **    * ****:*  ***.* **  *** *:**:**********:

predicted       ARNSQFFTFAVDFYEAMERLEALGDINELTLRRWILYFFVSEHIATTLNYLFQRLRNYGV
reference       ARNSQFFNFAVDFYEAMERLEALGDVSEMPLRRWIMYFFVTEHIATTLNYLYQRLCNYAV
                *******.*****************:.*:.*****:****:**********:*** **.*

predicted       FARFVELNLAQVVMRARDSDGGVVYSRVWNETGLNAFSQLMGRISNDLAATIERAGHGDL
reference       FTRHVELNLAQVVMRARDPDGAVVYSRVWNEAGMNAFSQLMGRISNDLAATVERAGRGDL
                *:*.**************.**.*********:*:*****************:****:***

predicted       QEEEIDQLMAEIAYQDNSGDIQEILRQAAVNDTEIDSVELSFRFKTTGPVVFTQRRQIQN
reference       QEEEIEQFMTEIAYQDNSGDVQEILRQAAVNDTEIDSVELSFRFKLTGPVAFTQRRQIQD
                *****:*:*:**********:************************ ****.********:

predicted       INRRVVAHASQLRAQHLPLPERQADIRLPQAPAEAEVPVP----ARRRF
reference       VNRRVVAHASLLRAQYQNLPARGADVPLPPLPPGPEPPLPPGARPRRRF
                :********* ****:  ** * **: **  *. .* *:*    .****

>57.10	10117	8222
tggctgggttccacgcgcagacgccctatatacgctcacagcggatcctgccggtttcga
accggggttcctcgctgtggtacccttgtgacttttccgccaggccacagaggggagtcg
cttaccgactttcattttctttacatctagAGCATTCAAGACTGCGCACGCCTCACCGGT
CAAAGCGTCCCAACCATTGAACGCTTTTTACCCCTGCGCAACATTTGGAACCAAGTTCGC
CAGTTTGCCCGGGCAACAACCACTGCCGCCGGCATCACGTGGATGTCCAGATACATATAT
GAATACCACCGCCTCATGTTAGAAGACCTTGCTCCCGGTGCGGCGGCTACACTTCGGTGG
CCGTTATATCAAGAACCTCCTCCTCATTTTCTAGTGGGCTATCAGTATTTGGTGCGCGCT
TGCAACGATTATGTTTTTGACTCTCGAGCTTACTCGCGCATACGATACACAGAAACCATA
CAGCCAGGTGTCCACACTGTTAATTGGTCAGTAATGACCAACTGCAGTTACACCATTAAT
ACAGGAGCTTACCACCGCTTTGTAGATATGGATGACTTTGAAAATACTCTTACCCAAATA
CAGCAGGCAGTACTTGCTGAACGGGTAGTTGCAGATTTAGCTTTATTGCAACCATTACAA
GGCTATGGTGCAACGCACATGGCTGATCGCCAAGACCGCGAAATACCAGTGGAAAGGCTC
ATGCACGACTACTACAAAGATCTTGGACGTTGTCAAAGTAGTGTGTGGGGAATGGCAGAC
CGCCTGCGAGTTCAACAAGCCGGACCAAAAGACGTGGTGCTTCTTAAAACCATCCGCAGA
CTTAAAACAGCCTATTTTAATTACATGATTAGCAACATAGTTCAACATCCCGGTGATTCA
CAGCAAACAAAACTTAGCCTACCTTGTGACTGTGACTGGATTGACGCCTTCCTTGAAAGG
TTTTCCGACCCAGTAGATATGCAGTCGCTTAGGTCCTGGCGCGGAGTTTCTACGCAACAA
ATCATAAAATGCATAGTAAGTGCTGTGTCGCTACCAAACGCACCTCGCAACGCATTTCCT
ACCCTACAACTAAGGGGTGGACTTTTCGAGCTTCGCCCGCGTGAAAATGGTCGAGCAGTG
ACGGAAACTATGCGCCGCCGCCGGGGCGAAATGATTGAAAGGTTTGTAGACAGGCTGCCC
GTTCGCCGGCGACGAAGAAGGCTACCCTCTCCGCCCGCGGTTCAAGAAGAAACAATGGAA
GTAGAAGAGGAACAGGAAGAAGAAGAAGCCCCGGAGGCTTTCGCGCTTGAAGTGCGCCAC
ACGGTGGCTGAAATTATTCGTCTTTTAGAAGAAGAATTAACTGTTGCAGCTCGAAACTCC
CAGTTTTTTACTTTTGCAGTTGACTTCTACGAAGCCATGGAACGTTTGGAAGCTCTGGGA
GACATCAACGAGCTCACGCTTCGTCGGTGGATTCTTTATTTTTTTGTTTCAGAACACATA
GCTACTACCTTAAACTACCTGTTTCAGCGTTTACGCAACTACGGTGTGTTCGCGCGCTTC
GTGGAACTTAACTTGGCGCAAGTGGTTATGCGTGCCAGAGACAGCGACGGAGGAGTTGTG
TACAGCCGCGTCTGGAACGAAACTGGACTTAACGCATTTTCACAGCTTATGGGACGCATA
TCTAATGACCTTGCAGCTACCATTGAACGAGCGGGTCATGGAGATCTCCAGGAGGAAGAA
ATTGATCAACTAATGGCAGAAATTGCCTACCAAGATAACTCAGGGGATATTCAGGAAATT
TTGAGGCAGGCTGCAGTAAATGACACTGAAATTGATTCTGTTGAACTTTCTTTCAGGTTC
AAAACAACGGGACCAGTGGTGTTTACACAACGTCGGCAAATTCAGAACATCAATCGTCGT
GTCGTCGCCCATGCCAGTCAACTACGGGCTCAGCACCTTCCACTACCAGAACGTCAGGCC
GACATACGACTGCCTCAAGCTCCCGCAGAAGCGGAAGTCCCAGTTCCTGCACGCCGTCGC
TTTTAAgcaggcgtgttgctcaccgcggaacagtaattgcacctcgggcttacggcacac
tgcacgcaatagattctaccgatggcactccgcttgaaattaagtatcaccttcacctac
ggcctgctcttacccgcctttgtgaagttaacttgc

Length = 647

Score =   359 bits (778), Expect(4) = 0.0
Identities = 141/184 (76%), Positives = 159/184 (86%)
Frame = -1

Query: 10117 SIQDCARLTGQSVPTIERFLPLRNIWNQVRQFARATTTAAGITWMSRYIYEYHRLMLEDL 9938
             SI DCARLTGQ+  T+  FLPLRNIWN+VR+F RA+TTAAGITWMSRYIY YHRLMLEDL
Sbjct: 4     SIHDCARLTGQTAATMNYFLPLRNIWNRVREFPRASTTAAGITWMSRYIYGYHRLMLEDL 63

Query: 9937  APGAAATLRWPLYQEPPPHFLVGYQYLVRACNDYVFDSRAYSRIRYTETIQPGVHTVNWS 9758
             APGA AT RWPLY++PPPHFLVGYQYLVRACNDY+FD+RAYSR++Y E ++PG  TVNWS
Sbjct: 64    APGAPATERWPLYRQPPPHFLVGYQYLVRACNDYIFDTRAYSRLKYHELVRPGHQTVNWS 123

Query: 9757  VMTNCSYTINTGAYHRFVDMDDFENTLTQIQQAVLAERVVADLALLQPLQGYGATHMADR 9578
             VM NCSYTINTGAYHRFVD DDF+ TLTQIQQA+L ERVVADLAL+QP +G+G T M  R
Sbjct: 124   VMANCSYTINTGAYHRFVDFDDFQTTLTQIQQAILTERVVADLALVQPQRGFGLTRMHGR 183

Query: 9577  QDRE 9566
                E
Sbjct: 184   AGEE 187

Score =   125 bits (267), Expect(4) = 0.0
Identities = 48/68 (70%), Positives = 57/68 (83%)
Frame = -1

Query: 9574  DREIPVERLMHDYYKDLGRCQSSVWGMADRLRVQQAGPKDVVLLKTIRRLKTAYFNYMIS 9395
             + E+PVERLM DYYKDL RCQ   WGMADRLR+QQAGPKD+VLL TIRRL+TAYFN++ S
Sbjct: 186   EEEVPVERLMQDYYKDLARCQDHAWGMADRLRIQQAGPKDLVLLATIRRLRTAYFNFITS 245

Query: 9394  NIVQHPGD 9371
             +I + P D
Sbjct: 246   SIARPPPD 253

Score =   103 bits (220), Expect(4) = 0.0
Identities = 38/55 (69%), Positives = 50/55 (90%)
Frame = -1

Query: 9373  DSQQTKLSLPCDCDWIDAFLERFSDPVDMQSLRSWRGVSTQQIIKCIVSAVSLPN 9209
             + Q+T LSLPCDCDW++AF++RFSDPVD+++LRS RGV T Q+I+CIVSA+SLPN
Sbjct: 257   EEQETGLSLPCDCDWLEAFVQRFSDPVDLETLRSLRGVPTGQLIRCIVSALSLPN 311

Score =   117 bits (250), Expect = 4e-30
Identities = 50/71 (70%), Positives = 57/71 (80%)
Frame = -1

Query: 9184  LQLRGGLFELRPRENGRAVTETMRRRRGEMIERFVDRLPVRRRRRRLPSPPAVQEETMEV 9005
             L++RGG+F LRPRE+GRAVTETMRRRRGE IERF+DRLPVRRRRRR P PP   EE +E 
Sbjct: 319   LEMRGGVFMLRPREDGRAVTETMRRRRGETIERFIDRLPVRRRRRRAPPPPPPPEEEVEE 378

Query: 9004  EEEQEEEEAPE 8972
                +EEEE  E
Sbjct: 379   MLVEEEEEEME 389

Score =   485 bits (1053), Expect(4) = 0.0
Identities = 209/272 (76%), Positives = 230/272 (84%)
Frame = -1

Query: 9043  PSPPAVQEETMEVEEEQEEEEAPEAFALEVRHTVAEIIRLLEEELTVAARNSQFFTFAVD 8864
             P    V+E  +E EEE+ EEE P AF  EVR T+AE+IRLLEEELTV+ARNSQFF FAVD
Sbjct: 371   PPEEEVEEMLVEEEEEEMEEEPPGAFEREVRATIAELIRLLEEELTVSARNSQFFNFAVD 430

Query: 8863  FYEAMERLEALGDINELTLRRWILYFFVSEHIATTLNYLFQRLRNYGVFARFVELNLAQV 8684
             FYEAMERLEALGD++E+ LRRWI+YFFV+EHIATTLNYL+QRL NY VF R VELNLAQV
Sbjct: 431   FYEAMERLEALGDVSEMPLRRWIMYFFVTEHIATTLNYLYQRLCNYAVFTRHVELNLAQV 490

Query: 8683  VMRARDSDGGVVYSRVWNETGLNAFSQLMGRISNDLAATIERAGHGDLQEEEIDQLMAEI 8504
             VMRARD DG VVYSRVWNE G+NAFSQLMGRISNDLAAT+ERAG GDLQEEEI+Q M EI
Sbjct: 491   VMRARDPDGAVVYSRVWNEAGMNAFSQLMGRISNDLAATVERAGRGDLQEEEIEQFMTEI 550

Query: 8503  AYQDNSGDIQEILRQAAVNDTEIDSVELSFRFKTTGPVVFTQRRQIQNINRRVVAHASQL 8324
             AYQDNSGD+QEILRQAAVNDTEIDSVELSFRFK TGPV FTQRRQIQ++NRRVVAHAS L
Sbjct: 551   AYQDNSGDVQEILRQAAVNDTEIDSVELSFRFKLTGPVAFTQRRQIQDVNRRVVAHASLL 610

Query: 8323  RAQHLPLPERQADIRLPQAPAEAEVPVPARRR 8228
             RAQ+  LP R AD+ LP  P   E P+P   R
Sbjct: 611   RAQYQNLPARGADVPLPPLPPGPEPPLPPGAR 642


========================================================================================================================

gene_id            %id    %sim   %cov   %t5   %gap  %t3   start..stop      pep sz ref sz ref id            definition
64.8               84.0   88.4   100.0  0.0   0.0   0.0   6067..6387       106    106    ABR27497.1        HYP-5 | hypothetical protein
                    stop codon embedded in CDS at 6082..6084

CLUSTAL 2.1 multiple sequence alignment


predicted       MDLMVXFLSRSARSLAAMLSWTYSRATHFHSGKTVVRSSGTILTRQPRLCRVTRSTLVAT
reference       MERMVWFFSLSARSLAAMLSCTYSRATHFHSGKTVVSSSGTILTCQPRLCRVMRSTLVAT
                *: ** *:* ********** *************** ******* ******* *******

predicted       SPRRGSLVQQRRPPLREQNGGSTSSRCSSGGSASMVKMPGQSSLSK
reference       SPRRGSLVQQRRPPLREQKGGRGSSISSSGGSASMVKMPGRRSGSK
                ******************:**  ** .*************: * **

>64.9	6067	6387
gtttctagaaacgaggaggatttgatgttggcctgccctgccgcaatgctttttaggaga
ctttcatccatctggtcagaaaagactatttttttattgtcaagcttggtggcaaaggag
ccatagagggcgttggagagaagcttggcgATGGATCTCATGGTCTGATTTTTGTCACGG
TCGGCGCGCTCCTTGGCCGCGATGTTGAGCTGGACATACTCGCGCGCGACACACTTCCAT
TCTGGGAAGACGGTGGTGCGCTCGTCGGGCACGATCCTGACGCGCCAGCCGCGATTATGC
AGGGTGACCAGGTCCACGCTGGTGGCCACCTCGCCGCGCAGGGGCTCGTTGGTCCAGCAG
AGGCGTCCGCCCTTGCGCGAGCAGAACGGGGGCAGCACATCAAGCAGATGCTCGTCAGGG
GGGTCCGCATCGATGGTGAAGATGCCCGGACAGAGTTCCTTGTCAAAATAAtcgattttt
gaggatgcatcatccaaggccatctgccactcgcgggcggccagcgctcgctcgtagggg
ttgaggggcggaccccagggcatgggatgcgtgagggcggaggcgtacatgccgcagatg
tcgtagacatagatgggctcc

Length = 106

Score =   192 bits (413), Expect = 5e-54
Identities = 89/106 (83%), Positives = 91/106 (85%)
Frame = +1

Query: 6067 MDLMV*FLSRSARSLAAMLSWTYSRATHFHSGKTVVRSSGTILTRQPRLCRVTRSTLVAT 6246
            M+ MV F S SARSLAAMLS TYSRATHFHSGKTVV SSGTILT QPRLCRV RSTLVAT
Sbjct: 1    MERMVWFFSLSARSLAAMLSCTYSRATHFHSGKTVVSSSGTILTCQPRLCRVMRSTLVAT 60

Query: 6247 SPRRGSLVQQRRPPLREQNGGSTSSRCSSGGSASMVKMPGQSSLSK 6384
            SPRRGSLVQQRRPPLREQ GG  SS  SSGGSASMVKMPG+ S SK
Sbjct: 61   SPRRGSLVQQRRPPLREQKGGRGSSISSSGGSASMVKMPGRRSGSK 106


========================================================================================================================

gene_id            %id    %sim   %cov   %t5   %gap  %t3   start..stop      pep sz ref sz ref id            definition
64.12              80.2   91.1   100.0  0.0   0.0   0.0   13472..13460     1186   1193   YP_068023.1       E2B | DNA polymerase
                                                          8521..4974                                       
                    stop codons embedded in CDS at 8519..8517 and 8510..8508

CLUSTAL 2.1 multiple sequence alignment


predicted       MALVNXFCXTVFQVQSHGARGLHAKAADPGCQPPRRRARQRSQGAAPGPARAPRRRASTA
reference       MALV----------QTHGSRGLHPEASDPGRQPSRRRSRQSSPGAVPEPARARRRRAPAT
                ****          *:**:****.:*:*** **.***:** * **.* **** ****.::

predicted       TARGAGTAAAAGSASATPLL----------KAHRGTVVAPRSYGLMQCVDTTTNSPVEIK
reference       TASGSRAAPTARRASSPPLLTMEAKPLPPAKKKRGTVVTPQGHGTLQAIDVATNGAVEIK
                ** *: :*.:*  **:.***          * :*****:*:.:* :*.:*.:**..****

predicted       YHLHLKHALTRLYEVN-LRTLPPDLDLR--DTMDSSQLRALVFALRPRRAEIWTWLPRGL
reference       YHLDLPRALEKLLQVNRAPPLPTDLTPQRLRTLDSSGLRALVLALRPVRAEVWTCLPRGL
                ***.* :** :* :**   .**.**  :   *:*** *****:**** ***:** *****

predicted       VSLSVLEEPQGESHAGEHENHQPGPP----LLKFLLKGRAVYLVDEVQPVQRCEYCGRFY
reference       VSMTTIEAEEGQADHHDVVQHQMQAPRLHFPLKFLVKGTQVQLVQHVHPVQRCEHCGRLY
                **::.:*  :*::.  :  :**  .*     ****:**  * **:.*:******:***:*

predicted       KHQHECSVRRRDFYFHHINSHSTNWWQEIQFFPIGSHPRTERLFVTYDVETYTWMGSFGK
reference       KHKHECSARRRHFYFHHINSHSSNWWQEIQFFPIGSHPRTERLFLTYDVETYTWMGSFGK
                **:****.***.**********:*********************:***************

predicted       QLVPFMLVMKFSGDPELVALARDLAVRLRWDRWERDPLTFYCVTPEKMAVGQQFRLFRDE
reference       QLVPFMLVMKLSGDDRLVELALDLALQLKWDRWHGDPRTFYCVTPEKMAVGQQFRQYRDR
                **********:*** .** ** ***::*:****. ** ***************** :**.

predicted       LQTLMARELWASFMQANPHLQEWALEQHGLQCPEDLTYEELKKLPHIKGRPRFMELYIVG
reference       LQTALAVDLWTSFLRANPHLADWALEQHGLSDPDELTYEELKKLPHVKGRPRFVELYIVG
                *** :* :**:**::***** :********. *::***********:******:******

predicted       HNINGFDEIVLAAQVINNRASVPGPFRITRNFMPRAGKILFNDVTFALPNPLSKKRTDFE
reference       HNINGFDEIVLAAQVINNRAEVPQPFRITRNFMPRAGKILFNDVTFALPNPAYKKRTDFQ
                ********************.** ***************************  ******:

predicted       LWEHGGCDDSDFKYQFLKVMVRDTFALTHTSLRKAAQAYALPVEKGCCPYKAVNHFYMLG
reference       LWEQGGCDDIDFKHQFLKVMVRDTFALTHTSLRKAAQAYALPVEKGCCAYKAVNQFYMLG
                ***:***** ***:**********************************.*****:*****

predicted       SYRADDRGFPLREYWKDDEEYALNRALWEKKEEAGYDIIRETLDYCAMDVLVTAELVAKL
reference       SYRADQDGFPLEEYWKDREEFLLNRELWKQKGQLKYDIIQETLDYCALDVLVTAELVAKL
                *****: ****.***** **: *** **::* :  ****:*******:************

predicted       QDSYAHFIRDSVRLPHAHFNIFQRPTISSNSHAIFRQIVFRAEQPQRTNLGPAFLAPSHE
reference       QDSYAHFIRDSVGLPHAHFNIFQRPTISSNSHAIFRQIVYRAEKPSRANLGAGLLAPSHE
                ************ **************************:***:*.*:***..:******

predicted       LYDYVRASIRGGRCYPTYIGILSEPIYVYDICGMYASALTHPMPWGPPLNPYERALAARE
reference       LYDYVRASIRGGRCYPTYIGILDEPLYVYDICGMYASALTHPMPWGTPLSPYERALAVRE
                **********************.**:********************.**.*******.**

predicted       WQMALDDASSKIDYFDKELCPGIFTIDADPPDEHLLDVLPPFCSRKGGRLCWTNEPLRGE
reference       WQASLDDLGTCISYFDPDLLPGIFTIDADPPDELMLDPLPPFCSRKGGRLCWTNEPLRGE
                ** :*** .: *.*** :* ************* :** **********************

predicted       VATSVDLVTLHNRGWRVRIVPDERTTVFPEWKCVAREYVQLNIAAKERADRDKNQTMRSI
reference       VATSVDLITLHNRGWQVRIVPDELTTVFPEWKCVAREYVQLNIAAKERADKEKNQTMRSI
                *******:*******:******* **************************::********

predicted       AKLLSNALYGSFATKLDNKKIVFSDQMDESLLKSIAAGQANIKSSSFLETDNLSAEVMPA
reference       AKLLSNALYGSFATKLDNKKIVFSDQMDEGLLKGISAGTVNIKSSSFLETDNLSAEVMPA
                *****************************.***.*:** .********************

predicted       LEREYLPQQLALVDSDAEESEDEHRPAPFYTPPSGTPGHVAYTYKPITFLDAEEGDMCLH
reference       FEREYLPQQLALLDSDPEDSEDEQRPAPFYTPPAGTPGHVAYTYKPITFLDVDEGDMCLH
                :***********:***.*:****:*********:*****************.:*******

predicted       TVEKVDPLVDNDRYPSHVASFVLAWTRAFVSEWSEFLYEEDRGTPLQDRPIKSVYGDTDS
reference       TLEKVDPLVDNDRYPSHVASFVLAWTRAFVSEWSGFLYDEDRGVPLEDRPIKSVYGDTDS
                *:******************************** ***:****.**:*************

predicted       LFVTERGHRLMETRGKKRIKKNGGKLVFDPEQPELTWLVECETVCAHCGADAFAPESVFL
reference       LFVTQRGHELMETRGKKRIKKNGGKLVFDPNQPDLTWLVECETVCAHCGADAYAPESVFL
                ****:***.*********************:**:******************:*******

predicted       APKLYALQSLLCPACGRSSKGKLRAKGHAAEALNYKLMVNCYLADAQGEDRARFSTSRMS
reference       APKLYALKSLLCPACGQTSKGKLRAKGHAAEALNYELMVNCYLADAQGADRERFSTSRMS
                *******:********::*****************:************ ** ********

predicted       LKRTLASAQPGAHPFTVTETTLTRTLRPWKDMTLAALDAHRLVPYSRSRPNPRNEEVCWI
reference       LKRTLASAQPGAHPFTVTETTLTRTLRPWKDRTLAALDAHRLAPYSRSRPNPRNEEVCWI
                ******************************* **********.*****************

predicted       EMP
reference       EMP
                ***

>64.7	13472	4974
tgctgtttctgccctccgtaggagccatataccgcggaggcacaaacggaacctccaggg
tcgcctgcgccatcacgctctcgtacgagggaggaggagaggaagacaccaccgcgcgcc
tcatctctaacaaggaagagaacgcacgctATGGCCTTGGTGAgttttattttgcattca
aaacatccgtcgccccagtctgggctgcagatgcgcgaacgggttggccccaccgctccc
gcccaagtccaacacgctgctatcgtcggccgagtcctcgtcgtcccacaccaggccccg
ctgccggtcgtgacgctgtcgccgcggcgcgggcgcaggttccctatggtcctgagcgta
ggttttccagcggttcagtttgtccaccagactctctatcccgttattgaccatggcgtt
cttgacccgcggcggctgcagcagcgagtcgttcaggtactcgtcctcgcccagcaagcg
cggccggctcaccctgccgctgttcaccgagcccggcaagctatgcaaactccctaagct
aggaaaggggctccgacccaccgcgccctcgctcgcgggcgtgcgcaccgcctcctggcg
cttttgcaaggtcggtgagaacaccgcgctgtccacgtcgtcccacaaaaacccgtcgtt
ggggtcaggcatgtcgtactcgcccgtgtagaaccccggcggcgggagccagtgcgggtt
caagatggcattggtaaagtagtccgagttcatggacgccgcgcggtgcaggtagtccat
cagcttattaataaacggccggttggcggcgtacatgctaggttccatgttgcgcgcggt
catgtccagcgcggcgctgggggtggccccctcctgcatcaggaacagccctacgctctg
ctgcacatatctcaggatgcgctcctcctcggccgacagcgcgtactgcgccgggatctt
ctgctgtctattggtcagcaagaagttcagggtggccctcagactgtcggtgtcgttctg
acccagcgcgcggctcacgctagtgatctcctggaaggtctgctcatccacctgcgcctg
gcctatggcctcgcggtacagcgtcagcaggtgacccaggtacgagttgcggttcacgct
gccactgtcggtgaagggcgcgatcagcagcagcagcagccgcgagttgggcgtcagcaa
gctgctcaccgtcgaccggtcgcccacgggcgcctgcacgccccacagcccgcgcaggtt
cttgaaagcctgactcaggttcaccgtctgcaggccctgtctgctcgtctggaaaaagta
gtccgggcccgactggtacacctcgctctggggcacctcggtcaccatcagccgcagcgc
gcttataaagttggtataatcatcctgcccgcgcggcacgttcgccggctgcgtcgccag
gaaggcgttcagcgccaccagcgaacccaggccctcgttcttgaaccgctcgcgctgcgc
cacggcctcgcgcacgtccgtcaccagccggtccaggttggactgcacgtttgtgctgtt
gtagcggcccacgcgctccagcagggcgttgtacactagcccggcctcgtcgggacggat
ggccttgttctccgccagcgcgttcacgatcgccagcaccttctcgtgcgtggggttggt
ccgagaaggaaccaccgcctccagaatggccgagagtctgttggcctgcggctgttgtct
aaaggactcggggttgcgggtcgtcagggccatgatgcgttgcatcgcggcctcccagtc
gtccgatgctagaccggacggctggctttgcagcgccgcccttatggcggggtccggggc
ttgctgcatctaaaaacacatcacggaggcgtcagtaccccgcaacgggtgcatcctcct
cctcttcctcttcctcatccaagtcctctggaccgtaggcggcctccaaggcgcgtcggc
tcggctgccaatgcaggtccgcccccatgtcaaagtaggactcctcaccgccggtggcgc
ctcctaccagcgcccggcgcagactcagcatcagctcgcggtcgctcagctcgcgccgcc
ggcttgtgctcacggccttgtggatgcggtcgttgcggtacacgcccaggtcgtcgctca
gcgtcagcaccttgagcgccatgcgcatgtaaaagctgtctatcttcacctccttgtcta
tgggcacatacggcgtcttgtaaatcttgcgcgcgtaaaacttgcccaggctcagcaccg
agtagttgatcgccgccaccttctcggccaggctcaggctgcgctcctgcactacgatgc
tctgcaagatgttaatcagctccagcagccagcgaccctcgggctcggcgatgttcagca
gtgcctccctgaacgcctcgttgtccctgctgtgctgcaccaccaggaacagctgtgccg
tcagaggcttgctgtccgggttctgcacgatggcctccgccaggtcccacaggtgcatca
ggcccagggccacctcctcgcgcgcgatcagggtgcgcacgtggttgttgaaactctttt
ggaagttgcgctcctgcttcaccgtctgctcgtaggccgtcaccaggttggccgccgcca
cgtgcgcgcgcgcggggctgatccccgtctgctcgttcggctcgaaatcctcgtcgcgca
gcacgcgctggcggtccaggccctcgcgcagctccctgcccgcccgaaaccggcagtcgc
gcatctcctcgggctcctccccgctgcggtccctgaacaggttctgcgcaggcacgtacg
ccgggcgcacgtccttctgcagctgcacgcggggatgtcgctccggggacggcgccccca
gtctcgccagcccttcgccctcttccaagtccatctctgtctgtggctgtggctggctag
cgccggcgcctgctacggccgcggtcgcggtggtcgccgggggggtgggacgcatttggc
gcaggacgggatgcatctggcaaaaagaaaaaagggggctcgctcccgtaactggagaag
tcggctggctgtgggtctttaaatcggcggggtgaccaagtcccgctcgccgcggccgtc
cttgaaccgggttctgccgcgactcaaccctggcgatgcttctccagactacgggcgcga
gccactacccggcagggttttcggccgctttcaagtctagcgactcccctcggccgacaa
aaagggctctccgccgtatcctggcggctatcgggcttgggtcgagacgggagtgccaat
accacgttagtcgcggctccagcctgattcgaggggactcgaaccggggtacacacgcgg
cctaacccgtttgcgttccgccaggctacggaggaagagcccgctcaaccgctttcgttt
ttgcctctagagcatcaatgactgcgcgcgtctcaccggccagaccgtgccgaccatgga
ctatttcctgcccctgcgcaacatctggaaccgcgtccgcgagttcccgcgcgcctccac
caccgccgccggcatcacctggatgtcccgctacctctacggctaccaccgactcatgct
tgaggacctggccccgggcgcgccggccacccagcgctggccgctctaccgccagccgcc
gccgcactttctagtcggataccagtacctcgtgcgcacctgcaacgactatgtcttcga
ctcgcgcgccttctcgcggctcaggtactccgaggtcgtgcaacccggcctgcagaccgt
caactggtcgcttatggccaactgcacttacaccatcaacacaggggcctaccaccgctt
cgtcgacatggacgacttccaggacaccctcacccgcgtgcaacaggccatcctcgccga
gcgcgtcgtcgccgacctggcgctcgtgcagccgttcaggggcgtcggggtcacccgcat
ggaagactccgcctccgccagtgatgacatcgagaggctcatgcatgactactacaagaa
cctgagccggtgtcagggccaggcctggggcatggccgagcggctccgcatccagcaagc
gggacccaaggacctggtcctcctcgccaccatccgccgcctcaaaaacgcctacttcaa
ttacatcatcagcaaccgcaattctaacagcgtccacagggctgctacgtgtttgagctt
accttgcgactgcgattggctagacgctttcctcgaaagattctccgatccggtcgatct
cgacgcgctcacgtgccctacaccgcaattgataagatgcattgtcagcgccctatcgct
gcccaacggggacccaccccattaccgggagatgaccggcggcgtcttcacgctgcgtcc
tcgcgaacggggtcgcgccgtcaccgaaaccatgcgtcgccgccgcggggagatgatcga
gcgcttcgtcgaccgtctcccggtgcgtcgccgtcgtcgtcgggccccgccaccaccacc
gcccccagaggaagaaatagaagaagaggtcgtcatggaagaagaggaagaggaggaggc
ccccggggatttcgagcgcgaggtgcgcgccaccatcgccgaactcatcaggctcctgga
agacgagctcacggtctcggcccgcaacgcccagtttttcaacttcgccgtggatttcta
cgaggccatggaaaggctggaggccattggcgacatcagcgaaatgcccctgcgccgctg
gattatgtacttcttcgtcaccgagcacatcgccaccaccctcaactacctcttccaacg
cctgcgcaactatgccgtcttcgcgcggcacgtggagctcaacctcgcgcaggtggtcat
gcgcgcgcgcgacgccgacggggacgtggtttacagccgcgtctggaacgagagcggcct
gggcgccttctcgcagctcatgggtcgcatctcgaatgaccttgccgccaccgtagagcg
cgcgggccgcggcgatctccaggaggaggaaatcgagcagttcatgtccgagatcgccta
ccaggacaactcgggcgacgtgcaagagatcctgcgtcaggccgccgtcaatgacgccga
gATTGATTCTGTTGAACTGTCTTTCAGGTTCAAAGTCACGGGGCCCGTGGTCTTCACGCA
AAGGCGGCAGATCCAGGATGTCAACCGCCGCGTCGTCGCGCACGCCAGCGCTCTCAGGGC
GCAGCACCGGGACCTGCCCGAGCGCCACGCCGACGTGCCTCTACCGCCACTGCCCGCGGG
GCCGGAACCGCCGCTGCCGCCGGGAGCGCGTCCGCGACACCGCTTCTAAAAGCGCACCGC
GGCACGGTCGTGGCCCCGCGCAGCTACGGGCTCATGCAATGCGTGGACACGACCACCAAC
TCACCCGTGGAGATCAAGTACCATCTGCATCTCAAGCACGCCCTCACCCGCCTCTACGAG
GTCAACCTCAGAACCCTGCCCCCGGACCTGGATCTCCGCGACACCATGGACAGCTCCCAA
CTGCGCGCCCTCGTTTTCGCTCTCCGCCCCCGCCGCGCCGAGATCTGGACCTGGCTCCCG
CGCGGGCTCGTCAGCCTCTCCGTCCTCGAGGAGCCCCAGGGTGAGTCCCACGCAGGCGAA
CATGAAAACCACCAGCCAGGGCCGCCACTCCTGAAGTTCCTCCTCAAGGGACGCGCTGTG
TATCTCGTGGATGAGGTACAGCCCGTGCAGCGCTGCGAGTACTGCGGACGCTTTTACAAG
CATCAGCACGAGTGCTCGGTTCGCCGGCGGGATTTCTACTTTCATCACATCAACAGCCAC
TCGACCAACTGGTGGCAGGAAATCCAGTTCTTCCCAATCGGCTCTCATCCTCGCACGGAG
CGGCTCTTTGTCACCTACGATGTAGAAACCTACACCTGGATGGGGTCCTTCGGCAAGCAG
CTCGTCCCCTTCATGCTGGTCATGAAATTCTCCGGGGACCCCGAGCTGGTCGCCCTCGCT
CGCGATCTCGCCGTGCGCTTACGCTGGGATCGCTGGGAGCGGGACCCCCTCACCTTCTAC
TGCGTCACCCCAGAAAAGATGGCCGTGGGCCAGCAGTTCCGCCTCTTTCGCGACGAGCTC
CAGACCCTCATGGCCCGCGAGCTCTGGGCTTCATTCATGCAAGCCAACCCACATCTCCAG
GAGTGGGCGCTCGAGCAGCACGGCCTGCAATGCCCCGAGGACCTCACCTACGAGGAACTC
AAAAAGCTGCCGCACATCAAAGGCCGCCCGCGATTCATGGAACTCTACATCGTCGGGCAC
AACATCAACGGCTTCGACGAGATCGTCCTCGCCGCCCAGGTCATCAACAACCGAGCCTCC
GTTCCGGGCCCTTTCCGCATCACCCGCAATTTCATGCCGCGGGCAGGCAAGATTCTCTTC
AATGACGTCACTTTCGCTCTGCCTAACCCCCTCTCGAAGAAGCGCACCGATTTCGAGCTC
TGGGAGCACGGCGGCTGCGACGACTCGGATTTCAAGTACCAGTTCTTGAAAGTCATGGTT
AGGGATACCTTCGCCCTGACGCACACCTCGCTCCGCAAGGCCGCTCAAGCTTACGCCCTC
CCCGTGGAGAAGGGCTGCTGTCCCTACAAGGCCGTGAACCATTTCTACATGCTGGGCTCT
TACCGTGCGGACGATCGAGGATTCCCGCTCCGGGAGTACTGGAAGGATGACGAGGAGTAC
GCCCTCAACCGCGCGCTGTGGGAGAAGAAAGAAGAGGCGGGTTATGACATCATCCGTGAA
ACGCTGGACTACTGCGCCATGGACGTCCTTGTCACCGCCGAGCTCGTTGCCAAGCTGCAA
GACTCCTACGCGCACTTCATCCGCGACTCGGTCCGCTTGCCCCACGCCCACTTTAACATC
TTCCAACGGCCCACCATCTCCTCCAACTCGCATGCCATCTTTCGCCAGATCGTCTTCCGC
GCCGAGCAGCCCCAGCGCACCAATCTCGGCCCCGCTTTCTTGGCCCCCTCGCACGAGTTG
TATGACTATGTGCGCGCCAGCATCCGCGGGGGGCGCTGTTATCCCACCTACATCGGCATC
CTCTCGGAGCCCATCTATGTCTACGACATCTGCGGCATGTACGCCTCCGCCCTCACGCAT
CCCATGCCCTGGGGTCCGCCCCTCAACCCCTACGAGCGAGCGCTGGCCGCCCGCGAGTGG
CAGATGGCCTTGGATGATGCATCCTCAAAAATCGATTATTTTGACAAGGAACTCTGTCCG
GGCATCTTCACCATCGATGCGGACCCCCCTGACGAGCATCTGCTTGATGTGCTGCCCCCG
TTCTGCTCGCGCAAGGGCGGACGCCTCTGCTGGACCAACGAGCCCCTGCGCGGCGAGGTG
GCCACCAGCGTGGACCTGGTCACCCTGCATAATCGCGGCTGGCGCGTCAGGATCGTGCCC
GACGAGCGCACCACCGTCTTCCCAGAATGGAAGTGTGTCGCGCGCGAGTATGTCCAGCTC
AACATCGCGGCCAAGGAGCGCGCCGACCGTGACAAAAATCAGACCATGAGATCCATCGCC
AAGCTTCTCTCCAACGCCCTCTATGGCTCCTTTGCCACCAAGCTTGACAATAAAAAAATA
GTCTTTTCTGACCAGATGGATGAAAGTCTCCTAAAAAGCATTGCGGCAGGGCAGGCCAAC
ATCAAATCCTCCTCGTTTCTAGAAACTGACAACCTGAGTGCCGAGGTCATGCCCGCTCTC
GAGAGGGAATACCTACCCCAACAGCTGGCGCTCGTGGACAGCGACGCGGAAGAGAGTGAG
GACGAGCACAGACCCGCCCCCTTTTATACCCCCCCGTCGGGGACCCCCGGTCACGTGGCC
TACACCTACAAGCCAATCACCTTCTTGGATGCGGAGGAGGGGGACATGTGTCTGCACACG
GTGGAAAAGGTGGACCCCCTGGTGGACAACGACCGCTACCCCTCGCACGTGGCCTCCTTT
GTCTTGGCGTGGACGCGCGCCTTTGTCTCAGAGTGGTCCGAGTTTCTCTACGAGGAGGAC
CGCGGGACGCCCCTGCAGGACAGGCCAATCAAGTCCGTCTACGGGGACACAGACAGCCTG
TTTGTCACCGAACGCGGACACAGACTCATGGAGACGCGAGGTAAGAAGCGCATCAAAAAG
AACGGGGGAAAACTGGTTTTTGACCCCGAGCAGCCCGAGCTCACCTGGCTCGTCGAGTGC
GAGACCGTCTGCGCCCACTGCGGAGCGGACGCCTTCGCTCCCGAGTCCGTCTTTCTCGCA
CCCAAGCTCTACGCCCTGCAATCCCTCCTCTGTCCCGCCTGCGGGCGCTCTTCCAAAGGC
AAGCTCCGTGCCAAGGGCCACGCCGCCGAGGCCCTTAACTACAAGCTCATGGTCAACTGC
TATCTCGCCGACGCGCAGGGCGAAGACCGTGCCCGTTTCAGCACCAGCAGGATGAGTCTC
AAGCGCACCCTTGCAAGCGCCCAGCCCGGGGCCCACCCCTTCACCGTGACGGAGACCACC
CTCACTCGGACCCTGAGACCCTGGAAGGACATGACGCTGGCCGCGCTGGACGCCCATCGT
CTCGTGCCCTACAGTCGCAGTCGTCCCAACCCCCGAAACGAGGAAGTCTGCTGGATCGAG
ATGCCGTAGagcacgtcaccgagctatgggaccgcctggagctcctctcgcagacccttg
ccaagatgcccatggccgacgggctcaagcccctgaaaaactttgcttccctgcaagagc
tgctctcgctgggcggggaccgcctcctcggcgagctcg

Length = 1193

Score =  94.1 bits (199), Expect = 3e-22
Identities = 41/67 (61%), Positives = 48/67 (71%)
Frame = -2

Query: 8495  VQSHGARGLHAKAADPGCQPPRRRARQRSQGAAPGPARAPRRRASTATARGAGTAAAAGS 8316
             VQ+HG+RGLH +A+DPG QP RRR+RQ S GA P PARA RRRA   TA G+  A  A  
Sbjct: 4     VQTHGSRGLHPEASDPGRQPSRRRSRQSSPGAVPEPARARRRRAPATTASGSRAAPTARR 63

Query: 8315  ASATPLL 8295
             AS+ PLL
Sbjct: 64    ASSPPLL 70

Score =  68.4 bits (143), Expect(3) = 0.0
Identities = 30/71 (42%), Positives = 38/71 (53%)
Frame = -2

Query: 8369  RASTATARGAGTAAAAGSASATPLLKAHRGTVVAPRSYGLMQCVDTTTNSPVEIKYHLHL 8190
             RA+    R +        A   P  K  RGTVV P+ +G +Q +D  TN  VEIKYHL L
Sbjct: 56    RAAPTARRASSPPLLTMEAKPLPPAKKKRGTVVTPQGHGTLQAIDVATNGAVEIKYHLDL 115

Query: 8189  KHALTRLYEVN 8157
               AL +L +VN
Sbjct: 116   PRALEKLLQVN 126

Score =  76.7 bits (161), Expect(3) = 0.0
Identities = 34/62 (54%), Positives = 43/62 (69%)
Frame = -2

Query: 8120  TMDSSQLRALVFALRPRRAEIWTWLPRGLVSLSVLEEPQGESHAGEHENHQPGPPLLKFL 7941
             T+DSS LRALV ALRP RAE+WT LPRGLVS++ +E  +G++   +   HQ   P L F 
Sbjct: 142   TLDSSGLRALVLALRPVRAEVWTCLPRGLVSMTTIEAEEGQADHHDVVQHQMQAPRLHFP 201

Query: 7940  LK 7935
             LK
Sbjct: 202   LK 203

Score =  2153 bits (4693), Expect(3) = 0.0
Identities = 862/992 (86%), Positives = 915/992 (92%)
Frame = -2

Query: 7952  LKFLLKGRAVYLVDEVQPVQRCEYCGRFYKHQHECSVRRRDFYFHHINSHSTNWWQEIQF 7773
             LKFL+KG  V LV  V PVQRCE+CGR YKH+HECS RRR FYFHHINSHS+NWWQEIQF
Sbjct: 202   LKFLVKGTQVQLVQHVHPVQRCEHCGRLYKHKHECSARRRHFYFHHINSHSSNWWQEIQF 261

Query: 7772  FPIGSHPRTERLFVTYDVETYTWMGSFGKQLVPFMLVMKFSGDPELVALARDLAVRLRWD 7593
             FPIGSHPRTERLF+TYDVETYTWMGSFGKQLVPFMLVMK SGD  LV LA DLA++L+WD
Sbjct: 262   FPIGSHPRTERLFLTYDVETYTWMGSFGKQLVPFMLVMKLSGDDRLVELALDLALQLKWD 321

Query: 7592  RWERDPLTFYCVTPEKMAVGQQFRLFRDELQTLMARELWASFMQANPHLQEWALEQHGLQ 7413
             RW  DP TFYCVTPEKMAVGQQFR +RD LQT +A +LW SF++ANPHL +WALEQHGL 
Sbjct: 322   RWHGDPRTFYCVTPEKMAVGQQFRQYRDRLQTALAVDLWTSFLRANPHLADWALEQHGLS 381

Query: 7412  CPEDLTYEELKKLPHIKGRPRFMELYIVGHNINGFDEIVLAAQVINNRASVPGPFRITRN 7233
              P++LTYEELKKLPH+KGRPRF+ELYIVGHNINGFDEIVLAAQVINNRA VP PFRITRN
Sbjct: 382   DPDELTYEELKKLPHVKGRPRFVELYIVGHNINGFDEIVLAAQVINNRAEVPQPFRITRN 441

Query: 7232  FMPRAGKILFNDVTFALPNPLSKKRTDFELWEHGGCDDSDFKYQFLKVMVRDTFALTHTS 7053
             FMPRAGKILFNDVTFALPNP  KKRTDF+LWE GGCDD DFK+QFLKVMVRDTFALTHTS
Sbjct: 442   FMPRAGKILFNDVTFALPNPAYKKRTDFQLWEQGGCDDIDFKHQFLKVMVRDTFALTHTS 501

Query: 7052  LRKAAQAYALPVEKGCCPYKAVNHFYMLGSYRADDRGFPLREYWKDDEEYALNRALWEKK 6873
             LRKAAQAYALPVEKGCC YKAVN FYMLGSYRAD  GFPL EYWKD EE+ LNR LW++K
Sbjct: 502   LRKAAQAYALPVEKGCCAYKAVNQFYMLGSYRADQDGFPLEEYWKDREEFLLNRELWKQK 561

Query: 6872  EEAGYDIIRETLDYCAMDVLVTAELVAKLQDSYAHFIRDSVRLPHAHFNIFQRPTISSNS 6693
              +  YDII+ETLDYCA+DVLVTAELVAKLQDSYAHFIRDSV LPHAHFNIFQRPTISSNS
Sbjct: 562   GQLKYDIIQETLDYCALDVLVTAELVAKLQDSYAHFIRDSVGLPHAHFNIFQRPTISSNS 621

Query: 6692  HAIFRQIVFRAEQPQRTNLGPAFLAPSHELYDYVRASIRGGRCYPTYIGILSEPIYVYDI 6513
             HAIFRQIV+RAE+P R NLG   LAPSHELYDYVRASIRGGRCYPTYIGIL EP+YVYDI
Sbjct: 622   HAIFRQIVYRAEKPSRANLGAGLLAPSHELYDYVRASIRGGRCYPTYIGILDEPLYVYDI 681

Query: 6512  CGMYASALTHPMPWGPPLNPYERALAAREWQMALDDASSKIDYFDKELCPGIFTIDADPP 6333
             CGMYASALTHPMPWG PL+PYERALA REWQ +LDD  + I YFD +L PGIFTIDADPP
Sbjct: 682   CGMYASALTHPMPWGTPLSPYERALAVREWQASLDDLGTCISYFDPDLLPGIFTIDADPP 741

Query: 6332  DEHLLDVLPPFCSRKGGRLCWTNEPLRGEVATSVDLVTLHNRGWRVRIVPDERTTVFPEW 6153
             DE +LD LPPFCSRKGGRLCWTNEPLRGEVATSVDL+TLHNRGW+VRIVPDE TTVFPEW
Sbjct: 742   DELMLDPLPPFCSRKGGRLCWTNEPLRGEVATSVDLITLHNRGWQVRIVPDELTTVFPEW 801

Query: 6152  KCVAREYVQLNIAAKERADRDKNQTMRSIAKLLSNALYGSFATKLDNKKIVFSDQMDESL 5973
             KCVAREYVQLNIAAKERAD++KNQTMRSIAKLLSNALYGSFATKLDNKKIVFSDQMDE L
Sbjct: 802   KCVAREYVQLNIAAKERADKEKNQTMRSIAKLLSNALYGSFATKLDNKKIVFSDQMDEGL 861

Query: 5972  LKSIAAGQANIKSSSFLETDNLSAEVMPALEREYLPQQLALVDSDAEESEDEHRPAPFYT 5793
             LK I+AG  NIKSSSFLETDNLSAEVMPA EREYLPQQLAL+DSD E+SEDE RPAPFYT
Sbjct: 862   LKGISAGTVNIKSSSFLETDNLSAEVMPAFEREYLPQQLALLDSDPEDSEDEQRPAPFYT 921

Query: 5792  PPSGTPGHVAYTYKPITFLDAEEGDMCLHTVEKVDPLVDNDRYPSHVASFVLAWTRAFVS 5613
             PP+GTPGHVAYTYKPITFLD +EGDMCLHT+EKVDPLVDNDRYPSHVASFVLAWTRAFVS
Sbjct: 922   PPAGTPGHVAYTYKPITFLDVDEGDMCLHTLEKVDPLVDNDRYPSHVASFVLAWTRAFVS 981

Query: 5612  EWSEFLYEEDRGTPLQDRPIKSVYGDTDSLFVTERGHRLMETRGKKRIKKNGGKLVFDPE 5433
             EWS FLY+EDRG PL+DRPIKSVYGDTDSLFVT+RGH LMETRGKKRIKKNGGKLVFDP 
Sbjct: 982   EWSGFLYDEDRGVPLEDRPIKSVYGDTDSLFVTQRGHELMETRGKKRIKKNGGKLVFDPN 1041

Query: 5432  QPELTWLVECETVCAHCGADAFAPESVFLAPKLYALQSLLCPACGRSSKGKLRAKGHAAE 5253
             QP+LTWLVECETVCAHCGADA+APESVFLAPKLYAL+SLLCPACG++SKGKLRAKGHAAE
Sbjct: 1042  QPDLTWLVECETVCAHCGADAYAPESVFLAPKLYALKSLLCPACGQTSKGKLRAKGHAAE 1101

Query: 5252  ALNYKLMVNCYLADAQGEDRARFSTSRMSLKRTLASAQPGAHPFTVTETTLTRTLRPWKD 5073
             ALNY+LMVNCYLADAQG DR RFSTSRMSLKRTLASAQPGAHPFTVTETTLTRTLRPWKD
Sbjct: 1102  ALNYELMVNCYLADAQGADRERFSTSRMSLKRTLASAQPGAHPFTVTETTLTRTLRPWKD 1161

Query: 5072  MTLAALDAHRLVPYSRSRPNPRNEEVCWIEMP 4977
              TLAALDAHRL PYSRSRPNPRNEEVCWIEMP
Sbjct: 1162  RTLAALDAHRLAPYSRSRPNPRNEEVCWIEMP 1193


========================================================================================================================

gene_id            %id    %sim   %cov   %t5   %gap  %t3   start..stop      pep sz ref sz ref id            definition
64.22              71.0   86.0   97.0   2.6   0.0   0.4   22787..24961     724    797    AAS10372.1        L4 | hexon-assembly protein
                    could not find valid start codon

CLUSTAL 2.1 multiple sequence alignment


predicted       ---------------------EQEEDLTT---------------HEQPK-IEQDLGFEEP
reference       METQPSSPTSPSAPAAADENQQQNESLTAPPPSPTSDAAAAPDMQEMEESIEIDLGYVTP
                                     :*:*.**:               :*  : ** ***:  *

predicted       --------ARLKPPQD-EQEH-EQDAGQEETDAGLEHG-YLGGEEDVLLKHLQRQSLILR
reference       AEHEEELAARFSAPEENHQEQPEQEAESEQQQAGLEHGDYLSGAEDVLIKHLARQCIIVK
                        **:..*:: .**: **:* .*: :****** **.* ****:*** **.:*::

predicted       DALADRSETPLSVEELCRAYELNLFSPRVPPKRQPNGTCEPNPRLNFYPVFAVPEALATY
reference       DALLDRAEVPLSVAELSRAYERNLFSPRVPPKRQPNGTCEPNPRLNFYPVFAVPEALATY
                *** **:*.**** **.**** **************************************

predicted       HIFFKNQKIPISCRANRTRADALLALGPGARIPDIASLEEVPKIFEGLGRDETRAANALK
reference       HLFFKNQRIPVSCRANRTRADALLNLGPGARLPDIASLEEVPKIFEGLGSDETRAANALQ
                *:*****:**:************* ******:***************** *********:

predicted       ETAEEEGYTSALVELEGDNARLAVLKRSVELTHFAYPAVNLPPKVMRRIMDQLIMPHIEA
reference       GSGEEHEHHSALVELEGDNARLAVLKRTVELTHFAYPALNLPPKVMSAVMDQVLIKRASP
                 :.**. : ******************:**********:*******  :***::: : ..

predicted       LDESQEQRPEN---AQPVVSDEMLARWLGTR-DPQALEQRRKLMLAVVLVTLELECMRRF
reference       LSDEDMQDPESSDEGKPVVSDEQLARWLGASSTPQSLEERRKLMMAVVLVTVELECLRRF
                *.:.: * **.   .:****** ******:   **:**:*****:******:****:***

predicted       FTDPETLRKVEETLHYTFRHGFVRQACKISNVELTNLVSCLGILHENRLGQTVLHSTLKG
reference       FADAETLRKVEENLHYLFRHGFVRQACKISNVELTNLVSYMGILHENRLGQNVLHTTLRG
                *:*.********.*** ********************** :**********.***:**:*

predicted       EARRDYIRDCVFLFLCHTWQAAMGVWQQCLEDENLKELDKLLARNLKKLWTGFDERTVAS
reference       EARRDYIRDCVYLYLCHTWQTGMGVWQQCLEEQNLKELCKLLQKNLKALWTGFDERTTAS
                ***********:*:******:.*********::***** *** :*** *********.**

predicted       DLAEIVFPERLRQTLKGGLPDFMSQSMLQNYRTFILERSGMLPATCNAFPSDFVPLSYRE
reference       DLADLIFPERLRLTLRNGLPDFMSQSMLQNFRSFILERSGILPATCSALPSDFVPLTFRE
                ***:::****** **:.*************:*:*******:*****.*:*******::**

predicted       CPPPLWSHCYLLQLANYIAHHSDVIEDVSGEGLLECHCRCNLCSPHRSLVCNPQLLSETQ
reference       CPPPLWSHCYLLRLANYLAYHSDVIEDVSGEGLLECHCRCNLCTPHRSLACNPQLLSETQ
                ************:****:*:***********************:*****.**********

predicted       VIGTFELQGPQESTAPLKLTPGLWTSAYLRKFVPEDYYAHEIKFFEDQSRPQHADLTACV
reference       IIGTFELQGPGEGKGGLKLTPGLWTSAYLRKFVPEDYHPFEIRFYEDQSQPPKAELSACV
                :********* *... *********************:..**:*:****:* :*:*:***

predicted       ITQGAILAQLHAIQKSRQEFLLKKGRGVYLDPQTGEVLNPGLPQHA-----EEEAG-AAS
reference       ITQGAILAQLQAIQKSRQEFLLKKGHGVYLDPQTGEELNPSFPQDAPRKQQEAESGAAAA
                **********:**************:********** ***.:**.*     * *:* **:

predicted       GGDGRRMG-QPGRGG---RMGGGD-RGGRLGR--GGRGAG---NRAARRRTIRAGSPS-G
reference       GGFGGRLGEQSGRGGGDGRLGQHSGRGGQPARQSGRRGGGGGRGRSSRRQTVVLGGESKQ
                ** * *:* *.****   *:*  . ***: .*  * **.*   .*::**:*:  *. *  

predicted       HGYNLRS-SGQASS---
reference       HGYHLRSGSGSRRPGPQ
                ***:*** **.  .

>64.23	22787	24961
ggcgaggggctcctctcctgctccggcggatagcgcgccgacccgtggccccggggcgga
gtggcctctcgctccatgaaccggcgcacgtcctgactgccgccggccattgtttcctag
gggaagatggaggagcagccgcgtaagcagGAGCAGGAGGAGGACTTAACCACCCACGAG
CAACCCAAAATCGAGCAGGACCTGGGCTTCGAAGAGCCGGCTCGTCTAAAACCCCCACAG
GATGAACAGGAGCACGAGCAAGACGCAGGCCAGGAGGAGACCGACGCTGGGCTCGAGCAT
GGCTACCTGGGAGGAGAGGAGGATGTGCTGCTAAAACACCTGCAGCGCCAGTCCCTCATC
CTCCGGGACGCCCTGGCCGACCGGAGCGAAACCCCCCTCAGCGTCGAGGAGCTGTGTCGG
GCCTACGAGCTCAACCTCTTCTCGCCGCGCGTGCCCCCCAAACGCCAGCCCAACGGCACC
TGCGAGCCCAACCCGCGTCTCAACTTCTATCCCGTCTTTGCGGTCCCCGAGGCCCTTGCC
ACCTATCACATCTTTTTCAAGAACCAAAAGATCCCCATCTCCTGTCGCGCCAATCGCACT
CGCGCCGACGCGCTCCTCGCTCTGGGGCCCGGCGCGCGCATACCTGATATCGCTTCCCTG
GAAGAGGTGCCCAAGATCTTCGAAGGGCTCGGTCGGGACGAGACGCGCGCGGCAAACGCT
CTGAAAGAAACAGCAGAGGAAGAGGGTTACACTAGCGCCCTGGTAGAGTTGGAAGGCGAC
AACGCCAGGCTGGCCGTGCTTAAGCGCAGCGTCGAGCTCACCCATTTCGCCTACCCCGCC
GTCAACCTCCCGCCCAAGGTCATGCGTCGCATCATGGATCAGCTCATCATGCCCCACATC
GAGGCCCTTGATGAAAGTCAGGAACAGCGCCCCGAGAACGCCCAGCCCGTGGTCAGCGAC
GAGATGCTCGCGCGCTGGCTCGGGACCCGCGACCCCCAGGCCCTGGAGCAGCGGCGCAAG
CTCATGCTGGCCGTGGTCCTGGTCACCCTTGAGCTCGAATGCATGCGCCGCTTTTTTACC
GACCCCGAGACCCTGCGCAAGGTCGAGGAGACCCTGCACTACACTTTCAGACACGGTTTC
GTCAGGCAGGCCTGCAAGATCTCCAACGTGGAGCTGACCAACCTGGTCTCCTGCCTGGGG
ATCCTACACGAGAACCGCTTGGGACAGACCGTGCTCCACTCTACCCTGAAGGGCGAGGCG
CGGCGGGACTACATCCGCGACTGCGTCTTTCTCTTTCTCTGCCACACATGGCAAGCGGCC
ATGGGCGTGTGGCAGCAGTGTCTCGAGGACGAGAACCTGAAGGAGCTGGACAAGCTTCTT
GCTAGAAACCTTAAAAAGCTGTGGACGGGCTTCGACGAGCGCACCGTCGCCTCGGACCTG
GCCGAGATCGTCTTCCCCGAGCGCCTGAGGCAGACGCTGAAAGGAGGGCTGCCCGACTTC
ATGAGCCAGAGCATGTTGCAAAACTACCGCACTTTCATTCTCGAGCGATCTGGGATGCTG
CCCGCCACCTGCAACGCCTTCCCCTCCGACTTTGTCCCGCTGAGCTACCGCGAGTGTCCC
CCGCCGCTGTGGAGCCACTGCTACCTCTTGCAGCTGGCCAACTACATTGCCCACCACTCG
GATGTGATCGAGGACGTGAGCGGCGAGGGGCTGCTCGAGTGCCACTGTCGCTGCAACCTA
TGCTCCCCGCACCGCTCCCTGGTCTGCAACCCCCAGCTACTGAGCGAGACCCAGGTCATC
GGTACCTTTGAGCTGCAAGGTCCGCAGGAGTCCACCGCTCCGCTGAAACTCACGCCGGGG
TTGTGGACTTCCGCGTACCTGCGCAAATTTGTACCCGAGGACTACTACGCCCATGAGATA
AAGTTCTTCGAGGACCAATCGCGTCCGCAGCACGCGGATCTCACGGCCTGCGTCATCACC
CAGGGCGCGATCCTCGCCCAATTGCACGCCATCCAAAAATCCCGCCAAGAGTTTCTTCTG
AAAAAGGGTAGAGGGGTCTACCTGGACCCCCAGACGGGCGAGGTGCTCAACCCGGGTCTC
CCCCAGCATGCCGAGGAAGAAGCAGGAGCCGCTAGTGGAGGAGATGGAAGAAGAATGGGA
CAGCCAGGCAGAGGAGGACGAATGGGAGGAGGAGACAGAGGAGGAAGACTTGGAAGAGGT
GGAAGAGGAGCAGGCAACAGAGCAGCCCGTCGCCGCACCATCCGCGCCGGCAGCCCCTCC
GGTCACGGATACAACCTCCGCAGCTCCGGCCAAGCCTCCTCGTAGatgggatcgagtgaa
gggtgacggtaagcacgagcgacagggctaccgatcatggagggcccacaaagccgcgat
catcgcctgcttgcaagactgcggggggaacatcgctttcgcccgccgctacctgctctt
ccaccgcggggtgaa

Length = 797

Score =   398 bits (864), Expect(2) = e-117
Identities = 166/233 (71%), Positives = 192/233 (82%)
Frame = +2

Query: 22880 EQEHEQDAGQEETDAGLEHGYLGGEEDVLLKHLQRQSLILRDALADRSETPLSVEELCRA 23059
             EQ  ++   +++        YL G EDVL+KHL RQ +I++DAL DR+E PLSV EL RA
Sbjct: 80    EQPEQEAESEQQQAGLEHGDYLSGAEDVLIKHLARQCIIVKDALLDRAEVPLSVAELSRA 139

Query: 23060 YELNLFSPRVPPKRQPNGTCEPNPRLNFYPVFAVPEALATYHIFFKNQKIPISCRANRTR 23239
             YE NLFSPRVPPKRQPNGTCEPNPRLNFYPVFAVPEALATYH+FFKNQ+IP+SCRANRTR
Sbjct: 140   YERNLFSPRVPPKRQPNGTCEPNPRLNFYPVFAVPEALATYHLFFKNQRIPVSCRANRTR 199

Query: 23240 ADALLALGPGARIPDIASLEEVPKIFEGLGRDETRAANALKETAEEEGYTSALVELEGDN 23419
             ADALL LGPGAR+PDIASLEEVPKIFEGLG DETRAANAL+ + EE  + SALVELEGDN
Sbjct: 200   ADALLNLGPGARLPDIASLEEVPKIFEGLGSDETRAANALQGSGEEHEHHSALVELEGDN 259

Query: 23420 ARLAVLKRSVELTHFAYPAVNLPPKVMRRIMDQLIMPHIEALDESQEQRPENA 23578
             ARLAVLKR+VELTHFAYPA+NLPPKVM  +MDQ+++     L +   Q PE++
Sbjct: 260   ARLAVLKRTVELTHFAYPALNLPPKVMSAVMDQVLIKRASPLSDEDMQDPESS 312

Score =   787 bits (1712), Expect(2) = 0.0
Identities = 322/448 (71%), Positives = 367/448 (81%)
Frame = +2

Query: 23495 VMRRIMDQLIMPHIEALDESQEQRPENAQPVVSDEMLARWLGTRDPQALEQRRKLMLAVV 23674
             VM +++ +   P  +   +  E   E    V  +++      +  PQ+LE+RRKLM+AVV
Sbjct: 289   VMDQVLIKRASPLSDEDMQDPESSDEGKPVVSDEQLARWLGASSTPQSLEERRKLMMAVV 348

Query: 23675 LVTLELECMRRFFTDPETLRKVEETLHYTFRHGFVRQACKISNVELTNLVSCLGILHENR 23854
             LVT+ELEC+RRFF D ETLRKVEE LHY FRHGFVRQACKISNVELTNLVS +GILHENR
Sbjct: 349   LVTVELECLRRFFADAETLRKVEENLHYLFRHGFVRQACKISNVELTNLVSYMGILHENR 408

Query: 23855 LGQTVLHSTLKGEARRDYIRDCVFLFLCHTWQAAMGVWQQCLEDENLKELDKLLARNLKK 24034
             LGQ VLH+TL+GEARRDYIRDCV+L+LCHTWQ  MGVWQQCLE++NLKEL KLL +NLK 
Sbjct: 409   LGQNVLHTTLRGEARRDYIRDCVYLYLCHTWQTGMGVWQQCLEEQNLKELCKLLQKNLKA 468

Query: 24035 LWTGFDERTVASDLAEIVFPERLRQTLKGGLPDFMSQSMLQNYRTFILERSGMLPATCNA 24214
             LWTGFDERT ASDLA+++FPERLR TL+ GLPDFMSQSMLQN+R+FILERSG+LPATC+A
Sbjct: 469   LWTGFDERTTASDLADLIFPERLRLTLRNGLPDFMSQSMLQNFRSFILERSGILPATCSA 528

Query: 24215 FPSDFVPLSYRECPPPLWSHCYLLQLANYIAHHSDVIEDVSGEGLLECHCRCNLCSPHRS 24394
              PSDFVPL++RECPPPLWSHCYLL+LANY+A+HSDVIEDVSGEGLLECHCRCNLC+PHRS
Sbjct: 529   LPSDFVPLTFRECPPPLWSHCYLLRLANYLAYHSDVIEDVSGEGLLECHCRCNLCTPHRS 588

Query: 24395 LVCNPQLLSETQVIGTFELQGPQESTAPLKLTPGLWTSAYLRKFVPEDYYAHEIKFFEDQ 24574
             L CNPQLLSETQ+IGTFELQGP E    LKLTPGLWTSAYLRKFVPEDY+  EI+F+EDQ
Sbjct: 589   LACNPQLLSETQIIGTFELQGPGEGKGGLKLTPGLWTSAYLRKFVPEDYHPFEIRFYEDQ 648

Query: 24575 SRPQHADLTACVITQGAILAQLHAIQKSRQEFLLKKGRGVYLDPQTGEVLNPGLPQHAEE 24754
             S+P  A+L+ACVITQGAILAQL AIQKSRQEFLLKKG GVYLDPQTGE LNP  PQ A  
Sbjct: 649   SQPPKAELSACVITQGAILAQLQAIQKSRQEFLLKKGHGVYLDPQTGEELNPSFPQDAPR 708

Query: 24755 EAGAASGGDGRRMGQPGRGGRMGGGDRG 24838
             +   A  G     G  GR G   G   G
Sbjct: 709   KQQEAESGAAAAGGFGGRLGEQSGRGGG 736

Score =  34.5 bits (69), Expect(2) = e-117
Identities = 20/60 (33%), Positives = 24/60 (40%)
Frame = +2

Query: 24761 GAASGGDGRRMGQPGRGGRMGGGDRGGRLGRGGRGAGNRAARRRTIRAGSPSGHGYNLRS 24940
             G  SG  G         GR G   R      GG G G  + R+  +  G    HGY+LRS
Sbjct: 728   GEQSGRGGGDGRLGQHSGRGGQPARQSGRRGGGGGRGRSSRRQTVVLGGESKQHGYHLRS 787


========================================================================================================================

gene_id            %id    %sim   %cov   %t5   %gap  %t3   start..stop      pep sz ref sz ref id            definition
gi_51527264.13     99.6   99.6   99.6   0.4   0.0   0.0   7814..7815       223    224    AAT97489.1        HYP-6 | hypothetical protein
                                                          8535..9204                                       
                    non-canonical splicing for intron at 7816..8534
                    could not find valid start codon

CLUSTAL 2.1 multiple sequence alignment


predicted       -IDDATVDVLDLTPLGEGHGTREFEPERQFDRINLGIIDGGLPQNLLHVARVVLVGNLGH
reference       MRDDATVDVLDLTPLGEGHGTREFEPERQFDRINLGIIDGGLPQNLLHVARVVLVGNLGH
                  **********************************************************

predicted       ELLDLLLLKVSAAGALHGGREVVGDAAHELREGVHARLVPDAAVNHGALGIAGAHDHLGE
reference       ELLDLLLLKVSAAGALHGGREVVGDAAHELREGVHARLVPDAAVNHGALGIAGAHDHLGE
                ************************************************************

predicted       VELHVARKNRVVAEALVEVVERGGNVLSDKEVHNPAAERHFADVAQGFQALHGLVKVHGE
reference       VELHVARKNRVVAEALVEVVERGGNVLSDKEVHNPAAERHFADVAQGFQALHGLVKVHGE
                ************************************************************

predicted       VEKLGVACRYGQVLLQKTDELGDGGAHLALEGSREFLHFLLFIH
reference       VEKLGVACRYGQVLLQKTDELGDGGAHLALEGSREFLHFLLFIH
                ********************************************

>gi_51527264.16	7814	9204
ctggagggcgagatcaagggcgagctcaacgagccggtcgtccccggagagtttcatgac
cagcatgaaggggacgagctgcttgccgaaggaccccatccaggtgtaggtttccacatc
gtaggtgaggaagagcctttcggtgcgaggATgcgagccgatggggaagaactggatctc
ctgccaccagttggaggaatggctgttgatgtgatggaagtagaaatgccgacggcgcgc
cgaacattcgtgcttgtgtttatacaagcggccacagtgctcgcaacgctgcacgggatg
cacgtgctgcacgagctgtacctgggttcctttgacgaggaatttcagtgggaagtggag
tcgtggcgcctgcatctggtgctgtactacgtcgtggtggtcggcctggccctcttctgc
ctcgatggtggtcatgctgacgagcccgcgcgggaggcaggtccagacctcggcgcgaac
gggtcggagagcgaggacgagggcgcgcaggccggagctgtccagggtcctgagacgctg
cggagtcaggtcagtgggcagcggcggcgcgcggttgacttgcaggagtttttcaagggc
gcgcgggaggtccagatggtacttgatctccaccgcgccgttggtggcgacgtcgatggc
ttgcagtgtcccgtgcccctggggagtgaccaccgtcccccgtttcttcttggcgggcgg
aagcggtttggcttccatggttaaaagcggcggcgaggacgcgcgccgggcggtaggggc
ggctcgggacccggaggcagtggtggcaggggcacgtcggcgccgcgcgcgggcaggttc
tggtactgcgcccggagaagactggcgtgagCGACGACGCGACGGTTGACGTCCTGGATC
TGACGCCTCTGGGTGAAGGCCACGGGACCCGTGAGTTTGAACCTGAAAGACAGTTCGACA
GAATCAATCTCGGTATCATTGACGGCGGCCTGCCGCAGAATCTCTTGCACGTCGCCCGAG
TTGTCCTGGTAGGCAATCTCGGTCATGAACTGCTCGATCTCCTCCTCCTGAAGGTCTCCG
CGGCCGGCGCGCTCCACGGTGGCCGCGAGGTCGTTGGAGATGCGGCCCATGAGCTGCGAG
AAGGCGTTCATGCCCGCCTCGTTCCAGACGCGGCTGTAAACCACGGCGCCCTCGGGATCG
CGGGCGCGCATGACCACCTGGGCGAGGTTGAGCTCCACGTGGCGCGCAAAAACCGCGTAG
TTGCAGAGGCGCTGGTAGAGGTAGTTGAGCGTGGTGGCAATGTGCTCAGTGACAAAGAAG
TACATAATCCAGCGGCGGAGCGGCATTTCGCTGACGTCGCCCAGGGCTTCCAAGCGCTCC
ATGGCCTCGTAAAAGTCCACGGCGAAGTTGAAAAACTGGGAGTTGCGTGCAGATACGGTC
AAGTCCTCCTCCAGAAGACGGATGAGCTCGGCGATGGTGGCGCGCACCTCGCGCTCGAAG
GCTCCCGGGAGTTCCTCCACTTCCTCCTCTTCATCCACTAAcatctcttctacttcctcc
tcaggcggtggtggcgggggagggggcctgcgtcgccggcggcgcacgggcagacggtcg
atgaaacgctcgatggtctcgccgcgccggcgtcgcatggtctcggtgacggcgcgcccg
tcctcgcgggg

Length = 224

Score =   525 bits (1140), Expect = e-153
Identities = 222/222 (100%), Positives = 222/222 (100%)
Frame = +1

Query: 8536 DDATVDVLDLTPLGEGHGTREFEPERQFDRINLGIIDGGLPQNLLHVARVVLVGNLGHEL 8715
            DDATVDVLDLTPLGEGHGTREFEPERQFDRINLGIIDGGLPQNLLHVARVVLVGNLGHEL
Sbjct: 3    DDATVDVLDLTPLGEGHGTREFEPERQFDRINLGIIDGGLPQNLLHVARVVLVGNLGHEL 62

Query: 8716 LDLLLLKVSAAGALHGGREVVGDAAHELREGVHARLVPDAAVNHGALGIAGAHDHLGEVE 8895
            LDLLLLKVSAAGALHGGREVVGDAAHELREGVHARLVPDAAVNHGALGIAGAHDHLGEVE
Sbjct: 63   LDLLLLKVSAAGALHGGREVVGDAAHELREGVHARLVPDAAVNHGALGIAGAHDHLGEVE 122

Query: 8896 LHVARKNRVVAEALVEVVERGGNVLSDKEVHNPAAERHFADVAQGFQALHGLVKVHGEVE 9075
            LHVARKNRVVAEALVEVVERGGNVLSDKEVHNPAAERHFADVAQGFQALHGLVKVHGEVE
Sbjct: 123  LHVARKNRVVAEALVEVVERGGNVLSDKEVHNPAAERHFADVAQGFQALHGLVKVHGEVE 182

Query: 9076 KLGVACRYGQVLLQKTDELGDGGAHLALEGSREFLHFLLFIH 9201
            KLGVACRYGQVLLQKTDELGDGGAHLALEGSREFLHFLLFIH
Sbjct: 183  KLGVACRYGQVLLQKTDELGDGGAHLALEGSREFLHFLLFIH 224


========================================================================================================================

gene_id            %id    %sim   %cov   %t5   %gap  %t3   start..stop      pep sz ref sz ref id            definition
gi_9626553.6       74.5   83.0   100.0  0.0   0.0   0.0   5840..6160       106    106    ABR27497.1        HYP-5 | hypothetical protein
                    stop codon embedded in CDS at 5900..5902

CLUSTAL 2.1 multiple sequence alignment


predicted       MERSVWFFSRSARSLAVILRXTYSFATQRHSGKTVARSSGSNRTCQPRLCSVIRSTLVTT
reference       MERMVWFFSLSARSLAAMLSCTYSRATHFHSGKTVVSSSGTILTCQPRLCRVMRSTLVAT
                *** ***** ******.:*  *** **: ******. ***:  ******* *:*****:*

predicted       SPRRGSLVQQRRPPLREQSGGKTSSRFSGGGSASMVKMPGSRVRLK
reference       SPRRGSLVQQRRPPLREQKGGRGSSISSSGGSASMVKMPGRRSGSK
                ******************.**: **  *.*********** *   *

>gi_9626553.8	5840	6160
gtttccacaaacgaggtggatttgatatttatctgccctgcggcaatgcttttgatggtg
gctgaatccatttggtcagaaaatacaatttttttgttatcaagtttggtagcaaaggat
ccatagagggcgttggagagcagtttggcaATGGAACGCAGTGTTTGGTTTTTTTCGCGG
TCGGCACGCTCCTTGGCGGTGATATTAAGATGAACGTACTCTTTTGCCACGCAGCGCCAC
TCGGGAAAGACAGTGGCGCGCTCGTCGGGAAGCAACCGCACATGCCAGCCCCGGTTGTGC
AGTGTTATAAGGTCCACACTGGTAACTACCTCGCCGCGCAGGGGCTCATTGGTCCAGCAA
AGGCGCCCTCCTTTGCGCGAACAGAGTGGGGGCAAAACATCTAGTAGGTTTTCAGGTGGG
GGGTCGGCGTCGATGGTAAAAATGCCAGGCAGCAGGGTGCGATTGAAATAAtcaatgggg
gtaccaacttgcaaaagagcgtgttcccaatctcggaccgctagggcgcgctcgtaggga
ttgagtgggaagccccacggcatgggatgggtaagtgcagaggcgtacatgccacagatg
tcataaacgtaaagtggttcg

Length = 106

Score =   174 bits (374), Expect = 1e-48
Identities = 78/102 (76%), Positives = 82/102 (80%)
Frame = +2

Query: 5840 MERSVWFFSRSARSLAVILR*TYSFATQRHSGKTVARSSGSNRTCQPRLCSVIRSTLVTT 6019
            MER VWFFS SARSLA +L  TYS AT  HSGKTV  SSG+  TCQPRLC V+RSTLV T
Sbjct: 1    MERMVWFFSLSARSLAAMLSCTYSRATHFHSGKTVVSSSGTILTCQPRLCRVMRSTLVAT 60

Query: 6020 SPRRGSLVQQRRPPLREQSGGKTSSRFSGGGSASMVKMPGSR 6145
            SPRRGSLVQQRRPPLREQ GG+ SS  S GGSASMVKMPG R
Sbjct: 61   SPRRGSLVQQRRPPLREQKGGRGSSISSSGGSASMVKMPGRR 102


========================================================================================================================

gene_id            %id    %sim   %cov   %t5   %gap  %t3   start..stop      pep sz ref sz ref id            definition
gi_61602086.8      75.5   84.2   100.0  0.0   0.0   0.0   5789..6109       106    106    ABR27497.1        HYP-5 | hypothetical protein
                    stop codon embedded in CDS at 5804..5806

CLUSTAL 2.1 multiple sequence alignment


predicted       MERRVXFFSRSALSLAAMLSCTYSRATHRHSGNTAVRSSGRMRTRQPRLCRVMRSTLVAT
reference       MERMVWFFSLSARSLAAMLSCTYSRATHFHSGKTVVSSSGTILTCQPRLCRVMRSTLVAT
                *** * *** ** *************** ***:*.* *** : * ***************

predicted       SPRRGSLVQHNRPPFLEQNGGRGSSKLAGGGSASMVNMPGSRILLK
reference       SPRRGSLVQQRRPPLREQKGGRGSSISSSGGSASMVKMPGRRSGSK
                *********:.***: **:******  :.*******:*** *   *

>gi_61602086.10	5789	6109
gtttctacaaacgaggtggatttgatattcacgtgccccgcggcgatgcttttgatggtg
gaggggtccatctgatcagaaaacacgatctttttattgtcaagtttggtggcgaaagac
ccgtagagggcgttggaaagcaacttggcgATGGAGCGCAGGGTCTGATTTTTCTCCCGA
TCGGCCCTCTCCTTGGCGGCGATGTTGAGTTGCACGTACTCGCGGGCCACGCACCGCCAC
TCGGGGAACACGGCGGTGCGCTCGTCGGGCAGGATGCGCACGCGCCAGCCGCGGTTGTGC
AGGGTGATGAGGTCCACGCTGGTGGCCACCTCCCCGCGGAGGGGCTCGTTGGTCCAACAC
AATCGCCCCCCTTTTCTGGAGCAGAACGGAGGCAGGGGATCTAGCAAGTTGGCGGGCGGG
GGGTCGGCGTCGATGGTAAATATGCCGGGTAGCAGAATTTTATTAAAATAAtcgatttcg
gtgtccgtgtcttgcaacgcgtcttcccacttcttcaccgccagggccctttcgtaggga
ttcaggggcggtccccagggcatggggtgggtcagggccgaggcgtacatgccgcagatg
tcgtacacgtacaggggctcc

Length = 106

Score =   174 bits (375), Expect = 9e-49
Identities = 79/102 (77%), Positives = 81/102 (79%)
Frame = +2

Query: 5789 MERRV*FFSRSALSLAAMLSCTYSRATHRHSGNTAVRSSGRMRTRQPRLCRVMRSTLVAT 5968
            MER V FFS SA SLAAMLSCTYSRATH HSG T V SSG + T QPRLCRVMRSTLVAT
Sbjct: 1    MERMVWFFSLSARSLAAMLSCTYSRATHFHSGKTVVSSSGTILTCQPRLCRVMRSTLVAT 60

Query: 5969 SPRRGSLVQHNRPPFLEQNGGRGSSKLAGGGSASMVNMPGSR 6094
            SPRRGSLVQ  RPP  EQ GGRGSS  + GGSASMV MPG R
Sbjct: 61   SPRRGSLVQQRRPPLREQKGGRGSSISSSGGSASMVKMPGRR 102


========================================================================================================================

gene_id            %id    %sim   %cov   %t5   %gap  %t3   start..stop      pep sz ref sz ref id            definition
gi_61602086.21     72.3   88.3   41.4   58.6  0.0   0.0   <24942..25211    89     222    AP_000317.1       L4-3 | putative splicing factor, C-terminal
                    missing exon 1

CLUSTAL 2.1 multiple sequence alignment


predicted       ------------------------------------------------------------
reference       MPRGNKKLKVELPPVEDLEEDWENSSQAEEEEMEEDWDSTQAEEDSLQDSLEEDEEEAEE
                                                                            

predicted       ------------------------------------------------------------
reference       EVEEAAAARPSSSAGEKASSTDTISAPGRGPARPHSRWDETGRFPNPTTQTAPTTSKKRQ
                                                                            

predicted       ----------AARKNSAAAA-----AAKDPPATEELRKRIFPTLYAIFQQSRGQHPQREL
reference       QQQKKTSRKPAARKSTAAAAGGLRIAANEPAQTRELRNRIFPTLYAIFQQSRGQ--EQEL
                          ****.:****     **::*. *.***:****************  ::**

predicted       KIKNRSFRSLTRSCLYHKREDQLQRTLDDAEALFSKYCSASLKD
reference       KVKNRSLRSLTRSCLYHKSEDQLQRTLEDAEALFNKYCALTLKE
                *:****:*********** ********:******.***: :**:

>gi_61602086.26	24942	25211
gcttgcaacactgcgggggaaacatctcctttgcccgacgctacctcctcttccatcacg
gtgtggccttccctcgcaacgttctctattattaccgtcatctctacagcccctacgaaa
cgctcggagaaaaaagctaaggcctcctccGCCGCGAGGAAAAACTCCGCCGCCGCTGCC
GCCGCCAAGGATCCACCGGCCACCGAAGAGCTGAGAAAGCGCATCTTTCCCACTCTGTAT
GCTATCTTTCAGCAAAGCCGCGGGCAGCACCCTCAGCGCGAACTGAAAATAAAAAACCGC
TCCTTCCGCTCGCTCACCCGCAGCTGTCTGTACCACAAGAGAGAAGACCAGCTGCAGCGC
ACCCTGGACGACGCCGAAGCACTGTTCAGCAAATACTGCTCAGCGTCTCTTAAAGACTAA
aagacccgcgctttttccccctcggccgccaaaacccacgtcatcgccagcatgagcaag
gagattcccaccccctacatgtggagctatcagccccagatgggcctggccgcgggggcc
gcccaggactactccagcaagatgaactgg

Length = 222

Score =  65.5 bits (137), Expect(2) = 2e-38
Identities = 30/57 (52%), Positives = 34/57 (59%)
Frame = +3

Query: 24909 KRSEKKAKASSAARKNSAAAAAAKDPPATEELRKRIFPTLYAIFQQSRGQHPQRELK 25079
             K S K A   S A        AA +P  T ELR RIFPTLYAIFQQSRGQ  + ++K
Sbjct: 125   KTSRKPAARKSTAAAAGGLRIAANEPAQTRELRNRIFPTLYAIFQQSRGQEQELKVK 181

Score =  95.6 bits (203), Expect(2) = 2e-38
Identities = 37/48 (77%), Positives = 45/48 (93%)
Frame = +3

Query: 25065 QRELKIKNRSFRSLTRSCLYHKREDQLQRTLDDAEALFSKYCSASLKD 25208
             ++ELK+KNRS RSLTRSCLYHK EDQLQRTL+DAEALF+KYC+ +LK+
Sbjct: 175   EQELKVKNRSLRSLTRSCLYHKSEDQLQRTLEDAEALFNKYCALTLKE 222


