========================================================================================================================

gene_id            %id    %sim   %cov   %t5   %gap  %t3   start..stop      pep sz ref sz ref id            definition
6.2                94.1   97.9   100.0  0.0   0.0   0.0   5083..6612       541    540    AAZ31396.2        VP1 | capsid protein VP1
                                                          6611..6706                                       
                    frameshift in genome at or near position 6612..6611 (+1=>+2)

CLUSTAL 2.1 multiple sequence alignment


predicted       MKMASNDANPSDGSAANLVPEVNNEVMALEPVVGAAIAAPVAGQQNVIDPWIRNNFVQAP
reference       MKMASNDATPSDGSTANLVPEVNNEVMALEPVVGAAIAAPVAGQQNVIDPWIRNNFVQAP
                ********.*****:*********************************************

predicted       GGEFTVSPRNAPGEILWSAPLGPDLNPYLSHLARMYNGYAGGFEVQVILAGNAFTAGKII
reference       GGEFTVSPRNAPGEILWSAPLGPDLNPYLSHLARMYNGYAGGFEVQVILAGNAFTAGKII
                ************************************************************

predicted       FAAVPPNFPTEGLSPSQVTMFPHIIVDVRQLEPVLIPLPDVRNNFYHYNQSNDSTIKLIA
reference       FAAVPPNFPTEVLSPSQVTMFPHIIVDVRQLEPVLIPLPDVRNNLYHYNQSNDPTIRLIA
                *********** ********************************:********.**:***

predicted       MLYTPLRANNGWGDVFTVSCRVLTRPSPDFDFIFLVPPTVESRTKPFTVPILTVEEMTNS
reference       MLYTPLRANNAGDDVFTVSCRVLTRPSPDFDFIFLVPPTVESRTKPFSVPILTVEEMTNS
                **********. .**********************************:************

predicted       RFPIPLEKLFTGPSGAFVVQPQNGRCTTDGVLLGTTQLSPVNICTFRGDVTHIAGSRNYT
reference       RFPIPLEKLFTGPSSAFVVQPQNGRCTTDGVLLGTTQLSPVNICTFRGDVTHIAGTQNYT
                **************.****************************************::***

predicted       MNLASLNWNNYDPTEEIPAPLGTPDFVGKIQGVLTQTTKGDGSTRGHKATVYTGSAPFTP
reference       MNLASQNWNNYDPTEEIPAPLGTPDFVGRIQGVLTQTTRRDGSTRGHKATVSTGSVHFTP
                ***** **********************:*********: *********** ***. ***

predicted       KLGSVQFSTDTENDFETHQNTKFTPVGVIQDGGTTHRNEPQQWVLPSYSGRDVHNVHLAP
reference       KLGSVQFSTDTSNDFETGQNTRFTPVGVVQDGSTTHQNEPQQWVLPDYSGRDSHNVHLAP
                ***********.***** ***:******:***.***:*********.***** *******

predicted       AVAPTFPGEQLLFFRSTMPGCSGYPNMDLDCLLPQEWVQHFYQEAAPAQSDVALLRFVNP
reference       AVAPTFPGEQLLFFRSTMPGCSGYPNMNLDCLLPQEWVQHFYQESAPAQSDVALLRFVNP
                ***************************:****************:***************

predicted       DTGRVLFECKLHKSGYVTVAHTGQHDLVIPPPNGYFRFDSWVNQFYTLAPMGNGTGRRRA
reference       DTGRVLFECKLHKSGYVTVAHTGQHDLVIPP-NGYFRFDSWVNQFYTLAPMGNGAGRRRA
                ******************************* **********************:*****

predicted       L
reference       L
                *

>6.2	5083	6706
acagtaaaatcagcaaattagtcattgcagagctaaaagaaggtggtatggatttttacg
tgcccaggcaagagccaatgttcagatggatgagattctcagatctgagcacgtgggagg
gcgatcgcaatctggctcccagttttgtgaATGAAGATGGCGTCGAATGACGCCAACCCA
TCTGATGGGTCCGCAGCCAACCTCGTCCCAGAGGTCAACAATGAGGTTATGGCTTTGGAG
CCCGTTGTCGGTGCCGCTATTGCGGCGCCTGTAGCGGGCCAACAAAATGTAATTGACCCC
TGGATTAGAAATAATTTTGTACAAGCCCCTGGTGGAGAGTTCACAGTATCCCCTAGAAAC
GCTCCAGGTGAAATACTATGGAGCGCGCCCTTAGGCCCTGATCTGAATCCCTACCTATCT
CATTTGGCCAGAATGTATAATGGTTATGCAGGTGGCTTTGAAGTGCAGGTGATCCTCGCG
GGGAACGCGTTCACCGCCGGAAAAATTATATTTGCAGCAGTCCCACCAAATTTTCCAACT
GAAGGCTTGAGTCCCAGCCAGGTCACTATGTTCCCCCACATAATAGTAGATGTTAGGCAA
TTGGAACCTGTGTTGATCCCCTTACCTGATGTTAGGAATAATTTTTATCACTATAATCAG
TCAAATGATTCTACCATTAAATTGATAGCAATGCTGTATACACCACTTAGGGCTAATAAT
GGCTGGGGAGACGTCTTCACAGTCTCTTGTCGAGTCCTCACTAGGCCGTCCCCTGATTTT
GATTTTATATTTTTGGTGCCACCCACAGTTGAGTCAAGAACTAAACCATTTACTGTCCCA
ATCTTAACCGTTGAAGAAATGACCAATTCAAGATTCCCCATTCCTTTGGAAAAGTTGTTC
ACGGGTCCCAGCGGTGCCTTTGTTGTCCAACCACAAAATGGCAGGTGCACGACTGATGGC
GTGCTCTTAGGCACCACCCAACTGTCTCCTGTCAACATCTGCACCTTCAGAGGGGATGTC
ACCCACATTGCAGGTTCTCGTAATTACACAATGAATTTGGCATCTCTAAATTGGAACAAT
TATGACCCAACAGAAGAAATTCCAGCCCCTCTAGGAACTCCAGATTTCGTGGGAAAGATC
CAAGGTGTGCTCACTCAAACCACAAAAGGAGATGGCTCGACCCGTGGCCATAAAGCTACA
GTTTACACTGGGAGTGCTCCCTTTACTCCAAAGCTGGGCAGTGTTCAATTCAGTACTGAC
ACAGAAAATGATTTTGAAACTCACCAAAACACAAAATTTACCCCAGTCGGTGTCATACAG
GACGGTGGCACCACCCACCGAAATGAACCCCAACAATGGGTGCTCCCAAGTTATTCAGGT
AGAGATGTTCATAATGTACACCTAGCCCCTGCTGTAGCCCCCACTTTTCCGGGTGAACAA
CTTCTTTTCTTCAGGTCCACTATGCCCGGATGCAGCGGGTATCCCAACATGGATTTGGAT
TGCCTACTCCCCCAGGAGTGGGTGCAGCACTTCTACCAAGAGGCAGCTCCAGCACAATCT
GATGTGGCTCTATTGAGATTTGTGAATCCAGACACGGGCAGGGTCCTGTTTGAGTGCAAA
CTTCATAAATCAGGCTATGTCACAGTGGCTCACACCGGTCAGCATGATTTGGTCATCCCC
CCCCAATGGCTATTTTAGGTTTGATTCGTGGGTTAATCAGTTTTACACACTTGCCCCCAT
GGGAAACGGAACGGGGCGTAGGCGCGCTTTATAAtggctggagctttctttgctggattg
gcatctgatgtccttggctctggacttggttccctaatcaatgctggggctggggctatc
aaccaaaagattgattttgaaaataatagaaaattgcagcaagcttctttccagtttagc
agta

Length = 540

Score =  1181 bits (2572), Expect(2) = 0.0
Identities = 482/515 (93%), Positives = 493/515 (95%)
Frame = +1

Query: 5083 MKMASNDANPSDGSAANLVPEVNNEVMALEPVVGAAIAAPVAGQQNVIDPWIRNNFVQAP 5262
            MKMASNDA PSDGS ANLVPEVNNEVMALEPVVGAAIAAPVAGQQNVIDPWIRNNFVQAP
Sbjct: 1    MKMASNDATPSDGSTANLVPEVNNEVMALEPVVGAAIAAPVAGQQNVIDPWIRNNFVQAP 60

Query: 5263 GGEFTVSPRNAPGEILWSAPLGPDLNPYLSHLARMYNGYAGGFEVQVILAGNAFTAGKII 5442
            GGEFTVSPRNAPGEILWSAPLGPDLNPYLSHLARMYNGYAGGFEVQVILAGNAFTAGKII
Sbjct: 61   GGEFTVSPRNAPGEILWSAPLGPDLNPYLSHLARMYNGYAGGFEVQVILAGNAFTAGKII 120

Query: 5443 FAAVPPNFPTEGLSPSQVTMFPHIIVDVRQLEPVLIPLPDVRNNFYHYNQSNDSTIKLIA 5622
            FAAVPPNFPTE LSPSQVTMFPHIIVDVRQLEPVLIPLPDVRNN YHYNQSND TI+LIA
Sbjct: 121  FAAVPPNFPTEVLSPSQVTMFPHIIVDVRQLEPVLIPLPDVRNNLYHYNQSNDPTIRLIA 180

Query: 5623 MLYTPLRANNGWGDVFTVSCRVLTRPSPDFDFIFLVPPTVESRTKPFTVPILTVEEMTNS 5802
            MLYTPLRANN   DVFTVSCRVLTRPSPDFDFIFLVPPTVESRTKPF+VPILTVEEMTNS
Sbjct: 181  MLYTPLRANNAGDDVFTVSCRVLTRPSPDFDFIFLVPPTVESRTKPFSVPILTVEEMTNS 240

Query: 5803 RFPIPLEKLFTGPSGAFVVQPQNGRCTTDGVLLGTTQLSPVNICTFRGDVTHIAGSRNYT 5982
            RFPIPLEKLFTGPS AFVVQPQNGRCTTDGVLLGTTQLSPVNICTFRGDVTHIAG++NYT
Sbjct: 241  RFPIPLEKLFTGPSSAFVVQPQNGRCTTDGVLLGTTQLSPVNICTFRGDVTHIAGTQNYT 300

Query: 5983 MNLASLNWNNYDPTEEIPAPLGTPDFVGKIQGVLTQTTKGDGSTRGHKATVYTGSAPFTP 6162
            MNLAS NWNNYDPTEEIPAPLGTPDFVG+IQGVLTQTT+ DGSTRGHKATV TGS  FTP
Sbjct: 301  MNLASQNWNNYDPTEEIPAPLGTPDFVGRIQGVLTQTTRRDGSTRGHKATVSTGSVHFTP 360

Query: 6163 KLGSVQFSTDTENDFETHQNTKFTPVGVIQDGGTTHRNEPQQWVLPSYSGRDVHNVHLAP 6342
            KLGSVQFSTDT NDFET QNT+FTPVGV+QDG TTH+NEPQQWVLP YSGRD HNVHLAP
Sbjct: 361  KLGSVQFSTDTSNDFETGQNTRFTPVGVVQDGSTTHQNEPQQWVLPDYSGRDSHNVHLAP 420

Query: 6343 AVAPTFPGEQLLFFRSTMPGCSGYPNMDLDCLLPQEWVQHFYQEAAPAQSDVALLRFVNP 6522
            AVAPTFPGEQLLFFRSTMPGCSGYPNM+LDCLLPQEWVQHFYQE+APAQSDVALLRFVNP
Sbjct: 421  AVAPTFPGEQLLFFRSTMPGCSGYPNMNLDCLLPQEWVQHFYQESAPAQSDVALLRFVNP 480

Query: 6523 DTGRVLFECKLHKSGYVTVAHTGQHDLVIPPQWLF 6627
            DTGRVLFECKLHKSGYVTVAHTGQHDLVIPP   F
Sbjct: 481  DTGRVLFECKLHKSGYVTVAHTGQHDLVIPPNGYF 515

------------------------------------------------------------
frameshifted from +1 to +2 between 6388-6850
  6388 TCCACTATGCCCGGATGCAGCGGGTATCCCAACATGGATTTGGATTGCCTACTCCCCCAG 6447  
  6448 GAGTGGGTGCAGCACTTCTACCAAGAGGCAGCTCCAGCACAATCTGATGTGGCTCTATTG 6507  
  6508 AGATTTGTGAATCCAGACACGGGCAGGGTCCTGTTTGAGTGCAAACTTCATAAATCAGGC 6567  
  6568 TATGTCACAGTGGCTCACACCGGTCAGCATGATTTGGTCATCCCCCCCCAATGGCTATTT 6627  
  6628 TAGGTTTGATTCGTGGGTTAATCAGTTTTACACACTTGCCCCCATGGGAAACGGAACGGG 6687  
  6688 GCGTAGGCGCGCTTTATAATGGCTGGAGCTTTCTTTGCTGGATTGGCATCTGATGTCCTT 6747  
  6748 GGCTCTGGACTTGGTTCCCTAATCAATGCTGGGGCTGGGGCTATCAACCAAAAGATTGAT 6807  
  6808 TTTGAAAATAATAGAAAATTGCAGCAAGCTTCTTTCCAGTTTA                  6850  
 frame +1
  6388  s -T--M--P--G--C--S--G--Y--P--N--M- d -L--D--C--L--L--P--Q- 6447   |
  6448 -E--W--V--Q--H--F--Y--Q--E- a -A--P--A--Q--S--D--V--A--L--L- 6507   |
  6508 -R--F--V--N--P--D--T--G--R--V--L--F--E--C--K--L--H--K--S--G- 6567   |
  6568 -Y--V--T--V--A--H--T--G--Q--H--D--L--V--I--P--P- q  w  l -F- 6627   |
  6628  *  v  *  f  v  g  *  s  v  l  h  t  c -P- h -G- k  r  n -G- 6687  
  6688  a  *  a  r  f  i  m  a  g  a  f  f  a  g  l  a  s  d  v  l  6747  
  6748  g  s  g  l  g  s  l  i  n  a  g  a  g  a  i  n  q  k  i  d  6807  
  6808  f  e  n  n  r  k  l  q  q  a  s  f  q  f                    6850  
 frame +2
  6388   p  l  c -P- d  a  a -G- i -P- t  w  i  w  i  a  y  s -P- r 6447  
  6448   s  g  c  s  t  s  t  k  r  q  l  q  h  n  l  m  w  l  y  * 6507  
  6508   d  l  *  i  q  t  r  a  g  s  c  l  s  a  n  f  i  n  q  a 6567  
  6568   m  s  q  w  l  t  p  v  s  m  i  w  s  s -P--P--N--G--Y--F 6627   |
  6628 --R--F--D--S--W--V--N--Q--F--Y--T--L--A--P--M--G--N--G- t -G 6687   |
  6688 --R--R--R--A--L- *  w  l  e  l  s  l  l  d  w  h  l  m  s  l 6747   |
  6748   a  l  d  l  v  p  *  s  m  l  g  l  g  l  s  t  k  r  l  i 6807  
  6808   l  k  i  i  e  n  c  s  k  l  l  s  s  l                   6850  
 frame +3
  6388    h  y  a  r  m  q  r  v  s  q  h  g  f -G- l  p  t  p -P-  6447  
  6448 g  v  g  a  a  l -L- p  r  g  s  s  s  t  i  *  c  g  s  i   6507  
  6508 e  i  c  e -S- r  h  g  q  g  p  v  *  v  q  t  s  *  i  r - 6567  
  6568 L- c  h  s  g  s -H- r -S- a  *  f  g  h  p  p  p  m  a  i   6627  
  6628 l  g  l -I- r  g  l  i  s -F- t  h  l  p  p  w  e  t  e  r   6687  
  6688 g  v  g  a  l  y -N--G- w  s  f  l  c  w  i  g  i  *  c  p   6747  
  6748 w  l  w  t  w  f  p  n  q  c  w  g  w  g  y  q  p  k  d  *   6807  
  6808 f  *  k  *  *  k  i  a  a  s  f  f  p  v                     6850  

reference sequence 436-540
TMPGCSGYPNMNLDCLLPQEWVQHFYQESAPAQSDVALLRFVNPDTGRVLFECKLHKSGY
VTVAHTGQHDLVIPPNGYFRFDSWVNQFYTLAPMGNGAGRRRAL
------------------------------------------------------------

Score =  81.3 bits (171), Expect(2) = 0.0
Identities = 30/31 (96%), Positives = 30/31 (96%)
Frame = +2

Query: 6611 PPNGYFRFDSWVNQFYTLAPMGNGTGRRRAL 6703
            PPNGYFRFDSWVNQFYTLAPMGNG GRRRAL
Sbjct: 510  PPNGYFRFDSWVNQFYTLAPMGNGAGRRRAL 540


========================================================================================================================

gene_id            %id    %sim   %cov   %t5   %gap  %t3   start..stop      pep sz ref sz ref id            definition
7.1                94.7   98.9   100.0  0.0   0.0   0.0   3..542           1701   1699   ACT76138.1        POL | nonstructural polyprotein
                                                          541..5106                                        
                    frameshift in genome at or near position 542..541 (+3=>+1)
7.1.1              93.1   97.5   100.0  0.0   0.0   0.0   3..542           332    330    NOROV_MP1         protein p48
                                                          541..996                                         
7.1.2              96.7   99.2   100.0  0.0   0.0   0.0   997..2094        366    366    NOROV_MP2         NTPase
7.1.3              93.3   99.3   100.0  0.0   0.0   0.0   2095..2631       179    179    NOROV_MP3         protein p22
7.1.4              97.7   100.0  100.0  0.0   0.0   0.0   2632..3030       133    133    NOROV_MP4         viral genome-linked protein
7.1.5              100.0  100.0  100.0  0.0   0.0   0.0   3031..3573       181    181    tr|G1FEL2         3C-like protease
7.1.6              99.8   100.0  100.0  0.0   0.0   0.0   3574..5103       510    510    ABV55633.1        RNA-directed RNA polymerase

CLUSTAL 2.1 multiple sequence alignment


predicted       MKMASNDASAAAVANSNNDTAKSSSDKMFSSMAVTFKRALGARPKQPPPRETPQRPPRPP
reference       MKMASNDASAAAVANSNNDTAKSSSDGVLSSMAVTFKRALGARPKQPPPREIPQRPPRPP
                ************************** ::********************** ********

predicted       TPELVKKIPPPPPNGEDEVVVSYSAKDGVSGLPELSTVRQPEETNTAFSVPPLNQRENRD
reference       TPELIKKVPPPPPNGEDEPVVSYNAKNGVSGLPELSTVRQPDENNTAFSVPPLNQRENRD
                ****:**:********** ****.**:**************:*.****************

predicted       AKEPLTGTILEMWDGEIYHYGLYVERGLVLGGGTQPPAAISLAKVELTPLSLFWRPVYTP
reference       AKEPLTGTILEMWDGEIYHYGLYVERGLVLG-VHKPPAAISLAKVELTPLSLFWRPVYTP
                *******************************   :*************************

predicted       PQYLISPDTLKKLHGETFPYTAFDNNCYAFCCWVLDLNDSWLSRRMIQRTTGFFRPYQDW
reference       -QYLISPDTLRRLHGESFPYTAFDNNCYAFCCWVLDLNDSWLSRRMIQRTTGFFRPYQDW
                 *********::****:*******************************************

predicted       NRKPLPTIDDSKLKKVANIFLCALSSLFTRPIKDIIGKLRPLNIINILASCDWTFAGIVE
reference       NRKPLPTMDDSKLKKVANIFLCALSSLFTRPIKDIIGKLKPLNILNILASCDWTFAGIVE
                *******:*******************************:****:***************

predicted       SLILLAELFGVFWTPPDVSAMIAPLLGDFELQGPEDLVVELVPVVMGGIGLVLGFTKEKI
reference       SLILLAELFGVFWTPPDVSAMIAPLLGDYELQGPEDLAVELVPVVMGGIGLVLGFTKEKI
                ****************************:********.**********************

predicted       GKMLSSAASTLRACKDLGAYGLEIXKLVMKWFFPKKEEANELXMVRSIEDAVLDLEAIEN
reference       GKMLSSAASTLRACKDLGAYGLEILKLVMKWFFPKKEEASELAMVRSIEDAVLDLEAIEN
                ************************ **************.** *****************

predicted       NHMTTLLKDKDSLATYMRTLDLEEEKARKLSTKSASPDIVGTINALLARIAAARSLVHRA
reference       NHLTTLLKDKDSLATYMRTLDLEEEKARKLSTKSASPDIVGTINALLARIAAARSLVHRA
                **:*********************************************************

predicted       KEELSSRPRPVVLMISGRPGIGKTHLAREVAKRIAASLTGDQRVGLIPRNGVDHWDAYKG
reference       KEELSSRPRPVVVMISGKPGIGKTHLARELAKKIATTLTGDQRVGLIPRNGVDHWDAYKG
                ************:****:***********:**:**::***********************

predicted       ERVVLWDDYGMSNPIHDALRLQELADTCPLTLNCDRIENKGKVFDSDVIIITTNLANPAP
reference       ERVVLWDDYGMSNPIHDALRLQELADTCPLTLNCDRIENKGKVFDSDAIIITTNLANPAP
                ***********************************************.************

predicted       LDYVNFEACSRRIDFLVYAEAPEVEKAKRDFPGQPDMWKNAFSSDFSHIKLALAPQGGFD
reference       LDYVNFEACSRRIDFLVYAEAPDVEKAKRDFPGQPDMWKNAFSPDFSHIKLMLAPQGGFD
                **********************:********************.******* ********

predicted       KNGNTPHGKGVMKTLTTGSLIARASGLLHERLDEFELQGPALTTFNFDRNKVLAFRQLAA
reference       KNGNTPHGKGVMKTLTIGSLIARASGLLHERLDEYELQGPALTTFNFDRNKVLAFRQLAA
                **************** *****************:*************************

predicted       ENKYGLMDTMKVGRQLKDVKTMPELKQALKNISIKKCQIVYSGCTYTLESDGKGNVKVDR
reference       ENKYGLMDTMRVGGQLKGVRTMPELKQALKNISIKRCQIVYGGSTYTLESDGKGSVRVDR
                **********:** ***.*:***************:*****.*.**********.*:***

predicted       VQSTSVQTNNELAGALHHLRCARIRYYVKCVQEALYSIIQIAGAAFVTTRIIKRVNIQDL
reference       VQSATVQTNNELAGALHHLRCARIRYYVKCVQEALYSIIQIAGAAFVTTRIVKRMNIQDL
                ***::**********************************************:**:*****

predicted       WSKPQVENTEEATNKDGCPKPKDDEEFVISSDDIKTEGKKGKNKAGRGKKHTAFSSKGLS
reference       WSKPQLEDTEEATGKDGCPKPKDDEEFVVSSDDIKVEGKKGKNKTGRGKKHTAFSSKGLS
                *****:*:*****.**************:******.********:***************

predicted       DEEYDEYKRIREERNGKYSIEEYLQDRDKYYEEVAIARATEEDFCEEEEAKIRQRIFRPT
reference       DEEYDEYKRIREERNGKYSIEEYLQDRDKYYEEVAIARATEEDFCEEEEAKIRQRIFRPT
                ************************************************************

predicted       RKQRKEERASLGLVTGSEIRKRNPEDFKPKGKLWADDDRSVDYNEKLSFEAPPSIWSRIV
reference       RKQRKEERASLGLVTGSEIRKRNPDDFKPKGKLWADDDRSVDYNEKLSFEAPPSIWSRIV
                ************************:***********************************

predicted       NFGSGWGFWVSPSLFITSTHVIPQGAKEFFGVPIKQIQVHKSGEFCRLRFPKPIRTDVTG
reference       NFGSGWGFWVSPSLFITSTHVIPQGTQEFFGVSIKQIQIHKSGEFCRLRFPKPIRTDVTG
                *************************::*****.*****:*********************

predicted       MILEEGAPEGTVVTLLIKRSTGELMPLAARMGTHATMKIQGRTVGGQMGMLLTGSNAKSM
reference       MILEEGAPEGTVATLLIKRPTGELMPLAARMGTHATMKIQGRTVGGQMGMLLTGSNAKSM
                ************.******.****************************************

predicted       DLGTTPGDCGCPYIYKRGNDYVVIGVHTAAARGGNTVICATQGGEGEATLEGGDSKGTYC
reference       DLGTTPGDCGCPYIYKRGNDYVVIGVHTAAARGGNTVICATQGSEGEATLEGGDNKGTYC
                *******************************************.**********.*****

predicted       GAPILGPGSAPKLSTKTKFWRSSTAPLPPGTYEPAYLGGKDPRVKGGPSLQQVMRDQLKP
reference       GAPILGPGSAPKLSTKTKFWRSSTAPLPPGTYEPAYLGGKDPRIKGGPSLQQVMRDQLKP
                *******************************************:****************

predicted       FTEPRGKPPKPSVLEAAKKTIINVLEQTIDPPEKWSFAQACASLDKTTSSGHPHHLRKND
reference       FTEPRGKQPKPSVLEAAKRTIINVLEQTIDPPQKWTFAQACASLDKTTSSGHPHHIRKNE
                ******* **********:*************:**:*******************:***:

predicted       CWNGESFTGKLADQASKANLMFEEGKNMTPVYTGALKDELVKTDKIYGKIKKRLLWGSDL
reference       CWNGDSFTGKLADQASKANLMFEEGKNMTPVYTGALKDELVKTDKIYGKIKKRLLWGSDL
                ****:*******************************************************

predicted       ATMIRCARAFGGLMDELKAHCVTLPIRVGMNMNEDGPIIFEKHSRYRYHYDADYSRWDST
reference       ATMIRCARAFGGLMDELKAHCVTLPVRVGMNMNEDGPIIFEKHSRYRYHYDADYSRWDST
                *************************:**********************************

predicted       QQRAVLAAALEIMVKFSSEPHLAQVVAEDLLSPSVVDVGDFTISINEGLPSGVPCTSQWN
reference       QQRAILAAALEIMVKFSPEPHLAQIVAEDLLSPSVMDVGDFKISINEGLPSGVPCTSQWN
                ****:************.******:**********:*****.******************

predicted       SIAHWLLTLCALSEVTNLSPDIIQANSLFSFYGDDEIVSTDIKLDPEKLTAKLKEYGLKP
reference       SIAHWLLTLCALSEVTDLSPDIVQANSLFSFYGDDEIVSTDIKLDPEKLTAKLKEYGLKP
                ****************:*****:*************************************

predicted       TRPDKTEGPLVISEDLDGLTFLRRTVTRDPAGWFGKLEQSSILRQMYWTRGPNHEDPSES
reference       TRPDKTEGPLIISEDLNGLTFLRRTVTRDPAGWFGKLEQSSILRQMYWTRGPNHEDPSET
                **********:*****:******************************************:

predicted       MIPHSQRPIQLMSLLGEAALHGPTFYSKISKLVIAELKEGGMDFYVPRQEPMFRWMRFSD
reference       MIPHSQRPTQLMSLLGEAALHGPAFYSKISKLVITELKEGGMDFYVPRQEPMFRWMRFSD
                ******** **************:**********:*************************

predicted       LSTWEGDRNLAPSFVNEDGVE
reference       LSTWEGDRNLAPSFVNEDGVE
                *********************

>7.1	3	5106
gaATGAAGATGGCGTCTAACGACGCTTCCGCTGCCGCTGTTGCTAACAGCAACAACGACA
CCGCAAAATCTTCAAGTGACAAAATGTTTTCTAGCATGGCTGTCACTTTTAAACGAGCCC
TCGGGGCGCGGCCTAAACAGCCCCCCCCGAGGGAAACACCACAAAGACCCCCACGACCAC
CTACTCCAGAACTGGTCAAAAAGATCCCTCCTCCCCCGCCCAACGGAGAGGATGAAGTAG
TGGTTTCTTATAGTGCCAAAGATGGCGTTTCCGGTTTACCTGAGCTTTCCACCGTCAGGC
AACCGGAAGAAACCAATACGGCCTTCAGTGTCCCTCCACTCAACCAGAGGGAGAATAGAG
ATGCTAAGGAACCACTGACTGGAACAATTCTGGAAATGTGGGATGGAGAAATCTACCATT
ATGGCCTGTATGTTGAGCGAGGTCTTGTGCTGGGTGGTGGCACACAACCACCAGCTGCCA
TAAGCCTCGCCAAGGTCGAACTAACACCACTCTCCTTGTTCTGGAGACCTGTGTACACTC
CCCCAGTACCTCATCTCTCCAGACACTCTCAAGAAATTACACGGAGAAACGTTTCCCTAC
ACAGCCTTTGACAACAATTGCTATGCCTTTTGTTGTTGGGTCCTGGATCTAAATGACTCG
TGGCTGAGTAGGAGAATGATCCAGAGAACAACTGGCTTCTTCAGACCCTACCAAGACTGG
AATAGGAAACCCCTCCCCACTATAGATGACTCCAAATTAAAGAAGGTAGCTAACATTTTC
CTGTGCGCCCTGTCTTCGCTATTCACCAGGCCCATAAAAGACATAATAGGAAAGCTAAGA
CCTCTCAACATCATCAACATCCTGGCTTCATGTGATTGGACTTTCGCAGGCATAGTGGAG
TCCTTGATACTCTTGGCAGAGCTCTTTGGAGTCTTCTGGACACCCCCAGATGTGTCTGCG
ATGATTGCCCCCTTACTCGGTGATTTCGAGTTACAAGGACCTGAGGACCTTGTAGTGGAG
CTCGTCCCTGTAGTAATGGGGGGAATTGGTTTGGTGCTGGGATTCACCAAAGAGAAGATT
GGAAAAATGTTGTCATCTGCTGCATCCACCTTGAGAGCTTGTAAAGATCTTGGTGCATAT
GGGCTAGAGATCYTAAAGTTAGTCATGAAGTGGTTCTTCCCGAAGAAAGAGGAGGCAAAT
GAACTGGMTATGGTGAGATCCATCGAGGATGCAGTACTGGACCTTGAGGCAATTGAAAAC
AACCATATGACCACCTTGCTCAAAGACAAAGACAGCCTGGCAACCTACATGAGAACCCTT
GACCTCGAGGAAGAGAAAGCCAGAAAACTCTCAACCAAGTCTGCTTCACCTGACATCGTG
GGCACAATCAACGCCCTTCTGGCGAGAATCGCCGCTGCACGCTCCCTGGTGCACCGAGCG
AAGGAGGAGCTTTCCAGCAGACCAAGACCTGTAGTCTTGATGATATCAGGCAGACCAGGG
ATAGGGAAGACCCACCTTGCTAGGGAAGTGGCTAAGAGAATCGCAGCCTCCCTCACAGGA
GACCAGCGTGTAGGCCTCATCCCACGCAATGGCGTCGATCACTGGGATGCGTACAAGGGG
GAGAGGGTCGTCCTATGGGACGACTATGGAATGAGCAATCCCATCCACGACGCCCTCAGG
CTGCAAGAACTCGCTGACACTTGCCCCCTCACTCTAAATTGTGACAGGATTGAGAATAAA
GGAAAGGTCTTTGACAGCGATGTCATCATTATCACTACTAATCTGGCCAACCCAGCACCA
CTGGACTATGTCAACTTTGAAGCGTGCTCGAGGCGCATCGATTTCCTCGTGTATGCAGAA
GCCCCCGAGGTCGAAAAGGCGAAGCGTGACTTCCCGGGCCAACCTGATATGTGGAAAAAC
GCTTTTAGTTCTGATTTCTCACACATAAAATTGGCACTGGCTCCACAAGGTGGCTTTGAT
AAGAACGGGAACACCCCACACGGGAAGGGCGTCATGAAGACTCTCACCACTGGCTCCCTC
ATTGCCCGGGCATCAGGGCTGCTCCATGAGAGATTGGATGAGTTTGAACTACAGGGCCCA
GCTCTTACCACCTTCAACTTTGACCGCAACAAAGTGCTTGCCTTCAGGCAGCTTGCTGCT
GAAAACAAATATGGGTTGATGGACACAATGAAAGTTGGGAGGCAGCTCAAGGATGTCAAA
ACCATGCCAGAACTTAAACAAGCACTCAAGAATATCTCAATCAAGAAGTGCCAGATTGTG
TATAGTGGTTGCACCTACACACTTGAGTCTGATGGCAAGGGCAATGTGAAAGTTGACAGA
GTTCAGAGCACCTCCGTACAGACCAACAATGAGCTGGCTGGCGCCCTGCACCATCTAAGG
TGCGCCAGAATCAGGTACTATGTCAAGTGTGTCCAGGAGGCCCTGTATTCTATCATCCAG
ATTGCTGGGGCTGCATTTGTCACCACGCGCATCATCAAGCGTGTGAACATTCAAGACTTA
TGGTCCAAGCCACAAGTGGAAAACACAGAGGAGGCTACCAACAAGGACGGGTGCCCAAAA
CCCAAAGATGATGAGGAGTTCGTCATTTCATCTGACGACATTAAAACTGAGGGTAAGAAA
GGGAAGAACAAGGCTGGCCGTGGCAAGAAGCACACAGCCTTCTCAAGTAAAGGTCTCAGT
GATGAAGAGTATGATGAGTACAAGAGAATTAGAGAGGAAAGGAATGGCAAGTACTCCATA
GAGGAGTACCTTCAGGACAGGGACAAATACTATGAGGAGGTGGCCATTGCCAGGGCGACC
GAGGAAGACTTCTGTGAAGAGGAGGAGGCCAAGATCCGGCAAAGGATCTTCAGACCAACA
AGGAAACAACGCAAGGAAGAAAGAGCTTCTCTCGGTTTAGTCACAGGTTCTGAAATTAGG
AAAAGAAACCCAGAAGACTTCAAGCCCAAGGGGAAACTATGGGCTGACGATGACAGAAGT
GTGGACTACAATGAGAAACTCAGTTTTGAGGCCCCACCAAGCATCTGGTCAAGGATAGTC
AACTTTGGCTCAGGTTGGGGTTTTTGGGTCTCCCCCAGCCTGTTCATAACATCAACCCAC
GTCATACCCCAAGGTGCAAAGGAGTTCTTTGGAGTCCCCATCAAACAAATTCAGGTACAC
AAGTCAGGCGAGTTCTGTCGCTTGAGGTTCCCAAAACCAATCAGGACTGATGTGACTGGC
ATGATCTTGGAAGAAGGTGCGCCCGAAGGCACCGTGGTCACACTACTCATCAAAAGGTCT
ACTGGAGAACTCATGCCCCTAGCAGCTAGAATGGGGACCCATGCAACCATGAAAATTCAA
GGGCGCACTGTTGGAGGTCAGATGGGTATGCTTCTGACAGGATCCAACGCCAAAAGCATG
GATCTAGGCACCACACCAGGTGATTGCGGCTGTCCCTACATCTACAAGAGAGGAAATGAC
TATGTGGTCATTGGAGTCCACACGGCTGCCGCTCGTGGGGGAAACACTGTCATATGTGCC
ACCCAGGGGGGTGAGGGGGAAGCTACACTTGAAGGTGGTGACAGTAAGGGAACATACTGT
GGTGCACCAATCCTAGGCCCAGGGAGTGCCCCAAAACTTAGCACCAAAACCAAATTCTGG
AGATCATCCACAGCACCACTCCCACCTGGCACCTATGAACCAGCCTACCTTGGTGGCAAG
GACCCCAGAGTCAAGGGTGGCCCCTCGTTGCAGCAAGTCATGAGGGACCAGCTGAAACCA
TTTACAGAGCCCAGGGGTAAGCCACCAAAGCCAAGTGTGTTAGAAGCTGCCAAGAAAACC
ATCATCAATGTCCTTGAACAAACAATTGACCCACCTGAGAAGTGGTCGTTCGCACAAGCT
TGCGCGTCCCTTGACAAGACCACTTCTAGCGGCCATCCGCACCACTTGCGGAAAAACGAC
TGCTGGAACGGGGAATCCTTCACAGGCAAGCTGGCAGACCAGGCTTCCAAGGCCAACCTG
ATGTTTGAAGAAGGGAAAAACATGACCCCAGTCTACACAGGTGCACTTAAGGATGAATTA
GTCAAAACTGACAAAATTTATGGTAAGATCAAGAAGAGGCTTCTCTGGGGCTCGGATTTA
GCAACCATGATCCGGTGTGCTCGAGCATTCGGAGGCCTAATGGATGAACTCAAAGCACAC
TGTGTCACACTTCCTATCAGAGTTGGTATGAATATGAATGAGGATGGCCCCATCATCTTC
GAGAAGCATTCCAGGTACAGATACCACTATGATGCTGATTACTCTCGGTGGGATTCAACA
CAACAGAGAGCCGTGCTGGCAGCTGCTCTAGAAATCATGGTTAAATTCTCCTCAGAACCA
CATTTGGCTCAGGTAGTCGCAGAAGACCTTCTTTCTCCTAGCGTGGTGGATGTGGGTGAC
TTCACAATATCAATCAACGAGGGTCTTCCCTCTGGGGTGCCCTGCACCTCCCAATGGAAC
TCCATCGCCCACTGGCTTCTCACTCTCTGTGCACTCTCCGAAGTTACAAATTTGTCTCCA
GACATCATACAGGCTAATTCTCTCTTCTCCTTCTATGGTGATGATGAAATTGTTAGTACA
GACATAAAATTAGACCCAGAGAAGTTGACAGCAAAGCTTAAGGAATATGGGTTGAAACCA
ACCCGCCCTGATAAAACTGAAGGACCTCTTGTTATTTCTGAAGACTTAGATGGTTTGACT
TTCCTGCGGAGAACTGTGACCCGCGACCCAGCTGGTTGGTTTGGAAAACTGGAGCAGAGC
TCAATACTCAGGCAAATGTACTGGACTAGGGGCCCCAACCATGAAGATCCATCTGAATCA
ATGATTCCACACTCTCAGAGACCCATACAATTGATGTCCTTACTGGGAGAGGCCGCACTC
CACGGCCCAACATTCTACAGTAAAATCAGCAAATTAGTCATTGCAGAGCTAAAAGAAGGT
GGTATGGATTTTTACGTGCCCAGGCAAGAGCCAATGTTCAGATGGATGAGATTCTCAGAT
CTGAGCACGTGGGAGGGCGATCGCAATCTGGCTCCCAGTTTTGTGAATGAAGATGGCGTC
GAATGAcgccaacccatctgatgggtccgcagccaacctcgtcccagaggtcaacaatga
ggttatggctttggagcccgttgtcggtgccgctattgcggcgcctgtagcgggccaaca
aaatgtaattgacccctggattagaaataattttgtacaagcccctggtggagagttcac
agtatcccctagaaacgctccaggtgaaatactatggagcgcgcccttaggccctgatct
gaatccctacctatctcatttggccagaatgtataatggttatgcaggtggctttgaagt
gcag

Length = 1699

Score =   344 bits (745), Expect(3) = 0.0
Identities = 142/158 (89%), Positives = 148/158 (93%)
Frame = +3

Query: 3    MKMASNDASAAAVANSNNDTAKSSSDKMFSSMAVTFKRALGARPKQPPPRETPQRPPRPP 182
            MKMASNDASAAAVANSNNDTAKSSSD + SSMAVTFKRALGARPKQPPPRE PQRPPRPP
Sbjct: 1    MKMASNDASAAAVANSNNDTAKSSSDGVLSSMAVTFKRALGARPKQPPPREIPQRPPRPP 60

Query: 183  TPELVKKIPPPPPNGEDEVVVSYSAKDGVSGLPELSTVRQPEETNTAFSVPPLNQRENRD 362
            TPEL+KK+PPPPPNGEDE VVSY+AK+GVSGLPELSTVRQP+E NTAFSVPPLNQRENRD
Sbjct: 61   TPELIKKVPPPPPNGEDEPVVSYNAKNGVSGLPELSTVRQPDENNTAFSVPPLNQRENRD 120

Query: 363  AKEPLTGTILEMWDGEIYHYGLYVERGLVLGGGTQPPA 476
            AKEPLTGTILEMWDGEIYHYGLYVERGLVLG    P A
Sbjct: 121  AKEPLTGTILEMWDGEIYHYGLYVERGLVLGVHKPPAA 158

Score =  64.3 bits (134), Expect(3) = 0.0
Identities = 26/29 (89%), Positives = 27/29 (93%)
Frame = +3

Query: 456  GGTQPPAAISLAKVELTPLSLFWRPVYTP 542
            G  +PPAAISLAKVELTPLSLFWRPVYTP
Sbjct: 151  GVHKPPAAISLAKVELTPLSLFWRPVYTP 179

------------------------------------------------------------
frameshifted from +3 to +1 between 303-780
   303 CCGGAAGAAACCAATACGGCCTTCAGTGTCCCTCCACTCAACCAGAGGGAGAATAGAGAT 362   
   363 GCTAAGGAACCACTGACTGGAACAATTCTGGAAATGTGGGATGGAGAAATCTACCATTAT 422   
   423 GGCCTGTATGTTGAGCGAGGTCTTGTGCTGGGTGGTGGCACACAACCACCAGCTGCCATA 482   
   483 AGCCTCGCCAAGGTCGAACTAACACCACTCTCCTTGTTCTGGAGACCTGTGTACACTCCC 542   
   543 CCAGTACCTCATCTCTCCAGACACTCTCAAGAAATTACACGGAGAAACGTTTCCCTACAC 602   
   603 AGCCTTTGACAACAATTGCTATGCCTTTTGTTGTTGGGTCCTGGATCTAAATGACTCGTG 662   
   663 GCTGAGTAGGAGAATGATCCAGAGAACAACTGGCTTCTTCAGACCCTACCAAGACTGGAA 722   
   723 TAGGAAACCCCTCCCCACTATAGATGACTCCAAATTAAAGAAGGTAGCTAACATTTTC   780   
 frame +3
   303 -P- e -E- t -N--T--A--F--S--V--P--P--L--N--Q--R--E--N--R--D- 362    |
   363 -A--K--E--P--L--T--G--T--I--L--E--M--W--D--G--E--I--Y--H--Y- 422    |
   423 -G--L--Y--V--E--R--G--L--V--L--G- g  g  t  q -P- p -A- a  i  482    |
   483  s  l  a  k  v  e  l  t  p  l  s  l  f  w  r  p  v  y  t  p  542   
   543  p  v  p  h  l  s  r  h  s  q  e  i  t  r  r  n  v  s  l  h  602   
   603  s  l  *  q  q  l  l  c  l  l  l  l  g  p  g  s  k  *  l  v  662   
   663  a  e  *  e  n  d  p  e  n  n  w  l  l  q  t  l  p  r  l  e  722   
   723  *  e  t -P- p  h  y  r  *  l  q  i -K- e  g  s  *  h  f     780   
 frame +1
   303   r  k  k  p  i  r  p  s  v -S- l  h  s  t  r  g -R- i  e  m 362   
   363   l  r  n  h  * -L- e  q  f  w  k  c  g  m  e  k  s  t  i  m 422   
   423   a  c  m  l  s -E- v  l  c  w  v  v  a -H- n  h  q  l  p  * 482   
   483   a  s  p  r  s  n  *  h  h  s  p  c  s  g  d  l  c  t  l -P 542   
   543 --Q--Y--L--I--S--P--D--T--L- k  k -L--H--G--E- t -F--P--Y--T 602    |
   603 --A--F--D--N--N--C--Y--A--F--C--C--W--V--L--D--L--N--D--S--W 662    |
   663 --L--S--R--R--M--I--Q--R--T--T--G--F--F--R--P--Y--Q--D--W--N 722    |
   723 --R--K--P--L--P--T- i -D--D--S--K--L--K--K--V--A--N--I--F-   780    |
 frame +2
   303    g  r  n  q  y  g  l  q  c  p  s  t  q  p  e  g  e  *  r   362   
   363 c  * -G- t  t  d  w  n  n  s  g  n  v  g  w  r  n -L- p  l   422   
   423 w  p  v  c  * -A- r -S- c -A- g  w  w  h -T- t  t -S- c  h   482   
   483 k  p  r  q  g  r  t  n  t  t  l  l  v  l  e  t  c  v  h  s   542   
   543 p  s  t  s  s  l  q  t  l  s  r -N- y  t  e  k  r  f  p  t   602   
   603 q  p -L- t  t  i  a  m  p  f  v  v  g  s  w  i  *  m  t  r   662   
   663 g  *  v  g  e  *  s -R- e  q -L- a  s  s -D- p  t -K- t  g   722   
   723 i  g  n  p  s  p -L- *  m  t  p  n  *  r  r  *  l  t  f      780   

reference sequence 100-258
PDENNTAFSVPPLNQRENRDAKEPLTGTILEMWDGEIYHYGLYVERGLVLGVHKPPAAIS
LAKVELTPLSLFWRPVYTPQYLISPDTLRRLHGESFPYTAFDNNCYAFCCWVLDLNDSWL
SRRMIQRTTGFFRPYQDWNRKPLPTMDDSKLKKVANIFL
------------------------------------------------------------

Score =  3534 bits (7708), Expect(3) = 0.0
Identities = 1448/1521 (95%), Positives = 1495/1521 (98%)
Frame = +1

Query: 541  PQYLISPDTLKKLHGETFPYTAFDNNCYAFCCWVLDLNDSWLSRRMIQRTTGFFRPYQDW 720
            PQYLISPDTL++LHGE+FPYTAFDNNCYAFCCWVLDLNDSWLSRRMIQRTTGFFRPYQDW
Sbjct: 179  PQYLISPDTLRRLHGESFPYTAFDNNCYAFCCWVLDLNDSWLSRRMIQRTTGFFRPYQDW 238

Query: 721  NRKPLPTIDDSKLKKVANIFLCALSSLFTRPIKDIIGKLRPLNIINILASCDWTFAGIVE 900
            NRKPLPT+DDSKLKKVANIFLCALSSLFTRPIKDIIGKL+PLNI+NILASCDWTFAGIVE
Sbjct: 239  NRKPLPTMDDSKLKKVANIFLCALSSLFTRPIKDIIGKLKPLNILNILASCDWTFAGIVE 298

Query: 901  SLILLAELFGVFWTPPDVSAMIAPLLGDFELQGPEDLVVELVPVVMGGIGLVLGFTKEKI 1080
            SLILLAELFGVFWTPPDVSAMIAPLLGD+ELQGPEDL VELVPVVMGGIGLVLGFTKEKI
Sbjct: 299  SLILLAELFGVFWTPPDVSAMIAPLLGDYELQGPEDLAVELVPVVMGGIGLVLGFTKEKI 358

Query: 1081 GKMLSSAASTLRACKDLGAYGLEILKLVMKWFFPKKEEANELXMVRSIEDAVLDLEAIEN 1260
            GKMLSSAASTLRACKDLGAYGLEILKLVMKWFFPKKEEA+EL MVRSIEDAVLDLEAIEN
Sbjct: 359  GKMLSSAASTLRACKDLGAYGLEILKLVMKWFFPKKEEASELAMVRSIEDAVLDLEAIEN 418

Query: 1261 NHMTTLLKDKDSLATYMRTLDLEEEKARKLSTKSASPDIVGTINALLARIAAARSLVHRA 1440
            NH+TTLLKDKDSLATYMRTLDLEEEKARKLSTKSASPDIVGTINALLARIAAARSLVHRA
Sbjct: 419  NHLTTLLKDKDSLATYMRTLDLEEEKARKLSTKSASPDIVGTINALLARIAAARSLVHRA 478

Query: 1441 KEELSSRPRPVVLMISGRPGIGKTHLAREVAKRIAASLTGDQRVGLIPRNGVDHWDAYKG 1620
            KEELSSRPRPVV+MISG+PGIGKTHLARE+AK+IA +LTGDQRVGLIPRNGVDHWDAYKG
Sbjct: 479  KEELSSRPRPVVVMISGKPGIGKTHLARELAKKIATTLTGDQRVGLIPRNGVDHWDAYKG 538

Query: 1621 ERVVLWDDYGMSNPIHDALRLQELADTCPLTLNCDRIENKGKVFDSDVIIITTNLANPAP 1800
            ERVVLWDDYGMSNPIHDALRLQELADTCPLTLNCDRIENKGKVFDSD IIITTNLANPAP
Sbjct: 539  ERVVLWDDYGMSNPIHDALRLQELADTCPLTLNCDRIENKGKVFDSDAIIITTNLANPAP 598

Query: 1801 LDYVNFEACSRRIDFLVYAEAPEVEKAKRDFPGQPDMWKNAFSSDFSHIKLALAPQGGFD 1980
            LDYVNFEACSRRIDFLVYAEAP+VEKAKRDFPGQPDMWKNAFS DFSHIKL LAPQGGFD
Sbjct: 599  LDYVNFEACSRRIDFLVYAEAPDVEKAKRDFPGQPDMWKNAFSPDFSHIKLMLAPQGGFD 658

Query: 1981 KNGNTPHGKGVMKTLTTGSLIARASGLLHERLDEFELQGPALTTFNFDRNKVLAFRQLAA 2160
            KNGNTPHGKGVMKTLT GSLIARASGLLHERLDE+ELQGPALTTFNFDRNKVLAFRQLAA
Sbjct: 659  KNGNTPHGKGVMKTLTIGSLIARASGLLHERLDEYELQGPALTTFNFDRNKVLAFRQLAA 718

Query: 2161 ENKYGLMDTMKVGRQLKDVKTMPELKQALKNISIKKCQIVYSGCTYTLESDGKGNVKVDR 2340
            ENKYGLMDTM+VG QLK V+TMPELKQALKNISIK+CQIVY G TYTLESDGKG+V+VDR
Sbjct: 719  ENKYGLMDTMRVGGQLKGVRTMPELKQALKNISIKRCQIVYGGSTYTLESDGKGSVRVDR 778

Query: 2341 VQSTSVQTNNELAGALHHLRCARIRYYVKCVQEALYSIIQIAGAAFVTTRIIKRVNIQDL 2520
            VQS +VQTNNELAGALHHLRCARIRYYVKCVQEALYSIIQIAGAAFVTTRI+KR+NIQDL
Sbjct: 779  VQSATVQTNNELAGALHHLRCARIRYYVKCVQEALYSIIQIAGAAFVTTRIVKRMNIQDL 838

Query: 2521 WSKPQVENTEEATNKDGCPKPKDDEEFVISSDDIKTEGKKGKNKAGRGKKHTAFSSKGLS 2700
            WSKPQ+E+TEEAT KDGCPKPKDDEEFV+SSDDIK EGKKGKNK GRGKKHTAFSSKGLS
Sbjct: 839  WSKPQLEDTEEATGKDGCPKPKDDEEFVVSSDDIKVEGKKGKNKTGRGKKHTAFSSKGLS 898

Query: 2701 DEEYDEYKRIREERNGKYSIEEYLQDRDKYYEEVAIARATEEDFCEEEEAKIRQRIFRPT 2880
            DEEYDEYKRIREERNGKYSIEEYLQDRDKYYEEVAIARATEEDFCEEEEAKIRQRIFRPT
Sbjct: 899  DEEYDEYKRIREERNGKYSIEEYLQDRDKYYEEVAIARATEEDFCEEEEAKIRQRIFRPT 958

Query: 2881 RKQRKEERASLGLVTGSEIRKRNPEDFKPKGKLWADDDRSVDYNEKLSFEAPPSIWSRIV 3060
            RKQRKEERASLGLVTGSEIRKRNP+DFKPKGKLWADDDRSVDYNEKLSFEAPPSIWSRIV
Sbjct: 959  RKQRKEERASLGLVTGSEIRKRNPDDFKPKGKLWADDDRSVDYNEKLSFEAPPSIWSRIV 1018

Query: 3061 NFGSGWGFWVSPSLFITSTHVIPQGAKEFFGVPIKQIQVHKSGEFCRLRFPKPIRTDVTG 3240
            NFGSGWGFWVSPSLFITSTHVIPQG +EFFGV IKQIQ+HKSGEFCRLRFPKPIRTDVTG
Sbjct: 1019 NFGSGWGFWVSPSLFITSTHVIPQGTQEFFGVSIKQIQIHKSGEFCRLRFPKPIRTDVTG 1078

Query: 3241 MILEEGAPEGTVVTLLIKRSTGELMPLAARMGTHATMKIQGRTVGGQMGMLLTGSNAKSM 3420
            MILEEGAPEGTV TLLIKR TGELMPLAARMGTHATMKIQGRTVGGQMGMLLTGSNAKSM
Sbjct: 1079 MILEEGAPEGTVATLLIKRPTGELMPLAARMGTHATMKIQGRTVGGQMGMLLTGSNAKSM 1138

Query: 3421 DLGTTPGDCGCPYIYKRGNDYVVIGVHTAAARGGNTVICATQGGEGEATLEGGDSKGTYC 3600
            DLGTTPGDCGCPYIYKRGNDYVVIGVHTAAARGGNTVICATQG EGEATLEGGD+KGTYC
Sbjct: 1139 DLGTTPGDCGCPYIYKRGNDYVVIGVHTAAARGGNTVICATQGSEGEATLEGGDNKGTYC 1198

Query: 3601 GAPILGPGSAPKLSTKTKFWRSSTAPLPPGTYEPAYLGGKDPRVKGGPSLQQVMRDQLKP 3780
            GAPILGPGSAPKLSTKTKFWRSSTAPLPPGTYEPAYLGGKDPR+KGGPSLQQVMRDQLKP
Sbjct: 1199 GAPILGPGSAPKLSTKTKFWRSSTAPLPPGTYEPAYLGGKDPRIKGGPSLQQVMRDQLKP 1258

Query: 3781 FTEPRGKPPKPSVLEAAKKTIINVLEQTIDPPEKWSFAQACASLDKTTSSGHPHHLRKND 3960
            FTEPRGK PKPSVLEAAK+TIINVLEQTIDPP+KW+FAQACASLDKTTSSGHPHH+RKN+
Sbjct: 1259 FTEPRGKQPKPSVLEAAKRTIINVLEQTIDPPQKWTFAQACASLDKTTSSGHPHHIRKNE 1318

Query: 3961 CWNGESFTGKLADQASKANLMFEEGKNMTPVYTGALKDELVKTDKIYGKIKKRLLWGSDL 4140
            CWNG+SFTGKLADQASKANLMFEEGKNMTPVYTGALKDELVKTDKIYGKIKKRLLWGSDL
Sbjct: 1319 CWNGDSFTGKLADQASKANLMFEEGKNMTPVYTGALKDELVKTDKIYGKIKKRLLWGSDL 1378

Query: 4141 ATMIRCARAFGGLMDELKAHCVTLPIRVGMNMNEDGPIIFEKHSRYRYHYDADYSRWDST 4320
            ATMIRCARAFGGLMDELKAHCVTLP+RVGMNMNEDGPIIFEKHSRYRYHYDADYSRWDST
Sbjct: 1379 ATMIRCARAFGGLMDELKAHCVTLPVRVGMNMNEDGPIIFEKHSRYRYHYDADYSRWDST 1438

Query: 4321 QQRAVLAAALEIMVKFSSEPHLAQVVAEDLLSPSVVDVGDFTISINEGLPSGVPCTSQWN 4500
            QQRA+LAAALEIMVKFS EPHLAQ+VAEDLLSPSV+DVGDF ISINEGLPSGVPCTSQWN
Sbjct: 1439 QQRAILAAALEIMVKFSPEPHLAQIVAEDLLSPSVMDVGDFKISINEGLPSGVPCTSQWN 1498

Query: 4501 SIAHWLLTLCALSEVTNLSPDIIQANSLFSFYGDDEIVSTDIKLDPEKLTAKLKEYGLKP 4680
            SIAHWLLTLCALSEVT+LSPDI+QANSLFSFYGDDEIVSTDIKLDPEKLTAKLKEYGLKP
Sbjct: 1499 SIAHWLLTLCALSEVTDLSPDIVQANSLFSFYGDDEIVSTDIKLDPEKLTAKLKEYGLKP 1558

Query: 4681 TRPDKTEGPLVISEDLDGLTFLRRTVTRDPAGWFGKLEQSSILRQMYWTRGPNHEDPSES 4860
            TRPDKTEGPL+ISEDL+GLTFLRRTVTRDPAGWFGKLEQSSILRQMYWTRGPNHEDPSE+
Sbjct: 1559 TRPDKTEGPLIISEDLNGLTFLRRTVTRDPAGWFGKLEQSSILRQMYWTRGPNHEDPSET 1618

Query: 4861 MIPHSQRPIQLMSLLGEAALHGPTFYSKISKLVIAELKEGGMDFYVPRQEPMFRWMRFSD 5040
            MIPHSQRP QLMSLLGEAALHGP FYSKISKLVI ELKEGGMDFYVPRQEPMFRWMRFSD
Sbjct: 1619 MIPHSQRPTQLMSLLGEAALHGPAFYSKISKLVITELKEGGMDFYVPRQEPMFRWMRFSD 1678

Query: 5041 LSTWEGDRNLAPSFVNEDGVE 5103
            LSTWEGDRNLAPSFVNEDGVE
Sbjct: 1679 LSTWEGDRNLAPSFVNEDGVE 1699


