========================================================================================================================

gene_id            %id    %sim   %cov   %t5   %gap  %t3   start..stop      pep sz ref sz ref id            definition
gi_597503885.2     99.6   99.9   100.0  0.0   0.0   0.0   65..13219        7078   7078   AGH58716.1        Pp1ab | polyprotein 1ab
                                                          13219..13485                                     
                                                          13486..19701                                     
                                                          19700..21298                                     
                    frameshifts in genome at or near positions 13219..13219 (+2=>+1), 13485..13486 (+1=>+3) and 19701..19700 (+3=>+2)
gi_597503885.2.1   100.0  100.0  100.0  0.0   0.0   0.0   65..643          193    193    gi_511262662_nsp1 nsp1
gi_597503885.2.2   99.8   99.8   100.0  0.0   0.0   0.0   644..2623        660    660    gi_511261290_nsp2 nsp2
gi_597503885.2.3   99.6   99.9   100.0  0.0   0.0   0.0   2624..8281       1886   1886   gi_511261314_nsp3 nsp3
gi_597503885.2.4   99.6   99.9   100.0  0.0   0.0   0.0   8282..9805       508    508    gi_511261278_nsp4 nsp4
gi_597503885.2.5   100.0  100.0  100.0  0.0   0.0   0.0   9806..10723      306    306    gi_511262662_nsp5 nsp5
gi_597503885.2.6   100.0  100.0  100.0  0.0   0.0   0.0   10724..11599     292    292    gi_511261314_nsp6 nsp6
gi_597503885.2.7   100.0  100.0  100.0  0.0   0.0   0.0   11600..11848     83     83     gi_496838675_nsp7 nsp7
gi_597503885.2.8   100.0  100.0  100.0  0.0   0.0   0.0   11849..12445     199    199    gi_511261314_NSP8 nsp8
gi_597503885.2.9   100.0  100.0  100.0  0.0   0.0   0.0   12446..12775     110    110    gi_511261278_NSP9 nsp9
gi_597503885.2.10  100.0  100.0  100.0  0.0   0.0   0.0   12776..13195     140    140    gi_511261302_nsp1 nsp10
gi_597503885.2.11  100.0  100.0  100.0  0.0   0.0   0.0   13196..13219     933    933    gi_511261290_nsp1 nsp12
                                                          13219..13485                                     
                                                          13486..15993                                     
gi_597503885.2.12  100.0  100.0  100.0  0.0   0.0   0.0   15994..17787     598    598    gi_511261278_nsp1 nsp13
gi_597503885.2.13  100.0  100.0  100.0  0.0   0.0   0.0   17788..19359     524    524    gi_496838675_nsp1 nsp14
gi_597503885.2.14  100.0  100.0  100.0  0.0   0.0   0.0   19360..19701     343    343    gi_511261314_nsp1 nsp15
                                                          19700..20386                                     
gi_597503885.2.15  100.0  100.0  100.0  0.0   0.0   0.0   20387..21295     303    303    gi_511261278_nsp1 nsp16

CLUSTAL 2.1 multiple sequence alignment


predicted       MSFVAGVTAQGARGTYRAALNSEKHQDHVSLTVPLCGSGNLVEKLSPWFMDGENAYEVVK
reference       MSFVAGVTAQGARGTYRAALNSEKHQDHVSLTVPLCGSGNLVEKLSPWFMDGENAYEVVK
                ************************************************************

predicted       AMLLKKEPLLYVPIRLAGHTRHLPGPRVYLVERLIACENPFMVNQLAYSSSANGSLVGTT
reference       AMLLKKEPLLYVPIRLAGHTRHLPGPRVYLVERLIACENPFMVNQLAYSSSANGSLVGTT
                ************************************************************

predicted       LQGKPIGMFFPYDIELVTGKQNILLRKYGRGGYHYTPFHYERDNTSCPEWMDDFEADPKG
reference       LQGKPIGMFFPYDIELVTGKQNILLRKYGRGGYHYTPFHYERDNTSCPEWMDDFEADPKG
                ************************************************************

predicted       KYAQNLLKKLIGGDVTPVDQYMCGVDGKPISAYAFLMAKDGITKLADVEADVAARADDEG
reference       KYAQNLLKKLIGGDVTPVDQYMCGVDGKPISAYAFLMAKDGITKLADVEADVAARADDEG
                ************************************************************

predicted       FITLKNNLYRLVWHVERKDVPYPKQSIFTINSVVQKDGVENTPPHYFTLGCKILTLTPRN
reference       FITLKNNLYRLVWHVERKDVPYPKQSIFTINSVVQKDGVENTPPHYFTLGCKILTLTPRN
                ************************************************************

predicted       KWSGVSDLSLKQKLLYTFYGKESLENPTYIYHSAFIECGSCGNDSWLTGNAIQGFACGCG
reference       KWSGVSDLSLKQKLLYTFYGKESLENPTYIYHSAFIECGSCGNDSWLTGNAIQGFACGCG
                ************************************************************

predicted       ASYTANDVEVQSSGMIKPNALLCATCPFAKGDSCSSNCKHSVAQLVSYLSERCNVIADSK
reference       ASYTANDVEVQSSGMIKPNALFCATCPFAKGDSCSSNCKHSVAQLVSYLSERCNVIADSK
                *********************:**************************************

predicted       SFTLIFGGVAYAYFGCEEGTMYFVPRAKSVVSRIGDSIFTGCTGSWNKVTQIANMFLEQT
reference       SFTLIFGGVAYAYFGCEEGTMYFVPRAKSVVSRIGDSIFTGCTGSWNKVTQIANMFLEQT
                ************************************************************

predicted       QHSLNFVGEFVVNDVVLAILSGTTTNVDKIRQLLKGVTLDKLRDYLADYDVAVTAGPFMD
reference       QHSLNFVGEFVVNDVVLAILSGTTTNVDKIRQLLKGVTIDKLRDYLADYDVAVTAGPFMD
                **************************************:*********************

predicted       NAINVGGTGLQYAAITAPYVVLTGLGESFKKVATIPYKVCNSVKDTLTYYAHSVLYRVFP
reference       NAINVGGTGLQYAAITAPYVVLTGLGESFKKVATIPYKVCNSVKDTLAYYAHSVLYRVFP
                ***********************************************:************

predicted       YDMDSGVSSFSELLFDCVDLSVASTYFLVRLLQDKTGDFMSTIITSCQTAVSKLLDTCFE
reference       YDMDSGVSSFSELLFDCVDLSVASTYFLVRLLQDKTGDFMSTIITSCQTAVSKLLDTCFE
                ************************************************************

predicted       ATEATFNFLLDLAGLFRIFLRNAYVYTSQGFVVVNGKVSTLVKQVLDLLNKGMQLLHTKV
reference       ATEATFNFLLDLAGLFRIFLRNAYVYTSQGFVVVNGKVSTLVKQVLDLLNKGMQLLHTKV
                ************************************************************

predicted       SWAGFNISAVIYSGRESLIFPSGTYYCVTTKAKSVQQDLDVILPGEFSKKQLGLLQPTDN
reference       SWAGSKISAVIYSGRESLIFPSGTYYCVTTKAKSVQQDFNVILPGEFSKKQLGLLQPTDN
                **** :********************************::********************

predicted       STTVSVTVSSNMVETVVGQLEQTNMHSPDVIVGDYVIISEKLFVRSKEEDGFAFYPACTN
reference       STTVSVTVSSNMVETVVGQLEQTNMHSPDVIVGDYVIISEKLFVRSKEEDGFAFYPACTN
                ************************************************************

predicted       GHAVPTLFRLKGGAPVKKVAFGGDQVHEVAAVRSVTVEYNIHAVLDTLLASSSLRTFVVD
reference       GHAVPTLFRLKGGAPVKKVAFGGDQVHEVAAVRSVTVEYNIHAVLDTLLASSSLRTFVVD
                ************************************************************

predicted       KSLSIEEFADVVKEQVSDLLVKLLRGMPIPDFDLDDFIDAPCYCFNAEGDASWSSTMIFS
reference       KSLSIEEFADVVKEQVSDLLVKLLRGMPIPDFDLDDFIDAPCYCFNAEGDASWSSTMIFS
                ************************************************************

predicted       LHPVECDEECSEVEASDLEEGESECISETSTEQVDVSHEISDDEWAAAVDEAFPLDEAED
reference       LHPVECDEECSEVEASDLEEGESECISETSTEQVDVSHETSDDEWAAAVDEAFPLDEAED
                *************************************** ********************

predicted       VTESVQEEAQPVEVPVEDIVQVVIADTLQETPVVSDTVEVPPQVVKLPSEPQTIQPEVKE
reference       VTESVQEEAQPVEVPVEDIAQVVIADTLQETPVVPDTVEVPPQVVKLPSEPQTIQPEVKE
                *******************.**************.*************************

predicted       VAPVYEADTEQTQSVTVKPKRLRKKRNVDPLSNFEHKVITECVTIVLGDAIQVAKCYGES
reference       VAPVYEADTEQTQSVTVKPKRLRKKRNVDPLSNFEHKVITECVTIVLGDAIQVAKCYGES
                ************************************************************

predicted       VLVNAANTHLKHGGGIAGAINAASKGAVQKESDEYILAKGPLQVGDSVLLQGHSLAKNIL
reference       VLVNAANTHLKHGGGIAGAINAASKGAVQKESDEYILAKGPLQVGDSVLLQGHSLAKNIL
                ************************************************************

predicted       HVVGPDARAKQDVSLLSKCYKAMNAYPLVVTPLVSAGIFGVKPAVSFDYLIREAKTRVLV
reference       HVVGPDARAKQDVSLLSKCYKAMNAYPLVVTPLVSAGIFGVKPAVSFDYLIREAKTRVLV
                ************************************************************

predicted       VVNSQDVYKSLTIVDIPQSLTFSYDGLRGAIRKAKDYGFTVFVCTDNSANTKVLRNKGVD
reference       VVNSQDVYKSLTIVDIPQSLTFSYDGLRGAIRKAKDYGFTVFVCTDNSANTKVLRNKGVD
                ************************************************************

predicted       YTKKFLTVDGVQYYCYTSKDTLDDILQQANKSVGIISMPLGYVSHGLDLIQAGSVVRRVN
reference       YTKKFLTVDGVQYYCYTSKDTLDDILQQANKSVGIISMPLGYVSHGLDLMQAGSVVRRVN
                *************************************************:**********

predicted       VPYVCLLANKEQEAILMSEDVKLNPSEDFIKHVRTNGGYNSWHLVEGELLVQDLRLNKLL
reference       VPYVCLLANKEQEAILMSEDVKLNPSEDFIKHVRTNGGYNSWHLVEGELLVQDLRLNKLL
                ************************************************************

predicted       HWSDQTICYKDSVFYVVKNSTAFPFETLSACRAYLDSRTTQQLTIEVLVTVDGVNFRTVV
reference       HWSDQTICYKDSVFYVVKNSTAFPFETLSACRAYLDSRTTQQLTIEVLVTVDGVNFRTVV
                ************************************************************

predicted       LNNKNTYRSQLGCVFFNGADISDTIPDEKQNGHSLYLADNLTADETKALKELYGPVDPTF
reference       LNNKNTYRSQLGCVFFNGADISDTIPDEKQNGHSLYLADNLTADETKALKELYGPVDPTF
                ************************************************************

predicted       LHRFYSLKAAVHEWKMVVCDKVRSLKLSDNNCYLNAVIMTLDLLKDIKFVIPALQHAFMK
reference       LHRFYSLKAAVHGWKMVVCDKVRSLKLSDNNCYLNAVIMTLDLLKDIKFVIPALQHAFMK
                ************ ***********************************************

predicted       HKGGDSTDFIALIMAYGNCTFGAPDDASRLLHTVLAKAELCCSARMVWREWCNVCGIKDV
reference       HKGGDSTDFIALIMAYGNCTFGAPDDASRLLHTVLAKAELCCSARMVWREWCNVCGIKDV
                ************************************************************

predicted       VLQGLKACCYVGVQTVEDLRARMTYVCQCGGERHRQIVEHTTPWLLLSGTPNEKLVTTST
reference       VLQGLKACCYVGVQTVEDLRARMTYVCQCGGERHRQLVEHTTPWLLLSGTPNEKLVTTST
                ************************************:***********************

predicted       APDFVAFNVFQGIETAVGHYVHARLKGGLILKFDSGTVSKTSDWKCKVTDVLFPGQKYSS
reference       APDFVAFNVFQGIETAVGHYVHARLKGGLILKFDSGTVSKTSDWKCKVTDVLFPGQKYSS
                ************************************************************

predicted       DCNVVRYSLDGNFRTEVDPDLSAFYVKDGKYFTSEPPVTYSPATILAGSVYTNSCLVSSD
reference       DCNVVRYSLDGNFRTEVDPDLSAFYVKDGKYFTSEPPVTYSPATILAGSVYTNSCLVSSD
                ************************************************************

predicted       GQPGGDAISLSFNNLLGFDSSKPVIKKYTYSFLPKEDGDVLLAEFDTYDPIYKNGAMYKG
reference       GQPGGDAISLSFNNLLGFDSSKPVTKKYTYSFLPKEDGDVLLAEFDTYDPIYKNGAMYKG
                ************************ ***********************************

predicted       KPILWVNKASYDTNLNKFNRASLRQIFDVAPIELENKFTPLSVESTPVEPPTVDVVALQQ
reference       KPILWVNKASYDTNLNKFNRASLRQIFDVAPIELENKFTPLSVESTPVEPPTVDVVALQQ
                ************************************************************

predicted       EMTIVKCKGLNKPFVKDNVSFVADDSGTPVVEYLSKEDLHTLYVDPKYQVIVLKDNVLSF
reference       EMTIVKCMGLNKPFVKDNVSFVADDSGTPVVEYLSKEDLHTLYVDPKYQVIVLKDNVLSS
                ******* *************************************************** 

predicted       MLRLHTVESGDINVVAASGSLTRKVKLLFRASFYFKEFATRTFTATTAVGSCIKSVVRHL
reference       MLRLHTVESGDINVVAASGSLTRKVKLLFRASFYFKEFATRTFTATTAVGSCIKSVVRHL
                ************************************************************

predicted       GVTKGILTGCFSFVKMLFMLPLAYFSDSKLGTTEVKVSALKTAGVVTGNVVKQCCTAAVD
reference       GVTKGILTGCFSFAKMLFMLPLAYFSDSKLGTTEVKVSALKTAGVVTGNVVKQCCTAAVD
                *************.**********************************************

predicted       LSMDKLRRVDWKSTLRLLLMLCTTMVLLSSVYHLYVFNQVLSSDVMFEDAQGLKKFYKEV
reference       LSMDKLRRVDWKSTLRLLLMLCTTMVLLSSVYHLYVFNQVLSSDVMFEDAQGLKKFYKEV
                ************************************************************

predicted       RAYLGISSACDGLASAYRANSFDVPTFCANRSAMCNWCLISQDSITHYPALKMVQTHLSH
reference       RAYLGISSACDGLASAYRANSFDVPTFCANRSAMCNWCLISQDSITHYPALKMVQTHLSH
                ************************************************************

predicted       YVLNIDWLWFAFETGLAYMLYTSAFNWLLLAGTLHYFFAQTSIFVDWRSYNYAVSSAFWL
reference       YVLNIDWLWFAFETGLAYMLYTSAFNWLLLAGTLHYFFAQTSIFVDWRSYNYAVSSAFWL
                ************************************************************

predicted       FTHIPMAGLVRMYNLLACLWLLRKFYQHVINGCKDTACLLCYKRNRLTRVEASTVVCGGK
reference       FTHIPMAGLVRMYNLLACLWLLRKFYQHVINGCKDTACLLCYKRNRLTRVEASTVVCGGK
                ************************************************************

predicted       RTFYITANGGISFCRRHNWNCVDCDTAGVGNTFICEEVANDLTTALRRPINATDRSHYYV
reference       RTFYITANGGISFCRRHNWNCVDCDTAGVGNTFICEEVANDLTTALRRPINATDRSHYYV
                ************************************************************

predicted       DSVTVKETVVQFNYRRDGQPFYERFPLCAFTNLDKLKFKEVCKTTTGIPEYNFIIYDSSD
reference       DSVTVKETVVQFNYRRDGQPFYERFPLCAFTNLDKLKFKEVCKTTTGIPEYNFIIYDSSD
                ************************************************************

predicted       RGQESLARSACVYYSQVLCKSILLVDSSLVTSVGDSSEIATKMFDSFVNSFVSLYNVTRD
reference       RGQESLARSACVYYSQVLCKSILLVDSSLVTSVGDSSEIATKMFDSFVNSFVSLYNVTRD
                ************************************************************

predicted       KLEKLISTARDGVRRGDNFHSVLTTFIDAARGPAGVESDVETNEIVDSVQYAHKHDIQIT
reference       KLEKLISTARDGVRRGDNFHSVLTTFIDAARGPAGVESDVETNEIVDSVQYAHKHDIQIT
                ************************************************************

predicted       NESYNNYVPSYVKPDSVSTSDLGSLIDCNAASVNQIVLRNSNGACIWNAAAYMKLSDALK
reference       NESYNNYVPSYVKPDSVSTSDLGSLIDCNAASVNQIVLRNSNGACIWNAAAYMKLSDALK
                ************************************************************

predicted       RQIRIACRKCNLAFRLTTSKLRANDNILSVRFTANKIVGGASTWFNALRDFTLKGYVLAT
reference       RQIRIACRKCNLAFRLTTSKLRANDNILSVRFTANKIVGGAPTWFNALRDFTLKGYVLAT
                *****************************************.******************

predicted       IIVFLCAVLMYLCLPTFSMVPVEFYEDRILDFKVLDNGIIRDVNPDDKCFANKHRSFTQW
reference       IIVFLCAVLMYLCLPTFSMAPVEFYEDRILDFKVLDNGIIRDVNPDDKCFANKHRSFTQW
                *******************.****************************************

predicted       YHEHVGGVYDNSITCPLTVAVIAGVAGARIPDVPTTLAWVNNQIIFFVSRVFANTGSVCY
reference       YHEHVGGVYDNSITCPLTVAVIAGVAGARIPDVPTTLAWVNNQIIFFVSRVFANTGSVCY
                ************************************************************

predicted       TPIDEIPYKSFSDSGCILPSECTMFRDAEGRMTPYCHDPTVLPGAFAYSQMRPHVRYDLY
reference       TPIDEIPYKSFSDSGCILPSECTMFRDAEGRMTPYCHDPTVLPGAFAYSQMRPHVRYDLY
                ************************************************************

predicted       DGNMFIKFPEVVFESTLRITRTLSTQYCRFGSCEYAQEGVCITTNGSWAIFNDHHLNRPG
reference       DGNMFIKFPEVVFESTLRITRTLSTQYCRFGSCEYAQEGVCITTNGSWAIFNDHHLNRPG
                ************************************************************

predicted       VYCGSDFIDIVRRLAVSLFQPITYFQLTTSLVLGIGLCAFLTLLFYYINKVKRAFADYTQ
reference       VYCGSDFIDIVRRLAVSLFQPITYFQLTTSLVLGIGLCAFLTLLFYYINKVKRAFADYTQ
                ************************************************************

predicted       CAVIAVVAAVLNSLCICFVASIPLCIVPYTALYYYATFYFTNEPAFIMHVSWYIMFGPIV
reference       CAVIAVVAAVLNSLCICFVTSIPLCIVPYTALYYYATFYFTNEPAFIMHVSWYIMFGPIV
                *******************:****************************************

predicted       PIWMTCVYTVAMCFRHFFWVLAYFSKKHVEVFTDGKLNCSFQDAASNIFVINKDTYAALR
reference       PIWMTCVYTVAMCFRHFFWVLAYFSKKHVEVFTDGKLNCSFQDAASNIFVINKDTYAALR
                ************************************************************

predicted       NSLTNDAYSRFLGLFNKYKYFSGAMETAAYREAAACHLAKALQTYSETGSDLLYQPPNCS
reference       NSLTNDAYSRFLGLFNKYKYFSGAMETAAYREAAACHLAKALQTYSETGSDLLYQPPNCS
                ************************************************************

predicted       ITSGVLQSGLVKMSHPSGDVEACMVQVTCGSMTLNGLWLDNTVWCPRHVMCPADQLSDPN
reference       ITSGVLQSGLVKMSHPSGDVEACMVQVTCGSMTLNGLWLDNTVWCPRHVMCPADQLSDPN
                ************************************************************

predicted       YDALLISMTNHSFSVQKHIGAPANLRVVGHAMQGTLLKLTVDVANPSTPAYTFTTVKPGA
reference       YDALLISMTNHSFSVQKHIGAPANLRVVGHAMQGTLLKLTVDVANPSTPAYTFTTVKPGA
                ************************************************************

predicted       AFSVLACYNGRPTGTFTVVMRPNYTIKGSFLCGSCGSVGYTKEGSVINFCYMHQMELANG
reference       AFSVLACYNGRPTGTFTVVMRPNYTIKGSFLCGSCGSVGYTKEGSVINFCYMHQMELANG
                ************************************************************

predicted       THTGSAFDGTMYGAFMDKQVHQVQLTDKYCSVNVVAWLYAAILNGCAWFVKPNRTSVVSF
reference       THTGSAFDGTMYGAFMDKQVHQVQLTDKYCSVNVVAWLYAAILNGCAWFVKPNRTSVVSF
                ************************************************************

predicted       NEWALANQFTEFVGTQSVDMLAVKTGVAIEQLLYAIQQLYTGFQGKQILGSTMLEDEFTP
reference       NEWALANQFTEFVGTQSVDMLAVKTGVAIEQLLYAIQQLYTGFQGKQILGSTMLEDEFTP
                ************************************************************

predicted       EDVNMQIMGVVMQSGVRKVTYGTAHWLFATLVSTYVIILQATKFTLWNYLFETIPTQLFP
reference       EDVNMQIMGVVMQSGVRKVTYGTAHWLFATLVSTYVIILQATKFTLWNYLFETIPTQLFP
                ************************************************************

predicted       LLFVTMAFVMLLVKHKHTFLTLFLLPVAICLTYANIVYEPTTPISSALIAVANWLAPTNA
reference       LLFVTMAFVMLLVKHKHTFLTLFLLPVAICLTYANIVYEPTTPISSALIAVANWLAPTNA
                ************************************************************

predicted       YMRTTHTDIGVYISMSLVLVIVVKRLYNPSLSNFALALCSGVMWLYTYSIGEASSPIAYL
reference       YMRTTHTDIGVYISMSXVLVIVVKRLYNPSLSNFALALCSGVMWLYTYSIGEASSPIAYL
                **************** *******************************************

predicted       VFVTTLTSDYTITVFVTVNLAKVCTYAIFAYSPQLTLVFPEVKMILLLYTCLGFMCTCYF
reference       VFVTTLTSDYTITVFVTVNLAKVCTYAIFAYSPQLTLVFPEVKMILLLYTCLGFMCTCYF
                ************************************************************

predicted       GVFSLLNLKLRAPMGVYDFKVSTQEFRFMTANNLTAPRNSWEAMALNFKLIGIGGTPCIK
reference       GVFSLLNLKLRAPMGVYDFKVSTQEFRFMTANNLTAPRNSWEAMALNFKLIGVGGAPCIK
                ****************************************************:**:****

predicted       VAAMQSKLTDLKCTSVVLLSVLQQLHLEANSRAWAFCVKCHNDILAATDPSEAFEKFVSL
reference       VAAMQSKLTDLKCTSVVLLSVLQQLHLEANSRAWAFCVKCHNDILAATDPSEAFEKFVSL
                ************************************************************

predicted       FATLMTFSGNVDLDALASDIFDTPSVLQATLSEFSHLATFAELEAAQKAYQEAMDSGDTS
reference       FATLMTFSGNVDLDALASDIFDTPSVLQATLSEFSHLATFAELEAAQKAYQEAMDSGDTS
                ************************************************************

predicted       PQVLKALQKAVNIAKNAYEKDKAVARKLERMADQAMTSMYKQARAEDKKAKIVSAMQTML
reference       PQVLKALQKAVNIAKNAYEKDKAVARKLERMADQAMTSMYKQARAEDKKAKIVSAMQTML
                ************************************************************

predicted       FGMIKKLDNDVLNGIISNARNGCIPLSVIPLCASNKLRVVIPDFTVWNQVVTYPSLNYAG
reference       FGMIKKLDNDVLNGIISNARNGCIPLSVIPLCASNKLRVVIPDFTVWNQVVTYPSLNYAG
                ************************************************************

predicted       ALWDITVINNVDNEIVKSSDVVDSNENLTWPLVLECTRASTSAVKLQNNEIKPSGLKTMV
reference       ALWDITVINNVDNEIVKSSDVVDSNENLTWPLVLECTRASTSAVKLQNNEIKPSGLKTMV
                ************************************************************

predicted       VSAGQEQTNCNTSSLAYYEPVQGRKMLMALLSDNAYLKWARVEGKDGFVSVELQPPCKFL
reference       VSAGQEQTNCNTSSLAYYEPVQGRKMLMALLSDNAYLKWARVEGKDGFVSVELQPPCKFL
                ************************************************************

predicted       IAGPKGPEIRYLYFVKNLNNLHRGQVLGHIAATVRLQAGSNTEFASNSSVLSLVNFTVDP
reference       IAGPKGPEIRYLYFVKNLNNLHRGQVLGHIAATVRLQAGSNTEFASNSSVLSLVNFTVDP
                ************************************************************

predicted       QKAYLDFVNAGGAPLTNCVKMLTPKTGTGIAISVKPESTADQETYGGASVCLYCRAHIEH
reference       QKAYLDFVNAGGAPLTNCVKMLTPKTGTGIAISVKPESTADQETYGGASVCLYCRAHIEH
                ************************************************************

predicted       PDVSGVCKYKGKFVQIPAQCVRDPVGFCLSNTPCNVCQYWIGYGCNCDSLRQAALPQSKD
reference       PDVSGVCKYKGKFVQIPAQCVRDPVGFCLSNTPCNVCQYWIGYGCNCDSLRQAALPQSKD
                ************************************************************

predicted       SNFLNRVRGSIVNARIEPCSSGLSTDVVFRAFDICNYKAKVAGIGKYYKTNTCRFVELDD
reference       SNFLNRVRGSIVNARIEPCSSGLSTDVVFRAFDICNYKAKVAGIGKYYKTNTCRFVELDD
                ************************************************************

predicted       QGHHLDSYFVVKRHTMENYELEKHCYDLLRDCDAVAPHDFFIFDVDKVKTPHIVRQRLTE
reference       QGHHLDSYFVVKRHTMENYELEKHCYDLLRDCDAVAPHDFFIFDVDKVKTPHIVRQRLTE
                ************************************************************

predicted       YTMMDLVYALRHFDQNSEVLKAILVKYGCCDVTYFENKLWFDFVENPSVIGVYHKLGERV
reference       YTMMDLVYALRHFDQNSEVLKAILVKYGCCDVTYFENKLWFDFVENPSVIGVYHKLGERV
                ************************************************************

predicted       RQAILNTVKFCDHMVKAGLVGVLTLDNQDLNGKWYDFGDFVITQPGSGVAIVDSYYSYLM
reference       RQAILNTVKFCDHMVKAGLVGVLTLDNQDLNGKWYDFGDFVITQPGSGVAIVDSYYSYLM
                ************************************************************

predicted       PVLSMTDCLAAETHRDCDFNKPLIEWPLTEYDFTDYKVQLFEKYFKYWDQTYHANCVNCT
reference       PVLSMTDCLAAETHRDCDFNKPLIEWPLIEYDFTDYKVQLFEKYFKYWDQTYHANCVNCT
                **************************** *******************************

predicted       DDRCVLHCANFNVLFAMTMPKTCFGPIVRKIFVDGVPFVVSCGYHYKELGLVMNMDVSLH
reference       DDRCVLHCANFNVLFAMTMPKTCFGPIVRKIFVDGVPFVVSCGYHYKELGLVMNMDVSLH
                ************************************************************

predicted       RHRLSLKELMMYAADPAMHIASSNAFLDLRTSCFSVAALTTGLTFQTVRPGNFNQDFYDF
reference       RHRLSLKELMMYAADPAMHIASSNAFLDLRTSCFSVAALTTGLTFQTVRPGNFNQDFYDF
                ************************************************************

predicted       VVSKGFFKEGSSVTLKHFFFAQDGNAAITDYNYYSYNLPTMCDIKQMLFCMEVVNKYFEI
reference       VVSKGFFKEGSSVTLKHFFFAQDGNAAITDYNYYSYNLPTMCDIKQMLFCMEVVNKYFEI
                ************************************************************

predicted       YDGGCLNASEVVVNNLDKSAGHPFNKFGKARVYYESMSYQEQDELFAMTKRNVIPTMTQM
reference       YDGGCLNASEVVVNNLDKSAGHPFNKFGKARVYYESMSYQEQDELFAMTKRNVIPTMTQM
                ************************************************************

predicted       NLKYAISAKNRARTVAGVSILSTMTNRQYHQKMLKSMAATRGATCVIGTTKFYGGWDFML
reference       NLKYAISAKNRARTVAGVSILSTMTNRQYHQKMLKSMAATRGATCVIGTTKFYGGWDFML
                ************************************************************

predicted       KTLYKDVDNPHLMGWDYPKCDRAMPNMCRIFASLILARKHGTCCTTRDRFYRLANECAQV
reference       KTLYKDVDNPHLMGWDYPKCDRAMPNMCRIFASLILARKHGTCCTTRDRFYRLANECAQV
                ************************************************************

predicted       LSEYVLCGGGYYVKPGGTSSGDATTAYANSVFNILQATTANVSALMGANGNKIVDKEVKD
reference       LSEYVLCGGGYYVKPGGTSSGDATTAYANSVFNILQATTANVSALMGANGNKIVDKEVKD
                ************************************************************

predicted       MQFDLYVNVYRSTSPDPKFVDKYYAFLNKHFSMMILSDDGVVCYNSDYAAKGYIAGIQNF
reference       MQFDLYVNVYRSTSPDPKFVDKYYAFLNKHFSMMILSDDGVVCYNSDYAAKGYIAGIQNF
                ************************************************************

predicted       KETLYYQNNVFMSEAKCWVETDLKKGPHEFCSQHTLYIKDGDDGYFLPYPDPSRILSAGC
reference       KETLYYQNNVFMSEAKCWVETDLKKGPHEFCSQHTLYIKDGDDGYFLPYPDPSRILSAGC
                ************************************************************

predicted       FVDDIVKTDGTLMVERFVSLAIDAYPLTKHEDIEYQNVFWVYLQYIEKLYKDLTGHMLDS
reference       FVDDIVKTDGTLMVERFVSLAIDAYPLTKHEDIEYQNVFWVYLQYIEKLYKDLTGHMLDS
                ************************************************************

predicted       YSVMLCGDNSAKFWEEAFYRDLYSSPTTLQAVGSCVVCHSQTSLRCGTCIRRPFLCCKCC
reference       YSVMLCGDNSAKFWEEAFYRDLYSSPTTLQAVGSCVVCHSQTSLRCGTCIRRPFLCCKCC
                ************************************************************

predicted       YDHVIATPHKMVLSVSPYVCNAPGCGVSDVTKLYLGGMSYFCVDHRPVCSFPLCANGLVF
reference       YDHVIATPHKMVLSVSPYVCNAPGCGVSDVTKLYLGGMSYFCVDHRPVCSFPLCANGLVF
                ************************************************************

predicted       GLYKNMCTGSPSIVEFNRLATCDWTESGDYTLANTTTEPLKLFAAETLRATEEASKQSYA
reference       GLYKNMCTGSPSIVEFNRLATCDWTESGDYTLANTTTEPLKLFAAETLRATEEASKQSYA
                ************************************************************

predicted       IATIKEIVGERQLLLVWEAGKSKPPLNRNYVFTGYHITKNSKVQLGEYIFERIDYSDAVS
reference       IATIKEIVGERQLLLVWEAGKSKPPLNRNYVFTGYHITKNSKVQLGEYIFERIDYSDAVS
                ************************************************************

predicted       YKSSTTYKLTVGDIFVLTSHSVATLTAPTIVNQERYVKITGLYPTITVPEEFASHVANFQ
reference       YKSSTTYKLTVGDIFVLTSHSVATLTAPTIVNQERYVKITGLYPTITVPEEFASHVANFQ
                ************************************************************

predicted       KSGYSKYVTVQGPPGTGKSHFAIGLAIYYPTARVVYTACSHAAVDALCEKAFKYLNIAKC
reference       KSGYSKYVTVQGPPGTGKSHFAIGLAIYYPTARVVYTACSHAAVDALCEKAFKYLNIAKC
                ************************************************************

predicted       SRIIPAKARVECYDRFKVNETNSQYLFSTINALPETSADILVVDEVSMCTNYDLSIINAR
reference       SRIIPAKARVECYDRFKVNETNSQYLFSTINALPETSADILVVDEVSMCTNYDLSIINAR
                ************************************************************

predicted       IKAKHIVYVGDPAQLPAPRTLLTRGTLEPENFNSVTRLMCNLGPDIFLSMCYRCPKEIVS
reference       IKAKHIVYVGDPAQLPAPRTLLTRGTLEPENFNSVTRLMCNLGPDIFLSMCYRCPKEIVS
                ************************************************************

predicted       TVSALVYNNKLLAKKELSGQCFKILYKGNVTHDASSAINRPQLTFVKNFITANPAWSKAV
reference       TVSALVYNNKLLAKKELSGQCFKILYKGNVTHDASSAINRPQLTFVKNFITANPAWSKAV
                ************************************************************

predicted       FISPYNSQNAVARSMLGLTTQTVDSSQGSEYQYVIFCQTADTAHANNINRFNVAITRAQK
reference       FISPYNSQNAVARSMLGLTTQTVDSSQGSEYQYVIFCQTADTAHANNINRFNVAITRAQK
                ************************************************************

predicted       GILCVMTSQALFESLEFTELSFTNYKLQSQIVTGLFKDCSRETSGLSPAYAPTYVSVDDK
reference       GILCVMTSQALFESLEFTELSFTNYKLQSQIVTGLFKDCSRETSGLSPAYAPTYVSVDDK
                ************************************************************

predicted       YKTSDELCVNLNLPANVPYSRVISRMGFKLDATVPGYPKLFITREEAVRQVRSWIGFDVE
reference       YKTSDELCVNLNLPANVPYSRVISRMGFKLDATVPGYPKLFITREEAVRQVRSWIGFDVE
                ************************************************************

predicted       GAHASRNACGTNVPLQLGFSTGVNFVVQPVGVVDTEWGNMLTGIAARPPPGEQFKHLVPL
reference       GAHASRNACGTNVPLQLGFSTGVNFVVQPVGVVDTEWGNMLTGIAARPPPGEQFKHLVPL
                ************************************************************

predicted       MHKGAAWPIVRRRIVQMLSDTLDKLSDYCTFVCWAHGFELTSASYFCKIGKEQKCCMCNR
reference       MHKGAAWPIVRRRIVQMLSDTLDKLSDYCTFVCWAHGFELTSASYFCKIGKEQKCCMCNR
                ************************************************************

predicted       RAAAYSSPLQSYACWTHSCGYDYVYNPFFVDVQQWGYVGNLATNHDRYCSVHQGAHVASN
reference       RAAAYSSPLQSYACWTHSCGYDYVYNPFFVDVQQWGYVGNLATNHDRYCSVHQGAHVASN
                ************************************************************

predicted       DAIMTRCLAIHSCFIERVDWDIEYPYISHEKKLNSCCRIVERNVVRAALLAGSFDKVYDI
reference       DAIMTRCLAIHSCFIERVDWDIEYPYISHEKKLNSCCRIVERNVVRAALLAGSFDKVYDI
                ************************************************************

predicted       GNPKGIPIVDDPVVDWHYFDAQPLTRKVQQLFYTEDMASRFADGLCLFWNCNVPKYPNNA
reference       GNPKGIPIVDDPVVDWHYFDAQPLTRKVQQLFYTEDMASRFADGLCLFWNCNVPKYPNNA
                ************************************************************

predicted       IVCRFDTRVHSEFNLPGCDGGSLYVNKHAFHTPAYDVSAFRDLKPLPFFYYSTTPCEVHG
reference       IVCRFDTRVHSEFNLPGCDGGSLYVNKHAFHTPAYDVSAFRDLKPLPFFYYSTTPCEVHG
                ************************************************************

predicted       NGSMIEDIDYVPLKSAVCITACNLGGAVCRKHATEYREYMEAYNLVSASGFRLWCYKTFD
reference       NGSMIEDIDYVPLKSAVCITACNLGGAVCRKHATEYREYMEAYNLVSASGFRLWCYKTFD
                ************************************************************

predicted       IYNLWSTFTKVQGLENIAFNVVKQGHFIGVEGELPVAVVNDKIFTKSGVNDICMFENKTT
reference       IYNLWSTFTKVQGLENIAFNVVKQGHFIGVEGELPVAVVNDKIFTKSGVNDICMFENKTT
                ************************************************************

predicted       LPTNIAFELYAKRAVRSHPDFKLLHNLQADICYKFVLWDYERSNIYGTATIGVCKYTDID
reference       LPTNIAFELYAKRAVRSHPDFKLLHNLQADICYKFVLWDYERSNIYGTATIGVCKYTDID
                ************************************************************

predicted       VNSALNICFDIRDNGSLEKFMSTPNAIFISDRKIKKYPCMVGPDYAYFNGAIIRDSDVVK
reference       VNSALNICFDIRDNGSLEKFMSTPNAIFISDRKIKKYPCMVGPDYAYFNGAIIRDSDVVK
                ************************************************************

predicted       QPVKFYLYKKVNNEFIDPTECIYTQSRSCSDFLPLSDMEKDFLSFDSDVFIKKYGLENYA
reference       QPVKFYLYKKVNNEFIDPTECIYTQSRSCSDFLPLSDMEKDFLFFDSDVFIKKYGLENYA
                ******************************************* ****************

predicted       FEHVVYGDFSHTTLGGLHLLIGLYKKQQEGHIIMEEMLKGSSTIHNYFITETNTAAFKAV
reference       FEHVVYGDFSHTTLGGLHLLIGLYKKQQEGHIIMEEMLKGSSTIHNYFITETNTAAFKAV
                ************************************************************

predicted       CSVIDLKLDDFVMILKSQDLGVVSKVVKVPIDLTMIEFMLWCKDGQVQTFYPRLQASADW
reference       CSVIDLKLDDFVMILKSQDLGVVSKVVKVPIDLTMIEFMLWCKDGQVQTFYPRLQASADW
                ************************************************************

predicted       KPGHAMPSLFKVQNVNLERCELANYKQSIPMPRGVHMNIAKYMQLCQYLNTCTLAVPANM
reference       KPGHAMPSLFKVQNVNLERCELANYKQSIPMPRGVHMNIAKYMQLCQYLNTCTLAVPANM
                ************************************************************

predicted       RVIHFGAGSDKGIAPGTSVLRQWLPTDAIIIDNDLNEFVSDADITLFGDCVTVRVGQQVD
reference       RVIHFGAGSDKGIAPGTSVLRQWLPTDAIIIDNDLNEFVSDADITLFGDCVTVRVGQQVD
                ************************************************************

predicted       LVISDMYDPTTKNVTGSNESKALFFTYLCNLINNNLALGGSVAIKITEHSWSVELYELMG
reference       LVISDMYDPTTKNVTGSNESKALFFTYLCNLINNNLALGGSVAIKITEHSWSVELYELMG
                ************************************************************

predicted       KFAWWTVFCTNANASSSEGFLLGINYLGTIKENIDGGAMHANYIFWRNSTPMNLSTYSLF
reference       KFAWWTVFCTNANASSSEGFLLGINYLGTIKENIDGGAMHANYIFWRNSTPMNLSTYSLF
                ************************************************************

predicted       DLSKFQLKLKGTPVLQLKESQINELVISLLSQGKLLIRDNDTLSVSTDVLVNTYRKLR
reference       DLSKFQLKLKGTPVLQLKESQINELVISLLSQGKLLIRDNDTLSVSTDVLVNTYRKLR
                **********************************************************

>gi_597503885.2	65	21298
gtctcttgtacgtctcggtcacaatacacggtttcgtccggtgcgtggcaattcggggca
catcATGTCTTTCGTGGCTGGTGTGACCGCGCAAGGTGCGCGCGGTACGTATCGAGCAGC
GCTCAACTCTGAAAAACATCAAGACCATGTGTCTCTAACTGTGCCACTCTGTGGTTCAGG
AAACCTGGTTGAAAAACTTTCACCATGGTTCATGGATGGCGAAAATGCCTATGAAGTGGT
GAAGGCCATGTTACTTAAAAAGGAGCCACTTCTCTATGTGCCCATCCGGCTGGCTGGACA
CACTAGACACCTCCCAGGTCCTCGTGTATACCTGGTTGAGAGGCTCATTGCTTGTGAAAA
TCCATTCATGGTTAACCAATTGGCTTATAGCTCTAGTGCAAATGGCAGCTTGGTTGGCAC
AACTTTGCAGGGCAAGCCTATTGGTATGTTCTTCCCTTATGACATCGAACTTGTCACAGG
AAAGCAAAATATTCTCCTGCGCAAGTATGGCCGTGGTGGTTATCACTACACCCCATTCCA
CTATGAGCGAGACAACACCTCTTGCCCTGAGTGGATGGACGATTTTGAGGCGGATCCTAA
AGGCAAATATGCCCAGAATCTGCTTAAGAAGTTGATTGGCGGTGATGTCACTCCAGTTGA
CCAATACATGTGTGGCGTTGATGGAAAACCCATTAGTGCCTACGCATTTTTAATGGCCAA
GGATGGAATAACCAAACTGGCTGATGTTGAAGCGGACGTCGCAGCACGTGCTGATGACGA
AGGCTTCATCACATTAAAGAACAATCTATATAGATTGGTTTGGCATGTTGAGCGTAAAGA
CGTTCCATATCCTAAGCAATCTATTTTTACTATTAATAGTGTGGTCCAAAAGGATGGTGT
TGAAAACACTCCTCCTCACTATTTTACTCTTGGATGCAAAATTTTAACGCTCACCCCACG
CAACAAGTGGAGTGGCGTTTCTGACTTGTCCCTCAAACAAAAACTCCTTTACACCTTCTA
TGGTAAGGAGTCACTTGAGAACCCAACCTACATTTACCACTCCGCATTCATTGAGTGTGG
AAGTTGTGGTAATGATTCCTGGCTTACAGGGAATGCTATCCAAGGGTTTGCCTGTGGATG
TGGGGCATCATATACAGCTAATGATGTCGAAGTCCAATCATCTGGCATGATTAAGCCAAA
TGCTCTTCTTTGTGCTACTTGCCCCTTTGCTAAGGGTGATAGCTGTTCTTCTAATTGCAA
ACATTCAGTTGCTCAGTTGGTTAGTTACCTTTCTGAACGTTGTAATGTTATTGCTGATTC
TAAGTCCTTCACACTTATCTTTGGTGGCGTAGCTTACGCCTACTTTGGATGTGAGGAAGG
TACTATGTACTTTGTGCCTAGAGCTAAGTCTGTTGTCTCAAGGATTGGAGACTCCATCTT
TACAGGCTGTACTGGCTCTTGGAACAAGGTTACTCAAATTGCTAACATGTTCTTGGAACA
GACTCAGCATTCCCTTAACTTTGTGGGAGAGTTCGTTGTCAACGATGTTGTCCTCGCAAT
TCTCTCTGGAACCACAACTAATGTTGACAAAATACGCCAGCTTCTCAAAGGTGTCACCCT
TGACAAGTTGCGTGATTATTTAGCTGACTATGACGTAGCAGTCACTGCCGGCCCATTCAT
GGATAATGCTATTAATGTTGGTGGTACAGGATTACAGTATGCCGCCATTACTGCACCTTA
TGTAGTTCTCACTGGCTTAGGTGAGTCCTTTAAGAAAGTTGCAACCATACCGTACAAGGT
TTGCAACTCTGTTAAGGATACTCTGACTTATTATGCTCACAGCGTGTTGTACAGAGTTTT
TCCTTATGACATGGATTCTGGTGTGTCATCCTTTAGTGAACTACTTTTTGATTGCGTTGA
TCTTTCAGTAGCTTCTACCTATTTTTTAGTCCGCCTCTTGCAAGATAAGACTGGCGACTT
TATGTCTACAATTATTACTTCCTGCCAAACTGCTGTTAGTAAGCTTCTAGATACATGTTT
TGAAGCTACAGAAGCAACATTTAACTTCTTGTTAGATTTGGCAGGATTGTTCAGAATCTT
TCTTCGCAATGCCTATGTGTACACTTCACAAGGGTTTGTGGTGGTCAATGGCAAAGTTTC
TACACTTGTCAAACAAGTGTTAGACTTGCTTAATAAGGGTATGCAACTTTTGCATACAAA
GGTCTCCTGGGCTGGTTTTAATATCAGTGCTGTTATCTACAGCGGCAGGGAGTCTCTAAT
ATTCCCATCGGGAACCTATTACTGTGTCACCACTAAGGCTAAGTCCGTTCAACAAGATCT
TGACGTTATTTTGCCTGGTGAGTTTTCCAAGAAGCAGTTAGGACTGCTCCAACCTACTGA
CAATTCTACAACTGTTAGTGTTACTGTATCCAGTAACATGGTTGAAACTGTTGTGGGTCA
ACTTGAGCAAACTAATATGCATAGTCCTGATGTTATAGTAGGTGACTATGTCATTATTAG
TGAAAAATTGTTTGTGCGTAGTAAGGAAGAAGATGGATTTGCCTTCTACCCTGCTTGCAC
TAATGGTCATGCTGTACCGACTCTCTTTAGACTTAAGGGAGGTGCACCTGTAAAAAAAGT
AGCCTTTGGCGGTGATCAAGTACATGAGGTTGCTGCTGTAAGAAGTGTTACTGTCGAGTA
CAACATTCATGCTGTATTAGACACACTACTTGCTTCTTCTAGTCTTAGAACCTTTGTTGT
AGATAAGTCTTTGTCAATTGAGGAGTTTGCTGACGTAGTAAAGGAACAAGTCTCAGACTT
GCTTGTTAAATTACTGCGTGGAATGCCGATTCCAGATTTTGATTTAGACGATTTTATTGA
CGCACCATGCTATTGCTTTAACGCTGAGGGTGATGCATCTTGGTCTTCTACTATGATCTT
CTCTCTTCACCCCGTCGAGTGTGACGAGGAGTGTTCTGAAGTAGAGGCTTCAGATTTAGA
AGAAGGTGAATCAGAGTGCATTTCTGAGACTTCAACTGAACAAGTTGACGTTTCTCATGA
GATTTCTGACGACGAGTGGGCTGCTGCAGTTGATGAAGCGTTCCCCCTCGATGAAGCAGA
AGATGTTACTGAATCTGTGCAAGAAGAAGCACAACCAGTAGAAGTACCTGTTGAAGATAT
TGTGCAGGTTGTCATAGCTGACACCTTACAGGAAACTCCTGTTGTGTCTGATACTGTTGA
AGTCCCACCGCAAGTGGTGAAACTTCCGTCTGAACCTCAGACTATCCAGCCCGAGGTAAA
AGAAGTTGCACCTGTCTATGAGGCTGATACCGAACAGACACAGAGTGTTACTGTTAAACC
TAAGAGGTTACGCAAAAAGCGTAATGTTGACCCTTTGTCCAATTTTGAACATAAGGTTAT
TACAGAGTGCGTTACCATAGTTTTAGGTGACGCAATTCAAGTAGCCAAGTGCTATGGGGA
GTCTGTGTTAGTCAATGCTGCTAACACACATCTTAAGCATGGCGGTGGTATCGCTGGTGC
TATTAATGCGGCTTCAAAAGGGGCTGTCCAAAAAGAGTCAGATGAGTATATTCTGGCTAA
AGGGCCGTTACAAGTAGGAGATTCAGTTCTCTTGCAAGGCCATTCTCTAGCTAAGAATAT
CCTGCATGTCGTAGGCCCAGATGCCCGCGCTAAACAGGATGTTTCTCTCCTTAGTAAGTG
CTATAAGGCTATGAATGCATATCCTCTTGTAGTCACTCCTCTTGTTTCAGCAGGCATATT
TGGTGTAAAACCAGCTGTGTCTTTTGATTATCTTATTAGAGAGGCTAAGACTAGAGTTTT
AGTCGTCGTTAATTCCCAAGATGTCTATAAGAGTCTTACCATAGTTGACATTCCACAGAG
TTTGACTTTTTCATATGATGGGTTACGTGGCGCAATACGTAAAGCTAAAGATTATGGTTT
TACTGTTTTTGTGTGCACAGACAACTCTGCTAACACTAAAGTTCTTAGGAACAAGGGTGT
TGATTATACTAAGAAGTTTCTTACAGTTGACGGTGTGCAATATTATTGCTACACGTCTAA
GGACACTTTAGATGATATCTTACAACAGGCTAATAAGTCTGTTGGTATTATATCTATGCC
TTTGGGATATGTGTCTCATGGTTTAGACTTAATTCAAGCAGGGAGTGTCGTGCGTAGAGT
TAACGTGCCCTACGTGTGTCTCCTAGCTAATAAAGAGCAAGAAGCTATTTTGATGTCTGA
AGACGTTAAGTTAAACCCTTCAGAAGATTTTATAAAGCACGTCCGCACTAATGGTGGTTA
CAATTCTTGGCATTTAGTCGAGGGTGAACTATTGGTGCAAGACTTACGCTTAAATAAGCT
CCTGCATTGGTCTGATCAAACCATATGCTACAAGGATAGTGTGTTTTATGTTGTAAAGAA
TAGTACAGCTTTTCCATTTGAAACACTTTCAGCATGTCGTGCGTATTTGGATTCACGCAC
GACACAGCAGTTAACAATCGAAGTCTTAGTGACTGTCGATGGTGTAAATTTTAGAACAGT
CGTTCTAAATAATAAGAACACTTATAGATCACAGCTTGGATGCGTTTTCTTTAATGGTGC
TGATATTTCTGACACCATTCCTGATGAGAAACAGAATGGTCACAGTTTATATCTAGCAGA
CAATTTGACTGCTGATGAAACAAAGGCGCTTAAAGAGTTATATGGCCCCGTTGATCCTAC
TTTCTTACACAGATTCTATTCACTTAAGGCTGCAGTCCATGAGTGGAAGATGGTTGTGTG
TGATAAGGTACGTTCTCTCAAATTGAGTGATAATAATTGTTATCTTAATGCAGTTATTAT
GACACTTGATTTATTGAAGGACATTAAATTTGTTATACCTGCTCTACAGCATGCATTTAT
GAAACATAAGGGCGGTGATTCAACTGACTTCATAGCCCTCATTATGGCTTATGGCAATTG
CACATTTGGTGCTCCAGATGATGCCTCTCGGTTACTTCATACCGTGCTTGCAAAGGCTGA
GTTATGCTGTTCTGCACGCATGGTTTGGAGAGAGTGGTGCAATGTCTGTGGCATAAAAGA
TGTTGTTCTACAAGGCTTAAAAGCTTGTTGTTACGTGGGTGTGCAAACTGTTGAAGATCT
GCGTGCTCGCATGACATATGTATGCCAGTGTGGTGGTGAACGTCATCGGCAAATAGTCGA
ACACACCACCCCCTGGTTGCTGCTCTCAGGCACACCAAATGAAAAATTGGTGACAACCTC
CACGGCGCCTGATTTTGTAGCGTTTAATGTCTTTCAGGGCATTGAAACGGCTGTTGGCCA
TTATGTTCATGCTCGCCTGAAGGGTGGTCTTATTTTAAAGTTTGACTCTGGCACCGTTAG
CAAGACTTCAGACTGGAAGTGCAAGGTGACAGATGTACTTTTCCCCGGCCAAAAATACAG
TAGCGATTGTAATGTCGTACGGTATTCTTTGGACGGTAATTTCAGAACAGAGGTTGATCC
CGACCTATCTGCTTTCTATGTTAAGGATGGTAAATACTTTACAAGTGAACCACCCGTAAC
ATATTCACCAGCTACAATTTTAGCTGGTAGTGTCTACACTAATAGCTGCCTTGTATCGTC
TGATGGACAACCTGGCGGTGATGCTATTAGTTTGAGTTTTAATAACCTTTTAGGGTTTGA
TTCTAGTAAACCAGTCATTAAGAAATACACTTACTCCTTCTTGCCTAAAGAAGACGGCGA
TGTGTTGTTGGCTGAGTTTGACACTTATGACCCTATTTATAAGAATGGTGCCATGTATAA
AGGCAAACCAATTCTTTGGGTCAACAAAGCATCTTATGATACTAATCTTAATAAGTTCAA
TAGAGCTAGTTTGCGTCAAATTTTTGACGTAGCCCCCATTGAACTCGAAAATAAATTCAC
ACCTTTGAGTGTGGAGTCTACACCAGTTGAACCTCCAACTGTAGATGTGGTAGCACTTCA
ACAGGAAATGACAATTGTCAAATGTAAGGGTTTAAATAAACCTTTCGTGAAGGACAATGT
CAGTTTCGTTGCTGATGACTCAGGTACTCCCGTTGTTGAGTATCTGTCTAAAGAAGACCT
ACATACATTGTATGTAGACCCTAAGTATCAAGTCATTGTCTTAAAAGACAATGTACTTTC
TTTTATGCTTAGATTGCACACCGTTGAGTCAGGTGATATTAACGTTGTTGCAGCTTCCGG
ATCTTTGACACGTAAAGTGAAGTTACTATTTAGGGCTTCATTTTATTTCAAAGAATTTGC
TACCCGCACTTTCACTGCTACCACTGCTGTAGGTAGTTGTATAAAGAGTGTAGTGCGGCA
TCTAGGTGTTACTAAAGGCATATTGACAGGCTGTTTTAGTTTTGTCAAGATGTTATTTAT
GCTTCCACTAGCTTACTTTAGTGATTCAAAACTCGGCACCACAGAGGTTAAAGTGAGTGC
TTTGAAAACAGCTGGCGTTGTGACAGGTAATGTTGTAAAACAGTGTTGCACTGCTGCTGT
TGATTTAAGTATGGATAAGTTGCGCCGTGTGGATTGGAAATCAACCCTACGGTTGTTACT
TATGTTATGCACAACTATGGTATTGTTGTCTTCTGTGTATCACTTGTATGTCTTCAATCA
GGTCTTATCAAGTGATGTTATGTTTGAAGATGCCCAAGGTTTGAAAAAGTTCTACAAAGA
AGTTAGAGCTTACCTAGGAATCTCTTCTGCTTGTGACGGTCTTGCTTCAGCTTATAGGGC
GAATTCCTTTGATGTACCTACATTCTGCGCAAACCGTTCTGCAATGTGTAATTGGTGCTT
GATTAGCCAAGATTCCATAACTCACTACCCAGCTCTTAAGATGGTTCAAACACATCTTAG
CCACTATGTTCTTAACATAGATTGGTTGTGGTTTGCATTTGAGACTGGTTTGGCATACAT
GCTCTATACCTCGGCCTTCAACTGGTTGTTGTTGGCAGGTACATTGCATTATTTCTTTGC
ACAGACTTCCATATTTGTAGACTGGCGGTCATACAATTATGCTGTGTCTAGTGCCTTCTG
GTTATTCACCCACATTCCAATGGCGGGTTTGGTACGAATGTATAATTTGTTAGCATGCCT
TTGGCTTTTACGCAAGTTTTATCAGCATGTAATCAATGGTTGCAAAGATACGGCATGCTT
GCTCTGCTATAAGAGGAACCGACTTACTAGAGTTGAAGCTTCTACCGTTGTCTGTGGTGG
AAAACGTACGTTTTATATCACAGCAAATGGCGGTATTTCATTCTGTCGTAGGCATAATTG
GAATTGTGTGGATTGTGACACTGCAGGTGTGGGGAATACCTTCATCTGTGAAGAAGTCGC
AAATGACCTCACTACCGCCCTACGCAGGCCTATTAACGCTACGGATAGATCACATTATTA
TGTGGATTCCGTTACAGTTAAAGAGACTGTTGTTCAGTTTAATTATCGTAGAGACGGTCA
ACCATTCTACGAGCGGTTTCCCCTCTGCGCTTTTACAAATCTAGATAAGTTGAAGTTCAA
AGAGGTCTGTAAAACTACTACTGGTATACCTGAATACAACTTTATCATCTACGACTCATC
AGATCGTGGCCAGGAAAGTTTAGCTAGGTCTGCATGTGTTTATTATTCTCAAGTCTTGTG
TAAATCAATTCTTTTGGTTGACTCAAGTTTGGTTACTTCTGTTGGTGATTCTAGTGAAAT
CGCCACTAAAATGTTTGATTCCTTTGTTAATAGTTTCGTCTCGCTGTATAATGTCACACG
CGATAAGTTGGAAAAACTTATCTCTACTGCTCGTGATGGCGTAAGGCGAGGCGATAACTT
CCATAGTGTCTTAACAACATTCATTGACGCAGCACGAGGCCCCGCAGGTGTGGAGTCTGA
TGTTGAGACCAATGAAATTGTTGACTCTGTGCAGTATGCTCATAAACATGACATACAAAT
TACTAATGAGAGTTACAATAATTATGTACCCTCATATGTTAAACCTGATAGTGTGTCTAC
CAGTGATTTAGGTAGTCTCATTGATTGTAATGCGGCTTCAGTTAACCAAATTGTCTTGCG
TAATTCTAATGGTGCTTGTATTTGGAACGCTGCTGCATATATGAAACTCTCGGATGCACT
TAAACGACAGATTCGCATTGCATGCCGTAAGTGTAATTTAGCTTTCCGGTTAACCACCTC
AAAGCTACGCGCTAATGATAATATCTTATCAGTTAGATTCACTGCTAACAAAATTGTTGG
TGGTGCTTCTACATGGTTTAATGCGTTGCGTGACTTTACGTTAAAGGGTTACGTTCTTGC
TACCATTATTGTGTTTCTGTGTGCTGTACTGATGTATTTGTGTTTACCTACATTTTCTAT
GGTACCTGTTGAATTTTATGAAGACCGCATCTTGGACTTTAAAGTTCTTGATAATGGTAT
CATTAGGGATGTAAATCCTGATGATAAGTGCTTTGCTAATAAGCACCGGTCCTTCACACA
ATGGTATCATGAGCATGTTGGTGGTGTCTATGACAACTCTATCACATGCCCATTGACAGT
TGCAGTAATTGCTGGAGTTGCTGGTGCTCGCATTCCAGACGTACCTACTACATTGGCTTG
GGTGAACAATCAGATAATTTTCTTTGTTTCTCGAGTCTTTGCTAATACAGGCAGTGTTTG
CTACACTCCTATAGATGAGATACCCTATAAGAGTTTCTCTGATAGTGGTTGCATTCTTCC
ATCTGAGTGCACTATGTTTAGGGATGCAGAGGGCCGTATGACACCATACTGCCATGATCC
TACTGTTTTGCCTGGGGCTTTTGCGTACAGTCAGATGAGGCCTCATGTTCGTTACGACTT
GTATGATGGTAACATGTTTATTAAATTTCCTGAAGTAGTATTTGAAAGTACACTTAGGAT
TACTAGAACTCTGTCAACTCAGTACTGCCGGTTCGGTAGTTGTGAGTATGCACAAGAGGG
TGTTTGTATTACCACAAATGGCTCGTGGGCCATTTTTAATGACCACCATCTTAATAGACC
TGGTGTCTATTGTGGCTCTGATTTTATTGACATTGTCAGGCGGTTAGCAGTATCACTGTT
CCAGCCTATTACTTATTTCCAATTGACTACCTCATTGGTCTTGGGTATAGGTTTGTGTGC
GTTCCTGACTTTGCTCTTCTATTATATTAATAAAGTAAAACGTGCTTTTGCAGATTACAC
CCAGTGTGCTGTAATTGCTGTTGTTGCTGCTGTTCTTAATAGCTTGTGCATCTGCTTTGT
TGCCTCTATACCATTGTGTATAGTACCTTACACTGCATTGTACTATTATGCTACATTCTA
TTTTACTAATGAGCCTGCATTTATTATGCATGTTTCTTGGTACATTATGTTCGGGCCTAT
CGTTCCCATATGGATGACCTGCGTCTATACAGTTGCAATGTGCTTTAGACACTTCTTCTG
GGTTTTAGCTTATTTTAGTAAGAAACATGTAGAAGTTTTTACTGATGGTAAGCTTAATTG
TAGTTTCCAGGACGCTGCCTCTAATATCTTTGTTATTAACAAGGACACTTATGCAGCTCT
TAGAAACTCTTTAACTAATGATGCCTATTCACGATTTTTGGGGTTGTTTAACAAGTATAA
GTACTTCTCTGGTGCTATGGAAACAGCCGCTTATCGTGAAGCTGCAGCATGTCATCTTGC
TAAAGCCTTACAAACATACAGCGAGACTGGTAGTGATCTTCTTTACCAACCACCCAACTG
TAGTATAACCTCTGGCGTGTTGCAAAGCGGTTTGGTGAAAATGTCACATCCCAGTGGAGA
TGTTGAGGCTTGTATGGTTCAGGTTACCTGCGGTAGCATGACTCTTAATGGTCTTTGGCT
TGACAACACAGTCTGGTGTCCACGACACGTAATGTGCCCAGCTGACCAGTTGTCTGATCC
TAATTATGATGCCTTGTTGATTTCTATGACTAATCATAGTTTCAGTGTGCAAAAACACAT
TGGCGCTCCAGCAAACTTGCGTGTTGTTGGTCATGCCATGCAAGGCACTCTTTTGAAGTT
GACTGTCGATGTTGCTAACCCTAGCACTCCAGCCTACACTTTTACAACAGTGAAACCTGG
CGCAGCATTTAGTGTGTTAGCATGCTATAATGGTCGTCCGACTGGTACATTCACTGTTGT
AATGCGCCCTAACTACACAATTAAGGGTTCCTTTCTGTGTGGTTCTTGTGGTAGTGTTGG
TTACACCAAGGAGGGTAGTGTGATCAATTTTTGTTACATGCATCAAATGGAACTTGCTAA
TGGTACACATACCGGTTCAGCATTTGATGGTACTATGTATGGTGCCTTTATGGATAAACA
AGTGCACCAAGTTCAGTTAACAGACAAATACTGCAGTGTTAATGTAGTAGCTTGGCTTTA
CGCAGCAATACTTAATGGTTGCGCTTGGTTTGTAAAACCTAATCGCACTAGTGTTGTTTC
TTTTAATGAATGGGCTCTTGCCAACCAATTCACTGAATTTGTTGGCACTCAATCCGTTGA
CATGTTAGCTGTCAAAACAGGCGTTGCTATTGAACAGCTGCTTTATGCGATCCAACAACT
TTATACTGGGTTCCAGGGAAAGCAAATCCTTGGCAGTACCATGTTGGAAGATGAATTCAC
ACCTGAGGATGTTAATATGCAGATTATGGGTGTGGTTATGCAGAGTGGTGTGAGAAAAGT
TACATATGGTACTGCGCATTGGTTGTTCGCGACCCTTGTCTCAACCTATGTGATAATCTT
ACAAGCCACTAAATTTACTTTGTGGAACTACTTGTTTGAGACTATTCCCACACAGTTGTT
CCCACTCTTATTTGTGACTATGGCCTTCGTTATGTTGTTGGTTAAACACAAACACACCTT
TTTGACACTTTTCTTGTTGCCTGTGGCTATTTGTTTGACTTATGCAAACATAGTCTACGA
GCCCACTACTCCCATTTCGTCAGCGCTGATTGCAGTTGCAAATTGGCTTGCCCCCACTAA
TGCTTATATGCGCACTACACATACTGATATTGGTGTCTACATTAGTATGTCACTTGTATT
AGTCATTGTAGTGAAGAGATTGTACAACCCATCACTTTCTAACTTTGCGTTAGCATTGTG
CAGTGGTGTAATGTGGTTGTACACTTATAGCATTGGAGAAGCCTCAAGCCCCATTGCCTA
TCTGGTTTTTGTCACTACACTCACTAGTGATTATACGATTACAGTCTTTGTTACTGTTAA
CCTTGCAAAAGTTTGCACTTATGCCATCTTTGCTTACTCGCCACAGCTTACACTTGTGTT
TCCGGAAGTGAAGATGATACTTTTATTATACACATGTTTAGGTTTCATGTGTACTTGCTA
TTTTGGTGTCTTCTCTCTTTTGAACCTTAAGCTTAGAGCACCTATGGGTGTCTATGACTT
TAAGGTCTCAACACAAGAGTTCAGATTCATGACTGCTAACAATCTAACTGCACCTAGAAA
TTCTTGGGAGGCTATGGCTCTGAACTTTAAGTTAATAGGTATTGGCGGTACACCTTGTAT
AAAGGTTGCTGCTATGCAGTCTAAACTTACAGATCTTAAATGCACATCTGTGGTTCTCCT
CTCTGTGCTCCAACAGTTACACTTAGAGGCTAATAGTAGGGCCTGGGCTTTCTGTGTTAA
ATGCCATAATGATATATTGGCAGCAACAGACCCCAGTGAGGCTTTCGAGAAATTCGTAAG
TCTCTTTGCCACTTTAATGACTTTTTCTGGTAATGTAGATCTTGATGCGTTAGCTAGTGA
TATTTTTGACACTCCTAGCGTACTTCAAGCTACTCTTTCTGAGTTTTCACACTTAGCTAC
CTTTGCTGAGTTGGAAGCTGCGCAGAAAGCCTATCAGGAAGCTATGGACTCTGGTGACAC
CTCACCACAAGTTCTTAAGGCTTTGCAGAAGGCTGTTAATATAGCTAAAAACGCCTATGA
GAAGGATAAGGCAGTGGCCCGTAAGTTAGAACGTATGGCTGATCAGGCTATGACTTCTAT
GTATAAGCAAGCACGTGCTGAAGACAAGAAAGCAAAAATTGTCAGTGCTATGCAAACTAT
GTTGTTTGGTATGATTAAGAAGCTCGACAACGATGTTCTTAATGGTATCATTTCTAACGC
TAGGAATGGTTGTATACCTCTTAGTGTCATTCCACTGTGTGCTTCAAATAAACTTCGCGT
TGTAATTCCTGACTTCACCGTCTGGAATCAGGTAGTCACATATCCCTCGCTTAACTACGC
TGGGGCTTTGTGGGACATTACAGTTATAAACAATGTGGACAATGAAATTGTTAAGTCTTC
AGATGTTGTAGACAGCAATGAAAATTTAACATGGCCACTTGTTTTAGAATGCACTAGGGC
ATCCACTTCTGCCGTTAAGTTGCAAAATAATGAGATCAAACCTTCAGGTTTAAAAACCAT
GGTTGTGTCTGCAGGTCAAGAGCAAACTAACTGTAATACTAGTTCCTTAGCTTATTACGA
ACCTGTGCAGGGTCGTAAAATGCTGATGGCTCTTCTTTCTGATAATGCCTATCTCAAATG
GGCGCGTGTTGAAGGTAAGGACGGATTTGTTAGTGTAGAGCTACAACCTCCTTGCAAATT
CTTGATTGCGGGACCAAAAGGACCTGAAATCCGATATCTCTATTTTGTTAAAAATCTTAA
CAACCTTCATCGCGGGCAAGTGTTAGGGCACATTGCTGCGACTGTTAGATTGCAAGCTGG
TTCTAACACCGAGTTTGCCTCTAATTCTTCGGTGTTGTCACTTGTTAACTTCACCGTTGA
TCCTCAAAAAGCTTATCTCGATTTCGTCAATGCGGGAGGTGCCCCATTGACAAATTGTGT
TAAGATGCTTACTCCTAAAACTGGTACAGGTATAGCTATATCTGTTAAACCAGAGAGTAC
AGCTGATCAAGAGACTTATGGTGGAGCTTCAGTGTGTCTCTATTGCCGTGCGCATATAGA
ACATCCTGATGTCTCTGGTGTTTGTAAATATAAGGGTAAGTTTGTCCAAATCCCTGCTCA
GTGTGTCCGTGACCCTGTGGGATTTTGTTTGTCAAATACCCCCTGTAATGTCTGTCAATA
TTGGATTGGATATGGGTGCAATTGTGACTCGCTTAGGCAAGCAGCACTGCCCCAATCTAA
AGATTCCAATTTTTTAAACGAGTCCGGGGTTCTATTGTAAATGCCCGAATAGAACCCTGT
TCAAGTGGTTTGTCCACTGATGTCGTCTTTAGGGCATTTGACATCTGCAACTATAAGGCT
AAGGTTGCTGGTATTGGAAAATACTACAAGACTAATACTTGTAGGTTTGTAGAATTAGAT
GACCAAGGGCATCATTTAGACTCCTATTTTGTCGTTAAGAGGCATACTATGGAGAATTAT
GAACTAGAGAAGCACTGTTACGATTTGTTACGTGACTGTGATGCTGTAGCTCCCCATGAT
TTCTTCATCTTTGATGTAGACAAAGTTAAAACACCTCATATTGTACGTCAGCGTTTAACT
GAGTACACTATGATGGATCTTGTATATGCCCTGAGGCACTTTGATCAAAATAGCGAAGTG
CTTAAGGCTATCTTAGTGAAGTATGGTTGCTGTGATGTTACCTACTTTGAAAATAAACTC
TGGTTTGATTTTGTTGAAAATCCCAGTGTTATTGGTGTTTATCATAAACTTGGAGAACGT
GTACGCCAAGCTATCTTAAACACTGTTAAATTTTGTGACCACATGGTCAAGGCTGGTTTA
GTCGGTGTGCTCACACTAGACAACCAGGACCTTAATGGCAAGTGGTATGATTTTGGTGAC
TTCGTAATCACTCAACCTGGTTCAGGAGTAGCTATAGTTGATAGCTACTATTCTTATTTG
ATGCCTGTGCTCTCAATGACCGATTGTCTGGCCGCTGAGACACATAGGGATTGTGATTTT
AATAAACCACTCATTGAGTGGCCACTTACTGAGTATGATTTTACTGATTATAAGGTACAA
CTCTTTGAGAAGTACTTTAAATATTGGGATCAGACGTATCACGCAAATTGCGTTAATTGT
ACTGATGACCGTTGTGTGTTACATTGTGCTAATTTCAATGTATTGTTTGCTATGACCATG
CCTAAGACTTGTTTCGGACCCATAGTCCGAAAGATCTTTGTTGATGGCGTGCCATTTGTA
GTATCTTGTGGTTATCACTACAAAGAATTAGGTTTAGTCATGAATATGGATGTTAGTCTC
CATAGACATAGGCTCTCTCTTAAGGAGTTGATGATGTATGCCGCTGATCCAGCCATGCAC
ATTGCCTCCTCTAACGCTTTTCTTGATTTGAGGACATCATGTTTTAGTGTCGCTGCACTT
ACAACTGGTTTGACTTTTCAAACTGTGCGGCCTGGCAATTTTAACCAAGACTTCTATGAT
TTCGTGGTATCTAAAGGTTTCTTTAAGGAGGGCTCTTCAGTGACGCTCAAACATTTTTTC
TTTGCTCAAGATGGTAATGCTGCTATTACAGATTATAATTACTATTCTTATAATCTGCCT
ACTATGTGTGACATCAAACAAATGTTGTTCTGCATGGAAGTTGTAAACAAGTACTTCGAA
ATCTATGACGGTGGTTGTCTTAATGCTTCTGAAGTGGTTGTTAATAATTTAGACAAGAGT
GCTGGCCATCCTTTTAATAAGTTTGGCAAAGCTCGTGTCTATTATGAGAGCATGTCTTAC
CAGGAGCAAGATGAACTCTTTGCCATGACAAAGCGTAACGTCATTCCTACCATGACTCAA
ATGAATCTAAAATATGCTATTAGTGCTAAGAATAGAGCTCGCACTGTTGCAGGCGTGTCC
ATACTTAGCACAATGACTAATCGCCAGTACCATCAGAAAATGCTTAAGTCCATGGCTGCA
ACTCGTGGAGCGACTTGCGTCATTGGTACTACAAAGTTCTATGGTGGCTGGGATTTCATG
CTTAAAACATTGTACAAAGATGTTGATAATCCGCATCTTATGGGTTGGGATTACCCTAAG
TGTGATAGAGCTATGCCTAATATGTGTAGAATCTTCGCTTCACTCATATTAGCTCGTAAA
CATGGCACTTGTTGTACTACAAGGGACAGATTTTATCGCTTGGCAAATGAGTGTGCTCAG
GTGCTAAGCGAATATGTTCTATGTGGTGGTGGTTACTACGTCAAACCTGGAGGTACCAGT
AGCGGAGATGCCACCACTGCATATGCCAATAGTGTCTTTAACATTTTGCAGGCGACAACT
GCTAATGTCAGTGCACTTATGGGTGCTAATGGCAACAAGATTGTTGACAAAGAAGTTAAA
GACATGCAGTTTGATTTGTATGTCAATGTTTACAGGAGCACTAGCCCAGACCCCAAATTT
GTTGATAAATACTATGCTTTTCTTAATAAGCACTTTTCTATGATGATACTGTCTGATGAC
GGTGTCGTTTGCTATAATAGTGATTATGCAGCTAAGGGTTACATTGCTGGAATACAGAAT
TTTAAGGAAACGCTGTATTATCAGAACAATGTCTTTATGTCTGAAGCTAAATGCTGGGTG
GAAACCGATCTGAAGAAAGGGCCACATGAATTCTGTTCACAGCATACGCTTTATATTAAG
GATGGCGACGATGGTTACTTCCTTCCTTATCCAGACCCTTCAAGAATTTTGTCTGCCGGT
TGCTTTGTAGATGATATCGTTAAGACTGACGGTACACTCATGGTAGAGCGGTTTGTGTCT
TTGGCTATAGATGCTTACCCTCTCACAAAGCATGAAGATATAGAATACCAGAATGTATTC
TGGGTCTACTTACAGTATATAGAAAAACTGTATAAAGACCTTACAGGACACATGCTTGAC
AGTTATTCTGTCATGCTATGTGGTGATAATTCTGCTAAGTTTTGGGAAGAGGCATTCTAT
AGAGATCTCTATAGTTCGCCTACCACTTTGCAGGCTGTCGGTTCATGCGTTGTATGCCAT
TCACAGACTTCCCTACGCTGTGGGACATGCATCCGTAGACCATTTCTCTGCTGTAAATGC
TGCTATGATCATGTTATAGCAACTCCACATAAGATGGTTTTGTCTGTTTCTCCTTACGTT
TGTAATGCCCCTGGTTGTGGCGTTTCAGACGTTACTAAGCTATATTTAGGTGGTATGAGC
TACTTTTGTGTAGATCATAGACCTGTGTGTAGTTTTCCACTTTGCGCTAATGGTCTTGTA
TTCGGCTTATACAAGAATATGTGCACAGGTAGTCCTTCTATAGTTGAATTTAATAGGTTG
GCTACCTGTGACTGGACTGAAAGTGGTGATTACACCCTTGCCAATACTACAACAGAACCA
CTCAAACTTTTTGCTGCTGAGACTTTACGTGCCACTGAAGAGGCGTCTAAGCAGTCTTAT
GCTATTGCCACCATCAAAGAAATTGTTGGTGAGCGCCAACTATTACTTGTGTGGGAGGCT
GGCAAGTCCAAACCACCACTCAATCGTAATTATGTTTTTACTGGTTATCATATAACCAAA
AATAGTAAAGTGCAGCTCGGTGAGTACATCTTCGAGCGCATTGATTATAGTGATGCTGTA
TCCTACAAGTCTAGTACAACGTATAAACTGACTGTAGGTGACATCTTCGTACTTACCTCT
CACTCTGTGGCTACCTTGACGGCGCCCACAATTGTGAATCAAGAGAGGTATGTTAAAATT
ACTGGGTTGTACCCAACCATTACGGTACCTGAAGAGTTCGCAAGTCATGTTGCCAACTTC
CAAAAATCAGGTTATAGTAAATATGTCACTGTTCAGGGACCACCTGGCACTGGCAAAAGT
CATTTTGCTATAGGGTTAGCGATTTACTACCCTACAGCACGTGTTGTTTATACAGCATGT
TCACACGCAGCTGTTGATGCTTTGTGTGAAAAAGCTTTTAAATATTTGAACATTGCTAAA
TGTTCCCGTATCATTCCTGCAAAGGCACGTGTTGAGTGCTATGACAGGTTTAAAGTTAAT
GAGACAAATTCTCAATATTTGTTTAGTACTATTAATGCTCTACCAGAAACTTCTGCCGAT
ATTCTGGTGGTTGATGAGGTTAGTATGTGCACTAATTATGATCTTTCAATTATTAATGCA
CGTATTAAAGCTAAGCACATTGTCTATGTAGGAGATCCAGCACAGTTGCCAGCTCCTAGG
ACTTTGTTGACTAGAGGCACATTGGAACCAGAAAATTTCAATAGTGTCACTAGATTGATG
TGTAACTTAGGTCCTGACATATTTTTAAGTATGTGCTACAGGTGTCCTAAGGAAATAGTA
AGCACTGTGAGCGCTCTTGTCTACAATAATAAATTGTTAGCCAAGAAGGAGCTTTCAGGC
CAGTGCTTTAAAATACTCTATAAGGGCAATGTGACGCATGATGCTAGCTCTGCCATTAAT
AGACCACAACTCACATTTGTGAAGAATTTTATTACTGCCAATCCGGCATGGAGTAAGGCA
GTCTTTATTTCGCCTTATAATTCACAGAATGCTGTGGCTCGTTCAATGCTGGGTCTTACT
ACTCAGACTGTTGATTCCTCACAGGGTTCAGAATACCAGTACGTTATCTTCTGTCAAACA
GCAGATACGGCACATGCTAACAACATTAACAGATTTAATGTTGCAATCACTCGTGCCCAA
AAAGGTATTCTTTGTGTTATGACATCTCAGGCACTCTTTGAGTCCTTAGAGTTTACTGAA
TTGTCTTTTACTAATTACAAGCTCCAGTCTCAGATTGTAACTGGCCTTTTTAAAGATTGC
TCTAGAGAAACTTCTGGCCTCTCACCTGCTTATGCACCAACATACGTTAGTGTTGATGAC
AAGTATAAGACGAGTGATGAGCTTTGCGTGAATCTTAATTTACCCGCAAATGTCCCATAC
TCTCGTGTTATTTCCAGGATGGGCTTTAAACTCGATGCAACAGTTCCTGGATATCCTAAG
CTTTTCATTACTCGTGAAGAGGCTGTAAGGCAAGTTCGAAGCTGGATAGGCTTCGATGTT
GAGGGTGCTCATGCTTCCCGTAATGCATGTGGCACCAATGTGCCTCTACAATTAGGATTT
TCAACTGGTGTGAACTTTGTTGTTCAGCCAGTTGGTGTTGTAGACACTGAGTGGGGTAAC
ATGTTAACGGGCATTGCTGCCCGTCCTCCACCAGGTGAACAGTTTAAGCACCTCGTGCCT
CTTATGCATAAGGGGGCTGCGTGGCCTATTGTTAGACGACGTATAGTGCAAATGTTGTCA
GACACTTTAGACAAATTGTCTGATTACTGTACGTTTGTTTGTTGGGCTCATGGCTTTGAA
TTAACGTCTGCATCATACTTTTGCAAGATAGGTAAGGAACAGAAGTGTTGCATGTGCAAT
AGACGCGCTGCAGCGTACTCTTCACCTCTGCAATCTTATGCCTGCTGGACTCATTCCTGC
GGTTATGATTATGTCTACAACCCTTTCTTTGTCGATGTTCAACAGTGGGGTTATGTAGGC
AATCTTGCTACTAATCACGATCGTTATTGCTCTGTCCATCAAGGAGCTCATGTGGCTTCT
AATGATGCAATAATGACTCGTTGTTTAGCTATTCATTCTTGTTTTATAGAACGTGTGGAT
TGGGATATAGAGTATCCTTATATCTCACATGAAAAGAAATTGAATTCCTGTTGTAGAATC
GTTGAGCGCAACGTCGTACGTGCTGCTCTTCTTGCCGGTTCATTTGACAAAGTCTATGAT
ATTGGCAATCCTAAAGGAATTCCTATTGTTGATGACCCTGTGGTTGATTGGCATTATTTT
GATGCACAGCCCTTGACCAGAAAGGTACAACAGCTTTTCTATACAGAGGACATGGCCTCA
AGATTTGCTGATGGGCTCTGCTTATTTTGGAACTGTAATGTACCAAAATATCCTAATAAT
GCAATTGTATGCAGGTTTGACACACGTGTGCATTCTGAGTTCAATTTGCCAGGTTGTGAT
GGCGGTAGTTTGTATGTTAACAAGCACGCTTTTCATACACCAGCATATGATGTGAGTGCA
TTCCGTGATCTGAAACCTTTACCATTCTTTTATTATTCTACTACACCATGTGAAGTGCAT
GGTAATGGTAGTATGATAGAGGATATTGATTATGTACCCCTAAAATCTGCAGTCTGTATT
ACAGCTTGTAATTTAGGGGGCGCTGTTTGTAGGAAGCATGCTACAGAGTACAGAGAGTAT
ATGGAAGCATATAATCTTGTCTCTGCATCAGGTTTCCGCCTTTGGTGTTATAAGACCTTT
GATATTTATAATCTCTGGTCTACTTTTACAAAAGTTCAAGGTTTGGAAAACATTGCTTTT
AATGTTGTTAAACAAGGCCATTTTATTGGTGTTGAGGGTGAACTACCTGTAGCTGTAGTC
AATGATAAGATCTTCACCAAGAGTGGCGTTAATGACATTTGTATGTTTGAGAATAAAACC
ACTTTGCCTACTAATATAGCTTTTGAACTCTATGCTAAGCGTGCTGTACGCTCGCATCCC
GATTTCAAATTGCTACACAATTTACAAGCAGACATTTGCTACAAGTTCGTCCTTTGGGAT
TATGAACGTAGCAATATTTATGGTACTGCTACTATTGGTGTATGTAAGTACACTGATATT
GATGTTAATTCAGCTTTGAATATGTTTTGACATACGCGATAATGGTTCATTGGAGAAGTT
TATGTCTACTCCCAATGCCATCTTTATTTCTGATAGAAAAATTAAGAAATACCCTTGTAT
GGTAGGTCCTGATTATGCTTACTTCAATGGTGCTATCATCCGTGATAGTGATGTTGTTAA
ACAACCAGTGAAGTTCTACTTGTATAAGAAAGTCAATAATGAGTTTATTGATCCTACTGA
GTGTATTTACACTCAGAGTCGCTCTTGTAGTGACTTCCTACCCCTGTCTGACATGGAGAA
AGACTTTCTATCTTTTGATAGTGATGTTTTCATTAAGAAGTATGGCTTGGAAAACTATGC
TTTTGAGCACGTAGTCTATGGAGACTTCTCTCATACTACGTTAGGCGGTCTTCACTTGCT
TATTGGTTTATACAAGAAGCAACAGGAAGGTCATATTATTATGGAAGAAATGCTAAAAGG
TAGCTCAACTATTCATAACTATTTTATTACTGAGACTAACACAGCGGCTTTTAAGGCGGT
GTGTTCTGTTATAGATTTAAAGCTTGACGACTTTGTTATGATTTTAAAGAGTCAAGACCT
TGGCGTAGTATCCAAGGTTGTCAAGGTTCCTATTGACTTAACAATGATTGAGTTTATGTT
ATGGTGTAAGGATGGACAGGTTCAAACCTTCTACCCTCGACTCCAGGCTTCTGCAGATTG
GAAACCTGGTCATGCAATGCCATCCCTCTTTAAAGTTCAAAATGTAAACCTTGAACGTTG
TGAGCTTGCTAATTACAAGCAATCTATTCCTATGCCTCGCGGTGTGCACATGAACATCGC
TAAATATATGCAATTGTGCCAGTATTTAAATACTTGCACATTAGCCGTGCCTGCCAATAT
GCGTGTTATACATTTTGGCGCTGGTTCTGATAAAGGTATCGCTCCTGGTACATCAGTTTT
ACGACAGTGGCTTCCTACAGATGCCATTATTATAGATAATGATTTAAATGAGTTCGTGTC
AGATGCTGACATAACTTTATTTGGAGATTGTGTAACTGTACGTGTCGGCCAACAAGTGGA
TCTTGTTATTTCCGACATGTATGATCCTACTACTAAGAATGTAACAGGTAGTAATGAGTC
AAAGGCTTTATTCTTTACTTACCTGTGTAACCTCATTAATAATAATCTTGCTCTTGGTGG
GTCTGTTGCTATTAAAATAACAGAACACTCTTGGAGCGTTGAACTTTATGAACTTATGGG
AAAATTTGCTTGGTGGACTGTTTTCTGCACCAATGCAAATGCATCCTCATCTGAAGGATT
CCTCTTAGGTATTAATTACTTGGGTACTATTAAAGAAAATATAGATGGTGGTGCTATGCA
CGCCAACTATATATTTTGGAGAAATTCCACTCCTATGAATCTGAGTACTTACTCACTTTT
TGATTTATCCAAGTTTCAATTAAAATTAAAAGGAACACCAGTTCTTCAATTAAAGGAGAG
TCAAATTAACGAACTCGTAATATCTCTCCTGTCGCAGGGTAAGTTACTTATCCGTGACAA
TGATACACTCAGTGTTTCTACTGATGTTCTTGTTAACACCTACAGAAAGTTACGTTGAtg
tagggccagattctgttaagtctgcttgtattgaggttgatatacaacagactttctttg
ataaaacttggcctaggccaattgatgtttctaaggctgacggtattatataccctcaag
gccgtacatattctaacataactatcacttatcaaggtctttttccctatcagggagacc
atggtgatatgtatgtttactctgcaggacatgctacaggcacaactccacaaa

Length = 7078

Score =  1.047e+04 bits (22834), Expect(3) = 0.0
Identities = 4362/4385 (99%), Positives = 4367/4385 (99%)
Frame = +2

Query: 65    MSFVAGVTAQGARGTYRAALNSEKHQDHVSLTVPLCGSGNLVEKLSPWFMDGENAYEVVK 244
             MSFVAGVTAQGARGTYRAALNSEKHQDHVSLTVPLCGSGNLVEKLSPWFMDGENAYEVVK
Sbjct: 1     MSFVAGVTAQGARGTYRAALNSEKHQDHVSLTVPLCGSGNLVEKLSPWFMDGENAYEVVK 60

Query: 245   AMLLKKEPLLYVPIRLAGHTRHLPGPRVYLVERLIACENPFMVNQLAYSSSANGSLVGTT 424
             AMLLKKEPLLYVPIRLAGHTRHLPGPRVYLVERLIACENPFMVNQLAYSSSANGSLVGTT
Sbjct: 61    AMLLKKEPLLYVPIRLAGHTRHLPGPRVYLVERLIACENPFMVNQLAYSSSANGSLVGTT 120

Query: 425   LQGKPIGMFFPYDIELVTGKQNILLRKYGRGGYHYTPFHYERDNTSCPEWMDDFEADPKG 604
             LQGKPIGMFFPYDIELVTGKQNILLRKYGRGGYHYTPFHYERDNTSCPEWMDDFEADPKG
Sbjct: 121   LQGKPIGMFFPYDIELVTGKQNILLRKYGRGGYHYTPFHYERDNTSCPEWMDDFEADPKG 180

Query: 605   KYAQNLLKKLIGGDVTPVDQYMCGVDGKPISAYAFLMAKDGITKLADVEADVAARADDEG 784
             KYAQNLLKKLIGGDVTPVDQYMCGVDGKPISAYAFLMAKDGITKLADVEADVAARADDEG
Sbjct: 181   KYAQNLLKKLIGGDVTPVDQYMCGVDGKPISAYAFLMAKDGITKLADVEADVAARADDEG 240

Query: 785   FITLKNNLYRLVWHVERKDVPYPKQSIFTINSVVQKDGVENTPPHYFTLGCKILTLTPRN 964
             FITLKNNLYRLVWHVERKDVPYPKQSIFTINSVVQKDGVENTPPHYFTLGCKILTLTPRN
Sbjct: 241   FITLKNNLYRLVWHVERKDVPYPKQSIFTINSVVQKDGVENTPPHYFTLGCKILTLTPRN 300

Query: 965   KWSGVSDLSLKQKLLYTFYGKESLENPTYIYHSAFIECGSCGNDSWLTGNAIQGFACGCG 1144
             KWSGVSDLSLKQKLLYTFYGKESLENPTYIYHSAFIECGSCGNDSWLTGNAIQGFACGCG
Sbjct: 301   KWSGVSDLSLKQKLLYTFYGKESLENPTYIYHSAFIECGSCGNDSWLTGNAIQGFACGCG 360

Query: 1145  ASYTANDVEVQSSGMIKPNALLCATCPFAKGDSCSSNCKHSVAQLVSYLSERCNVIADSK 1324
             ASYTANDVEVQSSGMIKPNAL CATCPFAKGDSCSSNCKHSVAQLVSYLSERCNVIADSK
Sbjct: 361   ASYTANDVEVQSSGMIKPNALFCATCPFAKGDSCSSNCKHSVAQLVSYLSERCNVIADSK 420

Query: 1325  SFTLIFGGVAYAYFGCEEGTMYFVPRAKSVVSRIGDSIFTGCTGSWNKVTQIANMFLEQT 1504
             SFTLIFGGVAYAYFGCEEGTMYFVPRAKSVVSRIGDSIFTGCTGSWNKVTQIANMFLEQT
Sbjct: 421   SFTLIFGGVAYAYFGCEEGTMYFVPRAKSVVSRIGDSIFTGCTGSWNKVTQIANMFLEQT 480

Query: 1505  QHSLNFVGEFVVNDVVLAILSGTTTNVDKIRQLLKGVTLDKLRDYLADYDVAVTAGPFMD 1684
             QHSLNFVGEFVVNDVVLAILSGTTTNVDKIRQLLKGVT+DKLRDYLADYDVAVTAGPFMD
Sbjct: 481   QHSLNFVGEFVVNDVVLAILSGTTTNVDKIRQLLKGVTIDKLRDYLADYDVAVTAGPFMD 540

Query: 1685  NAINVGGTGLQYAAITAPYVVLTGLGESFKKVATIPYKVCNSVKDTLTYYAHSVLYRVFP 1864
             NAINVGGTGLQYAAITAPYVVLTGLGESFKKVATIPYKVCNSVKDTL YYAHSVLYRVFP
Sbjct: 541   NAINVGGTGLQYAAITAPYVVLTGLGESFKKVATIPYKVCNSVKDTLAYYAHSVLYRVFP 600

Query: 1865  YDMDSGVSSFSELLFDCVDLSVASTYFLVRLLQDKTGDFMSTIITSCQTAVSKLLDTCFE 2044
             YDMDSGVSSFSELLFDCVDLSVASTYFLVRLLQDKTGDFMSTIITSCQTAVSKLLDTCFE
Sbjct: 601   YDMDSGVSSFSELLFDCVDLSVASTYFLVRLLQDKTGDFMSTIITSCQTAVSKLLDTCFE 660

Query: 2045  ATEATFNFLLDLAGLFRIFLRNAYVYTSQGFVVVNGKVSTLVKQVLDLLNKGMQLLHTKV 2224
             ATEATFNFLLDLAGLFRIFLRNAYVYTSQGFVVVNGKVSTLVKQVLDLLNKGMQLLHTKV
Sbjct: 661   ATEATFNFLLDLAGLFRIFLRNAYVYTSQGFVVVNGKVSTLVKQVLDLLNKGMQLLHTKV 720

Query: 2225  SWAGFNISAVIYSGRESLIFPSGTYYCVTTKAKSVQQDLDVILPGEFSKKQLGLLQPTDN 2404
             SWAG  ISAVIYSGRESLIFPSGTYYCVTTKAKSVQQD +VILPGEFSKKQLGLLQPTDN
Sbjct: 721   SWAGSKISAVIYSGRESLIFPSGTYYCVTTKAKSVQQDFNVILPGEFSKKQLGLLQPTDN 780

Query: 2405  STTVSVTVSSNMVETVVGQLEQTNMHSPDVIVGDYVIISEKLFVRSKEEDGFAFYPACTN 2584
             STTVSVTVSSNMVETVVGQLEQTNMHSPDVIVGDYVIISEKLFVRSKEEDGFAFYPACTN
Sbjct: 781   STTVSVTVSSNMVETVVGQLEQTNMHSPDVIVGDYVIISEKLFVRSKEEDGFAFYPACTN 840

Query: 2585  GHAVPTLFRLKGGAPVKKVAFGGDQVHEVAAVRSVTVEYNIHAVLDTLLASSSLRTFVVD 2764
             GHAVPTLFRLKGGAPVKKVAFGGDQVHEVAAVRSVTVEYNIHAVLDTLLASSSLRTFVVD
Sbjct: 841   GHAVPTLFRLKGGAPVKKVAFGGDQVHEVAAVRSVTVEYNIHAVLDTLLASSSLRTFVVD 900

Query: 2765  KSLSIEEFADVVKEQVSDLLVKLLRGMPIPDFDLDDFIDAPCYCFNAEGDASWSSTMIFS 2944
             KSLSIEEFADVVKEQVSDLLVKLLRGMPIPDFDLDDFIDAPCYCFNAEGDASWSSTMIFS
Sbjct: 901   KSLSIEEFADVVKEQVSDLLVKLLRGMPIPDFDLDDFIDAPCYCFNAEGDASWSSTMIFS 960

Query: 2945  LHPVECDEECSEVEASDLEEGESECISETSTEQVDVSHEISDDEWAAAVDEAFPLDEAED 3124
             LHPVECDEECSEVEASDLEEGESECISETSTEQVDVSHE SDDEWAAAVDEAFPLDEAED
Sbjct: 961   LHPVECDEECSEVEASDLEEGESECISETSTEQVDVSHETSDDEWAAAVDEAFPLDEAED 1020

Query: 3125  VTESVQEEAQPVEVPVEDIVQVVIADTLQETPVVSDTVEVPPQVVKLPSEPQTIQPEVKE 3304
             VTESVQEEAQPVEVPVEDI QVVIADTLQETPVV DTVEVPPQVVKLPSEPQTIQPEVKE
Sbjct: 1021  VTESVQEEAQPVEVPVEDIAQVVIADTLQETPVVPDTVEVPPQVVKLPSEPQTIQPEVKE 1080

Query: 3305  VAPVYEADTEQTQSVTVKPKRLRKKRNVDPLSNFEHKVITECVTIVLGDAIQVAKCYGES 3484
             VAPVYEADTEQTQSVTVKPKRLRKKRNVDPLSNFEHKVITECVTIVLGDAIQVAKCYGES
Sbjct: 1081  VAPVYEADTEQTQSVTVKPKRLRKKRNVDPLSNFEHKVITECVTIVLGDAIQVAKCYGES 1140

Query: 3485  VLVNAANTHLKHGGGIAGAINAASKGAVQKESDEYILAKGPLQVGDSVLLQGHSLAKNIL 3664
             VLVNAANTHLKHGGGIAGAINAASKGAVQKESDEYILAKGPLQVGDSVLLQGHSLAKNIL
Sbjct: 1141  VLVNAANTHLKHGGGIAGAINAASKGAVQKESDEYILAKGPLQVGDSVLLQGHSLAKNIL 1200

Query: 3665  HVVGPDARAKQDVSLLSKCYKAMNAYPLVVTPLVSAGIFGVKPAVSFDYLIREAKTRVLV 3844
             HVVGPDARAKQDVSLLSKCYKAMNAYPLVVTPLVSAGIFGVKPAVSFDYLIREAKTRVLV
Sbjct: 1201  HVVGPDARAKQDVSLLSKCYKAMNAYPLVVTPLVSAGIFGVKPAVSFDYLIREAKTRVLV 1260

Query: 3845  VVNSQDVYKSLTIVDIPQSLTFSYDGLRGAIRKAKDYGFTVFVCTDNSANTKVLRNKGVD 4024
             VVNSQDVYKSLTIVDIPQSLTFSYDGLRGAIRKAKDYGFTVFVCTDNSANTKVLRNKGVD
Sbjct: 1261  VVNSQDVYKSLTIVDIPQSLTFSYDGLRGAIRKAKDYGFTVFVCTDNSANTKVLRNKGVD 1320

Query: 4025  YTKKFLTVDGVQYYCYTSKDTLDDILQQANKSVGIISMPLGYVSHGLDLIQAGSVVRRVN 4204
             YTKKFLTVDGVQYYCYTSKDTLDDILQQANKSVGIISMPLGYVSHGLDL+QAGSVVRRVN
Sbjct: 1321  YTKKFLTVDGVQYYCYTSKDTLDDILQQANKSVGIISMPLGYVSHGLDLMQAGSVVRRVN 1380

Query: 4205  VPYVCLLANKEQEAILMSEDVKLNPSEDFIKHVRTNGGYNSWHLVEGELLVQDLRLNKLL 4384
             VPYVCLLANKEQEAILMSEDVKLNPSEDFIKHVRTNGGYNSWHLVEGELLVQDLRLNKLL
Sbjct: 1381  VPYVCLLANKEQEAILMSEDVKLNPSEDFIKHVRTNGGYNSWHLVEGELLVQDLRLNKLL 1440

Query: 4385  HWSDQTICYKDSVFYVVKNSTAFPFETLSACRAYLDSRTTQQLTIEVLVTVDGVNFRTVV 4564
             HWSDQTICYKDSVFYVVKNSTAFPFETLSACRAYLDSRTTQQLTIEVLVTVDGVNFRTVV
Sbjct: 1441  HWSDQTICYKDSVFYVVKNSTAFPFETLSACRAYLDSRTTQQLTIEVLVTVDGVNFRTVV 1500

Query: 4565  LNNKNTYRSQLGCVFFNGADISDTIPDEKQNGHSLYLADNLTADETKALKELYGPVDPTF 4744
             LNNKNTYRSQLGCVFFNGADISDTIPDEKQNGHSLYLADNLTADETKALKELYGPVDPTF
Sbjct: 1501  LNNKNTYRSQLGCVFFNGADISDTIPDEKQNGHSLYLADNLTADETKALKELYGPVDPTF 1560

Query: 4745  LHRFYSLKAAVHEWKMVVCDKVRSLKLSDNNCYLNAVIMTLDLLKDIKFVIPALQHAFMK 4924
             LHRFYSLKAAVH WKMVVCDKVRSLKLSDNNCYLNAVIMTLDLLKDIKFVIPALQHAFMK
Sbjct: 1561  LHRFYSLKAAVHGWKMVVCDKVRSLKLSDNNCYLNAVIMTLDLLKDIKFVIPALQHAFMK 1620

Query: 4925  HKGGDSTDFIALIMAYGNCTFGAPDDASRLLHTVLAKAELCCSARMVWREWCNVCGIKDV 5104
             HKGGDSTDFIALIMAYGNCTFGAPDDASRLLHTVLAKAELCCSARMVWREWCNVCGIKDV
Sbjct: 1621  HKGGDSTDFIALIMAYGNCTFGAPDDASRLLHTVLAKAELCCSARMVWREWCNVCGIKDV 1680

Query: 5105  VLQGLKACCYVGVQTVEDLRARMTYVCQCGGERHRQIVEHTTPWLLLSGTPNEKLVTTST 5284
             VLQGLKACCYVGVQTVEDLRARMTYVCQCGGERHRQ+VEHTTPWLLLSGTPNEKLVTTST
Sbjct: 1681  VLQGLKACCYVGVQTVEDLRARMTYVCQCGGERHRQLVEHTTPWLLLSGTPNEKLVTTST 1740

Query: 5285  APDFVAFNVFQGIETAVGHYVHARLKGGLILKFDSGTVSKTSDWKCKVTDVLFPGQKYSS 5464
             APDFVAFNVFQGIETAVGHYVHARLKGGLILKFDSGTVSKTSDWKCKVTDVLFPGQKYSS
Sbjct: 1741  APDFVAFNVFQGIETAVGHYVHARLKGGLILKFDSGTVSKTSDWKCKVTDVLFPGQKYSS 1800

Query: 5465  DCNVVRYSLDGNFRTEVDPDLSAFYVKDGKYFTSEPPVTYSPATILAGSVYTNSCLVSSD 5644
             DCNVVRYSLDGNFRTEVDPDLSAFYVKDGKYFTSEPPVTYSPATILAGSVYTNSCLVSSD
Sbjct: 1801  DCNVVRYSLDGNFRTEVDPDLSAFYVKDGKYFTSEPPVTYSPATILAGSVYTNSCLVSSD 1860

Query: 5645  GQPGGDAISLSFNNLLGFDSSKPVIKKYTYSFLPKEDGDVLLAEFDTYDPIYKNGAMYKG 5824
             GQPGGDAISLSFNNLLGFDSSKPV KKYTYSFLPKEDGDVLLAEFDTYDPIYKNGAMYKG
Sbjct: 1861  GQPGGDAISLSFNNLLGFDSSKPVTKKYTYSFLPKEDGDVLLAEFDTYDPIYKNGAMYKG 1920

Query: 5825  KPILWVNKASYDTNLNKFNRASLRQIFDVAPIELENKFTPLSVESTPVEPPTVDVVALQQ 6004
             KPILWVNKASYDTNLNKFNRASLRQIFDVAPIELENKFTPLSVESTPVEPPTVDVVALQQ
Sbjct: 1921  KPILWVNKASYDTNLNKFNRASLRQIFDVAPIELENKFTPLSVESTPVEPPTVDVVALQQ 1980

Query: 6005  EMTIVKCKGLNKPFVKDNVSFVADDSGTPVVEYLSKEDLHTLYVDPKYQVIVLKDNVLSF 6184
             EMTIVKC GLNKPFVKDNVSFVADDSGTPVVEYLSKEDLHTLYVDPKYQVIVLKDNVLS 
Sbjct: 1981  EMTIVKCMGLNKPFVKDNVSFVADDSGTPVVEYLSKEDLHTLYVDPKYQVIVLKDNVLSS 2040

Query: 6185  MLRLHTVESGDINVVAASGSLTRKVKLLFRASFYFKEFATRTFTATTAVGSCIKSVVRHL 6364
             MLRLHTVESGDINVVAASGSLTRKVKLLFRASFYFKEFATRTFTATTAVGSCIKSVVRHL
Sbjct: 2041  MLRLHTVESGDINVVAASGSLTRKVKLLFRASFYFKEFATRTFTATTAVGSCIKSVVRHL 2100

Query: 6365  GVTKGILTGCFSFVKMLFMLPLAYFSDSKLGTTEVKVSALKTAGVVTGNVVKQCCTAAVD 6544
             GVTKGILTGCFSF KMLFMLPLAYFSDSKLGTTEVKVSALKTAGVVTGNVVKQCCTAAVD
Sbjct: 2101  GVTKGILTGCFSFAKMLFMLPLAYFSDSKLGTTEVKVSALKTAGVVTGNVVKQCCTAAVD 2160

Query: 6545  LSMDKLRRVDWKSTLRLLLMLCTTMVLLSSVYHLYVFNQVLSSDVMFEDAQGLKKFYKEV 6724
             LSMDKLRRVDWKSTLRLLLMLCTTMVLLSSVYHLYVFNQVLSSDVMFEDAQGLKKFYKEV
Sbjct: 2161  LSMDKLRRVDWKSTLRLLLMLCTTMVLLSSVYHLYVFNQVLSSDVMFEDAQGLKKFYKEV 2220

Query: 6725  RAYLGISSACDGLASAYRANSFDVPTFCANRSAMCNWCLISQDSITHYPALKMVQTHLSH 6904
             RAYLGISSACDGLASAYRANSFDVPTFCANRSAMCNWCLISQDSITHYPALKMVQTHLSH
Sbjct: 2221  RAYLGISSACDGLASAYRANSFDVPTFCANRSAMCNWCLISQDSITHYPALKMVQTHLSH 2280

Query: 6905  YVLNIDWLWFAFETGLAYMLYTSAFNWLLLAGTLHYFFAQTSIFVDWRSYNYAVSSAFWL 7084
             YVLNIDWLWFAFETGLAYMLYTSAFNWLLLAGTLHYFFAQTSIFVDWRSYNYAVSSAFWL
Sbjct: 2281  YVLNIDWLWFAFETGLAYMLYTSAFNWLLLAGTLHYFFAQTSIFVDWRSYNYAVSSAFWL 2340

Query: 7085  FTHIPMAGLVRMYNLLACLWLLRKFYQHVINGCKDTACLLCYKRNRLTRVEASTVVCGGK 7264
             FTHIPMAGLVRMYNLLACLWLLRKFYQHVINGCKDTACLLCYKRNRLTRVEASTVVCGGK
Sbjct: 2341  FTHIPMAGLVRMYNLLACLWLLRKFYQHVINGCKDTACLLCYKRNRLTRVEASTVVCGGK 2400

Query: 7265  RTFYITANGGISFCRRHNWNCVDCDTAGVGNTFICEEVANDLTTALRRPINATDRSHYYV 7444
             RTFYITANGGISFCRRHNWNCVDCDTAGVGNTFICEEVANDLTTALRRPINATDRSHYYV
Sbjct: 2401  RTFYITANGGISFCRRHNWNCVDCDTAGVGNTFICEEVANDLTTALRRPINATDRSHYYV 2460

Query: 7445  DSVTVKETVVQFNYRRDGQPFYERFPLCAFTNLDKLKFKEVCKTTTGIPEYNFIIYDSSD 7624
             DSVTVKETVVQFNYRRDGQPFYERFPLCAFTNLDKLKFKEVCKTTTGIPEYNFIIYDSSD
Sbjct: 2461  DSVTVKETVVQFNYRRDGQPFYERFPLCAFTNLDKLKFKEVCKTTTGIPEYNFIIYDSSD 2520

Query: 7625  RGQESLARSACVYYSQVLCKSILLVDSSLVTSVGDSSEIATKMFDSFVNSFVSLYNVTRD 7804
             RGQESLARSACVYYSQVLCKSILLVDSSLVTSVGDSSEIATKMFDSFVNSFVSLYNVTRD
Sbjct: 2521  RGQESLARSACVYYSQVLCKSILLVDSSLVTSVGDSSEIATKMFDSFVNSFVSLYNVTRD 2580

Query: 7805  KLEKLISTARDGVRRGDNFHSVLTTFIDAARGPAGVESDVETNEIVDSVQYAHKHDIQIT 7984
             KLEKLISTARDGVRRGDNFHSVLTTFIDAARGPAGVESDVETNEIVDSVQYAHKHDIQIT
Sbjct: 2581  KLEKLISTARDGVRRGDNFHSVLTTFIDAARGPAGVESDVETNEIVDSVQYAHKHDIQIT 2640

Query: 7985  NESYNNYVPSYVKPDSVSTSDLGSLIDCNAASVNQIVLRNSNGACIWNAAAYMKLSDALK 8164
             NESYNNYVPSYVKPDSVSTSDLGSLIDCNAASVNQIVLRNSNGACIWNAAAYMKLSDALK
Sbjct: 2641  NESYNNYVPSYVKPDSVSTSDLGSLIDCNAASVNQIVLRNSNGACIWNAAAYMKLSDALK 2700

Query: 8165  RQIRIACRKCNLAFRLTTSKLRANDNILSVRFTANKIVGGASTWFNALRDFTLKGYVLAT 8344
             RQIRIACRKCNLAFRLTTSKLRANDNILSVRFTANKIVGGA TWFNALRDFTLKGYVLAT
Sbjct: 2701  RQIRIACRKCNLAFRLTTSKLRANDNILSVRFTANKIVGGAPTWFNALRDFTLKGYVLAT 2760

Query: 8345  IIVFLCAVLMYLCLPTFSMVPVEFYEDRILDFKVLDNGIIRDVNPDDKCFANKHRSFTQW 8524
             IIVFLCAVLMYLCLPTFSM PVEFYEDRILDFKVLDNGIIRDVNPDDKCFANKHRSFTQW
Sbjct: 2761  IIVFLCAVLMYLCLPTFSMAPVEFYEDRILDFKVLDNGIIRDVNPDDKCFANKHRSFTQW 2820

Query: 8525  YHEHVGGVYDNSITCPLTVAVIAGVAGARIPDVPTTLAWVNNQIIFFVSRVFANTGSVCY 8704
             YHEHVGGVYDNSITCPLTVAVIAGVAGARIPDVPTTLAWVNNQIIFFVSRVFANTGSVCY
Sbjct: 2821  YHEHVGGVYDNSITCPLTVAVIAGVAGARIPDVPTTLAWVNNQIIFFVSRVFANTGSVCY 2880

Query: 8705  TPIDEIPYKSFSDSGCILPSECTMFRDAEGRMTPYCHDPTVLPGAFAYSQMRPHVRYDLY 8884
             TPIDEIPYKSFSDSGCILPSECTMFRDAEGRMTPYCHDPTVLPGAFAYSQMRPHVRYDLY
Sbjct: 2881  TPIDEIPYKSFSDSGCILPSECTMFRDAEGRMTPYCHDPTVLPGAFAYSQMRPHVRYDLY 2940

Query: 8885  DGNMFIKFPEVVFESTLRITRTLSTQYCRFGSCEYAQEGVCITTNGSWAIFNDHHLNRPG 9064
             DGNMFIKFPEVVFESTLRITRTLSTQYCRFGSCEYAQEGVCITTNGSWAIFNDHHLNRPG
Sbjct: 2941  DGNMFIKFPEVVFESTLRITRTLSTQYCRFGSCEYAQEGVCITTNGSWAIFNDHHLNRPG 3000

Query: 9065  VYCGSDFIDIVRRLAVSLFQPITYFQLTTSLVLGIGLCAFLTLLFYYINKVKRAFADYTQ 9244
             VYCGSDFIDIVRRLAVSLFQPITYFQLTTSLVLGIGLCAFLTLLFYYINKVKRAFADYTQ
Sbjct: 3001  VYCGSDFIDIVRRLAVSLFQPITYFQLTTSLVLGIGLCAFLTLLFYYINKVKRAFADYTQ 3060

Query: 9245  CAVIAVVAAVLNSLCICFVASIPLCIVPYTALYYYATFYFTNEPAFIMHVSWYIMFGPIV 9424
             CAVIAVVAAVLNSLCICFV SIPLCIVPYTALYYYATFYFTNEPAFIMHVSWYIMFGPIV
Sbjct: 3061  CAVIAVVAAVLNSLCICFVTSIPLCIVPYTALYYYATFYFTNEPAFIMHVSWYIMFGPIV 3120

Query: 9425  PIWMTCVYTVAMCFRHFFWVLAYFSKKHVEVFTDGKLNCSFQDAASNIFVINKDTYAALR 9604
             PIWMTCVYTVAMCFRHFFWVLAYFSKKHVEVFTDGKLNCSFQDAASNIFVINKDTYAALR
Sbjct: 3121  PIWMTCVYTVAMCFRHFFWVLAYFSKKHVEVFTDGKLNCSFQDAASNIFVINKDTYAALR 3180

Query: 9605  NSLTNDAYSRFLGLFNKYKYFSGAMETAAYREAAACHLAKALQTYSETGSDLLYQPPNCS 9784
             NSLTNDAYSRFLGLFNKYKYFSGAMETAAYREAAACHLAKALQTYSETGSDLLYQPPNCS
Sbjct: 3181  NSLTNDAYSRFLGLFNKYKYFSGAMETAAYREAAACHLAKALQTYSETGSDLLYQPPNCS 3240

Query: 9785  ITSGVLQSGLVKMSHPSGDVEACMVQVTCGSMTLNGLWLDNTVWCPRHVMCPADQLSDPN 9964
             ITSGVLQSGLVKMSHPSGDVEACMVQVTCGSMTLNGLWLDNTVWCPRHVMCPADQLSDPN
Sbjct: 3241  ITSGVLQSGLVKMSHPSGDVEACMVQVTCGSMTLNGLWLDNTVWCPRHVMCPADQLSDPN 3300

Query: 9965  YDALLISMTNHSFSVQKHIGAPANLRVVGHAMQGTLLKLTVDVANPSTPAYTFTTVKPGA 10144
             YDALLISMTNHSFSVQKHIGAPANLRVVGHAMQGTLLKLTVDVANPSTPAYTFTTVKPGA
Sbjct: 3301  YDALLISMTNHSFSVQKHIGAPANLRVVGHAMQGTLLKLTVDVANPSTPAYTFTTVKPGA 3360

Query: 10145 AFSVLACYNGRPTGTFTVVMRPNYTIKGSFLCGSCGSVGYTKEGSVINFCYMHQMELANG 10324
             AFSVLACYNGRPTGTFTVVMRPNYTIKGSFLCGSCGSVGYTKEGSVINFCYMHQMELANG
Sbjct: 3361  AFSVLACYNGRPTGTFTVVMRPNYTIKGSFLCGSCGSVGYTKEGSVINFCYMHQMELANG 3420

Query: 10325 THTGSAFDGTMYGAFMDKQVHQVQLTDKYCSVNVVAWLYAAILNGCAWFVKPNRTSVVSF 10504
             THTGSAFDGTMYGAFMDKQVHQVQLTDKYCSVNVVAWLYAAILNGCAWFVKPNRTSVVSF
Sbjct: 3421  THTGSAFDGTMYGAFMDKQVHQVQLTDKYCSVNVVAWLYAAILNGCAWFVKPNRTSVVSF 3480

Query: 10505 NEWALANQFTEFVGTQSVDMLAVKTGVAIEQLLYAIQQLYTGFQGKQILGSTMLEDEFTP 10684
             NEWALANQFTEFVGTQSVDMLAVKTGVAIEQLLYAIQQLYTGFQGKQILGSTMLEDEFTP
Sbjct: 3481  NEWALANQFTEFVGTQSVDMLAVKTGVAIEQLLYAIQQLYTGFQGKQILGSTMLEDEFTP 3540

Query: 10685 EDVNMQIMGVVMQSGVRKVTYGTAHWLFATLVSTYVIILQATKFTLWNYLFETIPTQLFP 10864
             EDVNMQIMGVVMQSGVRKVTYGTAHWLFATLVSTYVIILQATKFTLWNYLFETIPTQLFP
Sbjct: 3541  EDVNMQIMGVVMQSGVRKVTYGTAHWLFATLVSTYVIILQATKFTLWNYLFETIPTQLFP 3600

Query: 10865 LLFVTMAFVMLLVKHKHTFLTLFLLPVAICLTYANIVYEPTTPISSALIAVANWLAPTNA 11044
             LLFVTMAFVMLLVKHKHTFLTLFLLPVAICLTYANIVYEPTTPISSALIAVANWLAPTNA
Sbjct: 3601  LLFVTMAFVMLLVKHKHTFLTLFLLPVAICLTYANIVYEPTTPISSALIAVANWLAPTNA 3660

Query: 11045 YMRTTHTDIGVYISMSLVLVIVVKRLYNPSLSNFALALCSGVMWLYTYSIGEASSPIAYL 11224
             YMRTTHTDIGVYISMS VLVIVVKRLYNPSLSNFALALCSGVMWLYTYSIGEASSPIAYL
Sbjct: 3661  YMRTTHTDIGVYISMSXVLVIVVKRLYNPSLSNFALALCSGVMWLYTYSIGEASSPIAYL 3720

Query: 11225 VFVTTLTSDYTITVFVTVNLAKVCTYAIFAYSPQLTLVFPEVKMILLLYTCLGFMCTCYF 11404
             VFVTTLTSDYTITVFVTVNLAKVCTYAIFAYSPQLTLVFPEVKMILLLYTCLGFMCTCYF
Sbjct: 3721  VFVTTLTSDYTITVFVTVNLAKVCTYAIFAYSPQLTLVFPEVKMILLLYTCLGFMCTCYF 3780

Query: 11405 GVFSLLNLKLRAPMGVYDFKVSTQEFRFMTANNLTAPRNSWEAMALNFKLIGIGGTPCIK 11584
             GVFSLLNLKLRAPMGVYDFKVSTQEFRFMTANNLTAPRNSWEAMALNFKLIG+GG PCIK
Sbjct: 3781  GVFSLLNLKLRAPMGVYDFKVSTQEFRFMTANNLTAPRNSWEAMALNFKLIGVGGAPCIK 3840

Query: 11585 VAAMQSKLTDLKCTSVVLLSVLQQLHLEANSRAWAFCVKCHNDILAATDPSEAFEKFVSL 11764
             VAAMQSKLTDLKCTSVVLLSVLQQLHLEANSRAWAFCVKCHNDILAATDPSEAFEKFVSL
Sbjct: 3841  VAAMQSKLTDLKCTSVVLLSVLQQLHLEANSRAWAFCVKCHNDILAATDPSEAFEKFVSL 3900

Query: 11765 FATLMTFSGNVDLDALASDIFDTPSVLQATLSEFSHLATFAELEAAQKAYQEAMDSGDTS 11944
             FATLMTFSGNVDLDALASDIFDTPSVLQATLSEFSHLATFAELEAAQKAYQEAMDSGDTS
Sbjct: 3901  FATLMTFSGNVDLDALASDIFDTPSVLQATLSEFSHLATFAELEAAQKAYQEAMDSGDTS 3960

Query: 11945 PQVLKALQKAVNIAKNAYEKDKAVARKLERMADQAMTSMYKQARAEDKKAKIVSAMQTML 12124
             PQVLKALQKAVNIAKNAYEKDKAVARKLERMADQAMTSMYKQARAEDKKAKIVSAMQTML
Sbjct: 3961  PQVLKALQKAVNIAKNAYEKDKAVARKLERMADQAMTSMYKQARAEDKKAKIVSAMQTML 4020

Query: 12125 FGMIKKLDNDVLNGIISNARNGCIPLSVIPLCASNKLRVVIPDFTVWNQVVTYPSLNYAG 12304
             FGMIKKLDNDVLNGIISNARNGCIPLSVIPLCASNKLRVVIPDFTVWNQVVTYPSLNYAG
Sbjct: 4021  FGMIKKLDNDVLNGIISNARNGCIPLSVIPLCASNKLRVVIPDFTVWNQVVTYPSLNYAG 4080

Query: 12305 ALWDITVINNVDNEIVKSSDVVDSNENLTWPLVLECTRASTSAVKLQNNEIKPSGLKTMV 12484
             ALWDITVINNVDNEIVKSSDVVDSNENLTWPLVLECTRASTSAVKLQNNEIKPSGLKTMV
Sbjct: 4081  ALWDITVINNVDNEIVKSSDVVDSNENLTWPLVLECTRASTSAVKLQNNEIKPSGLKTMV 4140

Query: 12485 VSAGQEQTNCNTSSLAYYEPVQGRKMLMALLSDNAYLKWARVEGKDGFVSVELQPPCKFL 12664
             VSAGQEQTNCNTSSLAYYEPVQGRKMLMALLSDNAYLKWARVEGKDGFVSVELQPPCKFL
Sbjct: 4141  VSAGQEQTNCNTSSLAYYEPVQGRKMLMALLSDNAYLKWARVEGKDGFVSVELQPPCKFL 4200

Query: 12665 IAGPKGPEIRYLYFVKNLNNLHRGQVLGHIAATVRLQAGSNTEFASNSSVLSLVNFTVDP 12844
             IAGPKGPEIRYLYFVKNLNNLHRGQVLGHIAATVRLQAGSNTEFASNSSVLSLVNFTVDP
Sbjct: 4201  IAGPKGPEIRYLYFVKNLNNLHRGQVLGHIAATVRLQAGSNTEFASNSSVLSLVNFTVDP 4260

Query: 12845 QKAYLDFVNAGGAPLTNCVKMLTPKTGTGIAISVKPESTADQETYGGASVCLYCRAHIEH 13024
             QKAYLDFVNAGGAPLTNCVKMLTPKTGTGIAISVKPESTADQETYGGASVCLYCRAHIEH
Sbjct: 4261  QKAYLDFVNAGGAPLTNCVKMLTPKTGTGIAISVKPESTADQETYGGASVCLYCRAHIEH 4320

Query: 13025 PDVSGVCKYKGKFVQIPAQCVRDPVGFCLSNTPCNVCQYWIGYGCNCDSLRQAALPQSKD 13204
             PDVSGVCKYKGKFVQIPAQCVRDPVGFCLSNTPCNVCQYWIGYGCNCDSLRQAALPQSKD
Sbjct: 4321  PDVSGVCKYKGKFVQIPAQCVRDPVGFCLSNTPCNVCQYWIGYGCNCDSLRQAALPQSKD 4380

Query: 13205 SNFLN 13219
             SNFLN
Sbjct: 4381  SNFLN 4385

------------------------------------------------------------
frameshifted from +2 to +1 between 12980-13449
 12980 GGTGGAGCTTCAGTGTGTCTCTATTGCCGTGCGCATATAGAACATCCTGATGTCTCTGGT 13039 
 13040 GTTTGTAAATATAAGGGTAAGTTTGTCCAAATCCCTGCTCAGTGTGTCCGTGACCCTGTG 13099 
 13100 GGATTTTGTTTGTCAAATACCCCCTGTAATGTCTGTCAATATTGGATTGGATATGGGTGC 13159 
 13160 AATTGTGACTCGCTTAGGCAAGCAGCACTGCCCCAATCTAAAGATTCCAATTTTTTAAAC 13219 
 13220 GAGTCCGGGGTTCTATTGTAAATGCCCGAATAGAACCCTGTTCAAGTGGTTTGTCCACTG 13279 
 13280 ATGTCGTCTTTAGGGCATTTGACATCTGCAACTATAAGGCTAAGGTTGCTGGTATTGGAA 13339 
 13340 AATACTACAAGACTAATACTTGTAGGTTTGTAGAATTAGATGACCAAGGGCATCATTTAG 13399 
 13400 ACTCCTATTTTGTCGTTAAGAGGCATACTATGGAGAATTATGAACTAGAG           13449 
 frame +2
 12980  g -G--A--S--V--C--L--Y--C--R--A--H--I--E--H--P--D--V--S--G- 13039  |
 13040 -V--C--K--Y--K--G--K--F--V--Q--I--P--A--Q--C--V--R--D--P--V- 13099  |
 13100 -G--F--C--L--S--N--T--P--C--N--V--C--Q--Y--W--I--G--Y--G--C- 13159  |
 13160 -N--C--D--S--L--R--Q--A--A--L--P--Q--S--K--D--S--N--F--L--N- 13219  |
 13220  e  s  g  v  l  l  *  m  p  e  *  n -P- v  q  v  v  c  p  l  13279 
 13280  m  s  s  l  g  h  l  t  s  a  t  i  r  l  r  l  l  v  l  e  13339 
 13340  n  t  t  r  l  i  l  v  g  l  *  n  *  m  t  k -G- i  i  *  13399 
 13400  t  p  i  l  s  l  r  g  i  l  w  r  i  m  n  *              13449 
 frame +3
 12980   v  e  l  q  c  v  s -I- a  v  r  i  *  n  i  l  m  s  l  v 13039 
 13040   f  v  n  i  r  v  s  l  s  k  s  l  l  s -V- s  v  t -L- w 13099 
 13100   d  f  v -C- q  i  p  p  v  m  s  v  n  i  g  l  d  m  g  a 13159 
 13160   i  v  t  r -L- g  k  q  h  c  p -N- l  k  i  p  i  f  *  t 13219 
 13220   s  p  g  f  y  c  k  c  p  n  r  t -L- f  k  w  f -V- h  * 13279 
 13280   c  r  l  *  g  i  *  h  l  q  l  * -G- * -G- c  w -Y- w  k 13339 
 13340   i  l  q  d  *  y  l  *  v  c  r  i  r  *  p  r  a  s -F- r 13399 
 13400   l  l  f  c  r  * -E- a -Y- y  g -E- l  *  t  r             13449 
 frame +1
 12980    w  s  f  s  v  s  l  l  p  c  a  y  r  t  s  *  c  l  w   13039 
 13040 c  l  *  i  * -G- *  v  c  p  n -P- c  s  v  c  p  * -P- c - 13099 
 13100 G- i  l  f  v  k  y -P- l  *  c  l  s  i  l  d  w  i  w  v   13159 
 13160 q  l  *  l  a  *  a  s  s  t  a  p  i  *  r  f  q -F- f  k - 13219 
 13220 R--V--R--G--S--I--V--N--A--R--I--E--P--C--S--S--G--L--S--T-- 13279  |
 13280 D--V--V--F--R--A--F--D--I--C--N--Y--K--A--K--V--A--G--I--G-- 13339  |
 13340 K--Y--Y--K--T--N--T--C--R--F--V--E--L--D--D--Q--G--H--H--L-- 13399  |
 13400 D--S--Y--F--V--V--K--R--H--T--M--E--N--Y--E--L--E-           13449  |

reference sequence 4306-4462
GASVCLYCRAHIEHPDVSGVCKYKGKFVQIPAQCVRDPVGFCLSNTPCNVCQYWIGYGCN
CDSLRQAALPQSKDSNFLNRVRGSIVNARIEPCSSGLSTDVVFRAFDICNYKAKVAGIGK
YYKTNTCRFVELDDQGHHLDSYFVVKRHTMENYELEK
------------------------------------------------------------

Score =  5331 bits (11630), Expect(3) = 0.0
Identities = 2161/2165 (99%), Positives = 2162/2165 (99%)
Frame = +1

Query: 13210 FFKRVRGSIVNARIEPCSSGLSTDVVFRAFDICNYKAKVAGIGKYYKTNTCRFVELDDQG 13389
             F  RVRGSIVNARIEPCSSGLSTDVVFRAFDICNYKAKVAGIGKYYKTNTCRFVELDDQG
Sbjct: 4383  FLNRVRGSIVNARIEPCSSGLSTDVVFRAFDICNYKAKVAGIGKYYKTNTCRFVELDDQG 4442

Query: 13390 HHLDSYFVVKRHTMENYELEKHCYDLLRDCDAVAPHDFFIFDVDKVKTPHIVRQRLTEYT 13569
             HHLDSYFVVKRHTMENYELEKHCYDLLRDCDAVAPHDFFIFDVDKVKTPHIVRQRLTEYT
Sbjct: 4443  HHLDSYFVVKRHTMENYELEKHCYDLLRDCDAVAPHDFFIFDVDKVKTPHIVRQRLTEYT 4502

Query: 13570 MMDLVYALRHFDQNSEVLKAILVKYGCCDVTYFENKLWFDFVENPSVIGVYHKLGERVRQ 13749
             MMDLVYALRHFDQNSEVLKAILVKYGCCDVTYFENKLWFDFVENPSVIGVYHKLGERVRQ
Sbjct: 4503  MMDLVYALRHFDQNSEVLKAILVKYGCCDVTYFENKLWFDFVENPSVIGVYHKLGERVRQ 4562

Query: 13750 AILNTVKFCDHMVKAGLVGVLTLDNQDLNGKWYDFGDFVITQPGSGVAIVDSYYSYLMPV 13929
             AILNTVKFCDHMVKAGLVGVLTLDNQDLNGKWYDFGDFVITQPGSGVAIVDSYYSYLMPV
Sbjct: 4563  AILNTVKFCDHMVKAGLVGVLTLDNQDLNGKWYDFGDFVITQPGSGVAIVDSYYSYLMPV 4622

Query: 13930 LSMTDCLAAETHRDCDFNKPLIEWPLTEYDFTDYKVQLFEKYFKYWDQTYHANCVNCTDD 14109
             LSMTDCLAAETHRDCDFNKPLIEWPL EYDFTDYKVQLFEKYFKYWDQTYHANCVNCTDD
Sbjct: 4623  LSMTDCLAAETHRDCDFNKPLIEWPLIEYDFTDYKVQLFEKYFKYWDQTYHANCVNCTDD 4682

Query: 14110 RCVLHCANFNVLFAMTMPKTCFGPIVRKIFVDGVPFVVSCGYHYKELGLVMNMDVSLHRH 14289
             RCVLHCANFNVLFAMTMPKTCFGPIVRKIFVDGVPFVVSCGYHYKELGLVMNMDVSLHRH
Sbjct: 4683  RCVLHCANFNVLFAMTMPKTCFGPIVRKIFVDGVPFVVSCGYHYKELGLVMNMDVSLHRH 4742

Query: 14290 RLSLKELMMYAADPAMHIASSNAFLDLRTSCFSVAALTTGLTFQTVRPGNFNQDFYDFVV 14469
             RLSLKELMMYAADPAMHIASSNAFLDLRTSCFSVAALTTGLTFQTVRPGNFNQDFYDFVV
Sbjct: 4743  RLSLKELMMYAADPAMHIASSNAFLDLRTSCFSVAALTTGLTFQTVRPGNFNQDFYDFVV 4802

Query: 14470 SKGFFKEGSSVTLKHFFFAQDGNAAITDYNYYSYNLPTMCDIKQMLFCMEVVNKYFEIYD 14649
             SKGFFKEGSSVTLKHFFFAQDGNAAITDYNYYSYNLPTMCDIKQMLFCMEVVNKYFEIYD
Sbjct: 4803  SKGFFKEGSSVTLKHFFFAQDGNAAITDYNYYSYNLPTMCDIKQMLFCMEVVNKYFEIYD 4862

Query: 14650 GGCLNASEVVVNNLDKSAGHPFNKFGKARVYYESMSYQEQDELFAMTKRNVIPTMTQMNL 14829
             GGCLNASEVVVNNLDKSAGHPFNKFGKARVYYESMSYQEQDELFAMTKRNVIPTMTQMNL
Sbjct: 4863  GGCLNASEVVVNNLDKSAGHPFNKFGKARVYYESMSYQEQDELFAMTKRNVIPTMTQMNL 4922

Query: 14830 KYAISAKNRARTVAGVSILSTMTNRQYHQKMLKSMAATRGATCVIGTTKFYGGWDFMLKT 15009
             KYAISAKNRARTVAGVSILSTMTNRQYHQKMLKSMAATRGATCVIGTTKFYGGWDFMLKT
Sbjct: 4923  KYAISAKNRARTVAGVSILSTMTNRQYHQKMLKSMAATRGATCVIGTTKFYGGWDFMLKT 4982

Query: 15010 LYKDVDNPHLMGWDYPKCDRAMPNMCRIFASLILARKHGTCCTTRDRFYRLANECAQVLS 15189
             LYKDVDNPHLMGWDYPKCDRAMPNMCRIFASLILARKHGTCCTTRDRFYRLANECAQVLS
Sbjct: 4983  LYKDVDNPHLMGWDYPKCDRAMPNMCRIFASLILARKHGTCCTTRDRFYRLANECAQVLS 5042

Query: 15190 EYVLCGGGYYVKPGGTSSGDATTAYANSVFNILQATTANVSALMGANGNKIVDKEVKDMQ 15369
             EYVLCGGGYYVKPGGTSSGDATTAYANSVFNILQATTANVSALMGANGNKIVDKEVKDMQ
Sbjct: 5043  EYVLCGGGYYVKPGGTSSGDATTAYANSVFNILQATTANVSALMGANGNKIVDKEVKDMQ 5102

Query: 15370 FDLYVNVYRSTSPDPKFVDKYYAFLNKHFSMMILSDDGVVCYNSDYAAKGYIAGIQNFKE 15549
             FDLYVNVYRSTSPDPKFVDKYYAFLNKHFSMMILSDDGVVCYNSDYAAKGYIAGIQNFKE
Sbjct: 5103  FDLYVNVYRSTSPDPKFVDKYYAFLNKHFSMMILSDDGVVCYNSDYAAKGYIAGIQNFKE 5162

Query: 15550 TLYYQNNVFMSEAKCWVETDLKKGPHEFCSQHTLYIKDGDDGYFLPYPDPSRILSAGCFV 15729
             TLYYQNNVFMSEAKCWVETDLKKGPHEFCSQHTLYIKDGDDGYFLPYPDPSRILSAGCFV
Sbjct: 5163  TLYYQNNVFMSEAKCWVETDLKKGPHEFCSQHTLYIKDGDDGYFLPYPDPSRILSAGCFV 5222

Query: 15730 DDIVKTDGTLMVERFVSLAIDAYPLTKHEDIEYQNVFWVYLQYIEKLYKDLTGHMLDSYS 15909
             DDIVKTDGTLMVERFVSLAIDAYPLTKHEDIEYQNVFWVYLQYIEKLYKDLTGHMLDSYS
Sbjct: 5223  DDIVKTDGTLMVERFVSLAIDAYPLTKHEDIEYQNVFWVYLQYIEKLYKDLTGHMLDSYS 5282

Query: 15910 VMLCGDNSAKFWEEAFYRDLYSSPTTLQAVGSCVVCHSQTSLRCGTCIRRPFLCCKCCYD 16089
             VMLCGDNSAKFWEEAFYRDLYSSPTTLQAVGSCVVCHSQTSLRCGTCIRRPFLCCKCCYD
Sbjct: 5283  VMLCGDNSAKFWEEAFYRDLYSSPTTLQAVGSCVVCHSQTSLRCGTCIRRPFLCCKCCYD 5342

Query: 16090 HVIATPHKMVLSVSPYVCNAPGCGVSDVTKLYLGGMSYFCVDHRPVCSFPLCANGLVFGL 16269
             HVIATPHKMVLSVSPYVCNAPGCGVSDVTKLYLGGMSYFCVDHRPVCSFPLCANGLVFGL
Sbjct: 5343  HVIATPHKMVLSVSPYVCNAPGCGVSDVTKLYLGGMSYFCVDHRPVCSFPLCANGLVFGL 5402

Query: 16270 YKNMCTGSPSIVEFNRLATCDWTESGDYTLANTTTEPLKLFAAETLRATEEASKQSYAIA 16449
             YKNMCTGSPSIVEFNRLATCDWTESGDYTLANTTTEPLKLFAAETLRATEEASKQSYAIA
Sbjct: 5403  YKNMCTGSPSIVEFNRLATCDWTESGDYTLANTTTEPLKLFAAETLRATEEASKQSYAIA 5462

Query: 16450 TIKEIVGERQLLLVWEAGKSKPPLNRNYVFTGYHITKNSKVQLGEYIFERIDYSDAVSYK 16629
             TIKEIVGERQLLLVWEAGKSKPPLNRNYVFTGYHITKNSKVQLGEYIFERIDYSDAVSYK
Sbjct: 5463  TIKEIVGERQLLLVWEAGKSKPPLNRNYVFTGYHITKNSKVQLGEYIFERIDYSDAVSYK 5522

Query: 16630 SSTTYKLTVGDIFVLTSHSVATLTAPTIVNQERYVKITGLYPTITVPEEFASHVANFQKS 16809
             SSTTYKLTVGDIFVLTSHSVATLTAPTIVNQERYVKITGLYPTITVPEEFASHVANFQKS
Sbjct: 5523  SSTTYKLTVGDIFVLTSHSVATLTAPTIVNQERYVKITGLYPTITVPEEFASHVANFQKS 5582

Query: 16810 GYSKYVTVQGPPGTGKSHFAIGLAIYYPTARVVYTACSHAAVDALCEKAFKYLNIAKCSR 16989
             GYSKYVTVQGPPGTGKSHFAIGLAIYYPTARVVYTACSHAAVDALCEKAFKYLNIAKCSR
Sbjct: 5583  GYSKYVTVQGPPGTGKSHFAIGLAIYYPTARVVYTACSHAAVDALCEKAFKYLNIAKCSR 5642

Query: 16990 IIPAKARVECYDRFKVNETNSQYLFSTINALPETSADILVVDEVSMCTNYDLSIINARIK 17169
             IIPAKARVECYDRFKVNETNSQYLFSTINALPETSADILVVDEVSMCTNYDLSIINARIK
Sbjct: 5643  IIPAKARVECYDRFKVNETNSQYLFSTINALPETSADILVVDEVSMCTNYDLSIINARIK 5702

Query: 17170 AKHIVYVGDPAQLPAPRTLLTRGTLEPENFNSVTRLMCNLGPDIFLSMCYRCPKEIVSTV 17349
             AKHIVYVGDPAQLPAPRTLLTRGTLEPENFNSVTRLMCNLGPDIFLSMCYRCPKEIVSTV
Sbjct: 5703  AKHIVYVGDPAQLPAPRTLLTRGTLEPENFNSVTRLMCNLGPDIFLSMCYRCPKEIVSTV 5762

Query: 17350 SALVYNNKLLAKKELSGQCFKILYKGNVTHDASSAINRPQLTFVKNFITANPAWSKAVFI 17529
             SALVYNNKLLAKKELSGQCFKILYKGNVTHDASSAINRPQLTFVKNFITANPAWSKAVFI
Sbjct: 5763  SALVYNNKLLAKKELSGQCFKILYKGNVTHDASSAINRPQLTFVKNFITANPAWSKAVFI 5822

Query: 17530 SPYNSQNAVARSMLGLTTQTVDSSQGSEYQYVIFCQTADTAHANNINRFNVAITRAQKGI 17709
             SPYNSQNAVARSMLGLTTQTVDSSQGSEYQYVIFCQTADTAHANNINRFNVAITRAQKGI
Sbjct: 5823  SPYNSQNAVARSMLGLTTQTVDSSQGSEYQYVIFCQTADTAHANNINRFNVAITRAQKGI 5882

Query: 17710 LCVMTSQALFESLEFTELSFTNYKLQSQIVTGLFKDCSRETSGLSPAYAPTYVSVDDKYK 17889
             LCVMTSQALFESLEFTELSFTNYKLQSQIVTGLFKDCSRETSGLSPAYAPTYVSVDDKYK
Sbjct: 5883  LCVMTSQALFESLEFTELSFTNYKLQSQIVTGLFKDCSRETSGLSPAYAPTYVSVDDKYK 5942

Query: 17890 TSDELCVNLNLPANVPYSRVISRMGFKLDATVPGYPKLFITREEAVRQVRSWIGFDVEGA 18069
             TSDELCVNLNLPANVPYSRVISRMGFKLDATVPGYPKLFITREEAVRQVRSWIGFDVEGA
Sbjct: 5943  TSDELCVNLNLPANVPYSRVISRMGFKLDATVPGYPKLFITREEAVRQVRSWIGFDVEGA 6002

Query: 18070 HASRNACGTNVPLQLGFSTGVNFVVQPVGVVDTEWGNMLTGIAARPPPGEQFKHLVPLMH 18249
             HASRNACGTNVPLQLGFSTGVNFVVQPVGVVDTEWGNMLTGIAARPPPGEQFKHLVPLMH
Sbjct: 6003  HASRNACGTNVPLQLGFSTGVNFVVQPVGVVDTEWGNMLTGIAARPPPGEQFKHLVPLMH 6062

Query: 18250 KGAAWPIVRRRIVQMLSDTLDKLSDYCTFVCWAHGFELTSASYFCKIGKEQKCCMCNRRA 18429
             KGAAWPIVRRRIVQMLSDTLDKLSDYCTFVCWAHGFELTSASYFCKIGKEQKCCMCNRRA
Sbjct: 6063  KGAAWPIVRRRIVQMLSDTLDKLSDYCTFVCWAHGFELTSASYFCKIGKEQKCCMCNRRA 6122

Query: 18430 AAYSSPLQSYACWTHSCGYDYVYNPFFVDVQQWGYVGNLATNHDRYCSVHQGAHVASNDA 18609
             AAYSSPLQSYACWTHSCGYDYVYNPFFVDVQQWGYVGNLATNHDRYCSVHQGAHVASNDA
Sbjct: 6123  AAYSSPLQSYACWTHSCGYDYVYNPFFVDVQQWGYVGNLATNHDRYCSVHQGAHVASNDA 6182

Query: 18610 IMTRCLAIHSCFIERVDWDIEYPYISHEKKLNSCCRIVERNVVRAALLAGSFDKVYDIGN 18789
             IMTRCLAIHSCFIERVDWDIEYPYISHEKKLNSCCRIVERNVVRAALLAGSFDKVYDIGN
Sbjct: 6183  IMTRCLAIHSCFIERVDWDIEYPYISHEKKLNSCCRIVERNVVRAALLAGSFDKVYDIGN 6242

Query: 18790 PKGIPIVDDPVVDWHYFDAQPLTRKVQQLFYTEDMASRFADGLCLFWNCNVPKYPNNAIV 18969
             PKGIPIVDDPVVDWHYFDAQPLTRKVQQLFYTEDMASRFADGLCLFWNCNVPKYPNNAIV
Sbjct: 6243  PKGIPIVDDPVVDWHYFDAQPLTRKVQQLFYTEDMASRFADGLCLFWNCNVPKYPNNAIV 6302

Query: 18970 CRFDTRVHSEFNLPGCDGGSLYVNKHAFHTPAYDVSAFRDLKPLPFFYYSTTPCEVHGNG 19149
             CRFDTRVHSEFNLPGCDGGSLYVNKHAFHTPAYDVSAFRDLKPLPFFYYSTTPCEVHGNG
Sbjct: 6303  CRFDTRVHSEFNLPGCDGGSLYVNKHAFHTPAYDVSAFRDLKPLPFFYYSTTPCEVHGNG 6362

Query: 19150 SMIEDIDYVPLKSAVCITACNLGGAVCRKHATEYREYMEAYNLVSASGFRLWCYKTFDIY 19329
             SMIEDIDYVPLKSAVCITACNLGGAVCRKHATEYREYMEAYNLVSASGFRLWCYKTFDIY
Sbjct: 6363  SMIEDIDYVPLKSAVCITACNLGGAVCRKHATEYREYMEAYNLVSASGFRLWCYKTFDIY 6422

Query: 19330 NLWSTFTKVQGLENIAFNVVKQGHFIGVEGELPVAVVNDKIFTKSGVNDICMFENKTTLP 19509
             NLWSTFTKVQGLENIAFNVVKQGHFIGVEGELPVAVVNDKIFTKSGVNDICMFENKTTLP
Sbjct: 6423  NLWSTFTKVQGLENIAFNVVKQGHFIGVEGELPVAVVNDKIFTKSGVNDICMFENKTTLP 6482

Query: 19510 TNIAFELYAKRAVRSHPDFKLLHNLQADICYKFVLWDYERSNIYGTATIGVCKYTDIDVN 19689
             TNIAFELYAKRAVRSHPDFKLLHNLQADICYKFVLWDYERSNIYGTATIGVCKYTDIDVN
Sbjct: 6483  TNIAFELYAKRAVRSHPDFKLLHNLQADICYKFVLWDYERSNIYGTATIGVCKYTDIDVN 6542

Query: 19690 SALNM 19704
             SALN+
Sbjct: 6543  SALNI 6547

------------------------------------------------------------
frameshifted from +1 to +2 between 19465-19939
 19465 GGCGTTAATGACATTTGTATGTTTGAGAATAAAACCACTTTGCCTACTAATATAGCTTTT 19524 
 19525 GAACTCTATGCTAAGCGTGCTGTACGCTCGCATCCCGATTTCAAATTGCTACACAATTTA 19584 
 19585 CAAGCAGACATTTGCTACAAGTTCGTCCTTTGGGATTATGAACGTAGCAATATTTATGGT 19644 
 19645 ACTGCTACTATTGGTGTATGTAAGTACACTGATATTGATGTTAATTCAGCTTTGAATATG 19704 
 19705 TTTTGACATACGCGATAATGGTTCATTGGAGAAGTTTATGTCTACTCCCAATGCCATCTT 19764 
 19765 TATTTCTGATAGAAAAATTAAGAAATACCCTTGTATGGTAGGTCCTGATTATGCTTACTT 19824 
 19825 CAATGGTGCTATCATCCGTGATAGTGATGTTGTTAAACAACCAGTGAAGTTCTACTTGTA 19884 
 19885 TAAGAAAGTCAATAATGAGTTTATTGATCCTACTGAGTGTATTTACACTCAGAGT      19939 
 frame +1
 19465  g -V--N--D--I--C--M--F--E--N--K--T--T--L--P--T--N--I--A--F- 19524  |
 19525 -E--L--Y--A--K--R--A--V--R--S--H--P--D--F--K--L--L--H--N--L- 19584  |
 19585 -Q--A--D--I--C--Y--K--F--V--L--W--D--Y--E--R--S--N--I--Y--G- 19644  |
 19645 -T--A--T--I--G--V--C--K--Y--T--D--I--D--V--N--S--A--L--N- m  19704  |
 19705  f  *  h  t -R- *  w  f  i  g -E- v  y  v  y  s  q  c  h  l  19764 
 19765  y  f  *  *  k  n  *  e  i  p  l  y  g  r  s  *  l  c  l  l  19824 
 19825  q  w  c  y  h  p  *  *  *  c  c  *  t  t  s  e  v  l  l  v  19884 
 19885  *  e  s  q  *  *  v  y  *  s  y  *  v  y  l  h  s  e        19939 
 frame +2
 19465   a  l  m  t  f  v  c  l  r  i  k  p -L- c  l  l -I- *  l  l 19524 
 19525   n  s  m  l  s  v  l  y  a  r  i  p  i  s  n  c  y  t  i  y 19584 
 19585   k  q  t  f  a  t  s  s  s  f  g  i  m  n  v  a -I- f  m  v 19644 
 19645   l  l  l  l -V- y  v  s -T- l -I- l  m  l  i  q -L- * -I--C 19704 
 19705 --F--D--I--R--D--N--G--S--L--E--K--F--M--S--T--P--N--A--I--F 19764  |
 19765 --I--S--D--R--K--I--K--K--Y--P--C--M--V--G--P--D--Y--A--Y--F 19824  |
 19825 --N--G--A--I--I--R--D--S--D--V--V--K--Q--P--V--K--F--Y--L--Y 19884  |
 19885 --K--K--V--N--N--E--F--I--D--P--T--E--C--I--Y--T--Q--S-      19939  |
 frame +3
 19465    r  *  *  h -L- y  v  *  e  *  n  h  f  a  y  *  y  s  f   19524 
 19525 *  t  l  c  *  a  c  c  t  l  a  s  r  f  q -I- a  t  q -F-  19584 
 19585 t  s  r  h  l  l  q  v  r  p  l -G- l  * -T- *  q  y  l  w - 19644 
 19645 Y- c  y  y  w  c  m  *  v  h  *  y  *  c  *  f  s  f  e  y   19704 
 19705 v -L- t  y  a  i  m  v  h  w  r  s  l  c  l  l  p  m  p  s   19764 
 19765 l  f  l  i  e  k  l  r  n  t  l  v  w  *  v  l -I- m  l  t - 19824 
 19825 S- m -V- l  s  s  v  i  v  m  l -L- n  n  q  *  s  s  t  c - 19884 
 19885 I- r  k  s  i  m  s  l  l  i  l  l  s  v  f  t  l  r         19939 

reference sequence 6468-6626
VNDICMFENKTTLPTNIAFELYAKRAVRSHPDFKLLHNLQADICYKFVLWDYERSNIYGT
ATIGVCKYTDIDVNSALNICFDIRDNGSLEKFMSTPNAIFISDRKIKKYPCMVGPDYAYF
NGAIIRDSDVVKQPVKFYLYKKVNNEFIDPTECIYTQSR
------------------------------------------------------------

Score =  1278 bits (2784), Expect(3) = 0.0
Identities = 531/532 (99%), Positives = 531/532 (99%)
Frame = +2

Query: 19700 ICFDIRDNGSLEKFMSTPNAIFISDRKIKKYPCMVGPDYAYFNGAIIRDSDVVKQPVKFY 19879
             ICFDIRDNGSLEKFMSTPNAIFISDRKIKKYPCMVGPDYAYFNGAIIRDSDVVKQPVKFY
Sbjct: 6547  ICFDIRDNGSLEKFMSTPNAIFISDRKIKKYPCMVGPDYAYFNGAIIRDSDVVKQPVKFY 6606

Query: 19880 LYKKVNNEFIDPTECIYTQSRSCSDFLPLSDMEKDFLSFDSDVFIKKYGLENYAFEHVVY 20059
             LYKKVNNEFIDPTECIYTQSRSCSDFLPLSDMEKDFL FDSDVFIKKYGLENYAFEHVVY
Sbjct: 6607  LYKKVNNEFIDPTECIYTQSRSCSDFLPLSDMEKDFLFFDSDVFIKKYGLENYAFEHVVY 6666

Query: 20060 GDFSHTTLGGLHLLIGLYKKQQEGHIIMEEMLKGSSTIHNYFITETNTAAFKAVCSVIDL 20239
             GDFSHTTLGGLHLLIGLYKKQQEGHIIMEEMLKGSSTIHNYFITETNTAAFKAVCSVIDL
Sbjct: 6667  GDFSHTTLGGLHLLIGLYKKQQEGHIIMEEMLKGSSTIHNYFITETNTAAFKAVCSVIDL 6726

Query: 20240 KLDDFVMILKSQDLGVVSKVVKVPIDLTMIEFMLWCKDGQVQTFYPRLQASADWKPGHAM 20419
             KLDDFVMILKSQDLGVVSKVVKVPIDLTMIEFMLWCKDGQVQTFYPRLQASADWKPGHAM
Sbjct: 6727  KLDDFVMILKSQDLGVVSKVVKVPIDLTMIEFMLWCKDGQVQTFYPRLQASADWKPGHAM 6786

Query: 20420 PSLFKVQNVNLERCELANYKQSIPMPRGVHMNIAKYMQLCQYLNTCTLAVPANMRVIHFG 20599
             PSLFKVQNVNLERCELANYKQSIPMPRGVHMNIAKYMQLCQYLNTCTLAVPANMRVIHFG
Sbjct: 6787  PSLFKVQNVNLERCELANYKQSIPMPRGVHMNIAKYMQLCQYLNTCTLAVPANMRVIHFG 6846

Query: 20600 AGSDKGIAPGTSVLRQWLPTDAIIIDNDLNEFVSDADITLFGDCVTVRVGQQVDLVISDM 20779
             AGSDKGIAPGTSVLRQWLPTDAIIIDNDLNEFVSDADITLFGDCVTVRVGQQVDLVISDM
Sbjct: 6847  AGSDKGIAPGTSVLRQWLPTDAIIIDNDLNEFVSDADITLFGDCVTVRVGQQVDLVISDM 6906

Query: 20780 YDPTTKNVTGSNESKALFFTYLCNLINNNLALGGSVAIKITEHSWSVELYELMGKFAWWT 20959
             YDPTTKNVTGSNESKALFFTYLCNLINNNLALGGSVAIKITEHSWSVELYELMGKFAWWT
Sbjct: 6907  YDPTTKNVTGSNESKALFFTYLCNLINNNLALGGSVAIKITEHSWSVELYELMGKFAWWT 6966

Query: 20960 VFCTNANASSSEGFLLGINYLGTIKENIDGGAMHANYIFWRNSTPMNLSTYSLFDLSKFQ 21139
             VFCTNANASSSEGFLLGINYLGTIKENIDGGAMHANYIFWRNSTPMNLSTYSLFDLSKFQ
Sbjct: 6967  VFCTNANASSSEGFLLGINYLGTIKENIDGGAMHANYIFWRNSTPMNLSTYSLFDLSKFQ 7026

Query: 21140 LKLKGTPVLQLKESQINELVISLLSQGKLLIRDNDTLSVSTDVLVNTYRKLR 21295
             LKLKGTPVLQLKESQINELVISLLSQGKLLIRDNDTLSVSTDVLVNTYRKLR
Sbjct: 7027  LKLKGTPVLQLKESQINELVISLLSQGKLLIRDNDTLSVSTDVLVNTYRKLR 7078


