========================================================================================================================

gene_id            %id    %sim   %cov   %t5   %gap  %t3   start..stop      pep sz ref sz ref id            definition
37.17              82.8   92.4   99.0   1.0   0.0   0.0   18237..21080     947    945    ACI04185-T5       L3-2 | hexon
                    could not find valid start codon

CLUSTAL 2.1 multiple sequence alignment


predicted       ---------KMATPSMLPQWAYMHIAGQDASEYLSPGLVQFARATDTYFNLGNKFRNPTV
reference       MCLTARERAKMATPSMMPQWAYMHIAGQDASEYLSPGLVQFARATDTYFSLGNKFRNPTV
                         *******:********************************.**********

predicted       APTHDVTTDRSQRLMLRFVPVDREDNTYSYKVRYTLAVGDNRVLDMASTFFDIRGVLDRG
reference       APTHDVTTDRSQRLTLRFVPVDREDTTYSYKARFTLAVGDNRVLDMASTYFDIRGVLDRG
                ************** **********.*****.*:***************:**********

predicted       PSFKPYSGTAYNSLAPKGAPNTSQWIAEGVKNGEERVTEEENNTTTYTFGNAPVKAEAEI
reference       PSFKPYSGTAYNSLAPKGAPNSSQWAQK--KTGED------NQTETRTFG-VAAMGGILI
                *********************:***  :  *.**:      *:* * *** ... .   *

predicted       TKEGLPIGLKVSDEESKPIYADKTYQPEPQLGDETWTDLDGKTEKYGGRALKPDTKMKPC
reference       DKNGLQIGTDETKPDNKEIYADKTFQPEPQKGEENWQDGD---VFYGGRTIKKETKMKPC
                 *:** ** . :. :.* ******:***** *:*.* * *     ****::* :******

predicted       YGSFAKPTTVKGGQAKPKTTEQPNQKVEYDIDMEFFDA--ASQKTNLSPKIVMYAENVNL
reference       YGSFARPTNEKGGQAKFKTNAEGQPTEELDIDLNFFDINGGAGDNEFNPDMVMYAENMNL
                *****:**. ****** **. : : . * ***::***   .: ..::.*.:******:**

predicted       ETPDTHVVYKPESEDTSSEANLGQQSMPNRPNYIGFRDNFIGLMYYNSTGNMGVLAGQAS
reference       ETPDTHVVYKPGTSDDSSEANLAQQSMPNRPNYIGFRDNFVGLMYYNSTGNMGVLAGQAS
                *********** :.* ******.*****************:*******************

predicted       QLNAVVDLQDRNTELSYQLLLDSLGDRTRYFSMWNQAVDSYDPDVRVIENHGVEDELPNY
reference       QLNAVVDLQDRNTELSYQLLLDSLGDRTRYFSMWNSAVDSYDPDVRIIENHGVEDELPNY
                ***********************************.**********:*************

predicted       CFPLNGIGVPTTSYKSIVSNGDNAPNWKEPEVNGTSEIRQGNLSAMEINLQANLWRSFLY
reference       CFPLDGTGTNST-YQGVKETAAQNGWEKDPNVAAQNQICKGNIYAMEINLQANLWKSFLY
                ****:* *. :* *:.: ... :    *:*:* . .:* :**: ***********:****

predicted       SNVALYLPDSYKYTPSNVTLPENKNTYDYMNGRVVPPSLVDTYVNIGARWSLDAMDNVNP
reference       SNVALYLPDSYKYTPANVTLPANTNTYEYMNGRVVAPSLVDAYINIGARWSLDPMDNVNP
                ***************:***** *.***:*******.*****:*:*********.******

predicted       FNHHRNAGLRYRSMLLGNGRYVPFHIQVPQKFFAVKNLLLLPGSYTYEWNFRKDVNMVLQ
reference       FNHHRNAGLRYRSMLLGNGRYVPFHIQVPQKFFAIKNLLLLPGSYTYEWNFRKDVNMILQ
                **********************************:**********************:**

predicted       SSLGNDLRVDGASISFTSINLYATFFPMAHNTASTLEAMLRNDTNDQSFNDYLSAANMLY
reference       SSLGNDLRVDGASVRFDSVNLYATFFPMAHNTASTLEAMLRNDTNDQSFNDYLSAANMLY
                *************: * *:*****************************************

predicted       PIPANATNIPISIPSRNWAAFRGWSFTRLKTKETPSLGSGFDPYFVYSGSIPYLDGTFYL
reference       PIPAKATNVPISIPSRNWAAFRGWSFTRLKTKETPSLGSGFDPYFVYSGSIPYLDGTFYL
                ****:***:***************************************************

predicted       NHTFKKVSIMFDSSVSWPGNDRLLSPNEFEIKRTVDGEGYNVAQCNMTKDWFLVQMLANY
reference       NHTFKKVSIMFDSSVSWPGNDRLLTPNEFEIKRSVDGEGYNVAQCNMTKDWFLVQMLSHY
                ************************:********:***********************::*

predicted       NIGYQGFYIPEGYKDRMYSFFRNFQPMSRQVVDEVNYKDFKAVAIPYQHNNSGFVGYMAP
reference       NIGYQGFHVPEGYKDRMYSFFRNFQPMSRQVVDEINYKDYKAVTLPFQHNNSGFTGYLAP
                *******::*************************:****:***::*:*******.**:**

predicted       TMRQGQPYPANYPYPLIGTTAVNSVTQKKFLCDRTMWRIPFSSNFMSMGALTDLGQNMLY
reference       TMRQGQPYPANFPYPLIGSTAVPSVTQKKFLCDRVMWRIPFSSNFMSMGALTDLGQNMLY
                ***********:******:*** ***********.*************************

predicted       ANSAHALDMTFEVDPMDEPTLLYLLFEVFDVVRVHQPHRGIIETVYLRTPFSAGNATT
reference       ANSAHALDMTFEVDPMDEPTLLYLLFEVFDVVRVHQPHRGVIEAVYLRTPFSAGNATT
                ****************************************:**:**************

>37.21	18237	21080
taggcgtgcaaagtgtaaaacgccgtcgctgcttttaattaaatatggagtagcgcttaa
cttgcctatctgtgtatatgtgtcattacacgccgtcacagcagcagaggaaaaaaggaa
gaggtcgtgcgtcgacgctgagttactttcAAGATGGCCACCCCATCGATGCTGCCCCAG
TGGGCATACATGCACATCGCCGGACAGGATGCTTCGGAGTACCTGAGTCCGGGTCTGGTG
CAGTTCGCCCGCGCCACAGACACCTACTTCAATCTGGGAAATAAGTTTAGAAATCCCACC
GTAGCGCCGACCCACGATGTGACCACCGATCGTAGCCAGCGGCTCATGTTGCGCTTCGTG
CCCGTTGACCGGGAGGACAATACATACTCTTACAAAGTGCGGTACACACTGGCCGTGGGC
GACAACAGAGTGCTGGATATGGCCAGCACGTTCTTTGACATTAGGGGCGTGTTGGACAGA
GGTCCCAGTTTCAAACCCTATTCTGGTACGGCTTACAACTCTCTGGCTCCTAAAGGCGCT
CCAAATACATCTCAGTGGATTGCAGAAGGTGTAAAAAATGGTGAGGAGCGCGTAACAGAA
GAGGAAAACAATACTACTACTTACACTTTTGGCAATGCTCCCGTAAAAGCTGAAGCTGAA
ATTACAAAAGAAGGACTCCCAATAGGTTTGAAAGTTTCAGATGAAGAAAGTAAACCGATT
TATGCTGATAAAACATATCAGCCAGAACCTCAGCTGGGAGATGAAACTTGGACTGACCTT
GATGGAAAGACCGAAAAGTATGGGGGCAGGGCTCTCAAACCAGATACTAAAATGAAACCA
TGCTACGGGTCCTTTGCCAAACCTACTACTGTGAAAGGCGGTCAGGCAAAACCAAAAACA
ACGGAGCAGCCAAATCAGAAAGTCGAATATGATATTGACATGGAGTTTTTTGATGCGGCA
TCACAGAAAACAAACTTAAGTCCTAAAATTGTCATGTATGCAGAAAATGTAAATTTGGAA
ACTCCAGACACTCATGTAGTGTACAAACCTGAATCAGAAGACACAAGTTCCGAAGCTAAT
TTGGGACAACAGTCTATGCCCAACAGACCCAACTACATTGGCTTCAGAGATAACTTTATT
GGACTTATGTACTATAACAGTACTGGTAACATGGGGGTGCTGGCTGGTCAAGCGTCTCAG
TTAAATGCAGTGGTTGACTTGCAGGACAGAAACACAGAACTTTCTTACCAACTCTTGCTT
GACTCTCTGGGCGACAGAACCAGATACTTTAGCATGTGGAATCAGGCTGTGGACAGTTAT
GATCCTGATGTACGTGTTATTGAAAATCATGGTGTGGAAGATGAACTTCCAAACTATTGT
TTTCCACTGAATGGCATAGGGGTTCCAACAACCAGTTACAAATCAATAGTTTCAAATGGA
GACAATGCACCTAATTGGAAGGAACCTGAAGTAAATGGAACAAGTGAGATCAGACAGGGT
AATTTGTCTGCCATGGAAATTAACCTTCAAGCCAATCTATGGCGAAGTTTCCTTTATTCC
AATGTGGCTCTGTATCTCCCAGACTCGTACAAATACACCCCGTCCAATGTCACTCTTCCA
GAAAACAAAAACACCTACGACTACATGAACGGGCGGGTGGTGCCGCCATCTCTAGTAGAC
ACCTATGTGAACATTGGCGCCAGGTGGTCTCTGGATGCTATGGACAATGTCAACCCATTC
AACCACCACCGTAACGCTGGCTTGCGTTACCGATCCATGCTTCTGGGTAACGGACGTTAT
GTGCCTTTCCACATACAAGTGCCTCAAAAATTCTTCGCTGTCAAAAACCTGCTGCTTCTC
CCAGGCTCCTACACTTATGAGTGGAACTTCAGAAAGGATGTGAACATGGTGCTACAGAGT
TCCCTTGGTAACGACCTACGGGTAGATGGCGCCAGCATCAGTTTCACGAGCATCAACCTC
TATGCTACCTTTTTCCCCATGGCTCACAACACCGCTTCCACCCTTGAAGCCATGCTGCGG
AATGACACCAATGATCAGTCATTCAACGACTACCTATCTGCAGCTAACATGCTCTATCCC
ATTCCTGCCAATGCAACCAATATTCCCATTTCCATTCCTTCTCGCAACTGGGCGGCTTTC
AGAGGCTGGTCATTTACCAGACTCAAAACCAAAGAAACTCCCTCTTTGGGGTCTGGATTT
GACCCCTACTTTGTCTATTCTGGTTCTATTCCCTACCTGGATGGTACCTTCTACCTGAAC
CACACTTTTAAGAAGGTTTCCATCATGTTTGACTCTTCAGTGAGCTGGCCTGGAAATGAC
AGGTTACTATCTCCCAACGAATTTGAAATAAAGCGCACTGTGGATGGCGAAGGCTACAAC
GTAGCCCAATGCAACATGACCAAAGACTGGTTCTTGGTACAGATGCTCGCCAACTACAAC
ATCGGCTATCAGGGCTTCTACATTCCAGAAGGATACAAAGATCGCATGTATTCATTTTTC
AGAAACTTCCAGCCCATGAGCAGGCAGGTGGTTGATGAGGTCAATTACAAAGACTTCAAG
GCCGTCGCCATACCCTACCAACACAACAACTCTGGCTTTGTGGGTTACATGGCTCCGACC
ATGCGCCAAGGTCAACCCTATCCCGCTAACTATCCCTATCCACTCATTGGAACAACTGCC
GTAAATAGTGTTACGCAGAAAAAGTTCTTGTGTGACAGAACCATGTGGCGCATACCGTTC
TCGAGCAACTTCATGTCTATGGGGGCCCTTACAGACTTGGGACAGAACATGCTTTATGCC
AACTCAGCTCATGCTCTGGACATGACCTTTGAGGTGGATCCCATGGATGAGCCCACCCTG
CTTTATCTTCTCTTCGAAGTTTTCGACGTGGTCAGAGTGCATCAGCCACATCGCGGCATC
ATCGAGACAGTCTACCTGCGTACACCGTTCTCGGCCGGTAACGCTACCACGTAAaaagct
tcttgcttcttgcaaacagcagcagctgcaaccatggcctgcggatcccaaaacggctcc
agcgagcaagagctcagagccattgtccaagacctgggttgcggaccctattttttggga
acctacgataagcgcttcccgggg

Length = 945

Score =   318 bits (689), Expect(5) = 0.0
Identities = 128/136 (94%), Positives = 133/136 (97%)
Frame = +3

Query: 18237 KMATPSMLPQWAYMHIAGQDASEYLSPGLVQFARATDTYFNLGNKFRNPTVAPTHDVTTD 18416
             KMATPSM+PQWAYMHIAGQDASEYLSPGLVQFARATDTYF+LGNKFRNPTVAPTHDVTTD
Sbjct: 10    KMATPSMMPQWAYMHIAGQDASEYLSPGLVQFARATDTYFSLGNKFRNPTVAPTHDVTTD 69

Query: 18417 RSQRLMLRFVPVDREDNTYSYKVRYTLAVGDNRVLDMASTFFDIRGVLDRGPSFKPYSGT 18596
             RSQRL LRFVPVDRED TYSYK R+TLAVGDNRVLDMAST+FDIRGVLDRGPSFKPYSGT
Sbjct: 70    RSQRLTLRFVPVDREDTTYSYKARFTLAVGDNRVLDMASTYFDIRGVLDRGPSFKPYSGT 129

Query: 18597 AYNSLAPKGAPNTSQW 18644
             AYNSLAPKGAPN+SQW
Sbjct: 130   AYNSLAPKGAPNSSQW 145

Score =  22.6 bits (43), Expect(5) = 0.0
Identities = 9/18 (50%), Positives = 12/18 (66%)
Frame = +3

Query: 18672 ERVTEEENNTTTYTFGNA 18725
             ++ T E+N T T TFG A
Sbjct: 147   QKKTGEDNQTETRTFGVA 164

Score =  58.3 bits (121), Expect(5) = 0.0
Identities = 23/41 (56%), Positives = 28/41 (68%)
Frame = +3

Query: 18747 ITKEGLPIGLKVSDEESKPIYADKTYQPEPQLGDETWTDLD 18869
             I K GL IG   +  ++K IYADKT+QPEPQ G+E W D D
Sbjct: 171   IDKNGLQIGTDETKPDNKEIYADKTFQPEPQKGEENWQDGD 211

Score =  84.9 bits (179), Expect(2) = 3e-21
Identities = 33/52 (63%), Positives = 38/52 (73%)
Frame = +3

Query: 18885 YGGRALKPDTKMKPCYGSFAKPTTVKGGQAKPKTTEQPNQKVEYDIDMEFFD 19040
             YGGR +K +TKMKPCYGSFA+PT  KGGQAK KT  +     E DID+ FFD
Sbjct: 214   YGGRTIKKETKMKPCYGSFARPTNEKGGQAKFKTNAEGQPTEELDIDLNFFD 265

Score =   329 bits (713), Expect(5) = 0.0
Identities = 132/175 (75%), Positives = 148/175 (84%)
Frame = +3

Query: 18975 KPKTTEQPNQKVEYDIDMEFFDAASQKTNLSPKIVMYAENVNLETPDTHVVYKPESEDTS 19154
             K     QP ++++ D++    +  +     +P +VMYAEN+NLETPDTHVVYKP + D S
Sbjct: 246   KTNAEGQPTEELDIDLNFFDINGGAGDNEFNPDMVMYAENMNLETPDTHVVYKPGTSDDS 305

Query: 19155 SEANLGQQSMPNRPNYIGFRDNFIGLMYYNSTGNMGVLAGQASQLNAVVDLQDRNTELSY 19334
             SEANL QQSMPNRPNYIGFRDNF+GLMYYNSTGNMGVLAGQASQLNAVVDLQDRNTELSY
Sbjct: 306   SEANLAQQSMPNRPNYIGFRDNFVGLMYYNSTGNMGVLAGQASQLNAVVDLQDRNTELSY 365

Query: 19335 QLLLDSLGDRTRYFSMWNQAVDSYDPDVRVIENHGVEDELPNYCFPLNGIGVPTT 19499
             QLLLDSLGDRTRYFSMWN AVDSYDPDVR+IENHGVEDELPNYCFPL+G G  +T
Sbjct: 366   QLLLDSLGDRTRYFSMWNSAVDSYDPDVRIIENHGVEDELPNYCFPLDGTGTNST 420

Score =  1171 bits (2550), Expect(5) = 0.0
Identities = 464/511 (90%), Positives = 492/511 (96%)
Frame = +3

Query: 19545 KEPEVNGTSEIRQGNLSAMEINLQANLWRSFLYSNVALYLPDSYKYTPSNVTLPENKNTY 19724
             K+P V   ++I +GN+ AMEINLQANLW+SFLYSNVALYLPDSYKYTP+NVTLP N NTY
Sbjct: 435   KDPNVAAQNQICKGNIYAMEINLQANLWKSFLYSNVALYLPDSYKYTPANVTLPANTNTY 494

Query: 19725 DYMNGRVVPPSLVDTYVNIGARWSLDAMDNVNPFNHHRNAGLRYRSMLLGNGRYVPFHIQ 19904
             +YMNGRVV PSLVD Y+NIGARWSLD MDNVNPFNHHRNAGLRYRSMLLGNGRYVPFHIQ
Sbjct: 495   EYMNGRVVAPSLVDAYINIGARWSLDPMDNVNPFNHHRNAGLRYRSMLLGNGRYVPFHIQ 554

Query: 19905 VPQKFFAVKNLLLLPGSYTYEWNFRKDVNMVLQSSLGNDLRVDGASISFTSINLYATFFP 20084
             VPQKFFA+KNLLLLPGSYTYEWNFRKDVNM+LQSSLGNDLRVDGAS+ F S+NLYATFFP
Sbjct: 555   VPQKFFAIKNLLLLPGSYTYEWNFRKDVNMILQSSLGNDLRVDGASVRFDSVNLYATFFP 614

Query: 20085 MAHNTASTLEAMLRNDTNDQSFNDYLSAANMLYPIPANATNIPISIPSRNWAAFRGWSFT 20264
             MAHNTASTLEAMLRNDTNDQSFNDYLSAANMLYPIPA ATN+PISIPSRNWAAFRGWSFT
Sbjct: 615   MAHNTASTLEAMLRNDTNDQSFNDYLSAANMLYPIPAKATNVPISIPSRNWAAFRGWSFT 674

Query: 20265 RLKTKETPSLGSGFDPYFVYSGSIPYLDGTFYLNHTFKKVSIMFDSSVSWPGNDRLLSPN 20444
             RLKTKETPSLGSGFDPYFVYSGSIPYLDGTFYLNHTFKKVSIMFDSSVSWPGNDRLL+PN
Sbjct: 675   RLKTKETPSLGSGFDPYFVYSGSIPYLDGTFYLNHTFKKVSIMFDSSVSWPGNDRLLTPN 734

Query: 20445 EFEIKRTVDGEGYNVAQCNMTKDWFLVQMLANYNIGYQGFYIPEGYKDRMYSFFRNFQPM 20624
             EFEIKR+VDGEGYNVAQCNMTKDWFLVQML++YNIGYQGF++PEGYKDRMYSFFRNFQPM
Sbjct: 735   EFEIKRSVDGEGYNVAQCNMTKDWFLVQMLSHYNIGYQGFHVPEGYKDRMYSFFRNFQPM 794

Query: 20625 SRQVVDEVNYKDFKAVAIPYQHNNSGFVGYMAPTMRQGQPYPANYPYPLIGTTAVNSVTQ 20804
             SRQVVDE+NYKD+KAV +P+QHNNSGF GY+APTMRQGQPYPAN+PYPLIG+TAV SVTQ
Sbjct: 795   SRQVVDEINYKDYKAVTLPFQHNNSGFTGYLAPTMRQGQPYPANFPYPLIGSTAVPSVTQ 854

Query: 20805 KKFLCDRTMWRIPFSSNFMSMGALTDLGQNMLYANSAHALDMTFEVDPMDEPTLLYLLFE 20984
             KKFLCDR MWRIPFSSNFMSMGALTDLGQNMLYANSAHALDMTFEVDPMDEPTLLYLLFE
Sbjct: 855   KKFLCDRVMWRIPFSSNFMSMGALTDLGQNMLYANSAHALDMTFEVDPMDEPTLLYLLFE 914

Query: 20985 VFDVVRVHQPHRGIIETVYLRTPFSAGNATT 21077
             VFDVVRVHQPHRG+IE VYLRTPFSAGNATT
Sbjct: 915   VFDVVRVHQPHRGVIEAVYLRTPFSAGNATT 945


========================================================================================================================

gene_id            %id    %sim   %cov   %t5   %gap  %t3   start..stop      pep sz ref sz ref id            definition
37.22              46.8   59.7   100.0  0.0   0.0   0.0   25584..25679     114    173    YP_001974455.1    L4-3 | splicing factor
                                                          26185..26433                                     
                    invalid splicing for intron  at 25680..26184

CLUSTAL 2.1 multiple sequence alignment


predicted       MSQRR------------ESKK------LKVQPPPPEDMEED-------------------
reference       MPRKKQEPLVEEMEEEWDSQAEEDEWEEETEEEELEEVEEEQATEQPVAAPSAPAAPAVT
                *.:::            :*:        :.:    *::**:                   

predicted       -------------WD--------SQAEEAEGG-LKITANEPAQTRELRNRIFPTLYAIFQ
reference       DTTSAAPAKPPRRWDRVKGDAKKKQVREVAGGGLRIAANEPLTTRELRNRIFPTLYAIFQ
                             **        .*..*. ** *:*:****  *****************

predicted       QSRGQEHELKIKNRSLRSLTRSCLYHKSEDQLQRTLEDAEALFNKYCALTLKE
reference       QSRGQQQELKVKNRSLRSLTRSCLYHKNEDQLQRTLEDAEALFHKYCALTLKD
                *****::***:****************.***************:********:

>37.27	25584	26433
aactttcggcctgcgtcatcacccagggggcaattctagcccaattgcaagccatccaaa
aatcccgccaagaatttctactgaaaaagggtaagggggtctaccttgacccccagaccg
gcgaggaactcaacacaaggttccctcaggATGTCCCAACGACGAGAAAGCAAGAAGTTG
AAGGTGCAGCCGCCGCCCCCAGAAGATATGGAGGAAGATTGGGACAGTCAGGCAGAGGAA
GCGGAGgaggacagtctggaggacagtctggaggaagacagtttggaggaggaaaacgag
gaggcagaggaggtggaagaagtaaccgccggcaaacagttatccccggctgcggagaca
agcaacagcgctatcatctccgctccgagtcgaggaacgcggcggcgtcccagcagtaga
tgggacgagaccggacgcttcccaaacccaaccaccgcttccaaaaccggtaagaaggat
cggcagggatacaagtcctggcgggggcataagaatgccatcatctcctgcttgcatgag
tgcgggggaaacatatccttcacgcgacgctacttgctattccaccatggggtgaacttt
ccgcgcaatgttttgcattactaccgtcacctccacagcccctactatagccagcaaatc
ccggcagtctcgacagaaaaagacagcggcggcgacctccaacagaaaaccagcagcggc
agttaaaaaatacacaacaagtgcagcaacaGGAGGATTAAAGATTACAGCCAACGAGCC
AGCGCAAACCCGAGAGCTAAGAAATCGGATCTTTCCAACCCTGTATGCCATCTTCCAGCA
GAGTCGGGGCCAAGAGCATGAACTGAAAATAAAAAACCGATCTTTGCGTTCGCTCACCAG
AAGTTGTTTGTATCACAAGAGCGAAGATCAACTTCAGCGCACTCTTGAGGACGCCGAGGC
TCTCTTCAACAAGTACTGCGCGCTGACTCTTAAAGAGTAGgcagcgaccgcgcttattca
aaaaaggcgggaattacatcatcctcgtcatgagtaaagaaattcccacgccttacatgt
ggagttatcagccccaaatgggattggcggcaggcgcctcccaggactactccacccgca
tgaattggct

Length = 173

Score =  45.5 bits (93), Expect(2) = 4e-57
Identities = 21/50 (42%), Positives = 29/50 (58%)
Frame = +3

Query: 25614 KVQPPPPEDMEEDWDSQAEEAEEDSLEDSLEEDSLEEENEEAEEVEEVTA 25763
             K Q P  E+MEE+WDSQAEE E +   +  E + +EEE    + V   +A
Sbjct: 4     KKQEPLVEEMEEEWDSQAEEDEWEEETEEEELEEVEEEQATEQPVAAPSA 53

Score =   181 bits (390), Expect(2) = 4e-57
Identities = 77/99 (77%), Positives = 84/99 (84%)
Frame = +1

Query: 26134 NRKPAAAVKKYTTSAATGGLKITANEPAQTRELRNRIFPTLYAIFQQSRGQEHELKIKNR 26313
             +R    A KK     A GGL+I ANEP  TRELRNRIFPTLYAIFQQSRGQ+ ELK+KNR
Sbjct: 75    DRVKGDAKKKQVREVAGGGLRIAANEPLTTRELRNRIFPTLYAIFQQSRGQQQELKVKNR 134

Query: 26314 SLRSLTRSCLYHKSEDQLQRTLEDAEALFNKYCALTLKE 26430
             SLRSLTRSCLYHK+EDQLQRTLEDAEALF+KYCALTLK+
Sbjct: 135   SLRSLTRSCLYHKNEDQLQRTLEDAEALFHKYCALTLKD 173


========================================================================================================================

gene_id            %id    %sim   %cov   %t5   %gap  %t3   start..stop      pep sz ref sz ref id            definition
57.3               71.8   84.1   95.5   4.5   0.0   0.0   6019..6276       85     89     ACI47083.1        HYP-2 | hypothetical protein
                    could not find valid start codon

CLUSTAL 2.1 multiple sequence alignment


predicted       ----TYSRAMHFQVGKTVVRSSGNNRRRHPRLCSVTKSTLVTTSPRKLSLVQAKRPPFRE
reference       MLSWTYSRATHFHSGKTVVRSSGTILTRQPRLCRVTRSTLVATSPRRGSLVQQRRPPLRE
                    ***** **: *********.   *:**** **:****:****: **** :***:**

predicted       QKGGRTSSWFSSGGSASTVKMPGHKILSK
reference       QNGGSTSSRCSSGGSASMVKMPGQSSLSK
                *:** ***  ******* *****:. ***

>57.6	6019	6276
tcttccatttgatcagaaaaaacaatttttttgttatctaattttgtagcaaaggatccg
tacagggcgtttgaaagtaacttggctatagatcttagcgtttggtttttgtccctgtct
gcccgttcttttgcggcgatattgagttgtACATATTCACGAGCAATGCATTTCCAAGTG
GGAAAAACGGTGGTACGTTCGTCTGGTAATAATCGCAGACGCCACCCGCGATTATGCAGT
GTAACTAAGTCTACACTGGTGACCACTTCGCCGCGCAAGCTCTCATTAGTCCAGGCTAAA
CGACCGCCTTTTCGAGAGCAAAAAGGAGGAAGAACATCCAGCTGGTTTTCGTCTGGAGGA
TCAGCATCCACAGTAAAAATGCCAGGACATAAAATTTTATCAAAATAAtcaattttggaa
gtaagattttcaagtgccacctgccactgccgtacggctaatgctcgttcgtaagggtta
agaggaggaccccaaggcatagggtgtgtaagggctgatgcatacatgccacaaatatca
tatacatatatgggttcc

Length = 89

Score =   138 bits (296), Expect = 5e-38
Identities = 63/89 (70%), Positives = 67/89 (75%)
Frame = +1

Query: 6007 ILSCTYSRAMHFQVGKTVVRSSGNNRRRHPRLCSVTKSTLVTTSPRKLSLVQAKRPPFRE 6186
            +LS TYSRA HF  GKTVVRSSG    R PRLC VT+STLV TSPR+ SLVQ +RPP RE
Sbjct: 1    MLSWTYSRATHFHSGKTVVRSSGTILTRQPRLCRVTRSTLVATSPRRGSLVQQRRPPLRE 60

Query: 6187 QKGGRTSSWFSSGGSASTVKMPGHKILSK 6273
            Q GG TSS  SSGGSAS VKMPG   LSK
Sbjct: 61   QNGGSTSSRCSSGGSASMVKMPGQSSLSK 89


========================================================================================================================

gene_id            %id    %sim   %cov   %t5   %gap  %t3   start..stop      pep sz ref sz ref id            definition
57.14              81.0   91.3   99.1   0.9   0.0   0.0   17613..20384     923    953    YP_003038612-T5   L3-2 | hexon
                    could not find valid start codon

CLUSTAL 2.1 multiple sequence alignment


predicted       ---------KMATPSMMPQWSYMHIAGQDASEYLSPGLVQFARATDTYFTLGNKFRNPTV
reference       MCLTARERAKMATPSMMPQWAYMHIAGQDASEYLSPGLVQFARATDTYFSLGNKFRNPTV
                         ***********:****************************:**********

predicted       APTHDVTTDRSQRLTLRFVPVDREDTAYSYKARFTLAVGDNRVLDMASSYFDIRGVLDRG
reference       APTHDVTTDRSQRLTLRFVPVDREDTTYSYKARFTLAVGDNRVLDMASTYFDIRGVLDRG
                **************************:*********************:***********

predicted       PSFKPYSGTAYNSLAPKGAPNASQWLT--TNNGN---KTHTFAQAPYIGDSISKDGIQVG
reference       PSFKPYSGTAYNSLAPKGAPNSSQWITKQTNAGNETTKTHTYGVAAMGGADITIKGLQIG
                *********************:***:*  ** **   ****:. *.  * .*: .*:*:*

predicted       TN-TANPQQAVYADKTYQPEPQVGESQWNASVSNNAKAAGRVLKSTTPMYPCYGSYARAT
reference       VDKTENKNEPIYANEIYQPEPQVGEENLQD-VEN--YYGGRALKKETKMKPCYGSFARPT
                .: * * ::.:**:: *********.: :  *.*    .**.**. * * *****:**.*

predicted       NEKGGQS---KNNDG-------VEMRFFAS----SANDNQNDPTVVMYSEDVNLEAPDTH
reference       NEKGGQAVFKTGNDGQPTTEHDITMAFFDTPGDTNAEDTELEADIVMYTENVNLETPDTH
                ******:   ..***       : * ** :    .*:*.: :. :***:*:****:****

predicted       IVYKPAVTADTISSELLLGQQAAPNRPNYIAFRDNFIGLMYYNSTGNMGVLAGQASQLNA
reference       VVYKPGPLED--SSEINLTQQSMPNRPNYIGFRDNFVGLMYYNSTGNMGVLAGQASQLNA
                :****.   *  ***: * **: *******.*****:***********************

predicted       VVDLQDRNTELSYQLMLDALGDRSRYFSMWNSAVDSYDPDVRIIENHGVEDELPNYCFPL
reference       VVDLQDRNTELSYQLLLDSLGDRTRYFSMWNSAVDSYDPDVRIIENHGVEDELPNYCFPL
                ***************:**:****:************************************

predicted       GAVGVVNSYKGVKQNDG-NG-----WVKDDSVADTNDIAKGNIFAMEINLQANLWRSFLY
reference       DGAGTNATYQGVKVKNGQDGDNNAEWEKDNAVADRNQICKGNIVAMEINLQANLWKSFLY
                ...*.  :*:*** ::* :*     * **::*** *:*.****.***********:****

predicted       SNVGLYLPDDLKYTPGNIKLPENKNTYEYMNGRVTVPGLVDTYVNIGARWSPDVMDNINP
reference       SNVALYLPDSFKYTPANVTLPTNTNTYEYMNGRVVAPSLVDAYVNIGARWSLDPMDNVNP
                ***.*****.:****.*:.** *.**********..*.***:********* * ***:**

predicted       FNHHRNAGLRYRSMLLGNGRFVPFHIQVPQKFFAIKNLLLLPGSYTYEWNFRKDVNMILQ
reference       FNHHRNAGLRYRSMLLGNGRYVPFHIQVPQKFFAIKNLLLLPGSYTYEWNFRKDVNMILQ
                ********************:***************************************

predicted       STLGNDLRVDGASIRFDNIALYANFFPMAHNTASTLEAMLRNDTNDQSFNDYLCAANMLY
reference       SSLGNDLRVDGASVRFDSVNLYATFFPMAHNTASTLEAMLRNDTNDQSFNDYLSAANMLY
                *:***********:***.: ***.*****************************.******

predicted       PIPANATSVPISIPSRNWAAFRGWSFTRLKTKETPSLGSGFDPYFVYSGTIPYLDGTFYL
reference       PIPAKATNVPISIPSRNWAAFRGWSFTRLKTKETPSLGSGFDPYFVYSGSIPYLDGTFYL
                ****:**.*****************************************:**********

predicted       NHTFKKVSIMFDSSVSWPGNDRLLTPNEFEIKRSVDGEGYNVAQCNMTKDWFLVQMLSHY
reference       NHTFKKVSIMFDSSVSWPGNDRLLTPNEFEIKRSVDGEGYNVAQCNMTKDWFLIQMLSHY
                *****************************************************:******

predicted       NIGYQGFYVPESYKDRMYSFFRNFQPMSRQVVDTTEYKEYKKVTVEFQHNNSGFVGYLGP
reference       NIGYQGFHVPEGYKDRMYSFFRNFQPMSRQVVDEINYKDYKAVALPFQHNNSGFTGYLAP
                *******:***.*********************  :**:** *:: ********.***.*

predicted       TMREGQAYPANYPYPLIGKTAVQSVTQKKFLCDRVMWRIPFSSNFMSMGALTDLGQNMLY
reference       TMRQGQPYPANFPYPLIGETAVPSVTQKKFLCDRVMWRIPFSSNFMSMGALTDLGQNMLY
                ***:**.****:******:*** *************************************

predicted       ANSAHALDMTFEVDPMEEPTLLYVLFEVFDVVRIHQPHRGVIEAVYLRTPFSAGNATT
reference       ANSAHALDMTFEVDPMDEPTLLYLLFEVFDVVRVHQPHRGVIEAVYLRTPFSAGNATT
                ****************:******:*********:************************

>57.17	17613	20384
aacagcattgtgggactgggagtaaagtctttaaaacgcagacgctgctattaacattaa
acaaaacatagtgttaactcccgtctgtatacgcctctatgttagcgccagaggaccaac
gctcgaattgcagttattaccagcgctttcAAGATGGCCACTCCCTCGATGATGCCGCAG
TGGTCTTACATGCACATCGCCGGTCAGGACGCCTCGGAGTACCTGAGTCCCGGTCTGGTG
CAATTCGCCCGCGCCACGGACACCTACTTCACCCTGGGAAACAAGTTTAGGAATCCCACT
GTGGCTCCCACCCATGATGTCACCACCGACCGCTCGCAGCGGTTGACGCTGCGTTTTGTG
CCCGTGGATCGGGAAGATACTGCTTATTCTTACAAGGCTCGCTTTACGCTGGCTGTGGGG
GACAATCGCGTGCTTGACATGGCTAGCTCTTACTTTGATATTAGAGGGGTGCTGGATCGC
GGTCCCAGTTTTAAGCCTTATTCGGGTACCGCCTATAACTCTTTAGCTCCAAAGGGCGCG
CCCAATGCCAGCCAATGGCTAACTACAAACAATGGCAACAAAACTCACACTTTTGCTCAA
GCGCCTTACATAGGAGACTCTATCAGTAAAGACGGCATTCAAGTTGGGACAAACACTGCC
AATCCCCAGCAAGCAGTATATGCCGACAAAACATACCAGCCAGAACCTCAAGTAGGCGAA
AGTCAATGGAACGCTTCAGTATCTAACAATGCAAAAGCAGCAGGAAGGGTGTTAAAAAGC
ACTACGCCCATGTATCCGTGCTATGGGTCTTATGCACGAGCAACAAATGAAAAAGGAGGT
CAATCAAAAAATAACGACGGTGTGGAAATGCGATTTTTTGCATCCAGTGCGAATGACAAT
CAAAATGATCCAACTGTTGTAATGTATAGCGAGGACGTAAACTTAGAGGCTCCTGACACA
CACATTGTTTACAAACCAGCTGTAACTGCGGACACTATCAGTTCAGAACTCCTCCTAGGA
CAACAAGCAGCACCTAACAGACCAAATTACATTGCCTTCAGAGACAATTTTATTGGGCTT
ATGTATTACAACAGCACTGGAAACATGGGAGTACTTGCAGGACAGGCTTCTCAGCTCAAT
GCAGTGGTTGATCTGCAAGATAGGAACACAGAGCTGTCCTACCAACTTATGTTGGATGCT
TTAGGCGATAGAAGCCGTTATTTTTCCATGTGGAATTCTGCCGTCGACAGCTACGATCCA
GACGTGCGAATTATTGAAAATCATGGTGTGGAAGACGAACTGCCCAATTACTGTTTTCCG
TTAGGGGCTGTAGGCGTTGTGAATTCATACAAAGGTGTGAAACAAAATGACGGAAATGGT
TGGGTAAAAGATGACAGTGTAGCAGATACCAATGACATAGCCAAAGGTAATATATTTGCC
ATGGAAATTAACTTACAGGCAAATTTGTGGAGAAGTTTTCTGTATTCAAATGTGGGGCTG
TACCTGCCTGACGACTTGAAATACACCCCCGGGAACATAAAACTTCCAGAAAACAAAAAC
ACCTACGAGTACATGAACGGGCGCGTGACTGTTCCCGGTCTGGTAGACACCTACGTTAAC
ATTGGCGCGCGCTGGTCTCCTGACGTAATGGATAACATAAACCCTTTTAACCACCACCGA
AACGCAGGGTTGCGCTATAGGTCCATGTTACTGGGCAACGGTAGATTTGTTCCGTTTCAC
ATTCAGGTACCTCAGAAATTTTTCGCTATTAAGAATTTGCTGCTGTTACCAGGGTCCTAC
ACTTATGAGTGGAACTTCAGAAAAGATGTAAACATGATACTTCAGAGCACCCTGGGCAAT
GATCTTAGAGTGGACGGAGCCAGCATTCGCTTTGACAACATTGCCCTGTATGCAAACTTC
TTCCCCATGGCTCACAATACAGCTTCTACATTGGAAGCCATGCTGCGAAATGACACCAAT
GACCAGTCTTTCAACGATTACTTGTGCGCGGCGAACATGTTGTATCCCATTCCAGCAAAT
GCCACCAGCGTGCCCATTTCAATACCTTCGCGAAATTGGGCAGCCTTCAGAGGGTGGAGT
TTTACTCGCCTTAAAACTAAAGAGACACCTTCTCTTGGTTCAGGGTTTGACCCCTACTTT
GTTTACTCTGGAACCATTCCCTACCTGGACGGGACTTTTTACCTGAACCACACTTTTAAA
AAGGTGTCAATCATGTTTGACTCCTCTGTTAGCTGGCCTGGAAATGACAGGCTGTTAACA
CCAAATGAATTTGAAATAAAACGTTCTGTAGACGGGGAAGGCTACAATGTGGCCCAATGT
AATATGACCAAAGATTGGTTTCTAGTACAAATGCTCAGTCATTATAATATTGGATACCAG
GGTTTTTACGTTCCAGAGAGCTACAAAGACCGCATGTATTCTTTCTTCAGAAACTTTCAG
CCCATGAGCAGGCAGGTTGTAGACACTACTGAATACAAGGAGTATAAAAAAGTAACCGTG
GAATTCCAGCATAACAACTCAGGGTTTGTGGGATACCTGGGTCCTACTATGCGCGAGGGA
CAAGCTTATCCCGCAAACTACCCCTATCCTCTCATAGGAAAAACCGCTGTACAGAGCGTC
ACACAAAAAAAGTTTCTCTGTGACCGTGTGATGTGGCGCATTCCATTTTCTAGCAATTTT
ATGTCAATGGGGGCGTTGACAGACCTCGGGCAAAATATGCTGTATGCAAATTCGGCCCAT
GCGTTAGATATGACATTTGAAGTTGACCCCATGGAAGAGCCCACCCTTCTTTATGTTTTG
TTTGAAGTTTTCGACGTGGTGCGCATTCATCAACCACACCGCGGAGTCATTGAAGCGGTC
TATCTGCGCACACCCTTCTCCGCGGGTAACGCCACCACCTAAagaaggcactttcccaga
tcgctgtaatgggttcaagcgaacaggagctgacggcgattgttcgagatctaggctgtg
gaccctattttttgggtacctttgacaaacgttttcccggttttgtgtctcgcgaccgct
tatcatgcgcta

Length = 953

Score =   327 bits (709), Expect(6) = 0.0
Identities = 132/138 (95%), Positives = 137/138 (99%)
Frame = +3

Query: 17613 KMATPSMMPQWSYMHIAGQDASEYLSPGLVQFARATDTYFTLGNKFRNPTVAPTHDVTTD 17792
             KMATPSMMPQW+YMHIAGQDASEYLSPGLVQFARATDTYF+LGNKFRNPTVAPTHDVTTD
Sbjct: 10    KMATPSMMPQWAYMHIAGQDASEYLSPGLVQFARATDTYFSLGNKFRNPTVAPTHDVTTD 69

Query: 17793 RSQRLTLRFVPVDREDTAYSYKARFTLAVGDNRVLDMASSYFDIRGVLDRGPSFKPYSGT 17972
             RSQRLTLRFVPVDREDT YSYKARFTLAVGDNRVLDMAS+YFDIRGVLDRGPSFKPYSGT
Sbjct: 70    RSQRLTLRFVPVDREDTTYSYKARFTLAVGDNRVLDMASTYFDIRGVLDRGPSFKPYSGT 129

Query: 17973 AYNSLAPKGAPNASQWLT 18026
             AYNSLAPKGAPN+SQW+T
Sbjct: 130   AYNSLAPKGAPNSSQWIT 147

Score =  27.6 bits (54), Expect(6) = 0.0
Identities = 11/29 (37%), Positives = 16/29 (55%)
Frame = +3

Query: 18030 NNGNKTHTFAQAPYIGDSISKDGIQVGTN 18116
             N   KTHT+  A   G  I+  G+Q+G +
Sbjct: 154   NETTKTHTYGVAAMGGADITIKGLQIGVD 182

Score =  37.7 bits (76), Expect(6) = 0.0
Identities = 13/22 (59%), Positives = 17/22 (77%)
Frame = +3

Query: 18117 TANPQQAVYADKTYQPEPQVGE 18182
             T N  + +YA++ YQPEPQVGE
Sbjct: 184   TENKNEPIYANEIYQPEPQVGE 205

Score =  52.8 bits (109), Expect(6) = 0.0
Identities = 20/28 (71%), Positives = 22/28 (78%)
Frame = +3

Query: 18225 GRVLKSTTPMYPCYGSYARATNEKGGQS 18308
             GR LK  T M PCYGS+AR TNEKGGQ+
Sbjct: 217   GRALKKETKMKPCYGSFARPTNEKGGQA 244

Score =  53.8 bits (111), Expect(6) = 0.0
Identities = 19/38 (50%), Positives = 28/38 (73%)
Frame = +3

Query: 18345 SSANDNQNDPTVVMYSEDVNLEAPDTHIVYKPAVTADT 18458
             ++A D + +  +VMY+E+VNLE PDTH+VYKP    D+
Sbjct: 271   TNAEDTELEADIVMYTENVNLETPDTHVVYKPGPLEDS 308

Score =   258 bits (558), Expect(6) = 0.0
Identities = 107/144 (74%), Positives = 118/144 (81%)
Frame = +3

Query: 18462 SSELLLGQQAAPNRPNYIAFRDNFIGLMYYNSTGNMGVLAGQASQLNAVVDLQDRNTELS 18641
             SSE+ L QQ+ PNRPNYI FRDNF+GLMYYNSTGNMGVLAGQASQLNAVVDLQDRNTELS
Sbjct: 308   SSEINLTQQSMPNRPNYIGFRDNFVGLMYYNSTGNMGVLAGQASQLNAVVDLQDRNTELS 367

Query: 18642 YQLMLDALGDRSRYFSMWNSAVDSYDPDVRIIENHGVEDELPNYCFPLGAVGVVNSYKGV 18821
             YQL+LD+LGDR+RYFSMWNSAVDSYDPDVRIIENHGVEDELPNYCFPL   G   +Y+GV
Sbjct: 368   YQLLLDSLGDRTRYFSMWNSAVDSYDPDVRIIENHGVEDELPNYCFPLDGAGTNATYQGV 427

Query: 18822 KQNDGNGWVKDDSVADTNDIAKGN 18893
             K  +G     +      N +A  N
Sbjct: 428   KVKNGQDGDNNAEWEKDNAVADRN 451

Score =  1148 bits (2501), Expect = 0.0
Identities = 458/513 (89%), Positives = 480/513 (93%)
Frame = +3

Query: 18843 WVKDDSVADTNDIAKGNIFAMEINLQANLWRSFLYSNVGLYLPDDLKYTPGNIKLPENKN 19022
             W KD++VAD N I KGNI AMEINLQANLW+SFLYSNV LYLPD  KYTP N+ LP N N
Sbjct: 441   WEKDNAVADRNQICKGNIVAMEINLQANLWKSFLYSNVALYLPDSFKYTPANVTLPTNTN 500

Query: 19023 TYEYMNGRVTVPGLVDTYVNIGARWSPDVMDNINPFNHHRNAGLRYRSMLLGNGRFVPFH 19202
             TYEYMNGRV  P LVD YVNIGARWS D MDN+NPFNHHRNAGLRYRSMLLGNGR+VPFH
Sbjct: 501   TYEYMNGRVVAPSLVDAYVNIGARWSLDPMDNVNPFNHHRNAGLRYRSMLLGNGRYVPFH 560

Query: 19203 IQVPQKFFAIKNLLLLPGSYTYEWNFRKDVNMILQSTLGNDLRVDGASIRFDNIALYANF 19382
             IQVPQKFFAIKNLLLLPGSYTYEWNFRKDVNMILQS+LGNDLRVDGAS+RFD++ LYA F
Sbjct: 561   IQVPQKFFAIKNLLLLPGSYTYEWNFRKDVNMILQSSLGNDLRVDGASVRFDSVNLYATF 620

Query: 19383 FPMAHNTASTLEAMLRNDTNDQSFNDYLCAANMLYPIPANATSVPISIPSRNWAAFRGWS 19562
             FPMAHNTASTLEAMLRNDTNDQSFNDYL AANMLYPIPA AT+VPISIPSRNWAAFRGWS
Sbjct: 621   FPMAHNTASTLEAMLRNDTNDQSFNDYLSAANMLYPIPAKATNVPISIPSRNWAAFRGWS 680

Query: 19563 FTRLKTKETPSLGSGFDPYFVYSGTIPYLDGTFYLNHTFKKVSIMFDSSVSWPGNDRLLT 19742
             FTRLKTKETPSLGSGFDPYFVYSG+IPYLDGTFYLNHTFKKVSIMFDSSVSWPGNDRLLT
Sbjct: 681   FTRLKTKETPSLGSGFDPYFVYSGSIPYLDGTFYLNHTFKKVSIMFDSSVSWPGNDRLLT 740

Query: 19743 PNEFEIKRSVDGEGYNVAQCNMTKDWFLVQMLSHYNIGYQGFYVPESYKDRMYSFFRNFQ 19922
             PNEFEIKRSVDGEGYNVAQCNMTKDWFL+QMLSHYNIGYQGF+VPE YKDRMYSFFRNFQ
Sbjct: 741   PNEFEIKRSVDGEGYNVAQCNMTKDWFLIQMLSHYNIGYQGFHVPEGYKDRMYSFFRNFQ 800

Query: 19923 PMSRQVVDTTEYKEYKKVTVEFQHNNSGFVGYLGPTMREGQAYPANYPYPLIGKTAVQSV 20102
             PMSRQVVD   YK+YK V + FQHNNSGF GYL PTMR+GQ YPAN+PYPLIG+TAV SV
Sbjct: 801   PMSRQVVDEINYKDYKAVALPFQHNNSGFTGYLAPTMRQGQPYPANFPYPLIGETAVPSV 860

Query: 20103 TQKKFLCDRVMWRIPFSSNFMSMGALTDLGQNMLYANSAHALDMTFEVDPMEEPTLLYVL 20282
             TQKKFLCDRVMWRIPFSSNFMSMGALTDLGQNMLYANSAHALDMTFEVDPM+EPTLLY+L
Sbjct: 861   TQKKFLCDRVMWRIPFSSNFMSMGALTDLGQNMLYANSAHALDMTFEVDPMDEPTLLYLL 920

Query: 20283 FEVFDVVRIHQPHRGVIEAVYLRTPFSAGNATT 20381
             FEVFDVVR+HQPHRGVIEAVYLRTPFSAGNATT
Sbjct: 921   FEVFDVVRVHQPHRGVIEAVYLRTPFSAGNATT 953


========================================================================================================================

gene_id            %id    %sim   %cov   %t5   %gap  %t3   start..stop      pep sz ref sz ref id            definition
47.1               40.1   59.6   100.0  0.0   0.0   0.0   560..973         168    191    ACI47086.1        E1A-2 | E1A 21 kDa protein
                                                          1453..1545                                       
                    invalid splicing for intron  at 974..1452

CLUSTAL 2.1 multiple sequence alignment


predicted       MRHIICHGGVITEEMAASLLDQLIEEVLADNLPPPSHFEP-PTLHELYDLDVTAPED-PN
reference       MRHLRLLSSTVPINMAALLLEDYVSTVLEDELHP-SPFELGPTLQDLYDLEVDAHDDDPN
                ***:   ...:. :*** **:: :. ** *:* * * **  ***::****:* * :* **

predicted       EEAVSQIFPESVML-------AVQEGIDLFTFPPAPGSPEPPHLS-RQPEQ--P---EQR
reference       EEAVNLIFPESLILQADIASEAVPTPLHTPTLSPIPELEEEDELDLRCYEEGFPPSDSED
                ****. *****::*       **   :.  *:.* *   *  .*. *  *:  *   .: 

predicted       ALGPVSMPNLVPEVIDLTC--HEAGFPPSDDED-----EEGGRRQAVECIEDLLNESG--
reference       EQGPVSEDESSPSEENHPCPPELSGETPLQVHKPTPVRPSGERRAAVEKIEDLLHDMGGD
                  ****  :  *.  : .*  . :* .* : ..      .* ** *** *****:: *  

predicted       QPLDLSCKRPRP
reference       EPLDLSLKRPRN
                :***** ****

>47.1	560	1545
tttccgcgttccgggtcaaagttggcgttttattattatagtcagctgacgcgcagtgta
tttatacccggtgagttcctcaagaggccactcttgagtgccagcgagtagagttttctc
ctccgagccgctccgacaccgggactgaaaATGAGACATATTATCTGCCACGGAGGTGTT
ATTACCGAAGAAATGGCCGCCAGTCTTTTGGACCAGCTGATCGAAGAGGTACTGGCTGAT
AATCTTCCACCTCCTAGCCATTTTGAACCACCTACCCTTCACGAACTGTATGATTTAGAC
GTGACGGCCCCCGAAGATCCCAACGAGGAGGCGGTTTCGCAGATTTTTCCCGAGTCTGTA
ATGTTGGCGGTGCAGGAAGGGATTGACTTATTCACTTTTCCGCCGGCGCCCGGTTCTCCG
GAGCCGCCTCACCTTTCCCGGCAGCCCGAGCAGCCGGAGCAGAGAGCCTTGGGTCCGGTT
TCTATGCCAAACCTTGTGCCGGAGGTGATCGATCTTACCTGCCACGAGGCTGGCTTTCCA
CCCAGTGACGACGAGGATGAAGAGggtgaggagtttgtgttagattatgtggagcacccc
gggcacggttgcaggtcttgtcattatcaccggaggaatacgggggacccagatattatg
tgttcgctttgctatatgaggacctgtggcatgtttgtctacagtaagtgaaaattatgg
gcagtgggtgatagagtggtgggtttggtgtggtaatttttttttttaatttttacagtt
ttgtggtttaaagaattttgtattgtgattttttaaaaggtcctgtgtctgaacctgagc
ctgagcccgagccagaaccggagcctgcaagacctacccggcgtcctaaattggtgcctg
ctatcctgagacgcccgacatcacctgtgtctagagaatgcaatagtagtacggatagct
gtgactccggtccttctaacacacctcctgagatacacccggtggtcccgctgtgcccca
ttaaaccagttgccgtgagagttGGTGGGCGTCGCCAGGCTGTGGAATGTATCGAGGACT
TGCTTAACGAGTCTGGGCAACCTTTGGACTTGAGCTGTAAACGCCCCAGGCCATAAggtg
taaacctgtgattgcgtgtgtggttaacgcctttgtttgctgaatgagttgatgtaagtt
taataaagggtgagataatgtttaacttgcatggcgtgttaaatggggcggggcttaaag
ggtatataatgcgccgtgggctaatc

Length = 191

Score =  49.2 bits (101), Expect(6) = 7e-31
Identities = 24/60 (40%), Positives = 31/60 (51%)
Frame = +2

Query: 560  MRHIICHGGVITEEMAASLLDQLIEEVLADNLPPPSHFEPPTLHELYDLDVTAPEDPNEE 739
            MRH+      +   MAA LL+  +  VL D L P      PTL +LYDL+V A +D   E
Sbjct: 1    MRHLRLLSSTVPINMAALLLEDYVSTVLEDELHPSPFELGPTLQDLYDLEVDAHDDDPNE 60

Score =  35.0 bits (70), Expect(6) = 7e-31
Identities = 13/18 (72%), Positives = 17/18 (94%)
Frame = +2

Query: 722  EDPNEEAVSQIFPESVML 775
            +DPNEEAV+ IFPES++L
Sbjct: 56   DDPNEEAVNLIFPESLIL 73

Score =  42.3 bits (86), Expect(6) = 7e-31
Identities = 14/20 (70%), Positives = 17/20 (85%)
Frame = +2

Query: 917  IDLTCHEAGFPPSDDEDEEG 976
            +DL C+E GFPPSD EDE+G
Sbjct: 103  LDLRCYEEGFPPSDSEDEQG 122

Score =  26.3 bits (51), Expect(6) = 7e-31
Identities = 10/20 (50%), Positives = 11/20 (55%)
Frame = +1

Query: 1225 KGPVSEPEPEPEPEPEPARP 1284
            +GPVSE E  P  E  P  P
Sbjct: 121  QGPVSEDESSPSEENHPCPP 140

Score =  27.2 bits (53), Expect(6) = 7e-31
Identities = 12/26 (46%), Positives = 14/26 (53%)
Frame = +1

Query: 1393 PPEIHPVVPLCPIKPVAVRVGGRRQA 1470
            PPE+    PL   KP  VR  G R+A
Sbjct: 139  PPELSGETPLQVHKPTPVRPSGERRA 164

Score =  29.9 bits (59), Expect(6) = 7e-31
Identities = 15/30 (50%), Positives = 17/30 (56%)
Frame = +1

Query: 1453 GGRRQAVECIEDLLNESGQPLDLSCKRPRP 1542
            G RR AVE IEDLL++ G    L     RP
Sbjct: 160  GERRAAVEKIEDLLHDMGGDEPLDLSLKRP 189


========================================================================================================================

gene_id            %id    %sim   %cov   %t5   %gap  %t3   start..stop      pep sz ref sz ref id            definition
47.18              77.2   90.0   99.0   1.0   0.0   0.0   18830..21739     969    945    ACI04185-T5       L3-2 | hexon
                    could not find valid start codon

CLUSTAL 2.1 multiple sequence alignment


predicted       ---------KMATPSMMPQWSYMHISGQDASEYLSPGLVQFARATETYFSLNNKFRNPTV
reference       MCLTARERAKMATPSMMPQWAYMHIAGQDASEYLSPGLVQFARATDTYFSLGNKFRNPTV
                         ***********:****:*******************:*****.********

predicted       APTHDVTTDRSQRLTLRFIPVDREDTAYSYKARFTLAVGDNRVLDMASTYFDIRGVLDRG
reference       APTHDVTTDRSQRLTLRFVPVDREDTTYSYKARFTLAVGDNRVLDMASTYFDIRGVLDRG
                ******************:*******:*********************************

predicted       PTFKPYSGTAYNALAPKGAPNSCEWEQTEDSGRAVAEDEEEEDEDEEEEEEEQNARDQAT
reference       PSFKPYSGTAYNSLAPKGAPNSSQWAQKK-TG-----------------EDNQ-------
                *:**********:*********.:* *.: :*                 *::*       

predicted       KKTHVYAQAPLSGETITKSGLQIGSDNAETQAKPVYADPSYQPEPQIGESQWNEADANAA
reference       TETRTFGVAAMGGILIDKNGLQIGTDETKPDNKEIYADKTFQPEPQKGEENWQDGDV-FY
                .:*:.:. *.:.*  * *.*****:*:::.: * :*** ::***** **.:*::.*.   

predicted       GGRVLKKTTPMKPCYGSYARPTNPFGGQSVLVPDEKGVPLPK--VDLQFFSNTTSLNDRQ
reference       GGRTIKKETKMKPCYGSFARPTNEKGGQAKFKTNAEGQPTEELDIDLNFFDINGGAGD--
                ***.:** * *******:*****  ***: : .: :* *  :  :**:**. . . .*  

predicted       GNATKPKVVLYSEDVNMETPDTHLSYKPGKGDENSKAMLGQQSMPNRPNYIAFRDNFIGL
reference       -NEFNPDMVMYAENMNLETPDTHVVYKPGTSDDSSEANLAQQSMPNRPNYIGFRDNFVGL
                 *  :*.:*:*:*::*:******: ****..*:.*:* *.***********.*****:**

predicted       MYYNSTGNMGVLAGQASQLNAVVDLQDRNTELSYQLLLDSIGDRTRYFSMWNQAVDSYDP
reference       MYYNSTGNMGVLAGQASQLNAVVDLQDRNTELSYQLLLDSLGDRTRYFSMWNSAVDSYDP
                ****************************************:***********.*******

predicted       DVRIIENHGTEDELPNYCFPLGGIGVTDTYQAIKANGNGSGDNGDTTWTKDETFATRNEI
reference       DVRIIENHGVEDELPNYCFPLDGTGTNSTYQGVKET---AAQNG---WEKDPNVAAQNQI
                *********.***********.* *...***.:* .   :.:**   * ** ..*::*:*

predicted       GVGNNFAMEINLNANLWRNFLYSNIALYLPDKLKYNPTNVEISDNPNTYDYMNKRVVAPG
reference       CKGNIYAMEINLQANLWKSFLYSNVALYLPDSYKYTPANVTLPANTNTYEYMNGRVVAPS
                  ** :******:****:.*****:******. **.*:** :. *.***:*** *****.

predicted       LVDCYINLGARWSLDYMDNVNPFNHHRNAGLRYRSMLLGNGRYVPFHIQVPQKFFAIKNL
reference       LVDAYINIGARWSLDPMDNVNPFNHHRNAGLRYRSMLLGNGRYVPFHIQVPQKFFAIKNL
                ***.***:******* ********************************************

predicted       LLLPGSYTYEWNFRKDVNMVLQSSLGNDLRVDGASIKFDSICLYATFFPMAHNTASTLEA
reference       LLLPGSYTYEWNFRKDVNMILQSSLGNDLRVDGASVRFDSVNLYATFFPMAHNTASTLEA
                *******************:***************::***: ******************

predicted       MLRNDTNDQSFNDYLSAANMLYPIPANATNVPISIPSRNWAAFRGWAFTRLKTKETPSLG
reference       MLRNDTNDQSFNDYLSAANMLYPIPAKATNVPISIPSRNWAAFRGWSFTRLKTKETPSLG
                **************************:*******************:*************

predicted       SGYDPYYTYSGSIPYLDGTFYLNHTFKKVAITFDSSVSWPGNDRLLTPNEFEIKRSVDGE
reference       SGFDPYFVYSGSIPYLDGTFYLNHTFKKVSIMFDSSVSWPGNDRLLTPNEFEIKRSVDGE
                **:***:.*********************:* ****************************

predicted       GYNVAQCNMTKDWFLVQMLANYNIGYQGFYIPESYKDRMYSFFRNFQPMSRQVVDDTKYK
reference       GYNVAQCNMTKDWFLVQMLSHYNIGYQGFHVPEGYKDRMYSFFRNFQPMSRQVVDEINYK
                *******************::********::**.*********************: :**

predicted       EYQQVGILHQHNNSGFVGYLAPTMREGQAYPANVPYPLIGKTAVDSITQKKFLCDRTLWR
reference       DYKAVTLPFQHNNSGFTGYLAPTMRQGQPYPANFPYPLIGSTAVPSVTQKKFLCDRVMWR
                :*: * : .*******.********:**.****.******.*** *:*********.:**

predicted       IPFSSNFMSMGALTDLGQNLLYANSAHALDMTFEVDPMDEPTLLYVLFEVFDVVRVHQPH
reference       IPFSSNFMSMGALTDLGQNMLYANSAHALDMTFEVDPMDEPTLLYLLFEVFDVVRVHQPH
                *******************:*************************:**************

predicted       RGVIETVYLRTPFSAGNATT
reference       RGVIEAVYLRTPFSAGNATT
                *****:**************

>47.20	18830	21739
tggcaaagcacactgaacagcatcgtgggtctgggggtgcaatccctgaagcgccgacga
tgcttctaaatagctaacgtgtcgtatgtgtcatgtatgcgtccatgtcgccgccagagg
agctgctgagccgccgtgcgcccgctttccAAGATGGCTACCCCTTCGATGATGCCGCAG
TGGTCTTACATGCACATCTCGGGCCAGGACGCCTCGGAGTACCTGAGCCCCGGGCTGGTG
CAGTTTGCCCGCGCCACCGAGACGTACTTCAGCCTGAATAACAAGTTTAGAAACCCCACG
GTGGCACCTACGCACGACGTAACCACAGACCGGTCCCAGCGTTTGACGCTGCGGTTCATC
CCTGTGGACCGCGAGGATACCGCGTACTCGTACAAAGCGCGGTTCACCCTGGCTGTGGGT
GACAACCGTGTGCTTGATATGGCTTCCACGTACTTTGACATCCGCGGCGTGCTGGACAGG
GGGCCTACTTTTAAGCCCTACTCCGGCACTGCCTACAACGCTCTAGCTCCCAAGGGCGCT
CCTAACTCCTGTGAGTGGGAACAAACCGAAGATAGCGGCCGGGCAGTTGCCGAGGATGAA
GAAGAGGAAGATGAAGATGAAGAAGAGGAAGAAGAAGAGCAAAACGCTCGAGATCAGGCT
ACTAAGAAAACACATGTCTATGCCCAGGCTCCTTTGTCTGGAGAAACAATTACAAAAAGC
GGGCTACAAATAGGATCAGACAATGCAGAAACACAAGCTAAACCTGTATACGCAGATCCT
TCCTATCAACCAGAACCTCAAATTGGCGAATCTCAGTGGAACGAAGCTGATGCTAATGCG
GCAGGAGGGAGAGTGCTTAAAAAAACAACTCCCATGAAACCATGCTATGGATCTTATGCC
AGGCCTACAAATCCTTTTGGTGGTCAATCCGTTCTGGTTCCGGATGAAAAAGGGGTGCCT
CTTCCAAAGGTTGACTTGCAATTCTTCTCAAATACTACCTCTTTGAACGACCGGCAAGGC
AATGCTACTAAACCAAAAGTGGTTTTGTACAGTGAAGATGTAAATATGGAAACCCCAGAC
ACACATCTGTCTTACAAACCTGGAAAAGGTGATGAAAATTCTAAAGCTATGTTGGGTCAA
CAATCTATGCCAAACAGACCCAATTACATTGCTTTCAGGGACAATTTTATTGGCCTAATG
TATTATAACAGCACTGGCAACATGGGTGTTCTTGCTGGTCAGGCATCGCAGCTAAATGCC
GTGGTAGATTTGCAAGACAGAAACACAGAGCTGTCCTATCAACTCTTGCTTGATTCCATA
GGTGATAGAACCAGATATTTTTCTATGTGGAATCAGGCTGTAGACAGCTATGATCCAGAT
GTTAGAATCATTGAAAACCATGGAACTGAGGATGAATTGCCAAATTATTGTTTTCCTCTT
GGGGGTATTGGGGTAACTGACACCTATCAAGCTATTAAGGCTAATGGCAATGGCTCAGGC
GATAATGGAGATACTACATGGACAAAAGATGAAACTTTTGCAACACGTAATGAAATAGGA
GTGGGTAACAACTTTGCCATGGAAATTAACCTAAATGCCAACCTATGGAGAAATTTCCTT
TATTCCAATATTGCGCTGTACCTGCCAGACAAGCTAAAATACAACCCCACCAATGTGGAA
ATATCTGACAACCCCAACACCTACGACTACATGAACAAGCGTGTGGTGGCTCCCGGGCTT
GTAGACTGCTACATTAACCTTGGGGCGCGCTGGTCTCTGGACTACATGGACAACGTTAAT
CCCTTTAACCACCACCGCAATGCGGGCCTCCGTTATCGCTCCATGTTGTTGGGAAACGGC
CGCTACGTGCCCTTTCACATTCAGGTGCCCCAAAAGTTTTTTGCCATTAAAAACCTCCTC
CTCCTGCCAGGCTCATATACATATGAATGGAACTTCAGGAAGGATGTTAACATGGTTCTG
CAGAGCTCTCTGGGAAACGATCTTAGAGTTGACGGGGCTAGCATTAAGTTTGACAGCATT
TGTCTTTACGCCACCTTCTTCCCCATGGCCCACAACACGGCCTCCACGCTGGAAGCCATG
CTCAGAAATGACACCAACGACCAGTCCTTTAATGACTACCTTTCCGCCGCCAACATGCTA
TACCCCATACCCGCCAACGCCACCAACGTGCCCATCTCCATCCCATCGCGCAACTGGGCA
GCATTTCGCGGTTGGGCCTTCACACGCTTGAAGACAAAGGAAACCCCTTCCCTGGGATCA
GGCTACGACCCTTACTACACCTACTCTGGCTCCATACCATACCTTGACGGAACCTTCTAT
CTTAATCACACCTTTAAGAAGGTGGCCATTACCTTTGACTCTTCTGTTAGCTGGCCGGGC
AACGACCGCCTGCTTACTCCCAATGAGTTTGAGATTAAACGCTCAGTTGACGGGGAGGGC
TACAACGTAGCTCAGTGCAACATGACCAAGGACTGGTTCCTGGTGCAGATGTTGGCCAAC
TACAATATTGGCTACCAGGGCTTCTACATTCCAGAAAGCTACAAGGACCGCATGTACTCG
TTCTTCAGAAACTTCCAGCCCATGAGCCGGCAAGTGGTTGACGATACTAAATACAAGGAG
TATCAGCAGGTTGGAATTCTTCACCAGCATAACAACTCAGGATTCGTAGGCTACCTCGCT
CCCACCATGCGCGAGGGACAGGCTTACCCCGCCAACGTGCCCTACCCACTAATAGGCAAA
ACCGCGGTTGACAGTATTACCCAGAAAAAGTTTCTTTGCGATCGCACCCTTTGGCGCATC
CCATTCTCCAGTAACTTTATGTCCATGGGCGCACTCACAGACCTGGGCCAAAACCTTCTC
TACGCCAACTCCGCCCACGCGCTAGACATGACTTTTGAGGTGGATCCCATGGACGAGCCC
ACCCTTCTTTATGTTTTGTTTGAAGTCTTTGACGTGGTCCGTGTGCACCAGCCGCACCGC
GGCGTCATCGAGACCGTGTACCTGCGCACGCCCTTCTCGGCCGGCAACGCCACAACATAA
aagaagcaagcaacatcaacaacagctgccgccatgggctccagtgagcaggaactgaaa
gccattgtcaaagatcttggttgtgggccatattttttgggcacctatgacaagcgcttt
ccaggctttgtttctccacacaagctcgcc

Length = 945

Score =   319 bits (691), Expect(5) = 0.0
Identities = 128/142 (90%), Positives = 136/142 (95%)
Frame = +2

Query: 18818 RPLSKMATPSMMPQWSYMHISGQDASEYLSPGLVQFARATETYFSLNNKFRNPTVAPTHD 18997
             R  +KMATPSMMPQW+YMHI+GQDASEYLSPGLVQFARAT+TYFSL NKFRNPTVAPTHD
Sbjct: 6     RERAKMATPSMMPQWAYMHIAGQDASEYLSPGLVQFARATDTYFSLGNKFRNPTVAPTHD 65

Query: 18998 VTTDRSQRLTLRFIPVDREDTAYSYKARFTLAVGDNRVLDMASTYFDIRGVLDRGPTFKP 19177
             VTTDRSQRLTLRF+PVDREDT YSYKARFTLAVGDNRVLDMASTYFDIRGVLDRGP+FKP
Sbjct: 66    VTTDRSQRLTLRFVPVDREDTTYSYKARFTLAVGDNRVLDMASTYFDIRGVLDRGPSFKP 125

Query: 19178 YSGTAYNALAPKGAPNSCEWEQ 19243
             YSGTAYN+LAPKGAPNS +W Q
Sbjct: 126   YSGTAYNSLAPKGAPNSSQWAQ 147

Score =  69.8 bits (146), Expect(5) = 0.0
Identities = 27/67 (40%), Positives = 39/67 (58%)
Frame = +2

Query: 19346 KTHVYAQAPLSGETITKSGLQIGSDNAETQAKPVYADPSYQPEPQIGESQWNEADANAAG 19525
             +T  +  A + G  I K+GLQIG+D  +   K +YAD ++QPEPQ GE  W + D    G
Sbjct: 157   ETRTFGVAAMGGILIDKNGLQIGTDETKPDNKEIYADKTFQPEPQKGEENWQDGDVFYGG 216

Query: 19526 GRVLKKT 19546
               + K+T
Sbjct: 217   RTIKKET 223

Score =  64.3 bits (134), Expect(5) = 0.0
Identities = 24/45 (53%), Positives = 32/45 (71%)
Frame = +2

Query: 19523 GGRVLKKTTPMKPCYGSYARPTNPFGGQSVLVPDEKGVPLPKVDL 19657
             GGR +KK T MKPCYGS+ARPTN  GGQ+    + +G P  ++D+
Sbjct: 215   GGRTIKKETKMKPCYGSFARPTNEKGGQAKFKTNAEGQPTEELDI 259

Score =   313 bits (677), Expect(5) = 0.0
Identities = 123/160 (76%), Positives = 137/160 (85%)
Frame = +2

Query: 19700 NATKPKVVLYSEDVNMETPDTHLSYKPGKGDENSKAMLGQQSMPNRPNYIAFRDNFIGLM 19879
             N   P +V+Y+E++N+ETPDTH+ YKPG  D++S+A L QQSMPNRPNYI FRDNF+GLM
Sbjct: 273   NEFNPDMVMYAENMNLETPDTHVVYKPGTSDDSSEANLAQQSMPNRPNYIGFRDNFVGLM 332

Query: 19880 YYNSTGNMGVLAGQASQLNAVVDLQDRNTELSYQLLLDSIGDRTRYFSMWNQAVDSYDPD 20059
             YYNSTGNMGVLAGQASQLNAVVDLQDRNTELSYQLLLDS+GDRTRYFSMWN AVDSYDPD
Sbjct: 333   YYNSTGNMGVLAGQASQLNAVVDLQDRNTELSYQLLLDSLGDRTRYFSMWNSAVDSYDPD 392

Query: 20060 VRIIENHGTEDELPNYCFPLGGIGVTDTYQAIKANGNGSG 20179
             VRIIENHG EDELPNYCFPL G G   TYQ +K     +G
Sbjct: 393   VRIIENHGVEDELPNYCFPLDGTGTNSTYQGVKETAAQNG 432

Score =  1115 bits (2429), Expect(5) = 0.0
Identities = 444/513 (86%), Positives = 474/513 (92%)
Frame = +2

Query: 20198 WTKDETFATRNEIGVGNNFAMEINLNANLWRNFLYSNIALYLPDKLKYNPTNVEISDNPN 20377
             W KD   A +N+I  GN +AMEINL ANLW++FLYSN+ALYLPD  KY P NV +  N N
Sbjct: 433   WEKDPNVAAQNQICKGNIYAMEINLQANLWKSFLYSNVALYLPDSYKYTPANVTLPANTN 492

Query: 20378 TYDYMNKRVVAPGLVDCYINLGARWSLDYMDNVNPFNHHRNAGLRYRSMLLGNGRYVPFH 20557
             TY+YMN RVVAP LVD YIN+GARWSLD MDNVNPFNHHRNAGLRYRSMLLGNGRYVPFH
Sbjct: 493   TYEYMNGRVVAPSLVDAYINIGARWSLDPMDNVNPFNHHRNAGLRYRSMLLGNGRYVPFH 552

Query: 20558 IQVPQKFFAIKNLLLLPGSYTYEWNFRKDVNMVLQSSLGNDLRVDGASIKFDSICLYATF 20737
             IQVPQKFFAIKNLLLLPGSYTYEWNFRKDVNM+LQSSLGNDLRVDGAS++FDS+ LYATF
Sbjct: 553   IQVPQKFFAIKNLLLLPGSYTYEWNFRKDVNMILQSSLGNDLRVDGASVRFDSVNLYATF 612

Query: 20738 FPMAHNTASTLEAMLRNDTNDQSFNDYLSAANMLYPIPANATNVPISIPSRNWAAFRGWA 20917
             FPMAHNTASTLEAMLRNDTNDQSFNDYLSAANMLYPIPA ATNVPISIPSRNWAAFRGW+
Sbjct: 613   FPMAHNTASTLEAMLRNDTNDQSFNDYLSAANMLYPIPAKATNVPISIPSRNWAAFRGWS 672

Query: 20918 FTRLKTKETPSLGSGYDPYYTYSGSIPYLDGTFYLNHTFKKVAITFDSSVSWPGNDRLLT 21097
             FTRLKTKETPSLGSG+DPY+ YSGSIPYLDGTFYLNHTFKKV+I FDSSVSWPGNDRLLT
Sbjct: 673   FTRLKTKETPSLGSGFDPYFVYSGSIPYLDGTFYLNHTFKKVSIMFDSSVSWPGNDRLLT 732

Query: 21098 PNEFEIKRSVDGEGYNVAQCNMTKDWFLVQMLANYNIGYQGFYIPESYKDRMYSFFRNFQ 21277
             PNEFEIKRSVDGEGYNVAQCNMTKDWFLVQML++YNIGYQGF++PE YKDRMYSFFRNFQ
Sbjct: 733   PNEFEIKRSVDGEGYNVAQCNMTKDWFLVQMLSHYNIGYQGFHVPEGYKDRMYSFFRNFQ 792

Query: 21278 PMSRQVVDDTKYKEYQQVGILHQHNNSGFVGYLAPTMREGQAYPANVPYPLIGKTAVDSI 21457
             PMSRQVVD+  YK+Y+ V +  QHNNSGF GYLAPTMR+GQ YPAN PYPLIG TAV S+
Sbjct: 793   PMSRQVVDEINYKDYKAVTLPFQHNNSGFTGYLAPTMRQGQPYPANFPYPLIGSTAVPSV 852

Query: 21458 TQKKFLCDRTLWRIPFSSNFMSMGALTDLGQNLLYANSAHALDMTFEVDPMDEPTLLYVL 21637
             TQKKFLCDR +WRIPFSSNFMSMGALTDLGQN+LYANSAHALDMTFEVDPMDEPTLLY+L
Sbjct: 853   TQKKFLCDRVMWRIPFSSNFMSMGALTDLGQNMLYANSAHALDMTFEVDPMDEPTLLYLL 912

Query: 21638 FEVFDVVRVHQPHRGVIETVYLRTPFSAGNATT 21736
             FEVFDVVRVHQPHRGVIE VYLRTPFSAGNATT
Sbjct: 913   FEVFDVVRVHQPHRGVIEAVYLRTPFSAGNATT 945


========================================================================================================================

gene_id            %id    %sim   %cov   %t5   %gap  %t3   start..stop      pep sz ref sz ref id            definition
47.21              88.0   97.9   48.0   52.0  0.0   0.0   <26871..27122    83     173    YP_001974455.1    L4-3 | putative splicing factor, C-terminal
                    missing exon 1

CLUSTAL 2.1 multiple sequence alignment


predicted       ------------------------------------------------------------
reference       MPRKKQEPLVEEMEEEWDSQAEEDEWEEETEEEELEEVEEEQATEQPVAAPSAPAAPAVT
                                                                            

predicted       ------------------------------GGALRLAPNEPVSTRELRNRIFPTLYAIFQ
reference       DTTSAAPAKPPRRWDRVKGDAKKKQVREVAGGGLRIAANEPLTTRELRNRIFPTLYAIFQ
                                              **.**:*.***::*****************

predicted       QSRGQEQELKIKNRSLRSLTRSCLYHKSEDQLRRTLEDAEALFSKYCALTLKD
reference       QSRGQQQELKVKNRSLRSLTRSCLYHKNEDQLQRTLEDAEALFHKYCALTLKD
                *****:****:****************.****:********** *********

>47.25	26871	27122
tcctgcattactaccgtcatctctacagcccctactgcaccggcggcagcggcagcggca
gcaacagcagcgatcacacagaagcaaaggcgaccggatagcaagactctgacaaagccc
aagaaatccacagcggcggcagcagcaggaGGAGGAGCGCTGCGTCTGGCGCCCAACGAA
CCCGTATCGACCCGCGAGCTTAGAAACAGGATTTTTCCCACTCTGTATGCTATATTTCAA
CAAAGCAGGGGCCAAGAACAAGAGCTGAAAATAAAAAACAGGTCTCTGCGCTCCCTCACC
CGCAGCTGCCTGTATCACAAAAGCGAAGATCAGCTTCGGCGCACGCTGGAAGACGCGGAG
GCTCTCTTCAGCAAATACTGCGCGCTGACTCTTAAGGACTAGtttcgcgccctttctcaa
atttaagcgcgaaaactacgtcatctccagcggccacacccggcgccagcacctgtcgtc
agcgccattatgagcaaggaaattcccacgccctacatgtggagttaccagccacaaatg
ggacttgcggct

Length = 173

Score =  20.3 bits (38), Expect(2) = 5e-50
Identities = 8/15 (53%), Positives = 10/15 (66%)
Frame = +3

Query: 26748 APTAPAAAAAAATAA 26792
             AP+APAA A   T +
Sbjct: 50    APSAPAAPAVTDTTS 64

Score =   179 bits (385), Expect(2) = 5e-50
Identities = 74/92 (80%), Positives = 81/92 (88%)
Frame = +3

Query: 26844 KSTAAAAAGGGALRLAPNEPVSTRELRNRIFPTLYAIFQQSRGQEQELKIKNRSLRSLTR 27023
             K        GG LR+A NEP++TRELRNRIFPTLYAIFQQSRGQ+QELK+KNRSLRSLTR
Sbjct: 82    KKKQVREVAGGGLRIAANEPLTTRELRNRIFPTLYAIFQQSRGQQQELKVKNRSLRSLTR 141

Query: 27024 SCLYHKSEDQLRRTLEDAEALFSKYCALTLKD 27119
             SCLYHK+EDQL+RTLEDAEALF KYCALTLKD
Sbjct: 142   SCLYHKNEDQLQRTLEDAEALFHKYCALTLKD 173


========================================================================================================================

gene_id            %id    %sim   %cov   %t5   %gap  %t3   start..stop      pep sz ref sz ref id            definition
47.25              72.7   92.0   89.8   10.2  0.0   0.0   30981..>30850    44     49     ACL13287.1        U | putative protein U, N-terminal
                    could not find valid start codon

CLUSTAL 2.1 multiple sequence alignment


predicted       -----EEFDIPFKLWRKFAAKRRLRYQSWEEGKEVMLNKLDKDLLTDFK
reference       MKIVDQEFDIPFKVWRKFAARRGLEYQSWEEGTEVLLNNYTKDILSDFK
                     :*******:******:* *.*******.**:**:  **:*:***

>47.29	30981	30850
ggtgaaacaaatggaggggtaagaaagggcacagttggaggcccggtttctgtgtcatat
ggatacacggggttgaaggtgtcttcagacggtctggcgcgtttcatctgcaacaatatg
aagatagtgggtgcggagggacaagaacatGAGGAATTTGACATCCCATTTAAACTTTGG
AGAAAGTTTGCAGCTAAAAGGCGGCTGAGATACCAGAGTTGGGAGGAAGGAAAGGAGGTG
ATGCTGAATAAGCTGGACAAAGATTTGCTGACTGATTTTAAGtaagtaatttattgtgtg
tttatgttagttgaatggaataagatctctaataccacacatggttttaataagagtgca
gaggtcctctggaccctgataggggaagtgcaggcagccctctgtttctgccgagtgctg
ggtgacggtgat

Length = 49

Score =  86.3 bits (182), Expect = 1e-22
Identities = 32/44 (72%), Positives = 38/44 (86%)
Frame = -1

Query: 30981 EEFDIPFKLWRKFAAKRRLRYQSWEEGKEVMLNKLDKDLLTDFK 30850
             +EFDIPFK+WRKFAA+R L YQSWEEG EV+LN   KD+L+DFK
Sbjct: 6     QEFDIPFKVWRKFAARRGLEYQSWEEGTEVLLNNYTKDILSDFK 49


========================================================================================================================

gene_id            %id    %sim   %cov   %t5   %gap  %t3   start..stop      pep sz ref sz ref id            definition
64.47              98.4   99.8   100.0  0.0   0.0   0.0   34712..34632     125    125    YP_001974474.1    E4-6 | E4 control protein orf1
                                                          34632..34336                                     
                    frameshift in genome at or near position 34632..34632 (-2=>-1)

CLUSTAL 2.1 multiple sequence alignment


predicted       MAESLYAFIDSPGGIAPVQEGASNRYNFFCPESFHIPPHGVVLLHLKVSVLVPTGYQGRF
reference       MAESLYAFIDSPGGIAPVQEGTSNRYTFFCPESFHIPPHGVVLLHLKVSVLVPTGYQGRF
                *********************:****.*********************************

predicted       MALNDYHARDILTQSDVIFAGRRQELTVLLFNHTDRFLYVRKGHPVGTLLLERVIFPSVK
reference       MALNDYHARDILTQSDVIFAGRRQELTVLLFNHTDRFLYVRKGHPVGTLLLERVIFPSVK
                ************************************************************

predicted       IATLV
reference       IATLV
                *****

>64.47	34712	34336
gtgtgttttttttggcggggtttttagacctttggtcattacgtcagtgtaaggtgcctt
taaatagggagctgggtcagtgggtagtcagttgctgctgttggcgcttgtactgctgtg
ctttctgtctactggtaagcgggctaagctATGGCTGAATCTCTGTATGCTTTTATAGAT
AGTCCTGGAGGGATTGCTCCCGTCCAGGAAGGGGCTAGCAATAGATATAATTTTTTTGCC
CTGAATCTTTCCACATTCCTCCGCATGGGGTGGTATTGCTTCACCTAAAAGTGAGTGTGC
TGGTTCCTACTGGATATCAGGGCAGATTTATGGCCTTGAATGACTACCATGCCAGGGACA
TACTAACCCAGTCTGATGTGATTTTTGCCGGAAGAAGACAGGAACTTACTGTGCTGCTTT
TTAATCACACGGACCGATTTTTGTATGTCCGCAAGGGCCACCCAGTGGGTACCCTGCTGC
TGGAGAGAGTGATTTTTCCTTCAGTGAAAATAGCCACCTTAGTTTAGtgcatgctttctg
tttttcagactctcatctctactaaccatgcttcagcgacgcggtgtaagctaccacatt
gtggtccctggggtcctagtgacttatttagaggacttttctattacgcaaatgattaaa
gaaaaactaccacgctt

Length = 125

Score =  67.5 bits (141), Expect(2) = 2e-81
Identities = 27/29 (93%), Positives = 27/29 (93%)
Frame = -2

Query: 34712 MAESLYAFIDSPGGIAPVQEGASNRYNFF 34626
             MAESLYAFIDSPGGIAPVQEG SNRY FF
Sbjct: 1     MAESLYAFIDSPGGIAPVQEGTSNRYTFF 29

------------------------------------------------------------
frameshifted from -2 to -1 between 34865-34393
 34865 CGTGTGTGTTTTTTTTGGCGGGGTTTTTAGACCTTTGGTCATTACGTCAGTGTAAGGTGC 34806 
 34805 CTTTAAATAGGGAGCTGGGTCAGTGGGTAGTCAGTTGCTGCTGTTGGCGCTTGTACTGCT 34746 
 34745 GTGCTTTCTGTCTACTGGTAAGCGGGCTAAGCTATGGCTGAATCTCTGTATGCTTTTATA 34686 
 34685 GATAGTCCTGGAGGGATTGCTCCCGTCCAGGAAGGGGCTAGCAATAGATATAATTTTTTT 34626 
 34625 GCCCTGAATCTTTCCACATTCCTCCGCATGGGGTGGTATTGCTTCACCTAAAAGTGAGTG 34566 
 34565 TGCTGGTTCCTACTGGATATCAGGGCAGATTTATGGCCTTGAATGACTACCATGCCAGGG 34506 
 34505 ACATACTAACCCAGTCTGATGTGATTTTTGCCGGAAGAAGACAGGAACTTACTGTGCTGC 34446 
 34445 TTTTTAATCACACGGACCGATTTTTGTATGTCCGCAAGGGCCACCCAGTGGGT        34393 
 frame -2
 34865  r  v  c  f  f  w  r  g  f  *  t  f  g  h  y  v  s  v  r  c  34806 
 34805  l  *  i  g  s  w  v  s  g  *  s  v  a  a  v  g  a  c  t  a  34746 
 34745  v  l  s  v  y  w  *  a  g  *  a  m -A--E--S--L--Y--A--F--I- 34686  |
 34685 -D--S--P--G--G--I--A--P--V--Q--E--G- a -S--N--R--Y- n -F--F- 34626  |
 34625  a  l  n  l  s  t  f  l  r  m -G- w  y  c  f  t  * -K- *  v  34566 
 34565  c  w  f  l  l  d  i  r  a  d  l  w  p  *  m  t  t  m  p  g  34506 
 34505  t  y  *  p  s  l  m  *  f  l  p  e  e  d  r  n -L- l  c  c  34446 
 34445  f  l  i  t  r  t  d -F- c  m  s  a  r  a  t  q  w           34393 
 frame -3
 34865   v  c  v  f  f  g  g  v  f  r  p -L- v  i  t  s -V- *  g  a 34806 
 34805   f  k  * -G- a  g  s  v  g  s  q -L- l  l  l  a  l  v  l  l 34746 
 34745   c  f  l -S- t  g  k  r -A- k  l  w  l  n -L- c  m -L--L- * 34686 
 34685   i  v  l  e  g  l -L- p  s -R--K--G- l  a  i  d  i  i  f  l 34626  |
 34625   p  *  i  f  p  h  s  s  a  w  g  g  i  a  s  p  k  s  e  c 34566 
 34565   a  g  s  y  w  i  s  g  q  i  y  g  l  e  *  l  p  c  q  g 34506 
 34505   h  t  n  p  v  *  c  d  f  c  r  k  k  t  g  t  y  c  a  a 34446 
 34445   f  *  s  h  g  p  i  f  v  c  p  q  g  p  p  s  g          34393 
 frame -1
 34865    c  v  f  f  l  a  g  f  l  d  l  w  s  l  r  q  c  k  v   34806 
 34805 p  l  n  r  e  l  g  q  w  v  v  s  c  c  c  w  r  l  y  c   34746 
 34745 c  a  f  c  l  l  v  s  g  l  s  y  g  *  i  s  v  c -F- y   34686 
 34685 r  *  s  w  r  d  c  s  r  p  g  r  g  *  q  *  i  * -F--F-- 34626 
 34625 C--P--E--S--F--H--I--P--P--H--G--V--V--L--L--H--L--K--V--S-- 34566  |
 34565 V--L--V--P--T--G--Y--Q--G--R--F--M--A--L--N--D--Y--H--A--R-- 34506  |
 34505 D--I--L--T--Q--S--D--V--I--F--A--G--R--R--Q--E--L--T--V--L-- 34446  |
 34445 L--F--N--H--T--D--R--F--L--Y--V--R--K--G--H--P--V--G-        34393  |

reference sequence 1-107
AESLYAFIDSPGGIAPVQEGTSNRYTFFCPESFHIPPHGVVLLHLKVSVLVPTGYQGRFM
ALNDYHARDILTQSDVIFAGRRQELTVLLFNHTDRFLYVRKGHPVGT
------------------------------------------------------------

Score =   237 bits (511), Expect(2) = 2e-81
Identities = 98/98 (100%), Positives = 98/98 (100%)
Frame = -1

Query: 34632 FFCPESFHIPPHGVVLLHLKVSVLVPTGYQGRFMALNDYHARDILTQSDVIFAGRRQELT 34453
             FFCPESFHIPPHGVVLLHLKVSVLVPTGYQGRFMALNDYHARDILTQSDVIFAGRRQELT
Sbjct: 28    FFCPESFHIPPHGVVLLHLKVSVLVPTGYQGRFMALNDYHARDILTQSDVIFAGRRQELT 87

Query: 34452 VLLFNHTDRFLYVRKGHPVGTLLLERVIFPSVKIATLV 34339
             VLLFNHTDRFLYVRKGHPVGTLLLERVIFPSVKIATLV
Sbjct: 88    VLLFNHTDRFLYVRKGHPVGTLLLERVIFPSVKIATLV 125


========================================================================================================================

gene_id            %id    %sim   %cov   %t5   %gap  %t3   start..stop      pep sz ref sz ref id            definition
gi_51527264.15     83.9   93.1   99.0   1.0   0.0   0.0   18245..21058     937    945    ACI04185-T5       L3-2 | hexon
                    could not find valid start codon

CLUSTAL 2.1 multiple sequence alignment


predicted       ---------KMATPSMLPQWAYMHIAGQDASEYLSPGLVQFARATDTYFSLGNKFRNPTV
reference       MCLTARERAKMATPSMMPQWAYMHIAGQDASEYLSPGLVQFARATDTYFSLGNKFRNPTV
                         *******:*******************************************

predicted       APTHDVTTDRSQRLTLRFVPVDREDNTYSYKVRYTLAVGDNRVLDMASTYFDIRGVLDRG
reference       APTHDVTTDRSQRLTLRFVPVDREDTTYSYKARFTLAVGDNRVLDMASTYFDIRGVLDRG
                *************************.*****.*:**************************

predicted       PSFKPYSGTAYNSLAPKGAPNTCQWK------DSDSKMHTFGAAAMPGVTGKKIEADGLP
reference       PSFKPYSGTAYNSLAPKGAPNSSQWAQKKTGEDNQTETRTFGVAAMGGIL---IDKNGLQ
                *********************:.**       *.::: :***.*** *:    *: :** 

predicted       IRIDSTSGTDTVIYADKTFQPEPQVGNDSWVDTNGAEEKYGGRALKDTTKMKPCYGSFAK
reference       IGTDETKPDNKEIYADKTFQPEPQKGEENWQD---GDVFYGGRTIKKETKMKPCYGSFAR
                *  *.*.  :. ************ *::.* *   .:  ****::*. ***********:

predicted       PTNKEGGQANLKDSEPAATTPNYDIDLAFFDSKTIVAN--YDPDIVMYTENVDLQTPDTH
reference       PTNEKGGQAKFKTNAEGQPTEELDIDLNFFDINGGAGDNEFNPDMVMYAENMNLETPDTH
                ***::****::* .  . .* : **** *** :  ..:  ::**:***:**::*:*****

predicted       IVYKPGTEDTSSESNLGQQAMPNRPNYIGFRDNFIGLMYYNSTGNMGVLAGQASQLNAVV
reference       VVYKPGTSDDSSEANLAQQSMPNRPNYIGFRDNFVGLMYYNSTGNMGVLAGQASQLNAVV
                :******.* ***:**.**:**************:*************************

predicted       DLQDRNTELSYQLLLDSLGDRTRYFSMWNQAVDSYDPDVRIIENHGVEDELPNYCFPLNG
reference       DLQDRNTELSYQLLLDSLGDRTRYFSMWNSAVDSYDPDVRIIENHGVEDELPNYCFPLDG
                *****************************.****************************:*

predicted       VGLTDTYQGVKVKTDAGSEKWDKDDTTVSNANEIHVGNPFAMEINIQANLWRNFLYANVA
reference       TGTNSTYQG--VKETAAQNGWEKD-PNVAAQNQICKGNIYAMEINLQANLWKSFLYSNVA
                .* ..****  **  *..: *:** ..*:  *:*  ** :*****:*****:.***:***

predicted       LYLPDKYKYTPANITLPTNTNTYEYMNGRVVAPSLVDAYINIGARWSLDPMDNVNPFNHH
reference       LYLPDSYKYTPANVTLPANTNTYEYMNGRVVAPSLVDAYINIGARWSLDPMDNVNPFNHH
                *****.*******:***:******************************************

predicted       RNAGLRYRSMLLGNGRYVPFHIQVPQKFFAIKSLLLLPGSYTYEWNFRKDVNMILQSSLG
reference       RNAGLRYRSMLLGNGRYVPFHIQVPQKFFAIKNLLLLPGSYTYEWNFRKDVNMILQSSLG
                ********************************.***************************

predicted       NDLRTDGASITFTSINLYATFFPMAHNTASTLEAMLRNDTNDQSFNDYLSAANMLYPIPA
reference       NDLRVDGASVRFDSVNLYATFFPMAHNTASTLEAMLRNDTNDQSFNDYLSAANMLYPIPA
                ****.****: * *:*********************************************

predicted       NATNVPISIPSRNWAAFRGWSFTRLKTKETPSLGSGFDPYFVYSGSIPYLDGTFYLNHTF
reference       KATNVPISIPSRNWAAFRGWSFTRLKTKETPSLGSGFDPYFVYSGSIPYLDGTFYLNHTF
                :***********************************************************

predicted       KKVSITFDSSVSWPGNDRLLTPNEFEIKRTVDGEGYNVAQCNMTKDWFLVQMLAHYNIGY
reference       KKVSIMFDSSVSWPGNDRLLTPNEFEIKRSVDGEGYNVAQCNMTKDWFLVQMLSHYNIGY
                ***** ***********************:***********************:******

predicted       QGFYVPEGYKDRMYSFFRNFQPMSRQVVDEVNYKDYQAVTLAYQHNNSGFVGYLAPTMRQ
reference       QGFHVPEGYKDRMYSFFRNFQPMSRQVVDEINYKDYKAVTLPFQHNNSGFTGYLAPTMRQ
                ***:**************************:*****:****.:*******.*********

predicted       GQPYPANYPYPLIGKSAVTSVTQKKFICDRVMWRIPFSSNFMSMGALTDLGQNMLYANSA
reference       GQPYPANFPYPLIGSTAVPSVTQKKFLCDRVMWRIPFSSNFMSMGALTDLGQNMLYANSA
                *******:******.:**.*******:*********************************

predicted       HALDMNFEVDPMDESTLLYVVFEVFDVVRVHQPHRGVIEAVYLRTPFSAGNATT
reference       HALDMTFEVDPMDEPTLLYLLFEVFDVVRVHQPHRGVIEAVYLRTPFSAGNATT
                *****.********.****::*********************************

>gi_51527264.20	18245	21058
tcgtgggtctgggagtgcagagtgtgaagcgccgccgctgttattaaaaaacactgtagc
gcttaacttgcttgtctgtgtatatgtgtatgtccgccgccgctgctgtccagaaggagg
agtgaagagaaaggcgcgtcgtcgagttgcAAGATGGCCACCCCATCGATGCTGCCCCAG
TGGGCGTACATGCACATCGCCGGACAGGACGCTTCGGAGTACCTGAGTCCGGGTCTGGTG
CAGTTCGCCCGCGCCACAGACACCTACTTCAGTCTGGGGAACAAGTTTAGGAACCCCACG
GTGGCGCCTACCCACGATGTGACCACCGACCGCAGCCAGCGGCTGACGCTGCGCTTTGTG
CCCGTGGACCGGGAGGACAACACCTACTCGTACAAAGTGCGCTACACGCTGGCCGTGGGC
GACAACCGCGTGCTGGACATGGCCAGCACCTACTTTGACATCCGCGGCGTGCTGGATCGG
GGCCCTAGCTTCAAACCCTACTCCGGCACTGCCTACAACAGCCTGGCTCCCAAGGGAGCG
CCCAACACCTGCCAGTGGAAGGATTCTGACAGCAAAATGCATACCTTTGGGGCAGCTGCC
ATGCCCGGTGTTACTGGGAAAAAGATAGAAGCTGATGGGCTGCCTATTAGAATAGATTCA
ACTTCTGGAACTGACACAGTAATTTATGCTGATAAAACTTTCCAACCAGAACCACAAGTT
GGAAATGACAGTTGGGTTGACACCAATGGTGCAGAGGAAAAATATGGAGGCAGAGCTCTA
AAGGACACTACAAAAATGAAACCCTGTTATGGTTCATTCGCCAAGCCTACCAACAAAGAA
GGTGGTCAGGCTAACTTAAAAGATTCAGAACCCGCCGCCACCACTCCTAACTATGATATA
GACCTGGCTTTCTTTGACAGCAAAACTATTGTTGCTAACTACGATCCAGATATTGTAATG
TACACAGAAAATGTTGACTTGCAGACTCCAGATACTCATATTGTATACAAACCTGGAACA
GAGGACACCAGCTCTGAATCCAATTTGGGTCAGCAGGCCATGCCTAACAGACCCAACTAC
ATTGGCTTCAGAGACAATTTTATCGGGCTCATGTACTACAACAGCACTGGCAATATGGGG
GTGCTGGCCGGTCAGGCCTCTCAGCTGAATGCTGTGGTTGACTTGCAAGACAGAAACACT
GAACTGTCCTACCAGCTCTTGCTTGACTCTCTGGGTGACAGAACCCGGTATTTCAGTATG
TGGAATCAGGCGGTGGACAGCTATGATCCTGATGTGCGCATTATTGAAAACCATGGTGTG
GAGGATGAATTGCCAAACTATTGCTTTCCGTTGAATGGTGTGGGATTGACAGACACTTAC
CAGGGTGTTAAAGTTAAAACAGATGCAGGTTCTGAAAAGTGGGACAAAGATGACACCACA
GTTAGTAATGCTAATGAAATCCATGTAGGCAATCCTTTTGCCATGGAAATCAACATCCAA
GCCAACCTGTGGAGGAACTTCCTCTATGCCAATGTTGCCCTCTATTTGCCTGATAAATAC
AAATACACACCGGCCAACATCACCCTGCCCACCAACACCAACACCTACGAGTACATGAAC
GGCCGGGTGGTGGCGCCCTCGCTGGTGGACGCCTACATTAACATTGGGGCGCGCTGGTCG
CTGGACCCCATGGACAACGTAAATCCCTTCAACCACCACCGCAATGCGGGCTTGCGCTAC
CGCTCCATGCTCCTGGGCAACGGGCGCTACGTGCCATTCCACATCCAGGTGCCCCAGAAA
TTTTTTGCCATTAAGAGCCTCCTGCTCCTGCCCGGGTCCTACACCTACGAGTGGAACTTC
CGCAAGGACGTCAACATGATCCTGCAGAGTTCCCTTGGCAACGACCTGCGCACAGACGGG
GCCTCCATCACCTTCACCAGCATTAACCTCTACGCCACCTTCTTCCCCATGGCGCACAAC
ACCGCCTCCACGCTTGAGGCCATGCTGCGCAACGACACCAATGACCAATCCTTCAACGAC
TACCTCTCGGCGGCCAACATGCTCTATCCCATCCCGGCCAACGCCACCAACGTGCCCATC
TCCATCCCCTCGCGCAACTGGGCCGCCTTTCGCGGCTGGTCCTTCACGCGTCTCAAGACC
AAAGAGACGCCCTCGCTGGGCTCCGGGTTCGACCCCTACTTCGTCTACTCGGGCTCCATC
CCCTACCTCGACGGCACCTTCTACCTCAACCACACCTTCAAGAAGGTCTCCATCACCTTC
GACTCTTCCGTCAGCTGGCCCGGCAACGACCGGCTCCTGACGCCCAACGAGTTCGAAATC
AAGCGCACCGTCGACGGCGAGGGATACAACGTGGCCCAGTGCAACATGACCAAGGACTGG
TTCCTGGTCCAGATGCTGGCCCACTACAACATCGGCTACCAGGGCTTCTACGTGCCCGAG
GGCTACAAGGACCGCATGTACTCCTTCTTCCGCAACTTCCAGCCCATGAGCCGCCAGGTG
GTGGACGAGGTTAACTACAAGGACTACCAGGCCGTCACCCTGGCCTACCAACACAACAAC
TCGGGCTTCGTTGGATACCTCGCGCCCACTATGCGCCAGGGCCAGCCCTACCCCGCCAAC
TACCCCTACCCGCTCATCGGCAAGAGCGCCGTTACCAGCGTCACCCAGAAAAAGTTCATC
TGCGACAGGGTCATGTGGCGCATCCCCTTCTCCAGCAACTTCATGTCCATGGGCGCGCTC
ACCGACCTCGGCCAGAACATGCTCTATGCTAACTCCGCCCACGCGCTAGACATGAATTTC
GAAGTCGACCCCATGGATGAGTCCACCCTTCTCTATGTTGTCTTCGAAGTCTTCGACGTC
GTCCGAGTGCACCAGCCCCACCGCGGCGTCATTGAGGCCGTCTACCTGCGCACCCCCTTC
TCAGCCGGTAACGCCACCACATAAattcttgcttcttgcaagaagccatggccgcgggct
ccggcgagcaggagctcagggccatcatccgcgacctggggtgcgggccctacttcctgg
gcaccttcgataagcgattcccgggattcatggccccgcacaaggtggcctgcg

Length = 945

Score =   323 bits (699), Expect(6) = 0.0
Identities = 131/141 (92%), Positives = 134/141 (95%)
Frame = +2

Query: 18230 ASSSCKMATPSMLPQWAYMHIAGQDASEYLSPGLVQFARATDTYFSLGNKFRNPTVAPTH 18409
             A    KMATPSM+PQWAYMHIAGQDASEYLSPGLVQFARATDTYFSLGNKFRNPTVAPTH
Sbjct: 5     ARERAKMATPSMMPQWAYMHIAGQDASEYLSPGLVQFARATDTYFSLGNKFRNPTVAPTH 64

Query: 18410 DVTTDRSQRLTLRFVPVDREDNTYSYKVRYTLAVGDNRVLDMASTYFDIRGVLDRGPSFK 18589
             DVTTDRSQRLTLRFVPVDRED TYSYK R+TLAVGDNRVLDMASTYFDIRGVLDRGPSFK
Sbjct: 65    DVTTDRSQRLTLRFVPVDREDTTYSYKARFTLAVGDNRVLDMASTYFDIRGVLDRGPSFK 124

Query: 18590 PYSGTAYNSLAPKGAPNTCQW 18652
             PYSGTAYNSLAPKGAPN+ QW
Sbjct: 125   PYSGTAYNSLAPKGAPNSSQW 145

Score =  24.0 bits (46), Expect(6) = 0.0
Identities = 8/18 (44%), Positives = 13/18 (72%)
Frame = +2

Query: 18653 KDSDSKMHTFGAAAMPGV 18706
             +D+ ++  TFG AAM G+
Sbjct: 152   EDNQTETRTFGVAAMGGI 169

Score =  53.8 bits (111), Expect(6) = 0.0
Identities = 22/42 (52%), Positives = 27/42 (64%)
Frame = +2

Query: 18710 GKKIEADGLPIRIDSTSGTDTVIYADKTFQPEPQVGNDSWVD 18835
             G  I+ +GL I  D T   +  IYADKTFQPEPQ G ++W D
Sbjct: 168   GILIDKNGLQIGTDETKPDNKEIYADKTFQPEPQKGEENWQD 209

Score =  83.1 bits (175), Expect(6) = 0.0
Identities = 32/52 (61%), Positives = 37/52 (71%)
Frame = +2

Query: 18857 YGGRALKDTTKMKPCYGSFAKPTNKEGGQANLKDSEPAATTPNYDIDLAFFD 19012
             YGGR +K  TKMKPCYGSFA+PTN++GGQA  K +     T   DIDL FFD
Sbjct: 214   YGGRTIKKETKMKPCYGSFARPTNEKGGQAKFKTNAEGQPTEELDIDLNFFD 265

Score =   335 bits (725), Expect(6) = 0.0
Identities = 131/151 (86%), Positives = 142/151 (94%)
Frame = +2

Query: 19034 YDPDIVMYTENVDLQTPDTHIVYKPGTEDTSSESNLGQQAMPNRPNYIGFRDNFIGLMYY 19213
             ++PD+VMY EN++L+TPDTH+VYKPGT D SSE+NL QQ+MPNRPNYIGFRDNF+GLMYY
Sbjct: 275   FNPDMVMYAENMNLETPDTHVVYKPGTSDDSSEANLAQQSMPNRPNYIGFRDNFVGLMYY 334

Query: 19214 NSTGNMGVLAGQASQLNAVVDLQDRNTELSYQLLLDSLGDRTRYFSMWNQAVDSYDPDVR 19393
             NSTGNMGVLAGQASQLNAVVDLQDRNTELSYQLLLDSLGDRTRYFSMWN AVDSYDPDVR
Sbjct: 335   NSTGNMGVLAGQASQLNAVVDLQDRNTELSYQLLLDSLGDRTRYFSMWNSAVDSYDPDVR 394

Query: 19394 IIENHGVEDELPNYCFPLNGVGLTDTYQGVK 19486
             IIENHGVEDELPNYCFPL+G G   TYQGVK
Sbjct: 395   IIENHGVEDELPNYCFPLDGTGTNSTYQGVK 425

Score =  1169 bits (2547), Expect(6) = 0.0
Identities = 468/510 (91%), Positives = 490/510 (96%)
Frame = +2

Query: 19526 DTTVSNANEIHVGNPFAMEINIQANLWRNFLYANVALYLPDKYKYTPANITLPTNTNTYE 19705
             D  V+  N+I  GN +AMEIN+QANLW++FLY+NVALYLPD YKYTPAN+TLP NTNTYE
Sbjct: 436   DPNVAAQNQICKGNIYAMEINLQANLWKSFLYSNVALYLPDSYKYTPANVTLPANTNTYE 495

Query: 19706 YMNGRVVAPSLVDAYINIGARWSLDPMDNVNPFNHHRNAGLRYRSMLLGNGRYVPFHIQV 19885
             YMNGRVVAPSLVDAYINIGARWSLDPMDNVNPFNHHRNAGLRYRSMLLGNGRYVPFHIQV
Sbjct: 496   YMNGRVVAPSLVDAYINIGARWSLDPMDNVNPFNHHRNAGLRYRSMLLGNGRYVPFHIQV 555

Query: 19886 PQKFFAIKSLLLLPGSYTYEWNFRKDVNMILQSSLGNDLRTDGASITFTSINLYATFFPM 20065
             PQKFFAIK+LLLLPGSYTYEWNFRKDVNMILQSSLGNDLR DGAS+ F S+NLYATFFPM
Sbjct: 556   PQKFFAIKNLLLLPGSYTYEWNFRKDVNMILQSSLGNDLRVDGASVRFDSVNLYATFFPM 615

Query: 20066 AHNTASTLEAMLRNDTNDQSFNDYLSAANMLYPIPANATNVPISIPSRNWAAFRGWSFTR 20245
             AHNTASTLEAMLRNDTNDQSFNDYLSAANMLYPIPA ATNVPISIPSRNWAAFRGWSFTR
Sbjct: 616   AHNTASTLEAMLRNDTNDQSFNDYLSAANMLYPIPAKATNVPISIPSRNWAAFRGWSFTR 675

Query: 20246 LKTKETPSLGSGFDPYFVYSGSIPYLDGTFYLNHTFKKVSITFDSSVSWPGNDRLLTPNE 20425
             LKTKETPSLGSGFDPYFVYSGSIPYLDGTFYLNHTFKKVSI FDSSVSWPGNDRLLTPNE
Sbjct: 676   LKTKETPSLGSGFDPYFVYSGSIPYLDGTFYLNHTFKKVSIMFDSSVSWPGNDRLLTPNE 735

Query: 20426 FEIKRTVDGEGYNVAQCNMTKDWFLVQMLAHYNIGYQGFYVPEGYKDRMYSFFRNFQPMS 20605
             FEIKR+VDGEGYNVAQCNMTKDWFLVQML+HYNIGYQGF+VPEGYKDRMYSFFRNFQPMS
Sbjct: 736   FEIKRSVDGEGYNVAQCNMTKDWFLVQMLSHYNIGYQGFHVPEGYKDRMYSFFRNFQPMS 795

Query: 20606 RQVVDEVNYKDYQAVTLAYQHNNSGFVGYLAPTMRQGQPYPANYPYPLIGKSAVTSVTQK 20785
             RQVVDE+NYKDY+AVTL +QHNNSGF GYLAPTMRQGQPYPAN+PYPLIG +AV SVTQK
Sbjct: 796   RQVVDEINYKDYKAVTLPFQHNNSGFTGYLAPTMRQGQPYPANFPYPLIGSTAVPSVTQK 855

Query: 20786 KFICDRVMWRIPFSSNFMSMGALTDLGQNMLYANSAHALDMNFEVDPMDESTLLYVVFEV 20965
             KF+CDRVMWRIPFSSNFMSMGALTDLGQNMLYANSAHALDM FEVDPMDE TLLY++FEV
Sbjct: 856   KFLCDRVMWRIPFSSNFMSMGALTDLGQNMLYANSAHALDMTFEVDPMDEPTLLYLLFEV 915

Query: 20966 FDVVRVHQPHRGVIEAVYLRTPFSAGNATT 21055
             FDVVRVHQPHRGVIEAVYLRTPFSAGNATT
Sbjct: 916   FDVVRVHQPHRGVIEAVYLRTPFSAGNATT 945


========================================================================================================================

gene_id            %id    %sim   %cov   %t5   %gap  %t3   start..stop      pep sz ref sz ref id            definition
gi_51527264.19     75.3   86.7   100.0  0.0   0.0   0.0   24833..24588     81     81     ACI47084.1        HYP-7 | hypothetical protein
                    stop codons embedded in CDS at 24827..24825, 24614..24612 and 24608..24606

CLUSTAL 2.1 multiple sequence alignment


predicted       MLXLIKSGKPLRSVSLRRSGKMRSARSEAVVRSSNPVHRALRFFCRSLQSSFRFCSSRHC
reference       MLWLMKSGSPPFSVCLRRSGKTISARSEATVRSSKPVHSFLRFLARSLSSSFRFSSSRHC
                ** *:***.*  **.******  ******.****:***  ***:.***.*****.*****

predicted       CHTPMAVCQVWQRXRXTQSRM
reference       CHTPMAACHVWQRKRKTQSRM
                ******.*:**** * *****

>gi_51527264.24	24833	24588
tagttggccaagcgcagcaggtagcagtggctccacagcggcggggggcactcgcggaag
gtcagcggcacgaagtccgagggcagcgcggagcaggtggccggcaggatcccggagcgt
tcgaggatgaaagagcgaaagttttgcaacATGCTTTGACTCATAAAGTCGGGCAAACCG
TTGCGCAGCGTCAGCCTGAGACGCTCGGGGAAAATGAGGTCTGCCAGGTCCGAGGCGGTG
GTGCGCTCGTCGAACCCGGTCCACAGGGCCTTGAGGTTCTTCTGCAGGAGCTTGCAGAGC
TCTTTTAGGTTCTGCTCCTCCAGACACTGCTGCCACACGCCCATGGCTGTCTGCCAGGTG
TGGCAGAGGTAGAGGTAAACGCAGTCGCGGATGTAGtcgcggcgggcctccccgcgcagg
gtggtgtgcagcacgttctgccccaggcggttctcgtgcaagatgcccatgtaggagacc
aggttggtcagctccacgttggagatcttgcaggcctggcgtacgaacccgtgcctgaag
atgtag

Length = 81

Score =   136 bits (292), Expect = 2e-37
Identities = 61/81 (75%), Positives = 62/81 (76%)
Frame = -2

Query: 24833 ML*LIKSGKPLRSVSLRRSGKMRSARSEAVVRSSNPVHRALRFFCRSLQSSFRFCSSRHC 24654
             ML L+KSG P  SV LRRSGK  SARSEA VRSS PVH  LRF  RSL SSFRF SSRHC
Sbjct: 1     MLWLMKSGSPPFSVCLRRSGKTISARSEATVRSSKPVHSFLRFLARSLSSSFRFSSSRHC 60

Query: 24653 CHTPMAVCQVWQR*R*TQSRM 24591
             CHTPMA C VWQR R TQSRM
Sbjct: 61    CHTPMAACHVWQRKRKTQSRM 81


========================================================================================================================

gene_id            %id    %sim   %cov   %t5   %gap  %t3   start..stop      pep sz ref sz ref id            definition
gi_51527264.21     57.2   69.8   100.0  0.0   0.0   0.0   25439..25618     144    173    YP_001974455.1    L4-3 | splicing factor
                                                          25998..26252                                     
                    invalid splicing for intron  at 25619..25997

CLUSTAL 2.1 multiple sequence alignment


predicted       MPRGSSKKLKVELPPVED--LEED-WESSQAEE--EEMED-------------------W
reference       MPRKKQEPLVEEMEEEWDSQAEEDEWEEETEEEELEEVEEEQATEQPVAAPSAPAAPAVT
                *** ..: *  *:    *   *** **..  **  **:*:                    

predicted       DSTQAEDSLQ----DSLEDEEEAEEVEEAAGG-LRIAANEPAQTRELRNRIFPTLYAIFQ
reference       DTTSAAPAKPPRRWDRVKGDAKKKQVREVAGGGLRIAANEPLTTRELRNRIFPTLYAIFQ
                *:*.*  :      * ::.: : ::*.*.*** ********  *****************

predicted       QSRGQEQELKVKNRSLRSLTRSCLYHKSEDQLQRTLEDAEALFNKYCALTLKE
reference       QSRGQQQELKVKNRSLRSLTRSCLYHKNEDQLQRTLEDAEALFHKYCALTLKD
                *****:*********************.***************:********:

>gi_51527264.26	25439	26252
agctgtcggcctgcgtcatcacccagggggcgatcctggcccaattgcaagctatccaga
aatcccgccaagaattcttgctgaaaaagggccgcggggtctaccttgatccccagaccg
gtgaggagcttaaccccggcttcccccaggATGCCCCGAGGAAGCAGCAAGAAGCTGAAA
GTGGAGCTGCCGCCCGTGGAGGATTTGGAGGAAGACTGGGAGAGCAGTCAGGCAGAGGAG
GAGGAGATGGAAGACTGGGACAGCACTCAGGCAGAGGACAGCCTGCAAGACAGTCTGGAA
GACGAGGAGGAGGCAGAGGAGGTGGAAGAAgtagccgccgccgccagaccgtcgtcctcg
gcggagaaagcaagcagcacggataccatctccgctccgggtcggggtcccgctcgaccc
cacagtagatgggacgagaccgggcgattcccgaaccccaccacccagaccggtaagaag
gagcggcagggatacaagtcctggcgggggcacaaaaacgccatcgtctcctgcttgcaa
gcttgcgggggcaacatctcattcacccggcgctacctgctctttcaccgcggggtgaac
ttcccccgcaacatcttgcattactaccgtcacctccacagcccctactacttccaagaa
gaggcagaaaaagacaaaaccagcagctagaaaatccacagcggcggcgGCGGCAGGTGG
ACTGAGGATCGCGGCGAACGAGCCGGCGCAGACCCGGGAACTGAGGAACCGGATCTTTCC
CACCCTCTATGCCATCTTCCAGCAGAGTCGGGGGCAGGAGCAGGAACTGAAAGTCAAGAA
CCGTTCTCTGCGCTCGCTCACCCGCAGTTGTCTGTATCACAAGAGCGAAGACCAACTTCA
GCGCACGCTTGAGGACGCCGAGGCTCTCTTCAACAAGTACTGCGCACTCACTCTTAAAGA
GTAGcccgcgcccgcccacacacggaaaaaggcgggaattacgtcacctgtgcaccccca
cccagcaccgctatgagcaaagaaattcccacgccttacatgtggagctaccagccccag
atgggcctggccgccggcgccgcccaggactact

Length = 173

Score =  50.8 bits (105), Expect(2) = 2e-60
Identities = 23/65 (35%), Positives = 34/65 (52%)
Frame = +2

Query: 25529 EEMEDWDSTQAEDSLQDSLEDEEEAEEVEEVAAAARPSSSAEKASSTDTISAPGRGPARP 25708
             EEME+   +QAE+   +   +EEE EEVEE  A  +P ++    ++          PA+P
Sbjct: 11    EEMEEEWDSQAEEDEWEEETEEEELEEVEEEQATEQPVAAPSAPAAPAVTDTTSAAPAKP 70

Query: 25709 HSRWD 25723
               RWD
Sbjct: 71    PRRWD 75

Score =   187 bits (402), Expect(2) = 2e-60
Identities = 79/93 (84%), Positives = 84/93 (90%)
Frame = +3

Query: 25971 AARKSTAAAAAGGLRIAANEPAQTRELRNRIFPTLYAIFQQSRGQEQELKVKNRSLRSLT 26150
             A +K     A GGLRIAANEP  TRELRNRIFPTLYAIFQQSRGQ+QELKVKNRSLRSLT
Sbjct: 81    AKKKQVREVAGGGLRIAANEPLTTRELRNRIFPTLYAIFQQSRGQQQELKVKNRSLRSLT 140

Query: 26151 RSCLYHKSEDQLQRTLEDAEALFNKYCALTLKE 26249
             RSCLYHK+EDQLQRTLEDAEALF+KYCALTLK+
Sbjct: 141   RSCLYHKNEDQLQRTLEDAEALFHKYCALTLKD 173


========================================================================================================================

gene_id            %id    %sim   %cov   %t5   %gap  %t3   start..stop      pep sz ref sz ref id            definition
gi_9626553.6       76.5   84.4   95.5   4.5   0.0   0.0   5903..6160       85     89     ACI47083.1        HYP-2 | hypothetical protein
                    could not find valid start codon

CLUSTAL 2.1 multiple sequence alignment


predicted       ----TYSFATQRHSGKTVARSSGSNRTCQPRLCSVIRSTLVTTSPRRGSLVQQRRPPLRE
reference       MLSWTYSRATHFHSGKTVVRSSGTILTRQPRLCRVTRSTLVATSPRRGSLVQQRRPPLRE
                    *** **: ******.****:  * ***** * *****:******************

predicted       QSGGKTSSRFSGGGSASMVKMPGSRVRLK
reference       QNGGSTSSRCSSGGSASMVKMPGQSSLSK
                *.**.**** *.***********.    *

>gi_9626553.8	5903	6160
gaatccatttggtcagaaaatacaatttttttgttatcaagtttggtagcaaaggatcca
tagagggcgttggagagcagtttggcaatggaacgcagtgtttggtttttttcgcggtcg
gcacgctccttggcggtgatattaagatgaACGTACTCTTTTGCCACGCAGCGCCACTCG
GGAAAGACAGTGGCGCGCTCGTCGGGAAGCAACCGCACATGCCAGCCCCGGTTGTGCAGT
GTTATAAGGTCCACACTGGTAACTACCTCGCCGCGCAGGGGCTCATTGGTCCAGCAAAGG
CGCCCTCCTTTGCGCGAACAGAGTGGGGGCAAAACATCTAGTAGGTTTTCAGGTGGGGGG
TCGGCGTCGATGGTAAAAATGCCAGGCAGCAGGGTGCGATTGAAATAAtcaatgggggta
ccaacttgcaaaagagcgtgttcccaatctcggaccgctagggcgcgctcgtagggattg
agtgggaagccccacggcatgggatgggtaagtgcagaggcgtacatgccacagatgtca
taaacgtaaagtggttcg

Length = 89

Score =   144 bits (308), Expect = 1e-39
Identities = 64/79 (81%), Positives = 66/79 (83%)
Frame = +2

Query: 5903 TYSFATQRHSGKTVARSSGSNRTCQPRLCSVIRSTLVTTSPRRGSLVQQRRPPLREQSGG 6082
            TYS AT  HSGKTV RSSG+  T QPRLC V RSTLV TSPRRGSLVQQRRPPLREQ+GG
Sbjct: 5    TYSRATHFHSGKTVVRSSGTILTRQPRLCRVTRSTLVATSPRRGSLVQQRRPPLREQNGG 64

Query: 6083 KTSSRFSGGGSASMVKMPG 6139
             TSSR S GGSASMVKMPG
Sbjct: 65   STSSRCSSGGSASMVKMPG 83


========================================================================================================================

gene_id            %id    %sim   %cov   %t5   %gap  %t3   start..stop      pep sz ref sz ref id            definition
gi_9626553.17      80.8   92.3   99.0   1.0   0.0   0.0   17640..20414     924    945    ACI04185-T5       L3-2 | hexon
                    could not find valid start codon

CLUSTAL 2.1 multiple sequence alignment


predicted       ---------KMATPSMMPQWSYMHIAGQDASEYLSPGLVQFARATDTYFSLGNKFRNPTV
reference       MCLTARERAKMATPSMMPQWAYMHIAGQDASEYLSPGLVQFARATDTYFSLGNKFRNPTV
                         ***********:***************************************

predicted       APTHDVTTDRSQRLTLRFVPVDREETAYSYKVRFTLAVGDNRVLDMASTYFDIRGVLDRG
reference       APTHDVTTDRSQRLTLRFVPVDREDTTYSYKARFTLAVGDNRVLDMASTYFDIRGVLDRG
                ************************:*:****.****************************

predicted       PSFKPYSGTAYNSLAPKGAPNPSQWT-------NQNKTNSFGQAPYIGQKITNQGVQVGS
reference       PSFKPYSGTAYNSLAPKGAPNSSQWAQKKTGEDNQTETRTFGVAAMGGILIDKNGLQIGT
                *********************.***:       **.:*.:** *.  *  * ::*:*:*:

predicted       DS---NNRDVFADKTYQPEPQVGQTQWNINPMQNAAGRILKQTTPMQPCYGSYARPTNEK
reference       DETKPDNKEIYADKTFQPEPQKGEENWQDGDVFYG-GRTIKKETKMKPCYGSFARPTNEK
                *.   :*::::****:***** *: :*: . :  . ** :*: * *:*****:*******

predicted       GGQAKLVKNDDNQ-TTTTNVGLNFFTTATETAN--FSPKVVLYSEDVNLEAPDTHLVFKP
reference       GGQAKFKTNAEGQPTEELDIDLNFFDINGGAGDNEFNPDMVMYAENMNLETPDTHVVYKP
                *****: .* :.* *   ::.****     :.:  *.*.:*:*:*::***:****:*:**

predicted       DVNGTSAELLLGQQAAPNRPNYIGFRDNFIGLMYYNSTGNMGVLAGQASQLNAVVDLQDR
reference       GTSDDSSEANLAQQSMPNRPNYIGFRDNFVGLMYYNSTGNMGVLAGQASQLNAVVDLQDR
                .... *:*  *.**: *************:******************************

predicted       NTELSYQLMLDALGDRSRYFSMWNQAVDSYDPDVRIIENHGVEDELPNYCFPLNGQGISN
reference       NTELSYQLLLDSLGDRTRYFSMWNSAVDSYDPDVRIIENHGVEDELPNYCFPLDGTGTNS
                ********:**:****:*******.****************************:* * ..

predicted       SYQGVKTDNGTNWSQNNTDVSSNNEISIGNVFAMEINLAANLWRSFLYSNVALYLPDSYK
reference       TYQGVKETAAQNGWEKDPNVAAQNQICKGNIYAMEINLQANLWKSFLYSNVALYLPDSYK
                :*****   . *  :::.:*:::*:*. **::****** ****:****************

predicted       ITPDNITLPDNKNTYAYMNGRVAVPSALDTYVNIGARWSPDPMDNVNPFNHHRNAGLRYR
reference       YTPANVTLPANTNTYEYMNGRVVAPSLVDAYINIGARWSLDPMDNVNPFNHHRNAGLRYR
                 ** *:*** *.*** ******..** :*:*:******* ********************

predicted       SMLLGNGRYVPFHIQVPQKFFAIKNLLLLPGSYTYEWNFRKDVNMILQSSLGNDLRVDGA
reference       SMLLGNGRYVPFHIQVPQKFFAIKNLLLLPGSYTYEWNFRKDVNMILQSSLGNDLRVDGA
                ************************************************************

predicted       SVRFDSINLYANFFPMAHNTASTLEAMLRNDTNDQSFNDYLCAANMLYPIPANATSVPIS
reference       SVRFDSVNLYATFFPMAHNTASTLEAMLRNDTNDQSFNDYLSAANMLYPIPAKATNVPIS
                ******:****.*****************************.**********:**.****

predicted       IPSRNWAAFRGWSFTRLKTKETPSLGSGFDPYFTYSGSVPYLDGTFYLNHTFKKVSVMFD
reference       IPSRNWAAFRGWSFTRLKTKETPSLGSGFDPYFVYSGSIPYLDGTFYLNHTFKKVSIMFD
                *********************************.****:*****************:***

predicted       SSVSWPGNDRLLTPNEFEIKRTVDGEGYNVAQCNMTKDWFLIQMLSHYNIGYQGFHVPES
reference       SSVSWPGNDRLLTPNEFEIKRSVDGEGYNVAQCNMTKDWFLVQMLSHYNIGYQGFHVPEG
                *********************:*******************:*****************.

predicted       YKDRMYSFFRNFQPMSRQVVDTTTYTEYQNVTLPFQHNNSGFVGYMGPAIREGQAYPANY
reference       YKDRMYSFFRNFQPMSRQVVDEINYKDYKAVTLPFQHNNSGFTGYLAPTMRQGQPYPANF
                *********************  .*.:*: ************.**:.*::*:**.****:

predicted       PYPLIGQTAVPSLTQKKFLCDRTMWRIPFSSNFMSMGALTDLGQNMLYANSAHALDMTFE
reference       PYPLIGSTAVPSVTQKKFLCDRVMWRIPFSSNFMSMGALTDLGQNMLYANSAHALDMTFE
                ******.*****:*********.*************************************

predicted       VDPMDEPTLLYVLFEVFDVVRIHQPHRGVIEAVYLRTPFSAGNATT
reference       VDPMDEPTLLYLLFEVFDVVRVHQPHRGVIEAVYLRTPFSAGNATT
                ***********:*********:************************

>gi_9626553.20	17640	20414
ctcttaacagcattgtgggtctgggagtaaaaagcctgaaacgccgccggtgctattaaa
atggaaccaagctaaatgccattattgtgtacgcctcctgtgttacgccagagagccgag
tgacacgtcaccgccaagagcgccgcttgcAAGATGGCCACCCCCTCGATGATGCCGCAA
TGGTCTTACATGCACATCGCCGGGCAGGACGCCTCGGAGTACCTGAGCCCGGGCCTGGTG
CAGTTCGCCCGTGCCACCGATACCTACTTCAGCCTGGGGAACAAGTTCAGAAACCCCACC
GTGGCTCCCACCCACGATGTAACCACAGACAGGTCGCAGCGACTGACGCTGCGCTTCGTG
CCCGTCGACCGCGAGGAAACCGCCTACTCTTACAAAGTGCGCTTTACGCTGGCCGTGGGC
GACAACCGGGTTTTGGACATGGCCAGCACCTACTTTGACATCCGCGGCGTGCTGGATCGT
GGTCCCAGCTTTAAACCCTATTCGGGCACTGCATACAACTCCCTGGCCCCCAAAGGTGCT
CCCAATCCTAGCCAGTGGACAAACCAAAACAAAACAAACTCCTTTGGACAAGCTCCCTAT
ATAGGACAAAAAATCACCAATCAGGGCGTGCAAGTGGGCTCAGACTCCAACAATCGCGAT
GTGTTTGCCGATAAAACGTACCAACCGGAGCCTCAAGTGGGGCAGACGCAATGGAACATT
AATCCAATGCAAAACGCTGCGGGAAGAATACTAAAACAAACCACGCCCATGCAGCCATGT
TATGGGTCATACGCTAGACCAACAAACGAAAAAGGAGGTCAAGCCAAGCTGGTAAAAAAT
GACGACAATCAGACCACAACAACAAACGTAGGTTTAAACTTTTTTACCACTGCCACTGAA
ACCGCTAATTTTTCACCAAAGGTGGTTCTGTACAGCGAAGATGTTAACTTAGAAGCGCCC
GATACCCACCTTGTGTTTAAGCCAGATGTCAACGGCACAAGTGCCGAGCTTTTACTGGGA
CAGCAGGCCGCTCCCAATCGACCTAATTACATTGGTTTTAGGGACAACTTCATTGGTTTG
ATGTACTACAATTCCACTGGCAACATGGGAGTGCTGGCCGGGCAAGCTTCTCAGCTCAAC
GCAGTGGTGGACTTACAAGATAGAAACACGGAGCTGTCTTACCAGTTAATGCTTGACGCT
TTAGGGGATCGGAGTCGATACTTCTCCATGTGGAACCAGGCAGTGGACAGCTATGACCCA
GACGTGAGAATTATTGAAAATCATGGCGTGGAAGACGAGCTCCCCAACTATTGCTTTCCT
CTTAATGGGCAAGGAATATCTAACAGTTACCAAGGCGTAAAGACTGACAATGGAACTAAC
TGGTCTCAGAATAATACAGACGTCTCAAGCAACAACGAAATTTCCATTGGCAATGTGTTT
GCCATGGAGATTAATCTGGCGGCTAACTTGTGGAGAAGCTTCTTGTACTCAAATGTAGCC
CTGTACTTGCCTGACTCTTACAAAATAACCCCCGATAACATTACTTTACCCGACAACAAA
AATACATATGCCTACATGAACGGTCGGGTTGCCGTCCCCAGCGCCCTGGATACATACGTG
AACATTGGGGCGCGGTGGTCTCCAGACCCCATGGACAACGTTAATCCCTTTAACCACCAC
CGCAATGCTGGTCTGCGCTACCGTTCTATGCTCCTGGGTAACGGCCGCTACGTGCCTTTT
CACATCCAAGTGCCCCAGAAATTTTTCGCCATTAAAAATCTCCTGCTCCTGCCCGGGTCC
TACACCTATGAGTGGAACTTCCGGAAGGATGTTAACATGATTCTCCAAAGCAGTCTCGGT
AACGACCTCAGGGTCGATGGAGCCAGCGTCAGGTTTGACAGCATTAACCTGTATGCCAAC
TTTTTCCCCATGGCTCACAACACCGCTTCCACCTTGGAAGCAATGCTTCGTAATGATACC
AACGATCAGTCTTTCAACGACTACCTCTGCGCTGCAAACATGCTTTACCCCATACCCGCC
AACGCTACTAGCGTGCCCATTTCTATTCCTTCGCGAAATTGGGCTGCTTTTCGGGGGTGG
AGTTTTACTAGACTAAAAACTAAAGAAACCCCCTCTTTGGGGTCCGGGTTTGATCCATAT
TTCACCTACTCTGGCTCCGTCCCATACTTGGATGGCACCTTTTACCTGAACCACACTTTT
AAAAAGGTGTCCGTTATGTTCGACTCCTCTGTGAGCTGGCCTGGTAACGACCGACTACTT
ACTCCCAACGAGTTTGAAATCAAACGAACCGTGGATGGGGAAGGATACAACGTGGCTCAA
TGTAACATGACCAAGGACTGGTTCCTCATACAAATGCTCAGTCACTACAATATTGGCTAC
CAGGGTTTCCACGTACCAGAAAGCTACAAGGACAGGATGTACTCCTTTTTCCGAAACTTC
CAACCCATGAGCCGCCAGGTGGTAGACACTACCACCTACACGGAGTATCAGAATGTAACT
CTCCCTTTCCAGCATAATAACTCTGGCTTTGTAGGATACATGGGACCTGCCATACGGGAG
GGACAAGCTTACCCCGCCAACTATCCATACCCCCTTATTGGTCAGACGGCCGTACCAAGC
CTGACTCAGAAAAAATTTCTTTGCGATCGTACCATGTGGCGCATTCCCTTTTCCAGCAAC
TTTATGTCTATGGGGGCCCTGACCGACCTGGGGCAAAACATGCTGTACGCCAACTCCGCC
CACGCGCTCGACATGACTTTTGAGGTGGACCCCATGGATGAGCCCACACTTCTCTATGTT
CTGTTCGAAGTTTTCGACGTTGTGCGCATCCACCAGCCGCACCGCGGCGTCATCGAGGCC
GTCTACCTGCGTACGCCGTTCTCGGCCGGTAACGCCACCACATAAgaagccagccaatgg
gctccagcgagcaggagttggtcgccatcgtgcgcgaactgggctgcggaccttactttc
tgggcacgtttgacaaacgctttccgggttttatggcaccgcataagctggcgtgtgcca
ttgttaacacggcgg

Length = 945

Score =   323 bits (700), Expect(5) = 0.0
Identities = 131/139 (94%), Positives = 134/139 (96%)
Frame = +3

Query: 17640 KMATPSMMPQWSYMHIAGQDASEYLSPGLVQFARATDTYFSLGNKFRNPTVAPTHDVTTD 17819
             KMATPSMMPQW+YMHIAGQDASEYLSPGLVQFARATDTYFSLGNKFRNPTVAPTHDVTTD
Sbjct: 10    KMATPSMMPQWAYMHIAGQDASEYLSPGLVQFARATDTYFSLGNKFRNPTVAPTHDVTTD 69

Query: 17820 RSQRLTLRFVPVDREETAYSYKVRFTLAVGDNRVLDMASTYFDIRGVLDRGPSFKPYSGT 17999
             RSQRLTLRFVPVDRE+T YSYK RFTLAVGDNRVLDMASTYFDIRGVLDRGPSFKPYSGT
Sbjct: 70    RSQRLTLRFVPVDREDTTYSYKARFTLAVGDNRVLDMASTYFDIRGVLDRGPSFKPYSGT 129

Query: 18000 AYNSLAPKGAPNPSQWTNQ 18056
             AYNSLAPKGAPN SQW  +
Sbjct: 130   AYNSLAPKGAPNSSQWAQK 148

Score =  31.3 bits (62), Expect(5) = 0.0
Identities = 13/33 (39%), Positives = 18/33 (54%)
Frame = +3

Query: 18051 NQNKTNSFGQAPYIGQKITNQGVQVGSDSNNRD 18149
             NQ +T +FG A   G  I   G+Q+G+D    D
Sbjct: 154   NQTETRTFGVAAMGGILIDKNGLQIGTDETKPD 186

Score =  43.2 bits (88), Expect(5) = 0.0
Identities = 15/38 (39%), Positives = 24/38 (63%)
Frame = +3

Query: 18138 NNRDVFADKTYQPEPQVGQTQWNINPMQNAAGRILKQT 18251
             +N++++ADKT+QPEPQ G+  W    +      I K+T
Sbjct: 186   DNKEIYADKTFQPEPQKGEENWQDGDVFYGGRTIKKET 223

Score =  66.1 bits (138), Expect(5) = 0.0
Identities = 25/39 (64%), Positives = 30/39 (76%)
Frame = +3

Query: 18231 GRILKQTTPMQPCYGSYARPTNEKGGQAKLVKNDDNQTT 18347
             GR +K+ T M+PCYGS+ARPTNEKGGQAK   N + Q T
Sbjct: 216   GRTIKKETKMKPCYGSFARPTNEKGGQAKFKTNAEGQPT 254

Score =  1445 bits (3148), Expect(5) = 0.0
Identities = 573/671 (85%), Positives = 619/671 (92%)
Frame = +3

Query: 18399 FSPKVVLYSEDVNLEAPDTHLVFKPDVNGTSAELLLGQQAAPNRPNYIGFRDNFIGLMYY 18578
             F+P +V+Y+E++NLE PDTH+V+KP  +  S+E  L QQ+ PNRPNYIGFRDNF+GLMYY
Sbjct: 275   FNPDMVMYAENMNLETPDTHVVYKPGTSDDSSEANLAQQSMPNRPNYIGFRDNFVGLMYY 334

Query: 18579 NSTGNMGVLAGQASQLNAVVDLQDRNTELSYQLMLDALGDRSRYFSMWNQAVDSYDPDVR 18758
             NSTGNMGVLAGQASQLNAVVDLQDRNTELSYQL+LD+LGDR+RYFSMWN AVDSYDPDVR
Sbjct: 335   NSTGNMGVLAGQASQLNAVVDLQDRNTELSYQLLLDSLGDRTRYFSMWNSAVDSYDPDVR 394

Query: 18759 IIENHGVEDELPNYCFPLNGQGISNSYQGVKTDNGTNWSQNNTDVSSNNEISIGNVFAME 18938
             IIENHGVEDELPNYCFPL+G G +++YQGVK     N  + + +V++ N+I  GN++AME
Sbjct: 395   IIENHGVEDELPNYCFPLDGTGTNSTYQGVKETAAQNGWEKDPNVAAQNQICKGNIYAME 454

Query: 18939 INLAANLWRSFLYSNVALYLPDSYKITPDNITLPDNKNTYAYMNGRVAVPSALDTYVNIG 19118
             INL ANLW+SFLYSNVALYLPDSYK TP N+TLP N NTY YMNGRV  PS +D Y+NIG
Sbjct: 455   INLQANLWKSFLYSNVALYLPDSYKYTPANVTLPANTNTYEYMNGRVVAPSLVDAYINIG 514

Query: 19119 ARWSPDPMDNVNPFNHHRNAGLRYRSMLLGNGRYVPFHIQVPQKFFAIKNLLLLPGSYTY 19298
             ARWS DPMDNVNPFNHHRNAGLRYRSMLLGNGRYVPFHIQVPQKFFAIKNLLLLPGSYTY
Sbjct: 515   ARWSLDPMDNVNPFNHHRNAGLRYRSMLLGNGRYVPFHIQVPQKFFAIKNLLLLPGSYTY 574

Query: 19299 EWNFRKDVNMILQSSLGNDLRVDGASVRFDSINLYANFFPMAHNTASTLEAMLRNDTNDQ 19478
             EWNFRKDVNMILQSSLGNDLRVDGASVRFDS+NLYA FFPMAHNTASTLEAMLRNDTNDQ
Sbjct: 575   EWNFRKDVNMILQSSLGNDLRVDGASVRFDSVNLYATFFPMAHNTASTLEAMLRNDTNDQ 634

Query: 19479 SFNDYLCAANMLYPIPANATSVPISIPSRNWAAFRGWSFTRLKTKETPSLGSGFDPYFTY 19658
             SFNDYL AANMLYPIPA AT+VPISIPSRNWAAFRGWSFTRLKTKETPSLGSGFDPYF Y
Sbjct: 635   SFNDYLSAANMLYPIPAKATNVPISIPSRNWAAFRGWSFTRLKTKETPSLGSGFDPYFVY 694

Query: 19659 SGSVPYLDGTFYLNHTFKKVSVMFDSSVSWPGNDRLLTPNEFEIKRTVDGEGYNVAQCNM 19838
             SGS+PYLDGTFYLNHTFKKVS+MFDSSVSWPGNDRLLTPNEFEIKR+VDGEGYNVAQCNM
Sbjct: 695   SGSIPYLDGTFYLNHTFKKVSIMFDSSVSWPGNDRLLTPNEFEIKRSVDGEGYNVAQCNM 754

Query: 19839 TKDWFLIQMLSHYNIGYQGFHVPESYKDRMYSFFRNFQPMSRQVVDTTTYTEYQNVTLPF 20018
             TKDWFL+QMLSHYNIGYQGFHVPE YKDRMYSFFRNFQPMSRQVVD   Y +Y+ VTLPF
Sbjct: 755   TKDWFLVQMLSHYNIGYQGFHVPEGYKDRMYSFFRNFQPMSRQVVDEINYKDYKAVTLPF 814

Query: 20019 QHNNSGFVGYMGPAIREGQAYPANYPYPLIGQTAVPSLTQKKFLCDRTMWRIPFSSNFMS 20198
             QHNNSGF GY+ P +R+GQ YPAN+PYPLIG TAVPS+TQKKFLCDR MWRIPFSSNFMS
Sbjct: 815   QHNNSGFTGYLAPTMRQGQPYPANFPYPLIGSTAVPSVTQKKFLCDRVMWRIPFSSNFMS 874

Query: 20199 MGALTDLGQNMLYANSAHALDMTFEVDPMDEPTLLYVLFEVFDVVRIHQPHRGVIEAVYL 20378
             MGALTDLGQNMLYANSAHALDMTFEVDPMDEPTLLY+LFEVFDVVR+HQPHRGVIEAVYL
Sbjct: 875   MGALTDLGQNMLYANSAHALDMTFEVDPMDEPTLLYLLFEVFDVVRVHQPHRGVIEAVYL 934

Query: 20379 RTPFSAGNATT 20411
             RTPFSAGNATT
Sbjct: 935   RTPFSAGNATT 945


========================================================================================================================

gene_id            %id    %sim   %cov   %t5   %gap  %t3   start..stop      pep sz ref sz ref id            definition
gi_61602086.15     79.1   91.4   99.0   1.0   0.0   0.0   17510..20308     932    945    ACI04185-T5       L3-2 | hexon
                    could not find valid start codon

CLUSTAL 2.1 multiple sequence alignment


predicted       ---------KMATPSMMPQWSYMHIAGQDASEYLSPGLVQFARATDTYFSLGNKFRNPTV
reference       MCLTARERAKMATPSMMPQWAYMHIAGQDASEYLSPGLVQFARATDTYFSLGNKFRNPTV
                         ***********:***************************************

predicted       APTHDVTTDRSQRLTLRFVPVDREDTAYSYKVRYTLAVGDNRVLDMASTYFDIRGVLDRG
reference       APTHDVTTDRSQRLTLRFVPVDREDTTYSYKARFTLAVGDNRVLDMASTYFDIRGVLDRG
                **************************:****.*:**************************

predicted       PSFKPYSGTAYNSLAPKGAPNPAEWTNSDSKVKVRAQAP-F-VSSYGATAITKEGIQVGV
reference       PSFKPYSGTAYNSLAPKGAPNSSQWAQKKTGEDNQTETRTFGVAAMGGILIDKNGLQIGT
                *********************.::*::..:  . ::::  * *:: *.  * *:*:*:*.

predicted       TLTDSGSTPQYADKTYQPEPQIGELQWNSDVGTDDKIAGRVLKKTTPMFPCYGSYARPTN
reference       DETKPDNKEIYADKTFQPEPQKGEENWQD--G-DVFYGGRTIKKETKMKPCYGSFARPTN
                  *.....  *****:***** ** :*:.  * *   .**.:** * * *****:*****

predicted       EKGGQATPSASQDVQ-----NPELQFFASTNVAN----TPKAVLYAEDVSIEAPDTHLVF
reference       EKGGQAKFKTNAEGQPTEELDIDLNFFDINGGAGDNEFNPDMVMYAENMNLETPDTHVVY
                ******. .:. : *     : :*:**  .. *.    .*. *:***::.:*:****:*:

predicted       KPTVTEGITSSEALLTQQAAPNRPNYIAFRDNFIGLMYYNSTGNMGVLAGQASQLNAVVD
reference       KPGTSD--DSSEANLAQQSMPNRPNYIGFRDNFVGLMYYNSTGNMGVLAGQASQLNAVVD
                ** .::   **** *:**: *******.*****:**************************

predicted       LQDRNTELSYQLMLDALGDRSRYFSMWNQAVDSYDPDVRIIENHGVEDELPNYCFPLGGM
reference       LQDRNTELSYQLLLDSLGDRTRYFSMWNSAVDSYDPDVRIIENHGVEDELPNYCFPLDGT
                ************:**:****:*******.****************************.* 

predicted       AVTDTYSPIKVNGGGNGWEANNGVFTERGVEIGSGNMFAMEINLQANLWRSFLYSNIGLY
reference       GTNSTYQGVKETAAQNGWEKDPNVAAQN--QICKGNIYAMEINLQANLWKSFLYSNVALY
                ....**. :* ... **** : .* ::.  :* .**::***********:******:.**

predicted       LPDSLKITPDNITLPENKNTYQYMNGRVTPPGLVDTYVNVGARWSPDVMDSINPFNHHRN
reference       LPDSYKYTPANVTLPANTNTYEYMNGRVVAPSLVDAYINIGARWSLDPMDNVNPFNHHRN
                **** * ** *:*** *.***:******..*.***:*:*:***** * **.:********

predicted       AGLRYRSMLLGNGRYVPFHIQVPQKFFAIKNLLLLPGSYTYEWNFRKDVNMILQSSLGND
reference       AGLRYRSMLLGNGRYVPFHIQVPQKFFAIKNLLLLPGSYTYEWNFRKDVNMILQSSLGND
                ************************************************************

predicted       LRVDGASIRFDSINLYANFFPMAHNTASTLEAMLRNDTNDQSFNDYLCAANMLYPIPANA
reference       LRVDGASVRFDSVNLYATFFPMAHNTASTLEAMLRNDTNDQSFNDYLSAANMLYPIPAKA
                *******:****:****.*****************************.**********:*

predicted       TSVPISIPSRNWAAFRGWSFTRLKTKETPSLGSGFDPYFVYSGSIPYLDGTFYLNHTFKK
reference       TNVPISIPSRNWAAFRGWSFTRLKTKETPSLGSGFDPYFVYSGSIPYLDGTFYLNHTFKK
                *.**********************************************************

predicted       VSIMFDSSVSWPGNDRLLTPNEFEIKRSVDGEGYNVAQSNMTKDWFLIQMLSHYNIGYQG
reference       VSIMFDSSVSWPGNDRLLTPNEFEIKRSVDGEGYNVAQCNMTKDWFLVQMLSHYNIGYQG
                **************************************.********:************

predicted       FYVPENYKDRMYSFFRNFQPMSRQIVDSTAYTNYQDVKLPYQHNNSGFVGYMGPTMREGQ
reference       FHVPEGYKDRMYSFFRNFQPMSRQVVDEINYKDYKAVTLPFQHNNSGFTGYLAPTMRQGQ
                *:***.******************:**.  *.:*: *.**:*******.**:.****:**

predicted       AYPANYPYPLIGATAVPSLTQKKFLCDRVMWRIPFSSNFMSMGSLTDLGQNMLYANSAHA
reference       PYPANFPYPLIGSTAVPSVTQKKFLCDRVMWRIPFSSNFMSMGALTDLGQNMLYANSAHA
                .****:******:*****:************************:****************

predicted       LDMTFEVDPMDEPTLLYVLFEVFDVVRIHQPHRGVIEAVYLRTPFSAGNATT
reference       LDMTFEVDPMDEPTLLYLLFEVFDVVRVHQPHRGVIEAVYLRTPFSAGNATT
                *****************:*********:************************

>gi_61602086.18	17510	20308
agcacgctgaacagcatcgtgggcctgggagtgaaaagcctgaaacgccgccgttgctat
tattaaaagtgtagctaaaaaatttcccgttgtatacgcctcctatgttaccgccagaga
cgcgtgactgtcgccgcgagcgccgctttcAAGATGGCCACCCCATCGATGATGCCGCAG
TGGTCTTACATGCACATCGCCGGGCAGGACGCCTCGGAGTACCTGAGCCCCGGTCTCGTG
CAGTTCGCCCGCGCCACCGACACCTACTTCAGCTTGGGAAACAAGTTTAGAAACCCCACC
GTGGCCCCCACCCACGATGTAACCACGGACCGCTCGCAAAGGCTGACCCTGCGTTTTGTG
CCCGTAGACCGGGAGGACACCGCGTACTCTTACAAAGTGCGCTACACGCTGGCCGTAGGG
GACAACCGAGTGCTGGACATGGCCAGCACCTACTTTGACATCCGGGGAGTGCTGGATCGC
GGTCCCAGTTTTAAGCCCTACTCGGGTACCGCGTACAATTCCCTGGCTCCCAAGGGCGCT
CCCAACCCTGCAGAATGGACGAATTCAGACAGCAAAGTTAAAGTGAGGGCACAGGCGCCT
TTTGTTAGCTCGTATGGTGCTACAGCGATTACAAAAGAGGGTATTCAGGTGGGAGTAACC
TTAACAGACTCCGGATCAACACCACAGTATGCAGATAAAACGTATCAGCCTGAGCCGCAA
ATTGGAGAACTACAGTGGAACAGCGATGTTGGAACCGATGACAAAATAGCAGGAAGAGTG
CTAAAGAAAACAACGCCCATGTTCCCTTGTTACGGCTCATATGCCAGGCCCACTAATGAA
AAAGGAGGACAGGCAACACCGTCCGCTAGTCAAGACGTGCAAAATCCCGAATTACAATTT
TTTGCCTCTACTAATGTCGCCAATACACCAAAAGCAGTTCTATATGCGGAGGACGTGTCA
ATTGAAGCGCCAGACACTCACTTGGTGTTCAAACCAACAGTCACTGAAGGCATTACAAGT
TCAGAGGCTCTACTGACCCAACAAGCTGCTCCCAACCGTCCAAACTACATAGCCTTTAGA
GATAATTTTATTGGTCTCATGTACTACAATAGCACAGGTAACATGGGAGTACTGGCAGGC
CAGGCTTCTCAGCTAAATGCAGTTGTTGACCTGCAAGACAGAAATACTGAGCTGTCCTAC
CAACTCATGTTGGACGCCCTCGGAGACCGCAGTCGGTACTTTTCTATGTGGAACCAAGCT
GTGGATAGTTACGATCCTGATGTAAGAATCATAGAAAACCATGGCGTAGAAGATGAATTG
CCTAATTATTGCTTTCCTTTGGGAGGCATGGCAGTAACCGACACCTACTCGCCTATAAAG
GTTAATGGAGGAGGCAATGGATGGGAAGCCAATAACGGCGTTTTCACCGAAAGAGGAGTG
GAAATAGGTTCAGGGAACATGTTTGCCATGGAGATTAACCTGCAAGCCAACCTATGGCGT
AGCTTTCTGTACTCCAATATTGGGCTGTACCTGCCAGACTCTCTCAAAATCACTCCTGAC
AACATCACACTCCCAGAGAACAAAAACACCTATCAGTATATGAACGGTCGCGTGACGCCA
CCCGGGCTGGTTGACACCTACGTTAACGTGGGCGCGCGCTGGTCCCCCGATGTCATGGAC
AGTATTAACCCTTTTAATCACCACCGCAACGCCGGACTCCGCTACCGTTCCATGCTCCTG
GGAAACGGACGCTACGTGCCCTTCCACATCCAGGTGCCCCAGAAATTCTTTGCAATTAAA
AACCTGCTGCTGCTCCCCGGTTCCTACACCTACGAGTGGAACTTCCGCAAGGACGTGAAC
ATGATCTTGCAGAGCTCGCTGGGCAATGACCTGCGAGTGGACGGGGCCAGCATCCGCTTC
GACAGCATCAACCTGTACGCCAACTTTTTCCCCATGGCCCACAACACGGCCTCCACCCTG
GAAGCCATGCTGCGCAACGACACCAACGACCAATCTTTCAACGACTACCTGTGCGCGGCC
AACATGCTGTACCCCATCCCCGCCAACGCCACCAGCGTGCCCATCTCCATTCCCTCTCGC
AACTGGGCAGCCTTCAGGGGCTGGAGTTTCACCCGCCTCAAAACCAAGGAGACCCCCTCG
CTGGGCTCCGGGTTCGACCCCTACTTCGTCTACTCCGGCTCCATCCCCTACCTGGACGGC
ACCTTCTACCTCAACCATACTTTCAAAAAGGTGTCAATCATGTTCGACTCCTCCGTCAGC
TGGCCCGGCAACGACCGTCTGCTGACGCCCAACGAGTTCGAAATCAAGCGTTCGGTGGAC
GGTGAAGGGTACAACGTGGCTCAGAGCAACATGACCAAGGACTGGTTCCTGATTCAGATG
CTCAGCCACTACAACATCGGCTACCAGGGCTTCTACGTGCCCGAAAATTACAAGGACCGC
ATGTACTCTTTCTTCAGAAACTTCCAACCCATGAGCCGCCAAATTGTAGATTCAACGGCT
TACACTAATTATCAGGATGTGAAACTGCCATACCAGCATAACAACTCAGGGTTCGTGGGC
TACATGGGACCCACCATGCGAGAGGGGCAGGCCTACCCGGCCAACTATCCCTATCCCCTG
ATTGGGGCCACCGCCGTGCCCAGCCTCACGCAGAAAAAGTTCCTCTGCGACCGGGTGATG
TGGAGGATCCCCTTCTCTAGCAACTTCATGTCTATGGGCTCCCTCACCGACCTGGGGCAG
AACATGCTGTACGCCAACTCCGCTCACGCCTTGGATATGACCTTTGAGGTGGATCCCATG
GATGAGCCCACGCTTCTCTATGTTCTGTTTGAAGTCTTCGACGTGGTGCGCATCCACCAG
CCGCACCGCGGCGTCATCGAGGCCGTCTACCTGCGCACACCTTTCTCTGCCGGTAACGCC
ACCACCTAAagaagccgatgggctccagcgaacaggagctgcaggccattgttcgcgacc
tgggctgcgggccctactttttgggcaccttcgacaagcgttttcccggcttcatgtccc
cccacaagccggcctgtgccatcgttaacacggccggac

Length = 945

Score =   320 bits (694), Expect(6) = 0.0
Identities = 129/136 (94%), Positives = 133/136 (97%)
Frame = +2

Query: 17510 KMATPSMMPQWSYMHIAGQDASEYLSPGLVQFARATDTYFSLGNKFRNPTVAPTHDVTTD 17689
             KMATPSMMPQW+YMHIAGQDASEYLSPGLVQFARATDTYFSLGNKFRNPTVAPTHDVTTD
Sbjct: 10    KMATPSMMPQWAYMHIAGQDASEYLSPGLVQFARATDTYFSLGNKFRNPTVAPTHDVTTD 69

Query: 17690 RSQRLTLRFVPVDREDTAYSYKVRYTLAVGDNRVLDMASTYFDIRGVLDRGPSFKPYSGT 17869
             RSQRLTLRFVPVDREDT YSYK R+TLAVGDNRVLDMASTYFDIRGVLDRGPSFKPYSGT
Sbjct: 70    RSQRLTLRFVPVDREDTTYSYKARFTLAVGDNRVLDMASTYFDIRGVLDRGPSFKPYSGT 129

Query: 17870 AYNSLAPKGAPNPAEW 17917
             AYNSLAPKGAPN ++W
Sbjct: 130   AYNSLAPKGAPNSSQW 145

Score =  52.4 bits (108), Expect(6) = 0.0
Identities = 21/45 (46%), Positives = 27/45 (60%)
Frame = +2

Query: 17963 VSSYGATAITKEGIQVGVTLTDSGSTPQYADKTYQPEPQIGELQW 18097
             V++ G   I K G+Q+G   T   +   YADKT+QPEPQ GE  W
Sbjct: 163   VAAMGGILIDKNGLQIGTDETKPDNKEIYADKTFQPEPQKGEENW 207

Score =  59.3 bits (123), Expect(6) = 0.0
Identities = 24/40 (60%), Positives = 28/40 (70%)
Frame = +2

Query: 18131 GRVLKKTTPMFPCYGSYARPTNEKGGQATPSASQDVQNPE 18250
             GR +KK T M PCYGS+ARPTNEKGGQA    + + Q  E
Sbjct: 216   GRTIKKETKMKPCYGSFARPTNEKGGQAKFKTNAEGQPTE 255

Score =  41.4 bits (84), Expect(6) = 0.0
Identities = 13/27 (48%), Positives = 22/27 (81%)
Frame = +2

Query: 18287 PKAVLYAEDVSIEAPDTHLVFKPTVTE 18367
             P  V+YAE++++E PDTH+V+KP  ++
Sbjct: 277   PDMVMYAENMNLETPDTHVVYKPGTSD 303

Score =   267 bits (577), Expect(6) = 0.0
Identities = 107/141 (75%), Positives = 116/141 (82%)
Frame = +2

Query: 18377 SSEALLTQQAAPNRPNYIAFRDNFIGLMYYNSTGNMGVLAGQASQLNAVVDLQDRNTELS 18556
             SSEA L QQ+ PNRPNYI FRDNF+GLMYYNSTGNMGVLAGQASQLNAVVDLQDRNTELS
Sbjct: 305   SSEANLAQQSMPNRPNYIGFRDNFVGLMYYNSTGNMGVLAGQASQLNAVVDLQDRNTELS 364

Query: 18557 YQLMLDALGDRSRYFSMWNQAVDSYDPDVRIIENHGVEDELPNYCFPLGGMAVTDTYSPI 18736
             YQL+LD+LGDR+RYFSMWN AVDSYDPDVRIIENHGVEDELPNYCFPL G     TY  +
Sbjct: 365   YQLLLDSLGDRTRYFSMWNSAVDSYDPDVRIIENHGVEDELPNYCFPLDGTGTNSTYQGV 424

Query: 18737 KVNGGGNGWEANNGVFTERGV 18799
             K     NGWE +  V  +  +
Sbjct: 425   KETAAQNGWEKDPNVAAQNQI 445

Score =  1125 bits (2450), Expect(6) = 0.0
Identities = 446/502 (88%), Positives = 474/502 (94%)
Frame = +2

Query: 18800 EIGSGNMFAMEINLQANLWRSFLYSNIGLYLPDSLKITPDNITLPENKNTYQYMNGRVTP 18979
             +I  GN++AMEINLQANLW+SFLYSN+ LYLPDS K TP N+TLP N NTY+YMNGRV  
Sbjct: 444   QICKGNIYAMEINLQANLWKSFLYSNVALYLPDSYKYTPANVTLPANTNTYEYMNGRVVA 503

Query: 18980 PGLVDTYVNVGARWSPDVMDSINPFNHHRNAGLRYRSMLLGNGRYVPFHIQVPQKFFAIK 19159
             P LVD Y+N+GARWS D MD++NPFNHHRNAGLRYRSMLLGNGRYVPFHIQVPQKFFAIK
Sbjct: 504   PSLVDAYINIGARWSLDPMDNVNPFNHHRNAGLRYRSMLLGNGRYVPFHIQVPQKFFAIK 563

Query: 19160 NLLLLPGSYTYEWNFRKDVNMILQSSLGNDLRVDGASIRFDSINLYANFFPMAHNTASTL 19339
             NLLLLPGSYTYEWNFRKDVNMILQSSLGNDLRVDGAS+RFDS+NLYA FFPMAHNTASTL
Sbjct: 564   NLLLLPGSYTYEWNFRKDVNMILQSSLGNDLRVDGASVRFDSVNLYATFFPMAHNTASTL 623

Query: 19340 EAMLRNDTNDQSFNDYLCAANMLYPIPANATSVPISIPSRNWAAFRGWSFTRLKTKETPS 19519
             EAMLRNDTNDQSFNDYL AANMLYPIPA AT+VPISIPSRNWAAFRGWSFTRLKTKETPS
Sbjct: 624   EAMLRNDTNDQSFNDYLSAANMLYPIPAKATNVPISIPSRNWAAFRGWSFTRLKTKETPS 683

Query: 19520 LGSGFDPYFVYSGSIPYLDGTFYLNHTFKKVSIMFDSSVSWPGNDRLLTPNEFEIKRSVD 19699
             LGSGFDPYFVYSGSIPYLDGTFYLNHTFKKVSIMFDSSVSWPGNDRLLTPNEFEIKRSVD
Sbjct: 684   LGSGFDPYFVYSGSIPYLDGTFYLNHTFKKVSIMFDSSVSWPGNDRLLTPNEFEIKRSVD 743

Query: 19700 GEGYNVAQSNMTKDWFLIQMLSHYNIGYQGFYVPENYKDRMYSFFRNFQPMSRQIVDSTA 19879
             GEGYNVAQ NMTKDWFL+QMLSHYNIGYQGF+VPE YKDRMYSFFRNFQPMSRQ+VD   
Sbjct: 744   GEGYNVAQCNMTKDWFLVQMLSHYNIGYQGFHVPEGYKDRMYSFFRNFQPMSRQVVDEIN 803

Query: 19880 YTNYQDVKLPYQHNNSGFVGYMGPTMREGQAYPANYPYPLIGATAVPSLTQKKFLCDRVM 20059
             Y +Y+ V LP+QHNNSGF GY+ PTMR+GQ YPAN+PYPLIG+TAVPS+TQKKFLCDRVM
Sbjct: 804   YKDYKAVTLPFQHNNSGFTGYLAPTMRQGQPYPANFPYPLIGSTAVPSVTQKKFLCDRVM 863

Query: 20060 WRIPFSSNFMSMGSLTDLGQNMLYANSAHALDMTFEVDPMDEPTLLYVLFEVFDVVRIHQ 20239
             WRIPFSSNFMSMG+LTDLGQNMLYANSAHALDMTFEVDPMDEPTLLY+LFEVFDVVR+HQ
Sbjct: 864   WRIPFSSNFMSMGALTDLGQNMLYANSAHALDMTFEVDPMDEPTLLYLLFEVFDVVRVHQ 923

Query: 20240 PHRGVIEAVYLRTPFSAGNATT 20305
             PHRGVIEAVYLRTPFSAGNATT
Sbjct: 924   PHRGVIEAVYLRTPFSAGNATT 945


