========================================================================================================================

gene_id            %id    %sim   %cov   %t5   %gap  %t3   start..stop      pep sz ref sz ref id            definition
37.7               73.2   90.8   96.8   0.0   0.0   3.2   5151..5702       183    189    AAW33157.1        HYP-1 | hypothetical protein
                    stop codons embedded in CDS at 5421..5423, 5526..5528 and 5652..5654

CLUSTAL 2.1 multiple sequence alignment


predicted       MGVQRCQGSVLPGSQSSGQGCFRHSEGVCACLGACQGALQTHPAGRKLVPLGALYVGQVA
reference       MGVQRCQGPILPWSQRPSQGCFRHGEGVRAWLGACEGALQTHPAGREPLPIGALHVGQVA
                ********.:** ** ..******.*** * ****:**********: :*:***:*****

predicted       VYHEFVVERLGCVALGAELTFGSFLAYRAVXAFQRIQLGRKENGFWGVCIRAAGGANSFT
reference       VYHEFVVERLGRVAFGTELTFGSFMAGGAVDTFEGIQLGREENGFGGVCIRTAGGADGFA
                *********** **:*:*******:*  ** :*: *****:**** *****:****:.*:

predicted       FHQPGXIRFIGVKNKFSAIFFDAFLTFGLHELVSSLSDKQAVRVPVDXFYRPLFQWSASV
reference       LHEPGQIRLIGVKNKFSAMFFDAFLTFGFHEFVSPLGDKEAVRVPVDRLYGPVLERSASV
                :*:** **:*********:*********:**:**.*.**:******* :* *::: ****

predicted       FFV------
reference       LFVEEPSPL
                :**

>37.9	5151	5702
ttagaccgtcagccatgggcattttggagagagtctgttgcaaaagttctagtctgttcc
acagttcagtgatgtgttctatggcatctcgatccagcagacctcctcgtttcgcgggtt
tggacggctcctggagtagggtatgagacgATGGGCGTCCAGCGCTGCCAGGGTTCGGTC
CTTCCAGGGTCTCAAAGTTCGGGTCAGGGTTGTTTCCGTCACAGTGAAGGGGTGTGCGCC
TGCTTGGGCGCTTGCCAGGGTGCGCTTCAGACTCATCCTGCTGGTCGAAAACTTGTGCCG
CTTGGCGCCCTGTATGTCGGCCAAGTAGCAGTTTACCATGAGTTCGTAGTTGAGCGCCTC
GGCTGCGTGGCCCTTGGCGCGGAGCTTACCTTTGGAAGTTTTCTTGCATACCGGGCAGTA
TAGGCATTTCAGCGCATACAGCTTGGGCGCAAGGAAAATGGATTCTGGGGAGTATGCATC
CGCGCCGCAGGAGGCGCAAACAGTTTCACATTCCACCAGCCAGGTTAAATCCGGTTCATT
GGGGTCAAAAACAAGTTTTCCGCCATATTTTTTGATGCGTTTCTTACCTTTGGTCTCCAT
GAGTTGGTGTCCTCGTTGAGTGACAAACAGGCTGTCCGTGTCCCCGTAGACTGATTTTAC
AGGCCTCTTTTCCAGTGGAGTGCCTCGGTCTTCTTCGTATAGgaactctgaccactctga
tacaaaggcgcgcgtccaggccagcacaaaggaggctatgtgggaggggtagcgatcgtt
gtcaaccagggggtccaccttttccaaagtatgcaaacacatgtcactctcttcaacatc
caggaatgtgat

Length = 189

Score =   319 bits (691), Expect = 6e-92
Identities = 137/189 (72%), Positives = 152/189 (80%)
Frame = +3

Query: 5151 MGVQRCQGSVLPGSQSSGQGCFRHSEGVCACLGACQGALQTHPAGRKLVPLGALYVGQVA 5330
            MGVQRCQG +LP SQ   QGCFRH EGV A LGAC+GALQTHPAGR+ +P+GAL+VGQVA
Sbjct: 1    MGVQRCQGPILPWSQRPSQGCFRHGEGVRAWLGACEGALQTHPAGREPLPIGALHVGQVA 60

Query: 5331 VYHEFVVERLGCVALGAELTFGSFLAYRAV*AFQRIQLGRKENGFWGVCIRAAGGANSFT 5510
            VYHEFVVERLG VA G ELTFGSF+A  AV  F+ IQLGR+ENGF GVCIR AGGA+ F 
Sbjct: 61   VYHEFVVERLGRVAFGTELTFGSFMAGGAVDTFEGIQLGREENGFGGVCIRTAGGADGFA 120

Query: 5511 FHQPG*IRFIGVKNKFSAIFFDAFLTFGLHELVSSLSDKQAVRVPVD*FYRPLFQWSASV 5690
             H+PG IR IGVKNKFSA+FFDAFLTFG HE VS L DK+AVRVPVD  Y P+ + SASV
Sbjct: 121  LHEPGQIRLIGVKNKFSAMFFDAFLTFGFHEFVSPLGDKEAVRVPVDRLYGPVLERSASV 180

Query: 5691 FFV*EL*PL 5717
             FV E  PL
Sbjct: 181  LFVEEPSPL 189


========================================================================================================================

gene_id            %id    %sim   %cov   %t5   %gap  %t3   start..stop      pep sz ref sz ref id            definition
37.9               71.7   92.9   100.0  0.0   0.0   0.0   7857..8453       198    198    AAW33159.1        HYP-4 | hypothetical protein
                    stop codons embedded in CDS at 8265..8267 and 8316..8318

CLUSTAL 2.1 multiple sequence alignment


predicted       MRADREKLDFLPPVGGLAVDVMEVEVSAARRAFVFVLVQTAAVVAALHGLYLVNELYLAS
reference       MRANREELDLLPPVGGMAVDVMEVELPATRRAFMLVLVQTAAVLAAIHGMHLMNELYLTS
                ***:**:**:******:********:.*:****::********:**:**::*:*****:*

predicted       LDEKFQWEAEAWRLYLVLFYIRCIGLFIFCFNGGHADEPPREASPDLGAGGAELKDESAQ
reference       FDEKFQWKIEAWRLYLALYYVVCIGMTIFCLDGGHADEPSREASPDLGAAGAELEDESAQ
                :******: *******.*:*: ***: ***::*******.*********.****:*****

predicted       AGAVQSPETLRTQVSRXGQKINLHNLFQGVREVXMVLDFHRFVCRDVNGLQGSVSFGCHY
reference       AGAVQGPETLRSQVSRQCQEINLHDLLEGVREVQIVLDLNGSVGGDVDGLQGSVSLGRYH
                *****.*****:****  *:****:*::***** :***::  *  **:*******:* ::

predicted       RTFVFSFDRRWLSCFLHA
reference       RALVFHFGRRWLCCFLHV
                *::** *.****.****.

>37.12	7857	8453
tttaatggctagatcgtgggccatgttgacgagacgctcttctcctgagagtttcatgac
cagcatgaaaggaactagttgtttgccaaaggaccccatccaggtgtaagtttccacatc
gtaggtcaggaagagtctttctgtgcgaggATGAGAGCCGATCGGGAAAAACTGGATTTC
CTGCCACCAGTTGGAGGATTGGCTGTTGATGTGATGGAAGTAGAAGTTTCTGCGGCGCGC
CGAGCATTCGTGTTTGTGCTTGTACAGACGGCCGCAGTAGTCGCAGCGTTGCACGGGTTG
TATCTCGTGAATGAGCTGTACCTGGCTTCCCTTGACGAGAAATTTCAGTGGGAAGCCGAG
GCCTGGCGATTGTATCTCGTGCTCTTCTATATTCGCTGTATTGGCCTGTTCATCTTCTGT
TTCAATGGTGGTCATGCTGACGAGCCCCCGCGGGAGGCAAGTCCAGACCTCGGCGCGGGA
GGGGCGGAGCTGAAGGACGAGAGCGCGCAGGCTGGAGCTGTCCAGAGTCCTGAGACGCTG
CGGACTCAGGTTAGTAGGTAGGGACAGAAGATTAACTTGCATAATCTTTTCCAGGGCGTG
CGGGAGGTTTAGATGGTACTTGATTTCCACAGGTTCGTTTGTAGAGACGTCAATGGCTTG
CAGGGTTCCGTGTCCTTTGGGTGCCACTACCGTACCTTTGTTTTTTCTTTTGATCGGCGG
TGGCTCTCTTGCTTCTTGCATGCTTAAaagcggtgacggggacgcgcgccgggcggcagc
ggttgttccggacccgggggcatggctggtagtggcacgtcggcgccgcgcacgggcagg
ttctggtactgcgctctgagaagacttgcgtgcgccaccacgcgtcgattgacgtct

Length = 198

Score =   342 bits (741), Expect = 8e-99
Identities = 142/197 (72%), Positives = 167/197 (84%)
Frame = +3

Query: 7857 MRADREKLDFLPPVGGLAVDVMEVEVSAARRAFVFVLVQTAAVVAALHGLYLVNELYLAS 8036
            MRA+RE+LD LPPVGG+AVDVMEVE+ A RRAF+ VLVQTAAV+AA+HG++L+NELYL S
Sbjct: 1    MRANREELDLLPPVGGMAVDVMEVELPATRRAFMLVLVQTAAVLAAIHGMHLMNELYLTS 60

Query: 8037 LDEKFQWEAEAWRLYLVLFYIRCIGLFIFCFNGGHADEPPREASPDLGAGGAELKDESAQ 8216
             DEKFQW+ EAWRLYL L+Y+ CIG+ IFC +GGHADEP REASPDLGA GAEL+DESAQ
Sbjct: 61   FDEKFQWKIEAWRLYLALYYVVCIGMTIFCLDGGHADEPSREASPDLGAAGAELEDESAQ 120

Query: 8217 AGAVQSPETLRTQVSR*GQKINLHNLFQGVREV*MVLDFHRFVCRDVNGLQGSVSFGCHY 8396
            AGAVQ PETLR+QVSR  Q+INLH+L +GVREV +VLD +  V  DV+GLQGSVS G ++
Sbjct: 121  AGAVQGPETLRSQVSRQCQEINLHDLLEGVREVQIVLDLNGSVGGDVDGLQGSVSLGRYH 180

Query: 8397 RTFVFSFDRRWLSCFLH 8447
            R  VF F RRWL CFLH
Sbjct: 181  RALVFHFGRRWLCCFLH 197


========================================================================================================================

gene_id            %id    %sim   %cov   %t5   %gap  %t3   start..stop      pep sz ref sz ref id            definition
37.11              71.9   94.7   97.8   2.2   0.0   0.0   9785..10054      89     91     AAW33161.1        HYP-3 | hypothetical protein
                    could not find valid start codon

CLUSTAL 2.1 multiple sequence alignment


predicted       --HSPSIILTSSQIFVVVLHQPFYGHFFFTRSAMHTCESKPAHWLDQCQVSYDSFGEDGL
reference       MSHSPSIILTSGQIFIVVLHESFHGHFFFARSAMHASDPEPAHGLDKCQVRYNPFGEDGL
                  *********.***:****:.*:*****:*****:.:.:*** **:*** *:.******

predicted       LYLGEGGLKVIKIHEAVVSPGIDGVSTVGHD
reference       LHLGEGGLEVVKVHEAVVGPGVDCVGAVGHD
                *:******:*:*:*****.**:* *.:****

>37.14	9785	10054
tcggtctgggtcttctattccttcttcatctcgggaaggtaagacgatgctgctggtgat
gaaattaaagtaggcagttctaagacggcggatggtggcgaggagcaccaggtctttggg
tccggcttgctggatacgcaggcgattggcCATTCCCCAAGCATTATTCTGACATCTAGC
CAGATCTTTGTAGTAGTCTTGCATCAGCCGTTCTACGGGCACTTCTTCTTCACCCGTTCT
GCCATGCATACGTGTGAGTCCAAACCCGCGCATTGGTTGGACCAGTGCCAAGTCAGCTAC
GACTCTTTCGGCGAGGATGGCTTGCTGTACTTGGGTGAGGGTGGCTTGAAAGTCATCAAA
ATCCACGAAGCGGTGGTAAGCCCCGGTATTGATGGTGTAAGCACAGTTGGCCATGACTGA
ccagttaactgtttggtgaccagggcgcacgagctcggtgtatttaaggcgcgaataggc
gcgggtgtcaaagatgtaatcgttgcaggtgcgcaccagatactggtaccctataagaaa
atgcggtggtggttggcggtagagaggcca

Length = 91

Score =   168 bits (361), Expect = 6e-47
Identities = 64/91 (70%), Positives = 77/91 (84%)
Frame = +2

Query: 9779  IGHSPSIILTSSQIFVVVLHQPFYGHFFFTRSAMHTCESKPAHWLDQCQVSYDSFGEDGL 9958
             + HSPSIILTS QIF+VVLH+ F+GHFFF RSAMH  + +PAH LD+CQV Y+ FGEDGL
Sbjct: 1     MSHSPSIILTSGQIFIVVLHESFHGHFFFARSAMHASDPEPAHGLDKCQVRYNPFGEDGL 60

Query: 9959  LYLGEGGLKVIKIHEAVVSPGIDGVSTVGHD 10051
             L+LGEGGL+V+K+HEAVV PG+D V  VGHD
Sbjct: 61    LHLGEGGLEVVKVHEAVVGPGVDCVGAVGHD 91


========================================================================================================================

gene_id            %id    %sim   %cov   %t5   %gap  %t3   start..stop      pep sz ref sz ref id            definition
37.40              91.7   95.6   100.0  0.0   0.0   0.0   33068..33577     169    169    AAW33189.1        L5-2 | agnoprotein
                    stop codon embedded in CDS at 33122..33124

CLUSTAL 2.1 multiple sequence alignment


predicted       MLASVVIKTPPHLIVLRKXSTVAYANPNQAMQLDCVSSRRGEGRDGRSMLIFIPNDLAVL
reference       MLASVVIKTPSYLIVLRKSSTVAYANPNQAMQLDCVSSSRGEGRDGRIMLIFIPNDLAVL
                **********.:****** ******************* ******** ************

predicted       QIVDRADGICRPHCVGEKAQLDQKKCDFQGAQRWLPAKPPRAHPRTKEYQKKEHFLTPQS
reference       QIVDRADGIYRPHCVGEKAQLNQKKCDFQGAQRWLPTKPPRAHPKTKEYQKKEHFLTPQT
                ********* ***********:**************:*******:**************:

predicted       SYYSPAPFPDNFQLSSLGLFVSFLVVNPIHTLQTGPGGRPPPPFLNTPS
reference       SYYIPAPFPDNFQLSSLELFVSVLVVNPNHTLQTGPGGRPPPPFLNTPS
                *** ************* ****.***** ********************

>37.42	33068	33577
tcataatggagttgcttcctgacattctcgtattttgtatagcaaaacgcggccctggca
gaacacactcttcttcgccttctatcctgccgcttagcgtgttccgtgtgatagttcaag
tacagccacactcttaagttggtcaaaagaATGCTGGCTTCAGTTGTAATCAAAACTCCA
CCACATCTAATCGTTCTGAGGAAATGATCCACGGTAGCATATGCAAATCCCAACCAAGCA
ATGCAACTGGATTGCGTTTCAAGCAGGAGAGGAGAGGGAAGAGACGGAAGAAGCATGTTA
ATTTTTATTCCAAACGATCTCGCAGTACTTCAAATTGTAGATCGCGCAGATGGCATCTGT
CGCCCCCACTGTGTTGGTGAAAAAGCACAGCTAGATCAAAAGAAATGCGATTTTCAAGGT
GCTCAACGGTGGCTTCCAGCAAAGCCTCCACGCGCACATCCAAGAACAAAAGAATACCAA
AAGAAGGAGCATTTTCTAACTCCTCAATCATCATATTACAGTCCTGCACCATTCCCAGAT
AATTTTCAGCTTTCCAGCCTTGGATTATTCGTGTCATTTCTTGTGGTAAATCCAATCCAC
ACATTACAAACAGGTCCCGGAGGGCGCCCTCCACCACCATTCTTAAACACACCCTCATAA
tgacaaaatatcttgctcctgtgtcacctgtagcaaattgagaatggcaacatcaattga
catgccgttggctctaagttcttctctaagttctagttgtaaatactctttcatattatc
accaaactgcttagccagaagccccccggg

Length = 169

Score =   376 bits (816), Expect = e-109
Identities = 155/169 (91%), Positives = 159/169 (94%)
Frame = +2

Query: 33068 MLASVVIKTPPHLIVLRK*STVAYANPNQAMQLDCVSSRRGEGRDGRSMLIFIPNDLAVL 33247
             MLASVVIKTP +LIVLRK STVAYANPNQAMQLDCVSS RGEGRDGR MLIFIPNDLAVL
Sbjct: 1     MLASVVIKTPSYLIVLRKSSTVAYANPNQAMQLDCVSSSRGEGRDGRIMLIFIPNDLAVL 60

Query: 33248 QIVDRADGICRPHCVGEKAQLDQKKCDFQGAQRWLPAKPPRAHPRTKEYQKKEHFLTPQS 33427
             QIVDRADGI RPHCVGEKAQL+QKKCDFQGAQRWLP KPPRAHP+TKEYQKKEHFLTPQ+
Sbjct: 61    QIVDRADGIYRPHCVGEKAQLNQKKCDFQGAQRWLPTKPPRAHPKTKEYQKKEHFLTPQT 120

Query: 33428 SYYSPAPFPDNFQLSSLGLFVSFLVVNPIHTLQTGPGGRPPPPFLNTPS 33574
             SYY PAPFPDNFQLSSL LFVS LVVNP HTLQTGPGGRPPPPFLNTPS
Sbjct: 121   SYYIPAPFPDNFQLSSLELFVSVLVVNPNHTLQTGPGGRPPPPFLNTPS 169


========================================================================================================================

gene_id            %id    %sim   %cov   %t5   %gap  %t3   start..stop      pep sz ref sz ref id            definition
57.4               72.8   90.8   92.8   7.2   0.0   0.0   <8201..4866      1111   1193   AP_000539.1       E2B | putative DNA polymerase, C-terminal
                    missing exon 1

CLUSTAL 2.1 multiple sequence alignment


predicted       ------------------------------------------------------------
reference       MALVQAHGAGSFHPEASDPGCQPPRRRTCESSQGAVPEPTRARRRRTTASHAAGSRAAPA
                                                                            

predicted       --------------------------GTVIAPRAYGTLHAIDSTDGTPLEIKYHLHLRPA
reference       ARCAPSTPLLNMQEATEPPPPKRKNKGTVVAPKGHGTLQAIDISTNGPVEIKYHLNLPHA
                                          ***:**:.:***:*** : . *:******:*  *

predicted       LTRLCEVNLQAFPADALSFMSDTMDSSRLQALISCFSPARAEIWTCSGRGAVTLSVVTFK
reference       LEKIMQVNLLTLPTNLTPQRLRTLDSSGLRALVLELRPCRAEVWTCLPRGLVSMTTIETE
                * :: :*** ::*::  .    *:*** *:**:  : *.***:***  ** *:::.:  :

predicted       DPNGDNDATEQEDNERQLPRSGIHFPMRFLVRGRQVHLIQHIQPMQRCEYCARFYKHRHE
reference       DGHADADNIV----ERQVQTPGLNFPLKFLVKGSQVQLIHEVHPVNRCEYCGRLYKHKHE
                * :.* *       ***:  .*::**::***:* **:**:.::*::*****.*:***:**

predicted       CSARRRDFYFHHINAHSSNWWQEIQFFPVGSHPRTERLFITYDIETYTWMGSFGKQLVPF
reference       CSARRREFYFHHINSHSSNWWQEIQFFPIGSHPRTERLFLTYDVETYTWMGSFGKQLIPF
                ******:*******:*************:**********:***:*************:**

predicted       MLVMKLSGDSSLVAHALQLALELGWDQWEKDSSTFYCITPEKMKVGQQFRTYRNRLQTSL
reference       MLVMKLSGDQRLVNIAYDLAMKLKWDRWRQDPQTFYCVTPEKMAVGQHFRQYRDQLQTAL
                *********. **  * :**::* **:*.:*..****:***** ***:** **::***:*

predicted       AANLWNTFLQNNPQLHQWAQQQNGLVSPDDLTFEQLKKAPVIKGQPRFLELYIVGHNING
reference       AVDLWSSFLKANPHVHEWALEHYALTDPTDLTFEELKKLPHVRGTPRFLELYIVGHNING
                *.:**.:**: **::*:** :: .*..* *****:*** * ::* ***************

predicted       FDEIVLAAQVINNRSDVPAPFKISRNFIPRAGKILFNDITFALPNPYYKKRTDFLLWEQG
reference       FDEIVLAAQVINNRAEVPQPFRITRNFMPRAGKILFNDVTFALPNPAYKKRVDFQLWEQG
                **************::** **:*:***:**********:******* ****.** *****

predicted       GCDDQDFKYQYLKVMVRDTFALTHTSLRKAAEAYALPVEKGCCPYKAINQFYMLGSYRAD
reference       ACDDMDFKYQFLKVMVRDTFALTHTSLRNAAQAYSLPVEKGCCPYKAVNQFYMLGSYRAE
                .*** *****:*****************:**:**:************:***********:

predicted       ADGFPVEEYWKDKQEYLLNQELWKKKGEKNYNLILETLNYCALDVIVTTLLVEKLRSSYA
reference       KDGFPLEEYWKDREEYLLNRELWEKKSQPRYDIIQETLDYCALDVLVTAELVAKLQESYA
                 ****:******::*****:***:**.: .*::* ***:******:**: ** **:.***

predicted       QFVNQSVGLQQAHFNVFQRPTISSNSHALFRQILYRAEKPKRTHLGPNLLAPSHELYDYV
reference       HFIRDSVGLPHAHFNIFQRPTISSNSHAIFRQIVYRAEKPNRTNLGPGLLAPSHELYDYV
                :*:.:**** :****:************:****:******:**:***.************

predicted       RASIRGGRCYPTYIGVIQEPIYVYDICGMYASALTHPMPWGPPLNPYERALAVRQWQVAL
reference       RASIRGGRCYPTYIGILEEPLYVYDICGMYASALTHPMPWGTPLNPYERALAVREWQMTL
                ***************:::**:********************.************:**::*

predicted       ENLTSKIDYFDKILCPGIFTVDADPPDENQLDVLPPFCSRKGGRLAWTNESLRGEVVTSV
reference       DDPTT-ISYFDKDLLPGIFTIDADPPDELMLDPLPPFCSRKGGRLCWTNEPLRGEVATSV
                :: *: *.**** * *****:*******  ** ************.****.*****.***

predicted       DLVTLHNRGWRLRLLPDERTTVFPTWKCIAREYVQLNIAAKERADRDKNQTLRSIAKLLS
reference       DLITLHNRGWRVRIVPDELTTIFPEWKCVAREYVQLNIAAKERADKEKNQTMRSIAKLLS
                **:********:*::*** **:** ***:****************::****:********

predicted       NALYGSFATKLDNKKIVFSDQMEEGLIKEIAAGRLHIKSSSFIETDTLSTDVLPAFQRAY
reference       NALYGSFATKLDNKKIVFSDQMDESLMKGISAGTVNIKSSSFLETDNLSAEVMPAFEREY
                **********************:*.*:* *:** ::******:***.**::*:***:* *

predicted       SPQQLALVNSEAEDSDEDQCPTPFYSPPPGNSDHVTYTYKPITFIDAEEEDMCLHTLESS
reference       LPQQLALLDSDPEDSEDEQRPAPFYTPPAGTPGHVAYTYKPITFLDVEEGDMCLHTVEKV
                 ******::*:.***:::* *:***:**.*...**:********:*.** ******:*. 

predicted       NPLISNDRYPSHVASFVLAWTRAFVSEWSEFLYEEDRGIALKDRPIKSVYGDTDSLFVTE
reference       DPLVDNDRYPSHVASFVLAWTRAFVSEWAGFLYEEDRGTPLEDRPIKSVYGDTDSLFVTQ
                :**:.***********************: ******** .*:*****************:

predicted       KGRRLMESQGKKRIKKYGGKLVFDPSYPELTWSVECETVCANCGADAYAPESVFLAPKLY
reference       RGHDLMETKGKKRIKKHGGKLVFDPDEPDLTWLVECETVCASCGADAYSPESIFLAPKLY
                :*: ***::*******:********. *:*** ********.******:***:*******

predicted       ALKCLQCPDCGSTSKGKIRAKGHATDALSYDLMLKCYLAEAQGED-THFSTSRTSLKRTL
reference       ALKCIYCPACHKTSKGKLRAKGHAAEALNYELMVNCYLADMQGADRQRFSTSRMSLKRTL
                ****: ** * .*****:******::**.*:**::****: ** *  :***** ******

predicted       ASAQPGAHPFTVTETTLTRTLRPWKDKTLVHLDAHRLVPYSNSQPNPRNEEVCWIEME
reference       ASAQPGAHPFTVTETTLTRTLRPWKDRTLAALDAHRLIPYSRSRPNPRNEEVCWIEMP
                **************************:**. ******:***.*:*************

>57.4	8201	4866
tcgtgtcgtcgcccatgccagtcaactacgggctcagcaccttccactaccagaacgtca
ggccgacatacgactgcctcaagctcccgcagaagcggaagtcccagttcctgcacgccg
tcgcttttaagcaggcgtgttgctcaccgcGGAACAGTAATTGCACCTCGGGCTTACGGC
ACACTGCACGCAATAGATTCTACCGATGGCACTCCGCTTGAAATTAAGTATCACCTTCAC
CTACGGCCTGCTCTTACCCGCCTTTGTGAAGTTAACTTGCAAGCTTTCCCCGCAGACGCG
CTTTCCTTTATGAGTGATACCATGGACAGTTCCAGACTGCAAGCTTTGATTTCCTGCTTC
AGCCCCGCTCGAGCCGAAATATGGACGTGCAGCGGTCGAGGCGCCGTTACCCTTTCCGTT
GTCACTTTCAAGGATCCAAACGGTGACAACGATGCAACAGAACAGGAAGACAACGAACGG
CAACTGCCAAGAAGTGGCATCCATTTTCCCATGCGCTTTTTGGTGCGCGGTCGTCAGGTG
CACCTCATTCAACACATACAGCCCATGCAACGATGCGAATACTGCGCACGCTTTTACAAA
CATCGACATGAATGCTCTGCTCGCCGGCGAGATTTCTACTTCCACCACATTAACGCCCAC
TCTTCCAACTGGTGGCAGGAGATCCAGTTTTTCCCGGTCGGTTCGCATCCTCGCACTGAA
CGTCTTTTTATTACCTATGACATAGAAACCTACACCTGGATGGGCTCGTTTGGAAAGCAA
CTTGTACCATTTATGCTGGTAATGAAACTGTCTGGGGACAGTAGCCTTGTAGCGCACGCA
TTACAACTTGCCTTAGAACTTGGATGGGACCAATGGGAGAAAGACTCCTCTACTTTCTAT
TGTATTACCCCAGAAAAAATGAAGGTCGGTCAGCAATTCCGTACCTACAGAAATCGCTTG
CAAACGTCTTTAGCCGCTAACCTCTGGAATACTTTTTTACAAAACAATCCGCAGTTGCAT
CAGTGGGCGCAACAGCAAAATGGTCTGGTTAGTCCTGACGATCTAACCTTTGAACAGCTT
AAAAAAGCTCCTGTCATCAAGGGGCAGCCAAGATTTCTAGAGTTATACATAGTGGGGCAC
AATATTAATGGATTTGATGAAATAGTTCTTGCCGCGCAGGTCATAAACAATCGGTCAGAT
GTACCGGCGCCATTTAAAATCTCTAGAAATTTTATTCCAAGAGCTGGTAAAATTTTATTT
AATGACATAACTTTTGCTCTCCCTAATCCTTACTACAAAAAGCGCACTGACTTCCTGCTG
TGGGAGCAAGGAGGATGTGACGACCAGGACTTTAAATACCAGTATTTAAAAGTAATGGTC
AGGGACACCTTTGCTTTAACTCATACATCTTTAAGAAAGGCCGCTGAAGCTTATGCCCTG
CCTGTAGAAAAAGGTTGTTGTCCCTACAAGGCCATAAATCAATTTTACATGCTTGGTTCT
TACCGCGCTGATGCAGATGGTTTCCCTGTAGAGGAGTATTGGAAGGATAAACAGGAATAC
CTCCTAAACCAAGAACTATGGAAAAAAAAAGGAGAAAAAAATTACAATCTTATTCTGGAA
ACTTTAAACTATTGCGCCCTGGATGTCATCGTTACGACCTTATTGGTAGAAAAACTGCGC
AGTTCCTACGCCCAGTTTGTTAATCAGTCGGTGGGTCTTCAGCAGGCACACTTCAATGTG
TTTCAACGTCCCACCATCTCCTCTAACTCTCATGCGCTTTTTCGACAAATTTTGTATCGC
GCAGAGAAACCAAAACGCACACATTTAGGCCCTAACCTTTTGGCGCCTTCGCACGAACTA
TACGACTACGTTCGCGCAAGCATTCGCGGCGGCAGGTGCTATCCTACCTATATAGGTGTT
ATACAGGAACCCATATATGTATATGATATTTGTGGCATGTATGCATCAGCCCTTACACAC
CCTATGCCTTGGGGTCCTCCTCTTAACCCTTACGAACGAGCATTAGCCGTACGGCAGTGG
CAGGTGGCACTTGAAAATCTTACTTCCAAAATTGATTATTTTGATAAAATTTTATGTCCT
GGCATTTTTACTGTGGATGCTGATCCTCCAGACGAAAACCAGCTGGATGTTCTTCCTCCT
TTTTGCTCTCGAAAAGGCGGTCGTTTAGCCTGGACTAATGAGAGCTTGCGCGGCGAAGTG
GTCACCAGTGTAGACTTAGTTACACTGCATAATCGCGGGTGGCGTCTGCGATTATTACCA
GACGAACGTACCACCGTTTTTCCCACTTGGAAATGCATTGCTCGTGAATATGTACAACTC
AATATCGCCGCAAAAGAACGGGCAGACAGGGACAAAAACCAAACGCTAAGATCTATAGCC
AAGTTACTTTCAAACGCCCTGTACGGATCCTTTGCTACAAAATTAGATAACAAAAAAATT
GTTTTTTCTGATCAAATGGAAGAGGGGCTCATAAAAGAAATTGCAGCGGGCCGTTTGCAC
ATCAAATCCTCATCGTTTATAGAAACTGATACTTTGAGTACAGATGTGTTACCTGCCTTT
CAGCGCGCGTACTCACCGCAACAGCTGGCGCTCGTAAACAGCGAAGCCGAAGACAGCGAT
GAAGATCAGTGTCCCACCCCTTTTTATAGCCCCCCACCAGGGAACTCTGATCACGTGACT
TACACCTACAAACCAATCACATTCATAGATGCTGAAGAAGAGGATATGTGCTTACACACC
TTGGAAAGTTCCAACCCTTTAATTAGTAACGATCGGTACCCTTCCCATGTGGCCTCGTTT
GTACTGGCTTGGACTAGGGCCTTTGTGTCAGAGTGGTCAGAGTTTCTGTACGAGGAGGAC
CGTGGAATAGCCCTAAAGGACAGACCCATTAAATCTGTGTACGGAGACACAGACAGTCTT
TTTGTCACAGAGAAAGGACGCCGCCTTATGGAGTCGCAAGGTAAGAAACGCATCAAAAAG
TATGGAGGGAAACTTGTTTTTGATCCATCTTATCCTGAGCTGACCTGGTCGGTGGAATGC
GAAACTGTTTGTGCTAACTGCGGTGCAGATGCTTACGCTCCAGAGTCTGTTTTTTTGGCT
CCGAAACTGTACGCCCTTAAATGCCTTCAGTGTCCTGATTGTGGCAGCACTTCAAAGGGG
AAAATACGGGCTAAAGGTCACGCCACGGATGCCTTATCTTATGATCTCATGTTAAAATGC
TACCTTGCCGAAGCACAGGGAGAAGACACACACTTCAGCACCAGCCGCACCAGCTTAAAG
CGCACGCTGGCCAGCGCCCAACCAGGGGCGCATCCGTTCACCGTGACCGAAACAACCCTG
ACGCGCACCTTACGTCCATGGAAGGACAAAACCCTGGTGCACTTGGATGCTCATCGCCTT
GTTCCTTACAGCAACAGCCAGCCCAATCCCCGCAACGAGGAAGTCTGTTGGATCGAGATG
GAATAGaaaacataactcagctatgggaccgcttgcaactgttaaaacaaaccctggacc
acatgccaatggctgacggtctgaaaccattaaaaactttcaactctttgcaagagttgc
tctccttgggcggtgaacgccttctcagggaacttg

Length = 1193

Score =  34.1 bits (68), Expect(5) = 0.0
Identities = 14/30 (46%), Positives = 18/30 (60%)
Frame = -3

Query: 8345 RRPCQSTTGSAPSTTRTSGRHTTASSSRRS 8256
            RR C+S+ G+ P  TR   R TTAS +  S
Sbjct: 26   RRTCESSQGAVPEPTRARRRRTTASHAAGS 55

Score =   108 bits (231), Expect(5) = 0.0
Identities = 45/103 (43%), Positives = 67/103 (65%)
Frame = -3

Query: 8207 HRGTVIAPRAYGTLHAIDSTDGTPLEIKYHLHLRPALTRLCEVNLQAFPADALSFMSDTM 8028
            ++GTV+AP+ +GTL AID +   P+EIKYHL+L  AL ++ +VNL   P +       T+
Sbjct: 85   NKGTVVAPKGHGTLQAIDISTNGPVEIKYHLNLPHALEKIMQVNLLTLPTNLTPQRLRTL 144

Query: 8027 DSSRLQALISCFSPARAEIWTCSGRGAVTLSVVTFKDPNGDND 7899
            DSS L+AL+    P RAE+WTC  RG V+++ +  +D + D D
Sbjct: 145  DSSGLRALVLELRPCRAEVWTCLPRGLVSMTTIETEDGHADAD 187

Score =  1054 bits (2296), Expect(5) = 0.0
Identities = 401/541 (74%), Positives = 470/541 (86%)
Frame = -3

Query: 7907 DNDATEQEDNERQLPRSGIHFPMRFLVRGRQVHLIQHIQPMQRCEYCARFYKHRHECSAR 7728
            D  A      ERQ+   G++FP++FLV+G QV LI  + P+ RCEYC R YKH+HECSAR
Sbjct: 181  DGHADADNIVERQVQTPGLNFPLKFLVKGSQVQLIHEVHPVNRCEYCGRLYKHKHECSAR 240

Query: 7727 RRDFYFHHINAHSSNWWQEIQFFPVGSHPRTERLFITYDIETYTWMGSFGKQLVPFMLVM 7548
            RR+FYFHHIN+HSSNWWQEIQFFP+GSHPRTERLF+TYD+ETYTWMGSFGKQL+PFMLVM
Sbjct: 241  RREFYFHHINSHSSNWWQEIQFFPIGSHPRTERLFLTYDVETYTWMGSFGKQLIPFMLVM 300

Query: 7547 KLSGDSSLVAHALQLALELGWDQWEKDSSTFYCITPEKMKVGQQFRTYRNRLQTSLAANL 7368
            KLSGD  LV  A  LA++L WD+W +D  TFYC+TPEKM VGQ FR YR++LQT+LA +L
Sbjct: 301  KLSGDQRLVNIAYDLAMKLKWDRWRQDPQTFYCVTPEKMAVGQHFRQYRDQLQTALAVDL 360

Query: 7367 WNTFLQNNPQLHQWAQQQNGLVSPDDLTFEQLKKAPVIKGQPRFLELYIVGHNINGFDEI 7188
            W++FL+ NP +H+WA +   L  P DLTFE+LKK P ++G PRFLELYIVGHNINGFDEI
Sbjct: 361  WSSFLKANPHVHEWALEHYALTDPTDLTFEELKKLPHVRGTPRFLELYIVGHNINGFDEI 420

Query: 7187 VLAAQVINNRSDVPAPFKISRNFIPRAGKILFNDITFALPNPYYKKRTDFLLWEQGGCDD 7008
            VLAAQVINNR++VP PF+I+RNF+PRAGKILFND+TFALPNP YKKR DF LWEQG CDD
Sbjct: 421  VLAAQVINNRAEVPQPFRITRNFMPRAGKILFNDVTFALPNPAYKKRVDFQLWEQGACDD 480

Query: 7007 QDFKYQYLKVMVRDTFALTHTSLRKAAEAYALPVEKGCCPYKAINQFYMLGSYRADADGF 6828
             DFKYQ+LKVMVRDTFALTHTSLR AA+AY+LPVEKGCCPYKA+NQFYMLGSYRA+ DGF
Sbjct: 481  MDFKYQFLKVMVRDTFALTHTSLRNAAQAYSLPVEKGCCPYKAVNQFYMLGSYRAEKDGF 540

Query: 6827 PVEEYWKDKQEYLLNQELWKKKGEKNYNLILETLNYCALDVIVTTLLVEKLRSSYAQFVN 6648
            P+EEYWKD++EYLLN+ELW+KK +  Y++I ETL+YCALDV+VT  LV KL+ SYA F+ 
Sbjct: 541  PLEEYWKDREEYLLNRELWEKKSQPRYDIIQETLDYCALDVLVTAELVAKLQESYAHFIR 600

Query: 6647 QSVGLQQAHFNVFQRPTISSNSHALFRQILYRAEKPKRTHLGPNLLAPSHELYDYVRASI 6468
             SVGL  AHFN+FQRPTISSNSHA+FRQI+YRAEKP RT+LGP LLAPSHELYDYVRASI
Sbjct: 601  DSVGLPHAHFNIFQRPTISSNSHAIFRQIVYRAEKPNRTNLGPGLLAPSHELYDYVRASI 660

Query: 6467 RGGRCYPTYIGVIQEPIYVYDICGMYASALTHPMPWGPPLNPYERALAVRQWQVALENLT 6288
            RGGRCYPTYIG+++EP+YVYDICGMYASALTHPMPWG PLNPYERALAVR+WQ+ L++ T
Sbjct: 661  RGGRCYPTYIGILEEPLYVYDICGMYASALTHPMPWGTPLNPYERALAVREWQMTLDDPT 720

Query: 6287 S 6285
            +
Sbjct: 721  T 721

Score =   774 bits (1685), Expect(5) = 0.0
Identities = 304/399 (76%), Positives = 352/399 (88%)
Frame = -3

Query: 6281 IDYFDKILCPGIFTVDADPPDENQLDVLPPFCSRKGGRLAWTNESLRGEVVTSVDLVTLH 6102
            I YFDK L PGIFT+DADPPDE  LD LPPFCSRKGGRL WTNE LRGEV TSVDL+TLH
Sbjct: 722  ISYFDKDLLPGIFTIDADPPDELMLDPLPPFCSRKGGRLCWTNEPLRGEVATSVDLITLH 781

Query: 6101 NRGWRLRLLPDERTTVFPTWKCIAREYVQLNIAAKERADRDKNQTLRSIAKLLSNALYGS 5922
            NRGWR+R++PDE TT+FP WKC+AREYVQLNIAAKERAD++KNQT+RSIAKLLSNALYGS
Sbjct: 782  NRGWRVRIVPDELTTIFPEWKCVAREYVQLNIAAKERADKEKNQTMRSIAKLLSNALYGS 841

Query: 5921 FATKLDNKKIVFSDQMEEGLIKEIAAGRLHIKSSSFIETDTLSTDVLPAFQRAYSPQQLA 5742
            FATKLDNKKIVFSDQM+E L+K I+AG ++IKSSSF+ETD LS +V+PAF+R Y PQQLA
Sbjct: 842  FATKLDNKKIVFSDQMDESLMKGISAGTVNIKSSSFLETDNLSAEVMPAFEREYLPQQLA 901

Query: 5741 LVNSEAEDSDEDQCPTPFYSPPPGNSDHVTYTYKPITFIDAEEEDMCLHTLESSNPLISN 5562
            L++S+ EDS+++Q P PFY+PP G   HV YTYKPITF+D EE DMCLHT+E  +PL+ N
Sbjct: 902  LLDSDPEDSEDEQRPAPFYTPPAGTPGHVAYTYKPITFLDVEEGDMCLHTVEKVDPLVDN 961

Query: 5561 DRYPSHVASFVLAWTRAFVSEWSEFLYEEDRGIALKDRPIKSVYGDTDSLFVTEKGRRLM 5382
            DRYPSHVASFVLAWTRAFVSEW+ FLYEEDRG  L+DRPIKSVYGDTDSLFVT++G  LM
Sbjct: 962  DRYPSHVASFVLAWTRAFVSEWAGFLYEEDRGTPLEDRPIKSVYGDTDSLFVTQRGHDLM 1021

Query: 5381 ESQGKKRIKKYGGKLVFDPSYPELTWSVECETVCANCGADAYAPESVFLAPKLYALKCLQ 5202
            E++GKKRIKK+GGKLVFDP  P+LTW VECETVCA+CGADAY+PES+FLAPKLYALKC+ 
Sbjct: 1022 ETKGKKRIKKHGGKLVFDPDEPDLTWLVECETVCASCGADAYSPESIFLAPKLYALKCIY 1081

Query: 5201 CPDCGSTSKGKIRAKGHATDALSYDLMLKCYLAEAQGED 5085
            CP C  TSKGK+RAKGHA +AL+Y+LM+ CYLA+ QG D
Sbjct: 1082 CPACHKTSKGKLRAKGHAAEALNYELMVNCYLADMQGAD 1120

Score =   156 bits (336), Expect(5) = 0.0
Identities = 62/69 (89%), Positives = 65/69 (94%)
Frame = -3

Query: 5078 FSTSRTSLKRTLASAQPGAHPFTVTETTLTRTLRPWKDKTLVHLDAHRLVPYSNSQPNPR 4899
            FSTSR SLKRTLASAQPGAHPFTVTETTLTRTLRPWKD+TL  LDAHRL+PYS S+PNPR
Sbjct: 1124 FSTSRMSLKRTLASAQPGAHPFTVTETTLTRTLRPWKDRTLAALDAHRLIPYSRSRPNPR 1183

Query: 4898 NEEVCWIEM 4872
            NEEVCWIEM
Sbjct: 1184 NEEVCWIEM 1192


========================================================================================================================

gene_id            %id    %sim   %cov   %t5   %gap  %t3   start..stop      pep sz ref sz ref id            definition
57.17              36.4   49.7   100.0  0.0   0.0   0.0   24657..24818     128    231    AP_000279.1       L4-3 | splicing factor
                                                          25210..25434                                     
                    invalid splicing for intron  at 24819..25209

CLUSTAL 2.1 multiple sequence alignment


predicted       MSPKT-AKQAIAQQRSKKQLQQ---QEIWEEDSWDSQAQEDQD------LEEWEE--ESL
reference       MSQRRGSKKLKVQLPPPEDMEEDWDSQTEEMEDWDSQAEEEEDSLEEDSLEEEDEEAEEV
                ** :  :*:  .*  . :::::   .:  * :.*****:*::*      *** :*  *.:

predicted       DE-----------------D----------------PE---EES---P------------
reference       EEATAAKQLSSAAETSKATDSTTATISAPGRGAQHRPNSRWDETGRLPNATTASKTAPIT
                :*                 *                *:   :*:   *            

predicted       ----------------------------------------EARELRKRIFPTLYAIFQQS
reference       ARKSRQKKTTAARTSSRKPAAVRKPTAGAGGLRITANEPAQTRELRNRIFPTLYAIFQQS
                                                        ::****:*************

predicted       RGQEHELKIKNRSLRSLTRSCLYLKSEDQLQRTLQDAEALFNKYCSLSLKE
reference       RGQEQELKVKNRSLRSLTRSCLYHKSEDQLQRTLEDAEALFNKYCALTLKE
                ****:***:************** **********:**********:*:***

>57.19	24657	25434
aaattttagcccaattacaagccattaaacaagcgcgcgaagaattcttactcacaaaag
gacgcggagtgtaccttgacccccagaccggcgaggaactgaaccttccatcacctctgt
gtgctactgcatcctctccccattcgcagcATGTCCCCGAAAACCGCAAAACAAGCTATT
GCACAGCAACGCTCAAAGAAGCAGCTACAACAGCAGGAAATCTGGGAGGAAGATTCTTGG
GACAGTCAGGCACAGGAGGACCAGGACTTGGAAGAATGGGAGGAGGAAAGCCTAGACGAG
GATCCAGAGGAGgacggttccaaggacggagcgaccgccgccaaaccgtcgctttcaacc
gaaccctctccagtgaaacacactgtcaacaaatctcagaaagcgagccgtagatgggac
accactgaagccagcgtcgtaaacatgggtaagaaatgcaagcaggtgcggcggggctac
tgctcatggcgggctcataaaagtaatatcatagcctgcttgcaacactgcgggggaaac
atctcatttgcaaggcggtatctgctctttcacgatggagtggcaattcctaggaatgtt
ctccattactaccgtcatctctacagccccttcgaagagatccacaaagaatcgacgtct
tacggaccagcggcccactagaaaaaccggcagcagcaacaagGAAAGTCCAGAGGCGCG
CGAGTTAAGAAAACGCATTTTTCCCACTCTATATGCTATTTTTCAGCAGAGCCGAGGCCA
AGAACACGAACTGAAAATAAAAAACAGATCCCTCCGTTCACTTACCCGCAGCTGTCTCTA
CCTCAAAAGCGAAGACCAGTTGCAACGCACCTTGCAGGACGCTGAAGCTCTGTTCAATAA
ATACTGCTCCCTCTCGCTTAAAGAGTAAaaaaagcccgcgcgcggacttctgacaagcgg
gaaagtgacgtcacatttataacaggatgagtaaagatattcccacgccttacatgtgga
gttttcaacctcaaatggggctagcggcgggtgcggctcaagactattctactaaaat

Length = 231

Score =  34.1 bits (68), Expect(2) = 3e-44
Identities = 15/39 (38%), Positives = 25/39 (64%)
Frame = +3

Query: 24735 EDSWDSQAQEDQDLEEWEEESLDEDPEEDGSKDGATAAK 24851
             E+  D  +Q +++ +  EE+SL+E+ EE    + ATAAK
Sbjct: 29    EEMEDWDSQAEEEEDSLEEDSLEEEDEEAEEVEEATAAK 67

Score =   150 bits (322), Expect(2) = 3e-44
Identities = 63/74 (85%), Positives = 68/74 (91%)
Frame = +1

Query: 25210 ESPEARELRKRIFPTLYAIFQQSRGQEHELKIKNRSLRSLTRSCLYLKSEDQLQRTLQDA 25389
             E  + RELR RIFPTLYAIFQQSRGQE ELK+KNRSLRSLTRSCLY KSEDQLQRTL+DA
Sbjct: 158   EPAQTRELRNRIFPTLYAIFQQSRGQEQELKVKNRSLRSLTRSCLYHKSEDQLQRTLEDA 217

Query: 25390 EALFNKYCSLSLKE 25431
             EALFNKYC+L+LKE
Sbjct: 218   EALFNKYCALTLKE 231


========================================================================================================================

gene_id            %id    %sim   %cov   %t5   %gap  %t3   start..stop      pep sz ref sz ref id            definition
64.10              79.3   91.2   100.0  0.0   0.0   0.0   13472..13460     1186   1192   AP_000266.1       E2B | DNA polymerase
                                                          8521..4974                                       
                    stop codons embedded in CDS at 8519..8517 and 8510..8508

CLUSTAL 2.1 multiple sequence alignment


predicted       MALVNXFCXTVFQVQSHGARGLHAKAADPGCQPPRRRARQRSQGAAPGPARAPRRRASTA
reference       MALV----------QAHGAGSFHPEATDPGRQPPRCRARKSSQGAVPEPTRARRRRATAS
                ****          *:*** .:*.:*:*** **** ***: ****.* *:** ****:::

predicted       TARGAGTAAAAGSASATPLL------------KAHRGTVVAPRSYGLMQCVDTTTNSPVE
reference       HAAGARAASTARRAPSPPLLNMQEATPPPPPKRKNKGTVVAPKGHGTLQAIDISTNGPVE
                 * ** :*::*  *.:.***            : ::******:.:* :*.:* :**.***

predicted       IKYHLHLKHALTRLYEVNLRTLPPDLDLR--DTMDSSQLRALVFALRPRRAEIWTWLPRG
reference       IKYHLNLPLALEKIMQVNLLTLPTNLTPQRLRTLDSSGLRALVLELRPSRAEVWTCLPRG
                *****:*  ** :: :*** ***.:*  :   *:*** *****: *** ***:** ****

predicted       LVSLSVLEEPQGESHAG---EHENHQPGPPL-LKFLLKGRAVYLVDEVQPVQRCEYCGRF
reference       LVSMTTIETEDGQADADNIVESEVKAPGLNFPLKFLVKGSQVQLIHEVHPVQRCEYCGRL
                ***::.:*  :*::.*.   * * : **  : ****:**  * *:.**:**********:

predicted       YKHQHECSVRRRDFYFHHINSHSTNWWQEIQFFPIGSHPRTERLFVTYDVETYTWMGSFG
reference       YKHKHECSARRRDFYFHHINSHSSNWWQEIQFFPIGSHPRTERLFLTYDVETYTWMGSFG
                ***:****.**************:*********************:**************

predicted       KQLVPFMLVMKFSGDPELVALARDLAVRLRWDRWERDPLTFYCVTPEKMAVGQQFRLFRD
reference       KQLIPFMLVMKLSGDERLVNIAYDLAMKLKWDRWQQDPKTFYCVTPEKMAVGQHFRQYRD
                ***:*******:*** .** :* ***::*:****::** **************:** :**

predicted       ELQTLMARELWASFMQANPHLQEWALEQHGLQCPEDLTYEELKKLPHIKGRPRFMELYIV
reference       QLQTALAVDLWSSFLNANPHLHEWALEHYALSDPTDLTFEELKKLPHVKGTPRFIELYIV
                :*** :* :**:**::*****:*****::.*. * ***:********:** ***:*****

predicted       GHNINGFDEIVLAAQVINNRASVPGPFRITRNFMPRAGKILFNDVTFALPNPLSKKRTDF
reference       GHNINGFDEIVLAAQVINNRAKVPQPFRITRNFMPRAGKILFNDVTFALPNPAYKKRVDF
                *********************.** ***************************  ***.**

predicted       ELWEHGGCDDSDFKYQFLKVMVRDTFALTHTSLRKAAQAYALPVEKGCCPYKAVNHFYML
reference       QLWEQGACNDIDFKYQFLKVMVRDTFALTHTSLRKAAQAYSLPVEKGCCPYKAVNQFYML
                :***:*.*:* *****************************:**************:****

predicted       GSYRADDRGFPLREYWKDDEEYALNRALWEKKEEAGYDIIRETLDYCAMDVLVTAELVAK
reference       GSYRADKDGFPLEEYWKDREEYLLNRELWEKKNQPGYDIIQETLDYCALDVLVTAELVAK
                ******. ****.***** *** *** *****::.*****:*******:***********

predicted       LQDSYAHFIRDSVRLPHAHFNIFQRPTISSNSHAIFRQIVFRAEQPQRTNLGPAFLAPSH
reference       LQESYAHFVRDSVGLPHAHFNIFQRPTISSNSHAIFRQIVYRAEKPNRTNLGPGLLAPSH
                **:*****:**** **************************:***:*:******.:*****

predicted       ELYDYVRASIRGGRCYPTYIGILSEPIYVYDICGMYASALTHPMPWGPPLNPYERALAAR
reference       ELYDYVRASIRGGRCYPTYIGILEEPLYVYDICGMYASALTHPMPWGTPLNPYERALAAR
                ***********************.**:********************.************

predicted       EWQMALDDASSKIDYFDKELCPGIFTIDADPPDEHLLDVLPPFCSRKGGRLCWTNEPLRG
reference       EWQMALDDP-AHISYFDKDLLPGIFTMDADPPDELMLDPLPPFCSRKGGRLCWTNEPLRG
                ********. ::*.****:* *****:******* :** *********************

predicted       EVATSVDLVTLHNRGWRVRIVPDERTTVFPEWKCVAREYVQLNIAAKERADRDKNQTMRS
reference       EVATSVDLITLHNRGWRVRIVPDELTTIFPEWKCLAREYVQLNIAAKERADKDKNQTMRS
                ********:*************** **:******:****************:********

predicted       IAKLLSNALYGSFATKLDNKKIVFSDQMDESLLKSIAAGQANIKSSSFLETDNLSAEVMP
reference       IAKLLSNALYGSFATKLDNKKIVFSDQMDESLMKGISTGTVNIKSSSFLETDNLSAEVMP
                ********************************:*.*::* .*******************

predicted       ALEREYLPQQLALVDSDAEESEDEHRPAPFYTPPSGTPGHVAYTYKPITFLDAEEGDMCL
reference       AFEREYLPQQLALLDSDPEDSEDEQRPAPFYTPPAGT-GHVAYTYKPITFLDVEEGDMCL
                *:***********:***.*:****:*********:** **************.*******

predicted       HTVEKVDPLVDNDRYPSHVASFVLAWTRAFVSEWSEFLYEEDRGTPLQDRPIKSVYGDTD
reference       HTVEKVDPLVDNDRYPSHVASFVLAWTRAFVSEWSGFLYEEDRGTPLEDRPIKSVYGDTD
                *********************************** ***********:************

predicted       SLFVTERGHRLMETRGKKRIKKNGGKLVFDPEQPELTWLVECETVCAHCGADAFAPESVF
reference       SLFVTQRGHELMETKGKKRIKKHGGKLVFDPDEPDLTWLVECETICASCGADAYSPESIF
                *****:***.****:*******:********::*:*********:** *****::***:*

predicted       LAPKLYALQSLLCPACGRSSKGKLRAKGHAAEALNYKLMVNCYLADAQGEDRARFSTSRM
reference       LAPKLYALKCLYCPACQKTSKGKLRAKGHAAEALNYELMVNCYMADMQGADRQRFSTSRM
                ********:.* **** ::*****************:******:** ** ** *******

predicted       SLKRTLASAQPGAHPFTVTETTLTRTLRPWKDMTLAALDAHRLVPYSRSRPNPRNEEVCW
reference       SLKRTLASAQPGAHPFTVTETTLTRTLRPWKDRTLAALDAHRLIPYSRSRPNPRNEEVCW
                ******************************** **********:****************

predicted       IEMP
reference       IEMP
                ****

>64.6	13472	4974
tgctgtttctgccctccgtaggagccatataccgcggaggcacaaacggaacctccaggg
tcgcctgcgccatcacgctctcgtacgagggaggaggagaggaagacaccaccgcgcgcc
tcatctctaacaaggaagagaacgcacgctATGGCCTTGGTGAgttttattttgcattca
aaacatccgtcgccccagtctgggctgcagatgcgcgaacgggttggccccaccgctccc
gcccaagtccaacacgctgctatcgtcggccgagtcctcgtcgtcccacaccaggccccg
ctgccggtcgtgacgctgtcgccgcggcgcgggcgcaggttccctatggtcctgagcgta
ggttttccagcggttcagtttgtccaccagactctctatcccgttattgaccatggcgtt
cttgacccgcggcggctgcagcagcgagtcgttcaggtactcgtcctcgcccagcaagcg
cggccggctcaccctgccgctgttcaccgagcccggcaagctatgcaaactccctaagct
aggaaaggggctccgacccaccgcgccctcgctcgcgggcgtgcgcaccgcctcctggcg
cttttgcaaggtcggtgagaacaccgcgctgtccacgtcgtcccacaaaaacccgtcgtt
ggggtcaggcatgtcgtactcgcccgtgtagaaccccggcggcgggagccagtgcgggtt
caagatggcattggtaaagtagtccgagttcatggacgccgcgcggtgcaggtagtccat
cagcttattaataaacggccggttggcggcgtacatgctaggttccatgttgcgcgcggt
catgtccagcgcggcgctgggggtggccccctcctgcatcaggaacagccctacgctctg
ctgcacatatctcaggatgcgctcctcctcggccgacagcgcgtactgcgccgggatctt
ctgctgtctattggtcagcaagaagttcagggtggccctcagactgtcggtgtcgttctg
acccagcgcgcggctcacgctagtgatctcctggaaggtctgctcatccacctgcgcctg
gcctatggcctcgcggtacagcgtcagcaggtgacccaggtacgagttgcggttcacgct
gccactgtcggtgaagggcgcgatcagcagcagcagcagccgcgagttgggcgtcagcaa
gctgctcaccgtcgaccggtcgcccacgggcgcctgcacgccccacagcccgcgcaggtt
cttgaaagcctgactcaggttcaccgtctgcaggccctgtctgctcgtctggaaaaagta
gtccgggcccgactggtacacctcgctctggggcacctcggtcaccatcagccgcagcgc
gcttataaagttggtataatcatcctgcccgcgcggcacgttcgccggctgcgtcgccag
gaaggcgttcagcgccaccagcgaacccaggccctcgttcttgaaccgctcgcgctgcgc
cacggcctcgcgcacgtccgtcaccagccggtccaggttggactgcacgtttgtgctgtt
gtagcggcccacgcgctccagcagggcgttgtacactagcccggcctcgtcgggacggat
ggccttgttctccgccagcgcgttcacgatcgccagcaccttctcgtgcgtggggttggt
ccgagaaggaaccaccgcctccagaatggccgagagtctgttggcctgcggctgttgtct
aaaggactcggggttgcgggtcgtcagggccatgatgcgttgcatcgcggcctcccagtc
gtccgatgctagaccggacggctggctttgcagcgccgcccttatggcggggtccggggc
ttgctgcatctaaaaacacatcacggaggcgtcagtaccccgcaacgggtgcatcctcct
cctcttcctcttcctcatccaagtcctctggaccgtaggcggcctccaaggcgcgtcggc
tcggctgccaatgcaggtccgcccccatgtcaaagtaggactcctcaccgccggtggcgc
ctcctaccagcgcccggcgcagactcagcatcagctcgcggtcgctcagctcgcgccgcc
ggcttgtgctcacggccttgtggatgcggtcgttgcggtacacgcccaggtcgtcgctca
gcgtcagcaccttgagcgccatgcgcatgtaaaagctgtctatcttcacctccttgtcta
tgggcacatacggcgtcttgtaaatcttgcgcgcgtaaaacttgcccaggctcagcaccg
agtagttgatcgccgccaccttctcggccaggctcaggctgcgctcctgcactacgatgc
tctgcaagatgttaatcagctccagcagccagcgaccctcgggctcggcgatgttcagca
gtgcctccctgaacgcctcgttgtccctgctgtgctgcaccaccaggaacagctgtgccg
tcagaggcttgctgtccgggttctgcacgatggcctccgccaggtcccacaggtgcatca
ggcccagggccacctcctcgcgcgcgatcagggtgcgcacgtggttgttgaaactctttt
ggaagttgcgctcctgcttcaccgtctgctcgtaggccgtcaccaggttggccgccgcca
cgtgcgcgcgcgcggggctgatccccgtctgctcgttcggctcgaaatcctcgtcgcgca
gcacgcgctggcggtccaggccctcgcgcagctccctgcccgcccgaaaccggcagtcgc
gcatctcctcgggctcctccccgctgcggtccctgaacaggttctgcgcaggcacgtacg
ccgggcgcacgtccttctgcagctgcacgcggggatgtcgctccggggacggcgccccca
gtctcgccagcccttcgccctcttccaagtccatctctgtctgtggctgtggctggctag
cgccggcgcctgctacggccgcggtcgcggtggtcgccgggggggtgggacgcatttggc
gcaggacgggatgcatctggcaaaaagaaaaaagggggctcgctcccgtaactggagaag
tcggctggctgtgggtctttaaatcggcggggtgaccaagtcccgctcgccgcggccgtc
cttgaaccgggttctgccgcgactcaaccctggcgatgcttctccagactacgggcgcga
gccactacccggcagggttttcggccgctttcaagtctagcgactcccctcggccgacaa
aaagggctctccgccgtatcctggcggctatcgggcttgggtcgagacgggagtgccaat
accacgttagtcgcggctccagcctgattcgaggggactcgaaccggggtacacacgcgg
cctaacccgtttgcgttccgccaggctacggaggaagagcccgctcaaccgctttcgttt
ttgcctctagagcatcaatgactgcgcgcgtctcaccggccagaccgtgccgaccatgga
ctatttcctgcccctgcgcaacatctggaaccgcgtccgcgagttcccgcgcgcctccac
caccgccgccggcatcacctggatgtcccgctacctctacggctaccaccgactcatgct
tgaggacctggccccgggcgcgccggccacccagcgctggccgctctaccgccagccgcc
gccgcactttctagtcggataccagtacctcgtgcgcacctgcaacgactatgtcttcga
ctcgcgcgccttctcgcggctcaggtactccgaggtcgtgcaacccggcctgcagaccgt
caactggtcgcttatggccaactgcacttacaccatcaacacaggggcctaccaccgctt
cgtcgacatggacgacttccaggacaccctcacccgcgtgcaacaggccatcctcgccga
gcgcgtcgtcgccgacctggcgctcgtgcagccgttcaggggcgtcggggtcacccgcat
ggaagactccgcctccgccagtgatgacatcgagaggctcatgcatgactactacaagaa
cctgagccggtgtcagggccaggcctggggcatggccgagcggctccgcatccagcaagc
gggacccaaggacctggtcctcctcgccaccatccgccgcctcaaaaacgcctacttcaa
ttacatcatcagcaaccgcaattctaacagcgtccacagggctgctacgtgtttgagctt
accttgcgactgcgattggctagacgctttcctcgaaagattctccgatccggtcgatct
cgacgcgctcacgtgccctacaccgcaattgataagatgcattgtcagcgccctatcgct
gcccaacggggacccaccccattaccgggagatgaccggcggcgtcttcacgctgcgtcc
tcgcgaacggggtcgcgccgtcaccgaaaccatgcgtcgccgccgcggggagatgatcga
gcgcttcgtcgaccgtctcccggtgcgtcgccgtcgtcgtcgggccccgccaccaccacc
gcccccagaggaagaaatagaagaagaggtcgtcatggaagaagaggaagaggaggaggc
ccccggggatttcgagcgcgaggtgcgcgccaccatcgccgaactcatcaggctcctgga
agacgagctcacggtctcggcccgcaacgcccagtttttcaacttcgccgtggatttcta
cgaggccatggaaaggctggaggccattggcgacatcagcgaaatgcccctgcgccgctg
gattatgtacttcttcgtcaccgagcacatcgccaccaccctcaactacctcttccaacg
cctgcgcaactatgccgtcttcgcgcggcacgtggagctcaacctcgcgcaggtggtcat
gcgcgcgcgcgacgccgacggggacgtggtttacagccgcgtctggaacgagagcggcct
gggcgccttctcgcagctcatgggtcgcatctcgaatgaccttgccgccaccgtagagcg
cgcgggccgcggcgatctccaggaggaggaaatcgagcagttcatgtccgagatcgccta
ccaggacaactcgggcgacgtgcaagagatcctgcgtcaggccgccgtcaatgacgccga
gATTGATTCTGTTGAACTGTCTTTCAGGTTCAAAGTCACGGGGCCCGTGGTCTTCACGCA
AAGGCGGCAGATCCAGGATGTCAACCGCCGCGTCGTCGCGCACGCCAGCGCTCTCAGGGC
GCAGCACCGGGACCTGCCCGAGCGCCACGCCGACGTGCCTCTACCGCCACTGCCCGCGGG
GCCGGAACCGCCGCTGCCGCCGGGAGCGCGTCCGCGACACCGCTTCTAAAAGCGCACCGC
GGCACGGTCGTGGCCCCGCGCAGCTACGGGCTCATGCAATGCGTGGACACGACCACCAAC
TCACCCGTGGAGATCAAGTACCATCTGCATCTCAAGCACGCCCTCACCCGCCTCTACGAG
GTCAACCTCAGAACCCTGCCCCCGGACCTGGATCTCCGCGACACCATGGACAGCTCCCAA
CTGCGCGCCCTCGTTTTCGCTCTCCGCCCCCGCCGCGCCGAGATCTGGACCTGGCTCCCG
CGCGGGCTCGTCAGCCTCTCCGTCCTCGAGGAGCCCCAGGGTGAGTCCCACGCAGGCGAA
CATGAAAACCACCAGCCAGGGCCGCCACTCCTGAAGTTCCTCCTCAAGGGACGCGCTGTG
TATCTCGTGGATGAGGTACAGCCCGTGCAGCGCTGCGAGTACTGCGGACGCTTTTACAAG
CATCAGCACGAGTGCTCGGTTCGCCGGCGGGATTTCTACTTTCATCACATCAACAGCCAC
TCGACCAACTGGTGGCAGGAAATCCAGTTCTTCCCAATCGGCTCTCATCCTCGCACGGAG
CGGCTCTTTGTCACCTACGATGTAGAAACCTACACCTGGATGGGGTCCTTCGGCAAGCAG
CTCGTCCCCTTCATGCTGGTCATGAAATTCTCCGGGGACCCCGAGCTGGTCGCCCTCGCT
CGCGATCTCGCCGTGCGCTTACGCTGGGATCGCTGGGAGCGGGACCCCCTCACCTTCTAC
TGCGTCACCCCAGAAAAGATGGCCGTGGGCCAGCAGTTCCGCCTCTTTCGCGACGAGCTC
CAGACCCTCATGGCCCGCGAGCTCTGGGCTTCATTCATGCAAGCCAACCCACATCTCCAG
GAGTGGGCGCTCGAGCAGCACGGCCTGCAATGCCCCGAGGACCTCACCTACGAGGAACTC
AAAAAGCTGCCGCACATCAAAGGCCGCCCGCGATTCATGGAACTCTACATCGTCGGGCAC
AACATCAACGGCTTCGACGAGATCGTCCTCGCCGCCCAGGTCATCAACAACCGAGCCTCC
GTTCCGGGCCCTTTCCGCATCACCCGCAATTTCATGCCGCGGGCAGGCAAGATTCTCTTC
AATGACGTCACTTTCGCTCTGCCTAACCCCCTCTCGAAGAAGCGCACCGATTTCGAGCTC
TGGGAGCACGGCGGCTGCGACGACTCGGATTTCAAGTACCAGTTCTTGAAAGTCATGGTT
AGGGATACCTTCGCCCTGACGCACACCTCGCTCCGCAAGGCCGCTCAAGCTTACGCCCTC
CCCGTGGAGAAGGGCTGCTGTCCCTACAAGGCCGTGAACCATTTCTACATGCTGGGCTCT
TACCGTGCGGACGATCGAGGATTCCCGCTCCGGGAGTACTGGAAGGATGACGAGGAGTAC
GCCCTCAACCGCGCGCTGTGGGAGAAGAAAGAAGAGGCGGGTTATGACATCATCCGTGAA
ACGCTGGACTACTGCGCCATGGACGTCCTTGTCACCGCCGAGCTCGTTGCCAAGCTGCAA
GACTCCTACGCGCACTTCATCCGCGACTCGGTCCGCTTGCCCCACGCCCACTTTAACATC
TTCCAACGGCCCACCATCTCCTCCAACTCGCATGCCATCTTTCGCCAGATCGTCTTCCGC
GCCGAGCAGCCCCAGCGCACCAATCTCGGCCCCGCTTTCTTGGCCCCCTCGCACGAGTTG
TATGACTATGTGCGCGCCAGCATCCGCGGGGGGCGCTGTTATCCCACCTACATCGGCATC
CTCTCGGAGCCCATCTATGTCTACGACATCTGCGGCATGTACGCCTCCGCCCTCACGCAT
CCCATGCCCTGGGGTCCGCCCCTCAACCCCTACGAGCGAGCGCTGGCCGCCCGCGAGTGG
CAGATGGCCTTGGATGATGCATCCTCAAAAATCGATTATTTTGACAAGGAACTCTGTCCG
GGCATCTTCACCATCGATGCGGACCCCCCTGACGAGCATCTGCTTGATGTGCTGCCCCCG
TTCTGCTCGCGCAAGGGCGGACGCCTCTGCTGGACCAACGAGCCCCTGCGCGGCGAGGTG
GCCACCAGCGTGGACCTGGTCACCCTGCATAATCGCGGCTGGCGCGTCAGGATCGTGCCC
GACGAGCGCACCACCGTCTTCCCAGAATGGAAGTGTGTCGCGCGCGAGTATGTCCAGCTC
AACATCGCGGCCAAGGAGCGCGCCGACCGTGACAAAAATCAGACCATGAGATCCATCGCC
AAGCTTCTCTCCAACGCCCTCTATGGCTCCTTTGCCACCAAGCTTGACAATAAAAAAATA
GTCTTTTCTGACCAGATGGATGAAAGTCTCCTAAAAAGCATTGCGGCAGGGCAGGCCAAC
ATCAAATCCTCCTCGTTTCTAGAAACTGACAACCTGAGTGCCGAGGTCATGCCCGCTCTC
GAGAGGGAATACCTACCCCAACAGCTGGCGCTCGTGGACAGCGACGCGGAAGAGAGTGAG
GACGAGCACAGACCCGCCCCCTTTTATACCCCCCCGTCGGGGACCCCCGGTCACGTGGCC
TACACCTACAAGCCAATCACCTTCTTGGATGCGGAGGAGGGGGACATGTGTCTGCACACG
GTGGAAAAGGTGGACCCCCTGGTGGACAACGACCGCTACCCCTCGCACGTGGCCTCCTTT
GTCTTGGCGTGGACGCGCGCCTTTGTCTCAGAGTGGTCCGAGTTTCTCTACGAGGAGGAC
CGCGGGACGCCCCTGCAGGACAGGCCAATCAAGTCCGTCTACGGGGACACAGACAGCCTG
TTTGTCACCGAACGCGGACACAGACTCATGGAGACGCGAGGTAAGAAGCGCATCAAAAAG
AACGGGGGAAAACTGGTTTTTGACCCCGAGCAGCCCGAGCTCACCTGGCTCGTCGAGTGC
GAGACCGTCTGCGCCCACTGCGGAGCGGACGCCTTCGCTCCCGAGTCCGTCTTTCTCGCA
CCCAAGCTCTACGCCCTGCAATCCCTCCTCTGTCCCGCCTGCGGGCGCTCTTCCAAAGGC
AAGCTCCGTGCCAAGGGCCACGCCGCCGAGGCCCTTAACTACAAGCTCATGGTCAACTGC
TATCTCGCCGACGCGCAGGGCGAAGACCGTGCCCGTTTCAGCACCAGCAGGATGAGTCTC
AAGCGCACCCTTGCAAGCGCCCAGCCCGGGGCCCACCCCTTCACCGTGACGGAGACCACC
CTCACTCGGACCCTGAGACCCTGGAAGGACATGACGCTGGCCGCGCTGGACGCCCATCGT
CTCGTGCCCTACAGTCGCAGTCGTCCCAACCCCCGAAACGAGGAAGTCTGCTGGATCGAG
ATGCCGTAGagcacgtcaccgagctatgggaccgcctggagctcctctcgcagacccttg
ccaagatgcccatggccgacgggctcaagcccctgaaaaactttgcttccctgcaagagc
tgctctcgctgggcggggaccgcctcctcggcgagctcg

Length = 1192

Score =  88.6 bits (187), Expect(2) = 0.0
Identities = 40/77 (51%), Positives = 47/77 (61%)
Frame = -2

Query: 8495  VQSHGARGLHAKAADPGCQPPRRRARQRSQGAAPGPARAPRRRASTATARGAGTAAAAGS 8316
             VQ+HGA   H +A DPG QPPR RAR+ SQGA P P RA RRRA+ + A GA  A+ A  
Sbjct: 4     VQAHGAGSFHPEATDPGRQPPRCRARKSSQGAVPEPTRARRRRATASHAAGARAASTARR 63

Query: 8315  ASATPLLKAHRGTVVAP 8265
             A + PLL     T   P
Sbjct: 64    APSPPLLNMQEATPPPP 80

Score =  70.7 bits (148), Expect(4) = 0.0
Identities = 32/62 (51%), Positives = 40/62 (64%)
Frame = -2

Query: 8120  TMDSSQLRALVFALRPRRAEIWTWLPRGLVSLSVLEEPQGESHAGEHENHQPGPPLLKFL 7941
             T+DSS LRALV  LRP RAE+WT LPRGLVS++ +E   G++ A      +   P L F 
Sbjct: 143   TLDSSGLRALVLELRPSRAEVWTCLPRGLVSMTTIETEDGQADADNIVESEVKAPGLNFP 202

Query: 7940  LK 7935
             LK
Sbjct: 203   LK 204

Score =  1110 bits (2418), Expect(4) = 0.0
Identities = 435/516 (84%), Positives = 468/516 (90%)
Frame = -2

Query: 7952  LKFLLKGRAVYLVDEVQPVQRCEYCGRFYKHQHECSVRRRDFYFHHINSHSTNWWQEIQF 7773
             LKFL+KG  V L+ EV PVQRCEYCGR YKH+HECS RRRDFYFHHINSHS+NWWQEIQF
Sbjct: 203   LKFLVKGSQVQLIHEVHPVQRCEYCGRLYKHKHECSARRRDFYFHHINSHSSNWWQEIQF 262

Query: 7772  FPIGSHPRTERLFVTYDVETYTWMGSFGKQLVPFMLVMKFSGDPELVALARDLAVRLRWD 7593
             FPIGSHPRTERLF+TYDVETYTWMGSFGKQL+PFMLVMK SGD  LV +A DLA++L+WD
Sbjct: 263   FPIGSHPRTERLFLTYDVETYTWMGSFGKQLIPFMLVMKLSGDERLVNIAYDLAMKLKWD 322

Query: 7592  RWERDPLTFYCVTPEKMAVGQQFRLFRDELQTLMARELWASFMQANPHLQEWALEQHGLQ 7413
             RW++DP TFYCVTPEKMAVGQ FR +RD+LQT +A +LW+SF+ ANPHL EWALE + L 
Sbjct: 323   RWQQDPKTFYCVTPEKMAVGQHFRQYRDQLQTALAVDLWSSFLNANPHLHEWALEHYALS 382

Query: 7412  CPEDLTYEELKKLPHIKGRPRFMELYIVGHNINGFDEIVLAAQVINNRASVPGPFRITRN 7233
              P DLT+EELKKLPH+KG PRF+ELYIVGHNINGFDEIVLAAQVINNRA VP PFRITRN
Sbjct: 383   DPTDLTFEELKKLPHVKGTPRFIELYIVGHNINGFDEIVLAAQVINNRAKVPQPFRITRN 442

Query: 7232  FMPRAGKILFNDVTFALPNPLSKKRTDFELWEHGGCDDSDFKYQFLKVMVRDTFALTHTS 7053
             FMPRAGKILFNDVTFALPNP  KKR DF+LWE G C+D DFKYQFLKVMVRDTFALTHTS
Sbjct: 443   FMPRAGKILFNDVTFALPNPAYKKRVDFQLWEQGACNDIDFKYQFLKVMVRDTFALTHTS 502

Query: 7052  LRKAAQAYALPVEKGCCPYKAVNHFYMLGSYRADDRGFPLREYWKDDEEYALNRALWEKK 6873
             LRKAAQAY+LPVEKGCCPYKAVN FYMLGSYRAD  GFPL EYWKD EEY LNR LWEKK
Sbjct: 503   LRKAAQAYSLPVEKGCCPYKAVNQFYMLGSYRADKDGFPLEEYWKDREEYLLNRELWEKK 562

Query: 6872  EEAGYDIIRETLDYCAMDVLVTAELVAKLQDSYAHFIRDSVRLPHAHFNIFQRPTISSNS 6693
              + GYDII+ETLDYCA+DVLVTAELVAKLQ+SYAHF+RDSV LPHAHFNIFQRPTISSNS
Sbjct: 563   NQPGYDIIQETLDYCALDVLVTAELVAKLQESYAHFVRDSVGLPHAHFNIFQRPTISSNS 622

Query: 6692  HAIFRQIVFRAEQPQRTNLGPAFLAPSHELYDYVRASIRGGRCYPTYIGILSEPIYVYDI 6513
             HAIFRQIV+RAE+P RTNLGP  LAPSHELYDYVRASIRGGRCYPTYIGIL EP+YVYDI
Sbjct: 623   HAIFRQIVYRAEKPNRTNLGPGLLAPSHELYDYVRASIRGGRCYPTYIGILEEPLYVYDI 682

Query: 6512  CGMYASALTHPMPWGPPLNPYERALAAREWQMALDD 6405
             CGMYASALTHPMPWG PLNPYERALAAREWQMALDD
Sbjct: 683   CGMYASALTHPMPWGTPLNPYERALAAREWQMALDD 718

Score =   447 bits (971), Expect(4) = 0.0
Identities = 182/210 (86%), Positives = 195/210 (92%)
Frame = -2

Query: 6407  DASSKIDYFDKELCPGIFTIDADPPDEHLLDVLPPFCSRKGGRLCWTNEPLRGEVATSVD 6228
             D  + I YFDK+L PGIFT+DADPPDE +LD LPPFCSRKGGRLCWTNEPLRGEVATSVD
Sbjct: 717   DDPAHISYFDKDLLPGIFTMDADPPDELMLDPLPPFCSRKGGRLCWTNEPLRGEVATSVD 776

Query: 6227  LVTLHNRGWRVRIVPDERTTVFPEWKCVAREYVQLNIAAKERADRDKNQTMRSIAKLLSN 6048
             L+TLHNRGWRVRIVPDE TT+FPEWKC+AREYVQLNIAAKERAD+DKNQTMRSIAKLLSN
Sbjct: 777   LITLHNRGWRVRIVPDELTTIFPEWKCLAREYVQLNIAAKERADKDKNQTMRSIAKLLSN 836

Query: 6047  ALYGSFATKLDNKKIVFSDQMDESLLKSIAAGQANIKSSSFLETDNLSAEVMPALEREYL 5868
             ALYGSFATKLDNKKIVFSDQMDESL+K I+ G  NIKSSSFLETDNLSAEVMPA EREYL
Sbjct: 837   ALYGSFATKLDNKKIVFSDQMDESLMKGISTGTVNIKSSSFLETDNLSAEVMPAFEREYL 896

Query: 5867  PQQLALVDSDAEESEDEHRPAPFYTPPSGT 5778
             PQQLAL+DSD E+SEDE RPAPFYTPP+GT
Sbjct: 897   PQQLALLDSDPEDSEDEQRPAPFYTPPAGT 926

Score =   605 bits (1316), Expect(2) = 0.0
Identities = 240/285 (84%), Positives = 261/285 (91%)
Frame = -2

Query: 5831  ESEDEHRPAPFYTPPSGTPGHVAYTYKPITFLDAEEGDMCLHTVEKVDPLVDNDRYPSHV 5652
             E  ++ +    +  P    GHVAYTYKPITFLD EEGDMCLHTVEKVDPLVDNDRYPSHV
Sbjct: 908   EDSEDEQRPAPFYTPPAGTGHVAYTYKPITFLDVEEGDMCLHTVEKVDPLVDNDRYPSHV 967

Query: 5651  ASFVLAWTRAFVSEWSEFLYEEDRGTPLQDRPIKSVYGDTDSLFVTERGHRLMETRGKKR 5472
             ASFVLAWTRAFVSEWS FLYEEDRGTPL+DRPIKSVYGDTDSLFVT+RGH LMET+GKKR
Sbjct: 968   ASFVLAWTRAFVSEWSGFLYEEDRGTPLEDRPIKSVYGDTDSLFVTQRGHELMETKGKKR 1027

Query: 5471  IKKNGGKLVFDPEQPELTWLVECETVCAHCGADAFAPESVFLAPKLYALQSLLCPACGRS 5292
             IKK+GGKLVFDP++P+LTWLVECET+CA CGADA++PES+FLAPKLYAL+ L CPAC ++
Sbjct: 1028  IKKHGGKLVFDPDEPDLTWLVECETICASCGADAYSPESIFLAPKLYALKCLYCPACQKT 1087

Query: 5291  SKGKLRAKGHAAEALNYKLMVNCYLADAQGEDRARFSTSRMSLKRTLASAQPGAHPFTVT 5112
             SKGKLRAKGHAAEALNY+LMVNCY+AD QG DR RFSTSRMSLKRTLASAQPGAHPFTVT
Sbjct: 1088  SKGKLRAKGHAAEALNYELMVNCYMADMQGADRQRFSTSRMSLKRTLASAQPGAHPFTVT 1147

Query: 5111  ETTLTRTLRPWKDMTLAALDAHRLVPYSRSRPNPRNEEVCWIEMP 4977
             ETTLTRTLRPWKD TLAALDAHRL+PYSRSRPNPRNEEVCWIEMP
Sbjct: 1148  ETTLTRTLRPWKDRTLAALDAHRLIPYSRSRPNPRNEEVCWIEMP 1192


========================================================================================================================

gene_id            %id    %sim   %cov   %t5   %gap  %t3   start..stop      pep sz ref sz ref id            definition
64.20              73.0   87.8   85.0   14.8  0.0   0.2   22949..24961     670    826    AP_000278.1       L4 | hexon-assembly protein
                    could not find valid start codon

CLUSTAL 2.1 multiple sequence alignment


predicted       ------------------------------------------------------------
reference       METQPSLPTPLQAPSHLASSDEEEEQSLTAPPPSPATTTSTLEDEEVDAPQEIQAQDMKD
                                                                            

predicted       ------------------------------------------------------------
reference       EKAEEIEADIEQDPGYVTPAEHEEELRRFLEKDDDNRPEQQADGDQQKAGLGGHVADYLT
                                                                            

predicted       --GEEDVLLKHLQRQSLILRDALADRSETPLSVEELCRAYELNLFSPRVPPKRQPNGTCE
reference       GLGGEDVLLKHLARQSIIIK--LLDRSEVPISVEELSRAYELNLFSPRVPPKRQPNGTCE
                  * ******** ***:*::  * ****.*:*****.***********************

predicted       PNPRLNFYPVFAVPEALATYHIFFKNQKIPISCRANRTRADALLALGPGARIPDIASLEE
reference       PNPRLNFYPAFTVPEVLATYHIFFKNQKIPISCRANRTRADALFNLGPGACLPDITSLEE
                *********.*:***.***************************: ***** :***:****

predicted       VPKIFEGLGRDETRAANALKETAE-EEGYTSALVELEGDNARLAVLKRSVELTHFAYPAV
reference       VPKIFEGLGSDETRAANALQQGESGIDEHHSALVELEGDNARLAVLKRSIEVTHFAYPAV
                ********* *********::  .  : : *******************:*:********

predicted       NLPPKVMRRIMDQLIMPHIEALDESQEQ--RPENAQPVVSDEMLARWLGTRDPQALEQRR
reference       NLPPKVMSAVMDQILIKRASPLSENMQDPDASDEGKPVVSDEQLSRWLGTNSPLDLEERR
                *******  :***::: : ..*.*. ::   .::.:****** *:*****..*  **:**

predicted       KLMLAVVLVTLELECMRRFFTDPETLRKVEETLHYTFRHGFVRQACKISNVELTNLVSCL
reference       KLMMAVVLVTVEMECLRRFFTDPETLRKLEENLHYTFRHGFVRQACKISNVELTNLVSYM
                ***:******:*:**:************:**.************************** :

predicted       GILHENRLGQTVLHSTLKGEARRDYIRDCVFLFLCHTWQAAMGVWQQCLEDENLKELDKL
reference       GILHENRLGQSVLHTTLKGEARRDYIRDTVYLYLCHTWQTGMGVWQQCLEEQNLKELDKL
                **********:***:************* *:*:******:.*********::********

predicted       LARNLKKLWTGFDERTVASDLAEIVFPERLRQTLKGGLPDFMSQSMLQNYRTFILERSGM
reference       LQRSLKSLWTGFDERTVASDLADLIFPERLRTTLRNGLPDFMSQSMLNNFRSFILERSGI
                * *.**.***************:::****** **:.***********:*:*:*******:

predicted       LPATCNAFPSDFVPLSYRECPPPLWSHCYLLQLANYIAHHSDVIEDVSGEGLLECHCRCN
reference       LPATCCALPSDFVPLTYRECPPPLWSHCYLFRLANYLSYHSDVIEDVSGDGLLECHCRCN
                ***** *:*******:**************::****:::**********:**********

predicted       LCSPHRSLVCNPQLLSETQVIGTFELQGPQ---ESTAP---LKLTPGLWTSAYLRKFVPE
reference       LCSPHRSLVCNPQLLSETQIIGTFELQGPSGEGDGSSPGQSLKLTPGLWTSAYLRKFSPE
                *******************:*********.   :.::*   **************** **

predicted       DYYAHEIKFFEDQSRPQHADLTACVITQGAILAQLHAIQKSRQEFLLKKGRGVYLDPQTG
reference       DYHPYEIRFYEDQSQPPKAELSACVITQGAILAQLQAIQKSRQEFLLKKGNGVYLDPQTG
                **:.:**:*:****:* :*:*:*************:**************.*********

predicted       EVLNP------GLPQHAEEEAGAAS-GGDGRRMGQPGRG-GRMG------GGDRGGR-LG
reference       EELNTRFSQDVSAPRKQEVESAAAAPRGYGGRLGQSDRGDGRLGQPGRGGGGQPGGRQFG
                * **.      . *:: * *:.**:  * * *:**..** **:*      **: *** :*

predicted       ---RGGRGAGNRAARRRTIRAGS--PSG----HGYNLRSS--GQASS--
reference       GGRRGGRGGG-RSNRRQTVVLGSGDKQGHRQYHSYHLRSGSGGPAPSQQ
                   *****.* *: **:*:  **   .*    *.*:***.  * *.*

>64.22	22949	24961
gacttaaccacccacgagcaacccaaaatcgagcaggacctgggcttcgaagagccggct
cgtctaaaacccccacaggatgaacaggagcacgagcaagacgcaggccaggaggagacc
gacgctgggctcgagcatggctacctgggaGGAGAGGAGGATGTGCTGCTAAAACACCTG
CAGCGCCAGTCCCTCATCCTCCGGGACGCCCTGGCCGACCGGAGCGAAACCCCCCTCAGC
GTCGAGGAGCTGTGTCGGGCCTACGAGCTCAACCTCTTCTCGCCGCGCGTGCCCCCCAAA
CGCCAGCCCAACGGCACCTGCGAGCCCAACCCGCGTCTCAACTTCTATCCCGTCTTTGCG
GTCCCCGAGGCCCTTGCCACCTATCACATCTTTTTCAAGAACCAAAAGATCCCCATCTCC
TGTCGCGCCAATCGCACTCGCGCCGACGCGCTCCTCGCTCTGGGGCCCGGCGCGCGCATA
CCTGATATCGCTTCCCTGGAAGAGGTGCCCAAGATCTTCGAAGGGCTCGGTCGGGACGAG
ACGCGCGCGGCAAACGCTCTGAAAGAAACAGCAGAGGAAGAGGGTTACACTAGCGCCCTG
GTAGAGTTGGAAGGCGACAACGCCAGGCTGGCCGTGCTTAAGCGCAGCGTCGAGCTCACC
CATTTCGCCTACCCCGCCGTCAACCTCCCGCCCAAGGTCATGCGTCGCATCATGGATCAG
CTCATCATGCCCCACATCGAGGCCCTTGATGAAAGTCAGGAACAGCGCCCCGAGAACGCC
CAGCCCGTGGTCAGCGACGAGATGCTCGCGCGCTGGCTCGGGACCCGCGACCCCCAGGCC
CTGGAGCAGCGGCGCAAGCTCATGCTGGCCGTGGTCCTGGTCACCCTTGAGCTCGAATGC
ATGCGCCGCTTTTTTACCGACCCCGAGACCCTGCGCAAGGTCGAGGAGACCCTGCACTAC
ACTTTCAGACACGGTTTCGTCAGGCAGGCCTGCAAGATCTCCAACGTGGAGCTGACCAAC
CTGGTCTCCTGCCTGGGGATCCTACACGAGAACCGCTTGGGACAGACCGTGCTCCACTCT
ACCCTGAAGGGCGAGGCGCGGCGGGACTACATCCGCGACTGCGTCTTTCTCTTTCTCTGC
CACACATGGCAAGCGGCCATGGGCGTGTGGCAGCAGTGTCTCGAGGACGAGAACCTGAAG
GAGCTGGACAAGCTTCTTGCTAGAAACCTTAAAAAGCTGTGGACGGGCTTCGACGAGCGC
ACCGTCGCCTCGGACCTGGCCGAGATCGTCTTCCCCGAGCGCCTGAGGCAGACGCTGAAA
GGAGGGCTGCCCGACTTCATGAGCCAGAGCATGTTGCAAAACTACCGCACTTTCATTCTC
GAGCGATCTGGGATGCTGCCCGCCACCTGCAACGCCTTCCCCTCCGACTTTGTCCCGCTG
AGCTACCGCGAGTGTCCCCCGCCGCTGTGGAGCCACTGCTACCTCTTGCAGCTGGCCAAC
TACATTGCCCACCACTCGGATGTGATCGAGGACGTGAGCGGCGAGGGGCTGCTCGAGTGC
CACTGTCGCTGCAACCTATGCTCCCCGCACCGCTCCCTGGTCTGCAACCCCCAGCTACTG
AGCGAGACCCAGGTCATCGGTACCTTTGAGCTGCAAGGTCCGCAGGAGTCCACCGCTCCG
CTGAAACTCACGCCGGGGTTGTGGACTTCCGCGTACCTGCGCAAATTTGTACCCGAGGAC
TACTACGCCCATGAGATAAAGTTCTTCGAGGACCAATCGCGTCCGCAGCACGCGGATCTC
ACGGCCTGCGTCATCACCCAGGGCGCGATCCTCGCCCAATTGCACGCCATCCAAAAATCC
CGCCAAGAGTTTCTTCTGAAAAAGGGTAGAGGGGTCTACCTGGACCCCCAGACGGGCGAG
GTGCTCAACCCGGGTCTCCCCCAGCATGCCGAGGAAGAAGCAGGAGCCGCTAGTGGAGGA
GATGGAAGAAGAATGGGACAGCCAGGCAGAGGAGGACGAATGGGAGGAGGAGACAGAGGA
GGAAGACTTGGAAGAGGTGGAAGAGGAGCAGGCAACAGAGCAGCCCGTCGCCGCACCATC
CGCGCCGGCAGCCCCTCCGGTCACGGATACAACCTCCGCAGCTCCGGCCAAGCCTCCTCG
TAGatgggatcgagtgaagggtgacggtaagcacgagcgacagggctaccgatcatggag
ggcccacaaagccgcgatcatcgcctgcttgcaagactgcggggggaacatcgctttcgc
ccgccgctacctgctcttccaccgcggggtgaa

Length = 826

Score =  33.6 bits (67), Expect(6) = 0.0
Identities = 13/18 (72%), Positives = 16/18 (88%)
Frame = +2

Query: 22949 GEEDVLLKHLQRQSLILR 23002
             G EDVLLKHL RQS+I++
Sbjct: 123   GGEDVLLKHLARQSIIIK 140

Score =   254 bits (550), Expect(6) = 0.0
Identities = 104/119 (87%), Positives = 108/119 (90%)
Frame = +2

Query: 23009 LADRSETPLSVEELCRAYELNLFSPRVPPKRQPNGTCEPNPRLNFYPVFAVPEALATYHI 23188
             L DRSE P+SVEEL RAYELNLFSPRVPPKRQPNGTCEPNPRLNFYP F VPE LATYHI
Sbjct: 141   LLDRSEVPISVEELSRAYELNLFSPRVPPKRQPNGTCEPNPRLNFYPAFTVPEVLATYHI 200

Query: 23189 FFKNQKIPISCRANRTRADALLALGPGARIPDIASLEEVPKIFEGLGRDETRAANALKE 23365
             FFKNQKIPISCRANRTRADAL  LGPGA +PDI SLEEVPKIFEGLG DETRAANAL++
Sbjct: 201   FFKNQKIPISCRANRTRADALFNLGPGACLPDITSLEEVPKIFEGLGSDETRAANALQQ 259

Score =  99.1 bits (210), Expect(6) = 0.0
Identities = 40/57 (70%), Positives = 48/57 (84%)
Frame = +2

Query: 23390 SALVELEGDNARLAVLKRSVELTHFAYPAVNLPPKVMRRIMDQLIMPHIEALDESQE 23560
             SALVELEGDNARLAVLKRS+E+THFAYPAVNLPPKVM  +MDQ+++     L E+ +
Sbjct: 269   SALVELEGDNARLAVLKRSIEVTHFAYPAVNLPPKVMSAVMDQILIKRASPLSENMQ 325

Score =   632 bits (1374), Expect(6) = 0.0
Identities = 246/297 (82%), Positives = 277/297 (93%)
Frame = +2

Query: 23570 ENAQPVVSDEMLARWLGTRDPQALEQRRKLMLAVVLVTLELECMRRFFTDPETLRKVEET 23749
             +  +PVVSDE L+RWLGT  P  LE+RRKLM+AVVLVT+E+EC+RRFFTDPETLRK+EE 
Sbjct: 331   DEGKPVVSDEQLSRWLGTNSPLDLEERRKLMMAVVLVTVEMECLRRFFTDPETLRKLEEN 390

Query: 23750 LHYTFRHGFVRQACKISNVELTNLVSCLGILHENRLGQTVLHSTLKGEARRDYIRDCVFL 23929
             LHYTFRHGFVRQACKISNVELTNLVS +GILHENRLGQ+VLH+TLKGEARRDYIRD V+L
Sbjct: 391   LHYTFRHGFVRQACKISNVELTNLVSYMGILHENRLGQSVLHTTLKGEARRDYIRDTVYL 450

Query: 23930 FLCHTWQAAMGVWQQCLEDENLKELDKLLARNLKKLWTGFDERTVASDLAEIVFPERLRQ 24109
             +LCHTWQ  MGVWQQCLE++NLKELDKLL R+LK LWTGFDERTVASDLA+++FPERLR 
Sbjct: 451   YLCHTWQTGMGVWQQCLEEQNLKELDKLLQRSLKSLWTGFDERTVASDLADLIFPERLRT 510

Query: 24110 TLKGGLPDFMSQSMLQNYRTFILERSGMLPATCNAFPSDFVPLSYRECPPPLWSHCYLLQ 24289
             TL+ GLPDFMSQSML N+R+FILERSG+LPATC A PSDFVPL+YRECPPPLWSHCYL +
Sbjct: 511   TLRNGLPDFMSQSMLNNFRSFILERSGILPATCCALPSDFVPLTYRECPPPLWSHCYLFR 570

Query: 24290 LANYIAHHSDVIEDVSGEGLLECHCRCNLCSPHRSLVCNPQLLSETQVIGTFELQGP 24460
             LANY+++HSDVIEDVSG+GLLECHCRCNLCSPHRSLVCNPQLLSETQ+IGTFELQGP
Sbjct: 571   LANYLSYHSDVIEDVSGDGLLECHCRCNLCSPHRSLVCNPQLLSETQIIGTFELQGP 627

Score =   168 bits (362), Expect(6) = 0.0
Identities = 70/88 (79%), Positives = 77/88 (87%)
Frame = +2

Query: 24479 LKLTPGLWTSAYLRKFVPEDYYAHEIKFFEDQSRPQHADLTACVITQGAILAQLHAIQKS 24658
             LKLTPGLWTSAYLRKF PEDY+ +EI+F+EDQS+P  A+L+ACVITQGAILAQL AIQKS
Sbjct: 640   LKLTPGLWTSAYLRKFSPEDYHPYEIRFYEDQSQPPKAELSACVITQGAILAQLQAIQKS 699

Query: 24659 RQEFLLKKGRGVYLDPQTGEVLNPGLPQ 24742
             RQEFLLKKG GVYLDPQTGE LN    Q
Sbjct: 700   RQEFLLKKGNGVYLDPQTGEELNTRFSQ 727

Score =  43.2 bits (88), Expect(6) = 0.0
Identities = 21/47 (44%), Positives = 26/47 (55%)
Frame = +2

Query: 24788 RMGQPGRGGRMGGGDRGGRLGRGGRGAGNRAARRRTIRAGSPSGHGY 24928
             R+GQPGRGG    G R    GR G   G R+ RR+T+  GS    G+
Sbjct: 760   RLGQPGRGGGGQPGGRQFGGGRRGGRGGGRSNRRQTVVLGSGDKQGH 806


========================================================================================================================

gene_id            %id    %sim   %cov   %t5   %gap  %t3   start..stop      pep sz ref sz ref id            definition
64.22              49.0   61.8   100.0  0.0   0.0   0.0   24744..25016     174    245    AAW33173.1        L4-3 | splicing factor
                                                          25186..25437                                     
                    invalid splicing for intron  at 25017..25185

CLUSTAL 2.1 multiple sequence alignment


predicted       MPRKK-------QEPLVEEMEEEWDSQAEED--EWE---------EET--EEED--LEEV
reference       MSHRRGSKKLKVQLSPPEDMKEDWDSQAEEEMEDWDSQAEEVDSLEEDSLEEEDEEAEEV
                *.:::       * .  *:*:*:*******:  :*:         **   ****   ***

predicted       EEEQATEQPVAAPSAPAAPPVTDTTSAAPAK-----PPRRWDR---------VKGDGKHE
reference       EEATAAKQLSSAAETSKSPDSSTATISAPGRGAQRRPNSRWDETGRFPNPTTASKTGKKE
                **  *::*  :*..:. :*  : :* :**.:     *  ***.         ..  **:*

predicted       RQGYRSW-----------------------------------GGGLRIAANEPLTTRELR
reference       RQGYKSWPPTAVSKSRQPRQKNTAATTVTRKPAVRKSTTSAPGGGLRITANEPAQTRELR
                ****:**                                   ******:****  *****

predicted       NRIFPTLYAIFQQSRGQQQELKVKNRSLRSLTRSCLYHKNEDQLQRTLEDAEALFHKYCA
reference       NRIFPTLYAIFQQSRGQEQELKVKNRSLRSLTRSCLYHKSEDQLQRTLEDAEALFNKYCA
                *****************:*********************.***************:****

predicted       LTLKD
reference       LTLKE
                ****:

>64.24	24744	25437
atctcacggcctgcgtcatcacccagggcgcgatcctcgcccaattgcacgccatccaaa
aatcccgccaagagtttcttctgaaaaagggtagaggggtctacctggacccccagacgg
gcgaggtgctcaacccgggtctcccccagcATGCCGAGGAAGAAGCAGGAGCCGCTAGTG
GAGGAGATGGAAGAAGAATGGGACAGCCAGGCAGAGGAGGACGAATGGGAGGAGGAGACA
GAGGAGGAAGACTTGGAAGAGGTGGAAGAGGAGCAGGCAACAGAGCAGCCCGTCGCCGCA
CCATCCGCGCCGGCAGCCCCTCCGGTCACGGATACAACCTCCGCAGCTCCGGCCAAGCCT
CCTCGTAGATGGGATCGAGTGAAGGGTGACGGTAAGCACGAGCGACAGGGCTACCGATCA
TGGagggcccacaaagccgcgatcatcgcctgcttgcaagactgcggggggaacatcgct
ttcgcccgccgctacctgctcttccaccgcggggtgaacatcccccgcaacgtgttgcat
tactaccgtcaccttcacagctaagaaaaagcaagtcaaaggagtcgccggaGGAGGAGG
CCTGAGGATCGCGGCGAACGAGCCCTTGACCACCAGGGAGCTGAGGAACCGGATCTTCCC
CACTCTTTATGCCATTTTTCAGCAAAGTCGAGGTCAGCAGCAAGAGCTCAAAGTAAAAAA
CCGGTCTCTGCGCTCGCTCACCCGCAGTTGCTTGTACCACAAAAACGAAGATCAGCTGCA
GCGCACTCTCGAAGACGCCGAGGCTCTGTTCCACAAGTACTGCGCGCTGACTCTTAAAGA
CTAAggcgcgcccacccggaaaaaaggcgggaattacctcatcgccaccatgagcaagga
gattcccaccccttacatgtggagctatcagccccagatgggcctggccgcgggcgcctc
ccaggactactccacccgcatgaactggcttagt

Length = 245

Score =  47.8 bits (98), Expect(3) = 8e-63
Identities = 19/56 (33%), Positives = 34/56 (60%)
Frame = +3

Query: 24774 EEMEEEWDSQAEEDEWEEETEEEDLEEVEEEQATEQPVAAPSAPAAPPVTDTTSAA 24941
             E+M+E+WDSQAEE+  + +++ E+++ +EE+   E+   A     A      +SAA
Sbjct: 18    EDMKEDWDSQAEEEMEDWDSQAEEVDSLEEDSLEEEDEEAEEVEEATAAKQLSSAA 73

Score =  28.1 bits (55), Expect(3) = 8e-63
Identities = 9/11 (81%), Positives = 10/11 (90%)
Frame = +3

Query: 24984 GKHERQGYRSW 25016
             GK ERQGY+SW
Sbjct: 117   GKKERQGYKSW 127

Score =   186 bits (401), Expect(3) = 8e-63
Identities = 81/100 (81%), Positives = 87/100 (87%)
Frame = +1

Query: 25135 TTVTFTAKKKQVKGVAGGGGLRIAANEPLTTRELRNRIFPTLYAIFQQSRGQQQELKVKN 25314
             TTVT     ++    A GGGLRI ANEP  TRELRNRIFPTLYAIFQQSRGQ+QELKVKN
Sbjct: 146   TTVTRKPAVRKSTTSAPGGGLRITANEPAQTRELRNRIFPTLYAIFQQSRGQEQELKVKN 205

Query: 25315 RSLRSLTRSCLYHKNEDQLQRTLEDAEALFHKYCALTLKD 25434
             RSLRSLTRSCLYHK+EDQLQRTLEDAEALF+KYCALTLK+
Sbjct: 206   RSLRSLTRSCLYHKSEDQLQRTLEDAEALFNKYCALTLKE 245


========================================================================================================================

gene_id            %id    %sim   %cov   %t5   %gap  %t3   start..stop      pep sz ref sz ref id            definition
gi_9626553.18      37.6   49.4   100.0  0.0   0.0   0.0   24559..24747     133    234    AP_000552.1       L4-3 | splicing factor
                                                          25160..25372                                     
                    invalid splicing for intron  at 24748..25159

CLUSTAL 2.1 multiple sequence alignment


predicted       MPPK-GNKHPIAQRQSQQKLQKQWD---EEETWD-DSQAEEVS----------DEEAEEQ
reference       MSHRRGSKKLKVQLTPPEDMEEDWDSQAEEEMEDWDSQAEEVDSLEEDSLEEEDEEAEEV
                *. : *.*:  .*  . :.::::**   ***  * *******.          ****** 

predicted       MES-------------------------------------WDS-----------------
reference       EEATAAKQLSSAAETSKSPDSSTATISAPGRGVQRRPNSRWDETGRFPNPTTASKTAPTA
                 *:                                     **.                 

predicted       LDEE-----------------------------DL---EDVEEETQELRKRIFPTLYAIF
reference       VSKSRQPRQKKTAATTVTRKPAVRKSTTSAAGGGLRITANEPAQTRELRNRIFPTLYAIF
                :.:.                             .*    :   :*:***:**********

predicted       QQSRGQQLELKVKNRSLRSLTRSCLYHRSEDQLQRTLEDAEALFNKYCSVSLKD
reference       QQSRGQEQELKVKNRSLRSLTRSCLYHKSEDQLQRTLEDAEALFNKYCALTLKE
                ******: *******************:********************:::**:

>gi_9626553.21	24559	25372
gccaaattctggcccaattacaagctattcagcaggcgcgtcaggaatttcttttaaaaa
aaggacacggggtctatttggacccccaaaccggtgaagaacttaataccccgtcactct
ccgccgccgcttcgtgccgttcgcagaaacATGCCACCCAAGGGAAACAAGCATCCCATC
GCGCAACGGCAATCCCAGCAGAAACTACAAAAGCAGTGGGACGAGGAGGAGACGTGGGAC
GACAGCCAGGCAGAGGAAGTTTCAGACGAGGAGGCGGAGGAGCAGATGGAGAGCTGGGAC
AGCCTAGACGAGGAGGACCTAGAGGACGTGGAGGAAGAAaccatcgccagcgacaaggca
ccatctttcaaaaaacccgttcggagccaacctccgaaaactatcccgcccctgccaccg
caaccatgttcactgaaagccagccgtaggtgggacaccgtctccatcgccggatcgcca
acagccccagctggtaagcagcctaagcgcgcacgacggggatactgctcctggcgagcc
cataaaagcaatattgtcgcatgcctccagcactgccggggcaatatctcattcgcacgg
cgttacttgctttttcacgacggggtggcggttcctcgcaacgtcctctactattaccgt
catctctacagcccctacgaaacgtttggagaaaacacctcgagtgcgtaagacctcatc
cgccattgccacccgccaggattcgcccgccACGCAGGAGCTCAGAAAACGCATCTTTCC
GACGCTGTATGCTATTTTCCAGCAGAGCCGCGGTCAACAGCTGGAACTCAAAGTAAAAAA
CCGATCACTCCGTTCGCTCACCCGCAGCTGCTTGTATCACAGAAGTGAAGACCAACTGCA
GCGCACGCTGGAGGACGCCGAGGCACTGTTCAATAAATATTGCTCGGTGTCTCTTAAGGA
CTAAacacccgcgctttttttaggcgccaaattacgtcattgacattatgagcaaagaca
ttcccacgccttacatgtggagctatcagccgcaaatgggcctggcagctggagcttctc
aggattactccagtcgcatgaattggcttagtgc

Length = 234

Score =  32.7 bits (65), Expect(3) = 4e-43
Identities = 18/58 (31%), Positives = 30/58 (51%)
Frame = +1

Query: 24610 KLQKQWDEEETWDDSQAEEVSDEEAEEQMESWDSLDEEDLEDVEEETIASDKAPSFKK 24783
             K+Q    E+   D     E   E+ + Q E  DSL+E+ LE+ +EE    ++A + K+
Sbjct: 11    KVQLTPPEDMEEDWDSQAEEEMEDWDSQAEEVDSLEEDSLEEEDEEAEEVEEATAAKQ 68

Score =  17.6 bits (32), Expect(3) = 4e-43
Identities = 7/30 (23%), Positives = 12/30 (40%)
Frame = +1

Query: 24823 PPQPCSLKASRRWDTVSIAGSPTAPAGKQP 24912
             P +    + + RWD      +PT  +   P
Sbjct: 89    PGRGVQRRPNSRWDETGRFPNPTTASKTAP 118

Score =   150 bits (322), Expect(3) = 4e-43
Identities = 62/77 (80%), Positives = 70/77 (90%)
Frame = +2

Query: 25139 TRQDSPATQELRKRIFPTLYAIFQQSRGQQLELKVKNRSLRSLTRSCLYHRSEDQLQRTL 25318
             T  +   T+ELR RIFPTLYAIFQQSRGQ+ ELKVKNRSLRSLTRSCLYH+SEDQLQRTL
Sbjct: 158   TANEPAQTRELRNRIFPTLYAIFQQSRGQEQELKVKNRSLRSLTRSCLYHKSEDQLQRTL 217

Query: 25319 EDAEALFNKYCSVSLKD 25369
             EDAEALFNKYC+++LK+
Sbjct: 218   EDAEALFNKYCALTLKE 234


========================================================================================================================

gene_id            %id    %sim   %cov   %t5   %gap  %t3   start..stop      pep sz ref sz ref id            definition
gi_61602086.7      73.7   89.1   100.0  0.0   0.0   0.0   13078..13066     1195   1192   AP_000266.1       E2B | DNA polymerase
                                                          8276..4702                                       
                    stop codon embedded in CDS at 8271..8269
                    non-canonical splicing for intron at 13065..8277

CLUSTAL 2.1 multiple sequence alignment


predicted       MALVRHXFCGTLFQVQDPGAGGLHAETAHPGPQPPRRRPRQQSPGSSSTAAESSRKRATA
reference       MALV-----------QAHGAGSFHPEATDPGRQPPRCRARKSSQGAVPEPTRARRRRATA
                ****           *  ***.:*.*::.** **** *.*:.* *: . .:.: *:****

predicted       SAAPRRRAASTPRRSPS-----TSEIKPP-------RGTVVAPRGHGLLYAVDASSNTPL
reference       SHAAGARAASTARRAPSPPLLNMQEATPPPPPKRKNKGTVVAPKGHGTLQAIDISTNGPV
                * *.  *****.**:**      .* .**       :******:*** * *:* *:* *:

predicted       EIKYHVHLAHALTGLLKVNLQTLPADLSAAALDSLDSGQLRPLLQRLRPSVAEIWTCGTR
reference       EIKYHLNLPLALEKIMQVNLLTLPTNLTPQRLRTLDSSGLRALVLELRPSRAEVWTCLPR
                *****::*. **  :::*** ***::*:.  * :***. **.*: .**** **:*** .*

predicted       GVVVPTVVHPEKEGADADSHRQGEGDAAPPSPRLNFPLRFLVRGRKAHLIQEIQSVQRCD
reference       GLVSMTTIETEDGQADADNIVESEVKA----PGLNFPLKFLVKGSQVQLIHEVHPVQRCE
                *:*  *.:..*.  ****.  :.* .*    * *****:***:* :.:**:*::.****:

predicted       YCGRFYKHQHECSVRRRDFYFHHINTHSSNWWQEISFFPIGSHARTQRLFVTYDVETYTW
reference       YCGRLYKHKHECSARRRDFYFHHINSHSSNWWQEIQFFPIGSHPRTERLFLTYDVETYTW
                ****:***:****.***********:*********.*******.**:***:*********

predicted       MGSFGKQLVPFMLVMHVSGEETLVRQACELALELRWDVWNDRPCTFYVVTPEKMAVGKKF
reference       MGSFGKQLIPFMLVMKLSGDERLVNIAYDLAMKLKWDRWQQDPKTFYCVTPEKMAVGQHF
                ********:******::**:* **. * :**::*:** *:: * *** *********::*

predicted       REFRDRLQTLLALDLWSSFLAANPQLSDWARAELGLSSPDCLTYEELKKAPALKGQPRFI
reference       RQYRDQLQTALAVDLWSSFLNANPHLHEWALEHYALSDPTDLTFEELKKLPHVKGTPRFI
                *::**:*** **:******* ***:* :**  . .**.*  **:***** * :** ****

predicted       ELYIVGHNINGFDEIVLAAQVINNRSDVPGPFRISRNFMPRAGKILFNDVTFALPNPRQK
reference       ELYIVGHNINGFDEIVLAAQVINNRAKVPQPFRITRNFMPRAGKILFNDVTFALPNPAYK
                *************************:.** ****:**********************  *

predicted       KRTDFTLWEQGACDDTDFKHQYLKVMVRDTFALTHTSLRKAAQAYALPVEKGCCPYKAVN
reference       KRVDFQLWEQGACNDIDFKYQFLKVMVRDTFALTHTSLRKAAQAYSLPVEKGCCPYKAVN
                **.** *******:* ***:*:***********************:**************

predicted       EFYMLGSYRADEKGFPAEEYWKDREEYLLNRELWEKKQETAYNLVRETLDYCALDVLVTA
reference       QFYMLGSYRADKDGFPLEEYWKDREEYLLNRELWEKKNQPGYDIIQETLDYCALDVLVTA
                :**********:.*** ********************::..*::::**************

predicted       ALVDKLRESYAQFIQDSVGLPGANFNVFQRPTISSNSHAIFRQILYRAEKPHKTHLGDGL
reference       ELVAKLQESYAHFVRDSVGLPHAHFNIFQRPTISSNSHAIFRQIVYRAEKPNRTNLGPGL
                 ** **:****:*::****** *:**:*****************:******::*:** **

predicted       MAPSHEMYDYVRASIRGGRCYPTYIGVLREPLYVYDICGMYASALTHPMPWGPPLNPYER
reference       LAPSHELYDYVRASIRGGRCYPTYIGILEEPLYVYDICGMYASALTHPMPWGTPLNPYER
                :*****:*******************:*.***********************.*******

predicted       ALAVKKWEDALQDTDTEIDYFNKILLPGIFTIDADPPPANLLDPLPPFCSRKGGRLCWTN
reference       ALAAREWQMALDDP-AHISYFDKDLLPGIFTMDADPPDELMLDPLPPFCSRKGGRLCWTN
                ***.::*: **:*. :.*.**:* *******:*****   :*******************

predicted       EPLRGEVATSVDLITLHNRGWRVRILPDERTAVFPEWRCVAREYVQLNIAAKERADREKN
reference       EPLRGEVATSVDLITLHNRGWRVRIVPDELTTIFPEWKCLAREYVQLNIAAKERADKDKN
                *************************:*** *::****:*:****************::**

predicted       QTLRSIAKLLSNALYGSFATKLDNKKIVFSDQMDPSTIKSIAAGHVNIKSTSFVETDNLS
reference       QTMRSIAKLLSNALYGSFATKLDNKKIVFSDQMDESLMKGISTGTVNIKSSSFLETDNLS
                **:******************************* * :*.*::* *****:**:******

predicted       AEIMPAFERAYSPEQLALVHSDAEESDGESGHAPFYTPWGGAGHVTYTYKPITFVDAEED
reference       AEVMPAFEREYLPQQLALLDSDPEDSEDEQRPAPFYTPPAGTGHVAYTYKPITFLDVEEG
                **:****** * *:****:.**.*:*:.*.  ****** .*:***:********:*.**.

predicted       DLCLHTLEKVDPLIENDRYPSQIASFVLAWTRAFVSEWSQFLYAEDLGTPLEDRPLKSVY
reference       DMCLHTVEKVDPLVDNDRYPSHVASFVLAWTRAFVSEWSGFLYEEDRGTPLEDRPIKSVY
                *:****:******::******::**************** *** ** ********:****

predicted       GDTDSLFVTEAGHRLMETQGKKRIKKNGGNLVFDPAKPELTWLVECETVCAQCGADAYSP
reference       GDTDSLFVTQRGHELMETKGKKRIKKHGGKLVFDPDEPDLTWLVECETICASCGADAYSP
                *********: **.****:*******:**:***** :*:*********:**.********

predicted       ESVFLAPKLYALKCLHCTKCQHVSKGKLRAKGHAAESLSYDLMLRCYLADSQGDD-ARFS
reference       ESIFLAPKLYALKCLYCPACQKTSKGKLRAKGHAAEALNYELMVNCYMADMQGADRQRFS
                **:************:*. **:.*************:*.*:**:.**:** ** *  ***

predicted       TSRMSLKRTLASAQPGAHPFTVTETTLTRTLRPWKDRTLAALDAHRLVPYSESRPNPRNQ
reference       TSRMSLKRTLASAQPGAHPFTVTETTLTRTLRPWKDRTLAALDAHRLIPYSRSRPNPRNE
                ***********************************************:***.*******:

predicted       EVCWIEIP
reference       EVCWIEMP
                ******:*

>gi_61602086.6	13078	4702
cctccagcgtggccggcacgttcgctgatcccatcacgctttcgtaagaagggggcggac
cctcatacgccgccggcgtgactctcaccgctcttctcattctgccgcgccgaggaagaa
agagaggaagaaaggacacacgctgtggccATGGCTCTGGTAAgtttccgcgtctttttt
attagtagaggcgactggaacgccccttgggttgcaagtgagcaaaggggttggctccgc
tccctcccaggtccaacacgctactatcgtctgcggagtcgtccgggtcttctctctgac
gacgccagtgcggcggaaccagcggtcgcggctgactgtcctcccactcccgctgctcct
gggcgtaggtcttccaacgattcattttatccaccaagctttccaccccgttgttgggga
aatttttcttcctagccggccgcagcaaggggtcgttcaggtagtcgctctcccccggca
accgcgggcgcgttacccgaccactgctggcggaagacagactgggaaagggactctctc
ccctagaggccgcctccacgctggagagggggagctcgtctccgccctccttcttctgga
atcggcgattgcccggcgtgaaaatgctgtcggacacgtcgtcccaaagaaagccgtcgt
cggcttcgggcaggtcaaactcgccggtgtagaagccggacgggggcatccaatgcggat
tcaggatggcattggtgaagtactccccgttcatggcggccgcgcgatggaagtagtcca
tcagacggttaatgaacggccggtgggcggagtaaaaggacggttccatgttccgagccg
tcatgtctaaagccgtggaagcggtggcgccctcccgcatcaagtacagactcacggact
gctgcacgtatcgcagaatcctctcctcctcggcgcttaacgtaaactgggagggtattt
tttgcctccggttggttagcaaaaagttcaacgtggcttccaggctgccggtatcttcct
gacccagggcccggctcacgttagtgatctcctgatatgtgtgctcgtcgatctgagcct
gaccgatggcctcgcggtacaaagtgatgagatgacccaggtacgagtcacggctgatag
tgctactgttggtgaacggcgcgatcaagagcagcagcaggcgagtgttgggggtcagca
gactggagatggtggctcgatcgcccaccggggccttaacgccccacatgccttgcaagt
ttttaaaggcctgagtcaggttcaccgtttgcaagccctgtcgggacgtctggaagaagt
aatccggcccagactgatacacctcgctctggggcacctcggacaccagcagcctcagag
cgctgatgaagctcacgtagtcctcctgcccgcggggcacgttggccggctgcgtgctca
ggaaggcgttgagtgccaccagagagcccagattgctgtccctcagaaaccgctccttct
gagccagcgcctccttcacgtcggtggtgaggcgatccagattggtctgaacgttagtgc
tgttgtagcgcgccacccgttccagcagagcgttgtaaatcaagcccgcctcgtcgcggc
ggatggccttgctgtctaccagggcgttcacgatagtcaggactttctcgtgtgtggggt
tggtgcgggagggcaccaccgcttccaagatggccgaaaaacggttggcctggggttgct
gtctaaaagcctcggggttgcgggtagtcagcgccataatgcggtccatggccgccgccc
agtcatcggaggcggtcacgcccgaaggttgactctgcatggatgccaaaagtgcgggat
ccgcggtggccccgtccgccggccgctgcatctaaaacaacacctgcccggtcaggcttc
gtcctcgtactcgcctgcctcctccaaatcgtcccgatcctcctcgtcggggtagcccgc
cgcctccaaggcgcgcgcgctgggacgccactgcagatcggctcccatgtcgaagtaagc
ctcgcgctcctcgtccccggcgcccgccagcgccctctgcaggctgtgcatcagctccct
gtcgctcagctcccgccggcggctggcgctcaccgccttgtggatcttgtcgttacggta
cacgccgaggtcgtcgctcagcgtcagcaccttcagcgccatgcgcatgtaaaagctgtc
tatcttcacctccttgtctatgggcacgtaagggctcttgtagatcttgcgagcgtagaa
cttccccaggctctgcatcgaatagttaatggccgccaccttgtccgctaagctgaggcc
cctctcctgcaccacgatgctctgcaggatgttaatcagatccaagagccagcgaccctc
gggctccgcgatgttcaacatggcgtcgcggaacgtctcgttgtcgcggctgtgctgcac
gatcaggaacagctgggccgtcagaggtttgctggccgggttctgcacgtaggcctccac
gaagtcccacagatgcatcagcccgatggtcacctcctccctcgcgatcagggtcctcac
gtgattgttaaagctcttttggaagttgcgctcctcgttcaccgtctgctcgtacgcgct
caccaggttggccgccgagacgtgagcgcgggccgggctcaccccagaacgctcgtcggg
ctcgaaatcctccgccctcaggagccgctcccgatcgaagcccgccctcagctctctacc
cgcccgaaacctgcaatcgcgcatctcctccgcctcctgaccgctgcggtccctaaacag
gttctgcttcggcacaaaagcctgcctggcgtccctcacgagctgaaccctagggtgtct
ctctggggacggcgctcccagccgggccagcccctctccctcttccaggtctaaagccag
ctcctcctcctccctgtcaccgcctccgctcaggtttactgccgccgcggcggtggtggt
gggcgtctgaggtcgcatctgccgcagcaccggatgcatctacgaaaaaacaccaaaaga
ctcccctccgtattggggcggagcgtcgcggctgggtctcgacgcggacgtcgtggatgc
ggggccaggcgcatcgggagcggcggatccggccggtctcgaaccggggttccccgccgc
cgcacccttgcgactttaccccccgagctacggaagggagtcgatgaccgccctgtcttt
tttccatctagagcgtacaagattgcgcccgcctcacggggcagagcgtgcccaccatgg
agcgctttcgccccctgcgcaacatctggaaccgcgtccgcgaattcaccagggccgcga
ccacctcggccggcatcacctggctctcccgctacatctaccactaccatcgcctcatgc
tggacgacctgtcccccggcgcccccgccacagtcggctggcccctgtaccgagaaccgc
ctccccacttcctggttggctaccagtatctggtacgcacatgcaacgactacgtgttcg
agtcccgcgcctactcgcgcctcaagtacacggagatcacccaacccggcatgcaagtcg
tcaactggtccgtcatggccaactgcacctacaccatcaacacgggggcctatcaccgct
tcgtggacctggacgacttccagaccaccctcacgcagatccaacaggccgtgctggccg
agagggtcgtggccgacctagcgttgctgcagcccctgcgggggttcggctcgactcgca
tggcagacaggggagaagcagaggttccggtggagagactgatgcaagactactacaaag
acctgcgtcgctgtcagagcgaggcctggggcatggccgagcgcctgcgcattcaacagg
ccgggcccaaagacgtggtcctcctcgccaccatccgccgcctgaagaccgcctacttta
attacatcatcagcagcatcacctcccaactgcccgcggacgccccccagcggcccaccg
tcctcagcttaccttgcgactgcgattggatagacgctttcctagagaagttctcggatc
ccgtcgacctcgacgttctcagatccctgcacggagtgcctacgcagcaattgataaaat
gcatcgtcagcgccgtgtccctgcccgacggccctaaccacttaccctccctgcacgggg
gcgctctgcgcggcggcgtcttcgaactgcgacctcgcgaaaacggacgcgccgtcaccg
agaccatgcgtcgccggcgcggcgaaatgatcgagcgcttcgtggaccgcctgccggtca
gacgacgacgtcgccgccccgtccccgtcgcagagctgccggaggaacccgtgcccctgg
aagaggaggagccggaggaagaagcagaggcgcctcggggcgctttcgagcaggaggtgc
gcgacacggtcgccgatctcatccgcctcctgcaagaagaactcacggtggccgcccgca
actcccaatttttcaacttcgccgtcgacttctacgaggccatggagcgtctcgaagcca
tcggagacatcaacgagatgaccctgcggcgctggatcatgtacttcttcgtctgcgagc
acatcgccaccacgctcaactacctcttccagcgcctcagaaactacgccgtcttcgccc
gccacgtggaactcaacgtggcccaggtggtcatgcgagcgcgcgactccttcggaaacg
tggtgtacagccgcgtgtggaacgagaacggcctcaacgccttctctcaactcatgcgtc
gcatctccaacgacctggccgccaccgtggagcgagcgggccacggcgacctccgcgagg
aagaagtggagcagttcatggccgagatcgcctatcaagacaactcgggcgacgtacagg
agatcctcaggcaggccgccgttaacgatgcaGACATTGATTCTGTGGAACTCTCTTTCA
GGTTCAGGACCCGGGGGCCGGTGGTCTTCACGCAGAGACGGCACATCCAGGACCTCAACC
GCCGCGTCGTCGCCCACGCCAGCAGTCTCCGGGCTCGTCATCAACCGCTGCCGAATCCTC
ACGAAAACGTGCCACTGCCTCCGCTGCCCCCCGGCGCAGAGCCGCCTCTACCCCCCGGCG
CTCGCCCTCGACGAGTGAGATAAAACCTCCTCGGGGCACGGTGGTGGCCCCGCGCGGACA
CGGCCTCCTCTACGCCGTGGACGCCTCTTCCAACACCCCCCTGGAAATCAAGTACCATGT
GCACCTGGCTCACGCTCTTACCGGTCTTCTGAAAGTGAACTTGCAAACGCTTCCCGCCGA
CCTCAGCGCGGCCGCCCTCGACTCCCTGGACAGCGGGCAGCTGCGTCCCCTCCTGCAACG
CCTGCGCCCCTCCGTGGCGGAGATCTGGACTTGCGGCACCCGGGGCGTCGTCGTCCCCAC
CGTCGTCCACCCAGAGAAGGAGGGCGCAGACGCAGACTCCCACCGCCAAGGCGAAGGGGA
TGCCGCCCCACCAAGCCCCCGTCTCAACTTCCCCCTCCGGTTTCTGGTGCGCGGGCGAAA
AGCGCATCTCATTCAGGAGATACAGAGCGTGCAGCGCTGCGACTACTGCGGTCGCTTTTA
CAAACATCAGCACGAATGCTCTGTGCGCCGGCGGGACTTCTACTTTCACCACATCAACAC
CCATTCCTCCAACTGGTGGCAGGAGATCAGCTTCTTCCCGATCGGCTCCCACGCGCGCAC
CCAGCGGCTCTTTGTCACCTACGACGTAGAAACCTACACATGGATGGGCTCGTTCGGGAA
ACAGTTGGTACCCTTCATGCTGGTCATGCACGTCTCGGGCGAGGAGACCCTCGTTCGTCA
AGCCTGCGAGCTGGCCCTAGAGCTCCGATGGGACGTCTGGAACGACCGCCCCTGCACTTT
CTACGTGGTGACGCCGGAGAAAATGGCCGTGGGGAAAAAGTTTCGCGAGTTCCGCGACCG
CTTGCAAACTCTGCTAGCCCTTGACCTGTGGAGCTCTTTCCTCGCGGCTAACCCTCAGCT
CTCCGACTGGGCCCGGGCGGAGCTGGGTCTCTCCTCGCCGGACTGTCTCACCTACGAGGA
GTTGAAAAAAGCGCCGGCCCTCAAGGGACAGCCGCGCTTTATCGAACTTTACATCGTGGG
CCACAACATCAACGGCTTCGACGAGATCGTCCTGGCGGCGCAAGTCATCAACAACCGCTC
GGACGTGCCCGGACCCTTCAGGATCTCTCGCAACTTCATGCCCCGCGCCGGGAAAATCCT
CTTTAACGACGTCACATTCGCCCTCCCCAATCCCAGGCAGAAAAAGCGCACCGACTTCAC
GCTGTGGGAACAGGGCGCCTGCGACGACACGGACTTCAAACATCAGTACCTGAAAGTGAT
GGTGCGGGACACCTTCGCCCTCACCCACACCTCTCTCAGAAAGGCCGCTCAAGCGTACGC
CCTGCCGGTAGAAAAAGGCTGTTGTCCATACAAAGCCGTGAACGAATTTTACATGTTAGG
TTCTTACCGAGCGGACGAAAAAGGATTTCCCGCCGAAGAGTACTGGAAAGACCGCGAGGA
ATACCTCCTCAATCGCGAACTGTGGGAGAAAAAACAAGAGACGGCCTACAACCTGGTCCG
CGAGACGTTGGACTACTGCGCTCTCGACGTGCTGGTAACCGCAGCCCTGGTGGACAAGCT
CCGGGAATCCTACGCCCAGTTCATCCAAGACTCCGTGGGACTGCCCGGAGCCAACTTTAA
CGTCTTCCAACGCCCCACTATCTCTTCCAACTCCCACGCCATCTTCAGGCAGATCCTCTA
CCGGGCCGAAAAACCCCACAAGACCCACTTGGGAGACGGGCTCATGGCTCCCTCTCACGA
GATGTACGACTACGTGCGAGCCAGCATCCGCGGGGGGCGCTGTTACCCCACTTACATCGG
GGTGTTGAGGGAGCCCCTGTACGTGTACGACATCTGCGGCATGTACGCCTCGGCCCTGAC
CCACCCCATGCCCTGGGGACCGCCCCTGAATCCCTACGAAAGGGCCCTGGCGGTGAAGAA
GTGGGAAGACGCGTTGCAAGACACGGACACCGAAATCGATTATTTTAATAAAATTCTGCT
ACCCGGCATATTTACCATCGACGCCGACCCCCCGCCCGCCAACTTGCTAGATCCCCTGCC
TCCGTTCTGCTCCAGAAAAGGGGGGCGATTGTGTTGGACCAACGAGCCCCTCCGCGGGGA
GGTGGCCACCAGCGTGGACCTCATCACCCTGCACAACCGCGGCTGGCGCGTGCGCATCCT
GCCCGACGAGCGCACCGCCGTGTTCCCCGAGTGGCGGTGCGTGGCCCGCGAGTACGTGCA
ACTCAACATCGCCGCCAAGGAGAGGGCCGATCGGGAGAAAAATCAGACCCTGCGCTCCAT
CGCCAAGTTGCTTTCCAACGCCCTCTACGGGTCTTTCGCCACCAAACTTGACAATAAAAA
GATCGTGTTTTCTGATCAGATGGACCCCTCCACCATCAAAAGCATCGCCGCGGGGCACGT
GAATATCAAATCCACCTCGTTTGTAGAAACTGACAACTTGAGCGCCGAAATCATGCCGGC
TTTTGAGAGGGCCTACTCACCCGAACAGCTGGCTCTGGTCCACAGCGATGCGGAAGAAAG
TGACGGGGAGAGTGGGCACGCCCCCTTTTATACCCCTTGGGGGGGTGCGGGTCACGTGAC
CTACACTTACAAGCCAATCACCTTCGTGGACGCGGAGGAGGACGACCTGTGTCTGCACAC
CCTGGAAAAGGTGGACCCCCTCATTGAAAACGACAGATACCCCTCGCAGATCGCCTCCTT
CGTGTTAGCCTGGACCCGAGCCTTTGTCTCGGAGTGGTCCCAGTTCCTGTACGCGGAAGA
CCTCGGAACACCTTTGGAAGATCGCCCCCTCAAGTCGGTCTACGGGGATACCGACAGCCT
TTTTGTCACGGAAGCGGGACACAGACTCATGGAGACGCAAGGTAAGAAACGCATCAAAAA
AAATGGAGGCAACTTGGTTTTTGATCCCGCTAAACCCGAGCTCACGTGGCTGGTGGAGTG
CGAGACCGTCTGCGCTCAGTGCGGAGCCGACGCCTACTCGCCCGAGTCGGTCTTCCTGGC
CCCAAAACTCTACGCCCTCAAGTGTCTGCACTGCACCAAATGTCAGCACGTTTCCAAGGG
AAAGCTGCGCGCCAAGGGACACGCGGCCGAGTCCCTCAGCTACGACCTCATGCTTCGTTG
CTATCTGGCCGACTCACAGGGAGACGACGCCCGCTTCAGCACCAGCAGGATGAGCCTGAA
GCGCACCCTCGCAAGCGCCCAGCCCGGGGCTCATCCCTTCACCGTCACCGAGACCACCCT
CACCCGAACGCTGAGACCCTGGAAGGACAGAACCCTCGCGGCCCTGGACGCCCACCGGCT
GGTGCCCTACAGCGAAAGTCGGCCCAACCCCCGAAACCAAGAAGTCTGCTGGATCGAGAT
TCCATAGagcacgtcaccgagctctgggaccgactgtacttgcttcgtcagtcgcttgaa
aagatgcccatggccgacggcctgaaaccgctgaaacacttcaacagcctggaagaactc
ttatccctgggtggggagaggctcttgcaaaacttag

Length = 1192

Score =  36.3 bits (73), Expect = 8e-05
Identities = 19/62 (30%), Positives = 29/62 (46%)
Frame = -1

Query: 8848  SRGTGSSGSSATGTGRRRRRLTGRRSTKRSIISPRRRRMVSVTARPFSRGRSSKTPPRRA 9027
             + G GS    AT  GR+  R   R+S++ ++  P R R    TA   +  R++ T  R  
Sbjct: 6     AHGAGSFHPEATDPGRQPPRCRARKSSQGAVPEPTRARRRRATASHAAGARAASTARRAP 65

Query: 9028  PP 9033
              P
Sbjct: 66    SP 67

Score =   136 bits (292), Expect(4) = 0.0
Identities = 63/147 (42%), Positives = 91/147 (61%)
Frame = -2

Query: 8154  SSSTAAESSRKRATASAAPRRRAASTPRRSPSTSEIKPPRGTVVAPRGHGLLYAVDASSN 7975
             ++++ A  +R  +TA  AP     +    +P     +  +GTVVAP+GHG L A+D S+N
Sbjct: 47    ATASHAAGARAASTARRAPSPPLLNMQEATPPPPPKRKNKGTVVAPKGHGTLQAIDISTN 106

Query: 7974  TPLEIKYHVHLAHALTGLLKVNLQTLPADLSAAALDSLDSGQLRPLLQRLRPSVAEIWTC 7795
              P+EIKYH++L  AL  +++VNL TLP +L+   L +LDS  LR L+  LRPS AE+WTC
Sbjct: 107   GPVEIKYHLNLPLALEKIMQVNLLTLPTNLTPQRLRTLDSSGLRALVLELRPSRAEVWTC 166

Query: 7794  GTRGVVVPTVVHPEKEGADADSHRQGE 7714
               RG+V  T +  E   ADAD+  + E
Sbjct: 167   LPRGLVSMTTIETEDGQADADNIVESE 193

Score =  1048 bits (2281), Expect(4) = 0.0
Identities = 410/523 (78%), Positives = 463/523 (88%)
Frame = -2

Query: 7695  SPRLNFPLRFLVRGRKAHLIQEIQSVQRCDYCGRFYKHQHECSVRRRDFYFHHINTHSSN 7516
             +P LNFPL+FLV+G +  LI E+  VQRC+YCGR YKH+HECS RRRDFYFHHIN+HSSN
Sbjct: 196   APGLNFPLKFLVKGSQVQLIHEVHPVQRCEYCGRLYKHKHECSARRRDFYFHHINSHSSN 255

Query: 7515  WWQEISFFPIGSHARTQRLFVTYDVETYTWMGSFGKQLVPFMLVMHVSGEETLVRQACEL 7336
             WWQEI FFPIGSH RT+RLF+TYDVETYTWMGSFGKQL+PFMLVM +SG+E LV  A +L
Sbjct: 256   WWQEIQFFPIGSHPRTERLFLTYDVETYTWMGSFGKQLIPFMLVMKLSGDERLVNIAYDL 315

Query: 7335  ALELRWDVWNDRPCTFYVVTPEKMAVGKKFREFRDRLQTLLALDLWSSFLAANPQLSDWA 7156
             A++L+WD W   P TFY VTPEKMAVG+ FR++RD+LQT LA+DLWSSFL ANP L +WA
Sbjct: 316   AMKLKWDRWQQDPKTFYCVTPEKMAVGQHFRQYRDQLQTALAVDLWSSFLNANPHLHEWA 375

Query: 7155  RAELGLSSPDCLTYEELKKAPALKGQPRFIELYIVGHNINGFDEIVLAAQVINNRSDVPG 6976
                  LS P  LT+EELKK P +KG PRFIELYIVGHNINGFDEIVLAAQVINNR+ VP 
Sbjct: 376   LEHYALSDPTDLTFEELKKLPHVKGTPRFIELYIVGHNINGFDEIVLAAQVINNRAKVPQ 435

Query: 6975  PFRISRNFMPRAGKILFNDVTFALPNPRQKKRTDFTLWEQGACDDTDFKHQYLKVMVRDT 6796
             PFRI+RNFMPRAGKILFNDVTFALPNP  KKR DF LWEQGAC+D DFK+Q+LKVMVRDT
Sbjct: 436   PFRITRNFMPRAGKILFNDVTFALPNPAYKKRVDFQLWEQGACNDIDFKYQFLKVMVRDT 495

Query: 6795  FALTHTSLRKAAQAYALPVEKGCCPYKAVNEFYMLGSYRADEKGFPAEEYWKDREEYLLN 6616
             FALTHTSLRKAAQAY+LPVEKGCCPYKAVN+FYMLGSYRAD+ GFP EEYWKDREEYLLN
Sbjct: 496   FALTHTSLRKAAQAYSLPVEKGCCPYKAVNQFYMLGSYRADKDGFPLEEYWKDREEYLLN 555

Query: 6615  RELWEKKQETAYNLVRETLDYCALDVLVTAALVDKLRESYAQFIQDSVGLPGANFNVFQR 6436
             RELWEKK +  Y++++ETLDYCALDVLVTA LV KL+ESYA F++DSVGLP A+FN+FQR
Sbjct: 556   RELWEKKNQPGYDIIQETLDYCALDVLVTAELVAKLQESYAHFVRDSVGLPHAHFNIFQR 615

Query: 6435  PTISSNSHAIFRQILYRAEKPHKTHLGDGLMAPSHEMYDYVRASIRGGRCYPTYIGVLRE 6256
             PTISSNSHAIFRQI+YRAEKP++T+LG GL+APSHE+YDYVRASIRGGRCYPTYIG+L E
Sbjct: 616   PTISSNSHAIFRQIVYRAEKPNRTNLGPGLLAPSHELYDYVRASIRGGRCYPTYIGILEE 675

Query: 6255  PLYVYDICGMYASALTHPMPWGPPLNPYERALAVKKWEDALQD 6127
             PLYVYDICGMYASALTHPMPWG PLNPYERALA ++W+ AL D
Sbjct: 676   PLYVYDICGMYASALTHPMPWGTPLNPYERALAAREWQMALDD 718

Score =   801 bits (1743), Expect(4) = 0.0
Identities = 318/403 (78%), Positives = 357/403 (88%)
Frame = -2

Query: 6129  DTDTEIDYFNKILLPGIFTIDADPPPANLLDPLPPFCSRKGGRLCWTNEPLRGEVATSVD 5950
             D    I YF+K LLPGIFT+DADPP   +LDPLPPFCSRKGGRLCWTNEPLRGEVATSVD
Sbjct: 717   DDPAHISYFDKDLLPGIFTMDADPPDELMLDPLPPFCSRKGGRLCWTNEPLRGEVATSVD 776

Query: 5949  LITLHNRGWRVRILPDERTAVFPEWRCVAREYVQLNIAAKERADREKNQTLRSIAKLLSN 5770
             LITLHNRGWRVRI+PDE T +FPEW+C+AREYVQLNIAAKERAD++KNQT+RSIAKLLSN
Sbjct: 777   LITLHNRGWRVRIVPDELTTIFPEWKCLAREYVQLNIAAKERADKDKNQTMRSIAKLLSN 836

Query: 5769  ALYGSFATKLDNKKIVFSDQMDPSTIKSIAAGHVNIKSTSFVETDNLSAEIMPAFERAYS 5590
             ALYGSFATKLDNKKIVFSDQMD S +K I+ G VNIKS+SF+ETDNLSAE+MPAFER Y 
Sbjct: 837   ALYGSFATKLDNKKIVFSDQMDESLMKGISTGTVNIKSSSFLETDNLSAEVMPAFEREYL 896

Query: 5589  PEQLALVHSDAEESDGESGHAPFYTPWGGAGHVTYTYKPITFVDAEEDDLCLHTLEKVDP 5410
             P+QLAL+ SD E+S+ E   APFYTP  G GHV YTYKPITF+D EE D+CLHT+EKVDP
Sbjct: 897   PQQLALLDSDPEDSEDEQRPAPFYTPPAGTGHVAYTYKPITFLDVEEGDMCLHTVEKVDP 956

Query: 5409  LIENDRYPSQIASFVLAWTRAFVSEWSQFLYAEDLGTPLEDRPLKSVYGDTDSLFVTEAG 5230
             L++NDRYPS +ASFVLAWTRAFVSEWS FLY ED GTPLEDRP+KSVYGDTDSLFVT+ G
Sbjct: 957   LVDNDRYPSHVASFVLAWTRAFVSEWSGFLYEEDRGTPLEDRPIKSVYGDTDSLFVTQRG 1016

Query: 5229  HRLMETQGKKRIKKNGGNLVFDPAKPELTWLVECETVCAQCGADAYSPESVFLAPKLYAL 5050
             H LMET+GKKRIKK+GG LVFDP +P+LTWLVECET+CA CGADAYSPES+FLAPKLYAL
Sbjct: 1017  HELMETKGKKRIKKHGGKLVFDPDEPDLTWLVECETICASCGADAYSPESIFLAPKLYAL 1076

Query: 5049  KCLHCTKCQHVSKGKLRAKGHAAESLSYDLMLRCYLADSQGDD 4921
             KCL+C  CQ  SKGKLRAKGHAAE+L+Y+LM+ CY+AD QG D
Sbjct: 1077  KCLYCPACQKTSKGKLRAKGHAAEALNYELMVNCYMADMQGAD 1119

Score =   171 bits (367), Expect(4) = 0.0
Identities = 68/74 (91%), Positives = 71/74 (95%)
Frame = -2

Query: 4926  DDARFSTSRMSLKRTLASAQPGAHPFTVTETTLTRTLRPWKDRTLAALDAHRLVPYSESR 4747
             D  RFSTSRMSLKRTLASAQPGAHPFTVTETTLTRTLRPWKDRTLAALDAHRL+PYS SR
Sbjct: 1119  DRQRFSTSRMSLKRTLASAQPGAHPFTVTETTLTRTLRPWKDRTLAALDAHRLIPYSRSR 1178

Query: 4746  PNPRNQEVCWIEIP 4705
             PNPRN+EVCWIE+P
Sbjct: 1179  PNPRNEEVCWIEMP 1192


========================================================================================================================

gene_id            %id    %sim   %cov   %t5   %gap  %t3   start..stop      pep sz ref sz ref id            definition
gi_61602086.17     36.0   45.8   91.8   8.2   0.0   0.0   24479..24562     106    231    AP_000279.1       L4-3 | splicing factor
                                                          24975..25211                                     
                    invalid splicing for intron  at 24563..24974

CLUSTAL 2.1 multiple sequence alignment


predicted       -------------------M---WDSQAEEVSE-D---EEEMESW--DSLDEEEDE----
reference       MSQRRGSKKLKVQLPPPEDMEEDWDSQTEEMEDWDSQAEEEEDSLEEDSLEEEDEEAEEV
                                   *   ****:**:.: *   *** :*   ***:**::*    

predicted       ------------------------------------------------------------
reference       EEATAAKQLSSAAETSKATDSTTATISAPGRGAQHRPNSRWDETGRLPNATTASKTAPIT
                                                                            

predicted       -----------------------------------AKDPPATEELRKRIFPTLYAIFQQS
reference       ARKSRQKKTTAARTSSRKPAAVRKPTAGAGGLRITANEPAQTRELRNRIFPTLYAIFQQS
                                                   *::*. *.***:*************

predicted       RGQHPQRELKIKNRSFRSLTRSCLYHKREDQLQRTLDDAEALFSKYCSASLKD
reference       RGQ--EQELKVKNRSLRSLTRSCLYHKSEDQLQRTLEDAEALFNKYCALTLKE
                ***  ::***:****:*********** ********:******.***: :**:

>gi_61602086.22	24479	25211
agaccggcgaggaactcaacccgtccacactctccgtcgaagcagcccccccgagacatg
ccgcccaagggaaccgccaagcagctgatcgctcggcagagagcgaagaagcaagagctg
ctccagcagcaggtggaggacgaggaagagATGTGGGACAGCCAGGCAGAGGAGGTGTCA
GAGGACGAGGAGGAGATGGAAAGCTGGGACAGCCTAGACGAGGAGGAGGACGAGctttca
gaggaagaggcgaccgaagaaaaaccacctgcatccagcgcgccttctctgagccgacag
ccgaagccccggcccccgacgcccccggccggctcactcaaagccagccgtaggtgggac
gccaccgaatctccagcggcagcggcaacggcagcgggtaaggccaaacgcgagcggcgg
gggtattgctcctggcgggcccacaaaagcagtattgtgaactgcttgcaacactgcggg
ggaaacatctcctttgcccgacgctacctcctcttccatcacggtgtggccttccctcgc
aacgttctctattattaccgtcatctctacagcccctacgaaacgctcggagaaaaaagc
taaggcctcctccgccgcgaggaaaaactccgccgccgctgccgccGCCAAGGATCCACC
GGCCACCGAAGAGCTGAGAAAGCGCATCTTTCCCACTCTGTATGCTATCTTTCAGCAAAG
CCGCGGGCAGCACCCTCAGCGCGAACTGAAAATAAAAAACCGCTCCTTCCGCTCGCTCAC
CCGCAGCTGTCTGTACCACAAGAGAGAAGACCAGCTGCAGCGCACCCTGGACGACGCCGA
AGCACTGTTCAGCAAATACTGCTCAGCGTCTCTTAAAGACTAAaagacccgcgctttttc
cccctcggccgccaaaacccacgtcatcgccagcatgagcaaggagattcccacccccta
catgtggagctatcagccccagatgggcctggccgcgggggccgcccaggactactccag
caagatgaactgg

Length = 231

Score =  48.1 bits (99), Expect(4) = 1e-44
Identities = 24/67 (35%), Positives = 37/67 (55%)
Frame = +2

Query: 24422 RQRAKKQELLQQQVEDEEEMWDSQAEEVSEDEEEMESWDSLDEEEDELSEEEATEEKPPA 24601
             R+ +KK ++     ED EE WDSQ EE+ + + + E  +   EE+    E+E  EE   A
Sbjct: 4     RRGSKKLKVQLPPPEDMEEDWDSQTEEMEDWDSQAEEEEDSLEEDSLEEEDEEAEEVEEA 63

Query: 24602 SSAPSLS 24622
             ++A  LS
Sbjct: 64    TAAKQLS 70

Score =  19.9 bits (37), Expect(4) = 1e-44
Identities = 7/18 (38%), Positives = 14/18 (77%)
Frame = +3

Query: 24798 NTAGETSPLPDATSSSIT 24851
             ++A ETS   D+T+++I+
Sbjct: 70    SSAAETSKATDSTTATIS 87

Score =  60.2 bits (125), Expect(4) = 1e-44
Identities = 28/62 (45%), Positives = 33/62 (53%)
Frame = +3

Query: 24894 STAPTKRSEKKAKASSAARKNSAAAAAAKDPPATEELRKRIFPTLYAIFQQSRGQHPQRE 25073
             +TA    S K A               A +P  T ELR RIFPTLYAIFQQSRGQ  + +
Sbjct: 129   TTAARTSSRKPAAVRKPTAGAGGLRITANEPAQTRELRNRIFPTLYAIFQQSRGQEQELK 188

Query: 25074 LK 25079
             +K
Sbjct: 189   VK 190

Score =  95.9 bits (203), Expect(4) = 1e-44
Identities = 37/48 (77%), Positives = 45/48 (93%)
Frame = +3

Query: 25065 QRELKIKNRSFRSLTRSCLYHKREDQLQRTLDDAEALFSKYCSASLKD 25208
             ++ELK+KNRS RSLTRSCLYHK EDQLQRTL+DAEALF+KYC+ +LK+
Sbjct: 184   EQELKVKNRSLRSLTRSCLYHKSEDQLQRTLEDAEALFNKYCALTLKE 231


