========================================================================================================================

gene_id            %id    %sim   %cov   %t5   %gap  %t3   start..stop      pep sz ref sz ref id            definition
MF564037.1.1       96.6   96.6   100.0  0.0   0.0   0.0   1..468           252    261    CAB06706.1        RL1-ii | neurovirulence protein ICP34.5
                                                          566..856                                         
                    invalid splicing for intron  at 469..565

CLUSTAL 2.1 multiple sequence alignment


predicted       MSRRR-PRRRGPRRRPRPGAPAVPRP--------GALPTADSQMVPAYDSGTAVESAPAA
reference       MSRRRGPRRRGPRRRPRPGAPAVPRPGAPAVPRPGALPTADSQMVPAYDSGTAVESAPAA
                ***** ********************        **************************

predicted       SSLLRRWLLVPQADDSDDADYAGNDDAEWANSPPSEGGGKAPEAPHAAPAAACPPPPPRK
reference       SSLLRRWLLVPQADDSDDADYAGNDDAEWANSPPSEGGGKAPEAPHAAPAAACPPPPPRK
                ************************************************************

predicted       ERGPQRPLPPHLALRLRTTTEYLARLSLRRRRPPASPPADAPRGKVCFSPRVQVRHLVAW
reference       ERGPQRPLPPHLALRLRTTTEYLARLSLRRRRPPASPPADAPRGKVCFSPRVQVRHLVAW
                ************************************************************

predicted       ETAARLARRGSWARERADRDRFRRRVAAAEAVIGPCLEPEARARARARARAHEDGGPAEE
reference       ETAARLARRGSWARERADRDRFRRRVAAAEAVIGPCLEPEARARARARARAHEDGGPAEE
                ************************************************************

predicted       EEAAAAARGSSAAAGPGRRAV
reference       EEAAAAARGSSAAAGPGRRAV
                *********************

>MF564037.1.1	1	856
ATGTCCCGCCGGCGTCCCCGCCGCCGGGGTCCCCGGCGCCGGCCGCGCCCCGGCGCTCCA
GCCGTGCCGCGCCCCGGCGCGCTCCCAACCGCAGACTCCCAAATGGTCCCTGCGTACGAC
TCGGGAACCGCGGTCGAGAGCGCGCCGGCCGCGTCCTCGCTCCTGCGGCGCTGGCTGCTG
GTGCCCCAGGCGGACGACAGCGACGACGCGGACTACGCCGGCAACGACGACGCAGAGTGG
GCGAACAGCCCCCCGAGCGAGGGCGGGGGGAAGGCGCCGGAGGCCCCGCACGCCGCGCCT
GCCGCCGCCTGCCCCCCGCCGCCGCCGCGCAAGGAGCGCGGGCCGCAGCGCCCCCTTCCG
CCCCACCTGGCCCTACGGCTGCGCACCACGACGGAGTACCTGGCGCGCCTGAGCCTGCGC
CGGCGGCGGCCCCCCGCGTCCCCGCCCGCGGACGCGCCGCGCGGGAAGgtacgcctcccc
tccgaccccctgacgcccctccgaccccctgacgcccctccgaccccctgacgcccctcc
gacccccgtgtctccccgcccgcagGTGTGCTTCTCGCCGCGCGTGCAGGTGCGCCATCT
GGTGGCCTGGGAGACGGCCGCGCGCCTGGCCCGACGGGGGTCCTGGGCGCGCGAGCGGGC
CGACCGCGACCGGTTCCGGCGCCGCGTGGCGGCGGCCGAGGCGGTCATCGGACCGTGCCT
GGAGCCCGAGGCCCGAGCTCGGGCCCGAGCCCGAGCCCGGGCCCACGAAGACGGCGGACC
CGCGGAGGAGGAGGAGGCGGCGGCGGCGGCGCGCGGGTCCTCCGCCGCCGCGGGCCCGGG
CCGTCGGGCGGTCTAGggttgaaccggcgagggcggcctcggccggcggagccccggagc
tccgaaggtctgcgcgaggccgctctccgaagagacgatgggagccccgcgtatatatcc
gcgagggcccggcgccgccccgccgctccgcccgccccagggggcggcgccggccaaccg
cgcgccgccgcgcgggcccggactccgccccggcgaccgccccgcgccggcttcccggta
tggtaattagaaacttttaataggcggtcccggccgccatccccgcgcatggtaattagc
aacttttaatgggccg

Length = 261

Score =   358 bits (775), Expect(2) = e-105
Identities = 147/154 (95%), Positives = 147/154 (95%)
Frame = +1

Query: 10  RRPRRRGPRRRPRPGAPAVPRPGALPTADSQMVPAYDSGTAVESAPAASSLLRRWLLVPQ 189
           RR  R G    PRPGAPAVPRPGALPTADSQMVPAYDSGTAVESAPAASSLLRRWLLVPQ
Sbjct: 13  RRRPRPGAPAVPRPGAPAVPRPGALPTADSQMVPAYDSGTAVESAPAASSLLRRWLLVPQ 72

Query: 190 ADDSDDADYAGNDDAEWANSPPSEGGGKAPEAPHAAPAAACPPPPPRKERGPQRPLPPHL 369
           ADDSDDADYAGNDDAEWANSPPSEGGGKAPEAPHAAPAAACPPPPPRKERGPQRPLPPHL
Sbjct: 73  ADDSDDADYAGNDDAEWANSPPSEGGGKAPEAPHAAPAAACPPPPPRKERGPQRPLPPHL 132

Query: 370 ALRLRTTTEYLARLSLRRRRPPASPPADAPRGKV 471
           ALRLRTTTEYLARLSLRRRRPPASPPADAPRGKV
Sbjct: 133 ALRLRTTTEYLARLSLRRRRPPASPPADAPRGKV 166

------------------------------------------------------------
frameshifted or splicing from +1 to +2 between 232-760
   232 GCAGAGTGGGCGAACAGCCCCCCGAGCGAGGGCGGGGGGAAGGCGCCGGAGGCCCCGCAC 291   
   292 GCCGCGCCTGCCGCCGCCTGCCCCCCGCCGCCGCCGCGCAAGGAGCGCGGGCCGCAGCGC 351   
   352 CCCCTTCCGCCCCACCTGGCCCTACGGCTGCGCACCACGACGGAGTACCTGGCGCGCCTG 411   
   412 AGCCTGCGCCGGCGGCGGCCCCCCGCGTCCCCGCCCGCGGACGCGCCGCGCGGGAAGGTA 471   
   472 CGCCTCCCCTCCGACCCCCTGACGCCCCTCCGACCCCCTGACGCCCCTCCGACCCCCTGA 531   
   532 CGCCCCTCCGACCCCCGTGTCTCCCCGCCCGCAGGTGTGCTTCTCGCCGCGCGTGCAGGT 591   
   592 GCGCCATCTGGTGGCCTGGGAGACGGCCGCGCGCCTGGCCCGACGGGGGTCCTGGGCGCG 651   
   652 CGAGCGGGCCGACCGCGACCGGTTCCGGCGCCGCGTGGCGGCGGCCGAGGCGGTCATCGG 711   
   712 ACCGTGCCTGGAGCCCGAGGCCCGAGCTCGGGCCCGAGCCCGAGCCCGG            760   
 frame +1
   232  a -E--W--A--N--S--P--P--S--E--G--G--G--K--A--P--E--A--P--H- 291    |
   292 -A--A--P--A--A--A--C--P--P--P--P--P--R--K--E--R--G--P--Q--R- 351    |
   352 -P--L--P--P--H--L--A--L--R--L--R--T--T--T--E--Y--L--A--R--L- 411    |
   412 -S--L--R--R--R--R--P--P--A--S--P--P--A--D--A--P--R--G--K--V- 471    |
   472  r  l  p  s  d  p  l  t  p  l  r  p  p  d  a  p  p  t  p  *  531   
   532  r  p  s  d  p  r  v  s  p  p -A- g  v  l  l  a  a -R- a  g  591   
   592 -A- p  s  g  g  l  g  d  g  r  a  p  g  p  t  g  v  l  g  a  651   
   652  r  a  g -R- p  r  p  v  p  a  p  r  g  g  g  r  g  g  h  r  711   
   712  t  v  p  g  a  r  g  p  s  s  g  p  s  p  s  p              760   
 frame +2
   232   q  s  g  r  t  a  p  r  a  r  a  g  g  r  r  r  r  p  r  t 291   
   292   p  r  l  p  p  p  a  p  r  r  r  r  a  r  s -A- g  r  s  a 351   
   352   p  f  r  p  t  w  p  y  g  c  a  p  r  r  s  t  w  r  a  * 411   
   412   a  c  a  g  g  g  p  p  r -P- r  p  r  t  r  r  a  g  r  y 471   
   472   a  s  p  p -T- p  *  r  p  s  d  p  l  t  p  l -R- p -P- d 531   
   532  -A- p -P- t  p  v  s -P--R- p  q -V--C--F--S--P--R--V--Q--V 591    |
   592 --R--H--L--V--A--W--E--T--A--A--R--L--A--R--R--G--S--W--A--R 651    |
   652 --E--R--A--D--R--D--R--F--R--R--R--V--A--A--A--E--A--V--I--G 711    |
   712 --P--C--L--E--P--E--A--R--A--R--A--R--A--R--A--R-            760    |
 frame +3
   232    r  v  g  e  q  p  p  e  r  g  r  g  e  g  a  g  g  p  a   291   
   292 r  r  a  c  r  r  l  p  p  a  a  a -A- q  g -A- r  a -A--A-- 351   
   352 P- p  s -A- p -P- g -P- t  a  a  h  h  d -G- v  p  g  a  p   411   
   412 e -P- a  p -A- a  a  p -R- v  p  a  r  g  r -A- a  r  e  g   471   
   472 t  p  p  l  r -P- p  d  a -P- p  t  p  * -R- p  s  d  p  l   531   
   532 t -P- l  r  p  p  c  l  p  a  r  r  c  a  s  r -R- a  c -R-  591   
   592 c  a  i -W- w  p  g -R- r  p -R- a  w  p  d  g  g  p  g  r - 651   
   652 A- s  g  p  t  a  t  g  s  g  a  a  w -R- r  p  r -R- s  s   711   
   712 d -R--A- w  s  p  r  p  e  l  g  p  e  p  e  p               760   

reference sequence 87-230
EWANSPPSEGGGKAPEAPHAAPAAACPPPPPRKERGPQRPLPPHLALRLRTTTEYLARLS
LRRRRPPASPPADAPRGKVCFSPRVQVRHLVAWETAARLARRGSWARERADRDRFRRRVA
AAEAVIGPCLEPEARARARARARA
------------------------------------------------------------

Score =   237 bits (513), Expect(4) = 2e-79
Identities = 102/111 (91%), Positives = 104/111 (93%)
Frame = +2

Query: 521 RPPDAPPTPVSPRPQVCFSPRVQVRHLVAWETAARLARRGSWARERADRDRFRRRVAAAE 700
           R P A P   +PR +VCFSPRVQVRHLVAWETAARLARRGSWARERADRDRFRRRVAAAE
Sbjct: 151 RRPPASPPADAPRGKVCFSPRVQVRHLVAWETAARLARRGSWARERADRDRFRRRVAAAE 210

Query: 701 AVIGPCLEPEARARARARARAHEDGGPAEEEEAAAAARGSSAAAGPGRRAV 853
           AVIGPCLEPEARARARARARAHEDGGPAEEEEAAAAARGSSAAAGPGRRAV
Sbjct: 211 AVIGPCLEPEARARARARARAHEDGGPAEEEEAAAAARGSSAAAGPGRRAV 261


========================================================================================================================

gene_id            %id    %sim   %cov   %t5   %gap  %t3   start..stop      pep sz ref sz ref id            definition
MF564037.1.2       99.3   99.6   100.0  0.0   0.0   0.0   1780..1854       832    833    AEV91397.2        RL2 | ubiquitin E3 ligase ICP0
                                                          2265..2939                                       
                                                          3036..4784                                       
                    invalid splicing for intron  at 2940..3035

CLUSTAL 2.1 multiple sequence alignment


predicted       MEPRPGTSSRADPGPERPPRQTPGAPAAPHAWGMLNDMQWLASSDSEEETEVGISDDDLH
reference       MEPRPGTSSRADPGPERPPRQTPGTPAAPHAWGMLNDMQWLASSDSEEETEVGISDDDLH
                ************************:***********************************

predicted       RDSTSEAGSTDTEMFEAGLMDAATPPARPPAERQGSPTPADAQGSCGGGPVGEEEAEAGG
reference       RDSTSEAGSTDTEMFEAGLMDAATPPARPPAERQGSPTPADAQGSCGGGPVGEEEAEAGG
                ************************************************************

predicted       GGDVCAVCTDEIAPPLRCQSFPCLHPFCIPCMKTWIPLRNTCPLCNTPVAYLIVGVTASG
reference       GGDVCAVCTDEIAPPLRCQSFPCLHPFCIPCMKTWIPLRNTCPLCNTPVAYLIVGVTASG
                ************************************************************

predicted       SFSTIPIVNDPRTRVEAEAAVRSGTAVDFIWTGNPRTAPRSLSLGGHTVRALSPTPPWPG
reference       SFSTIPIVNDPRTRVEAEAAVRAGTAVDFIWTGNQRTAPRSLSLGGHTVRALSPTPPWPG
                **********************:*********** *************************

predicted       TDDEDDDLAD-DYVPPAPRRAPRRGGGGAGATRGTSQPAATRPAPPGAPRSSSSGGAPLR
reference       TDDEDDDLADVDYVPPAPRRAPRRGGGGAGATRGTSQPAATRPAPPGAPRSSSSGGAPLR
                ********** *************************************************

predicted       AGVGSGSGGGPAVAAVVPRVASLPPAAGGGRAQARRVGEDAAAAEGRTPPARQPRAAQEP
reference       AGVGSGSGGGPAVAAVVPRVASLPPAAGGGRAQARRVGEDAAAAEGRTPPAGQPRAAQEP
                *************************************************** ********

predicted       PIVISDSPPPSPRRPAGPGPLSFVSSSSAQVSSGPGGGGLPQSSGRAARPRAAVAPRVRS
reference       PIVISDSPPPSPRRPAGPGPLSFFSSSSAQVSSGPGGGGLPQSSGRAARPRAAVAPRVRS
                ***********************.************************************

predicted       PPRAAAAPVVSASADAAGPAPPAVPVDAHRAPRSRMTQAQTDTQAQSLGRAGATDARGSG
reference       PPRAAAAPVVSASADAAGPAPPAVPVDAHRAPRSRMTQAQTDTQAQSLGRAGATDARGSG
                ************************************************************

predicted       GPGAEGGPGVPRGTNTPGAAPHAAEGAAARPRKRRGSDSGPAASSSASSSAAPRSPLAPQ
reference       GPGAEGGPGVPRGTNTPGAAPHAAEGAAARPRKRRGSDSGPAASSSASSSAAPRSPLAPQ
                ************************************************************

predicted       GVGAKRAAPRRAPDSDSGDRGHGPLAPASAGAAPPSASPSSQAAVAAAASSSSSAASSSS
reference       GVGAKRAAPRRAPDSDSGDRGHGPLAPASAGAAPPSASPSSQAAVAAAASSSSSAASSSS
                ************************************************************

predicted       SAASSSSSAASSSSSAASSSSAASSSSSSSSASSSAGGAGGSVASASGAGERRETSLGPR
reference       SAASSSSSAASSSSSAASSSSAASSSSSSSSASSSAGGAGGSVASASGAGERRETSLGPR
                ************************************************************

predicted       AAAPRGPRKCARKTRHAEGGPEPGARDPAPGLTRYLPIAGVSSVVALAPYVNKTVTGDCL
reference       AAAPRGPRKCARKTRHAEGGPEPGARDPAPGLTRYLPIAGVSSVVALAPYVNKTVTGDCL
                ************************************************************

predicted       PVLDMETGHIGAYVVLVDQTGNVADLLRAAAPAWSRRTLLPEHARNCVRPPDYPTPPASE
reference       PVLDMETGHIGAYVVLVDQTGNVADLLRAAAPAWSRRTLLPEHARNCVRPPDYPTPPASE
                ************************************************************

predicted       WNSLWMTPVGNMLFDQGTLVGALDFHGLRSRHPWSREQGAPAPAGDAPAGHGE
reference       WNSLWMTPVGNMLFDQGTLVGALDFHGLRSRHPWSREQGAPAPAGDAPAGHGE
                *****************************************************

>MF564037.1.2	1780	4784
ccgtgtgacggtcgggccgcattcgcaccccggcactgcgagcgacggagcggcggcccg
gcgggaggaggagacccggagagacagagactaaaacccggcaagagagagaccgcgggc
cgccgtctcgagtctaccctaccccggctcATGGAACCCCGGCCCGGCACGAGCTCCCGG
GCGGACCCCGGCCCCGAGCGGCCGCCGCGGCAGACCCCCGGCGCGgtgagagggcgaccc
ccgggtctcaggcccccccttttccccggaccacccggctgcgggttgggggtggtcgcg
ggcggtgggctcgggggcggggacgcttgacggggccgacccccggcccgcttaagcggt
cgggggacccccgtgggccgtgcgccgccccccgaccctctgggggggcgagggaggcag
ggaggagcccgagagcgggggacagggggggagacgaggggtcggaatccaaaggacgca
gaccacctttggttacggacccctttctcccccccttccgaacaaaaagcagcgggcggg
gggccggggtgagggagggacacgggggacacggcacgggggtcccgcctcacgccccgc
gccctctaaatcccccccgtttctttgtcaagcagCCCGCCGCCCCGCACGCCTGGGGGA
TGCTCAACGACATGCAGTGGCTCGCCAGCAGCGACTCGGAGGAGGAGACCGAGGTGGGAA
TCTCTGACGACGACCTTCACCGCGACTCCACCTCCGAGGCGGGCAGCACGGACACGGAGA
TGTTCGAGGCGGGCCTGATGGACGCGGCCACGCCCCCGGCCCGGCCCCCGGCCGAGCGCC
AGGGCAGCCCCACGCCCGCCGACGCGCAGGGATCCTGCGGGGGTGGGCCCGTGGGTGAGG
AGGAAGCGGAAGCGGGAGGGGGGGGCGACGTGTGCGCCGTGTGCACGGACGAGATCGCCC
CGCCCCTGCGCTGCCAGAGTTTTCCCTGCCTGCACCCCTTCTGCATCCCGTGCATGAAGA
CCTGGATTCCGTTGCGCAACACGTGTCCCCTGTGCAACACCCCGGTGGCGTACCTGATAG
TGGGCGTGACCGCCAGCGGGTCGTTCAGCACCATCCCGATAGTGAACGACCCCCGGACCC
GCGTGGAGGCCGAGGCGGCCGTGCGGTCCGGCACGGCCGTGGACTTTATCTGGACGGGCA
ACCCGCGGACGGCCCCGCGCTCCCTGTCGCTGGGGGGACACACGGTCCGCGCCCTGTCGC
CCACCCCCCCGTGGCCCGGCACGGACGACGAGGACGATGACCTGGCCGACggtgagggcg
ggcgggggtcgggcgggggtcgggcgggggtcgggcgggggtcgggcactaaccgggggc
tcccgtctctgtctccctctgcagcgGACTACGTCCCGCCCGCCCCCCGAAGAGCGCCCC
GGCGCGGGGGCGGCGGTGCGGGGGCGACCCGCGGAACCTCCCAGCCCGCCGCGACCCGAC
CGGCGCCCCCTGGCGCCCCGCGGAGCAGCAGCAGCGGCGGCGCCCCGTTGCGGGCGGGGG
TGGGATCTGGGTCTGGGGGCGGCCCTGCCGTCGCGGCCGTCGTGCCGAGAGTGGCCTCTC
TTCCCCCTGCGGCCGGCGGGGGGCGCGCGCAGGCGCGGCGGGTGGGCGAAGACGCCGCGG
CGGCGGAGGGCAGGACGCCCCCCGCGAGACAGCCCCGCGCGGCCCAGGAGCCCCCCATAG
TCATCAGCGACTCTCCCCCGCCGTCTCCGCGCCGCCCCGCGGGCCCCGGGCCGCTCTCCT
TTGTCTCCTCCTCCTCCGCGCAGGTGTCCTCGGGCCCCGGGGGGGGAGGTCTGCCACAGT
CGTCGGGGCGCGCGGCGCGCCCCCGCGCGGCCGTCGCCCCGCGCGTCCGGAGTCCGCCCC
GCGCCGCCGCCGCCCCCGTGGTGTCTGCGAGCGCGGACGCGGCCGGGCCCGCGCCGCCCG
CCGTGCCGGTGGACGCGCACCGCGCGCCCCGGTCGCGCATGACCCAGGCTCAGACCGACA
CCCAAGCACAGAGTCTGGGCCGGGCAGGCGCGACCGACGCGCGCGGGTCGGGAGGGCCGG
GCGCGGAGGGAGGACCCGGGGTCCCCCGCGGCACCAACACCCCCGGTGCCGCCCCCCACG
CCGCGGAGGGGGCGGCGGCCCGCCCCCGGAAGAGGCGCGGGTCGGACTCGGGCCCTGCGG
CCTCGTCCTCCGCCTCTTCCTCCGCCGCCCCGCGCTCGCCCCTCGCCCCCCAGGGGGTGG
GGGCCAAGAGGGCGGCGCCGCGCCGGGCCCCGGACTCGGACTCGGGCGACCGCGGCCACG
GGCCGCTCGCCCCGGCGTCCGCGGGCGCCGCGCCCCCGTCGGCGTCTCCGTCGTCCCAGG
CCGCGGTCGCCGCCGCCGCCTCCTCTTCCTCCTCCGCCGCCTCCTCTTCCTCCTCCGCCG
CCTCCTCTTCCTCCTCCGCCGCCTCCTCTTCCTCCTCCGCCGCCTCTTCCTCCTCCGCCG
CCTCCTCTTCCTCCTCCTCCTCCTCCGCCTCTTCCTCTGCGGGCGGGGCTGGTGGGAGCG
TCGCGTCCGCGTCCGGCGCTGGGGAGAGACGAGAAACCTCCCTCGGCCCCCGCGCTGCTG
CGCCGCGGGGGCCGAGGAAGTGTGCCAGGAAGACGCGCCACGCGGAGGGCGGCCCCGAGC
CCGGGGCCCGCGACCCGGCGCCCGGCCTCACGCGCTACCTGCCCATCGCGGGGGTCTCGA
GCGTCGTGGCCCTGGCGCCTTACGTGAACAAGACGGTCACGGGGGACTGCCTGCCCGTCC
TGGACATGGAGACGGGCCACATAGGGGCCTACGTGGTCCTCGTGGACCAGACGGGGAACG
TGGCGGACCTGCTGCGGGCCGCGGCCCCCGCGTGGAGCCGCCGCACCCTGCTCCCCGAGC
ACGCGCGCAACTGCGTGAGGCCCCCCGACTACCCGACGCCCCCCGCGTCGGAGTGGAACA
GCCTCTGGATGACCCCGGTGGGCAACATGCTCTTTGACCAGGGCACCCTGGTGGGCGCGC
TGGACTTCCACGGCCTCCGGTCGCGCCACCCGTGGTCTCGGGAGCAGGGCGCGCCCGCGC
CGGCCGGCGACGCCCCCGCGGGCCACGGGGAGTAGggggagctaacactcggcttgctgc
ccgaaggaagccgccccccaccggaccaccggccgaggcgcctcgggggcagggggaggt
gggggggaaagacggggaggagacaggaagtgggggtgggagtggggggggacggacacg
gcccc

Length = 833

Score =  64.8 bits (135), Expect(9) = 8e-50
Identities = 24/24 (100%), Positives = 24/24 (100%)
Frame = +1

Query: 1780 MEPRPGTSSRADPGPERPPRQTPG 1851
            MEPRPGTSSRADPGPERPPRQTPG
Sbjct: 1    MEPRPGTSSRADPGPERPPRQTPG 24

Score =   558 bits (1237), Expect(2) = 0.0
Identities = 228/238 (95%), Positives = 229/238 (96%)
Frame = +3

Query: 2226 PRPLNPPRFFVKQPAAPHAWGMLNDMQWLASSDSEEETEVGISDDDLHRDSTSEAGSTDT 2405
            P P  PPR     PAAPHAWGMLNDMQWLASSDSEEETEVGISDDDLHRDSTSEAGSTDT
Sbjct: 13   PGPERPPRQTPGTPAAPHAWGMLNDMQWLASSDSEEETEVGISDDDLHRDSTSEAGSTDT 72

Query: 2406 EMFEAGLMDAATPPARPPAERQGSPTPADAQGSCGGGPVGEEEAEAGGGGDVCAVCTDEI 2585
            EMFEAGLMDAATPPARPPAERQGSPTPADAQGSCGGGPVGEEEAEAGGGGDVCAVCTDEI
Sbjct: 73   EMFEAGLMDAATPPARPPAERQGSPTPADAQGSCGGGPVGEEEAEAGGGGDVCAVCTDEI 132

Query: 2586 APPLRCQSFPCLHPFCIPCMKTWIPLRNTCPLCNTPVAYLIVGVTASGSFSTIPIVNDPR 2765
            APPLRCQSFPCLHPFCIPCMKTWIPLRNTCPLCNTPVAYLIVGVTASGSFSTIPIVNDPR
Sbjct: 133  APPLRCQSFPCLHPFCIPCMKTWIPLRNTCPLCNTPVAYLIVGVTASGSFSTIPIVNDPR 192

Query: 2766 TRVEAEAAVRSGTAVDFIWTGNPRTAPRSLSLGGHTVRALSPTPPWPGTDDEDDDLAD 2939
            TRVEAEAAVR+GTAVDFIWTGN RTAPRSLSLGGHTVRALSPTPPWPGTDDEDDDLAD
Sbjct: 193  TRVEAEAAVRAGTAVDFIWTGNQRTAPRSLSLGGHTVRALSPTPPWPGTDDEDDDLAD 250

Score =  1333 bits (2961), Expect(2) = 0.0
Identities = 580/582 (99%), Positives = 580/582 (99%)
Frame = +3

Query: 3036 DYVPPAPRRAPRRGGGGAGATRGTSQPAATRPAPPGAPRSSSSGGAPLRAGVGSGSGGGP 3215
            DYVPPAPRRAPRRGGGGAGATRGTSQPAATRPAPPGAPRSSSSGGAPLRAGVGSGSGGGP
Sbjct: 252  DYVPPAPRRAPRRGGGGAGATRGTSQPAATRPAPPGAPRSSSSGGAPLRAGVGSGSGGGP 311

Query: 3216 AVAAVVPRVASLPPAAGGGRAQARRVGEDAAAAEGRTPPARQPRAAQEPPIVISDSPPPS 3395
            AVAAVVPRVASLPPAAGGGRAQARRVGEDAAAAEGRTPPA QPRAAQEPPIVISDSPPPS
Sbjct: 312  AVAAVVPRVASLPPAAGGGRAQARRVGEDAAAAEGRTPPAGQPRAAQEPPIVISDSPPPS 371

Query: 3396 PRRPAGPGPLSFVSSSSAQVSSGPGGGGLPQSSGRAARPRAAVAPRVRSPPRAAAAPVVS 3575
            PRRPAGPGPLSF SSSSAQVSSGPGGGGLPQSSGRAARPRAAVAPRVRSPPRAAAAPVVS
Sbjct: 372  PRRPAGPGPLSFFSSSSAQVSSGPGGGGLPQSSGRAARPRAAVAPRVRSPPRAAAAPVVS 431

Query: 3576 ASADAAGPAPPAVPVDAHRAPRSRMTQAQTDTQAQSLGRAGATDARGSGGPGAEGGPGVP 3755
            ASADAAGPAPPAVPVDAHRAPRSRMTQAQTDTQAQSLGRAGATDARGSGGPGAEGGPGVP
Sbjct: 432  ASADAAGPAPPAVPVDAHRAPRSRMTQAQTDTQAQSLGRAGATDARGSGGPGAEGGPGVP 491

Query: 3756 RGTNTPGAAPHAAEGAAARPRKRRGSDSGPAASSSASSSAAPRSPLAPQGVGAKRAAPRR 3935
            RGTNTPGAAPHAAEGAAARPRKRRGSDSGPAASSSASSSAAPRSPLAPQGVGAKRAAPRR
Sbjct: 492  RGTNTPGAAPHAAEGAAARPRKRRGSDSGPAASSSASSSAAPRSPLAPQGVGAKRAAPRR 551

Query: 3936 APDSDSGDRGHGPLAPASAGAAPPSASPSSQAAVAAAASSSSSAASSSSSAASSSSSAAS 4115
            APDSDSGDRGHGPLAPASAGAAPPSASPSSQAAVAAAASSSSSAASSSSSAASSSSSAAS
Sbjct: 552  APDSDSGDRGHGPLAPASAGAAPPSASPSSQAAVAAAASSSSSAASSSSSAASSSSSAAS 611

Query: 4116 SSSSAASSSSAASSSSSSSSASSSAGGAGGSVASASGAGERRETSLGPRAAAPRGPRKCA 4295
            SSSSAASSSSAASSSSSSSSASSSAGGAGGSVASASGAGERRETSLGPRAAAPRGPRKCA
Sbjct: 612  SSSSAASSSSAASSSSSSSSASSSAGGAGGSVASASGAGERRETSLGPRAAAPRGPRKCA 671

Query: 4296 RKTRHAEGGPEPGARDPAPGLTRYLPIAGVSSVVALAPYVNKTVTGDCLPVLDMETGHIG 4475
            RKTRHAEGGPEPGARDPAPGLTRYLPIAGVSSVVALAPYVNKTVTGDCLPVLDMETGHIG
Sbjct: 672  RKTRHAEGGPEPGARDPAPGLTRYLPIAGVSSVVALAPYVNKTVTGDCLPVLDMETGHIG 731

Query: 4476 AYVVLVDQTGNVADLLRAAAPAWSRRTLLPEHARNCVRPPDYPTPPASEWNSLWMTPVGN 4655
            AYVVLVDQTGNVADLLRAAAPAWSRRTLLPEHARNCVRPPDYPTPPASEWNSLWMTPVGN
Sbjct: 732  AYVVLVDQTGNVADLLRAAAPAWSRRTLLPEHARNCVRPPDYPTPPASEWNSLWMTPVGN 791

Query: 4656 MLFDQGTLVGALDFHGLRSRHPWSREQGAPAPAGDAPAGHGE 4781
            MLFDQGTLVGALDFHGLRSRHPWSREQGAPAPAGDAPAGHGE
Sbjct: 792  MLFDQGTLVGALDFHGLRSRHPWSREQGAPAPAGDAPAGHGE 833


========================================================================================================================

gene_id            %id    %sim   %cov   %t5   %gap  %t3   start..stop      pep sz ref sz ref id            definition
MF564037.1.61      97.4   98.7   100.0  0.0   0.0   0.0   124100..124026   835    826    CAB06705.1        RL2-ii | ubiquitin E3 ligase ICP0
                                                          123618..122938                                   
                                                          122833..121082                                   
                    invalid splicing for intron  at 122937..122834

CLUSTAL 2.1 multiple sequence alignment


predicted       MEPRPGTSSRADPGPERPPRQTPGAQPAAPHAWGMLNDMQWLASSDSEEETEVGISDDDL
reference       MEPRPGTSSRADPGPERPPRQTPGTQPAAPHAWGMLNDMQWLASSDSEEETEVGISDDDL
                ************************:***********************************

predicted       HRDSTSEAGSTDTEMFEAGLMDAATPPARPPAERQGSPTPADAQGSCGGGPVGEEEAEAG
reference       HRDSTSEAGSTDTEMFEAGLMDAATPPARPPAERQGSPTPADAQGSCGGGPVGEEEAEAG
                ************************************************************

predicted       GGGDVCAVCTDEIAPPLRCQSFPCLHPFCIPCMKTWIPLRNTCPLCNTPVAYLIVGVTAS
reference       GGGDVCAVCTDEIAPPLRCQSFPCLHPFCIPCMKTWIPLRNTCPLCNTPVAYLIVGVTAS
                ************************************************************

predicted       GSFSTIPIVNDPRTRVEAEAAVRSGTAVDFIWTGNPRTAPRSLSLGGHTVRALSPTPPWP
reference       GSFSTIPIVNDPRTRVEAEAAVRAGTAVDFIWTGNPRTAPRSLSLGGHTVRALSPTPPWP
                ***********************:************************************

predicted       GTDDEDDDLADG-DYVPPAPRRAPRRGGGGAGATRGTSQPAATRPAPPGAPRSSSSGGAP
reference       GTDDEDDDLADGVDYVPPAPRRAPRRGGGGAGATRGTSQPAATRPAPPGAPRSSSSGGAP
                ************ ***********************************************

predicted       LRAGVGSGSGGGPAVAAVVPRVASLPPAAGGGRAQARRVGEDAAAAEGRTPPARQPRAAQ
reference       LRAGVGSGSGGGPAVAAVVPRVASLPPAAGGGRAQARRVGEDAAAAEGRTPPARQPRAAQ
                ************************************************************

predicted       EPPIVISDSPPPSPRRPAGPGPLSFVSSSSAQVSSGPGGGGLPQSSGRAARPRAAVAPRV
reference       EPPIVISDSPPPSPRRPAGPGPLSFVSSSSAQVSSGPGGGGLPQSSGRAARPRAAVAPRV
                ************************************************************

predicted       RSPPRAAAAPVVSASADAAGPAPPAVPVDAHRAPRSRMTQAQTDTQAQSLGRAGATDARG
reference       RSPPRAAAAPVVSASADAAGPAPPAVPVDAHRAPRSRMTQAQTDTQAQSLGRAGATDARG
                ************************************************************

predicted       SGGPGAEGGPGVPRGTNTPGAAPHAAEGAAARPRKRRGSDSGPAASSSASSSAAPRSPLA
reference       SGGPGAEGGPGVPRGTNTPGAAPHAAEGAAARPRKRRGSDSGPAASSSASSSAAPRSPLA
                ************************************************************

predicted       PQGVGAKRAAPRRAPDSDSGDRGHGPLAPASAGAAPPSASPSSQAAVAAAASSSSSSSSS
reference       PQGVGAKRAAPRRAPDSDSGDRGHGPLAPASAGAAPPSASPSSQAAVAAASSSSASSSSA
                **************************************************:***:****:

predicted       SSASSSAGGAGASSSSSSASSSAGGAGASSSSSSASSSAGGAGGSVASASGAGERRETSL
reference       SSSSASS----SSASSSSASSS------SASSSSASSSAGGAGGSVASASGAGERRETSL
                **:*:*:    :*:********      *:******************************

predicted       GPRAAAPRGPRKCARKTRHAEGGPEPGARDPAPGLTRYLPIAGVSSVVALAPYVNKTVTG
reference       GPRAAAPRGPRKCARKTRHAEGGPEPGARDPAPGLTRYLPIAGVSSVVALAPYVNKTVTG
                ************************************************************

predicted       DCLPVLDMETGHIGAYVVLVDQTGNVADLLRAAAPAWSRRTLLPEHARNCVRPPDYPTPP
reference       DCLPVLDMETGHIGAYVVLVDQTGNVADLLRAAAPAWSRRTLLPEHARNCVRPPDYPTPP
                ************************************************************

predicted       ASEWNSLWMTPVGNMLFDQGTLVGALDFHGLRSRHPWSREQGAPAPAGDAPAGHGE
reference       ASEWNSLWMTPVGNMLFDQGTLVGALDFHGLRSRHPWSREQGAPAPAGDAPAGHGE
                ********************************************************

>MF564037.1.62	124100	121082
ccgtgtgacggtcgggccgcattcgcaccccggcactgcgagcgacggagcggcggcccg
gcgggaggaggagacccggagagacagagactaaaacccggcaagagagagaccgcgggc
cgccgtctcgagtctaccctaccccggctcATGGAACCCCGGCCCGGCACGAGCTCCCGG
GCGGACCCCGGCCCCGAGCGGCCGCCGCGGCAGACCCCCGGCGCGgtgagagggcgaccc
ccgggtctcaggcccccccttttccccggaccacccggctgcgggttgggggtggtcgcg
ggcggtgggctcgggggcggggacgcttgacggggccgacccccggcccgcttaagcggt
cgggggacccccgtgggccgtgcgccgccccccgaccctctgggggggcgagggaggcag
ggaggagcccgagagcgggggacagggggggagacgaggggtcggaatccaaaggacgca
gaccacctttggttacggacccctttctcccccccttccgaacaaaaagcagcgggcggg
gggccggggtgagggagggacacgggggacacggcacgggggtcccgcctcacgccccgc
gccctctaaatcccccccgtttctttgtcaagCAGCCCGCCGCCCCGCACGCCTGGGGGA
TGCTCAACGACATGCAGTGGCTCGCCAGCAGCGACTCGGAGGAGGAGACCGAGGTGGGAA
TCTCTGACGACGACCTTCACCGCGACTCCACCTCCGAGGCGGGCAGCACGGACACGGAGA
TGTTCGAGGCGGGCCTGATGGACGCGGCCACGCCCCCGGCCCGGCCCCCGGCCGAGCGCC
AGGGCAGCCCCACGCCCGCCGACGCGCAGGGATCCTGCGGGGGTGGGCCCGTGGGTGAGG
AGGAAGCGGAAGCGGGAGGGGGGGGCGACGTGTGCGCCGTGTGCACGGACGAGATCGCCC
CGCCCCTGCGCTGCCAGAGTTTTCCCTGCCTGCACCCCTTCTGCATCCCGTGCATGAAGA
CCTGGATTCCGTTGCGCAACACGTGTCCCCTGTGCAACACCCCGGTGGCGTACCTGATAG
TGGGCGTGACCGCCAGCGGGTCGTTCAGCACCATCCCGATAGTGAACGACCCCCGGACCC
GCGTGGAGGCCGAGGCGGCCGTGCGGTCCGGCACGGCCGTGGACTTTATCTGGACGGGCA
ACCCGCGGACGGCCCCGCGCTCCCTGTCGCTGGGGGGACACACGGTCCGCGCCCTGTCGC
CCACCCCCCCGTGGCCCGGCACGGACGACGAGGACGATGACCTGGCCGACGGTgagggcg
ggcgggggtcgggcgggggtcgggcgggggtcgggcgggggtcgggcgggggtcgggcac
taaccgggggctcccgtctctgtctccctctgcagcgGACTACGTCCCGCCCGCCCCCCG
AAGAGCGCCCCGGCGCGGGGGCGGCGGTGCGGGGGCGACCCGCGGAACCTCCCAGCCCGC
CGCGACCCGACCGGCGCCCCCTGGCGCCCCGCGGAGCAGCAGCAGCGGCGGCGCCCCGTT
GCGGGCGGGGGTGGGATCTGGGTCTGGGGGCGGCCCTGCCGTCGCGGCCGTCGTGCCGAG
AGTGGCCTCTCTTCCCCCTGCGGCCGGCGGGGGGCGCGCGCAGGCGCGGCGGGTGGGCGA
AGACGCCGCGGCGGCGGAGGGCAGGACGCCCCCCGCGAGACAGCCCCGCGCGGCCCAGGA
GCCCCCCATAGTCATCAGCGACTCTCCCCCGCCGTCTCCGCGCCGCCCCGCGGGCCCCGG
GCCGCTCTCCTTTGTCTCCTCCTCCTCCGCGCAGGTGTCCTCGGGCCCCGGGGGGGGAGG
TCTGCCACAGTCGTCGGGGCGCGCGGCGCGCCCCCGCGCGGCCGTCGCCCCGCGCGTCCG
GAGTCCGCCCCGCGCCGCCGCCGCCCCCGTGGTGTCTGCGAGCGCGGACGCGGCCGGGCC
CGCGCCGCCCGCCGTGCCGGTGGACGCGCACCGCGCGCCCCGGTCGCGCATGACCCAGGC
TCAGACCGACACCCAAGCACAGAGTCTGGGCCGGGCAGGCGCGACCGACGCGCGCGGGTC
GGGAGGGCCGGGCGCGGAGGGAGGACCCGGGGTCCCCCGCGGCACCAACACCCCCGGTGC
CGCCCCCCACGCCGCGGAGGGGGCGGCGGCCCGCCCCCGGAAGAGGCGCGGGTCGGACTC
GGGCCCTGCGGCCTCGTCCTCCGCCTCTTCCTCCGCCGCCCCGCGCTCGCCCCTCGCCCC
CCAGGGGGTGGGGGCCAAGAGGGCGGCGCCGCGCCGGGCCCCGGACTCGGACTCGGGCGA
CCGCGGCCACGGGCCGCTCGCCCCGGCGTCCGCGGGCGCCGCGCCCCCGTCGGCGTCTCC
GTCGTCCCAGGCCGCGGTCGCCGCCGCCGCCTCCTCTTCCTCCTCCTCCTCCTCCTCCTC
CTCCGCCTCTTCCTCTGCGGGCGGGGCTGGTGCTTCCTCCTCCTCCTCCTCCGCCTCTTC
CTCTGCGGGCGGGGCTGGTGCTTCCTCCTCCTCCTCCTCCGCCTCTTCCTCTGCGGGCGG
GGCTGGTGGGAGCGTCGCGTCCGCGTCCGGCGCTGGGGAGAGACGAGAAACCTCCCTCGG
CCCCCGCGCTGCTGCGCCGCGGGGGCCGAGGAAGTGTGCCAGGAAGACGCGCCACGCGGA
GGGCGGCCCCGAGCCCGGGGCCCGCGACCCGGCGCCCGGCCTCACGCGCTACCTGCCCAT
CGCGGGGGTCTCGAGCGTCGTGGCCCTGGCGCCTTACGTGAACAAGACGGTCACGGGGGA
CTGCCTGCCCGTCCTGGACATGGAGACGGGCCACATAGGGGCCTACGTGGTCCTCGTGGA
CCAGACGGGGAACGTGGCGGACCTGCTGCGGGCCGCGGCCCCCGCGTGGAGCCGCCGCAC
CCTGCTCCCCGAGCACGCGCGCAACTGCGTGAGGCCCCCCGACTACCCGACGCCCCCCGC
GTCGGAGTGGAACAGCCTCTGGATGACCCCGGTGGGCAACATGCTCTTTGACCAGGGCAC
CCTGGTGGGCGCGCTGGACTTCCACGGCCTCCGGTCGCGCCACCCGTGGTCTCGGGAGCA
GGGCGCGCCCGCGCCGGCCGGCGACGCCCCCGCGGGCCACGGGGAGTAGggggagctaac
actcggcttgctgcccgaaggaagccgccccccaccggaccaccggccgaggcgcctcgg
gggcagggggaggtgggggggaaagacggggaggagacaggaagtgggggtgggagtggg
gggggacggacacggcccc

Length = 826

Score =  65.7 bits (137), Expect(8) = 0.0
Identities = 25/30 (83%), Positives = 25/30 (83%)
Frame = -3

Query: 124100 MEPRPGTSSRADPGPERPPRQTPGAVRGRP 124011
              MEPRPGTSSRADPGPERPPRQTPG     P
Sbjct: 1      MEPRPGTSSRADPGPERPPRQTPGTQPAAP 30

Score =   570 bits (1238), Expect(2) = 0.0
Identities = 226/227 (99%), Positives = 227/227 (100%)
Frame = -2

Query: 123618 QPAAPHAWGMLNDMQWLASSDSEEETEVGISDDDLHRDSTSEAGSTDTEMFEAGLMDAAT 123439
              QPAAPHAWGMLNDMQWLASSDSEEETEVGISDDDLHRDSTSEAGSTDTEMFEAGLMDAAT
Sbjct: 26     QPAAPHAWGMLNDMQWLASSDSEEETEVGISDDDLHRDSTSEAGSTDTEMFEAGLMDAAT 85

Query: 123438 PPARPPAERQGSPTPADAQGSCGGGPVGEEEAEAGGGGDVCAVCTDEIAPPLRCQSFPCL 123259
              PPARPPAERQGSPTPADAQGSCGGGPVGEEEAEAGGGGDVCAVCTDEIAPPLRCQSFPCL
Sbjct: 86     PPARPPAERQGSPTPADAQGSCGGGPVGEEEAEAGGGGDVCAVCTDEIAPPLRCQSFPCL 145

Query: 123258 HPFCIPCMKTWIPLRNTCPLCNTPVAYLIVGVTASGSFSTIPIVNDPRTRVEAEAAVRSG 123079
              HPFCIPCMKTWIPLRNTCPLCNTPVAYLIVGVTASGSFSTIPIVNDPRTRVEAEAAVR+G
Sbjct: 146    HPFCIPCMKTWIPLRNTCPLCNTPVAYLIVGVTASGSFSTIPIVNDPRTRVEAEAAVRAG 205

Query: 123078 TAVDFIWTGNPRTAPRSLSLGGHTVRALSPTPPWPGTDDEDDDLADG 122938
              TAVDFIWTGNPRTAPRSLSLGGHTVRALSPTPPWPGTDDEDDDLADG
Sbjct: 206    TAVDFIWTGNPRTAPRSLSLGGHTVRALSPTPPWPGTDDEDDDLADG 252

Score =   836 bits (1835), Expect(2) = 0.0
Identities = 361/390 (92%), Positives = 378/390 (96%)
Frame = -1

Query: 122833 DYVPPAPRRAPRRGGGGAGATRGTSQPAATRPAPPGAPRSSSSGGAPLRAGVGSGSGGGP 122654
              DYVPPAPRRAPRRGGGGAGATRGTSQPAATRPAPPGAPRSSSSGGAPLRAGVGSGSGGGP
Sbjct: 254    DYVPPAPRRAPRRGGGGAGATRGTSQPAATRPAPPGAPRSSSSGGAPLRAGVGSGSGGGP 313

Query: 122653 AVAAVVPRVASLPPAAGGGRAQARRVGEDAAAAEGRTPPARQPRAAQEPPIVISDSPPPS 122474
              AVAAVVPRVASLPPAAGGGRAQARRVGEDAAAAEGRTPPARQPRAAQEPPIVISDSPPPS
Sbjct: 314    AVAAVVPRVASLPPAAGGGRAQARRVGEDAAAAEGRTPPARQPRAAQEPPIVISDSPPPS 373

Query: 122473 PRRPAGPGPLSFVSSSSAQVSSGPGGGGLPQSSGRAARPRAAVAPRVRSPPRAAAAPVVS 122294
              PRRPAGPGPLSFVSSSSAQVSSGPGGGGLPQSSGRAARPRAAVAPRVRSPPRAAAAPVVS
Sbjct: 374    PRRPAGPGPLSFVSSSSAQVSSGPGGGGLPQSSGRAARPRAAVAPRVRSPPRAAAAPVVS 433

Query: 122293 ASADAAGPAPPAVPVDAHRAPRSRMTQAQTDTQAQSLGRAGATDARGSGGPGAEGGPGVP 122114
              ASADAAGPAPPAVPVDAHRAPRSRMTQAQTDTQAQSLGRAGATDARGSGGPGAEGGPGVP
Sbjct: 434    ASADAAGPAPPAVPVDAHRAPRSRMTQAQTDTQAQSLGRAGATDARGSGGPGAEGGPGVP 493

Query: 122113 RGTNTPGAAPHAAEGAAARPRKRRGSDSGPAASSSASSSAAPRSPLAPQGVGAKRAAPRR 121934
              RGTNTPGAAPHAAEGAAARPRKRRGSDSGPAASSSASSSAAPRSPLAPQGVGAKRAAPRR
Sbjct: 494    RGTNTPGAAPHAAEGAAARPRKRRGSDSGPAASSSASSSAAPRSPLAPQGVGAKRAAPRR 553

Query: 121933 APDSDSGDRGHGPLAPASAGAAPPSASPSSQAAVAAAASSSSSSSSSSSASSSAGGAGAS 121754
              APDSDSGDRGHGPLAPASAGAAPPSASPSSQAAVAAA+SSS+SSSS+SS+S+S+  A +S
Sbjct: 554    APDSDSGDRGHGPLAPASAGAAPPSASPSSQAAVAAASSSSASSSSASSSSASSSSASSS 613

Query: 121753 SSSSSASSSAGGAGASSSSSSASSSAGGAG 121664
              S+SSS++SS+  + ++  +  + +SA GAG
Sbjct: 614    SASSSSASSSSASSSAGGAGGSVASASGAG 643

Score =   541 bits (1185), Expect(8) = 0.0
Identities = 225/264 (85%), Positives = 246/264 (93%)
Frame = -1

Query: 121876 GAAPPSASPSSQAAVAAAASSSSSSSSSSSASSSAGGAGASSSSSSASSSAGGAGASSSS 121697
              G  P + + +  A  +A+ SS ++ +++SS+S+S+  A +SS+SSS++SS+  + +S+SS
Sbjct: 563    GHGPLAPASAGAAPPSASPSSQAAVAAASSSSASSSSASSSSASSSSASSSSASSSSASS 622

Query: 121696 SSASSSAGGAGGSVASASGAGERRETSLGPRAAAPRGPRKCARKTRHAEGGPEPGARDPA 121517
              SSASSSAGGAGGSVASASGAGERRETSLGPRAAAPRGPRKCARKTRHAEGGPEPGARDPA
Sbjct: 623    SSASSSAGGAGGSVASASGAGERRETSLGPRAAAPRGPRKCARKTRHAEGGPEPGARDPA 682

Query: 121516 PGLTRYLPIAGVSSVVALAPYVNKTVTGDCLPVLDMETGHIGAYVVLVDQTGNVADLLRA 121337
              PGLTRYLPIAGVSSVVALAPYVNKTVTGDCLPVLDMETGHIGAYVVLVDQTGNVADLLRA
Sbjct: 683    PGLTRYLPIAGVSSVVALAPYVNKTVTGDCLPVLDMETGHIGAYVVLVDQTGNVADLLRA 742

Query: 121336 AAPAWSRRTLLPEHARNCVRPPDYPTPPASEWNSLWMTPVGNMLFDQGTLVGALDFHGLR 121157
              AAPAWSRRTLLPEHARNCVRPPDYPTPPASEWNSLWMTPVGNMLFDQGTLVGALDFHGLR
Sbjct: 743    AAPAWSRRTLLPEHARNCVRPPDYPTPPASEWNSLWMTPVGNMLFDQGTLVGALDFHGLR 802

Query: 121156 SRHPWSREQGAPAPAGDAPAGHGE 121085
              SRHPWSREQGAPAPAGDAPAGHGE
Sbjct: 803    SRHPWSREQGAPAPAGDAPAGHGE 826


========================================================================================================================

gene_id            %id    %sim   %cov   %t5   %gap  %t3   start..stop      pep sz ref sz ref id            definition
MF564035.1.2       99.4   99.6   100.0  0.0   0.0   0.0   1822..1896       832    833    AEV91397.2        RL2 | ubiquitin E3 ligase ICP0
                                                          2307..2981                                       
                                                          3078..4826                                       
                    invalid splicing for intron  at 2982..3077

CLUSTAL 2.1 multiple sequence alignment


predicted       MEPRPGTSSRADPGPERPPRQTPGTPAAPHAWGMLNDMQWLASSDSEEETEVGISDDDLH
reference       MEPRPGTSSRADPGPERPPRQTPGTPAAPHAWGMLNDMQWLASSDSEEETEVGISDDDLH
                ************************************************************

predicted       RDSTSEAGSTDTEMFEAGLMDAATPPARPPAERQGSPTPADAQGSCGGGPVGEEEAEAGG
reference       RDSTSEAGSTDTEMFEAGLMDAATPPARPPAERQGSPTPADAQGSCGGGPVGEEEAEAGG
                ************************************************************

predicted       GGDVCAVCTDEIAPPLRCQSFPCLHPFCIPCMKTWIPLRNTCPLCNTPVAYLIVGVTASG
reference       GGDVCAVCTDEIAPPLRCQSFPCLHPFCIPCMKTWIPLRNTCPLCNTPVAYLIVGVTASG
                ************************************************************

predicted       SFSTIPIVNDPRTRVEAEAAVRAGTAVDFIWTGNPRTAPRSLSLGGHTVRALSPTPPWPG
reference       SFSTIPIVNDPRTRVEAEAAVRAGTAVDFIWTGNQRTAPRSLSLGGHTVRALSPTPPWPG
                ********************************** *************************

predicted       TDDEDDDLAD-DYVPPAPRRAPRRGGGGAGATRGTSQPAATRPAPPGAPRSSSSGGAPLR
reference       TDDEDDDLADVDYVPPAPRRAPRRGGGGAGATRGTSQPAATRPAPPGAPRSSSSGGAPLR
                ********** *************************************************

predicted       AGVGSGSGGGPAVAAVVPRVASLPPAAGGGRAQARRVGEDAAAAEGRTPPARQPRAAQEP
reference       AGVGSGSGGGPAVAAVVPRVASLPPAAGGGRAQARRVGEDAAAAEGRTPPAGQPRAAQEP
                *************************************************** ********

predicted       PIVISDSPPPSPRRPAGPGPLSLFSSSSAQVSSGPGGGGLPQSSGRAARPRAAVAPRVRS
reference       PIVISDSPPPSPRRPAGPGPLSFFSSSSAQVSSGPGGGGLPQSSGRAARPRAAVAPRVRS
                **********************:*************************************

predicted       PPRAAAAPVVSASADAAGPAPPAVPVDAHRAPRSRMTQAQTDTQAQSLGRAGATDARGSG
reference       PPRAAAAPVVSASADAAGPAPPAVPVDAHRAPRSRMTQAQTDTQAQSLGRAGATDARGSG
                ************************************************************

predicted       GPGAEGGPGVPRGTNTPGAAPHAAEGAAARPRKRRGSDSGPAASSSASSSAAPRSPLAPQ
reference       GPGAEGGPGVPRGTNTPGAAPHAAEGAAARPRKRRGSDSGPAASSSASSSAAPRSPLAPQ
                ************************************************************

predicted       GVGAKRAAPRRAPDSDSGDRGHGPLAPASAGAAPPSASPSSQAAVAAAASSSSSAASSSS
reference       GVGAKRAAPRRAPDSDSGDRGHGPLAPASAGAAPPSASPSSQAAVAAAASSSSSAASSSS
                ************************************************************

predicted       SAASSSSSAASSSSSAASSSSAASSSSSSSSASSSAGGAGGSVASASGAGERRETSLGPR
reference       SAASSSSSAASSSSSAASSSSAASSSSSSSSASSSAGGAGGSVASASGAGERRETSLGPR
                ************************************************************

predicted       AAAPRGPRKCARKTRHAEGGPEPGARDPAPGLTRYLPIAGASSVVALAPYVNKTVTGDCL
reference       AAAPRGPRKCARKTRHAEGGPEPGARDPAPGLTRYLPIAGVSSVVALAPYVNKTVTGDCL
                ****************************************.*******************

predicted       PVLDMETGHIGAYVVLVDQTGNVADLLRAAAPAWSRRTLLPEHARNCVRPPDYPTPPASE
reference       PVLDMETGHIGAYVVLVDQTGNVADLLRAAAPAWSRRTLLPEHARNCVRPPDYPTPPASE
                ************************************************************

predicted       WNSLWMTPVGNMLFDQGTLVGALDFHGLRSRHPWSREQGAPAPAGDAPAGHGE
reference       WNSLWMTPVGNMLFDQGTLVGALDFHGLRSRHPWSREQGAPAPAGDAPAGHGE
                *****************************************************

>MF564035.1.2	1822	4826
ccgtgtgacggtcgggccgcattcgcaccccggcactgcgagcgacggagcggcggcccg
gcgggaggaggagacccggagagacagagactaacacccggcaagagagagaccgcgggc
cgccgtctcgagtctaccctaccccggctcATGGAACCCCGGCCCGGCACGAGCTCCCGG
GCGGACCCCGGCCCCGAGCGGCCGCCGCGGCAGACCCCCGGCACGgtgagagggcgaccc
ccgggtctcaggcccccccttttccccggaccacccggctgcgggttgggggtggtcgcg
ggcggtgggctcgggggcggggacgcttgacggggccgacccccggcccgcttaagcggt
cgggggacccccgtgggccgtgcgccgccccccgaccctttgggggggcgagggaggcag
ggaggagcccgagagcgggggacagggggggagacgaggggtcggaattcaaaggacgca
gaccacctttggttacggacccctttctcccccccttccgaacaaaaagcagcgggcggg
gggccggggtgagggagggacacgggggacacggcacgggggtcccgcctcacgccccgc
gccctctaaatcccccccgtttctttgtcaagcagCCCGCCGCCCCGCACGCCTGGGGGA
TGCTCAACGACATGCAGTGGCTCGCCAGCAGCGACTCGGAGGAGGAGACCGAGGTGGGAA
TCTCTGACGACGACCTTCACCGCGACTCCACCTCCGAGGCGGGCAGCACGGACACGGAGA
TGTTCGAGGCGGGCCTGATGGACGCGGCCACGCCCCCGGCCCGGCCCCCGGCCGAGCGCC
AGGGCAGCCCCACGCCCGCCGACGCGCAGGGATCCTGCGGGGGTGGGCCCGTGGGTGAGG
AGGAAGCGGAAGCGGGAGGGGGGGGCGACGTGTGTGCCGTGTGCACGGACGAGATCGCCC
CGCCCCTGCGCTGCCAGAGTTTTCCCTGCCTGCACCCCTTCTGCATCCCGTGCATGAAGA
CCTGGATTCCGTTGCGCAACACGTGTCCCCTGTGCAACACCCCGGTGGCGTACCTGATAG
TGGGCGTGACCGCCAGCGGGTCGTTCAGCACCATCCCGATAGTGAACGACCCCCGGACCC
GCGTGGAGGCCGAGGCGGCCGTGCGGGCCGGCACGGCCGTGGACTTTATCTGGACGGGCA
ACCCGCGGACGGCCCCGCGCTCCCTGTCGCTGGGGGGACACACGGTCCGCGCCCTGTCGC
CCACCCCCCCGTGGCCCGGCACGGACGACGAGGACGATGACCTGGCCGACggtgagggcg
ggcgggggtcgggcgggggtcgggcgggggtcgggcgggggtcgggcactaaccgggggt
tcccgtctctgtctccctctgcagcgGACTACGTCCCGCCCGCCCCCCGAAGAGCGCCCC
GGCGCGGGGGCGGCGGTGCGGGGGCGACCCGCGGAACCTCCCAGCCCGCCGCGACCCGAC
CGGCGCCCCCTGGCGCCCCGCGGAGCAGCAGCAGCGGCGGCGCCCCGTTGCGGGCGGGGG
TGGGATCTGGGTCTGGGGGCGGCCCTGCCGTCGCGGCCGTCGTGCCGAGAGTGGCCTCTC
TTCCCCCTGCGGCCGGCGGGGGGCGCGCGCAGGCGCGGCGGGTGGGCGAAGACGCCGCGG
CGGCGGAGGGCAGGACGCCCCCCGCGAGACAGCCCCGCGCGGCCCAGGAGCCCCCCATAG
TCATCAGCGACTCTCCCCCGCCGTCTCCGCGCCGCCCCGCGGGCCCCGGGCCGCTCTCCT
TGTTCTCCTCCTCCTCCGCGCAGGTGTCCTCGGGCCCCGGGGGGGGAGGTCTGCCACAGT
CGTCGGGGCGCGCGGCGCGCCCCCGCGCGGCCGTCGCCCCGCGCGTCCGGAGTCCGCCCC
GCGCCGCCGCCGCCCCCGTGGTGTCTGCGAGCGCGGACGCGGCCGGGCCCGCGCCGCCCG
CCGTGCCGGTGGACGCGCACCGCGCGCCCCGGTCGCGCATGACCCAGGCTCAGACCGACA
CCCAAGCACAGAGTCTGGGCCGGGCAGGCGCGACCGACGCGCGCGGGTCGGGAGGGCCGG
GCGCGGAGGGAGGACCCGGGGTCCCCCGCGGCACCAACACCCCCGGTGCCGCCCCCCACG
CCGCGGAGGGGGCGGCGGCCCGCCCCCGGAAGAGGCGCGGGTCGGACTCGGGCCCTGCGG
CCTCGTCCTCCGCCTCTTCCTCCGCCGCCCCGCGCTCGCCCCTCGCCCCCCAGGGGGTGG
GGGCCAAGAGGGCGGCGCCGCGCCGGGCCCCGGACTCGGACTCGGGCGACCGCGGCCACG
GGCCGCTCGCCCCGGCGTCCGCGGGCGCCGCGCCCCCGTCGGCGTCTCCGTCGTCCCAGG
CCGCGGTCGCCGCCGCCGCCTCCTCTTCCTCCTCCGCCGCCTCCTCTTCCTCCTCCGCCG
CCTCCTCTTCCTCCTCCGCCGCCTCCTCTTCCTCCTCCGCCGCCTCTTCCTCCTCCGCCG
CCTCCTCTTCCTCCTCCTCCTCCTCCGCCTCTTCCTCTGCGGGCGGGGCTGGTGGGAGCG
TCGCGTCCGCGTCCGGCGCTGGGGAGAGACGAGAAACCTCCCTCGGCCCCCGCGCTGCTG
CGCCGCGGGGGCCGAGGAAGTGTGCCAGGAAGACGCGCCACGCGGAGGGCGGCCCCGAGC
CCGGGGCCCGCGACCCGGCGCCCGGCCTCACGCGCTACCTGCCCATCGCGGGGGCCTCGA
GCGTCGTGGCCCTGGCGCCTTACGTGAACAAGACGGTCACGGGGGACTGCCTGCCCGTCC
TGGACATGGAGACGGGCCACATAGGGGCCTACGTGGTCCTCGTGGACCAGACGGGGAACG
TGGCGGACCTGCTGCGGGCCGCGGCCCCCGCGTGGAGCCGCCGCACCCTGCTCCCCGAGC
ACGCGCGCAACTGCGTGAGGCCCCCCGACTACCCGACGCCCCCCGCGTCGGAGTGGAACA
GCCTCTGGATGACCCCGGTGGGCAACATGCTCTTTGACCAGGGCACCCTGGTGGGCGCGC
TGGACTTCCACGGCCTCCGGTCGCGCCACCCGTGGTCTCGGGAGCAGGGCGCGCCCGCGC
CGGCCGGCGACGCCCCCGCGGGCCACGGGGAGTAGggggagctaacactcggcttgctgc
ccgaaggaagccgccccccaccggaccaccggccgaggcgcctcgggggcagggggaggt
gggggggaaagacggggaggagacaggaagtgggggtgggagggggggggacggacacgg
ccccg

Length = 833

Score =   560 bits (1240), Expect(2) = 0.0
Identities = 229/238 (96%), Positives = 229/238 (96%)
Frame = +3

Query: 2268 PRPLNPPRFFVKQPAAPHAWGMLNDMQWLASSDSEEETEVGISDDDLHRDSTSEAGSTDT 2447
            P P  PPR     PAAPHAWGMLNDMQWLASSDSEEETEVGISDDDLHRDSTSEAGSTDT
Sbjct: 13   PGPERPPRQTPGTPAAPHAWGMLNDMQWLASSDSEEETEVGISDDDLHRDSTSEAGSTDT 72

Query: 2448 EMFEAGLMDAATPPARPPAERQGSPTPADAQGSCGGGPVGEEEAEAGGGGDVCAVCTDEI 2627
            EMFEAGLMDAATPPARPPAERQGSPTPADAQGSCGGGPVGEEEAEAGGGGDVCAVCTDEI
Sbjct: 73   EMFEAGLMDAATPPARPPAERQGSPTPADAQGSCGGGPVGEEEAEAGGGGDVCAVCTDEI 132

Query: 2628 APPLRCQSFPCLHPFCIPCMKTWIPLRNTCPLCNTPVAYLIVGVTASGSFSTIPIVNDPR 2807
            APPLRCQSFPCLHPFCIPCMKTWIPLRNTCPLCNTPVAYLIVGVTASGSFSTIPIVNDPR
Sbjct: 133  APPLRCQSFPCLHPFCIPCMKTWIPLRNTCPLCNTPVAYLIVGVTASGSFSTIPIVNDPR 192

Query: 2808 TRVEAEAAVRAGTAVDFIWTGNPRTAPRSLSLGGHTVRALSPTPPWPGTDDEDDDLAD 2981
            TRVEAEAAVRAGTAVDFIWTGN RTAPRSLSLGGHTVRALSPTPPWPGTDDEDDDLAD
Sbjct: 193  TRVEAEAAVRAGTAVDFIWTGNQRTAPRSLSLGGHTVRALSPTPPWPGTDDEDDDLAD 250

Score =  1333 bits (2958), Expect(2) = 0.0
Identities = 579/582 (99%), Positives = 579/582 (99%)
Frame = +3

Query: 3078 DYVPPAPRRAPRRGGGGAGATRGTSQPAATRPAPPGAPRSSSSGGAPLRAGVGSGSGGGP 3257
            DYVPPAPRRAPRRGGGGAGATRGTSQPAATRPAPPGAPRSSSSGGAPLRAGVGSGSGGGP
Sbjct: 252  DYVPPAPRRAPRRGGGGAGATRGTSQPAATRPAPPGAPRSSSSGGAPLRAGVGSGSGGGP 311

Query: 3258 AVAAVVPRVASLPPAAGGGRAQARRVGEDAAAAEGRTPPARQPRAAQEPPIVISDSPPPS 3437
            AVAAVVPRVASLPPAAGGGRAQARRVGEDAAAAEGRTPPA QPRAAQEPPIVISDSPPPS
Sbjct: 312  AVAAVVPRVASLPPAAGGGRAQARRVGEDAAAAEGRTPPAGQPRAAQEPPIVISDSPPPS 371

Query: 3438 PRRPAGPGPLSLFSSSSAQVSSGPGGGGLPQSSGRAARPRAAVAPRVRSPPRAAAAPVVS 3617
            PRRPAGPGPLS FSSSSAQVSSGPGGGGLPQSSGRAARPRAAVAPRVRSPPRAAAAPVVS
Sbjct: 372  PRRPAGPGPLSFFSSSSAQVSSGPGGGGLPQSSGRAARPRAAVAPRVRSPPRAAAAPVVS 431

Query: 3618 ASADAAGPAPPAVPVDAHRAPRSRMTQAQTDTQAQSLGRAGATDARGSGGPGAEGGPGVP 3797
            ASADAAGPAPPAVPVDAHRAPRSRMTQAQTDTQAQSLGRAGATDARGSGGPGAEGGPGVP
Sbjct: 432  ASADAAGPAPPAVPVDAHRAPRSRMTQAQTDTQAQSLGRAGATDARGSGGPGAEGGPGVP 491

Query: 3798 RGTNTPGAAPHAAEGAAARPRKRRGSDSGPAASSSASSSAAPRSPLAPQGVGAKRAAPRR 3977
            RGTNTPGAAPHAAEGAAARPRKRRGSDSGPAASSSASSSAAPRSPLAPQGVGAKRAAPRR
Sbjct: 492  RGTNTPGAAPHAAEGAAARPRKRRGSDSGPAASSSASSSAAPRSPLAPQGVGAKRAAPRR 551

Query: 3978 APDSDSGDRGHGPLAPASAGAAPPSASPSSQAAVAAAASSSSSAASSSSSAASSSSSAAS 4157
            APDSDSGDRGHGPLAPASAGAAPPSASPSSQAAVAAAASSSSSAASSSSSAASSSSSAAS
Sbjct: 552  APDSDSGDRGHGPLAPASAGAAPPSASPSSQAAVAAAASSSSSAASSSSSAASSSSSAAS 611

Query: 4158 SSSSAASSSSAASSSSSSSSASSSAGGAGGSVASASGAGERRETSLGPRAAAPRGPRKCA 4337
            SSSSAASSSSAASSSSSSSSASSSAGGAGGSVASASGAGERRETSLGPRAAAPRGPRKCA
Sbjct: 612  SSSSAASSSSAASSSSSSSSASSSAGGAGGSVASASGAGERRETSLGPRAAAPRGPRKCA 671

Query: 4338 RKTRHAEGGPEPGARDPAPGLTRYLPIAGASSVVALAPYVNKTVTGDCLPVLDMETGHIG 4517
            RKTRHAEGGPEPGARDPAPGLTRYLPIAG SSVVALAPYVNKTVTGDCLPVLDMETGHIG
Sbjct: 672  RKTRHAEGGPEPGARDPAPGLTRYLPIAGVSSVVALAPYVNKTVTGDCLPVLDMETGHIG 731

Query: 4518 AYVVLVDQTGNVADLLRAAAPAWSRRTLLPEHARNCVRPPDYPTPPASEWNSLWMTPVGN 4697
            AYVVLVDQTGNVADLLRAAAPAWSRRTLLPEHARNCVRPPDYPTPPASEWNSLWMTPVGN
Sbjct: 732  AYVVLVDQTGNVADLLRAAAPAWSRRTLLPEHARNCVRPPDYPTPPASEWNSLWMTPVGN 791

Query: 4698 MLFDQGTLVGALDFHGLRSRHPWSREQGAPAPAGDAPAGHGE 4823
            MLFDQGTLVGALDFHGLRSRHPWSREQGAPAPAGDAPAGHGE
Sbjct: 792  MLFDQGTLVGALDFHGLRSRHPWSREQGAPAPAGDAPAGHGE 833


========================================================================================================================

gene_id            %id    %sim   %cov   %t5   %gap  %t3   start..stop      pep sz ref sz ref id            definition
MF564035.1.61      97.8   99.5   100.0  0.0   0.0   0.0   124098..124024   823    826    CAB06705.1        RL2-ii | ubiquitin E3 ligase ICP0
                                                          123616..122936                                   
                                                          122820..121105                                   
                    invalid splicing for intron  at 122935..122821

CLUSTAL 2.1 multiple sequence alignment


predicted       MEPRPGTSSRADPGPERPPRQTPGTQPAAPHAWGMLNDMQWLASSDSEEETEVGISDDDL
reference       MEPRPGTSSRADPGPERPPRQTPGTQPAAPHAWGMLNDMQWLASSDSEEETEVGISDDDL
                ************************************************************

predicted       HRDSTSEAGSTDTEMFEAGLMDAATPPARPPAERQGSPTPADAQGSCGGGPVGEEEAEAG
reference       HRDSTSEAGSTDTEMFEAGLMDAATPPARPPAERQGSPTPADAQGSCGGGPVGEEEAEAG
                ************************************************************

predicted       GGGDVCAVCTDEIAPPLRCQSFPCLHPFCIPCMKTWIPLRNTCPLCNTPVAYLIVGVTAS
reference       GGGDVCAVCTDEIAPPLRCQSFPCLHPFCIPCMKTWIPLRNTCPLCNTPVAYLIVGVTAS
                ************************************************************

predicted       GSFSTIPIVNDPRTRVEAEAAVRAGTAVDFIWTGNPRTAPRSLSLGGHTVRALSPTPPWP
reference       GSFSTIPIVNDPRTRVEAEAAVRAGTAVDFIWTGNPRTAPRSLSLGGHTVRALSPTPPWP
                ************************************************************

predicted       GTDDEDDDLADG-DYVPPAPRRAPRRGGGGAGATRGTSQPAATRPAPPGAPRSSSSGGAP
reference       GTDDEDDDLADGVDYVPPAPRRAPRRGGGGAGATRGTSQPAATRPAPPGAPRSSSSGGAP
                ************ ***********************************************

predicted       LRAGVGSGSGGGPAVAAVVPRVASLPPAAGGGRAQARRVGEDAAAAEGRTPPARQPRAAQ
reference       LRAGVGSGSGGGPAVAAVVPRVASLPPAAGGGRAQARRVGEDAAAAEGRTPPARQPRAAQ
                ************************************************************

predicted       EPPIVISDSPPPSPRRPAGPGPLSLFSSSSAQVSSGPGGGGLPQSSGRAARPRAAVAPRV
reference       EPPIVISDSPPPSPRRPAGPGPLSFVSSSSAQVSSGPGGGGLPQSSGRAARPRAAVAPRV
                ************************:.**********************************

predicted       RSPPRAAAAPVVSASADAAGPAPPAVPVDAHRAPRSRMTQAQTDTQAQSLGRAGATDARG
reference       RSPPRAAAAPVVSASADAAGPAPPAVPVDAHRAPRSRMTQAQTDTQAQSLGRAGATDARG
                ************************************************************

predicted       SGGPGAEGGPGVPRGTNTPGAAPHAAEGAAARPRKRRGSDSGPAASSSASSSAAPRSPLA
reference       SGGPGAEGGPGVPRGTNTPGAAPHAAEGAAARPRKRRGSDSGPAASSSASSSAAPRSPLA
                ************************************************************

predicted       PQGVGAKRAAPRRAPDSDSGDRGHGPLAPASAGAAPPSASPSSQAAVAAAASS--SSSAA
reference       PQGVGAKRAAPRRAPDSDSGDRGHGPLAPASAGAAPPSASPSSQAAVAAASSSSASSSSA
                **************************************************:**  ***:*

predicted       SSSSSSSSASSSAGGAGASSSSSSASSSAGGAGGSVASASGAGERRETSLGPRAAAPRGP
reference       SSSSASSSSASSSSASSSSASSSSASSSAGGAGGSVASASGAGERRETSLGPRAAAPRGP
                ****:***::**:..:.:*:****************************************

predicted       RKCARKTRHAEGGPEPGARDPAPGLTRYLPIAGASSVVALAPYVNKTVTGDCLPVLDMET
reference       RKCARKTRHAEGGPEPGARDPAPGLTRYLPIAGVSSVVALAPYVNKTVTGDCLPVLDMET
                *********************************.**************************

predicted       GHIGAYVVLVDQTGNVADLLRAAAPAWSRRTLLPEHARNCVRPPDYPTPPASEWNSLWMT
reference       GHIGAYVVLVDQTGNVADLLRAAAPAWSRRTLLPEHARNCVRPPDYPTPPASEWNSLWMT
                ************************************************************

predicted       PVGNMLFDQGTLVGALDFHGLRSRHPWSREQGAPAPAGDAPAGHGE
reference       PVGNMLFDQGTLVGALDFHGLRSRHPWSREQGAPAPAGDAPAGHGE
                **********************************************

>MF564035.1.62	124098	121105
ccgtgtgacggtcgggccgcattcgcaccccggcactgcgagcgacggagcggcggcccg
gcgggaggaggagacccggagagacagagactaacacccggcaagagagagaccgcgggc
cgccgtctcgagtctaccctaccccggctcATGGAACCCCGGCCCGGCACGAGCTCCCGG
GCGGACCCCGGCCCCGAGCGGCCGCCGCGGCAGACCCCCGGCACGgtgagagggcgaccc
ccgggtctcaggcccccccttttccccggaccacccggctgcgggttgggggtggtcgcg
ggcggtgggctcgggggcggggacgcttgacggggccgacccccggcccgcttaagcggt
cgggggacccccgtgggccgtgcgccgccccccgaccctttgggggggcgagggaggcag
ggaggagcccgagagcgggggacagggggggagacgaggggtcggaattcaaaggacgca
gaccacctttggttacggacccctttctcccccccttccgaacaaaaagcagcgggcggg
gggccggggtgagggagggacacgggggacacggcacgggggtcccgcctcacgccccgc
gccctctaaatcccccccgtttctttgtcaagCAGCCCGCCGCCCCGCACGCCTGGGGGA
TGCTCAACGACATGCAGTGGCTCGCCAGCAGCGACTCGGAGGAGGAGACCGAGGTGGGAA
TCTCTGACGACGACCTTCACCGCGACTCCACCTCCGAGGCGGGCAGCACGGACACGGAGA
TGTTCGAGGCGGGCCTGATGGACGCGGCCACGCCCCCGGCCCGGCCCCCGGCCGAGCGCC
AGGGCAGCCCCACGCCCGCCGACGCGCAGGGATCCTGCGGGGGTGGGCCCGTGGGTGAGG
AGGAAGCGGAAGCGGGAGGGGGGGGCGACGTGTGTGCCGTGTGCACGGACGAGATCGCCC
CGCCCCTGCGCTGCCAGAGTTTTCCCTGCCTGCACCCCTTCTGCATCCCGTGCATGAAGA
CCTGGATTCCGTTGCGCAACACGTGTCCCCTGTGCAACACCCCGGTGGCGTACCTGATAG
TGGGCGTGACCGCCAGCGGGTCGTTCAGCACCATCCCGATAGTGAACGACCCCCGGACCC
GCGTGGAGGCCGAGGCGGCCGTGCGGGCCGGCACGGCCGTGGACTTTATCTGGACGGGCA
ACCCGCGGACGGCCCCGCGCTCCCTGTCGCTGGGGGGACACACGGTCCGCGCCCTGTCGC
CCACCCCCCCGTGGCCCGGCACGGACGACGAGGACGATGACCTGGCCGACGGTgagggcg
ggcgggggtcgggcgggggtcgggcgggggtcgggcgggggtcgggcgggggtcgggcgg
gggtcgggcactaaccgggggttcccgtctctgtctccctctgcagcgGACTACGTCCCG
CCCGCCCCCCGAAGAGCGCCCCGGCGCGGGGGCGGCGGTGCGGGGGCGACCCGCGGAACC
TCCCAGCCCGCCGCGACCCGACCGGCGCCCCCTGGCGCCCCGCGGAGCAGCAGCAGCGGC
GGCGCCCCGTTGCGGGCGGGGGTGGGATCTGGGTCTGGGGGCGGCCCTGCCGTCGCGGCC
GTCGTGCCGAGAGTGGCCTCTCTTCCCCCTGCGGCCGGCGGGGGGCGCGCGCAGGCGCGG
CGGGTGGGCGAAGACGCCGCGGCGGCGGAGGGCAGGACGCCCCCCGCGAGACAGCCCCGC
GCGGCCCAGGAGCCCCCCATAGTCATCAGCGACTCTCCCCCGCCGTCTCCGCGCCGCCCC
GCGGGCCCCGGGCCGCTCTCCTTGTTCTCCTCCTCCTCCGCGCAGGTGTCCTCGGGCCCC
GGGGGGGGAGGTCTGCCACAGTCGTCGGGGCGCGCGGCGCGCCCCCGCGCGGCCGTCGCC
CCGCGCGTCCGGAGTCCGCCCCGCGCCGCCGCCGCCCCCGTGGTGTCTGCGAGCGCGGAC
GCGGCCGGGCCCGCGCCGCCCGCCGTGCCGGTGGACGCGCACCGCGCGCCCCGGTCGCGC
ATGACCCAGGCTCAGACCGACACCCAAGCACAGAGTCTGGGCCGGGCAGGCGCGACCGAC
GCGCGCGGGTCGGGAGGGCCGGGCGCGGAGGGAGGACCCGGGGTCCCCCGCGGCACCAAC
ACCCCCGGTGCCGCCCCCCACGCCGCGGAGGGGGCGGCGGCCCGCCCCCGGAAGAGGCGC
GGGTCGGACTCGGGCCCTGCGGCCTCGTCCTCCGCCTCTTCCTCCGCCGCCCCGCGCTCG
CCCCTCGCCCCCCAGGGGGTGGGGGCCAAGAGGGCGGCGCCGCGCCGGGCCCCGGACTCG
GACTCGGGCGACCGCGGCCACGGGCCGCTCGCCCCGGCGTCCGCGGGCGCCGCGCCCCCG
TCGGCGTCTCCGTCGTCCCAGGCCGCGGTCGCCGCCGCCGCCTCCTCTTCCTCCTCCGCC
GCCTCCTCTTCCTCCTCCTCCTCCTCCGCCTCTTCCTCTGCGGGCGGGGCTGGTGCTTCC
TCCTCCTCCTCCTCCGCCTCTTCCTCTGCGGGCGGGGCTGGTGGGAGCGTCGCGTCCGCG
TCCGGCGCTGGGGAGAGACGAGAAACCTCCCTCGGCCCCCGCGCTGCTGCGCCGCGGGGG
CCGAGGAAGTGTGCCAGGAAGACGCGCCACGCGGAGGGCGGCCCCGAGCCCGGGGCCCGC
GACCCGGCGCCCGGCCTCACGCGCTACCTGCCCATCGCGGGGGCCTCGAGCGTCGTGGCC
CTGGCGCCTTACGTGAACAAGACGGTCACGGGGGACTGCCTGCCCGTCCTGGACATGGAG
ACGGGCCACATAGGGGCCTACGTGGTCCTCGTGGACCAGACGGGGAACGTGGCGGACCTG
CTGCGGGCCGCGGCCCCCGCGTGGAGCCGCCGCACCCTGCTCCCCGAGCACGCGCGCAAC
TGCGTGAGGCCCCCCGACTACCCGACGCCCCCCGCGTCGGAGTGGAACAGCCTCTGGATG
ACCCCGGTGGGCAACATGCTCTTTGACCAGGGCACCCTGGTGGGCGCGCTGGACTTCCAC
GGCCTCCGGTCGCGCCACCCGTGGTCTCGGGAGCAGGGCGCGCCCGCGCCGGCCGGCGAC
GCCCCCGCGGGCCACGGGGAGTAGggggagctaacactcggcttgctgcccgaaggaagc
cgccccccaccggaccaccggccgaggcgcctcgggggcagggggaggtgggggggaaag
acggggaggagacaggaagtgggggtgggagtggggggggacggacacggcccc

Length = 826

Score =  68.0 bits (142), Expect(8) = 0.0
Identities = 26/30 (86%), Positives = 26/30 (86%)
Frame = -3

Query: 124098 MEPRPGTSSRADPGPERPPRQTPGTVRGRP 124009
              MEPRPGTSSRADPGPERPPRQTPGT    P
Sbjct: 1      MEPRPGTSSRADPGPERPPRQTPGTQPAAP 30

Score =   571 bits (1241), Expect(2) = 0.0
Identities = 227/227 (100%), Positives = 227/227 (100%)
Frame = -2

Query: 123616 QPAAPHAWGMLNDMQWLASSDSEEETEVGISDDDLHRDSTSEAGSTDTEMFEAGLMDAAT 123437
              QPAAPHAWGMLNDMQWLASSDSEEETEVGISDDDLHRDSTSEAGSTDTEMFEAGLMDAAT
Sbjct: 26     QPAAPHAWGMLNDMQWLASSDSEEETEVGISDDDLHRDSTSEAGSTDTEMFEAGLMDAAT 85

Query: 123436 PPARPPAERQGSPTPADAQGSCGGGPVGEEEAEAGGGGDVCAVCTDEIAPPLRCQSFPCL 123257
              PPARPPAERQGSPTPADAQGSCGGGPVGEEEAEAGGGGDVCAVCTDEIAPPLRCQSFPCL
Sbjct: 86     PPARPPAERQGSPTPADAQGSCGGGPVGEEEAEAGGGGDVCAVCTDEIAPPLRCQSFPCL 145

Query: 123256 HPFCIPCMKTWIPLRNTCPLCNTPVAYLIVGVTASGSFSTIPIVNDPRTRVEAEAAVRAG 123077
              HPFCIPCMKTWIPLRNTCPLCNTPVAYLIVGVTASGSFSTIPIVNDPRTRVEAEAAVRAG
Sbjct: 146    HPFCIPCMKTWIPLRNTCPLCNTPVAYLIVGVTASGSFSTIPIVNDPRTRVEAEAAVRAG 205

Query: 123076 TAVDFIWTGNPRTAPRSLSLGGHTVRALSPTPPWPGTDDEDDDLADG 122936
              TAVDFIWTGNPRTAPRSLSLGGHTVRALSPTPPWPGTDDEDDDLADG
Sbjct: 206    TAVDFIWTGNPRTAPRSLSLGGHTVRALSPTPPWPGTDDEDDDLADG 252

Score =   835 bits (1817), Expect(2) = 0.0
Identities = 358/388 (92%), Positives = 375/388 (96%)
Frame = -3

Query: 122820 DYVPPAPRRAPRRGGGGAGATRGTSQPAATRPAPPGAPRSSSSGGAPLRAGVGSGSGGGP 122641
              DYVPPAPRRAPRRGGGGAGATRGTSQPAATRPAPPGAPRSSSSGGAPLRAGVGSGSGGGP
Sbjct: 254    DYVPPAPRRAPRRGGGGAGATRGTSQPAATRPAPPGAPRSSSSGGAPLRAGVGSGSGGGP 313

Query: 122640 AVAAVVPRVASLPPAAGGGRAQARRVGEDAAAAEGRTPPARQPRAAQEPPIVISDSPPPS 122461
              AVAAVVPRVASLPPAAGGGRAQARRVGEDAAAAEGRTPPARQPRAAQEPPIVISDSPPPS
Sbjct: 314    AVAAVVPRVASLPPAAGGGRAQARRVGEDAAAAEGRTPPARQPRAAQEPPIVISDSPPPS 373

Query: 122460 PRRPAGPGPLSLFSSSSAQVSSGPGGGGLPQSSGRAARPRAAVAPRVRSPPRAAAAPVVS 122281
              PRRPAGPGPLS  SSSSAQVSSGPGGGGLPQSSGRAARPRAAVAPRVRSPPRAAAAPVVS
Sbjct: 374    PRRPAGPGPLSFVSSSSAQVSSGPGGGGLPQSSGRAARPRAAVAPRVRSPPRAAAAPVVS 433

Query: 122280 ASADAAGPAPPAVPVDAHRAPRSRMTQAQTDTQAQSLGRAGATDARGSGGPGAEGGPGVP 122101
              ASADAAGPAPPAVPVDAHRAPRSRMTQAQTDTQAQSLGRAGATDARGSGGPGAEGGPGVP
Sbjct: 434    ASADAAGPAPPAVPVDAHRAPRSRMTQAQTDTQAQSLGRAGATDARGSGGPGAEGGPGVP 493

Query: 122100 RGTNTPGAAPHAAEGAAARPRKRRGSDSGPAASSSASSSAAPRSPLAPQGVGAKRAAPRR 121921
              RGTNTPGAAPHAAEGAAARPRKRRGSDSGPAASSSASSSAAPRSPLAPQGVGAKRAAPRR
Sbjct: 494    RGTNTPGAAPHAAEGAAARPRKRRGSDSGPAASSSASSSAAPRSPLAPQGVGAKRAAPRR 553

Query: 121920 APDSDSGDRGHGPLAPASAGAAPPSASPSSQAAVAAAASSSSSAASSSSSSSSASSSAGG 121741
              APDSDSGDRGHGPLAPASAGAAPPSASPSSQAAVAAA+SSS+S++S+SSSS+S+SS++  
Sbjct: 554    APDSDSGDRGHGPLAPASAGAAPPSASPSSQAAVAAASSSSASSSSASSSSASSSSASSS 613

Query: 121740 AGASSSSSSASSSAGGAGGSVASASGAG 121657
              + +SSS+SS+S+S+   G   + AS +G
Sbjct: 614    SASSSSASSSSASSSAGGAGGSVASASG 641

Score =   547 bits (1188), Expect(8) = 0.0
Identities = 230/269 (85%), Positives = 243/269 (90%)
Frame = -3

Query: 121914 DSDSGDRGHGPLAPASAGAAPPSASPSSQAAVAAAASSSSSAASSSSSSSSASSSAGGAG 121735
              DS     G    A A A     S S  +  A A+++S+SSS+ASSSS+SSS++SS+  + 
Sbjct: 558    DSGDRGHGPLAPASAGAAPPSASPSSQAAVAAASSSSASSSSASSSSASSSSASSSSASS 617

Query: 121734 ASSSSSSASSSAGGAGGSVASASGAGERRETSLGPRAAAPRGPRKCARKTRHAEGGPEPG 121555
              +S+SSSSASSSAGGAGGSVASASGAGERRETSLGPRAAAPRGPRKCARKTRHAEGGPEPG
Sbjct: 618    SSASSSSASSSAGGAGGSVASASGAGERRETSLGPRAAAPRGPRKCARKTRHAEGGPEPG 677

Query: 121554 ARDPAPGLTRYLPIAGASSVVALAPYVNKTVTGDCLPVLDMETGHIGAYVVLVDQTGNVA 121375
              ARDPAPGLTRYLPIAG SSVVALAPYVNKTVTGDCLPVLDMETGHIGAYVVLVDQTGNVA
Sbjct: 678    ARDPAPGLTRYLPIAGVSSVVALAPYVNKTVTGDCLPVLDMETGHIGAYVVLVDQTGNVA 737

Query: 121374 DLLRAAAPAWSRRTLLPEHARNCVRPPDYPTPPASEWNSLWMTPVGNMLFDQGTLVGALD 121195
              DLLRAAAPAWSRRTLLPEHARNCVRPPDYPTPPASEWNSLWMTPVGNMLFDQGTLVGALD
Sbjct: 738    DLLRAAAPAWSRRTLLPEHARNCVRPPDYPTPPASEWNSLWMTPVGNMLFDQGTLVGALD 797

Query: 121194 FHGLRSRHPWSREQGAPAPAGDAPAGHGE 121108
              FHGLRSRHPWSREQGAPAPAGDAPAGHGE
Sbjct: 798    FHGLRSRHPWSREQGAPAPAGDAPAGHGE 826


========================================================================================================================

gene_id            %id    %sim   %cov   %t5   %gap  %t3   start..stop      pep sz ref sz ref id            definition
MF564034.1.2       99.4   99.6   100.0  0.0   0.0   0.0   1822..1896       832    833    AEV91397.2        RL2 | ubiquitin E3 ligase ICP0
                                                          2307..2981                                       
                                                          3078..4826                                       
                    invalid splicing for intron  at 2982..3077

CLUSTAL 2.1 multiple sequence alignment


predicted       MEPRPGTSSRADPGPERPPRQTPGTPAAPHAWGMLNDMQWLASSDSEEETEVGISDDDLH
reference       MEPRPGTSSRADPGPERPPRQTPGTPAAPHAWGMLNDMQWLASSDSEEETEVGISDDDLH
                ************************************************************

predicted       RDSTSEAGSTDTEMFEAGLMDAATPPARPPAERQGSPTPADAQGSCGGGPVGEEEAEAGG
reference       RDSTSEAGSTDTEMFEAGLMDAATPPARPPAERQGSPTPADAQGSCGGGPVGEEEAEAGG
                ************************************************************

predicted       GGDVCAVCTDEIAPPLRCQSFPCLHPFCIPCMKTWIPLRNTCPLCNTPVAYLIVGVTASG
reference       GGDVCAVCTDEIAPPLRCQSFPCLHPFCIPCMKTWIPLRNTCPLCNTPVAYLIVGVTASG
                ************************************************************

predicted       SFSTIPIVNDPRTRVEAEAAVRAGTAVDFIWTGNPRTAPRSLSLGGHTVRALSPTPPWPG
reference       SFSTIPIVNDPRTRVEAEAAVRAGTAVDFIWTGNQRTAPRSLSLGGHTVRALSPTPPWPG
                ********************************** *************************

predicted       TDDEDDDLAD-DYVPPAPRRAPRRGGGGAGATRGTSQPAATRPAPPGAPRSSSSGGAPLR
reference       TDDEDDDLADVDYVPPAPRRAPRRGGGGAGATRGTSQPAATRPAPPGAPRSSSSGGAPLR
                ********** *************************************************

predicted       AGVGSGSGGGPAVAAVVPRVASLPPAAGGGRAQARRVGEDAAAAEGRTPPARQPRAAQEP
reference       AGVGSGSGGGPAVAAVVPRVASLPPAAGGGRAQARRVGEDAAAAEGRTPPAGQPRAAQEP
                *************************************************** ********

predicted       PIVISDSPPPSPRRPAGPGPLSLFSSSSAQVSSGPGGGGLPQSSGRAARPRAAVAPRVRS
reference       PIVISDSPPPSPRRPAGPGPLSFFSSSSAQVSSGPGGGGLPQSSGRAARPRAAVAPRVRS
                **********************:*************************************

predicted       PPRAAAAPVVSASADAAGPAPPAVPVDAHRAPRSRMTQAQTDTQAQSLGRAGATDARGSG
reference       PPRAAAAPVVSASADAAGPAPPAVPVDAHRAPRSRMTQAQTDTQAQSLGRAGATDARGSG
                ************************************************************

predicted       GPGAEGGPGVPRGTNTPGAAPHAAEGAAARPRKRRGSDSGPAASSSASSSAAPRSPLAPQ
reference       GPGAEGGPGVPRGTNTPGAAPHAAEGAAARPRKRRGSDSGPAASSSASSSAAPRSPLAPQ
                ************************************************************

predicted       GVGAKRAAPRRAPDSDSGDRGHGPLAPASAGAAPPSASPSSQAAVAAAASSSSSAASSSS
reference       GVGAKRAAPRRAPDSDSGDRGHGPLAPASAGAAPPSASPSSQAAVAAAASSSSSAASSSS
                ************************************************************

predicted       SAASSSSSAASSSSSAASSSSAASSSSSSSSASSSAGGAGGSVASASGAGERRETSLGPR
reference       SAASSSSSAASSSSSAASSSSAASSSSSSSSASSSAGGAGGSVASASGAGERRETSLGPR
                ************************************************************

predicted       AAAPRGPRKCARKTRHAEGGPEPGARDPAPGLTRYLPIAGASSVVALAPYVNKTVTGDCL
reference       AAAPRGPRKCARKTRHAEGGPEPGARDPAPGLTRYLPIAGVSSVVALAPYVNKTVTGDCL
                ****************************************.*******************

predicted       PVLDMETGHIGAYVVLVDQTGNVADLLRAAAPAWSRRTLLPEHARNCVRPPDYPTPPASE
reference       PVLDMETGHIGAYVVLVDQTGNVADLLRAAAPAWSRRTLLPEHARNCVRPPDYPTPPASE
                ************************************************************

predicted       WNSLWMTPVGNMLFDQGTLVGALDFHGLRSRHPWSREQGAPAPAGDAPAGHGE
reference       WNSLWMTPVGNMLFDQGTLVGALDFHGLRSRHPWSREQGAPAPAGDAPAGHGE
                *****************************************************

>MF564034.1.2	1822	4826
ccgtgtgacggtcgggccgcattcgcaccccggcactgcgagcgacggagcggcggcccg
gcgggaggaggagacccggagagacagagactaacacccggcaagagagagaccgcgggc
cgccgtctcgagtctaccctaccccggctcATGGAACCCCGGCCCGGCACGAGCTCCCGG
GCGGACCCCGGCCCCGAGCGGCCGCCGCGGCAGACCCCCGGCACGgtgagagggcgaccc
ccgggtctcaggcccccccttttccccggaccacccggctgcgggttgggggtggtcgcg
ggcggtgggctcgggggcggggacgcttgacggggccgacccccggcccgcttaagcggt
cgggggacccccgtgggccgtgcgccgccccccgaccctttgggggggcgagggaggcag
ggaggagcccgagagcgggggacagggggggagacgaggggtcggaattcaaaggacgca
gaccacctttggttacggacccctttctcccccccttccgaacaaaaagcagcgggcggg
gggccggggtgagggagggacacgggggacacggcacgggggtcccgcctcacgccccgc
gccctctaaatcccccccgtttctttgtcaagcagCCCGCCGCCCCGCACGCCTGGGGGA
TGCTCAACGACATGCAGTGGCTCGCCAGCAGCGACTCGGAGGAGGAGACCGAGGTGGGAA
TCTCTGACGACGACCTTCACCGCGACTCCACCTCCGAGGCGGGCAGCACGGACACGGAGA
TGTTCGAGGCGGGCCTGATGGACGCGGCCACGCCCCCGGCCCGGCCCCCGGCCGAGCGCC
AGGGCAGCCCCACGCCCGCCGACGCGCAGGGATCCTGCGGGGGTGGGCCCGTGGGTGAGG
AGGAAGCGGAAGCGGGAGGGGGGGGCGACGTGTGTGCCGTGTGCACGGACGAGATCGCCC
CGCCCCTGCGCTGCCAGAGTTTTCCCTGCCTGCACCCCTTCTGCATCCCGTGCATGAAGA
CCTGGATTCCGTTGCGCAACACGTGTCCCCTGTGCAACACCCCGGTGGCGTACCTGATAG
TGGGCGTGACCGCCAGCGGGTCGTTCAGCACCATCCCGATAGTGAACGACCCCCGGACCC
GCGTGGAGGCCGAGGCGGCCGTGCGGGCCGGCACGGCCGTGGACTTTATCTGGACGGGCA
ACCCGCGGACGGCCCCGCGCTCCCTGTCGCTGGGGGGACACACGGTCCGCGCCCTGTCGC
CCACCCCCCCGTGGCCCGGCACGGACGACGAGGACGATGACCTGGCCGACggtgagggcg
ggcgggggtcgggcgggggtcgggcgggggtcgggcgggggtcgggcactaaccgggggt
tcccgtctctgtctccctctgcagcgGACTACGTCCCGCCCGCCCCCCGAAGAGCGCCCC
GGCGCGGGGGCGGCGGTGCGGGGGCGACCCGCGGAACCTCCCAGCCCGCCGCGACCCGAC
CGGCGCCCCCTGGCGCCCCGCGGAGCAGCAGCAGCGGCGGCGCCCCGTTGCGGGCGGGGG
TGGGATCTGGGTCTGGGGGCGGCCCTGCCGTCGCGGCCGTCGTGCCGAGAGTGGCCTCTC
TTCCCCCTGCGGCCGGCGGGGGGCGCGCGCAGGCGCGGCGGGTGGGCGAAGACGCCGCGG
CGGCGGAGGGCAGGACGCCCCCCGCGAGACAGCCCCGCGCGGCCCAGGAGCCCCCCATAG
TCATCAGCGACTCTCCCCCGCCGTCTCCGCGCCGCCCCGCGGGCCCCGGGCCGCTCTCCT
TGTTCTCCTCCTCCTCCGCGCAGGTGTCCTCGGGCCCCGGGGGGGGAGGTCTGCCACAGT
CGTCGGGGCGCGCGGCGCGCCCCCGCGCGGCCGTCGCCCCGCGCGTCCGGAGTCCGCCCC
GCGCCGCCGCCGCCCCCGTGGTGTCTGCGAGCGCGGACGCGGCCGGGCCCGCGCCGCCCG
CCGTGCCGGTGGACGCGCACCGCGCGCCCCGGTCGCGCATGACCCAGGCTCAGACCGACA
CCCAAGCACAGAGTCTGGGCCGGGCAGGCGCGACCGACGCGCGCGGGTCGGGAGGGCCGG
GCGCGGAGGGAGGACCCGGGGTCCCCCGCGGCACCAACACCCCCGGTGCCGCCCCCCACG
CCGCGGAGGGGGCGGCGGCCCGCCCCCGGAAGAGGCGCGGGTCGGACTCGGGCCCTGCGG
CCTCGTCCTCCGCCTCTTCCTCCGCCGCCCCGCGCTCGCCCCTCGCCCCCCAGGGGGTGG
GGGCCAAGAGGGCGGCGCCGCGCCGGGCCCCGGACTCGGACTCGGGCGACCGCGGCCACG
GGCCGCTCGCCCCGGCGTCCGCGGGCGCCGCGCCCCCGTCGGCGTCTCCGTCGTCCCAGG
CCGCGGTCGCCGCCGCCGCCTCCTCTTCCTCCTCCGCCGCCTCCTCTTCCTCCTCCGCCG
CCTCCTCTTCCTCCTCCGCCGCCTCCTCTTCCTCCTCCGCCGCCTCTTCCTCCTCCGCCG
CCTCCTCTTCCTCCTCCTCCTCCTCCGCCTCTTCCTCTGCGGGCGGGGCTGGTGGGAGCG
TCGCGTCCGCGTCCGGCGCTGGGGAGAGACGAGAAACCTCCCTCGGCCCCCGCGCTGCTG
CGCCGCGGGGGCCGAGGAAGTGTGCCAGGAAGACGCGCCACGCGGAGGGCGGCCCCGAGC
CCGGGGCCCGCGACCCGGCGCCCGGCCTCACGCGCTACCTGCCCATCGCGGGGGCCTCGA
GCGTCGTGGCCCTGGCGCCTTACGTGAACAAGACGGTCACGGGGGACTGCCTGCCCGTCC
TGGACATGGAGACGGGCCACATAGGGGCCTACGTGGTCCTCGTGGACCAGACGGGGAACG
TGGCGGACCTGCTGCGGGCCGCGGCCCCCGCGTGGAGCCGCCGCACCCTGCTCCCCGAGC
ACGCGCGCAACTGCGTGAGGCCCCCCGACTACCCGACGCCCCCCGCGTCGGAGTGGAACA
GCCTCTGGATGACCCCGGTGGGCAACATGCTCTTTGACCAGGGCACCCTGGTGGGCGCGC
TGGACTTCCACGGCCTCCGGTCGCGCCACCCGTGGTCTCGGGAGCAGGGCGCGCCCGCGC
CGGCCGGCGACGCCCCCGCGGGCCACGGGGAGTAGggggagctaacactcggcttgctgc
ccgaaggaagccgccccccaccggaccaccggccgaggcgcctcgggggcagggggaggt
gggggggaaagacggggaggagacaggaagtgggggtgggagggggggggacggacacgg
ccccg

Length = 833

Score =   560 bits (1240), Expect(2) = 0.0
Identities = 229/238 (96%), Positives = 229/238 (96%)
Frame = +3

Query: 2268 PRPLNPPRFFVKQPAAPHAWGMLNDMQWLASSDSEEETEVGISDDDLHRDSTSEAGSTDT 2447
            P P  PPR     PAAPHAWGMLNDMQWLASSDSEEETEVGISDDDLHRDSTSEAGSTDT
Sbjct: 13   PGPERPPRQTPGTPAAPHAWGMLNDMQWLASSDSEEETEVGISDDDLHRDSTSEAGSTDT 72

Query: 2448 EMFEAGLMDAATPPARPPAERQGSPTPADAQGSCGGGPVGEEEAEAGGGGDVCAVCTDEI 2627
            EMFEAGLMDAATPPARPPAERQGSPTPADAQGSCGGGPVGEEEAEAGGGGDVCAVCTDEI
Sbjct: 73   EMFEAGLMDAATPPARPPAERQGSPTPADAQGSCGGGPVGEEEAEAGGGGDVCAVCTDEI 132

Query: 2628 APPLRCQSFPCLHPFCIPCMKTWIPLRNTCPLCNTPVAYLIVGVTASGSFSTIPIVNDPR 2807
            APPLRCQSFPCLHPFCIPCMKTWIPLRNTCPLCNTPVAYLIVGVTASGSFSTIPIVNDPR
Sbjct: 133  APPLRCQSFPCLHPFCIPCMKTWIPLRNTCPLCNTPVAYLIVGVTASGSFSTIPIVNDPR 192

Query: 2808 TRVEAEAAVRAGTAVDFIWTGNPRTAPRSLSLGGHTVRALSPTPPWPGTDDEDDDLAD 2981
            TRVEAEAAVRAGTAVDFIWTGN RTAPRSLSLGGHTVRALSPTPPWPGTDDEDDDLAD
Sbjct: 193  TRVEAEAAVRAGTAVDFIWTGNQRTAPRSLSLGGHTVRALSPTPPWPGTDDEDDDLAD 250

Score =  1333 bits (2958), Expect(2) = 0.0
Identities = 579/582 (99%), Positives = 579/582 (99%)
Frame = +3

Query: 3078 DYVPPAPRRAPRRGGGGAGATRGTSQPAATRPAPPGAPRSSSSGGAPLRAGVGSGSGGGP 3257
            DYVPPAPRRAPRRGGGGAGATRGTSQPAATRPAPPGAPRSSSSGGAPLRAGVGSGSGGGP
Sbjct: 252  DYVPPAPRRAPRRGGGGAGATRGTSQPAATRPAPPGAPRSSSSGGAPLRAGVGSGSGGGP 311

Query: 3258 AVAAVVPRVASLPPAAGGGRAQARRVGEDAAAAEGRTPPARQPRAAQEPPIVISDSPPPS 3437
            AVAAVVPRVASLPPAAGGGRAQARRVGEDAAAAEGRTPPA QPRAAQEPPIVISDSPPPS
Sbjct: 312  AVAAVVPRVASLPPAAGGGRAQARRVGEDAAAAEGRTPPAGQPRAAQEPPIVISDSPPPS 371

Query: 3438 PRRPAGPGPLSLFSSSSAQVSSGPGGGGLPQSSGRAARPRAAVAPRVRSPPRAAAAPVVS 3617
            PRRPAGPGPLS FSSSSAQVSSGPGGGGLPQSSGRAARPRAAVAPRVRSPPRAAAAPVVS
Sbjct: 372  PRRPAGPGPLSFFSSSSAQVSSGPGGGGLPQSSGRAARPRAAVAPRVRSPPRAAAAPVVS 431

Query: 3618 ASADAAGPAPPAVPVDAHRAPRSRMTQAQTDTQAQSLGRAGATDARGSGGPGAEGGPGVP 3797
            ASADAAGPAPPAVPVDAHRAPRSRMTQAQTDTQAQSLGRAGATDARGSGGPGAEGGPGVP
Sbjct: 432  ASADAAGPAPPAVPVDAHRAPRSRMTQAQTDTQAQSLGRAGATDARGSGGPGAEGGPGVP 491

Query: 3798 RGTNTPGAAPHAAEGAAARPRKRRGSDSGPAASSSASSSAAPRSPLAPQGVGAKRAAPRR 3977
            RGTNTPGAAPHAAEGAAARPRKRRGSDSGPAASSSASSSAAPRSPLAPQGVGAKRAAPRR
Sbjct: 492  RGTNTPGAAPHAAEGAAARPRKRRGSDSGPAASSSASSSAAPRSPLAPQGVGAKRAAPRR 551

Query: 3978 APDSDSGDRGHGPLAPASAGAAPPSASPSSQAAVAAAASSSSSAASSSSSAASSSSSAAS 4157
            APDSDSGDRGHGPLAPASAGAAPPSASPSSQAAVAAAASSSSSAASSSSSAASSSSSAAS
Sbjct: 552  APDSDSGDRGHGPLAPASAGAAPPSASPSSQAAVAAAASSSSSAASSSSSAASSSSSAAS 611

Query: 4158 SSSSAASSSSAASSSSSSSSASSSAGGAGGSVASASGAGERRETSLGPRAAAPRGPRKCA 4337
            SSSSAASSSSAASSSSSSSSASSSAGGAGGSVASASGAGERRETSLGPRAAAPRGPRKCA
Sbjct: 612  SSSSAASSSSAASSSSSSSSASSSAGGAGGSVASASGAGERRETSLGPRAAAPRGPRKCA 671

Query: 4338 RKTRHAEGGPEPGARDPAPGLTRYLPIAGASSVVALAPYVNKTVTGDCLPVLDMETGHIG 4517
            RKTRHAEGGPEPGARDPAPGLTRYLPIAG SSVVALAPYVNKTVTGDCLPVLDMETGHIG
Sbjct: 672  RKTRHAEGGPEPGARDPAPGLTRYLPIAGVSSVVALAPYVNKTVTGDCLPVLDMETGHIG 731

Query: 4518 AYVVLVDQTGNVADLLRAAAPAWSRRTLLPEHARNCVRPPDYPTPPASEWNSLWMTPVGN 4697
            AYVVLVDQTGNVADLLRAAAPAWSRRTLLPEHARNCVRPPDYPTPPASEWNSLWMTPVGN
Sbjct: 732  AYVVLVDQTGNVADLLRAAAPAWSRRTLLPEHARNCVRPPDYPTPPASEWNSLWMTPVGN 791

Query: 4698 MLFDQGTLVGALDFHGLRSRHPWSREQGAPAPAGDAPAGHGE 4823
            MLFDQGTLVGALDFHGLRSRHPWSREQGAPAPAGDAPAGHGE
Sbjct: 792  MLFDQGTLVGALDFHGLRSRHPWSREQGAPAPAGDAPAGHGE 833


========================================================================================================================

gene_id            %id    %sim   %cov   %t5   %gap  %t3   start..stop      pep sz ref sz ref id            definition
MF564034.1.61      99.4   99.6   100.0  0.0   0.0   0.0   124110..124036   832    833    AEV91397.2        RL2-ii | ubiquitin E3 ligase ICP0
                                                          123625..122951                                   
                                                          122854..121106                                   
                    invalid splicing for intron  at 122950..122855

CLUSTAL 2.1 multiple sequence alignment


predicted       MEPRPGTSSRADPGPERPPRQTPGTPAAPHAWGMLNDMQWLASSDSEEETEVGISDDDLH
reference       MEPRPGTSSRADPGPERPPRQTPGTPAAPHAWGMLNDMQWLASSDSEEETEVGISDDDLH
                ************************************************************

predicted       RDSTSEAGSTDTEMFEAGLMDAATPPARPPAERQGSPTPADAQGSCGGGPVGEEEAEAGG
reference       RDSTSEAGSTDTEMFEAGLMDAATPPARPPAERQGSPTPADAQGSCGGGPVGEEEAEAGG
                ************************************************************

predicted       GGDVCAVCTDEIAPPLRCQSFPCLHPFCIPCMKTWIPLRNTCPLCNTPVAYLIVGVTASG
reference       GGDVCAVCTDEIAPPLRCQSFPCLHPFCIPCMKTWIPLRNTCPLCNTPVAYLIVGVTASG
                ************************************************************

predicted       SFSTIPIVNDPRTRVEAEAAVRAGTAVDFIWTGNPRTAPRSLSLGGHTVRALSPTPPWPG
reference       SFSTIPIVNDPRTRVEAEAAVRAGTAVDFIWTGNQRTAPRSLSLGGHTVRALSPTPPWPG
                ********************************** *************************

predicted       TDDEDDDLAD-DYVPPAPRRAPRRGGGGAGATRGTSQPAATRPAPPGAPRSSSSGGAPLR
reference       TDDEDDDLADVDYVPPAPRRAPRRGGGGAGATRGTSQPAATRPAPPGAPRSSSSGGAPLR
                ********** *************************************************

predicted       AGVGSGSGGGPAVAAVVPRVASLPPAAGGGRAQARRVGEDAAAAEGRTPPARQPRAAQEP
reference       AGVGSGSGGGPAVAAVVPRVASLPPAAGGGRAQARRVGEDAAAAEGRTPPAGQPRAAQEP
                *************************************************** ********

predicted       PIVISDSPPPSPRRPAGPGPLSLFSSSSAQVSSGPGGGGLPQSSGRAARPRAAVAPRVRS
reference       PIVISDSPPPSPRRPAGPGPLSFFSSSSAQVSSGPGGGGLPQSSGRAARPRAAVAPRVRS
                **********************:*************************************

predicted       PPRAAAAPVVSASADAAGPAPPAVPVDAHRAPRSRMTQAQTDTQAQSLGRAGATDARGSG
reference       PPRAAAAPVVSASADAAGPAPPAVPVDAHRAPRSRMTQAQTDTQAQSLGRAGATDARGSG
                ************************************************************

predicted       GPGAEGGPGVPRGTNTPGAAPHAAEGAAARPRKRRGSDSGPAASSSASSSAAPRSPLAPQ
reference       GPGAEGGPGVPRGTNTPGAAPHAAEGAAARPRKRRGSDSGPAASSSASSSAAPRSPLAPQ
                ************************************************************

predicted       GVGAKRAAPRRAPDSDSGDRGHGPLAPASAGAAPPSASPSSQAAVAAAASSSSSAASSSS
reference       GVGAKRAAPRRAPDSDSGDRGHGPLAPASAGAAPPSASPSSQAAVAAAASSSSSAASSSS
                ************************************************************

predicted       SAASSSSSAASSSSSAASSSSAASSSSSSSSASSSAGGAGGSVASASGAGERRETSLGPR
reference       SAASSSSSAASSSSSAASSSSAASSSSSSSSASSSAGGAGGSVASASGAGERRETSLGPR
                ************************************************************

predicted       AAAPRGPRKCARKTRHAEGGPEPGARDPAPGLTRYLPIAGASSVVALAPYVNKTVTGDCL
reference       AAAPRGPRKCARKTRHAEGGPEPGARDPAPGLTRYLPIAGVSSVVALAPYVNKTVTGDCL
                ****************************************.*******************

predicted       PVLDMETGHIGAYVVLVDQTGNVADLLRAAAPAWSRRTLLPEHARNCVRPPDYPTPPASE
reference       PVLDMETGHIGAYVVLVDQTGNVADLLRAAAPAWSRRTLLPEHARNCVRPPDYPTPPASE
                ************************************************************

predicted       WNSLWMTPVGNMLFDQGTLVGALDFHGLRSRHPWSREQGAPAPAGDAPAGHGE
reference       WNSLWMTPVGNMLFDQGTLVGALDFHGLRSRHPWSREQGAPAPAGDAPAGHGE
                *****************************************************

>MF564034.1.62	124110	121106
ccgtgtgacggtcgggccgcattcgcaccccggcactgcgagcgacggagcggcggcccg
gcgggaggaggagacccggagagacagagactaacacccggcaagagagagaccgcgggc
cgccgtctcgagtctaccctaccccggctcATGGAACCCCGGCCCGGCACGAGCTCCCGG
GCGGACCCCGGCCCCGAGCGGCCGCCGCGGCAGACCCCCGGCACGgtgagagggcgaccc
ccgggtctcaggcccccccttttccccggaccacccggctgcgggttgggggtggtcgcg
ggcggtgggctcgggggcggggacgcttgacggggccgacccccggcccgcttaagcggt
cgggggacccccgtgggccgtgcgccgccccccgaccctttgggggggcgagggaggcag
ggaggagcccgagagcgggggacagggggggagacgaggggtcggaattcaaaggacgca
gaccacctttggttacggacccctttctcccccccttccgaacaaaaagcagcgggcggg
gggccggggtgagggagggacacgggggacacggcacgggggtcccgcctcacgccccgc
gccctctaaatcccccccgtttctttgtcaagcagCCCGCCGCCCCGCACGCCTGGGGGA
TGCTCAACGACATGCAGTGGCTCGCCAGCAGCGACTCGGAGGAGGAGACCGAGGTGGGAA
TCTCTGACGACGACCTTCACCGCGACTCCACCTCCGAGGCGGGCAGCACGGACACGGAGA
TGTTCGAGGCGGGCCTGATGGACGCGGCCACGCCCCCGGCCCGGCCCCCGGCCGAGCGCC
AGGGCAGCCCCACGCCCGCCGACGCGCAGGGATCCTGCGGGGGTGGGCCCGTGGGTGAGG
AGGAAGCGGAAGCGGGAGGGGGGGGCGACGTGTGTGCCGTGTGCACGGACGAGATCGCCC
CGCCCCTGCGCTGCCAGAGTTTTCCCTGCCTGCACCCCTTCTGCATCCCGTGCATGAAGA
CCTGGATTCCGTTGCGCAACACGTGTCCCCTGTGCAACACCCCGGTGGCGTACCTGATAG
TGGGCGTGACCGCCAGCGGGTCGTTCAGCACCATCCCGATAGTGAACGACCCCCGGACCC
GCGTGGAGGCCGAGGCGGCCGTGCGGGCCGGCACGGCCGTGGACTTTATCTGGACGGGCA
ACCCGCGGACGGCCCCGCGCTCCCTGTCGCTGGGGGGACACACGGTCCGCGCCCTGTCGC
CCACCCCCCCGTGGCCCGGCACGGACGACGAGGACGATGACCTGGCCGACggtgagggcg
ggcgggggtcgggcgggggtcgggcgggggtcgggcgggggtcgggcactaaccgggggt
tcccgtctctgtctccctctgcagcgGACTACGTCCCGCCCGCCCCCCGAAGAGCGCCCC
GGCGCGGGGGCGGCGGTGCGGGGGCGACCCGCGGAACCTCCCAGCCCGCCGCGACCCGAC
CGGCGCCCCCTGGCGCCCCGCGGAGCAGCAGCAGCGGCGGCGCCCCGTTGCGGGCGGGGG
TGGGATCTGGGTCTGGGGGCGGCCCTGCCGTCGCGGCCGTCGTGCCGAGAGTGGCCTCTC
TTCCCCCTGCGGCCGGCGGGGGGCGCGCGCAGGCGCGGCGGGTGGGCGAAGACGCCGCGG
CGGCGGAGGGCAGGACGCCCCCCGCGAGACAGCCCCGCGCGGCCCAGGAGCCCCCCATAG
TCATCAGCGACTCTCCCCCGCCGTCTCCGCGCCGCCCCGCGGGCCCCGGGCCGCTCTCCT
TGTTCTCCTCCTCCTCCGCGCAGGTGTCCTCGGGCCCCGGGGGGGGAGGTCTGCCACAGT
CGTCGGGGCGCGCGGCGCGCCCCCGCGCGGCCGTCGCCCCGCGCGTCCGGAGTCCGCCCC
GCGCCGCCGCCGCCCCCGTGGTGTCTGCGAGCGCGGACGCGGCCGGGCCCGCGCCGCCCG
CCGTGCCGGTGGACGCGCACCGCGCGCCCCGGTCGCGCATGACCCAGGCTCAGACCGACA
CCCAAGCACAGAGTCTGGGCCGGGCAGGCGCGACCGACGCGCGCGGGTCGGGAGGGCCGG
GCGCGGAGGGAGGACCCGGGGTCCCCCGCGGCACCAACACCCCCGGTGCCGCCCCCCACG
CCGCGGAGGGGGCGGCGGCCCGCCCCCGGAAGAGGCGCGGGTCGGACTCGGGCCCTGCGG
CCTCGTCCTCCGCCTCTTCCTCCGCCGCCCCGCGCTCGCCCCTCGCCCCCCAGGGGGTGG
GGGCCAAGAGGGCGGCGCCGCGCCGGGCCCCGGACTCGGACTCGGGCGACCGCGGCCACG
GGCCGCTCGCCCCGGCGTCCGCGGGCGCCGCGCCCCCGTCGGCGTCTCCGTCGTCCCAGG
CCGCGGTCGCCGCCGCCGCCTCCTCTTCCTCCTCCGCCGCCTCCTCTTCCTCCTCCGCCG
CCTCCTCTTCCTCCTCCGCCGCCTCCTCTTCCTCCTCCGCCGCCTCTTCCTCCTCCGCCG
CCTCCTCTTCCTCCTCCTCCTCCTCCGCCTCTTCCTCTGCGGGCGGGGCTGGTGGGAGCG
TCGCGTCCGCGTCCGGCGCTGGGGAGAGACGAGAAACCTCCCTCGGCCCCCGCGCTGCTG
CGCCGCGGGGGCCGAGGAAGTGTGCCAGGAAGACGCGCCACGCGGAGGGCGGCCCCGAGC
CCGGGGCCCGCGACCCGGCGCCCGGCCTCACGCGCTACCTGCCCATCGCGGGGGCCTCGA
GCGTCGTGGCCCTGGCGCCTTACGTGAACAAGACGGTCACGGGGGACTGCCTGCCCGTCC
TGGACATGGAGACGGGCCACATAGGGGCCTACGTGGTCCTCGTGGACCAGACGGGGAACG
TGGCGGACCTGCTGCGGGCCGCGGCCCCCGCGTGGAGCCGCCGCACCCTGCTCCCCGAGC
ACGCGCGCAACTGCGTGAGGCCCCCCGACTACCCGACGCCCCCCGCGTCGGAGTGGAACA
GCCTCTGGATGACCCCGGTGGGCAACATGCTCTTTGACCAGGGCACCCTGGTGGGCGCGC
TGGACTTCCACGGCCTCCGGTCGCGCCACCCGTGGTCTCGGGAGCAGGGCGCGCCCGCGC
CGGCCGGCGACGCCCCCGCGGGCCACGGGGAGTAGggggagctaacactcggcttgctgc
ccgaaggaagccgccccccaccggaccaccggccgaggcgcctcgggggcagggggaggt
gggggggaaagacggggaggagacaggaagtgggggtgggagtggggggggacggacacg
gcccc

Length = 833

Score =   560 bits (1240), Expect(2) = 0.0
Identities = 229/238 (96%), Positives = 229/238 (96%)
Frame = -2

Query: 123664 PRPLNPPRFFVKQPAAPHAWGMLNDMQWLASSDSEEETEVGISDDDLHRDSTSEAGSTDT 123485
              P P  PPR     PAAPHAWGMLNDMQWLASSDSEEETEVGISDDDLHRDSTSEAGSTDT
Sbjct: 13     PGPERPPRQTPGTPAAPHAWGMLNDMQWLASSDSEEETEVGISDDDLHRDSTSEAGSTDT 72

Query: 123484 EMFEAGLMDAATPPARPPAERQGSPTPADAQGSCGGGPVGEEEAEAGGGGDVCAVCTDEI 123305
              EMFEAGLMDAATPPARPPAERQGSPTPADAQGSCGGGPVGEEEAEAGGGGDVCAVCTDEI
Sbjct: 73     EMFEAGLMDAATPPARPPAERQGSPTPADAQGSCGGGPVGEEEAEAGGGGDVCAVCTDEI 132

Query: 123304 APPLRCQSFPCLHPFCIPCMKTWIPLRNTCPLCNTPVAYLIVGVTASGSFSTIPIVNDPR 123125
              APPLRCQSFPCLHPFCIPCMKTWIPLRNTCPLCNTPVAYLIVGVTASGSFSTIPIVNDPR
Sbjct: 133    APPLRCQSFPCLHPFCIPCMKTWIPLRNTCPLCNTPVAYLIVGVTASGSFSTIPIVNDPR 192

Query: 123124 TRVEAEAAVRAGTAVDFIWTGNPRTAPRSLSLGGHTVRALSPTPPWPGTDDEDDDLAD 122951
              TRVEAEAAVRAGTAVDFIWTGN RTAPRSLSLGGHTVRALSPTPPWPGTDDEDDDLAD
Sbjct: 193    TRVEAEAAVRAGTAVDFIWTGNQRTAPRSLSLGGHTVRALSPTPPWPGTDDEDDDLAD 250

Score =  1333 bits (2958), Expect(2) = 0.0
Identities = 579/582 (99%), Positives = 579/582 (99%)
Frame = -2

Query: 122854 DYVPPAPRRAPRRGGGGAGATRGTSQPAATRPAPPGAPRSSSSGGAPLRAGVGSGSGGGP 122675
              DYVPPAPRRAPRRGGGGAGATRGTSQPAATRPAPPGAPRSSSSGGAPLRAGVGSGSGGGP
Sbjct: 252    DYVPPAPRRAPRRGGGGAGATRGTSQPAATRPAPPGAPRSSSSGGAPLRAGVGSGSGGGP 311

Query: 122674 AVAAVVPRVASLPPAAGGGRAQARRVGEDAAAAEGRTPPARQPRAAQEPPIVISDSPPPS 122495
              AVAAVVPRVASLPPAAGGGRAQARRVGEDAAAAEGRTPPA QPRAAQEPPIVISDSPPPS
Sbjct: 312    AVAAVVPRVASLPPAAGGGRAQARRVGEDAAAAEGRTPPAGQPRAAQEPPIVISDSPPPS 371

Query: 122494 PRRPAGPGPLSLFSSSSAQVSSGPGGGGLPQSSGRAARPRAAVAPRVRSPPRAAAAPVVS 122315
              PRRPAGPGPLS FSSSSAQVSSGPGGGGLPQSSGRAARPRAAVAPRVRSPPRAAAAPVVS
Sbjct: 372    PRRPAGPGPLSFFSSSSAQVSSGPGGGGLPQSSGRAARPRAAVAPRVRSPPRAAAAPVVS 431

Query: 122314 ASADAAGPAPPAVPVDAHRAPRSRMTQAQTDTQAQSLGRAGATDARGSGGPGAEGGPGVP 122135
              ASADAAGPAPPAVPVDAHRAPRSRMTQAQTDTQAQSLGRAGATDARGSGGPGAEGGPGVP
Sbjct: 432    ASADAAGPAPPAVPVDAHRAPRSRMTQAQTDTQAQSLGRAGATDARGSGGPGAEGGPGVP 491

Query: 122134 RGTNTPGAAPHAAEGAAARPRKRRGSDSGPAASSSASSSAAPRSPLAPQGVGAKRAAPRR 121955
              RGTNTPGAAPHAAEGAAARPRKRRGSDSGPAASSSASSSAAPRSPLAPQGVGAKRAAPRR
Sbjct: 492    RGTNTPGAAPHAAEGAAARPRKRRGSDSGPAASSSASSSAAPRSPLAPQGVGAKRAAPRR 551

Query: 121954 APDSDSGDRGHGPLAPASAGAAPPSASPSSQAAVAAAASSSSSAASSSSSAASSSSSAAS 121775
              APDSDSGDRGHGPLAPASAGAAPPSASPSSQAAVAAAASSSSSAASSSSSAASSSSSAAS
Sbjct: 552    APDSDSGDRGHGPLAPASAGAAPPSASPSSQAAVAAAASSSSSAASSSSSAASSSSSAAS 611

Query: 121774 SSSSAASSSSAASSSSSSSSASSSAGGAGGSVASASGAGERRETSLGPRAAAPRGPRKCA 121595
              SSSSAASSSSAASSSSSSSSASSSAGGAGGSVASASGAGERRETSLGPRAAAPRGPRKCA
Sbjct: 612    SSSSAASSSSAASSSSSSSSASSSAGGAGGSVASASGAGERRETSLGPRAAAPRGPRKCA 671

Query: 121594 RKTRHAEGGPEPGARDPAPGLTRYLPIAGASSVVALAPYVNKTVTGDCLPVLDMETGHIG 121415
              RKTRHAEGGPEPGARDPAPGLTRYLPIAG SSVVALAPYVNKTVTGDCLPVLDMETGHIG
Sbjct: 672    RKTRHAEGGPEPGARDPAPGLTRYLPIAGVSSVVALAPYVNKTVTGDCLPVLDMETGHIG 731

Query: 121414 AYVVLVDQTGNVADLLRAAAPAWSRRTLLPEHARNCVRPPDYPTPPASEWNSLWMTPVGN 121235
              AYVVLVDQTGNVADLLRAAAPAWSRRTLLPEHARNCVRPPDYPTPPASEWNSLWMTPVGN
Sbjct: 732    AYVVLVDQTGNVADLLRAAAPAWSRRTLLPEHARNCVRPPDYPTPPASEWNSLWMTPVGN 791

Query: 121234 MLFDQGTLVGALDFHGLRSRHPWSREQGAPAPAGDAPAGHGE 121109
              MLFDQGTLVGALDFHGLRSRHPWSREQGAPAPAGDAPAGHGE
Sbjct: 792    MLFDQGTLVGALDFHGLRSRHPWSREQGAPAPAGDAPAGHGE 833


