========================================================================================================================

gene_id            %id    %sim   %cov   %t5   %gap  %t3   start..stop      pep sz ref sz ref id            definition
KP765763.1.2       96.0   98.2   100.0  0.0   0.0   0.0   1801..2699       300    299    BAM15589.1        V | protein V
                    stop codon embedded in CDS at 2517..2519
                    transcription exception 2486..2492:AAAAGGGGGGG

CLUSTAL 2.1 multiple sequence alignment


predicted       MAEEQAYHVNKGLECLKALRENPPDIEEIQEVSNIRGQTRNPGQEDGTASMQEEEVSQDL
reference       MAEEQAYHVNKGLECLKALRENPPDIEEIQEVSSIRDQTRNPGQENGTASMQEEEVSQDL
                *********************************.**.********:**************

predicted       DESHEPAKGSNYVGHVLQNNPGCGESNTALVEAEQPANDDVQPGPGIRCYHVYDHSGEEV
reference       DESHEPAKGSNYLGHVLQNNPGCGESNTALVEAEQPAKDDIQPGPGIRCYHVYDHSGEEV
                ************:************************:**:*******************

predicted       KGIEDADSLVVPAGAVSNRGFEGGEGSLDDSTEDSGEDYSEGNASSNWGYSFGLKPDRAA
reference       KGIEDADSLVVPAGAVSNRGFERGEGSPDDSTEDSGEDYSEGNASSNWGYSFGLKPDRAA
                ********************** **** ********************************

predicted       DVSMLMEEELSALLKTSRNVGIKKRDGMTLQFPHNPEGKTEDPECGSIKKGGHRREVSLT
reference       DVSMLMEEELSALLKTSRNVGIKKRDGKTLQFPHNPEGKTEDPECGSIKKG-HRREVSLT
                *************************** *********************** ********

predicted       XNGDSCWIDKWCNPICTQVNWGIIRAKCVCGECPPTCNECKDDPEMQTRVWYATPSQDLK
reference       WNGDSCWIDKWCNPICTQVNWGIIRAKCVCGECPPTCNECKDDPEMQTRVWYATPSQDIK
                 *********************************************************:*

>KP765763.1.2	1801	2699
tctataatgatagagagctactcaattaaatattcaagaccagtgttacatcaatcacca
attatccttctaaactcattataaaaaacttaggacccaggtccaacaatcccgatcaac
cattcatccgaccaaccgttctatctctaaATGGCAGAAGAGCAGGCCTATCATGTCAAT
AAAGGGCTGGAATGCCTCAAAGCCCTCAGAGAGAATCCTCCTGACATTGAGGAGATTCAA
GAGGTCAGCAATATCAGAGGTCAAACCCGCAACCCAGGCCAAGAGGATGGAACCGCAAGC
ATGCAAGAAGAAGAGGTCTCTCAGGATCTCGATGAATCACACGAGCCAGCAAAAGGATCA
AACTATGTCGGCCATGTACTCCAAAATAATCCGGGATGTGGAGAGAGCAACACTGCACTT
GTGGAGGCAGAGCAGCCAGCTAACGATGATGTCCAACCAGGACCTGGAATACGATGTTAT
CATGTTTATGATCACAGTGGTGAAGAGGTTAAGGGAATCGAAGATGCTGACAGTCTCGTG
GTACCTGCAGGCGCTGTCAGTAATCGAGGATTCGAGGGAGGAGAAGGAAGCCTTGATGAT
AGCACTGAGGATTCTGGCGAAGATTATTCCGAGGGAAATGCTTCATCTAACTGGGGATAT
TCTTTCGGCCTTAAACCAGACAGAGCGGCTGATGTGAGCATGCTGATGGAAGAGGAATTG
AGTGCTCTGCTCAAGACAAGCAGAAATGTGGGGATTAAGAAAAGGGATGGGATGACTCTG
CAGTTCCCACACAATCCCGAAGGTAAGACAGAGGATCCGGAGTGTGGATCCATTAAAAAG
GGCACAGGAGAGAGGTCAGCCTCACATAGAATGGGGATAGTTGCTGGATCGACAAATGGT
GCAACCCAATCTGCACTCAAGTCAACTGGGGGATCATCAGGGCCAAGTGTGTCTGCGGAG
AATGTCCGCCAACCTGCAATGAATGCAAAGATGACCCAGAAATGCAAACCCGAGTCTGGT
ACGCAACTCCCTCCCAGGACCTCAAATGAggctgaatctgatagtgagtatgacgatgag
cttttttctgaaatacaagaaattcgatctgctattactaagctaacggaagataatcaa
gcaatactttctaaactggataccctattactgcttaaaggagagactgattcaattaa

Length = 299

Score =   529 bits (1175), Expect(2) = 0.0
Identities = 222/231 (96%), Positives = 226/231 (97%)
Frame = +1

Query: 1801 MAEEQAYHVNKGLECLKALRENPPDIEEIQEVSNIRGQTRNPGQEDGTASMQEEEVSQDL 1980
            MAEEQAYHVNKGLECLKALRENPPDIEEIQEVS+IR QTRNPGQE+GTASMQEEEVSQDL
Sbjct: 1    MAEEQAYHVNKGLECLKALRENPPDIEEIQEVSSIRDQTRNPGQENGTASMQEEEVSQDL 60

Query: 1981 DESHEPAKGSNYVGHVLQNNPGCGESNTALVEAEQPANDDVQPGPGIRCYHVYDHSGEEV 2160
            DESHEPAKGSNY+GHVLQNNPGCGESNTALVEAEQPA DD+QPGPGIRCYHVYDHSGEEV
Sbjct: 61   DESHEPAKGSNYLGHVLQNNPGCGESNTALVEAEQPAKDDIQPGPGIRCYHVYDHSGEEV 120

Query: 2161 KGIEDADSLVVPAGAVSNRGFEGGEGSLDDSTEDSGEDYSEGNASSNWGYSFGLKPDRAA 2340
            KGIEDADSLVVPAGAVSNRGFE GEGS DDSTEDSGEDYSEGNASSNWGYSFGLKPDRAA
Sbjct: 121  KGIEDADSLVVPAGAVSNRGFERGEGSPDDSTEDSGEDYSEGNASSNWGYSFGLKPDRAA 180

Query: 2341 DVSMLMEEELSALLKTSRNVGIKKRDGMTLQFPHNPEGKTEDPECGSIKKG 2493
            DVSMLMEEELSALLKTSRNVGIKKRDG TLQFPHNPEGKTEDPECGSIKKG
Sbjct: 181  DVSMLMEEELSALLKTSRNVGIKKRDGKTLQFPHNPEGKTEDPECGSIKKG 231

------------------------------------------------------------
frameshifted from +1 to +3 between 2254-2726
  2254 ACTGAGGATTCTGGCGAAGATTATTCCGAGGGAAATGCTTCATCTAACTGGGGATATTCT 2313  
  2314 TTCGGCCTTAAACCAGACAGAGCGGCTGATGTGAGCATGCTGATGGAAGAGGAATTGAGT 2373  
  2374 GCTCTGCTCAAGACAAGCAGAAATGTGGGGATTAAGAAAAGGGATGGGATGACTCTGCAG 2433  
  2434 TTCCCACACAATCCCGAAGGTAAGACAGAGGATCCGGAGTGTGGATCCATTAAAAAGGGC 2493  
  2494 ACAGGAGAGAGGTCAGCCTCACATAGAATGGGGATAGTTGCTGGATCGACAAATGGTGCA 2553  
  2554 ACCCAATCTGCACTCAAGTCAACTGGGGGATCATCAGGGCCAAGTGTGTCTGCGGAGAAT 2613  
  2614 GTCCGCCAACCTGCAATGAATGCAAAGATGACCCAGAAATGCAAACCCGAGTCTGGTACG 2673  
  2674 CAACTCCCTCCCAGGACCTCAAATGAGGCTGAATCTGATAGTGAGTATGACGA        2726  
 frame +1
  2254  t -E--D--S--G--E--D--Y--S--E--G--N--A--S--S--N--W--G--Y--S- 2313   |
  2314 -F--G--L--K--P--D--R--A--A--D--V--S--M--L--M--E--E--E--L--S- 2373   |
  2374 -A--L--L--K--T--S--R--N--V--G--I--K--K--R--D--G- m -T--L--Q- 2433   |
  2434 -F--P--H--N--P--E--G--K--T--E--D--P--E--C--G--S--I--K--K--G- 2493   |
  2494  t  g  e  r  s  a  s  h  r  m -G- i  v  a  g  s  t  n  g  a  2553  
  2554  t  q  s  a  l  k  s  t  g -G- s  s  g  p  s  v  s  a  e  n  2613  
  2614  v  r  q  p  a  m  n  a -K- m  t  q  k  c  k  p  e  s  g  t  2673  
  2674  q  l -P- p  r  t  s  n  e  a  e  s  d  s  e  y  d           2726  
 frame +2
  2254   l  r  i -L- a  k  i  i  p  r  e  m  l  h -L- t  g  d  i -L 2313  
  2314 --S--A--L- n  q -T- e -R- l  m  *  a  c  *  w  k  r  n  *  v 2373   |
  2374   l  c  s  r  q  a -E- m  w  g  l  r  k  g  m -G- *  l  c  s 2433  
  2434   s -H- t  i  p  k  v  r  q  r  i  r  s  v  d  p  l  k  r  a 2493  
  2494   q  e  r  g  q  p  h  i  e -W--G- *  l  l  d  r  q  m  v  q 2553  
  2554   p  n  l  h  s  s  q  l  g  d  h  q  g  q  v  c  l -R- r  m 2613  
  2614   s -A- n  l  q  *  m  q  r  *  p  r  n  a  n  p  s  l  v  r 2673  
  2674   n  s  l  p  g  p  q  m  r  l  n  l  i  v  s  m  t          2726  
 frame +3
  2254    *  g  f  w  r  r  l  f  r -G- k  c  f  i  *  l -G- i  f - 2313  
  2314 F- r  p  *  t  r  q  s  g  *  c  e  h  a  d  g  r  g  i  e   2373  
  2374 c  s  a  q  d  k  q  k  c -G- d  *  e  k  g  w  d  d  s  a   2433  
  2434 v -P- t  q  s  r  r  *  d  r  g  s  g  v  w  i  h  * -K--G-- 2493  
  2494 H--R--R--E--V--S--L--T- * -N--G--D--S--C--W--I--D--K--W--C-- 2553   |
  2554 N--P--I--C--T--Q--V--N--W--G--I--I--R--A--K--C--V--C--G--E-- 2613   |
  2614 C--P--P--T--C--N--E--C--K--D--D--P--E--M--Q--T--R--V--W--Y-- 2673   |
  2674 A--T--P--S--Q--D- l -K- *  g  *  i  *  *  *  v  *  r         2726   |

reference sequence 152-299
EDSGEDYSEGNASSNWGYSFGLKPDRAADVSMLMEEELSALLKTSRNVGIKKRDGKTLQF
PHNPEGKTEDPECGSIKKGHRREVSLTWNGDSCWIDKWCNPICTQVNWGIIRAKCVCGEC
PPTCNECKDDPEMQTRVWYATPSQDIK
------------------------------------------------------------

Score =   189 bits (408), Expect(2) = 0.0
Identities = 68/70 (97%), Positives = 69/70 (98%)
Frame = +3

Query: 2487 KGHRREVSLT*NGDSCWIDKWCNPICTQVNWGIIRAKCVCGECPPTCNECKDDPEMQTRV 2666
            KGHRREVSLT NGDSCWIDKWCNPICTQVNWGIIRAKCVCGECPPTCNECKDDPEMQTRV
Sbjct: 230  KGHRREVSLTWNGDSCWIDKWCNPICTQVNWGIIRAKCVCGECPPTCNECKDDPEMQTRV 289

Query: 2667 WYATPSQDLK 2696
            WYATPSQD+K
Sbjct: 290  WYATPSQDIK 299


