========================================================================================================================

gene_id            %id    %sim   %cov   %t5   %gap  %t3   start..stop      pep sz ref sz ref id            definition
KM972720.1.1       77.1   94.0   99.4   0.6   0.0   0.0   127..4398        1423   1432   AED98379.1        M | polyprotein
                    could not find valid start codon
KM972720.1.1.1     44.9   78.0   98.3   1.7   0.0   0.0   127..1002        292    301    AF186243_mp1      glycoprotein G2
KM972720.1.1.2     28.3   61.8   100.0  0.0   0.0   0.0   1003..1536       178    174    LCU18980_mp2      non-structural protein NSm
KM972720.1.1.3     36.3   71.3   99.9   0.0   0.0   0.1   1537..4395       953    939    AF312381_mp3      glycoprotein G1

CLUSTAL 2.1 multiple sequence alignment


predicted       ---------ISGVQPAPNPGLNKCFTGGFLVSKRTMNHGISDFCVRDDISMIKGVSVQVK
reference       MIFIFMLSILTGALTAPNPSLNKCFAGGFLVQKRVMTHGIADFCVRDDISMIKGTSDQLK
                         ::*. .****.*****:*****.**.*.***:*************.* *:*

predicted       NESNFNNAIYRMWNVKNWHKCNPIEMAGGTFTVYDIDSTMSLVPKSFSCRSDCRISIDKE
reference       NESKFTNVIHRMWNVKNWHKCNPIEMSGGTFTVYDVDSTMALVPKSFSCRSECRINIDKE
                ***:*.*.*:****************:********:****:**********:***.****

predicted       EGSIILSSESLNHYSVTGSSSQTGWFKTKTAVQLSNTCEHIVVSCGTNQKPIHACFKTHM
reference       EGAIILSSESLNHYSITGSSTQSGWFKTKTSVQLSNTCEHIVVSCGTLQKPVHACFKTHM
                **:************:****:*:*******:**************** ***:********

predicted       SCVRFLHKTMLPGQMAMSLCANIEIILLTLFSTITYLLLWMISGTYIIYILLPIFWPITY
reference       SCVRFLHKTMLPGQMAMSLCSNIEIILLTTFSLITYLLLWMISGTYIIYILLPIFWPLTY
                ********************:******** ** ************************:**

predicted       IFGLLYTKACKTCSTCGKPYHPFTKCGVECICGAEFGSTDRLKMHRQGKLCHGFKSGTTA
reference       ICGVMYTRCCKACVTCGKPYHPLTKCGTECICGAEFGSTDRLKSHRQGRLCHGFKAGATA
                * *::**:.**:* ********:****.*************** ****:******:*:**

predicted       RALCRNKGSNLVLSILLAILFFSFLTPVHGLEDKERYSLLELGEVLPNIGYCPCPLQSSD
reference       RALCRNKGSNLILSIILAIFFFSFLTPVHGENTQQLYSLTELGEVLEDIGYCKCEYGYT-
                ***********:***:***:********** : :: *** ****** :**** *    : 

predicted       WASWIAILVNLLASMLILLTPWIINKMYYHRIYNCRECEMYHYRKEVRIFGDFTNRCDTC
reference       WTEIVSIITCLAGTILLVLIPYIINKMYYHKIYNCRECDMYHYRSGLKIWGDFTNRCETC
                *:. ::*:. * .::*::* *:********:*******:*****. ::*:*******:**

predicted       ICGFEPQVYEEIDYVCPVKDIHKKSENCLYQFDRKTVKFILLTLLLLNVISTGFVVAEPN
reference       ICGFTPNEYEEVDYEAPIKNMHKKSENCLYSFDRRTVKCVLFISIILMVMSMSFAVAEPD
                **** *: ***:** .*:*::*********.***:*** :*:  ::* *:* .*.****:

predicted       PDCLKKPIDSNLSDFYKCYGKALVFNECGTHGTPNKQEIYNDFVEKGYAHSTDRKIFDLL
reference       PNCLKKPINSNLSDLYNCYGSALVFNECISHSLPNKDNIYREFVAKGYAHPSDKKIFDLL
                *:******:*****:*:***.******* :*. ***::**.:** *****.:*:******

predicted       DDDFNSAMTKIELNNNKHYQVLGESIVYQRYCDYHKTLNQVAGYSSVGFKTSLQFHHLNL
reference       DDNFNSAMTKIELNENRHYQILGESIIYQRYCDYHKALNQVSGYSSVGFKTYLQLLHLNL
                **:***********:*:***:*****:*********:****:********* **: ****

predicted       CAYYPYKSICYCIEKIGSCRYTNDDFLETTENFYRSDNTSWSEDMNLVLQAISYAYRGLG
reference       CAHYPYKSICGCIGKTGSCKWADDDFFGTTTTFYKSDNISWGEDINVILQAISYAYRGFG
                **:******* ** * ***::::***: ** .**:*** **.**:*::**********:*

predicted       TSIMASLYNGWDVENLKEFLKNMTDSTPRNVFLTGLIKFAKFVVGLNITKPTVSNYWAHL
reference       TSIMASLINDWDIDNLITFLGNMTSRSPRNIFLTGLVKFAKFVVSLNITDPPVSSYWKHL
                ******* *.**::**  ** ***. :***:*****:*******.****.*.**.** **

predicted       ENTQRVQRSTQSLAAITINTGSTPIKECQNAKLVKCKSKIGDAVVVELVKCGSANNYYQV
reference       QTSGRQSRSATPFTALTINKSAAPRKDCQDAKLVQCKSKVGDTISIEMVKCGSSNDYYQV
                :.: * .**: .::*:***..::* *:**:****:****:**:: :*:*****:*:****

predicted       PAEGVTFSKDDKWCRGDTHCLKDFDPVTDQSQVKDLQCSDNSYLTHATIWHKDEKTCHLL
reference       PAEGVKHSSEMKWCRGDTHCLKDFDPITDDSDIPNLKCTTSSYLTTDTAWKKEEKTCHLL
                *****..*.: ***************:**:*:: :*:*: .****  * *:*:*******

predicted       NKGVCNVLGHS-WEIAHCNNEHYYLTEASIKHSGSNNITEYCITANCKSSRRPIHPAYIT
reference       NKGVCTVVDNANWEIAHCDNEHFYLTEPSIKHSGSNNITEYCLTSGCKNSRRPIHPSFIT
                *****.*:.:: ******:***:****.**************:*:.**.*******::**

predicted       ECKWENHLQNVMHSASILYADIDSFRHSLESTIEGDLNSHLFKPLSNMPKIKPKYLSFTI
reference       NCKWENHVQNVIHSASVLYADIDSFRHTLEATIGGDLNMHLFKPMSNMPKIKPKYLSFTI
                :******:***:****:**********:**:** **** *****:***************

predicted       QGVETEEGIRDSFISGEMAAIAGMANGFKVYTKDGQELFDIILYLKSAEYHAEYREIYKT
reference       QGVETEEGIRDAFISGEMAAIAGMANGFKVYTKDGQELFDIILYLKTAEYHAEYQEIYKT
                ***********:**********************************:*******:*****

predicted       GPTTTINVRHSEKCTGSCSQDLPVAKGWMGFSKEHTSSWGCEEFGCLAIGTGCLYGSCQD
reference       GPTTTINVRHSEKCTGSCSSDLPVAKGWMGFSREHTSNWGCEEFGCLAIGTGCLYGSCQD
                *******************.************:****.**********************

predicted       VIKPESTVYKKIGEDTTALDLCITLPHTTYCSKLDMLEPTITEKFELVFENTQVSILPER
reference       VIKPEASVYRKFGEDTTFLDLCITLPHTTFCSKLDILEPTITEKFELVFENTQVSVLPER
                *****::**:*:***** ***********:*****:*******************:****

predicted       ILVRNNKVYTGQINDLGSFAKYCGNVQQVNKTVIGQGVPKFDYICHAMQRKDVVVRKCFD
reference       ILVRNNKVYTGQINDLGSYAKYCGNVQQVNKTVLGQGTPKFDYICHAMQRKDVVVRKCFD
                ******************:**************:***.**********************

predicted       NNYNNCLQLQNDPNLLMINNGSKLSLHIFGKKLGTMRYKVKLGDLNYKLYKQDVDVDGTG
reference       NNYSSCLHLDNDPNLLMVNNGSKLSLHIFGKKLGTMRYKVKLGDLNYKLYKQSIEIDGTG
                ***..**:*:*******:**********************************.:::****

predicted       KCAGNSMSAMGISCQLDIEVSFETVCRLTSSCDSFHSTILLLPTEKKYSIKLMCQPKTEK
reference       KCAGNTMNANGIMCQLDIEVSFESICRLTSTCDSFHSTLVVYPTEKKYNIKLLCPPKTDK
                *****:*.* ** **********::*****:*******::: ******.***:* ***:*

predicted       IELQVCGHNIPIESNLIYKNEILDLAPVDQTHYVNEEDLKCATWICKVKEEGLSFIFKPF
reference       IQVQVCGHEVPIESNLIHRNEVLDLAPIDQTHYVNEEDLKCSTWICKAEEEGISFIFRPI
                *::*****::*******::**:*****:*************:*****.:***:****:*:

predicted       LDMLGKYTWIAIAVVVVILVLILSYYILIPVCGKIRDRLKEQQELDYSRIKNK
reference       LDLFGRYTWAVIATVGLILIVLLAYYLLIPICGRIRDHLKAQQQLDYEKIKSR
                **::*:*** .**.* :**:::*:**:***:**:***:** **:***.:**.:

>KM972720.1.1	127	4398
gcgacgtcgctttttgatccttcgatgtcggctcttcctatcattgtgaagcagaattca
ccaagcgttggattgttcacccactaatagggaacgtgagctgggttagaccgtcggctt
ttagcaATTTCAGGTGTTCAACCGGCACCTAACCCAGGATTAAATAAATGCTTCACTGGA
GGCTTCTTAGTCTCCAAACGGACTATGAATCACGGCATTTCGGACTTTTGTGTGAGAGAC
GATATTTCAATGATCAAAGGTGTCTCTGTTCAGGTTAAAAATGAAAGCAATTTTAATAAT
GCGATTTACAGGATGTGGAATGTAAAAAACTGGCACAAATGCAATCCGATTGAGATGGCT
GGCGGGACATTCACTGTATATGATATAGATTCAACAATGTCATTGGTTCCAAAATCATTT
TCATGCCGATCTGATTGTAGAATCAGCATCGACAAAGAGGAAGGCTCCATAATATTATCA
AGTGAATCTCTCAACCATTATAGTGTCACAGGGAGCTCATCTCAAACAGGGTGGTTTAAA
ACTAAAACAGCAGTTCAACTCTCAAATACCTGCGAGCACATTGTTGTATCATGTGGGACA
AATCAAAAGCCTATTCATGCATGCTTCAAGACACACATGTCTTGTGTCAGATTTTTGCAC
AAGACAATGCTCCCAGGCCAAATGGCAATGTCTCTGTGTGCTAATATAGAGATCATACTA
CTGACCCTATTTTCAACAATAACATATCTGCTCTTATGGATGATCTCAGGTACATATATA
ATATATATTCTTTTGCCTATATTCTGGCCAATTACTTATATTTTTGGGCTCCTGTACACC
AAAGCATGCAAAACTTGCTCTACATGTGGCAAACCTTATCATCCATTCACAAAATGTGGA
GTGGAGTGCATATGTGGTGCTGAGTTTGGGTCAACCGATAGGCTCAAAATGCATAGGCAA
GGAAAACTCTGCCACGGGTTCAAATCAGGAACAACTGCAAGAGCATTATGCAGAAACAAA
GGCTCTAATCTGGTGTTGTCTATATTGTTGGCAATTTTATTCTTCTCATTTCTGACACCT
GTGCACGGTCTTGAGGACAAAGAGAGATATTCTCTGCTTGAGTTAGGGGAAGTGCTGCCA
AATATTGGTTATTGCCCCTGCCCTCTACAAAGCTCTGACTGGGCTAGTTGGATTGCCATA
CTTGTCAATCTACTTGCTAGTATGCTAATCTTACTGACACCTTGGATTATCAATAAGATG
TACTATCATAGGATTTATAATTGTAGAGAGTGCGAAATGTACCATTACAGGAAAGAGGTC
AGAATATTTGGTGATTTTACCAATAGATGCGACACTTGTATTTGCGGCTTTGAGCCACAA
GTGTATGAAGAGATCGATTATGTATGCCCTGTCAAAGATATCCATAAAAAATCAGAGAAT
TGTTTATACCAATTTGATAGGAAAACTGTGAAATTCATATTATTGACTTTGCTTCTCTTG
AATGTTATCTCAACAGGTTTTGTAGTAGCAGAACCAAACCCAGATTGCTTGAAGAAGCCT
ATTGACAGCAACCTCTCTGACTTCTACAAGTGCTATGGGAAAGCTCTGGTTTTCAATGAA
TGCGGGACACATGGGACACCAAACAAGCAGGAGATATACAATGATTTTGTTGAGAAAGGA
TATGCTCATTCTACAGATAGAAAGATTTTTGACCTGCTTGATGATGACTTTAACTCTGCT
ATGACAAAAATTGAACTGAATAACAACAAGCATTATCAGGTACTAGGTGAGTCTATAGTA
TACCAAAGGTACTGTGACTACCACAAAACATTAAACCAAGTTGCTGGATATTCATCTGTT
GGATTCAAGACATCTCTACAATTCCACCACTTAAACTTGTGTGCATATTATCCATACAAG
TCAATATGCTACTGTATTGAGAAGATTGGCTCATGCAGATACACAAATGATGATTTTCTA
GAAACAACAGAGAATTTTTATAGGTCAGATAACACATCTTGGTCTGAAGATATGAATTTG
GTCTTACAGGCCATATCATATGCTTATCGAGGATTGGGAACCAGTATAATGGCTTCTCTG
TACAATGGTTGGGATGTTGAAAACTTGAAAGAGTTCTTAAAAAATATGACAGATTCAACT
CCTAGGAATGTTTTCCTTACTGGATTAATAAAATTTGCAAAATTTGTTGTTGGACTGAAT
ATAACAAAGCCAACTGTCTCTAATTACTGGGCACATTTGGAAAATACTCAAAGGGTACAA
CGATCAACTCAATCATTGGCAGCAATAACTATCAATACTGGATCAACACCAATTAAAGAA
TGCCAAAATGCTAAGTTAGTTAAATGCAAGTCAAAAATAGGTGATGCAGTCGTTGTAGAA
TTAGTAAAGTGTGGTTCTGCTAACAATTATTATCAGGTACCAGCTGAGGGTGTGACATTT
TCTAAGGATGATAAATGGTGTAGAGGAGATACACACTGTCTGAAAGATTTTGATCCTGTG
ACAGATCAGTCACAAGTCAAAGACTTGCAGTGTTCAGATAATAGCTATCTGACACATGCA
ACAATATGGCACAAAGACGAAAAGACTTGCCATCTTCTCAACAAGGGAGTATGCAATGTA
CTAGGGCATTCTTGGGAGATTGCCCATTGCAACAATGAGCATTACTACTTGACAGAGGCA
TCAATTAAGCATTCAGGTTCGAATAATATAACTGAGTATTGTATAACTGCTAATTGTAAA
TCAAGTAGAAGACCAATACACCCTGCATATATCACAGAATGCAAATGGGAGAATCATCTG
CAGAATGTAATGCATTCTGCCTCTATACTCTATGCAGATATTGATAGTTTTAGACACTCT
TTGGAATCAACAATAGAAGGTGACCTCAACAGTCATTTGTTTAAACCTTTATCAAATATG
CCTAAGATTAAGCCTAAATACCTTTCTTTCACCATACAAGGAGTGGAAACAGAGGAGGGG
ATAAGAGACTCTTTCATCTCTGGAGAGATGGCAGCAATAGCAGGCATGGCAAATGGGTTC
AAGGTTTACACAAAAGATGGTCAAGAGTTGTTTGATATCATACTTTATCTAAAATCTGCA
GAATATCATGCAGAATATAGAGAGATCTATAAGACAGGGCCAACAACTACTATTAATGTT
AGACATTCAGAAAAATGTACCGGGTCTTGCAGCCAAGACTTACCTGTTGCTAAAGGATGG
ATGGGATTTTCAAAAGAACATACTAGTAGCTGGGGGTGTGAAGAATTTGGCTGTCTGGCA
ATCGGGACTGGCTGCCTATATGGTTCCTGCCAAGATGTGATTAAGCCAGAGTCAACAGTT
TATAAAAAGATTGGAGAAGACACAACAGCCTTAGATCTTTGCATTACACTGCCGCATACA
ACATATTGTTCTAAATTAGATATGCTAGAGCCGACAATAACGGAGAAGTTTGAATTGGTC
TTCGAAAATACACAAGTCTCTATTCTCCCTGAAAGGATATTGGTTCGAAACAACAAAGTT
TACACAGGACAAATAAATGATTTGGGATCATTTGCAAAGTATTGTGGAAATGTTCAACAG
GTTAATAAGACGGTTATAGGTCAAGGAGTCCCTAAATTTGATTATATATGCCATGCAATG
CAGCGTAAAGATGTTGTAGTTAGGAAATGTTTTGATAATAATTATAATAATTGCCTGCAG
TTACAGAATGATCCAAATCTACTAATGATCAACAATGGGTCCAAATTGAGTTTGCATATT
TTTGGAAAGAAACTAGGGACAATGAGATATAAAGTTAAATTAGGTGATCTCAATTATAAG
CTATACAAACAAGATGTAGATGTTGATGGGACAGGAAAGTGTGCTGGGAATTCAATGTCA
GCAATGGGAATATCCTGCCAGTTAGATATTGAAGTATCATTTGAGACAGTTTGCAGGTTA
ACATCATCATGTGATTCTTTCCATTCTACAATCTTACTTCTTCCAACAGAGAAGAAGTAC
AGTATAAAGCTAATGTGTCAACCTAAAACTGAAAAGATAGAATTGCAAGTCTGCGGGCAT
AACATACCTATTGAGTCAAATTTAATATATAAAAATGAAATCTTAGACCTAGCCCCTGTT
GACCAGACCCATTATGTCAATGAAGAAGACCTCAAATGTGCGACATGGATCTGCAAAGTG
AAAGAGGAAGGGCTTTCATTTATCTTCAAGCCATTCTTAGACATGTTAGGAAAGTATACA
TGGATTGCAATTGCTGTTGTAGTAGTGATCTTAGTATTGATATTATCTTATTACATTTTA
ATACCAGTTTGTGGTAAGATTAGGGACAGATTAAAAGAACAGCAAGAACTAGATTATAGC
AGGATAAAAAACAAATAAagaattgacaatttggcctaggaaagttagtaaccctttaag
ggttactaacaaaatgaaacagtatat

Length = 1432

Score =   735 bits (1599), Expect(3) = 0.0
Identities = 286/348 (82%), Positives = 314/348 (90%)
Frame = +1

Query: 118  LLAISGVQPAPNPGLNKCFTGGFLVSKRTMNHGISDFCVRDDISMIKGVSVQVKNESNFN 297
            L  ++G   APNP LNKCF GGFLV KR M HGI+DFCVRDDISMIKG S Q+KNES F 
Sbjct: 7    LSILTGALTAPNPSLNKCFAGGFLVQKRVMTHGIADFCVRDDISMIKGTSDQLKNESKFT 66

Query: 298  NAIYRMWNVKNWHKCNPIEMAGGTFTVYDIDSTMSLVPKSFSCRSDCRISIDKEEGSIIL 477
            N I+RMWNVKNWHKCNPIEM+GGTFTVYD+DSTM+LVPKSFSCRS+CRI+IDKEEG+IIL
Sbjct: 67   NVIHRMWNVKNWHKCNPIEMSGGTFTVYDVDSTMALVPKSFSCRSECRINIDKEEGAIIL 126

Query: 478  SSESLNHYSVTGSSSQTGWFKTKTAVQLSNTCEHIVVSCGTNQKPIHACFKTHMSCVRFL 657
            SSESLNHYS+TGSS+Q+GWFKTKT+VQLSNTCEHIVVSCGT QKP+HACFKTHMSCVRFL
Sbjct: 127  SSESLNHYSITGSSTQSGWFKTKTSVQLSNTCEHIVVSCGTLQKPVHACFKTHMSCVRFL 186

Query: 658  HKTMLPGQMAMSLCANIEIILLTLFSTITYLLLWMISGTYIIYILLPIFWPITYIFGLLY 837
            HKTMLPGQMAMSLC+NIEIILLT FS ITYLLLWMISGTYIIYILLPIFWP+TYI G++Y
Sbjct: 187  HKTMLPGQMAMSLCSNIEIILLTTFSLITYLLLWMISGTYIIYILLPIFWPLTYICGVMY 246

Query: 838  TKACKTCSTCGKPYHPFTKCGVECICGAEFGSTDRLKMHRQGKLCHGFKSGTTARALCRN 1017
            T+ CK C TCGKPYHP TKCG ECICGAEFGSTDRLK HRQG+LCHGFK+G TARALCRN
Sbjct: 247  TRCCKACVTCGKPYHPLTKCGTECICGAEFGSTDRLKSHRQGRLCHGFKAGATARALCRN 306

Query: 1018 KGSNLVLSILLAILFFSFLTPVHGLEDKERYSLLELGEVLPNIGYCPC 1161
            KGSNL+LSI+LAI FFSFLTPVHG   ++ YSL ELGEVL +IGYC C
Sbjct: 307  KGSNLILSIILAIFFFSFLTPVHGENTQQLYSLTELGEVLEDIGYCKC 354

Score =   868 bits (1889), Expect(3) = 0.0
Identities = 327/491 (66%), Positives = 400/491 (81%)
Frame = +1

Query: 1180 WASWIAILVNLLASMLILLTPWIINKMYYHRIYNCRECEMYHYRKEVRIFGDFTNRCDTC 1359
            W   ++I+  L  ++L++L P+IINKMYYH+IYNCREC+MYHYR  ++I+GDFTNRC+TC
Sbjct: 360  WTEIVSIITCLAGTILLVLIPYIINKMYYHKIYNCRECDMYHYRSGLKIWGDFTNRCETC 419

Query: 1360 ICGFEPQVYEEIDYVCPVKDIHKKSENCLYQFDRKTVKFILLTLLLLNVISTGFVVAEPN 1539
            ICGF P  YEE+DY  P+K++HKKSENCLY FDR+TVK +L   ++L V+S  F VAEP+
Sbjct: 420  ICGFTPNEYEEVDYEAPIKNMHKKSENCLYSFDRRTVKCVLFISIILMVMSMSFAVAEPD 479

Query: 1540 PDCLKKPIDSNLSDFYKCYGKALVFNECGTHGTPNKQEIYNDFVEKGYAHSTDRKIFDLL 1719
            P+CLKKPI+SNLSD Y CYG ALVFNEC +H  PNK  IY +FV KGYAH +D+KIFDLL
Sbjct: 480  PNCLKKPINSNLSDLYNCYGSALVFNECISHSLPNKDNIYREFVAKGYAHPSDKKIFDLL 539

Query: 1720 DDDFNSAMTKIELNNNKHYQVLGESIVYQRYCDYHKTLNQVAGYSSVGFKTSLQFHHLNL 1899
            DD+FNSAMTKIELN N+HYQ+LGESI+YQRYCDYHK LNQV+GYSSVGFKT LQ  HLNL
Sbjct: 540  DDNFNSAMTKIELNENRHYQILGESIIYQRYCDYHKALNQVSGYSSVGFKTYLQLLHLNL 599

Query: 1900 CAYYPYKSICYCIEKIGSCRYTNDDFLETTENFYRSDNTSWSEDMNLVLQAISYAYRGLG 2079
            CA+YPYKSIC CI K GSC++ +DDF  TT  FY+SDN SW ED+N++LQAISYAYRG G
Sbjct: 600  CAHYPYKSICGCIGKTGSCKWADDDFFGTTTTFYKSDNISWGEDINVILQAISYAYRGFG 659

Query: 2080 TSIMASLYNGWDVENLKEFLKNMTDSTPRNVFLTGLIKFAKFVVGLNITKPTVSNYWAHL 2259
            TSIMASL N WD++NL  FL NMT  +PRN+FLTGL+KFAKFVV LNIT P VS+YW HL
Sbjct: 660  TSIMASLINDWDIDNLITFLGNMTSRSPRNIFLTGLVKFAKFVVSLNITDPPVSSYWKHL 719

Query: 2260 ENTQRVQRSTQSLAAITINTGSTPIKECQNAKLVKCKSKIGDAVVVELVKCGSANNYYQV 2439
            + + R  RS     A+TIN  + P K+CQ+AKLV+CKSK+GD + +E+VKCGS+N+YYQV
Sbjct: 720  QTSGRQSRSATPFTALTINKSAAPRKDCQDAKLVQCKSKVGDTISIEMVKCGSSNDYYQV 779

Query: 2440 PAEGVTFSKDDKWCRGDTHCLKDFDPVTDQSQVKDLQCSDNSYLTHATIWHKDEKTCHLL 2619
            PAEGV  S + KWCRGDTHCLKDFDP+TD S + +L+C+ +SYLT  T W K+EKTCHLL
Sbjct: 780  PAEGVKHSSEMKWCRGDTHCLKDFDPITDDSDIPNLKCTTSSYLTTDTAWKKEEKTCHLL 839

Query: 2620 NKGVCNVLGHS 2652
            NKGVC V+ ++
Sbjct: 840  NKGVCTVVDNA 850

Score =  1269 bits (2765), Expect(3) = 0.0
Identities = 486/582 (83%), Positives = 555/582 (95%)
Frame = +1

Query: 2650 SWEIAHCNNEHYYLTEASIKHSGSNNITEYCITANCKSSRRPIHPAYITECKWENHLQNV 2829
            +WEIAHC+NEH+YLTE SIKHSGSNNITEYC+T+ CK+SRRPIHP++IT CKWENH+QNV
Sbjct: 851  NWEIAHCDNEHFYLTEPSIKHSGSNNITEYCLTSGCKNSRRPIHPSFITNCKWENHVQNV 910

Query: 2830 MHSASILYADIDSFRHSLESTIEGDLNSHLFKPLSNMPKIKPKYLSFTIQGVETEEGIRD 3009
            +HSAS+LYADIDSFRH+LE+TI GDLN HLFKP+SNMPKIKPKYLSFTIQGVETEEGIRD
Sbjct: 911  IHSASVLYADIDSFRHTLEATIGGDLNMHLFKPMSNMPKIKPKYLSFTIQGVETEEGIRD 970

Query: 3010 SFISGEMAAIAGMANGFKVYTKDGQELFDIILYLKSAEYHAEYREIYKTGPTTTINVRHS 3189
            +FISGEMAAIAGMANGFKVYTKDGQELFDIILYLK+AEYHAEY+EIYKTGPTTTINVRHS
Sbjct: 971  AFISGEMAAIAGMANGFKVYTKDGQELFDIILYLKTAEYHAEYQEIYKTGPTTTINVRHS 1030

Query: 3190 EKCTGSCSQDLPVAKGWMGFSKEHTSSWGCEEFGCLAIGTGCLYGSCQDVIKPESTVYKK 3369
            EKCTGSCS DLPVAKGWMGFS+EHTS+WGCEEFGCLAIGTGCLYGSCQDVIKPE++VY+K
Sbjct: 1031 EKCTGSCSSDLPVAKGWMGFSREHTSNWGCEEFGCLAIGTGCLYGSCQDVIKPEASVYRK 1090

Query: 3370 IGEDTTALDLCITLPHTTYCSKLDMLEPTITEKFELVFENTQVSILPERILVRNNKVYTG 3549
             GEDTT LDLCITLPHTT+CSKLD+LEPTITEKFELVFENTQVS+LPERILVRNNKVYTG
Sbjct: 1091 FGEDTTFLDLCITLPHTTFCSKLDILEPTITEKFELVFENTQVSVLPERILVRNNKVYTG 1150

Query: 3550 QINDLGSFAKYCGNVQQVNKTVIGQGVPKFDYICHAMQRKDVVVRKCFDNNYNNCLQLQN 3729
            QINDLGS+AKYCGNVQQVNKTV+GQG PKFDYICHAMQRKDVVVRKCFDNNY++CL L N
Sbjct: 1151 QINDLGSYAKYCGNVQQVNKTVLGQGTPKFDYICHAMQRKDVVVRKCFDNNYSSCLHLDN 1210

Query: 3730 DPNLLMINNGSKLSLHIFGKKLGTMRYKVKLGDLNYKLYKQDVDVDGTGKCAGNSMSAMG 3909
            DPNLLM+NNGSKLSLHIFGKKLGTMRYKVKLGDLNYKLYKQ +++DGTGKCAGN+M+A G
Sbjct: 1211 DPNLLMVNNGSKLSLHIFGKKLGTMRYKVKLGDLNYKLYKQSIEIDGTGKCAGNTMNANG 1270

Query: 3910 ISCQLDIEVSFETVCRLTSSCDSFHSTILLLPTEKKYSIKLMCQPKTEKIELQVCGHNIP 4089
            I CQLDIEVSFE++CRLTS+CDSFHST+++ PTEKKY+IKL+C PKT+KI++QVCGH +P
Sbjct: 1271 IMCQLDIEVSFESICRLTSTCDSFHSTLVVYPTEKKYNIKLLCPPKTDKIQVQVCGHEVP 1330

Query: 4090 IESNLIYKNEILDLAPVDQTHYVNEEDLKCATWICKVKEEGLSFIFKPFLDMLGKYTWIA 4269
            IESNLI++NE+LDLAP+DQTHYVNEEDLKC+TWICK +EEG+SFIF+P LD+ G+YTW  
Sbjct: 1331 IESNLIHRNEVLDLAPIDQTHYVNEEDLKCSTWICKAEEEGISFIFRPILDLFGRYTWAV 1390

Query: 4270 IAVVVVILVLILSYYILIPVCGKIRDRLKEQQELDYSRIKNK 4395
            IA V +IL+++L+YY+LIP+CG+IRD LK QQ+LDY +IK++
Sbjct: 1391 IATVGLILIVLLAYYLLIPICGRIRDHLKAQQQLDYEKIKSR 1432


========================================================================================================================

gene_id            %id    %sim   %cov   %t5   %gap  %t3   start..stop      pep sz ref sz ref id            definition
KU937313.1.2       96.7   97.8   100.0  0.0   0.0   0.0   61..336          91     91     AAL78236.1        NSs | non-structural protein NSs
                    stop codon embedded in CDS at 109..111

CLUSTAL 2.1 multiple sequence alignment


predicted       MFLNGISLRLTRRSGMXHLLLNMGPNSISIPLESSSSTRRRPRWYSVRRHNRVLILHLVA
reference       MFLNGISLRLTRRSGMWHLLLNMGPNSISIPLESSSSIRRRPRWYSVRRHNQVLILHLVA
                **************** ******************** *************:********

predicted       SNLHWLITIFPNTQQILCQTLPSLSTVSQDI
reference       SNLHWLITIFPNTQQILCQTLPSLSTVSQDI
                *******************************

>KU937313.1.2	61	336
cagtagtgtactccactatagaacaaagcttttgaatggcaaaccagtttattttccaag
ATGTTCCTCAACGGAATCTCGCTACGTTTAACCCGGAGGTCGGGTATGTAGCATTTATTG
CTAAACATGGGGCCCAACTCAATTTCGATACCGTTAGAGTCTTCTTCCTCAACCAGAAGA
AGGCCAAGATGGTACTCAGTAAGACGGCACAACCGAGTGTTGATCTTACATTTGGTGGCA
TCAAATTTACACTGGTTAATAACCATTTTCCCCAATACACAGCAAATCCTGTGCCAGACA
CTGCCCTCACTCTCCACCGTCTCTCAGGATATCTAGcaaaatgggttgcagatcaatgca
aaacaaaccaaatcaaattggcagaggccatggaaaaaatagtcatgccacttgctgaag
taaagggttgcacctggactgaggggttgactatgtatctgggatttgcaccaggtgctg
aaatgttcctggagacttttgagttctaccccctggttattgacatgcacagagtgctaa
aagatgggatggatgtcaacttcatgcgaaaggttc

Length = 91

Score =   207 bits (447), Expect = 8e-59
Identities = 88/91 (96%), Positives = 89/91 (97%)
Frame = +1

Query: 61  MFLNGISLRLTRRSGM*HLLLNMGPNSISIPLESSSSTRRRPRWYSVRRHNRVLILHLVA 240
           MFLNGISLRLTRRSGM HLLLNMGPNSISIPLESSSS RRRPRWYSVRRHN+VLILHLVA
Sbjct: 1   MFLNGISLRLTRRSGMWHLLLNMGPNSISIPLESSSSIRRRPRWYSVRRHNQVLILHLVA 60

Query: 241 SNLHWLITIFPNTQQILCQTLPSLSTVSQDI 333
           SNLHWLITIFPNTQQILCQTLPSLSTVSQDI
Sbjct: 61  SNLHWLITIFPNTQQILCQTLPSLSTVSQDI 91


