========================================================================================================================

gene_id            %id    %sim   %cov   %t5   %gap  %t3   start..stop      pep sz ref sz ref id            definition
KM597072.1.1       97.6   99.1   100.0  0.0   0.0   0.0   84..422          549    549    Q77IS8.1          NP | nucleocapsid protein
                                                          422..1732                                        
                    frameshift in genome at or near position 422..422 (+3=>+2)

CLUSTAL 2.1 multiple sequence alignment


predicted       MSSVLKAFERFTIEQELQDRGEEGSIPPETLKSAVKVFVINTPNPTTRYQMLNFCLRIIC
reference       MSSVLKAFERFTIEQELQDRGEEGSIPPETLKSAVKVFVINTPNPTTRYQMLNFCLRIIC
                ************************************************************

predicted       SQNARASHRVGALITLFSLPSAGMQNHIRLADKSPEARIERCEIDGFEPGTYSLIPNARA
reference       SQNARASHRVGALITLFSLPSAGMQNHIRLADRSPEAQIERCEIDGFEPGTYRLIPNARA
                ********************************:****:************** *******

predicted       NLTANEIAAYALLADDLPPTINNGTPYVHADVEGQPCDEIEQFLDRCYSVLIQAWVMVCK
reference       NLTANEIAAYALLADDLPPTINNGTPYVHADVEGQPCDEIEQFLDRCYSVLIQAWVMVCK
                ************************************************************

predicted       CMTAYDQPAGSADRRFAKYQQQGRLEARYMLQPEAQRLIQTAIRKSLVVRQYLTFELQLA
reference       CMTAYDQPAGSADRRFAKYQQQGRLEARYMLQPEAQRLIQTAIRKSLVVRQYLTFELQLA
                ************************************************************

predicted       RRQGLLSNRYYAMVGDIGKYIENSGLTAFFLTLKYALGTKWSPLSLAAFTGELTKLRSLM
reference       RRQGLLSNRYYAMVGDIGKYIENSGLTAFFLTLKYALGTKWSPLSLAAFTGELTKLRSLM
                ************************************************************

predicted       MLYRDLGEQARYLALLEAPQIMDFAPGGYPLIFSYAMGVGTVLDVQMRNYTYARPFLNGY
reference       MLYRGLGEQARYLALLEAPQIMDFAPGGYPLIFSYAMGVGTVLDVQMRNYTYARPFLNGY
                ****.*******************************************************

predicted       YFQIGVETARRQQGTVDNRVADDLGLTPEQRTEVTQLVDRLARGRGAGIPGGPVNPFVPP
reference       YFQIGVETARRQQGTVDNRVADDLGLTPEQRTEVTQLVDRLARGRGAGIPGGPVNPFVPP
                ************************************************************

predicted       VQQQQPAAVYEDIPALEESDDDGDEDGGAGFQNGAQAPAVRQGGQNEFRAQPLQDPIQAQ
reference       VQQQQPAAVYEDIPALEESDDDGDEDGGAGFQNGVQLPAVRQGGQTDFRAQPLQDPIQAQ
                **********************************.* ********.:*************

predicted       LFMPLYPQVSNIPNHQNHQINRIGGMEHQDLLRYNENGDSQQDARGEHGNTFPNNPNQNA
reference       LFMPLYPQVSNMPNNQNHQINRIGGLEHQDLLRYNENGDSQQDARGEHVNTFPNNPNQNA
                ***********:**:**********:********************** ***********

predicted       QSQVGDWDE
reference       QLQVGDWDE
                * *******

>KM597072.1.1	84	1732
gaagtggtgttttgcgatttcgaggccgggctcgatcctcacctttcattgtcgataggg
gacattttgacactaccttgaaaATGTCGTCCGTGCTCAAAGCATTTGAGCGATTCACGA
TAGAACAGGAACTTCAAGACAGGGGTGAGGAGGGTTCAATTCCGCCGGAGACTTTAAAGT
CAGCAGTCAAAGTCTTCGTTATTAACACACCCAATCCCACCACACGCTACCAGATGCTAA
ACTTTTGCCTAAGAATAATTTGCAGTCAAAATGCTAGGGCTTCTCACAGAGTGGGTGCAT
TGATAACATTATTCTCACTTCCCTCGGCAGGTATGCAAAATCATATTAGACTAGCAGATA
AATCACCCGAAGCCAGAATAGAACGCTGTGAGATTGATGGTTTTGAGCCTGGCACATATA
GCTGATTCCGAATGCACGCGCCAATCTTACTGCCAATGAAATTGCTGCCTATGCTTTGCT
TGCAGATGACCTTCCTCCAACCATAAATAATGGAACTCCTTATGTACATGCAGATGTTGA
AGGGCAGCCGTGTGATGAAATTGAACAATTCCTGGATCGATGCTACAGTGTACTAATCCA
GGCTTGGGTGATGGTCTGTAAATGTATGACAGCTTACGACCAACCTGCTGGATCTGCTGA
TCGGAGATTTGCGAAATACCAGCAGCAAGGTCGCCTGGAAGCAAGATACATGCTGCAGCC
GGAAGCCCAAAGGTTGATTCAAACTGCCATCAGGAAAAGTCTTGTTGTTAGACAGTATCT
TACCTTTGAACTCCAGCTGGCAAGACGGCAGGGGTTGCTATCAAACAGATACTACGCAAT
GGTGGGTGACATTGGAAAGTACATTGAGAATTCAGGCCTTACTGCCTTCTTTCTCACCCT
CAAATATGCACTAGGTACCAAATGGAGTCCTCTGTCATTGGCCGCATTCACCGGTGAACT
CACTAAGCTCCGATCCTTGATGATGTTATATCGAGATCTCGGAGAACAAGCCAGATACCT
TGCTTTGTTGGAGGCTCCCCAAATAATGGACTTTGCTCCCGGGGGCTACCCATTGATATT
CAGTTATGCTATGGGAGTCGGTACAGTCTTAGATGTCCAAATGCGAAATTACACTTATGC
ACGACCTTTCCTAAATGGTTACTATTTCCAGATTGGGGTTGAGACCGCACGACGGCAACA
AGGCACTGTTGACAATAGAGTAGCAGATGATCTAGGCCTGACTCCTGAACAAAGAACTGA
GGTCACTCAGCTTGTTGACAGGCTTGCAAGAGGCAGAGGTGCGGGGATACCAGGTGGGCC
TGTGAATCCCTTTGTTCCTCCAGTTCAACAGCAACAACCTGCTGCCGTATATGAGGACAT
TCCTGCATTGGAGGAATCAGATGACGATGGTGATGAAGATGGCGGTGCAGGATTCCAAAA
TGGAGCACAAGCACCAGCTGTAAGACAGGGAGGTCAAAATGAATTTAGAGCACAGCCGTT
ACAGGATCCAATTCAAGCACAACTCTTCATGCCATTATATCCTCAAGTCAGCAACATCCC
AAATCATCAGAATCATCAGATTAATCGCATCGGGGGGATGGAACACCAAGATTTATTACG
ATACAACGAAAATGGTGATTCTCAGCAGGATGCAAGGGGCGAACACGGAAATACCTTCCC
AAACAATCCCAATCAAAACGCACAGTCACAAGTGGGTGACTGGGATGAGTAAatcactga
catgaccaaactacccccgactgcaacaaacccagaacaatctagccacagccaactgct
caaatccactacattccattcatatttagtctttaagaaaaaattaggcccggaaagaat
tagttctacgagcatcgacacgattatcttgatcgtgtttctttccgggcaagccatgga
tcaatttataaaacaagatgaaactggtg

Length = 549

Score =   263 bits (569), Expect(2) = 0.0
Identities = 110/112 (98%), Positives = 112/112 (100%)
Frame = +3

Query: 84   MSSVLKAFERFTIEQELQDRGEEGSIPPETLKSAVKVFVINTPNPTTRYQMLNFCLRIIC 263
            MSSVLKAFERFTIEQELQDRGEEGSIPPETLKSAVKVFVINTPNPTTRYQMLNFCLRIIC
Sbjct: 1    MSSVLKAFERFTIEQELQDRGEEGSIPPETLKSAVKVFVINTPNPTTRYQMLNFCLRIIC 60

Query: 264  SQNARASHRVGALITLFSLPSAGMQNHIRLADKSPEARIERCEIDGFEPGTY 419
            SQNARASHRVGALITLFSLPSAGMQNHIRLAD+SPEA+IERCEIDGFEPGTY
Sbjct: 61   SQNARASHRVGALITLFSLPSAGMQNHIRLADRSPEAQIERCEIDGFEPGTY 112

------------------------------------------------------------
frameshifted from +3 to +2 between 180-661
   180 TCAGCAGTCAAAGTCTTCGTTATTAACACACCCAATCCCACCACACGCTACCAGATGCTA 239   
   240 AACTTTTGCCTAAGAATAATTTGCAGTCAAAATGCTAGGGCTTCTCACAGAGTGGGTGCA 299   
   300 TTGATAACATTATTCTCACTTCCCTCGGCAGGTATGCAAAATCATATTAGACTAGCAGAT 359   
   360 AAATCACCCGAAGCCAGAATAGAACGCTGTGAGATTGATGGTTTTGAGCCTGGCACATAT 419   
   420 AGCTGATTCCGAATGCACGCGCCAATCTTACTGCCAATGAAATTGCTGCCTATGCTTTGC 479   
   480 TTGCAGATGACCTTCCTCCAACCATAAATAATGGAACTCCTTATGTACATGCAGATGTTG 539   
   540 AAGGGCAGCCGTGTGATGAAATTGAACAATTCCTGGATCGATGCTACAGTGTACTAATCC 599   
   600 AGGCTTGGGTGATGGTCTGTAAATGTATGACAGCTTACGACCAACCTGCTGGATCTGCTG 659   
   660 AT                                                           661   
 frame +3
   180  s -A--V--K--V--F--V--I--N--T--P--N--P--T--T--R--Y--Q--M--L- 239    |
   240 -N--F--C--L--R--I--I--C--S--Q--N--A--R--A--S--H--R--V--G--A- 299    |
   300 -L--I--T--L--F--S--L--P--S--A--G--M--Q--N--H--I--R--L--A--D- 359    |
   360  k -S--P--E--A- r -I--E--R--C--E--I--D--G--F--E--P--G--T--Y- 419    |
   420  s  *  f  r  m  h  a  p  i -L- l  p  m  k  l  l  p  m  l  c  479   
   480 -L- q  m  t  f  l  q  p  *  i  m  e  l  l  m  y  m  q  m  l  539   
   540  k -G- s  r  v  m  k  l  n  n  s  w  i  d  a  t  v  y  *  s  599   
   600  r  l  g  *  w  s  v  n  v  *  q  l  t  t  n  l  l  d  l  l  659   
 frame +1
   180   q -Q- s  k  s  s  l -L- t  h  p  i  p  p  h -A- t  r  c  * 239   
   240   t  f  a  *  e  *  f  a  v  k  m  l  g  l  l  t  e  w  v  h 299   
   300   *  *  h  y  s  h  f  p  r -Q- v  c  k  i  i  l -D- *  q  i 359   
   360   n  h  p  k  p  e  *  n  a  v -R- l  m  v  l  s  l  a  h  i 419   
   420  -A- d  s  e  c  t  r  q  s  y  c  q  * -N- c  c  l  c  f  a 479   
   480   c  r  *  p  s  s  n  h  k  *  w  n  s  l  c  t  c -R--C- * 539   
   540   r  a  a  v  *  *  n  *  t  i  p  g  s -M- l  q  c  t  n -P 599   
   600 - g  l  g  d  g  l  *  m  y  d  s  l  r  p  t  c  w  i  c  * 659   
 frame +2
   180    s  s  q  s  l  r  y  *  h  t  q  s  h  h  t  l  p  d  a   239   
   240 k  l  l  p  k  n  n  l  q  s  k  c  *  g  f  s  q  s -G- c   299   
   300 i  d  n  i  i  l  t  s  l  g  r  y  a  k  s  y  *  t  s  r   359   
   360 *  i  t  r  s -Q- n  r  t  l  *  d  *  w -F- *  a  w  h  i   419   
   420 * -L--I--P--N--A--R--A--N--L--T--A--N--E--I--A--A--Y--A--L-- 479    |
   480 L--A--D--D--L--P--P--T--I--N--N--G--T--P--Y--V--H--A--D--V-- 539    |
   540 E--G--Q--P--C--D--E--I--E--Q--F--L--D--R--C--Y--S--V--L--I-- 599    |
   600 Q--A--W--V--M--V--C--K--C--M--T--A--Y--D--Q--P--A--G--S--A-- 659    |
   660 D-                                                           661   

reference sequence 33-193
AVKVFVINTPNPTTRYQMLNFCLRIICSQNARASHRVGALITLFSLPSAGMQNHIRLADR
SPEAQIERCEIDGFEPGTYRLIPNARANLTANEIAAYALLADDLPPTINNGTPYVHADVE
GQPCDEIEQFLDRCYSVLIQAWVMVCKCMTAYDQPAGSADR
------------------------------------------------------------

Score =  1028 bits (2239), Expect(2) = 0.0
Identities = 426/436 (97%), Positives = 430/436 (98%)
Frame = +2

Query: 422  LIPNARANLTANEIAAYALLADDLPPTINNGTPYVHADVEGQPCDEIEQFLDRCYSVLIQ 601
            LIPNARANLTANEIAAYALLADDLPPTINNGTPYVHADVEGQPCDEIEQFLDRCYSVLIQ
Sbjct: 114  LIPNARANLTANEIAAYALLADDLPPTINNGTPYVHADVEGQPCDEIEQFLDRCYSVLIQ 173

Query: 602  AWVMVCKCMTAYDQPAGSADRRFAKYQQQGRLEARYMLQPEAQRLIQTAIRKSLVVRQYL 781
            AWVMVCKCMTAYDQPAGSADRRFAKYQQQGRLEARYMLQPEAQRLIQTAIRKSLVVRQYL
Sbjct: 174  AWVMVCKCMTAYDQPAGSADRRFAKYQQQGRLEARYMLQPEAQRLIQTAIRKSLVVRQYL 233

Query: 782  TFELQLARRQGLLSNRYYAMVGDIGKYIENSGLTAFFLTLKYALGTKWSPLSLAAFTGEL 961
            TFELQLARRQGLLSNRYYAMVGDIGKYIENSGLTAFFLTLKYALGTKWSPLSLAAFTGEL
Sbjct: 234  TFELQLARRQGLLSNRYYAMVGDIGKYIENSGLTAFFLTLKYALGTKWSPLSLAAFTGEL 293

Query: 962  TKLRSLMMLYRDLGEQARYLALLEAPQIMDFAPGGYPLIFSYAMGVGTVLDVQMRNYTYA 1141
            TKLRSLMMLYR LGEQARYLALLEAPQIMDFAPGGYPLIFSYAMGVGTVLDVQMRNYTYA
Sbjct: 294  TKLRSLMMLYRGLGEQARYLALLEAPQIMDFAPGGYPLIFSYAMGVGTVLDVQMRNYTYA 353

Query: 1142 RPFLNGYYFQIGVETARRQQGTVDNRVADDLGLTPEQRTEVTQLVDRLARGRGAGIPGGP 1321
            RPFLNGYYFQIGVETARRQQGTVDNRVADDLGLTPEQRTEVTQLVDRLARGRGAGIPGGP
Sbjct: 354  RPFLNGYYFQIGVETARRQQGTVDNRVADDLGLTPEQRTEVTQLVDRLARGRGAGIPGGP 413

Query: 1322 VNPFVPPVQQQQPAAVYEDIPALEESDDDGDEDGGAGFQNGAQAPAVRQGGQNEFRAQPL 1501
            VNPFVPPVQQQQPAAVYEDIPALEESDDDGDEDGGAGFQNG Q PAVRQGGQ +FRAQPL
Sbjct: 414  VNPFVPPVQQQQPAAVYEDIPALEESDDDGDEDGGAGFQNGVQLPAVRQGGQTDFRAQPL 473

Query: 1502 QDPIQAQLFMPLYPQVSNIPNHQNHQINRIGGMEHQDLLRYNENGDSQQDARGEHGNTFP 1681
            QDPIQAQLFMPLYPQVSN+PN+QNHQINRIGG+EHQDLLRYNENGDSQQDARGEH NTFP
Sbjct: 474  QDPIQAQLFMPLYPQVSNMPNNQNHQINRIGGLEHQDLLRYNENGDSQQDARGEHVNTFP 533

Query: 1682 NNPNQNAQSQVGDWDE 1729
            NNPNQNAQ QVGDWDE
Sbjct: 534  NNPNQNAQLQVGDWDE 549


========================================================================================================================

gene_id            %id    %sim   %cov   %t5   %gap  %t3   start..stop      pep sz ref sz ref id            definition
KM597072.1.2       97.7   98.7   100.0  0.0   0.0   0.0   1916..2374       170    171    AEY76114.1        I | I protein
                                                          2374..2427                                       
                    frameshift in genome at or near position 2374..2374 (+2=>+1)

CLUSTAL 2.1 multiple sequence alignment


predicted       MDQFIKQDETGDLIETGMNVANHFLSAPIQGTNSLSKATIIPGVAPVLIGNPEQKNIQYP
reference       MDQFIKQDETGDLIETGMNVANHFLSAPIQGTNLLSKATIIPGVAPVLIGNPEQKNIQYP
                ********************************* **************************

predicted       TAPHQGSKSKGRSSGARPIIVSSSEVGTGGTQIPEPLFAQTGQGGTVTTVYQDPTIQPTG
reference       TASHQGSKSKGRSSGAKPIIVSSSEVGTGGTQIPEPLFAQTGQGGTVTTVYQDPTIQPTG
                **.*************:*******************************************

predicted       SYRSVELAKIGKERMINRFVEKPRTSTPVTEFK-GGGRERLLKARQSKRRA
reference       SYRSVELAKIGKERMINRFVEKPRTSTPVTEFKRGGGRERLLKARQSKRRA
                ********************************* *****************

>KM597072.1.2	1916	2427
acaaacccagaacaatctagccacagccaactgctcaaatccactacattccattcatat
ttagtctttaagaaaaaattaggcccggaaagaattagttctacgagcatcgacacgatt
atcttgatcgtgtttctttccgggcaagccATGGATCAATTTATAAAACAAGATGAAACT
GGTGATTTAATTGAGACAGGAATGAATGTTGCAAATCACTTCCTATCTGCCCCCATTCAG
GGAACCAACTCACTGAGCAAGGCCACAATCATCCCCGGCGTTGCACCAGTACTCATTGGC
AATCCGGAGCAAAAGAACATTCAGTACCCCACTGCACCACATCAGGGATCCAAGTCAAAG
GGAAGAAGCTCAGGAGCCAGGCCCATCATAGTCTCATCTTCCGAAGTAGGCACTGGAGGG
ACTCAGATTCCTGAGCCCCTTTTCGCACAAACCGGACAAGGTGGCACTGTCACCACCGTT
TATCAGGATCCAACTATCCAACCAACAGGTTCATACCGAAGTGTGGAATTGGCTAAGATA
GGAAAAGAGAGAATGATTAATCGATTTGTTGAAAAACCCAGGACCTCAACGCCGGTAACA
GAATTTAAGGGGGGGGCCGGGAGCGGCTGCTCAAGGCCAGACAATCCAAGAGGAGGGCAT
AGacgggaatggagcctcagctgggtccaaggagaggtccgggtctttgagtggtgcaac
cccatatgctcacctatcactgccgcagcaagattccactcctgcaaatgtgggaattgc
ccagcaaagtgcgatcagtgcgaacgagatta

Length = 171

Score =   355 bits (777), Expect(2) = e-109
Identities = 152/157 (96%), Positives = 153/157 (97%)
Frame = +2

Query: 1916 MDQFIKQDETGDLIETGMNVANHFLSAPIQGTNSLSKATIIPGVAPVLIGNPEQKNIQYP 2095
            MDQFIKQDETGDLIETGMNVANHFLSAPIQGTN LSKATIIPGVAPVLIGNPEQKNIQYP
Sbjct: 1    MDQFIKQDETGDLIETGMNVANHFLSAPIQGTNLLSKATIIPGVAPVLIGNPEQKNIQYP 60

Query: 2096 TAPHQGSKSKGRSSGARPIIVSSSEVGTGGTQIPEPLFAQTGQGGTVTTVYQDPTIQPTG 2275
            TA HQGSKSKGRSSGA+PIIVSSSEVGTGGTQIPEPLFAQTGQGGTVTTVYQDPTIQPTG
Sbjct: 61   TASHQGSKSKGRSSGAKPIIVSSSEVGTGGTQIPEPLFAQTGQGGTVTTVYQDPTIQPTG 120

Query: 2276 SYRSVELAKIGKERMINRFVEKPRTSTPVTEFKGGAG 2386
            SYRSVELAKIGKERMINRFVEKPRTSTPVTEFK G G
Sbjct: 121  SYRSVELAKIGKERMINRFVEKPRTSTPVTEFKRGGG 157

------------------------------------------------------------
frameshifted from +2 to +1 between 2147-2613
  2147 CCCATCATAGTCTCATCTTCCGAAGTAGGCACTGGAGGGACTCAGATTCCTGAGCCCCTT 2206  
  2207 TTCGCACAAACCGGACAAGGTGGCACTGTCACCACCGTTTATCAGGATCCAACTATCCAA 2266  
  2267 CCAACAGGTTCATACCGAAGTGTGGAATTGGCTAAGATAGGAAAAGAGAGAATGATTAAT 2326  
  2327 CGATTTGTTGAAAAACCCAGGACCTCAACGCCGGTAACAGAATTTAAGGGGGGGGCCGGG 2386  
  2387 AGCGGCTGCTCAAGGCCAGACAATCCAAGAGGAGGGCATAGACGGGAATGGAGCCTCAGC 2446  
  2447 TGGGTCCAAGGAGAGGTCCGGGTCTTTGAGTGGTGCAACCCCATATGCTCACCTATCACT 2506  
  2507 GCCGCAGCAAGATTCCACTCCTGCAAATGTGGGAATTGCCCAGCAAAGTGCGATCAGTGC 2566  
  2567 GAACGAGATTATGGACCTCCTTAGAGGTATGGATGCTCGCCTGCAAC              2613  
 frame +2
  2147  p -I--I--V--S--S--S--E--V--G--T--G--G--T--Q--I--P--E--P--L- 2206   |
  2207 -F--A--Q--T--G--Q--G--G--T--V--T--T--V--Y--Q--D--P--T--I--Q- 2266   |
  2267 -P--T--G--S--Y--R--S--V--E--L--A--K--I--G--K--E--R--M--I--N- 2326   |
  2327 -R--F--V--E--K--P--R--T--S--T--P--V--T--E--F--K- g -G- a -G- 2386   |
  2387  s  g  c  s  r  p  d  n  p  r  g  g  h  r  r  e  w  s  l  s  2446  
  2447  w  v  q  g  e  v  r  v  f  e  w  c  n  p  i  c  s  p  i  t  2506  
  2507  a  a  a  r  f  h  s  c  k  c  g  n  c  p  a  k  c  d  q  c  2566  
  2567  e  r  d  y  g  p  p  *  r  y  g  c  s  p  a                 2613  
 frame +3
  2147   p -S- *  s  h  l  p  k  *  a  l  e  g  l  r -F- l  s  p  f 2206  
  2207   s  h  k  p  d  k  v  a  l  s  p -P- f -I- r  i  q  l -S- n 2266  
  2267   q  q -V- h  t  e  v  w  n  w  l -R- *  e  k -R- e  *  l  i 2326  
  2327   d  l  l  k  n -P- g  p  q  r  r  *  q  n  l -R- g  g  p  g 2386  
  2387   a -A- a -Q- g  q  t  i  q  e  e  g  i  d  g  n  g  a  s  a 2446  
  2447   g  s  k  e  r  s  g  s  l  s  g  a  t  p  y  a  h  l  s  l 2506  
  2507   p  q  q  d  s  t  p  a  n  v  g  i  a  q  q  s  a  i  s  a 2566  
  2567   n  e  i  m  d  l  l  r  g  m  d  a  r  l  q                2613  
 frame +1
  2147    h  h -S- l  i  f  r  s  r  h  w  r  d  s  d  s  *  a  p   2206  
  2207 f  r -T- n  r  t  r  w  h  c  h  h  r  l  s  g  s  n  y -P-- 2266  
  2267 T- n  r  f  i  p  k  c  g  i  g  *  d  r  k -R- e  n  d  *   2326  
  2327 s  i  c  *  k  t  q  d  l  n  a  g  n  r  i  * -G--G--G--R-- 2386   |
  2387 E--R--L--L--K--A--R--Q--S--K--R--R--A- *  t  g  m  e  p  q   2446   |
  2447 l  g  p  r  r  g  p  g  l  *  v  v  q  p  h  m  l  t  y  h   2506  
  2507 c  r  s  k  i  p  l  l  q  m  w  e  l  p  s  k  v  r  s  v   2566  
  2567 r  t  r  l  w  t  s  l  e  v  w  m  l  a  c  n               2613  

reference sequence 78-171
IIVSSSEVGTGGTQIPEPLFAQTGQGGTVTTVYQDPTIQPTGSYRSVELAKIGKERMINR
FVEKPRTSTPVTEFKRGGGRERLLKARQSKRRA
------------------------------------------------------------

Score =  40.9 bits (83), Expect(2) = e-109
Identities = 17/17 (100%), Positives = 17/17 (100%)
Frame = +1

Query: 2374 GGGRERLLKARQSKRRA 2424
            GGGRERLLKARQSKRRA
Sbjct: 155  GGGRERLLKARQSKRRA 171


========================================================================================================================

gene_id            %id    %sim   %cov   %t5   %gap  %t3   start..stop      pep sz ref sz ref id            definition
KM597072.1.4       97.4   99.0   100.0  0.0   0.0   0.0   1916..2374       391    391    NP_054708.1       P | phosphoprotein
                                                          2373..3089                                       
                    frameshift in genome at or near position 2374..2373 (+2=>+3)

CLUSTAL 2.1 multiple sequence alignment


predicted       MDQFIKQDETGDLIETGMNVANHFLSAPIQGTNSLSKATIIPGVAPVLIGNPEQKNIQYP
reference       MDQFIKQDETGDLIETGMNVANHFLSAPIQGTNSLSKATIIPGVAPVLIGNPEQKNIQYP
                ************************************************************

predicted       TAPHQGSKSKGRSSGARPIIVSSSEVGTGGTQIPEPLFAQTGQGGTVTTVYQDPTIQPTG
reference       TTSHQGSKSKGRGSGARPIIVSSSEGGTGGTQVPEPLFAQTGQGGIVTTVYQDPTIQPTG
                *:.*********.************ ******:************ **************

predicted       SYRSVELAKIGKERMINRFVEKPRTSTPVTEFKRGGPGAAAQGQTIQEEGIDGNGASAGS
reference       SYRSVELAKIGKERMINRFVEKPRTSTPVTEFKRGGPGAAAQGQTIQEEGIDGNGASAGS
                ************************************************************

predicted       KERSGSLSGATPYAHLSLPQQDSTPANVGIAQQSAISANEIMDLLRGMDARLQHLEQKVD
reference       KERSGSLSGATPYAHLSLPQQDSTPANVGIAPQSAISANEIMDLLRGMDARLQHLEQKVD
                ******************************* ****************************

predicted       KVLAQGSMVTQIKNELSTVKTTLATIEGMMATVKIMDPGNPTGVPVDELRRSFSDHVTIV
reference       KVLAQGSMVTQIKNELSTVKTTLATIEGMMATVKIMDPGNPTGVPVDELRRSFSDHVTIV
                ************************************************************

predicted       SGPGDVSFSSSEEPTLYLDELARPIPKPRPAKQPKPQPVKDLAGRKVMITKMITDCVANP
reference       SGPGDVSFSSGEEPTLYLDELARPVPKPRPAKQPKPQPVKDLAGRKVMITKMITDCVANP
                **********.*************:***********************************

predicted       QMKQAFEQRLAKASTEDALNDIKRDIIRSAI
reference       QMKQVFEQRLAKASTEDALNDIKRDIIRSAI
                ****.**************************

>KM597072.1.4	1916	3089
acaaacccagaacaatctagccacagccaactgctcaaatccactacattccattcatat
ttagtctttaagaaaaaattaggcccggaaagaattagttctacgagcatcgacacgatt
atcttgatcgtgtttctttccgggcaagccATGGATCAATTTATAAAACAAGATGAAACT
GGTGATTTAATTGAGACAGGAATGAATGTTGCAAATCACTTCCTATCTGCCCCCATTCAG
GGAACCAACTCACTGAGCAAGGCCACAATCATCCCCGGCGTTGCACCAGTACTCATTGGC
AATCCGGAGCAAAAGAACATTCAGTACCCCACTGCACCACATCAGGGATCCAAGTCAAAG
GGAAGAAGCTCAGGAGCCAGGCCCATCATAGTCTCATCTTCCGAAGTAGGCACTGGAGGG
ACTCAGATTCCTGAGCCCCTTTTCGCACAAACCGGACAAGGTGGCACTGTCACCACCGTT
TATCAGGATCCAACTATCCAACCAACAGGTTCATACCGAAGTGTGGAATTGGCTAAGATA
GGAAAAGAGAGAATGATTAATCGATTTGTTGAAAAACCCAGGACCTCAACGCCGGTAACA
GAATTTAAGGGGGGGGCCGGGAGCGGCTGCTCAAGGCCAGACAATCCAAGAGGAGGGCAT
AGACGGGAATGGAGCCTCAGCTGGGTCCAAGGAGAGGTCCGGGTCTTTGAGTGGTGCAAC
CCCATATGCTCACCTATCACTGCCGCAGCAAGATTCCACTCCTGCAAATGTGGGAATTGC
CCAGCAAAGTGCGATCAGTGCGAACGAGATTATGGACCTCCTTAGAGGTATGGATGCTCG
CCTGCAACATCTTGAACAAAAGGTGGACAAGGTGCTTGCACAGGGCAGCATGGTGACCCA
AATAAAGAATGAATTATCTACAGTAAAGACAACACTAGCTACAATTGAAGGAATGATGGC
GACAGTAAAGATCATGGATCCTGGAAACCCGACGGGGGTCCCAGTTGATGAGCTTAGAAG
AAGTTTTAGTGATCATGTAACAATTGTTAGTGGACCAGGTGATGTGTCATTCAGCTCCAG
TGAAGAACCTACACTGTATTTGGATGAACTAGCAAGGCCTATCCCCAAGCCTCGTCCTGC
AAAACAGCCAAAACCCCAACCAGTAAAGGATTTAGCAGGACGGAAGGTGATGATAACCAA
GATGATCACTGACTGTGTGGCCAATCCTCAAATGAAGCAGGCGTTCGAGCAACGATTGGC
AAAGGCCAGTACCGAGGATGCCCTGAATGATATCAAGCGAGACATCATACGAAGCGCCAT
ATGAacctaccaagaacaccaaactcacagggaaatccatgaactgatagccgcaatgat
tccctattaaataaaaaataagcacgaacacaagtccaatccagccacagcaacaatggc
cggatcacagatcaaaattcctcttccgaagccc

Length = 391

Score =   350 bits (758), Expect(2) = 0.0
Identities = 148/155 (95%), Positives = 149/155 (96%)
Frame = +2

Query: 1916 MDQFIKQDETGDLIETGMNVANHFLSAPIQGTNSLSKATIIPGVAPVLIGNPEQKNIQYP 2095
            MDQFIKQDETGDLIETGMNVANHFLSAPIQGTNSLSKATIIPGVAPVLIGNPEQKNIQYP
Sbjct: 1    MDQFIKQDETGDLIETGMNVANHFLSAPIQGTNSLSKATIIPGVAPVLIGNPEQKNIQYP 60

Query: 2096 TAPHQGSKSKGRSSGARPIIVSSSEVGTGGTQIPEPLFAQTGQGGTVTTVYQDPTIQPTG 2275
            T  HQGSKSKGR SGARPIIVSSSE GTGGTQ+PEPLFAQTGQGG VTTVYQDPTIQPTG
Sbjct: 61   TTSHQGSKSKGRGSGARPIIVSSSEGGTGGTQVPEPLFAQTGQGGIVTTVYQDPTIQPTG 120

Query: 2276 SYRSVELAKIGKERMINRFVEKPRTSTPVTEFKGG 2380
            SYRSVELAKIGKERMINRFVEKPRTSTPVTEFK G
Sbjct: 121  SYRSVELAKIGKERMINRFVEKPRTSTPVTEFKRG 155

------------------------------------------------------------
frameshifted from +2 to +3 between 2141-2612
  2141 GCCAGGCCCATCATAGTCTCATCTTCCGAAGTAGGCACTGGAGGGACTCAGATTCCTGAG 2200  
  2201 CCCCTTTTCGCACAAACCGGACAAGGTGGCACTGTCACCACCGTTTATCAGGATCCAACT 2260  
  2261 ATCCAACCAACAGGTTCATACCGAAGTGTGGAATTGGCTAAGATAGGAAAAGAGAGAATG 2320  
  2321 ATTAATCGATTTGTTGAAAAACCCAGGACCTCAACGCCGGTAACAGAATTTAAGGGGGGG 2380  
  2381 GCCGGGAGCGGCTGCTCAAGGCCAGACAATCCAAGAGGAGGGCATAGACGGGAATGGAGC 2440  
  2441 CTCAGCTGGGTCCAAGGAGAGGTCCGGGTCTTTGAGTGGTGCAACCCCATATGCTCACCT 2500  
  2501 ATCACTGCCGCAGCAAGATTCCACTCCTGCAAATGTGGGAATTGCCCAGCAAAGTGCGAT 2560  
  2561 CAGTGCGAACGAGATTATGGACCTCCTTAGAGGTATGGATGCTCGCCTGCAA         2612  
 frame +2
  2141  a -R--P--I--I--V--S--S--S--E- v -G--T--G--G--T--Q- i -P--E- 2200   |
  2201 -P--L--F--A--Q--T--G--Q--G--G- t -V--T--T--V--Y--Q--D--P--T- 2260   |
  2261 -I--Q--P--T--G--S--Y--R--S--V--E--L--A--K--I--G--K--E--R--M- 2320   |
  2321 -I--N--R--F--V--E--K--P--R--T--S--T--P--V--T--E--F--K- g -G- 2380   |
  2381  a  g  s  g  c  s  r  p  d  n  p  r  g  g  h  r  r  e  w  s  2440  
  2441  l -S- w  v  q  g -E- v  r  v  f  e  w  c  n  p  i  c  s  p  2500  
  2501  i  t  a  a  a  r  f  h  s  c  k  c  g  n  c  p  a  k  c  d  2560  
  2561  q  c  e  r  d  y  g  p  p  * -R- y  g  c  s  p  a           2612  
 frame +3
  2141   p  g  p  s  * -S- h  l  p  k  *  a  l  e  g  l  r  f  l  s 2200  
  2201   p -F- s  h  k  p  d  k  v  a  l  s  p  p  f  i  r  i  q  l 2260  
  2261   s  n  q  q  v  h  t  e -V- w  n  w  l  r  *  e  k -R- e  * 2320  
  2321   l  i  d  l  l -K- n  p  g  p  q  r  r  *  q  n  l -R--G--G 2380  
  2381 --P--G--A--A--A--Q--G--Q--T--I--Q--E--E--G--I--D--G--N--G--A 2440   |
  2441 --S--A--G--S--K--E--R--S--G--S--L--S--G--A--T--P--Y--A--H--L 2500   |
  2501 --S--L--P--Q--Q--D--S--T--P--A--N--V--G--I--A- q -Q--S--A--I 2560   |
  2561 --S--A--N--E--I--M--D--L--L--R--G--M--D--A--R--L--Q-         2612   |
 frame +1
  2141    q  a  h  h  s  l  i  f  r  s -R- h  w  r  d -S- d -S- *   2200  
  2201 a  p  f  r  t  n  r  t  r  w  h  c  h  h  r  l  s  g  s  n   2260  
  2261 y  p -T- n  r  f  i  p  k  c  g  i  g  *  d  r  k -R- e  n   2320  
  2321 d  *  s  i  c  * -K- t  q  d  l -N- a  g  n  r  i  *  g  g   2380  
  2381 g  r  e  r  l  l  k  a -R- q  s  k  r  r -A- *  t -G- m  e   2440  
  2441 p -Q- l  g  p  r  r -G- p -G- l  *  v  v  q  p  h  m  l  t   2500  
  2501 y  h  c  r  s  k  i  p  l  l  q  m  w  e  l  p  s  k  v  r   2560  
  2561 s  v  r  t  r  l  w  t -S- l  e  v  w  m  l  a  c            2612  

reference sequence 76-233
RPIIVSSSEGGTGGTQVPEPLFAQTGQGGIVTTVYQDPTIQPTGSYRSVELAKIGKERMI
NRFVEKPRTSTPVTEFKRGGPGAAAQGQTIQEEGIDGNGASAGSKERSGSLSGATPYAHL
SLPQQDSTPANVGIAPQSAISANEIMDLLRGMDARLQH
------------------------------------------------------------

Score =   543 bits (1179), Expect(2) = 0.0
Identities = 234/238 (98%), Positives = 235/238 (98%)
Frame = +3

Query: 2373 RGGPGAAAQGQTIQEEGIDGNGASAGSKERSGSLSGATPYAHLSLPQQDSTPANVGIAQQ 2552
            RGGPGAAAQGQTIQEEGIDGNGASAGSKERSGSLSGATPYAHLSLPQQDSTPANVGIA Q
Sbjct: 154  RGGPGAAAQGQTIQEEGIDGNGASAGSKERSGSLSGATPYAHLSLPQQDSTPANVGIAPQ 213

Query: 2553 SAISANEIMDLLRGMDARLQHLEQKVDKVLAQGSMVTQIKNELSTVKTTLATIEGMMATV 2732
            SAISANEIMDLLRGMDARLQHLEQKVDKVLAQGSMVTQIKNELSTVKTTLATIEGMMATV
Sbjct: 214  SAISANEIMDLLRGMDARLQHLEQKVDKVLAQGSMVTQIKNELSTVKTTLATIEGMMATV 273

Query: 2733 KIMDPGNPTGVPVDELRRSFSDHVTIVSGPGDVSFSSSEEPTLYLDELARPIPKPRPAKQ 2912
            KIMDPGNPTGVPVDELRRSFSDHVTIVSGPGDVSFSS EEPTLYLDELARP+PKPRPAKQ
Sbjct: 274  KIMDPGNPTGVPVDELRRSFSDHVTIVSGPGDVSFSSGEEPTLYLDELARPVPKPRPAKQ 333

Query: 2913 PKPQPVKDLAGRKVMITKMITDCVANPQMKQAFEQRLAKASTEDALNDIKRDIIRSAI 3086
            PKPQPVKDLAGRKVMITKMITDCVANPQMKQ FEQRLAKASTEDALNDIKRDIIRSAI
Sbjct: 334  PKPQPVKDLAGRKVMITKMITDCVANPQMKQVFEQRLAKASTEDALNDIKRDIIRSAI 391


========================================================================================================================

gene_id            %id    %sim   %cov   %t5   %gap  %t3   start..stop      pep sz ref sz ref id            definition
KF738113.1.2       97.1   99.1   100.0  0.0   0.0   0.0   1979..2487       171    171    AEY76114.1        I | I protein
                    transcription exception 2435..2441:AAGAGGGGGGG
                    could not find valid stop codon

CLUSTAL 2.1 multiple sequence alignment


predicted       MDQFIKQDETGDLIETGMNVANHFLSAPIQGTNSLSKATIIPGVAPVLIGNPEQKNIQYP
reference       MDQFIKQDETGDLIETGMNVANHFLSAPIQGTNLLSKATIIPGVAPVLIGNPEQKNIQYP
                ********************************* **************************

predicted       TAPHQGSKSKGRSSGARPIIVSSSEVGPGGTQIPEPLFAQTGQGGTVTTVYQDPTIQPTG
reference       TASHQGSKSKGRSSGAKPIIVSSSEVGTGGTQIPEPLFAQTGQGGTVTTVYQDPTIQPTG
                **.*************:**********.********************************

predicted       SYRSVELAKIGRERMINRFVEKPRTSTPVTEFKRGGGRERLLKARQSKRRA
reference       SYRSVELAKIGKERMINRFVEKPRTSTPVTEFKRGGGRERLLKARQSKRRA
                ***********:***************************************

>KF738113.1.2	1979	2487
acaaacccaggacaatctagccacagctaattgctcaaatccactacattccattcatat
ttagtctttaagaaaaaattaggcccggaaagaattagttctacgagcatcgacacaatc
atcttgatcgtgtttctttccgggcaagccATGGATCAATTTATAAAACAAGATGAAACT
GGTGATTTAATTGAGACAGGAATGAACGTTGCAAATCACTTCCTATCTGCCCCCATTCAG
GGAACAAACTCGTTGAGCAAGGCCACAATCATCCCTGGCGTTGCACCGGTACTCATTGGC
AATCCAGAGCAAAAGAACATTCAGTACCCCACTGCACCACATCAGGGATCCAAGTCAAAG
GGAAGAAGCTCAGGGGCCAGGCCCATCATAGTCTCATCTTCCGAAGTAGGCCCTGGAGGG
ACTCAGATTCCTGAGCCCCTTTTCGCACAAACAGGACAAGGTGGCACTGTCACCACCGTT
TATCAGGATCCAACTATCCAACCAACAGGTTCATACCGAAGTGTGGAATTGGCTAAGATA
GGAAGAGAGAGAATGATTAATCGATTTGTTGAAAAACCCAGGACCTCAACGCCGGTAACA
GAATTTAAGAGGGGGGCCGGGAGCGGCTGCTCAAGGCCAGACAATCCAAGAGGAGGGCAc
agacgggaatggagcctcagctgggtccaaggagaggtccgggtctttgagtggtgcaac
cccatatgctcacctatcactgccgcagcaagattccactcctgcaaatgtgggaattgc
ccagcaaagtgcgatcagtgcgaacgaga

Length = 171

Score =   358 bits (775), Expect(2) = e-108
Identities = 151/157 (96%), Positives = 153/157 (97%)
Frame = +2

Query: 1979 MDQFIKQDETGDLIETGMNVANHFLSAPIQGTNSLSKATIIPGVAPVLIGNPEQKNIQYP 2158
            MDQFIKQDETGDLIETGMNVANHFLSAPIQGTN LSKATIIPGVAPVLIGNPEQKNIQYP
Sbjct: 1    MDQFIKQDETGDLIETGMNVANHFLSAPIQGTNLLSKATIIPGVAPVLIGNPEQKNIQYP 60

Query: 2159 TAPHQGSKSKGRSSGARPIIVSSSEVGPGGTQIPEPLFAQTGQGGTVTTVYQDPTIQPTG 2338
            TA HQGSKSKGRSSGA+PIIVSSSEVG GGTQIPEPLFAQTGQGGTVTTVYQDPTIQPTG
Sbjct: 61   TASHQGSKSKGRSSGAKPIIVSSSEVGTGGTQIPEPLFAQTGQGGTVTTVYQDPTIQPTG 120

Query: 2339 SYRSVELAKIGRERMINRFVEKPRTSTPVTEFKRGAG 2449
            SYRSVELAKIG+ERMINRFVEKPRTSTPVTEFKRG G
Sbjct: 121  SYRSVELAKIGKERMINRFVEKPRTSTPVTEFKRGGG 157

------------------------------------------------------------
frameshifted from +2 to +1 between 2210-2679
  2210 CCCATCATAGTCTCATCTTCCGAAGTAGGCCCTGGAGGGACTCAGATTCCTGAGCCCCTT 2269  
  2270 TTCGCACAAACAGGACAAGGTGGCACTGTCACCACCGTTTATCAGGATCCAACTATCCAA 2329  
  2330 CCAACAGGTTCATACCGAAGTGTGGAATTGGCTAAGATAGGAAGAGAGAGAATGATTAAT 2389  
  2390 CGATTTGTTGAAAAACCCAGGACCTCAACGCCGGTAACAGAATTTAAGAGGGGGGCCGGG 2449  
  2450 AGCGGCTGCTCAAGGCCAGACAATCCAAGAGGAGGGCACAGACGGGAATGGAGCCTCAGC 2509  
  2510 TGGGTCCAAGGAGAGGTCCGGGTCTTTGAGTGGTGCAACCCCATATGCTCACCTATCACT 2569  
  2570 GCCGCAGCAAGATTCCACTCCTGCAAATGTGGGAATTGCCCAGCAAAGTGCGATCAGTGC 2629  
  2630 GAACGAGATTATGGACCTCCTTAGAGGGATGGATGCTCGCCTGCAACATC           2679  
 frame +2
  2210  p -I--I--V--S--S--S--E--V--G- p -G--G--T--Q--I--P--E--P--L- 2269   |
  2270 -F--A--Q--T--G--Q--G--G--T--V--T--T--V--Y--Q--D--P--T--I--Q- 2329   |
  2330 -P--T--G--S--Y--R--S--V--E--L--A--K--I--G- r -E--R--M--I--N- 2389   |
  2390 -R--F--V--E--K--P--R--T--S--T--P--V--T--E--F--K--R--G- a -G- 2449   |
  2450  s  g  c  s  r  p  d  n  p  r  g  g  h  r  r  e  w  s  l  s  2509  
  2510  w  v  q  g  e  v  r  v  f  e  w  c  n  p  i  c  s  p  i  t  2569  
  2570  a  a  a  r  f  h  s  c  k  c  g  n  c  p  a  k  c  d  q  c  2629  
  2630  e  r  d  y  g  p  p  *  r  d  g  c  s  p  a  t              2679  
 frame +3
  2210   p -S- *  s  h  l  p  k  *  a  l  e  g  l  r -F- l  s  p  f 2269  
  2270   s  h  k  q  d  k  v  a  l  s  p -P- f -I- r  i  q  l -S- n 2329  
  2330   q  q -V- h  t  e  v  w  n  w  l -R- *  e  e -R- e  *  l  i 2389  
  2390   d  l  l  k  n -P- g  p  q  r  r  *  q  n  l -R- g  g  p  g 2449  
  2450   a -A- a -Q- g  q  t  i  q  e  e  g  t  d  g  n  g  a  s  a 2509  
  2510   g  s  k  e  r  s  g  s  l  s  g  a  t  p  y  a  h  l  s  l 2569  
  2570   p  q  q  d  s  t  p  a  n  v  g  i  a  q  q  s  a  i  s  a 2629  
  2630   n  e  i  m  d  l  l  r  g  m  d  a  r  l  q  h             2679  
 frame +1
  2210    h  h -S- l  i  f  r  s  r  p  w  r  d  s  d  s  *  a  p   2269  
  2270 f  r -T- n  r  t  r  w  h  c  h  h  r  l  s  g  s  n  y -P-- 2329  
  2330 T- n  r  f  i  p  k  c  g  i  g  *  d  r  k -R- e  n  d  *   2389  
  2390 s  i  c  *  k  t  q  d  l  n  a  g  n  r  i  *  e -G--G--R-- 2449   |
  2450 E--R--L--L--K--A--R--Q--S--K--R--R--A- q  t  g  m  e  p  q   2509   |
  2510 l  g  p  r  r  g  p  g  l  *  v  v  q  p  h  m  l  t  y  h   2569  
  2570 c  r  s  k  i  p  l  l  q  m  w  e  l  p  s  k  v  r  s  v   2629  
  2630 r  t  r  l  w  t  s  l  e  g  w  m  l  a  c  n  i            2679  

reference sequence 78-171
IIVSSSEVGTGGTQIPEPLFAQTGQGGTVTTVYQDPTIQPTGSYRSVELAKIGKERMINR
FVEKPRTSTPVTEFKRGGGRERLLKARQSKRRA
------------------------------------------------------------

Score =  38.2 bits (77), Expect(2) = e-108
Identities = 16/16 (100%), Positives = 16/16 (100%)
Frame = +1

Query: 2440 GGRERLLKARQSKRRA 2487
            GGRERLLKARQSKRRA
Sbjct: 156  GGRERLLKARQSKRRA 171


========================================================================================================================

gene_id            %id    %sim   %cov   %t5   %gap  %t3   start..stop      pep sz ref sz ref id            definition
KJ810514.1.1       97.6   99.1   100.0  0.0   0.0   0.0   84..422          549    549    Q77IS8.1          NP | nucleocapsid protein
                                                          422..1732                                        
                    frameshift in genome at or near position 422..422 (+3=>+2)

CLUSTAL 2.1 multiple sequence alignment


predicted       MSSVLKAFERFTIEQELQDRGEEGSIPPETLKSAVKVFVINTPNPTTRYQMLNFCLRIIC
reference       MSSVLKAFERFTIEQELQDRGEEGSIPPETLKSAVKVFVINTPNPTTRYQMLNFCLRIIC
                ************************************************************

predicted       SQNARASHRVGALITLFSLPSAGMQNHIRLADKSPEARIERCEIDGFEPGTYSLIPNARA
reference       SQNARASHRVGALITLFSLPSAGMQNHIRLADRSPEAQIERCEIDGFEPGTYRLIPNARA
                ********************************:****:************** *******

predicted       NLTANEIAAYALLADDLPPTINNGTPYVHADVEGQPCDEIEQFLDRCYSVLIQAWVMVCK
reference       NLTANEIAAYALLADDLPPTINNGTPYVHADVEGQPCDEIEQFLDRCYSVLIQAWVMVCK
                ************************************************************

predicted       CMTAYDQPAGSADRRFAKYQQQGRLEARYMLQPEAQRLIQTAIRKSLVVRQYLTFELQLA
reference       CMTAYDQPAGSADRRFAKYQQQGRLEARYMLQPEAQRLIQTAIRKSLVVRQYLTFELQLA
                ************************************************************

predicted       RRQGLLSNRYYAMVGDIGKYIENSGLTAFFLTLKYALGTKWSPLSLAAFTGELTKLRSLM
reference       RRQGLLSNRYYAMVGDIGKYIENSGLTAFFLTLKYALGTKWSPLSLAAFTGELTKLRSLM
                ************************************************************

predicted       MLYRDLGEQARYLALLEAPQIMDFAPGGYPLIFSYAMGVGTVLDVQMRNYTYARPFLNGY
reference       MLYRGLGEQARYLALLEAPQIMDFAPGGYPLIFSYAMGVGTVLDVQMRNYTYARPFLNGY
                ****.*******************************************************

predicted       YFQIGVETARRQQGTVDNRVADDLGLTPEQRTEVTQLVDRLARGRGAGIPGGPVNPFVPP
reference       YFQIGVETARRQQGTVDNRVADDLGLTPEQRTEVTQLVDRLARGRGAGIPGGPVNPFVPP
                ************************************************************

predicted       VQQQQPAAVYEDIPALEESDDDGDEDGGAGFQNGAQAPAVRQGGQNEFRAQPLQDPIQAQ
reference       VQQQQPAAVYEDIPALEESDDDGDEDGGAGFQNGVQLPAVRQGGQTDFRAQPLQDPIQAQ
                **********************************.* ********.:*************

predicted       LFMPLYPQVSNIPNHQNHQINRIGGMEHQDLLRYNENGDSQQDARGEHGNTFPNNPNQNA
reference       LFMPLYPQVSNMPNNQNHQINRIGGLEHQDLLRYNENGDSQQDARGEHVNTFPNNPNQNA
                ***********:**:**********:********************** ***********

predicted       QSQVGDWDE
reference       QLQVGDWDE
                * *******

>KJ810514.1.1	84	1732
gaagtggtgttttgcgatttcgaggccgggctcgatcctcacctttcattgtcgataggg
gacattttgacactaccttgaaaATGTCGTCCGTGCTCAAAGCATTTGAGCGATTCACGA
TAGAACAGGAACTTCAAGACAGGGGTGAGGAGGGTTCAATTCCGCCGGAGACTTTAAAGT
CAGCAGTCAAAGTCTTCGTTATTAACACACCCAATCCCACCACACGCTACCAGATGCTAA
ACTTTTGCCTAAGAATAATTTGCAGTCAAAATGCTAGGGCTTCTCACAGAGTGGGTGCAT
TGATAACATTATTCTCACTTCCCTCGGCAGGTATGCAAAATCATATTAGACTAGCAGATA
AATCACCCGAAGCCAGAATAGAACGCTGTGAGATTGATGGTTTTGAGCCTGGCACATATA
GCTGATTCCGAATGCACGCGCCAATCTTACTGCCAATGAAATTGCTGCCTATGCTTTGCT
TGCAGATGACCTTCCTCCAACCATAAATAATGGAACTCCTTATGTACATGCAGATGTTGA
AGGGCAGCCGTGTGATGAAATTGAACAATTCCTGGATCGATGCTACAGTGTACTAATCCA
GGCTTGGGTGATGGTCTGTAAATGTATGACAGCTTACGACCAACCTGCTGGATCTGCTGA
TCGGAGATTTGCGAAATACCAGCAGCAAGGTCGCCTGGAAGCAAGATACATGCTGCAGCC
GGAAGCCCAAAGGTTGATTCAAACTGCCATCAGGAAAAGTCTTGTTGTTAGACAGTATCT
TACCTTTGAACTCCAGCTGGCAAGACGGCAGGGGTTGCTATCAAACAGATACTACGCAAT
GGTGGGTGACATTGGAAAGTACATTGAGAATTCAGGCCTTACTGCCTTCTTTCTCACCCT
CAAATATGCACTAGGTACCAAATGGAGTCCTCTGTCATTGGCCGCATTCACCGGTGAACT
CACTAAGCTCCGATCCTTGATGATGTTATATCGAGATCTCGGAGAACAAGCCAGATACCT
TGCTTTGTTGGAGGCTCCCCAAATAATGGACTTTGCTCCCGGGGGCTACCCATTGATATT
CAGTTATGCTATGGGAGTCGGTACAGTCTTAGATGTCCAAATGCGAAATTACACTTATGC
ACGACCTTTCCTAAATGGTTACTATTTCCAGATTGGGGTTGAGACCGCACGACGGCAACA
AGGCACTGTTGACAATAGAGTAGCAGATGATCTAGGCCTGACTCCTGAACAAAGAACTGA
GGTCACTCAGCTTGTTGACAGGCTTGCAAGAGGCAGAGGTGCGGGGATACCAGGTGGGCC
TGTGAATCCCTTTGTTCCTCCAGTTCAACAGCAACAACCTGCTGCCGTATATGAGGACAT
TCCTGCATTGGAGGAATCAGATGACGATGGTGATGAAGATGGCGGTGCAGGATTCCAAAA
TGGAGCACAAGCACCAGCTGTAAGACAGGGAGGTCAAAATGAATTTAGAGCACAGCCGTT
ACAGGATCCAATTCAAGCACAACTCTTCATGCCATTATATCCTCAAGTCAGCAACATCCC
AAATCATCAGAATCATCAGATTAATCGCATCGGGGGGATGGAACACCAAGATTTATTACG
ATACAACGAAAATGGTGATTCTCAGCAGGATGCAAGGGGCGAACACGGAAATACCTTCCC
AAACAATCCCAATCAAAACGCACAGTCACAAGTGGGTGACTGGGATGAGTAAatcactga
catgaccaaactacccccgactgcaacaaacccagaacaatctagccacagccaactgct
caaatccactacattccattcatatttagtctttaagaaaaaattaggcccggaaagaat
tagttctacgagcatcgacacgattatcttgatcgtgtttctttccgggcaagccatgga
tcaatttataaaacaagatgaaactggtg

Length = 549

Score =   263 bits (569), Expect(2) = 0.0
Identities = 110/112 (98%), Positives = 112/112 (100%)
Frame = +3

Query: 84   MSSVLKAFERFTIEQELQDRGEEGSIPPETLKSAVKVFVINTPNPTTRYQMLNFCLRIIC 263
            MSSVLKAFERFTIEQELQDRGEEGSIPPETLKSAVKVFVINTPNPTTRYQMLNFCLRIIC
Sbjct: 1    MSSVLKAFERFTIEQELQDRGEEGSIPPETLKSAVKVFVINTPNPTTRYQMLNFCLRIIC 60

Query: 264  SQNARASHRVGALITLFSLPSAGMQNHIRLADKSPEARIERCEIDGFEPGTY 419
            SQNARASHRVGALITLFSLPSAGMQNHIRLAD+SPEA+IERCEIDGFEPGTY
Sbjct: 61   SQNARASHRVGALITLFSLPSAGMQNHIRLADRSPEAQIERCEIDGFEPGTY 112

------------------------------------------------------------
frameshifted from +3 to +2 between 180-661
   180 TCAGCAGTCAAAGTCTTCGTTATTAACACACCCAATCCCACCACACGCTACCAGATGCTA 239   
   240 AACTTTTGCCTAAGAATAATTTGCAGTCAAAATGCTAGGGCTTCTCACAGAGTGGGTGCA 299   
   300 TTGATAACATTATTCTCACTTCCCTCGGCAGGTATGCAAAATCATATTAGACTAGCAGAT 359   
   360 AAATCACCCGAAGCCAGAATAGAACGCTGTGAGATTGATGGTTTTGAGCCTGGCACATAT 419   
   420 AGCTGATTCCGAATGCACGCGCCAATCTTACTGCCAATGAAATTGCTGCCTATGCTTTGC 479   
   480 TTGCAGATGACCTTCCTCCAACCATAAATAATGGAACTCCTTATGTACATGCAGATGTTG 539   
   540 AAGGGCAGCCGTGTGATGAAATTGAACAATTCCTGGATCGATGCTACAGTGTACTAATCC 599   
   600 AGGCTTGGGTGATGGTCTGTAAATGTATGACAGCTTACGACCAACCTGCTGGATCTGCTG 659   
   660 AT                                                           661   
 frame +3
   180  s -A--V--K--V--F--V--I--N--T--P--N--P--T--T--R--Y--Q--M--L- 239    |
   240 -N--F--C--L--R--I--I--C--S--Q--N--A--R--A--S--H--R--V--G--A- 299    |
   300 -L--I--T--L--F--S--L--P--S--A--G--M--Q--N--H--I--R--L--A--D- 359    |
   360  k -S--P--E--A- r -I--E--R--C--E--I--D--G--F--E--P--G--T--Y- 419    |
   420  s  *  f  r  m  h  a  p  i -L- l  p  m  k  l  l  p  m  l  c  479   
   480 -L- q  m  t  f  l  q  p  *  i  m  e  l  l  m  y  m  q  m  l  539   
   540  k -G- s  r  v  m  k  l  n  n  s  w  i  d  a  t  v  y  *  s  599   
   600  r  l  g  *  w  s  v  n  v  *  q  l  t  t  n  l  l  d  l  l  659   
 frame +1
   180   q -Q- s  k  s  s  l -L- t  h  p  i  p  p  h -A- t  r  c  * 239   
   240   t  f  a  *  e  *  f  a  v  k  m  l  g  l  l  t  e  w  v  h 299   
   300   *  *  h  y  s  h  f  p  r -Q- v  c  k  i  i  l -D- *  q  i 359   
   360   n  h  p  k  p  e  *  n  a  v -R- l  m  v  l  s  l  a  h  i 419   
   420  -A- d  s  e  c  t  r  q  s  y  c  q  * -N- c  c  l  c  f  a 479   
   480   c  r  *  p  s  s  n  h  k  *  w  n  s  l  c  t  c -R--C- * 539   
   540   r  a  a  v  *  *  n  *  t  i  p  g  s -M- l  q  c  t  n -P 599   
   600 - g  l  g  d  g  l  *  m  y  d  s  l  r  p  t  c  w  i  c  * 659   
 frame +2
   180    s  s  q  s  l  r  y  *  h  t  q  s  h  h  t  l  p  d  a   239   
   240 k  l  l  p  k  n  n  l  q  s  k  c  *  g  f  s  q  s -G- c   299   
   300 i  d  n  i  i  l  t  s  l  g  r  y  a  k  s  y  *  t  s  r   359   
   360 *  i  t  r  s -Q- n  r  t  l  *  d  *  w -F- *  a  w  h  i   419   
   420 * -L--I--P--N--A--R--A--N--L--T--A--N--E--I--A--A--Y--A--L-- 479    |
   480 L--A--D--D--L--P--P--T--I--N--N--G--T--P--Y--V--H--A--D--V-- 539    |
   540 E--G--Q--P--C--D--E--I--E--Q--F--L--D--R--C--Y--S--V--L--I-- 599    |
   600 Q--A--W--V--M--V--C--K--C--M--T--A--Y--D--Q--P--A--G--S--A-- 659    |
   660 D-                                                           661   

reference sequence 33-193
AVKVFVINTPNPTTRYQMLNFCLRIICSQNARASHRVGALITLFSLPSAGMQNHIRLADR
SPEAQIERCEIDGFEPGTYRLIPNARANLTANEIAAYALLADDLPPTINNGTPYVHADVE
GQPCDEIEQFLDRCYSVLIQAWVMVCKCMTAYDQPAGSADR
------------------------------------------------------------

Score =  1028 bits (2239), Expect(2) = 0.0
Identities = 426/436 (97%), Positives = 430/436 (98%)
Frame = +2

Query: 422  LIPNARANLTANEIAAYALLADDLPPTINNGTPYVHADVEGQPCDEIEQFLDRCYSVLIQ 601
            LIPNARANLTANEIAAYALLADDLPPTINNGTPYVHADVEGQPCDEIEQFLDRCYSVLIQ
Sbjct: 114  LIPNARANLTANEIAAYALLADDLPPTINNGTPYVHADVEGQPCDEIEQFLDRCYSVLIQ 173

Query: 602  AWVMVCKCMTAYDQPAGSADRRFAKYQQQGRLEARYMLQPEAQRLIQTAIRKSLVVRQYL 781
            AWVMVCKCMTAYDQPAGSADRRFAKYQQQGRLEARYMLQPEAQRLIQTAIRKSLVVRQYL
Sbjct: 174  AWVMVCKCMTAYDQPAGSADRRFAKYQQQGRLEARYMLQPEAQRLIQTAIRKSLVVRQYL 233

Query: 782  TFELQLARRQGLLSNRYYAMVGDIGKYIENSGLTAFFLTLKYALGTKWSPLSLAAFTGEL 961
            TFELQLARRQGLLSNRYYAMVGDIGKYIENSGLTAFFLTLKYALGTKWSPLSLAAFTGEL
Sbjct: 234  TFELQLARRQGLLSNRYYAMVGDIGKYIENSGLTAFFLTLKYALGTKWSPLSLAAFTGEL 293

Query: 962  TKLRSLMMLYRDLGEQARYLALLEAPQIMDFAPGGYPLIFSYAMGVGTVLDVQMRNYTYA 1141
            TKLRSLMMLYR LGEQARYLALLEAPQIMDFAPGGYPLIFSYAMGVGTVLDVQMRNYTYA
Sbjct: 294  TKLRSLMMLYRGLGEQARYLALLEAPQIMDFAPGGYPLIFSYAMGVGTVLDVQMRNYTYA 353

Query: 1142 RPFLNGYYFQIGVETARRQQGTVDNRVADDLGLTPEQRTEVTQLVDRLARGRGAGIPGGP 1321
            RPFLNGYYFQIGVETARRQQGTVDNRVADDLGLTPEQRTEVTQLVDRLARGRGAGIPGGP
Sbjct: 354  RPFLNGYYFQIGVETARRQQGTVDNRVADDLGLTPEQRTEVTQLVDRLARGRGAGIPGGP 413

Query: 1322 VNPFVPPVQQQQPAAVYEDIPALEESDDDGDEDGGAGFQNGAQAPAVRQGGQNEFRAQPL 1501
            VNPFVPPVQQQQPAAVYEDIPALEESDDDGDEDGGAGFQNG Q PAVRQGGQ +FRAQPL
Sbjct: 414  VNPFVPPVQQQQPAAVYEDIPALEESDDDGDEDGGAGFQNGVQLPAVRQGGQTDFRAQPL 473

Query: 1502 QDPIQAQLFMPLYPQVSNIPNHQNHQINRIGGMEHQDLLRYNENGDSQQDARGEHGNTFP 1681
            QDPIQAQLFMPLYPQVSN+PN+QNHQINRIGG+EHQDLLRYNENGDSQQDARGEH NTFP
Sbjct: 474  QDPIQAQLFMPLYPQVSNMPNNQNHQINRIGGLEHQDLLRYNENGDSQQDARGEHVNTFP 533

Query: 1682 NNPNQNAQSQVGDWDE 1729
            NNPNQNAQ QVGDWDE
Sbjct: 534  NNPNQNAQLQVGDWDE 549


========================================================================================================================

gene_id            %id    %sim   %cov   %t5   %gap  %t3   start..stop      pep sz ref sz ref id            definition
KJ810514.1.2       97.1   98.1   100.0  0.0   0.0   0.0   1916..2374       170    171    AEY76114.1        I | I protein
                                                          2374..2427                                       
                    frameshift in genome at or near position 2374..2374 (+2=>+1)
                    stop codon embedded in CDS at 2372..2374

CLUSTAL 2.1 multiple sequence alignment


predicted       MDQFIKQDETGDLIETGMNVANHFLSAPIQGTNSLSKATIIPGVAPVLIGNPEQKNIQYP
reference       MDQFIKQDETGDLIETGMNVANHFLSAPIQGTNLLSKATIIPGVAPVLIGNPEQKNIQYP
                ********************************* **************************

predicted       TAPHQGSKSKGRSSGARPIIVSSSEVGTGGTQIPEPLFAQTGQGGTVTTVYQDPTIQPTG
reference       TASHQGSKSKGRSSGAKPIIVSSSEVGTGGTQIPEPLFAQTGQGGTVTTVYQDPTIQPTG
                **.*************:*******************************************

predicted       SYRSVELAKIGKERMINRFVEKPRTSTPVTEFX-GGGRERLLKARQSKRRA
reference       SYRSVELAKIGKERMINRFVEKPRTSTPVTEFKRGGGRERLLKARQSKRRA
                ********************************  *****************

>KJ810514.1.2	1916	2427
acaaacccagaacaatctagccacagccaactgctcaaatccactacattccattcatat
ttagtctttaagaaaaaattaggcccggaaagaattagttctacgagcatcgacacgatt
atcttgatcgtgtttctttccgggcaagccATGGATCAATTTATAAAACAAGATGAAACT
GGTGATTTAATTGAGACAGGAATGAATGTTGCAAATCACTTCCTATCTGCCCCCATTCAG
GGAACCAACTCACTGAGCAAGGCCACAATCATCCCCGGCGTTGCACCAGTACTCATTGGC
AATCCGGAGCAAAAGAACATTCAGTACCCCACTGCACCACATCAGGGATCCAAGTCAAAG
GGAAGAAGCTCAGGAGCCAGGCCCATCATAGTCTCATCTTCCGAAGTAGGCACTGGAGGG
ACTCAGATTCCTGAGCCCCTTTTCGCACAAACCGGACAAGGTGGCACTGTCACCACCGTT
TATCAGGATCCAACTATCCAACCAACAGGTTCATACCGAAGTGTGGAATTGGCTAAGATA
GGAAAAGAGAGAATGATTAATCGATTTGTTGAAAAACCCAGGACCTCAACGCCGGTAACA
GAATTTTAGGGGGGGGCCGGGAGCGGCTGCTCAAGGCCAGACAATCCAAGAGGAGGGCAT
AGacgggaatggagcctcagctgggtccaaggagaggtccgggtctttgagtggtgcaac
cccatatgctcacctatcactgccgcagcaagattccactcctgcaaatgtgggaattgc
ccagcaaagtgcgatcagtgcgaacgagatta

Length = 171

Score =   354 bits (768), Expect(2) = e-108
Identities = 151/157 (96%), Positives = 152/157 (96%)
Frame = +2

Query: 1916 MDQFIKQDETGDLIETGMNVANHFLSAPIQGTNSLSKATIIPGVAPVLIGNPEQKNIQYP 2095
            MDQFIKQDETGDLIETGMNVANHFLSAPIQGTN LSKATIIPGVAPVLIGNPEQKNIQYP
Sbjct: 1    MDQFIKQDETGDLIETGMNVANHFLSAPIQGTNLLSKATIIPGVAPVLIGNPEQKNIQYP 60

Query: 2096 TAPHQGSKSKGRSSGARPIIVSSSEVGTGGTQIPEPLFAQTGQGGTVTTVYQDPTIQPTG 2275
            TA HQGSKSKGRSSGA+PIIVSSSEVGTGGTQIPEPLFAQTGQGGTVTTVYQDPTIQPTG
Sbjct: 61   TASHQGSKSKGRSSGAKPIIVSSSEVGTGGTQIPEPLFAQTGQGGTVTTVYQDPTIQPTG 120

Query: 2276 SYRSVELAKIGKERMINRFVEKPRTSTPVTEF*GGAG 2386
            SYRSVELAKIGKERMINRFVEKPRTSTPVTEF  G G
Sbjct: 121  SYRSVELAKIGKERMINRFVEKPRTSTPVTEFKRGGG 157

------------------------------------------------------------
frameshifted from +2 to +1 between 2147-2613
  2147 CCCATCATAGTCTCATCTTCCGAAGTAGGCACTGGAGGGACTCAGATTCCTGAGCCCCTT 2206  
  2207 TTCGCACAAACCGGACAAGGTGGCACTGTCACCACCGTTTATCAGGATCCAACTATCCAA 2266  
  2267 CCAACAGGTTCATACCGAAGTGTGGAATTGGCTAAGATAGGAAAAGAGAGAATGATTAAT 2326  
  2327 CGATTTGTTGAAAAACCCAGGACCTCAACGCCGGTAACAGAATTTTAGGGGGGGGCCGGG 2386  
  2387 AGCGGCTGCTCAAGGCCAGACAATCCAAGAGGAGGGCATAGACGGGAATGGAGCCTCAGC 2446  
  2447 TGGGTCCAAGGAGAGGTCCGGGTCTTTGAGTGGTGCAACCCCATATGCTCACCTATCACT 2506  
  2507 GCCGCAGCAAGATTCCACTCCTGCAAATGTGGGAATTGCCCAGCAAAGTGCGATCAGTGC 2566  
  2567 GAACGAGATTATGGACCTCCTTAGAGGTATGGATGCTCGCCTGCAAC              2613  
 frame +2
  2147  p -I--I--V--S--S--S--E--V--G--T--G--G--T--Q--I--P--E--P--L- 2206   |
  2207 -F--A--Q--T--G--Q--G--G--T--V--T--T--V--Y--Q--D--P--T--I--Q- 2266   |
  2267 -P--T--G--S--Y--R--S--V--E--L--A--K--I--G--K--E--R--M--I--N- 2326   |
  2327 -R--F--V--E--K--P--R--T--S--T--P--V--T--E--F- *  g -G- a -G- 2386   |
  2387  s  g  c  s  r  p  d  n  p  r  g  g  h  r  r  e  w  s  l  s  2446  
  2447  w  v  q  g  e  v  r  v  f  e  w  c  n  p  i  c  s  p  i  t  2506  
  2507  a  a  a  r  f  h  s  c  k  c  g  n  c  p  a  k  c  d  q  c  2566  
  2567  e  r  d  y  g  p  p  *  r  y  g  c  s  p  a                 2613  
 frame +3
  2147   p  s  *  s  h  l  p  k  *  a  l  e  g  l  r  f  l -S- p  f 2206  
  2207   s  h  k  p  d  k  v  a  l  s  p -P- f  i  r  i  q  l  s  n 2266  
  2267   q  q -V- h -T- e  v  w  n  w  l  r  *  e  k  r  e  *  l  i 2326  
  2327   d  l -L- k  n  p -G- p  q -R- r  *  q  n -F- r  g  g -P- g 2386  
  2387   a  a  a  q  g  q  t  i  q  e  e -G- i  d  g  n  g  a  s -A 2446  
  2447 - g  s  k  e -R- s  g  s  l  s  g  a  t  p  y  a  h  l  s  l 2506  
  2507   p  q  q  d  s  t  p  a  n  v  g  i  a  q  q  s  a  i  s  a 2566  
  2567   n  e  i  m  d  l  l  r  g  m  d  a  r  l  q                2613  
 frame +1
  2147    h  h -S- l  i  f  r  s  r  h  w  r  d  s  d  s  *  a  p   2206  
  2207 f  r -T- n  r  t  r  w  h  c  h  h  r  l  s  g  s  n  y -P-- 2266  
  2267 T- n  r  f  i  p  k  c  g  i  g  *  d  r  k -R- e  n  d  *   2326  
  2327 s  i  c  *  k  t  q  d  l  n  a  g  n  r  i  l -G--G--G--R-- 2386   |
  2387 E--R--L--L--K--A--R--Q--S--K--R--R--A- *  t  g  m  e  p  q   2446   |
  2447 l  g  p  r  r  g  p  g  l  *  v  v  q  p  h  m  l  t  y  h   2506  
  2507 c  r  s  k  i  p  l  l  q  m  w  e  l  p  s  k  v  r  s  v   2566  
  2567 r  t  r  l  w  t  s  l  e  v  w  m  l  a  c  n               2613  

reference sequence 78-171
IIVSSSEVGTGGTQIPEPLFAQTGQGGTVTTVYQDPTIQPTGSYRSVELAKIGKERMINR
FVEKPRTSTPVTEFKRGGGRERLLKARQSKRRA
------------------------------------------------------------

Score =  40.9 bits (83), Expect(2) = e-108
Identities = 17/17 (100%), Positives = 17/17 (100%)
Frame = +1

Query: 2374 GGGRERLLKARQSKRRA 2424
            GGGRERLLKARQSKRRA
Sbjct: 155  GGGRERLLKARQSKRRA 171


========================================================================================================================

gene_id            %id    %sim   %cov   %t5   %gap  %t3   start..stop      pep sz ref sz ref id            definition
KJ810514.1.3       97.3   98.1   100.0  0.0   0.0   0.0   1916..2590       224    224    BAK26765.1        V | V protein
                    stop codon embedded in CDS at 2372..2374

CLUSTAL 2.1 multiple sequence alignment


predicted       MDQFIKQDETGDLIETGMNVANHFLSAPIQGTNSLSKATIIPGVAPVLIGNPEQKNIQYP
reference       MDQFIKQDETGDLIETGMNVANHFLSAPIQGTNSLSKATIIPGVAPVLIGNPEQKNIQYP
                ************************************************************

predicted       TAPHQGSKSKGRSSGARPIIVSSSEVGTGGTQIPEPLFAQTGQGGTVTTVYQDPTIQPTG
reference       TAPHQGSKSKGRGSGARPIIVSSSEGGTGGTQIPEPLFAQTGQGGIVTTVYQDPTIQPAG
                ************.************ ******************* ************:*

predicted       SYRSVELAKIGKERMINRFVEKPRTSTPVTEFXGGAGSGCSRPDNPRGGHRREWSLSWVQ
reference       SYRSVELAKIGKERMINRFVEKPRTSTPVTEFKRGAGSGCSRPDNPRGGHRREWSLSWVQ
                ********************************  **************************

predicted       GEVRVFEWCNPICSPITAAARFHSCKCGNCPAKCDQCERDYGPP
reference       GEVRVFEWCNPICSPITAAARFHSCKCGNCPAKCDQCERDYGPP
                ********************************************

>KJ810514.1.3	1916	2590
acaaacccagaacaatctagccacagccaactgctcaaatccactacattccattcatat
ttagtctttaagaaaaaattaggcccggaaagaattagttctacgagcatcgacacgatt
atcttgatcgtgtttctttccgggcaagccATGGATCAATTTATAAAACAAGATGAAACT
GGTGATTTAATTGAGACAGGAATGAATGTTGCAAATCACTTCCTATCTGCCCCCATTCAG
GGAACCAACTCACTGAGCAAGGCCACAATCATCCCCGGCGTTGCACCAGTACTCATTGGC
AATCCGGAGCAAAAGAACATTCAGTACCCCACTGCACCACATCAGGGATCCAAGTCAAAG
GGAAGAAGCTCAGGAGCCAGGCCCATCATAGTCTCATCTTCCGAAGTAGGCACTGGAGGG
ACTCAGATTCCTGAGCCCCTTTTCGCACAAACCGGACAAGGTGGCACTGTCACCACCGTT
TATCAGGATCCAACTATCCAACCAACAGGTTCATACCGAAGTGTGGAATTGGCTAAGATA
GGAAAAGAGAGAATGATTAATCGATTTGTTGAAAAACCCAGGACCTCAACGCCGGTAACA
GAATTTTAGGGGGGGGCCGGGAGCGGCTGCTCAAGGCCAGACAATCCAAGAGGAGGGCAT
AGACGGGAATGGAGCCTCAGCTGGGTCCAAGGAGAGGTCCGGGTCTTTGAGTGGTGCAAC
CCCATATGCTCACCTATCACTGCCGCAGCAAGATTCCACTCCTGCAAATGTGGGAATTGC
CCAGCAAAGTGCGATCAGTGCGAACGAGATTATGGACCTCCTTAGaggtatggatgctcg
cctgcaacatcttgaacaaaaggtggacaaggtgcttgcacagggcagcatggtgaccca
aataaagaatgaattatctacagtaaagacaacactagctacaattgaaggaatgatggc
gacagtaaagatcat

Length = 224

Score =   539 bits (1172), Expect = e-158
Identities = 218/224 (97%), Positives = 218/224 (97%)
Frame = +2

Query: 1916 MDQFIKQDETGDLIETGMNVANHFLSAPIQGTNSLSKATIIPGVAPVLIGNPEQKNIQYP 2095
            MDQFIKQDETGDLIETGMNVANHFLSAPIQGTNSLSKATIIPGVAPVLIGNPEQKNIQYP
Sbjct: 1    MDQFIKQDETGDLIETGMNVANHFLSAPIQGTNSLSKATIIPGVAPVLIGNPEQKNIQYP 60

Query: 2096 TAPHQGSKSKGRSSGARPIIVSSSEVGTGGTQIPEPLFAQTGQGGTVTTVYQDPTIQPTG 2275
            TAPHQGSKSKGR SGARPIIVSSSE GTGGTQIPEPLFAQTGQGG VTTVYQDPTIQP G
Sbjct: 61   TAPHQGSKSKGRGSGARPIIVSSSEGGTGGTQIPEPLFAQTGQGGIVTTVYQDPTIQPAG 120

Query: 2276 SYRSVELAKIGKERMINRFVEKPRTSTPVTEF*GGAGSGCSRPDNPRGGHRREWSLSWVQ 2455
            SYRSVELAKIGKERMINRFVEKPRTSTPVTEF  GAGSGCSRPDNPRGGHRREWSLSWVQ
Sbjct: 121  SYRSVELAKIGKERMINRFVEKPRTSTPVTEFKRGAGSGCSRPDNPRGGHRREWSLSWVQ 180

Query: 2456 GEVRVFEWCNPICSPITAAARFHSCKCGNCPAKCDQCERDYGPP 2587
            GEVRVFEWCNPICSPITAAARFHSCKCGNCPAKCDQCERDYGPP
Sbjct: 181  GEVRVFEWCNPICSPITAAARFHSCKCGNCPAKCDQCERDYGPP 224


========================================================================================================================

gene_id            %id    %sim   %cov   %t5   %gap  %t3   start..stop      pep sz ref sz ref id            definition
KJ810514.1.4       97.2   98.7   100.0  0.0   0.0   0.0   1916..2371       391    391    NP_054708.1       P | phosphoprotein
                                                          2370..3089                                       
                    frameshift in genome at or near position 2371..2370 (+2=>+3)

CLUSTAL 2.1 multiple sequence alignment


predicted       MDQFIKQDETGDLIETGMNVANHFLSAPIQGTNSLSKATIIPGVAPVLIGNPEQKNIQYP
reference       MDQFIKQDETGDLIETGMNVANHFLSAPIQGTNSLSKATIIPGVAPVLIGNPEQKNIQYP
                ************************************************************

predicted       TAPHQGSKSKGRSSGARPIIVSSSEVGTGGTQIPEPLFAQTGQGGTVTTVYQDPTIQPTG
reference       TTSHQGSKSKGRGSGARPIIVSSSEGGTGGTQVPEPLFAQTGQGGIVTTVYQDPTIQPTG
                *:.*********.************ ******:************ **************

predicted       SYRSVELAKIGKERMINRFVEKPRTSTPVTEFFRGGPGAAAQGQTIQEEGIDGNGASAGS
reference       SYRSVELAKIGKERMINRFVEKPRTSTPVTEFKRGGPGAAAQGQTIQEEGIDGNGASAGS
                ******************************** ***************************

predicted       KERSGSLSGATPYAHLSLPQQDSTPANVGIAQQSAISANEIMDLLRGMDARLQHLEQKVD
reference       KERSGSLSGATPYAHLSLPQQDSTPANVGIAPQSAISANEIMDLLRGMDARLQHLEQKVD
                ******************************* ****************************

predicted       KVLAQGSMVTQIKNELSTVKTTLATIEGMMATVKIMDPGNPTGVPVDELRRSFSDHVTIV
reference       KVLAQGSMVTQIKNELSTVKTTLATIEGMMATVKIMDPGNPTGVPVDELRRSFSDHVTIV
                ************************************************************

predicted       SGPGDVSFSSSEEPTLYLDELARPIPKPRPAKQPKPQPVKDLAGRKVMITKMITDCVANP
reference       SGPGDVSFSSGEEPTLYLDELARPVPKPRPAKQPKPQPVKDLAGRKVMITKMITDCVANP
                **********.*************:***********************************

predicted       QMKQAFEQRLAKASTEDALNDIKRDIIRSAI
reference       QMKQVFEQRLAKASTEDALNDIKRDIIRSAI
                ****.**************************

>KJ810514.1.4	1916	3089
acaaacccagaacaatctagccacagccaactgctcaaatccactacattccattcatat
ttagtctttaagaaaaaattaggcccggaaagaattagttctacgagcatcgacacgatt
atcttgatcgtgtttctttccgggcaagccATGGATCAATTTATAAAACAAGATGAAACT
GGTGATTTAATTGAGACAGGAATGAATGTTGCAAATCACTTCCTATCTGCCCCCATTCAG
GGAACCAACTCACTGAGCAAGGCCACAATCATCCCCGGCGTTGCACCAGTACTCATTGGC
AATCCGGAGCAAAAGAACATTCAGTACCCCACTGCACCACATCAGGGATCCAAGTCAAAG
GGAAGAAGCTCAGGAGCCAGGCCCATCATAGTCTCATCTTCCGAAGTAGGCACTGGAGGG
ACTCAGATTCCTGAGCCCCTTTTCGCACAAACCGGACAAGGTGGCACTGTCACCACCGTT
TATCAGGATCCAACTATCCAACCAACAGGTTCATACCGAAGTGTGGAATTGGCTAAGATA
GGAAAAGAGAGAATGATTAATCGATTTGTTGAAAAACCCAGGACCTCAACGCCGGTAACA
GAATTTTAGGGGGGGGCCGGGAGCGGCTGCTCAAGGCCAGACAATCCAAGAGGAGGGCAT
AGACGGGAATGGAGCCTCAGCTGGGTCCAAGGAGAGGTCCGGGTCTTTGAGTGGTGCAAC
CCCATATGCTCACCTATCACTGCCGCAGCAAGATTCCACTCCTGCAAATGTGGGAATTGC
CCAGCAAAGTGCGATCAGTGCGAACGAGATTATGGACCTCCTTAGAGGTATGGATGCTCG
CCTGCAACATCTTGAACAAAAGGTGGACAAGGTGCTTGCACAGGGCAGCATGGTGACCCA
AATAAAGAATGAATTATCTACAGTAAAGACAACACTAGCTACAATTGAAGGAATGATGGC
GACAGTAAAGATCATGGATCCTGGAAACCCGACGGGGGTCCCAGTTGATGAGCTTAGAAG
AAGTTTTAGTGATCATGTAACAATTGTTAGTGGACCAGGTGATGTGTCATTCAGCTCCAG
TGAAGAACCTACACTGTATTTGGATGAACTAGCAAGGCCTATCCCCAAGCCTCGTCCTGC
AAAACAGCCAAAACCCCAACCAGTAAAGGATTTAGCAGGACGGAAGGTGATGATAACCAA
GATGATCACTGACTGTGTGGCCAATCCTCAAATGAAGCAGGCGTTCGAGCAACGATTGGC
AAAGGCCAGTACCGAGGATGCCCTGAATGATATCAAGCGAGACATCATACGAAGCGCCAT
ATGAacctaccaagaacaccaaactcacagggaaatccatgaactgatagccgcaatgat
tccctattaaataaaaaataagcacgaacacaagtccaatccagccacagcaacaatggc
cggatcacagatcaaaattcctcttccgaagccc

Length = 391

Score =   346 bits (749), Expect(2) = 0.0
Identities = 146/152 (96%), Positives = 147/152 (96%)
Frame = +2

Query: 1916 MDQFIKQDETGDLIETGMNVANHFLSAPIQGTNSLSKATIIPGVAPVLIGNPEQKNIQYP 2095
            MDQFIKQDETGDLIETGMNVANHFLSAPIQGTNSLSKATIIPGVAPVLIGNPEQKNIQYP
Sbjct: 1    MDQFIKQDETGDLIETGMNVANHFLSAPIQGTNSLSKATIIPGVAPVLIGNPEQKNIQYP 60

Query: 2096 TAPHQGSKSKGRSSGARPIIVSSSEVGTGGTQIPEPLFAQTGQGGTVTTVYQDPTIQPTG 2275
            T  HQGSKSKGR SGARPIIVSSSE GTGGTQ+PEPLFAQTGQGG VTTVYQDPTIQPTG
Sbjct: 61   TTSHQGSKSKGRGSGARPIIVSSSEGGTGGTQVPEPLFAQTGQGGIVTTVYQDPTIQPTG 120

Query: 2276 SYRSVELAKIGKERMINRFVEKPRTSTPVTEF 2371
            SYRSVELAKIGKERMINRFVEKPRTSTPVTEF
Sbjct: 121  SYRSVELAKIGKERMINRFVEKPRTSTPVTEF 152

------------------------------------------------------------
frameshifted from +2 to +3 between 2132-2612
  2132 AGCTCAGGAGCCAGGCCCATCATAGTCTCATCTTCCGAAGTAGGCACTGGAGGGACTCAG 2191  
  2192 ATTCCTGAGCCCCTTTTCGCACAAACCGGACAAGGTGGCACTGTCACCACCGTTTATCAG 2251  
  2252 GATCCAACTATCCAACCAACAGGTTCATACCGAAGTGTGGAATTGGCTAAGATAGGAAAA 2311  
  2312 GAGAGAATGATTAATCGATTTGTTGAAAAACCCAGGACCTCAACGCCGGTAACAGAATTT 2371  
  2372 TAGGGGGGGGCCGGGAGCGGCTGCTCAAGGCCAGACAATCCAAGAGGAGGGCATAGACGG 2431  
  2432 GAATGGAGCCTCAGCTGGGTCCAAGGAGAGGTCCGGGTCTTTGAGTGGTGCAACCCCATA 2491  
  2492 TGCTCACCTATCACTGCCGCAGCAAGATTCCACTCCTGCAAATGTGGGAATTGCCCAGCA 2551  
  2552 AAGTGCGATCAGTGCGAACGAGATTATGGACCTCCTTAGAGGTATGGATGCTCGCCTGCA 2611  
  2612 A                                                            2612  
 frame +2
  2132  s -S--G--A--R--P--I--I--V--S--S--S--E- v -G--T--G--G--T--Q- 2191   |
  2192  i -P--E--P--L--F--A--Q--T--G--Q--G--G- t -V--T--T--V--Y--Q- 2251   |
  2252 -D--P--T--I--Q--P--T--G--S--Y--R--S--V--E--L--A--K--I--G--K- 2311   |
  2312 -E--R--M--I--N--R--F--V--E--K--P--R--T--S--T--P--V--T--E--F- 2371   |
  2372  *  g -G- a  g  s  g  c  s  r  p  d  n  p  r  g  g  h  r  r  2431  
  2432  e  w  s  l -S- w  v  q  g -E- v  r  v  f  e  w  c  n  p  i  2491  
  2492  c  s  p  i  t  a  a  a  r  f  h  s  c  k  c  g  n  c  p  a  2551  
  2552  k  c  d  q  c  e  r  d  y  g  p  p  * -R- y  g  c  s  p  a  2611  
 frame +3
  2132   a  q  e  p  g  p  s  * -S- h  l  p  k  *  a  l  e  g  l  r 2191  
  2192   f  l  s  p -F- s  h  k  p  d  k  v  a  l  s  p  p  f  i  r 2251  
  2252   i  q  l  s  n  q  q  v  h  t  e -V- w  n  w  l  r  *  e  k 2311  
  2312  -R- e  *  l  i  d  l  l -K- n  p  g  p  q  r  r  *  q  n  f 2371  
  2372  -R--G--G--P--G--A--A--A--Q--G--Q--T--I--Q--E--E--G--I--D--G 2431   |
  2432 --N--G--A--S--A--G--S--K--E--R--S--G--S--L--S--G--A--T--P--Y 2491   |
  2492 --A--H--L--S--L--P--Q--Q--D--S--T--P--A--N--V--G--I--A- q -Q 2551   |
  2552 --S--A--I--S--A--N--E--I--M--D--L--L--R--G--M--D--A--R--L--Q 2611   |
  2612 -                                                            2612  
 frame +1
  2132    l  r  s  q  a  h  h  s  l  i  f  r  s -R- h  w  r  d -S-  2191  
  2192 d -S- *  a  p  f  r  t  n  r  t  r  w  h  c  h  h  r  l  s   2251  
  2252 g  s  n  y  p -T- n  r  f  i  p  k  c  g  i  g  *  d  r  k - 2311  
  2312 R- e  n  d  *  s  i  c  * -K- t  q  d  l -N- a  g  n  r  i   2371  
  2372 l  g  g  g  r  e  r  l  l  k  a -R- q  s  k  r  r -A- *  t - 2431  
  2432 G- m  e  p -Q- l  g  p  r  r -G- p -G- l  *  v  v  q  p  h   2491  
  2492 m  l  t  y  h  c  r  s  k  i  p  l  l  q  m  w  e  l  p  s   2551  
  2552 k  v  r  s  v  r  t  r  l  w  t -S- l  e  v  w  m  l  a  c   2611  

reference sequence 73-233
SGARPIIVSSSEGGTGGTQVPEPLFAQTGQGGIVTTVYQDPTIQPTGSYRSVELAKIGKE
RMINRFVEKPRTSTPVTEFKRGGPGAAAQGQTIQEEGIDGNGASAGSKERSGSLSGATPY
AHLSLPQQDSTPANVGIAPQSAISANEIMDLLRGMDARLQH
------------------------------------------------------------

Score =   543 bits (1179), Expect(2) = 0.0
Identities = 234/238 (98%), Positives = 235/238 (98%)
Frame = +3

Query: 2373 RGGPGAAAQGQTIQEEGIDGNGASAGSKERSGSLSGATPYAHLSLPQQDSTPANVGIAQQ 2552
            RGGPGAAAQGQTIQEEGIDGNGASAGSKERSGSLSGATPYAHLSLPQQDSTPANVGIA Q
Sbjct: 154  RGGPGAAAQGQTIQEEGIDGNGASAGSKERSGSLSGATPYAHLSLPQQDSTPANVGIAPQ 213

Query: 2553 SAISANEIMDLLRGMDARLQHLEQKVDKVLAQGSMVTQIKNELSTVKTTLATIEGMMATV 2732
            SAISANEIMDLLRGMDARLQHLEQKVDKVLAQGSMVTQIKNELSTVKTTLATIEGMMATV
Sbjct: 214  SAISANEIMDLLRGMDARLQHLEQKVDKVLAQGSMVTQIKNELSTVKTTLATIEGMMATV 273

Query: 2733 KIMDPGNPTGVPVDELRRSFSDHVTIVSGPGDVSFSSSEEPTLYLDELARPIPKPRPAKQ 2912
            KIMDPGNPTGVPVDELRRSFSDHVTIVSGPGDVSFSS EEPTLYLDELARP+PKPRPAKQ
Sbjct: 274  KIMDPGNPTGVPVDELRRSFSDHVTIVSGPGDVSFSSGEEPTLYLDELARPVPKPRPAKQ 333

Query: 2913 PKPQPVKDLAGRKVMITKMITDCVANPQMKQAFEQRLAKASTEDALNDIKRDIIRSAI 3086
            PKPQPVKDLAGRKVMITKMITDCVANPQMKQ FEQRLAKASTEDALNDIKRDIIRSAI
Sbjct: 334  PKPQPVKDLAGRKVMITKMITDCVANPQMKQVFEQRLAKASTEDALNDIKRDIIRSAI 391


