========================================================================================================================

gene_id            %id    %sim   %cov   %t5   %gap  %t3   start..stop      pep sz ref sz ref id            definition
7.1                95.5   98.9   100.0  0.0   0.0   0.0   3..542           1701   1699   BAC98439.1        POL | nonstructural polyprotein
                                                          541..5106                                        
                    frameshift in genome at or near position 542..541 (+3=>+1)
7.1.1              37.3   62.3   100.0  0.0   0.0   0.0   3..542           332    398    NP_786945.1       protein p48
                                                          541..996                                         
7.1.2              53.0   81.2   100.0  0.0   0.0   0.0   997..2094        366    363    NP_786946.1       NTPase
7.1.3              28.4   58.6   100.0  0.0   0.0   0.0   2095..2628       178    201    NP_786947.1       protein p22
7.1.4              56.8   81.3   100.0  0.0   0.0   0.0   2629..3030       134    138    NP_786948.1       viral genome-linked protein
7.1.5              66.9   91.4   100.0  0.0   0.0   0.0   3031..3573       181    181    NP_786949.1       3C-like protease
7.1.6              64.1   87.4   100.0  0.0   0.0   0.0   3574..5103       510    508    NP_786950.1       RNA-directed RNA polymerase

CLUSTAL 2.1 multiple sequence alignment


predicted       MKMASNDASAAAVANSNNDTAKSSSDKMFSSMAVTFKRALGARPKQPPPRETPQRPPRPP
reference       MKMASNDASAAAAANSNNDTAKSSSDGVLSSMAVTFKRALGARPKQPPPREIPQRPPRPP
                ************.************* ::********************** ********

predicted       TPELVKKIPPPPPNGEDEVVVSYSAKDGVSGLPELSTVRQPEETNTAFSVPPLNQRENRD
reference       TPELVKKIPPPPPNGEDEPVVSYSVKDGVSGLPELTTVRQPGETNTAFSVPPLNQRENRD
                ****************** *****.**********:***** ******************

predicted       AKEPLTGTILEMWDGEIYHYGLYVERGLVLGGGTQPPAAISLAKVELTPLSLFWRPVYTP
reference       AKEPLTGTILEMWDGEIYHYGLYVERGLVLG-VHKPPAAISLAKVELTPLSLFWRPVYTP
                *******************************   :*************************

predicted       PQYLISPDTLKKLHGETFPYTAFDNNCYAFCCWVLDLNDSWLSRRMIQRTTGFFRPYQDW
reference       -QYLISPDTLRRLHGESFPYTAFDNNCYAFCCWVLDLNDSWLCRRMIQRTTGFFRPYQDW
                 *********::****:*************************.*****************

predicted       NRKPLPTIDDSKLKKVANIFLCALSSLFTRPIKDIIGKLRPLNIINILASCDWTFAGIVE
reference       NRKPLPTMDDSKLKKVANIFLCALSSLFTRPIKDIIGKLRPLNILNILASCDWTFAGIVE
                *******:************************************:***************

predicted       SLILLAELFGVFWTPPDVSAMIAPLLGDFELQGPEDLVVELVPVVMGGIGLVLGFTKEKI
reference       SLILLAELFGVFWTPPDVSAMIAPLLGDYELQGPEDLAVELVPIVMGGIGLVLGFTKEKI
                ****************************:********.*****:****************

predicted       GKMLSSAASTLRACKDLGAYGLEIXKLVMKWFFPKKEEANELXMVRSIEDAVLDLEAIEN
reference       GKMLSSAASTLRACKDLGAYGLEILKLVMKWFFPKKEEANELAMVRSIEDAVLDLEAIEN
                ************************ ***************** *****************

predicted       NHMTTLLKDKDSLATYMRTLDLEEEKARKLSTKSASPDIVGTINALLARIAAARSLVHRA
reference       NHMTALLKDKDSLATYMRTLDLEEEKARKLSTKSASPDIVGTINALLARIAAARSLVHRA
                ****:*******************************************************

predicted       KEELSSRPRPVVLMISGRPGIGKTHLAREVAKRIAASLTGDQRVGLIPRNGVDHWDAYKG
reference       KEELSSRPRPVVVMISGRPGIGKTHLARELAKRIAASLTGDQRVGLIPRNGVDHWDAYKG
                ************:****************:******************************

predicted       ERVVLWDDYGMSNPIHDALRLQELADTCPLTLNCDRIENKGKVFDSDVIIITTNLANPAP
reference       ERVVLWDDYGMSNPIHDALRLQELADTCPLTLNCDRIENKGKVFDSDAIIITTNLANPAP
                ***********************************************.************

predicted       LDYVNFEACSRRIDFLVYAEAPEVEKAKRDFPGQPDMWKNAFSSDFSHIKLALAPQGGFD
reference       LDYVNFEACSRRIDFLVYADAPEVEKAKRDFPGQPDMWKNAFSPDFSHIKLMLAPQGGFD
                *******************:***********************.******* ********

predicted       KNGNTPHGKGVMKTLTTGSLIARASGLLHERLDEFELQGPALTTFNFDRNKVLAFRQLAA
reference       KNGNTPHGKGVMKTLTTGSLIARASGLLHERLDEYELQGPTPTTFNFDRNKVLAFRQLAA
                **********************************:*****: ******************

predicted       ENKYGLMDTMKVGRQLKDVKTMPELKQALKNISIKKCQIVYSGCTYTLESDGKGNVKVDR
reference       ENKYGLMDTMRVGRQLKDVRTMPELKQALRNISIKSCQIVYGGCTYMLESDGKGDVKVDR
                **********:********:*********:*****.*****.**** *******:*****

predicted       VQSTSVQTNNELAGALHHLRCARIRYYVKCVQEALYSIIQIAGAAFVTTRIIKRVNIQDL
reference       VQNATVQTNNELAGALHHLRCARIRYYVKCVQEALYSIIQIAGAAFVTTRIVKRMNIQDL
                **.::**********************************************:**:*****

predicted       WSKPQVENTEEATNKDGCPKPKDDEEFVISSDDIKTEGKKGKNKAGRGKKHTAFSSKGLS
reference       WSKPQVEDTEETASKDGCPKPKDDDEFVVSSDDIKTEGKKGKNKSGRGKKHTAFSSKGLS
                *******:***::.**********:***:***************:***************

predicted       DEEYDEYKRIREERNGKYSIEEYLQDRDKYYEEVAIARATEEDFCEEEEAKIRQRIFRPT
reference       DEEYDEYKRIREERNGKYSIEEYLQDRDKYYEEVAIARATEEDFCEEEEAKIRQRIFRPT
                ************************************************************

predicted       RKQRKEERASLGLVTGSEIRKRNPEDFKPKGKLWADDDRSVDYNEKLSFEAPPSIWSRIV
reference       RKQRKEERASLGLVTGSEIRKRNPDDFKPKGKLWADDDRSVDYNERLNFEAPPSIWSRIV
                ************************:********************:*.************

predicted       NFGSGWGFWVSPSLFITSTHVIPQGAKEFFGVPIKQIQVHKSGEFCRLRFPKPIRTDVTG
reference       NFGSGWGFWVSPSLFITSTHVIPQGAQEFFGVSIKQIQIHKSGEFCRLRFPKPIRTDVTG
                **************************:*****.*****:*********************

predicted       MILEEGAPEGTVVTLLIKRSTGELMPLAARMGTHATMKIQGRTVGGQMGMLLTGSNAKSM
reference       MILEEGAPEGTVVTLLIKRPTGELMPLAARMGTHATMKIQGRTVGGQMGMLLTGSNAKSM
                *******************.****************************************

predicted       DLGTTPGDCGCPYIYKRGNDYVVIGVHTAAARGGNTVICATQGGEGEATLEGGDSKGTYC
reference       DLGTTPGDCGCPYIYKRGNDYVVIGVHTAAARGGNTVICATQGSEGEATLEGGDNKGTYC
                *******************************************.**********.*****

predicted       GAPILGPGSAPKLSTKTKFWRSSTAPLPPGTYEPAYLGGKDPRVKGGPSLQQVMRDQLKP
reference       GAPILGPGSAPKLSTKTKFWRSSTAPLPPGTYEPAYLGGKDPRVKGGPSLQQVMRDQLKP
                ************************************************************

predicted       FTEPRGKPPKPSVLEAAKKTIINVLEQTIDPPEKWSFAQACASLDKTTSSGHPHHLRKND
reference       FTEPRGKPPKPSVLEAAKKTIINVLEQTIDPPQKWSFAQACASLDKTTSSGHPHHMRKND
                ********************************:**********************:****

predicted       CWNGESFTGKLADQASKANLMFEEGKNMTPVYTGALKDELVKTDKIYGKIKKRLLWGSDL
reference       CWNGESFTGKLADQASKANLMFEEGKNMTPVYTGALKDELVKTDKIYGRIKKRLLWGSDL
                ************************************************:***********

predicted       ATMIRCARAFGGLMDELKAHCVTLPIRVGMNMNEDGPIIFEKHSRYRYHYDADYSRWDST
reference       ATMIRCARAFGGLMEELKAHCVTLPVRVGMNMNEDGPIIFERHSRYKYHYDADYSRWDST
                **************:**********:***************:****:*************

predicted       QQRAVLAAALEIMVKFSSEPHLAQVVAEDLLSPSVVDVGDFTISINEGLPSGVPCTSQWN
reference       QQRAVLAAALEIMVKFSPEPHLAQKVAEDLLSPSVMDVGDFKISINEGLPSGVPCTSQWN
                *****************.****** **********:*****.******************

predicted       SIAHWLLTLCALSEVTNLSPDIIQANSLFSFYGDDEIVSTDIKLDPEKLTAKLKEYGLKP
reference       SIAHWLLTLCALSEVTNLSPDIIQANSLFSFYGDDEIVSTDIKLDPEKLTAKLKEYGLKP
                ************************************************************

predicted       TRPDKTEGPLVISEDLDGLTFLRRTVTRDPAGWFGKLEQSSILRQMYWTRGPNHEDPSES
reference       TRPDKTEGPLVISEDLNGLTFLRRTVTRDPAGWFGKLEQSSILRQMYWTRGPNHEDPSET
                ****************:******************************************:

predicted       MIPHSQRPIQLMSLLGEAALHGPTFYSKISKLVIAELKEGGMDFYVPRQEPMFRWMRFSD
reference       MIPHSQRPIQLMSLLGEAALHGPAFYSKISKLVIAELKEGGMDFYVPRQEPMFRWMRFSD
                ***********************:************************************

predicted       LSTWEGDRNLAPSFVNEDGVE
reference       LSTWEGDRNLAPSFVNEDGVE
                *********************

>7.1	3	5106
gaATGAAGATGGCGTCTAACGACGCTTCCGCTGCCGCTGTTGCTAACAGCAACAACGACA
CCGCAAAATCTTCAAGTGACAAAATGTTTTCTAGCATGGCTGTCACTTTTAAACGAGCCC
TCGGGGCGCGGCCTAAACAGCCCCCCCCGAGGGAAACACCACAAAGACCCCCACGACCAC
CTACTCCAGAACTGGTCAAAAAGATCCCTCCTCCCCCGCCCAACGGAGAGGATGAAGTAG
TGGTTTCTTATAGTGCCAAAGATGGCGTTTCCGGTTTACCTGAGCTTTCCACCGTCAGGC
AACCGGAAGAAACCAATACGGCCTTCAGTGTCCCTCCACTCAACCAGAGGGAGAATAGAG
ATGCTAAGGAACCACTGACTGGAACAATTCTGGAAATGTGGGATGGAGAAATCTACCATT
ATGGCCTGTATGTTGAGCGAGGTCTTGTGCTGGGTGGTGGCACACAACCACCAGCTGCCA
TAAGCCTCGCCAAGGTCGAACTAACACCACTCTCCTTGTTCTGGAGACCTGTGTACACTC
CCCCAGTACCTCATCTCTCCAGACACTCTCAAGAAATTACACGGAGAAACGTTTCCCTAC
ACAGCCTTTGACAACAATTGCTATGCCTTTTGTTGTTGGGTCCTGGATCTAAATGACTCG
TGGCTGAGTAGGAGAATGATCCAGAGAACAACTGGCTTCTTCAGACCCTACCAAGACTGG
AATAGGAAACCCCTCCCCACTATAGATGACTCCAAATTAAAGAAGGTAGCTAACATTTTC
CTGTGCGCCCTGTCTTCGCTATTCACCAGGCCCATAAAAGACATAATAGGAAAGCTAAGA
CCTCTCAACATCATCAACATCCTGGCTTCATGTGATTGGACTTTCGCAGGCATAGTGGAG
TCCTTGATACTCTTGGCAGAGCTCTTTGGAGTCTTCTGGACACCCCCAGATGTGTCTGCG
ATGATTGCCCCCTTACTCGGTGATTTCGAGTTACAAGGACCTGAGGACCTTGTAGTGGAG
CTCGTCCCTGTAGTAATGGGGGGAATTGGTTTGGTGCTGGGATTCACCAAAGAGAAGATT
GGAAAAATGTTGTCATCTGCTGCATCCACCTTGAGAGCTTGTAAAGATCTTGGTGCATAT
GGGCTAGAGATCYTAAAGTTAGTCATGAAGTGGTTCTTCCCGAAGAAAGAGGAGGCAAAT
GAACTGGMTATGGTGAGATCCATCGAGGATGCAGTACTGGACCTTGAGGCAATTGAAAAC
AACCATATGACCACCTTGCTCAAAGACAAAGACAGCCTGGCAACCTACATGAGAACCCTT
GACCTCGAGGAAGAGAAAGCCAGAAAACTCTCAACCAAGTCTGCTTCACCTGACATCGTG
GGCACAATCAACGCCCTTCTGGCGAGAATCGCCGCTGCACGCTCCCTGGTGCACCGAGCG
AAGGAGGAGCTTTCCAGCAGACCAAGACCTGTAGTCTTGATGATATCAGGCAGACCAGGG
ATAGGGAAGACCCACCTTGCTAGGGAAGTGGCTAAGAGAATCGCAGCCTCCCTCACAGGA
GACCAGCGTGTAGGCCTCATCCCACGCAATGGCGTCGATCACTGGGATGCGTACAAGGGG
GAGAGGGTCGTCCTATGGGACGACTATGGAATGAGCAATCCCATCCACGACGCCCTCAGG
CTGCAAGAACTCGCTGACACTTGCCCCCTCACTCTAAATTGTGACAGGATTGAGAATAAA
GGAAAGGTCTTTGACAGCGATGTCATCATTATCACTACTAATCTGGCCAACCCAGCACCA
CTGGACTATGTCAACTTTGAAGCGTGCTCGAGGCGCATCGATTTCCTCGTGTATGCAGAA
GCCCCCGAGGTCGAAAAGGCGAAGCGTGACTTCCCGGGCCAACCTGATATGTGGAAAAAC
GCTTTTAGTTCTGATTTCTCACACATAAAATTGGCACTGGCTCCACAAGGTGGCTTTGAT
AAGAACGGGAACACCCCACACGGGAAGGGCGTCATGAAGACTCTCACCACTGGCTCCCTC
ATTGCCCGGGCATCAGGGCTGCTCCATGAGAGATTGGATGAGTTTGAACTACAGGGCCCA
GCTCTTACCACCTTCAACTTTGACCGCAACAAAGTGCTTGCCTTCAGGCAGCTTGCTGCT
GAAAACAAATATGGGTTGATGGACACAATGAAAGTTGGGAGGCAGCTCAAGGATGTCAAA
ACCATGCCAGAACTTAAACAAGCACTCAAGAATATCTCAATCAAGAAGTGCCAGATTGTG
TATAGTGGTTGCACCTACACACTTGAGTCTGATGGCAAGGGCAATGTGAAAGTTGACAGA
GTTCAGAGCACCTCCGTACAGACCAACAATGAGCTGGCTGGCGCCCTGCACCATCTAAGG
TGCGCCAGAATCAGGTACTATGTCAAGTGTGTCCAGGAGGCCCTGTATTCTATCATCCAG
ATTGCTGGGGCTGCATTTGTCACCACGCGCATCATCAAGCGTGTGAACATTCAAGACTTA
TGGTCCAAGCCACAAGTGGAAAACACAGAGGAGGCTACCAACAAGGACGGGTGCCCAAAA
CCCAAAGATGATGAGGAGTTCGTCATTTCATCTGACGACATTAAAACTGAGGGTAAGAAA
GGGAAGAACAAGGCTGGCCGTGGCAAGAAGCACACAGCCTTCTCAAGTAAAGGTCTCAGT
GATGAAGAGTATGATGAGTACAAGAGAATTAGAGAGGAAAGGAATGGCAAGTACTCCATA
GAGGAGTACCTTCAGGACAGGGACAAATACTATGAGGAGGTGGCCATTGCCAGGGCGACC
GAGGAAGACTTCTGTGAAGAGGAGGAGGCCAAGATCCGGCAAAGGATCTTCAGACCAACA
AGGAAACAACGCAAGGAAGAAAGAGCTTCTCTCGGTTTAGTCACAGGTTCTGAAATTAGG
AAAAGAAACCCAGAAGACTTCAAGCCCAAGGGGAAACTATGGGCTGACGATGACAGAAGT
GTGGACTACAATGAGAAACTCAGTTTTGAGGCCCCACCAAGCATCTGGTCAAGGATAGTC
AACTTTGGCTCAGGTTGGGGTTTTTGGGTCTCCCCCAGCCTGTTCATAACATCAACCCAC
GTCATACCCCAAGGTGCAAAGGAGTTCTTTGGAGTCCCCATCAAACAAATTCAGGTACAC
AAGTCAGGCGAGTTCTGTCGCTTGAGGTTCCCAAAACCAATCAGGACTGATGTGACTGGC
ATGATCTTGGAAGAAGGTGCGCCCGAAGGCACCGTGGTCACACTACTCATCAAAAGGTCT
ACTGGAGAACTCATGCCCCTAGCAGCTAGAATGGGGACCCATGCAACCATGAAAATTCAA
GGGCGCACTGTTGGAGGTCAGATGGGTATGCTTCTGACAGGATCCAACGCCAAAAGCATG
GATCTAGGCACCACACCAGGTGATTGCGGCTGTCCCTACATCTACAAGAGAGGAAATGAC
TATGTGGTCATTGGAGTCCACACGGCTGCCGCTCGTGGGGGAAACACTGTCATATGTGCC
ACCCAGGGGGGTGAGGGGGAAGCTACACTTGAAGGTGGTGACAGTAAGGGAACATACTGT
GGTGCACCAATCCTAGGCCCAGGGAGTGCCCCAAAACTTAGCACCAAAACCAAATTCTGG
AGATCATCCACAGCACCACTCCCACCTGGCACCTATGAACCAGCCTACCTTGGTGGCAAG
GACCCCAGAGTCAAGGGTGGCCCCTCGTTGCAGCAAGTCATGAGGGACCAGCTGAAACCA
TTTACAGAGCCCAGGGGTAAGCCACCAAAGCCAAGTGTGTTAGAAGCTGCCAAGAAAACC
ATCATCAATGTCCTTGAACAAACAATTGACCCACCTGAGAAGTGGTCGTTCGCACAAGCT
TGCGCGTCCCTTGACAAGACCACTTCTAGCGGCCATCCGCACCACTTGCGGAAAAACGAC
TGCTGGAACGGGGAATCCTTCACAGGCAAGCTGGCAGACCAGGCTTCCAAGGCCAACCTG
ATGTTTGAAGAAGGGAAAAACATGACCCCAGTCTACACAGGTGCACTTAAGGATGAATTA
GTCAAAACTGACAAAATTTATGGTAAGATCAAGAAGAGGCTTCTCTGGGGCTCGGATTTA
GCAACCATGATCCGGTGTGCTCGAGCATTCGGAGGCCTAATGGATGAACTCAAAGCACAC
TGTGTCACACTTCCTATCAGAGTTGGTATGAATATGAATGAGGATGGCCCCATCATCTTC
GAGAAGCATTCCAGGTACAGATACCACTATGATGCTGATTACTCTCGGTGGGATTCAACA
CAACAGAGAGCCGTGCTGGCAGCTGCTCTAGAAATCATGGTTAAATTCTCCTCAGAACCA
CATTTGGCTCAGGTAGTCGCAGAAGACCTTCTTTCTCCTAGCGTGGTGGATGTGGGTGAC
TTCACAATATCAATCAACGAGGGTCTTCCCTCTGGGGTGCCCTGCACCTCCCAATGGAAC
TCCATCGCCCACTGGCTTCTCACTCTCTGTGCACTCTCCGAAGTTACAAATTTGTCTCCA
GACATCATACAGGCTAATTCTCTCTTCTCCTTCTATGGTGATGATGAAATTGTTAGTACA
GACATAAAATTAGACCCAGAGAAGTTGACAGCAAAGCTTAAGGAATATGGGTTGAAACCA
ACCCGCCCTGATAAAACTGAAGGACCTCTTGTTATTTCTGAAGACTTAGATGGTTTGACT
TTCCTGCGGAGAACTGTGACCCGCGACCCAGCTGGTTGGTTTGGAAAACTGGAGCAGAGC
TCAATACTCAGGCAAATGTACTGGACTAGGGGCCCCAACCATGAAGATCCATCTGAATCA
ATGATTCCACACTCTCAGAGACCCATACAATTGATGTCCTTACTGGGAGAGGCCGCACTC
CACGGCCCAACATTCTACAGTAAAATCAGCAAATTAGTCATTGCAGAGCTAAAAGAAGGT
GGTATGGATTTTTACGTGCCCAGGCAAGAGCCAATGTTCAGATGGATGAGATTCTCAGAT
CTGAGCACGTGGGAGGGCGATCGCAATCTGGCTCCCAGTTTTGTGAATGAAGATGGCGTC
GAATGAcgccaacccatctgatgggtccgcagccaacctcgtcccagaggtcaacaatga
ggttatggctttggagcccgttgtcggtgccgctattgcggcgcctgtagcgggccaaca
aaatgtaattgacccctggattagaaataattttgtacaagcccctggtggagagttcac
agtatcccctagaaacgctccaggtgaaatactatggagcgcgcccttaggccctgatct
gaatccctacctatctcatttggccagaatgtataatggttatgcaggtggctttgaagt
gcag

Length = 1699

Score =   344 bits (745), Expect(3) = 0.0
Identities = 144/158 (91%), Positives = 146/158 (92%)
Frame = +3

Query: 3    MKMASNDASAAAVANSNNDTAKSSSDKMFSSMAVTFKRALGARPKQPPPRETPQRPPRPP 182
            MKMASNDASAAA ANSNNDTAKSSSD + SSMAVTFKRALGARPKQPPPRE PQRPPRPP
Sbjct: 1    MKMASNDASAAAAANSNNDTAKSSSDGVLSSMAVTFKRALGARPKQPPPREIPQRPPRPP 60

Query: 183  TPELVKKIPPPPPNGEDEVVVSYSAKDGVSGLPELSTVRQPEETNTAFSVPPLNQRENRD 362
            TPELVKKIPPPPPNGEDE VVSYS KDGVSGLPEL+TVRQP ETNTAFSVPPLNQRENRD
Sbjct: 61   TPELVKKIPPPPPNGEDEPVVSYSVKDGVSGLPELTTVRQPGETNTAFSVPPLNQRENRD 120

Query: 363  AKEPLTGTILEMWDGEIYHYGLYVERGLVLGGGTQPPA 476
            AKEPLTGTILEMWDGEIYHYGLYVERGLVLG    P A
Sbjct: 121  AKEPLTGTILEMWDGEIYHYGLYVERGLVLGVHKPPAA 158

Score =  64.3 bits (134), Expect(3) = 0.0
Identities = 26/29 (89%), Positives = 27/29 (93%)
Frame = +3

Query: 456  GGTQPPAAISLAKVELTPLSLFWRPVYTP 542
            G  +PPAAISLAKVELTPLSLFWRPVYTP
Sbjct: 151  GVHKPPAAISLAKVELTPLSLFWRPVYTP 179

------------------------------------------------------------
frameshifted from +3 to +1 between 303-780
   303 CCGGAAGAAACCAATACGGCCTTCAGTGTCCCTCCACTCAACCAGAGGGAGAATAGAGAT 362   
   363 GCTAAGGAACCACTGACTGGAACAATTCTGGAAATGTGGGATGGAGAAATCTACCATTAT 422   
   423 GGCCTGTATGTTGAGCGAGGTCTTGTGCTGGGTGGTGGCACACAACCACCAGCTGCCATA 482   
   483 AGCCTCGCCAAGGTCGAACTAACACCACTCTCCTTGTTCTGGAGACCTGTGTACACTCCC 542   
   543 CCAGTACCTCATCTCTCCAGACACTCTCAAGAAATTACACGGAGAAACGTTTCCCTACAC 602   
   603 AGCCTTTGACAACAATTGCTATGCCTTTTGTTGTTGGGTCCTGGATCTAAATGACTCGTG 662   
   663 GCTGAGTAGGAGAATGATCCAGAGAACAACTGGCTTCTTCAGACCCTACCAAGACTGGAA 722   
   723 TAGGAAACCCCTCCCCACTATAGATGACTCCAAATTAAAGAAGGTAGCTAACATTTTC   780   
 frame +3
   303 -P- e -E--T--N--T--A--F--S--V--P--P--L--N--Q--R--E--N--R--D- 362    |
   363 -A--K--E--P--L--T--G--T--I--L--E--M--W--D--G--E--I--Y--H--Y- 422    |
   423 -G--L--Y--V--E--R--G--L--V--L--G- g  g  t  q -P- p -A- a  i  482    |
   483  s  l  a  k  v  e  l  t  p  l  s  l  f  w  r  p  v  y  t  p  542   
   543  p  v  p  h  l  s  r  h  s  q  e  i  t  r  r  n  v  s  l  h  602   
   603  s  l  *  q  q  l  l  c  l  l  l  l  g  p  g  s  k  *  l  v  662   
   663  a  e  *  e  n  d  p  e  n  n  w  l  l  q  t  l  p  r  l  e  722   
   723  *  e  t -P- p  h  y  r  *  l  q  i -K- e  g  s  *  h  f     780   
 frame +1
   303   r  k  k  p  i  r  p  s  v -S- l  h  s  t  r  g -R- i  e  m 362   
   363   l  r  n  h  * -L- e  q  f  w  k  c  g  m  e  k  s  t  i  m 422   
   423   a  c  m  l  s -E- v  l  c  w  v  v  a -H- n  h  q  l  p  * 482   
   483   a  s  p  r  s  n  *  h  h  s  p  c  s  g  d  l  c  t  l -P 542   
   543 --Q--Y--L--I--S--P--D--T--L- k  k -L--H--G--E- t -F--P--Y--T 602    |
   603 --A--F--D--N--N--C--Y--A--F--C--C--W--V--L--D--L--N--D--S--W 662    |
   663 --L- s -R--R--M--I--Q--R--T--T--G--F--F--R--P--Y--Q--D--W--N 722    |
   723 --R--K--P--L--P--T- i -D--D--S--K--L--K--K--V--A--N--I--F-   780    |
 frame +2
   303    g  r  n  q  y  g  l  q  c  p  s  t  q  p  e  g  e  *  r   362   
   363 c  * -G- t  t  d  w  n  n  s  g  n  v  g  w  r  n -L- p  l   422   
   423 w  p  v  c  * -A- r -S- c -A- g  w  w  h -T- t  t -S- c  h   482   
   483 k  p  r  q  g  r  t  n  t  t  l  l  v  l  e  t  c  v  h  s   542   
   543 p  s  t  s  s  l  q  t  l  s  r -N- y  t  e  k  r  f  p  t   602   
   603 q  p -L- t  t  i  a  m  p  f  v  v  g  s  w  i  *  m  t  r   662   
   663 g  *  v  g  e  *  s -R- e  q -L- a  s  s -D- p  t -K- t  g   722   
   723 i  g  n  p  s  p -L- *  m  t  p  n  *  r  r  *  l  t  f      780   

reference sequence 100-258
PGETNTAFSVPPLNQRENRDAKEPLTGTILEMWDGEIYHYGLYVERGLVLGVHKPPAAIS
LAKVELTPLSLFWRPVYTPQYLISPDTLRRLHGESFPYTAFDNNCYAFCCWVLDLNDSWL
CRRMIQRTTGFFRPYQDWNRKPLPTMDDSKLKKVANIFL
------------------------------------------------------------

Score =  3554 bits (7750), Expect(3) = 0.0
Identities = 1459/1521 (95%), Positives = 1499/1521 (98%)
Frame = +1

Query: 541  PQYLISPDTLKKLHGETFPYTAFDNNCYAFCCWVLDLNDSWLSRRMIQRTTGFFRPYQDW 720
            PQYLISPDTL++LHGE+FPYTAFDNNCYAFCCWVLDLNDSWL RRMIQRTTGFFRPYQDW
Sbjct: 179  PQYLISPDTLRRLHGESFPYTAFDNNCYAFCCWVLDLNDSWLCRRMIQRTTGFFRPYQDW 238

Query: 721  NRKPLPTIDDSKLKKVANIFLCALSSLFTRPIKDIIGKLRPLNIINILASCDWTFAGIVE 900
            NRKPLPT+DDSKLKKVANIFLCALSSLFTRPIKDIIGKLRPLNI+NILASCDWTFAGIVE
Sbjct: 239  NRKPLPTMDDSKLKKVANIFLCALSSLFTRPIKDIIGKLRPLNILNILASCDWTFAGIVE 298

Query: 901  SLILLAELFGVFWTPPDVSAMIAPLLGDFELQGPEDLVVELVPVVMGGIGLVLGFTKEKI 1080
            SLILLAELFGVFWTPPDVSAMIAPLLGD+ELQGPEDL VELVP+VMGGIGLVLGFTKEKI
Sbjct: 299  SLILLAELFGVFWTPPDVSAMIAPLLGDYELQGPEDLAVELVPIVMGGIGLVLGFTKEKI 358

Query: 1081 GKMLSSAASTLRACKDLGAYGLEILKLVMKWFFPKKEEANELXMVRSIEDAVLDLEAIEN 1260
            GKMLSSAASTLRACKDLGAYGLEILKLVMKWFFPKKEEANEL MVRSIEDAVLDLEAIEN
Sbjct: 359  GKMLSSAASTLRACKDLGAYGLEILKLVMKWFFPKKEEANELAMVRSIEDAVLDLEAIEN 418

Query: 1261 NHMTTLLKDKDSLATYMRTLDLEEEKARKLSTKSASPDIVGTINALLARIAAARSLVHRA 1440
            NHMT LLKDKDSLATYMRTLDLEEEKARKLSTKSASPDIVGTINALLARIAAARSLVHRA
Sbjct: 419  NHMTALLKDKDSLATYMRTLDLEEEKARKLSTKSASPDIVGTINALLARIAAARSLVHRA 478

Query: 1441 KEELSSRPRPVVLMISGRPGIGKTHLAREVAKRIAASLTGDQRVGLIPRNGVDHWDAYKG 1620
            KEELSSRPRPVV+MISGRPGIGKTHLARE+AKRIAASLTGDQRVGLIPRNGVDHWDAYKG
Sbjct: 479  KEELSSRPRPVVVMISGRPGIGKTHLARELAKRIAASLTGDQRVGLIPRNGVDHWDAYKG 538

Query: 1621 ERVVLWDDYGMSNPIHDALRLQELADTCPLTLNCDRIENKGKVFDSDVIIITTNLANPAP 1800
            ERVVLWDDYGMSNPIHDALRLQELADTCPLTLNCDRIENKGKVFDSD IIITTNLANPAP
Sbjct: 539  ERVVLWDDYGMSNPIHDALRLQELADTCPLTLNCDRIENKGKVFDSDAIIITTNLANPAP 598

Query: 1801 LDYVNFEACSRRIDFLVYAEAPEVEKAKRDFPGQPDMWKNAFSSDFSHIKLALAPQGGFD 1980
            LDYVNFEACSRRIDFLVYA+APEVEKAKRDFPGQPDMWKNAFS DFSHIKL LAPQGGFD
Sbjct: 599  LDYVNFEACSRRIDFLVYADAPEVEKAKRDFPGQPDMWKNAFSPDFSHIKLMLAPQGGFD 658

Query: 1981 KNGNTPHGKGVMKTLTTGSLIARASGLLHERLDEFELQGPALTTFNFDRNKVLAFRQLAA 2160
            KNGNTPHGKGVMKTLTTGSLIARASGLLHERLDE+ELQGP  TTFNFDRNKVLAFRQLAA
Sbjct: 659  KNGNTPHGKGVMKTLTTGSLIARASGLLHERLDEYELQGPTPTTFNFDRNKVLAFRQLAA 718

Query: 2161 ENKYGLMDTMKVGRQLKDVKTMPELKQALKNISIKKCQIVYSGCTYTLESDGKGNVKVDR 2340
            ENKYGLMDTM+VGRQLKDV+TMPELKQAL+NISIK CQIVY GCTY LESDGKG+VKVDR
Sbjct: 719  ENKYGLMDTMRVGRQLKDVRTMPELKQALRNISIKSCQIVYGGCTYMLESDGKGDVKVDR 778

Query: 2341 VQSTSVQTNNELAGALHHLRCARIRYYVKCVQEALYSIIQIAGAAFVTTRIIKRVNIQDL 2520
            VQ+ +VQTNNELAGALHHLRCARIRYYVKCVQEALYSIIQIAGAAFVTTRI+KR+NIQDL
Sbjct: 779  VQNATVQTNNELAGALHHLRCARIRYYVKCVQEALYSIIQIAGAAFVTTRIVKRMNIQDL 838

Query: 2521 WSKPQVENTEEATNKDGCPKPKDDEEFVISSDDIKTEGKKGKNKAGRGKKHTAFSSKGLS 2700
            WSKPQVE+TEE  +KDGCPKPKDD+EFV+SSDDIKTEGKKGKNK+GRGKKHTAFSSKGLS
Sbjct: 839  WSKPQVEDTEETASKDGCPKPKDDDEFVVSSDDIKTEGKKGKNKSGRGKKHTAFSSKGLS 898

Query: 2701 DEEYDEYKRIREERNGKYSIEEYLQDRDKYYEEVAIARATEEDFCEEEEAKIRQRIFRPT 2880
            DEEYDEYKRIREERNGKYSIEEYLQDRDKYYEEVAIARATEEDFCEEEEAKIRQRIFRPT
Sbjct: 899  DEEYDEYKRIREERNGKYSIEEYLQDRDKYYEEVAIARATEEDFCEEEEAKIRQRIFRPT 958

Query: 2881 RKQRKEERASLGLVTGSEIRKRNPEDFKPKGKLWADDDRSVDYNEKLSFEAPPSIWSRIV 3060
            RKQRKEERASLGLVTGSEIRKRNP+DFKPKGKLWADDDRSVDYNE+L+FEAPPSIWSRIV
Sbjct: 959  RKQRKEERASLGLVTGSEIRKRNPDDFKPKGKLWADDDRSVDYNERLNFEAPPSIWSRIV 1018

Query: 3061 NFGSGWGFWVSPSLFITSTHVIPQGAKEFFGVPIKQIQVHKSGEFCRLRFPKPIRTDVTG 3240
            NFGSGWGFWVSPSLFITSTHVIPQGA+EFFGV IKQIQ+HKSGEFCRLRFPKPIRTDVTG
Sbjct: 1019 NFGSGWGFWVSPSLFITSTHVIPQGAQEFFGVSIKQIQIHKSGEFCRLRFPKPIRTDVTG 1078

Query: 3241 MILEEGAPEGTVVTLLIKRSTGELMPLAARMGTHATMKIQGRTVGGQMGMLLTGSNAKSM 3420
            MILEEGAPEGTVVTLLIKR TGELMPLAARMGTHATMKIQGRTVGGQMGMLLTGSNAKSM
Sbjct: 1079 MILEEGAPEGTVVTLLIKRPTGELMPLAARMGTHATMKIQGRTVGGQMGMLLTGSNAKSM 1138

Query: 3421 DLGTTPGDCGCPYIYKRGNDYVVIGVHTAAARGGNTVICATQGGEGEATLEGGDSKGTYC 3600
            DLGTTPGDCGCPYIYKRGNDYVVIGVHTAAARGGNTVICATQG EGEATLEGGD+KGTYC
Sbjct: 1139 DLGTTPGDCGCPYIYKRGNDYVVIGVHTAAARGGNTVICATQGSEGEATLEGGDNKGTYC 1198

Query: 3601 GAPILGPGSAPKLSTKTKFWRSSTAPLPPGTYEPAYLGGKDPRVKGGPSLQQVMRDQLKP 3780
            GAPILGPGSAPKLSTKTKFWRSSTAPLPPGTYEPAYLGGKDPRVKGGPSLQQVMRDQLKP
Sbjct: 1199 GAPILGPGSAPKLSTKTKFWRSSTAPLPPGTYEPAYLGGKDPRVKGGPSLQQVMRDQLKP 1258

Query: 3781 FTEPRGKPPKPSVLEAAKKTIINVLEQTIDPPEKWSFAQACASLDKTTSSGHPHHLRKND 3960
            FTEPRGKPPKPSVLEAAKKTIINVLEQTIDPP+KWSFAQACASLDKTTSSGHPHH+RKND
Sbjct: 1259 FTEPRGKPPKPSVLEAAKKTIINVLEQTIDPPQKWSFAQACASLDKTTSSGHPHHMRKND 1318

Query: 3961 CWNGESFTGKLADQASKANLMFEEGKNMTPVYTGALKDELVKTDKIYGKIKKRLLWGSDL 4140
            CWNGESFTGKLADQASKANLMFEEGKNMTPVYTGALKDELVKTDKIYG+IKKRLLWGSDL
Sbjct: 1319 CWNGESFTGKLADQASKANLMFEEGKNMTPVYTGALKDELVKTDKIYGRIKKRLLWGSDL 1378

Query: 4141 ATMIRCARAFGGLMDELKAHCVTLPIRVGMNMNEDGPIIFEKHSRYRYHYDADYSRWDST 4320
            ATMIRCARAFGGLM+ELKAHCVTLP+RVGMNMNEDGPIIFE+HSRY+YHYDADYSRWDST
Sbjct: 1379 ATMIRCARAFGGLMEELKAHCVTLPVRVGMNMNEDGPIIFERHSRYKYHYDADYSRWDST 1438

Query: 4321 QQRAVLAAALEIMVKFSSEPHLAQVVAEDLLSPSVVDVGDFTISINEGLPSGVPCTSQWN 4500
            QQRAVLAAALEIMVKFS EPHLAQ VAEDLLSPSV+DVGDF ISINEGLPSGVPCTSQWN
Sbjct: 1439 QQRAVLAAALEIMVKFSPEPHLAQKVAEDLLSPSVMDVGDFKISINEGLPSGVPCTSQWN 1498

Query: 4501 SIAHWLLTLCALSEVTNLSPDIIQANSLFSFYGDDEIVSTDIKLDPEKLTAKLKEYGLKP 4680
            SIAHWLLTLCALSEVTNLSPDIIQANSLFSFYGDDEIVSTDIKLDPEKLTAKLKEYGLKP
Sbjct: 1499 SIAHWLLTLCALSEVTNLSPDIIQANSLFSFYGDDEIVSTDIKLDPEKLTAKLKEYGLKP 1558

Query: 4681 TRPDKTEGPLVISEDLDGLTFLRRTVTRDPAGWFGKLEQSSILRQMYWTRGPNHEDPSES 4860
            TRPDKTEGPLVISEDL+GLTFLRRTVTRDPAGWFGKLEQSSILRQMYWTRGPNHEDPSE+
Sbjct: 1559 TRPDKTEGPLVISEDLNGLTFLRRTVTRDPAGWFGKLEQSSILRQMYWTRGPNHEDPSET 1618

Query: 4861 MIPHSQRPIQLMSLLGEAALHGPTFYSKISKLVIAELKEGGMDFYVPRQEPMFRWMRFSD 5040
            MIPHSQRPIQLMSLLGEAALHGP FYSKISKLVIAELKEGGMDFYVPRQEPMFRWMRFSD
Sbjct: 1619 MIPHSQRPIQLMSLLGEAALHGPAFYSKISKLVIAELKEGGMDFYVPRQEPMFRWMRFSD 1678

Query: 5041 LSTWEGDRNLAPSFVNEDGVE 5103
            LSTWEGDRNLAPSFVNEDGVE
Sbjct: 1679 LSTWEGDRNLAPSFVNEDGVE 1699


