========================================================================================================================

gene_id            %id    %sim   %cov   %t5   %gap  %t3   start..stop      pep sz ref sz ref id            definition
6.2                94.1   97.9   100.0  0.0   0.0   0.0   5083..6612       541    540    AAZ31396.2        VP1 | capsid protein VP1
                                                          6611..6706                                       
                    frameshift in genome at or near position 6612..6611 (+1=>+2)

CLUSTAL 2.1 multiple sequence alignment


predicted       MKMASNDANPSDGSAANLVPEVNNEVMALEPVVGAAIAAPVAGQQNVIDPWIRNNFVQAP
reference       MKMASNDATPSDGSTANLVPEVNNEVMALEPVVGAAIAAPVAGQQNVIDPWIRNNFVQAP
                ********.*****:*********************************************

predicted       GGEFTVSPRNAPGEILWSAPLGPDLNPYLSHLARMYNGYAGGFEVQVILAGNAFTAGKII
reference       GGEFTVSPRNAPGEILWSAPLGPDLNPYLSHLARMYNGYAGGFEVQVILAGNAFTAGKII
                ************************************************************

predicted       FAAVPPNFPTEGLSPSQVTMFPHIIVDVRQLEPVLIPLPDVRNNFYHYNQSNDSTIKLIA
reference       FAAVPPNFPTEVLSPSQVTMFPHIIVDVRQLEPVLIPLPDVRNNLYHYNQSNDPTIRLIA
                *********** ********************************:********.**:***

predicted       MLYTPLRANNGWGDVFTVSCRVLTRPSPDFDFIFLVPPTVESRTKPFTVPILTVEEMTNS
reference       MLYTPLRANNAGDDVFTVSCRVLTRPSPDFDFIFLVPPTVESRTKPFSVPILTVEEMTNS
                **********. .**********************************:************

predicted       RFPIPLEKLFTGPSGAFVVQPQNGRCTTDGVLLGTTQLSPVNICTFRGDVTHIAGSRNYT
reference       RFPIPLEKLFTGPSSAFVVQPQNGRCTTDGVLLGTTQLSPVNICTFRGDVTHIAGTQNYT
                **************.****************************************::***

predicted       MNLASLNWNNYDPTEEIPAPLGTPDFVGKIQGVLTQTTKGDGSTRGHKATVYTGSAPFTP
reference       MNLASQNWNNYDPTEEIPAPLGTPDFVGRIQGVLTQTTRRDGSTRGHKATVSTGSVHFTP
                ***** **********************:*********: *********** ***. ***

predicted       KLGSVQFSTDTENDFETHQNTKFTPVGVIQDGGTTHRNEPQQWVLPSYSGRDVHNVHLAP
reference       KLGSVQFSTDTSNDFETGQNTRFTPVGVVQDGSTTHQNEPQQWVLPDYSGRDSHNVHLAP
                ***********.***** ***:******:***.***:*********.***** *******

predicted       AVAPTFPGEQLLFFRSTMPGCSGYPNMDLDCLLPQEWVQHFYQEAAPAQSDVALLRFVNP
reference       AVAPTFPGEQLLFFRSTMPGCSGYPNMNLDCLLPQEWVQHFYQESAPAQSDVALLRFVNP
                ***************************:****************:***************

predicted       DTGRVLFECKLHKSGYVTVAHTGQHDLVIPPPNGYFRFDSWVNQFYTLAPMGNGTGRRRA
reference       DTGRVLFECKLHKSGYVTVAHTGQHDLVIPP-NGYFRFDSWVNQFYTLAPMGNGAGRRRA
                ******************************* **********************:*****

predicted       L
reference       L
                *

>6.2	5083	6706
acagtaaaatcagcaaattagtcattgcagagctaaaagaaggtggtatggatttttacg
tgcccaggcaagagccaatgttcagatggatgagattctcagatctgagcacgtgggagg
gcgatcgcaatctggctcccagttttgtgaATGAAGATGGCGTCGAATGACGCCAACCCA
TCTGATGGGTCCGCAGCCAACCTCGTCCCAGAGGTCAACAATGAGGTTATGGCTTTGGAG
CCCGTTGTCGGTGCCGCTATTGCGGCGCCTGTAGCGGGCCAACAAAATGTAATTGACCCC
TGGATTAGAAATAATTTTGTACAAGCCCCTGGTGGAGAGTTCACAGTATCCCCTAGAAAC
GCTCCAGGTGAAATACTATGGAGCGCGCCCTTAGGCCCTGATCTGAATCCCTACCTATCT
CATTTGGCCAGAATGTATAATGGTTATGCAGGTGGCTTTGAAGTGCAGGTGATCCTCGCG
GGGAACGCGTTCACCGCCGGAAAAATTATATTTGCAGCAGTCCCACCAAATTTTCCAACT
GAAGGCTTGAGTCCCAGCCAGGTCACTATGTTCCCCCACATAATAGTAGATGTTAGGCAA
TTGGAACCTGTGTTGATCCCCTTACCTGATGTTAGGAATAATTTTTATCACTATAATCAG
TCAAATGATTCTACCATTAAATTGATAGCAATGCTGTATACACCACTTAGGGCTAATAAT
GGCTGGGGAGACGTCTTCACAGTCTCTTGTCGAGTCCTCACTAGGCCGTCCCCTGATTTT
GATTTTATATTTTTGGTGCCACCCACAGTTGAGTCAAGAACTAAACCATTTACTGTCCCA
ATCTTAACCGTTGAAGAAATGACCAATTCAAGATTCCCCATTCCTTTGGAAAAGTTGTTC
ACGGGTCCCAGCGGTGCCTTTGTTGTCCAACCACAAAATGGCAGGTGCACGACTGATGGC
GTGCTCTTAGGCACCACCCAACTGTCTCCTGTCAACATCTGCACCTTCAGAGGGGATGTC
ACCCACATTGCAGGTTCTCGTAATTACACAATGAATTTGGCATCTCTAAATTGGAACAAT
TATGACCCAACAGAAGAAATTCCAGCCCCTCTAGGAACTCCAGATTTCGTGGGAAAGATC
CAAGGTGTGCTCACTCAAACCACAAAAGGAGATGGCTCGACCCGTGGCCATAAAGCTACA
GTTTACACTGGGAGTGCTCCCTTTACTCCAAAGCTGGGCAGTGTTCAATTCAGTACTGAC
ACAGAAAATGATTTTGAAACTCACCAAAACACAAAATTTACCCCAGTCGGTGTCATACAG
GACGGTGGCACCACCCACCGAAATGAACCCCAACAATGGGTGCTCCCAAGTTATTCAGGT
AGAGATGTTCATAATGTACACCTAGCCCCTGCTGTAGCCCCCACTTTTCCGGGTGAACAA
CTTCTTTTCTTCAGGTCCACTATGCCCGGATGCAGCGGGTATCCCAACATGGATTTGGAT
TGCCTACTCCCCCAGGAGTGGGTGCAGCACTTCTACCAAGAGGCAGCTCCAGCACAATCT
GATGTGGCTCTATTGAGATTTGTGAATCCAGACACGGGCAGGGTCCTGTTTGAGTGCAAA
CTTCATAAATCAGGCTATGTCACAGTGGCTCACACCGGTCAGCATGATTTGGTCATCCCC
CCCCAATGGCTATTTTAGGTTTGATTCGTGGGTTAATCAGTTTTACACACTTGCCCCCAT
GGGAAACGGAACGGGGCGTAGGCGCGCTTTATAAtggctggagctttctttgctggattg
gcatctgatgtccttggctctggacttggttccctaatcaatgctggggctggggctatc
aaccaaaagattgattttgaaaataatagaaaattgcagcaagcttctttccagtttagc
agta

Length = 540

Score =  1181 bits (2572), Expect(2) = 0.0
Identities = 482/515 (93%), Positives = 493/515 (95%)
Frame = +1

Query: 5083 MKMASNDANPSDGSAANLVPEVNNEVMALEPVVGAAIAAPVAGQQNVIDPWIRNNFVQAP 5262
            MKMASNDA PSDGS ANLVPEVNNEVMALEPVVGAAIAAPVAGQQNVIDPWIRNNFVQAP
Sbjct: 1    MKMASNDATPSDGSTANLVPEVNNEVMALEPVVGAAIAAPVAGQQNVIDPWIRNNFVQAP 60

Query: 5263 GGEFTVSPRNAPGEILWSAPLGPDLNPYLSHLARMYNGYAGGFEVQVILAGNAFTAGKII 5442
            GGEFTVSPRNAPGEILWSAPLGPDLNPYLSHLARMYNGYAGGFEVQVILAGNAFTAGKII
Sbjct: 61   GGEFTVSPRNAPGEILWSAPLGPDLNPYLSHLARMYNGYAGGFEVQVILAGNAFTAGKII 120

Query: 5443 FAAVPPNFPTEGLSPSQVTMFPHIIVDVRQLEPVLIPLPDVRNNFYHYNQSNDSTIKLIA 5622
            FAAVPPNFPTE LSPSQVTMFPHIIVDVRQLEPVLIPLPDVRNN YHYNQSND TI+LIA
Sbjct: 121  FAAVPPNFPTEVLSPSQVTMFPHIIVDVRQLEPVLIPLPDVRNNLYHYNQSNDPTIRLIA 180

Query: 5623 MLYTPLRANNGWGDVFTVSCRVLTRPSPDFDFIFLVPPTVESRTKPFTVPILTVEEMTNS 5802
            MLYTPLRANN   DVFTVSCRVLTRPSPDFDFIFLVPPTVESRTKPF+VPILTVEEMTNS
Sbjct: 181  MLYTPLRANNAGDDVFTVSCRVLTRPSPDFDFIFLVPPTVESRTKPFSVPILTVEEMTNS 240

Query: 5803 RFPIPLEKLFTGPSGAFVVQPQNGRCTTDGVLLGTTQLSPVNICTFRGDVTHIAGSRNYT 5982
            RFPIPLEKLFTGPS AFVVQPQNGRCTTDGVLLGTTQLSPVNICTFRGDVTHIAG++NYT
Sbjct: 241  RFPIPLEKLFTGPSSAFVVQPQNGRCTTDGVLLGTTQLSPVNICTFRGDVTHIAGTQNYT 300

Query: 5983 MNLASLNWNNYDPTEEIPAPLGTPDFVGKIQGVLTQTTKGDGSTRGHKATVYTGSAPFTP 6162
            MNLAS NWNNYDPTEEIPAPLGTPDFVG+IQGVLTQTT+ DGSTRGHKATV TGS  FTP
Sbjct: 301  MNLASQNWNNYDPTEEIPAPLGTPDFVGRIQGVLTQTTRRDGSTRGHKATVSTGSVHFTP 360

Query: 6163 KLGSVQFSTDTENDFETHQNTKFTPVGVIQDGGTTHRNEPQQWVLPSYSGRDVHNVHLAP 6342
            KLGSVQFSTDT NDFET QNT+FTPVGV+QDG TTH+NEPQQWVLP YSGRD HNVHLAP
Sbjct: 361  KLGSVQFSTDTSNDFETGQNTRFTPVGVVQDGSTTHQNEPQQWVLPDYSGRDSHNVHLAP 420

Query: 6343 AVAPTFPGEQLLFFRSTMPGCSGYPNMDLDCLLPQEWVQHFYQEAAPAQSDVALLRFVNP 6522
            AVAPTFPGEQLLFFRSTMPGCSGYPNM+LDCLLPQEWVQHFYQE+APAQSDVALLRFVNP
Sbjct: 421  AVAPTFPGEQLLFFRSTMPGCSGYPNMNLDCLLPQEWVQHFYQESAPAQSDVALLRFVNP 480

Query: 6523 DTGRVLFECKLHKSGYVTVAHTGQHDLVIPPQWLF 6627
            DTGRVLFECKLHKSGYVTVAHTGQHDLVIPP   F
Sbjct: 481  DTGRVLFECKLHKSGYVTVAHTGQHDLVIPPNGYF 515

------------------------------------------------------------
frameshifted from +1 to +2 between 6388-6850
  6388 TCCACTATGCCCGGATGCAGCGGGTATCCCAACATGGATTTGGATTGCCTACTCCCCCAG 6447  
  6448 GAGTGGGTGCAGCACTTCTACCAAGAGGCAGCTCCAGCACAATCTGATGTGGCTCTATTG 6507  
  6508 AGATTTGTGAATCCAGACACGGGCAGGGTCCTGTTTGAGTGCAAACTTCATAAATCAGGC 6567  
  6568 TATGTCACAGTGGCTCACACCGGTCAGCATGATTTGGTCATCCCCCCCCAATGGCTATTT 6627  
  6628 TAGGTTTGATTCGTGGGTTAATCAGTTTTACACACTTGCCCCCATGGGAAACGGAACGGG 6687  
  6688 GCGTAGGCGCGCTTTATAATGGCTGGAGCTTTCTTTGCTGGATTGGCATCTGATGTCCTT 6747  
  6748 GGCTCTGGACTTGGTTCCCTAATCAATGCTGGGGCTGGGGCTATCAACCAAAAGATTGAT 6807  
  6808 TTTGAAAATAATAGAAAATTGCAGCAAGCTTCTTTCCAGTTTA                  6850  
 frame +1
  6388  s -T--M--P--G--C--S--G--Y--P--N--M- d -L--D--C--L--L--P--Q- 6447   |
  6448 -E--W--V--Q--H--F--Y--Q--E- a -A--P--A--Q--S--D--V--A--L--L- 6507   |
  6508 -R--F--V--N--P--D--T--G--R--V--L--F--E--C--K--L--H--K--S--G- 6567   |
  6568 -Y--V--T--V--A--H--T--G--Q--H--D--L--V--I--P--P- q  w  l -F- 6627   |
  6628  *  v  *  f  v  g  *  s  v  l  h  t  c -P- h -G- k  r  n -G- 6687  
  6688  a  *  a  r  f  i  m  a  g  a  f  f  a  g  l  a  s  d  v  l  6747  
  6748  g  s  g  l  g  s  l  i  n  a  g  a  g  a  i  n  q  k  i  d  6807  
  6808  f  e  n  n  r  k  l  q  q  a  s  f  q  f                    6850  
 frame +2
  6388   p  l  c -P- d  a  a -G- i -P- t  w  i  w  i  a  y  s -P- r 6447  
  6448   s  g  c  s  t  s  t  k  r  q  l  q  h  n  l  m  w  l  y  * 6507  
  6508   d  l  *  i  q  t  r  a  g  s  c  l  s  a  n  f  i  n  q  a 6567  
  6568   m  s  q  w  l  t  p  v  s  m  i  w  s  s -P--P--N--G--Y--F 6627   |
  6628 --R--F--D--S--W--V--N--Q--F--Y--T--L--A--P--M--G--N--G- t -G 6687   |
  6688 --R--R--R--A--L- *  w  l  e  l  s  l  l  d  w  h  l  m  s  l 6747   |
  6748   a  l  d  l  v  p  *  s  m  l  g  l  g  l  s  t  k  r  l  i 6807  
  6808   l  k  i  i  e  n  c  s  k  l  l  s  s  l                   6850  
 frame +3
  6388    h  y  a  r  m  q  r  v  s  q  h  g  f -G- l  p  t  p -P-  6447  
  6448 g  v  g  a  a  l -L- p  r  g  s  s  s  t  i  *  c  g  s  i   6507  
  6508 e  i  c  e -S- r  h  g  q  g  p  v  *  v  q  t  s  *  i  r - 6567  
  6568 L- c  h  s  g  s -H- r -S- a  *  f  g  h  p  p  p  m  a  i   6627  
  6628 l  g  l -I- r  g  l  i  s -F- t  h  l  p  p  w  e  t  e  r   6687  
  6688 g  v  g  a  l  y -N--G- w  s  f  l  c  w  i  g  i  *  c  p   6747  
  6748 w  l  w  t  w  f  p  n  q  c  w  g  w  g  y  q  p  k  d  *   6807  
  6808 f  *  k  *  *  k  i  a  a  s  f  f  p  v                     6850  

reference sequence 436-540
TMPGCSGYPNMNLDCLLPQEWVQHFYQESAPAQSDVALLRFVNPDTGRVLFECKLHKSGY
VTVAHTGQHDLVIPPNGYFRFDSWVNQFYTLAPMGNGAGRRRAL
------------------------------------------------------------

Score =  81.3 bits (171), Expect(2) = 0.0
Identities = 30/31 (96%), Positives = 30/31 (96%)
Frame = +2

Query: 6611 PPNGYFRFDSWVNQFYTLAPMGNGTGRRRAL 6703
            PPNGYFRFDSWVNQFYTLAPMGNG GRRRAL
Sbjct: 510  PPNGYFRFDSWVNQFYTLAPMGNGAGRRRAL 540


========================================================================================================================

gene_id            %id    %sim   %cov   %t5   %gap  %t3   start..stop      pep sz ref sz ref id            definition
7.1                94.7   98.9   100.0  0.0   0.0   0.0   3..542           1701   1699   ACT76138.1        POL | nonstructural polyprotein
                                                          541..5106                                        
                    frameshift in genome at or near position 542..541 (+3=>+1)
7.1.1              93.1   97.5   100.0  0.0   0.0   0.0   3..542           332    330    NOROV_MP1         protein p48
                                                          541..996                                         
7.1.2              96.7   99.2   100.0  0.0   0.0   0.0   997..2094        366    366    NOROV_MP2         NTPase
7.1.3              93.3   99.3   100.0  0.0   0.0   0.0   2095..2631       179    179    NOROV_MP3         protein p22
7.1.4              97.7   100.0  100.0  0.0   0.0   0.0   2632..3030       133    133    NOROV_MP4         viral genome-linked protein
7.1.5              100.0  100.0  100.0  0.0   0.0   0.0   3031..3573       181    181    tr|G1FEL2         3C-like protease
7.1.6              99.8   100.0  100.0  0.0   0.0   0.0   3574..5103       510    510    ABV55633.1        RNA-directed RNA polymerase

CLUSTAL 2.1 multiple sequence alignment


predicted       MKMASNDASAAAVANSNNDTAKSSSDKMFSSMAVTFKRALGARPKQPPPRETPQRPPRPP
reference       MKMASNDASAAAVANSNNDTAKSSSDGVLSSMAVTFKRALGARPKQPPPREIPQRPPRPP
                ************************** ::********************** ********

predicted       TPELVKKIPPPPPNGEDEVVVSYSAKDGVSGLPELSTVRQPEETNTAFSVPPLNQRENRD
reference       TPELIKKVPPPPPNGEDEPVVSYNAKNGVSGLPELSTVRQPDENNTAFSVPPLNQRENRD
                ****:**:********** ****.**:**************:*.****************

predicted       AKEPLTGTILEMWDGEIYHYGLYVERGLVLGGGTQPPAAISLAKVELTPLSLFWRPVYTP
reference       AKEPLTGTILEMWDGEIYHYGLYVERGLVLG-VHKPPAAISLAKVELTPLSLFWRPVYTP
                *******************************   :*************************

predicted       PQYLISPDTLKKLHGETFPYTAFDNNCYAFCCWVLDLNDSWLSRRMIQRTTGFFRPYQDW
reference       -QYLISPDTLRRLHGESFPYTAFDNNCYAFCCWVLDLNDSWLSRRMIQRTTGFFRPYQDW
                 *********::****:*******************************************

predicted       NRKPLPTIDDSKLKKVANIFLCALSSLFTRPIKDIIGKLRPLNIINILASCDWTFAGIVE
reference       NRKPLPTMDDSKLKKVANIFLCALSSLFTRPIKDIIGKLKPLNILNILASCDWTFAGIVE
                *******:*******************************:****:***************

predicted       SLILLAELFGVFWTPPDVSAMIAPLLGDFELQGPEDLVVELVPVVMGGIGLVLGFTKEKI
reference       SLILLAELFGVFWTPPDVSAMIAPLLGDYELQGPEDLAVELVPVVMGGIGLVLGFTKEKI
                ****************************:********.**********************

predicted       GKMLSSAASTLRACKDLGAYGLEIXKLVMKWFFPKKEEANELXMVRSIEDAVLDLEAIEN
reference       GKMLSSAASTLRACKDLGAYGLEILKLVMKWFFPKKEEASELAMVRSIEDAVLDLEAIEN
                ************************ **************.** *****************

predicted       NHMTTLLKDKDSLATYMRTLDLEEEKARKLSTKSASPDIVGTINALLARIAAARSLVHRA
reference       NHLTTLLKDKDSLATYMRTLDLEEEKARKLSTKSASPDIVGTINALLARIAAARSLVHRA
                **:*********************************************************

predicted       KEELSSRPRPVVLMISGRPGIGKTHLAREVAKRIAASLTGDQRVGLIPRNGVDHWDAYKG
reference       KEELSSRPRPVVVMISGKPGIGKTHLARELAKKIATTLTGDQRVGLIPRNGVDHWDAYKG
                ************:****:***********:**:**::***********************

predicted       ERVVLWDDYGMSNPIHDALRLQELADTCPLTLNCDRIENKGKVFDSDVIIITTNLANPAP
reference       ERVVLWDDYGMSNPIHDALRLQELADTCPLTLNCDRIENKGKVFDSDAIIITTNLANPAP
                ***********************************************.************

predicted       LDYVNFEACSRRIDFLVYAEAPEVEKAKRDFPGQPDMWKNAFSSDFSHIKLALAPQGGFD
reference       LDYVNFEACSRRIDFLVYAEAPDVEKAKRDFPGQPDMWKNAFSPDFSHIKLMLAPQGGFD
                **********************:********************.******* ********

predicted       KNGNTPHGKGVMKTLTTGSLIARASGLLHERLDEFELQGPALTTFNFDRNKVLAFRQLAA
reference       KNGNTPHGKGVMKTLTIGSLIARASGLLHERLDEYELQGPALTTFNFDRNKVLAFRQLAA
                **************** *****************:*************************

predicted       ENKYGLMDTMKVGRQLKDVKTMPELKQALKNISIKKCQIVYSGCTYTLESDGKGNVKVDR
reference       ENKYGLMDTMRVGGQLKGVRTMPELKQALKNISIKRCQIVYGGSTYTLESDGKGSVRVDR
                **********:** ***.*:***************:*****.*.**********.*:***

predicted       VQSTSVQTNNELAGALHHLRCARIRYYVKCVQEALYSIIQIAGAAFVTTRIIKRVNIQDL
reference       VQSATVQTNNELAGALHHLRCARIRYYVKCVQEALYSIIQIAGAAFVTTRIVKRMNIQDL
                ***::**********************************************:**:*****

predicted       WSKPQVENTEEATNKDGCPKPKDDEEFVISSDDIKTEGKKGKNKAGRGKKHTAFSSKGLS
reference       WSKPQLEDTEEATGKDGCPKPKDDEEFVVSSDDIKVEGKKGKNKTGRGKKHTAFSSKGLS
                *****:*:*****.**************:******.********:***************

predicted       DEEYDEYKRIREERNGKYSIEEYLQDRDKYYEEVAIARATEEDFCEEEEAKIRQRIFRPT
reference       DEEYDEYKRIREERNGKYSIEEYLQDRDKYYEEVAIARATEEDFCEEEEAKIRQRIFRPT
                ************************************************************

predicted       RKQRKEERASLGLVTGSEIRKRNPEDFKPKGKLWADDDRSVDYNEKLSFEAPPSIWSRIV
reference       RKQRKEERASLGLVTGSEIRKRNPDDFKPKGKLWADDDRSVDYNEKLSFEAPPSIWSRIV
                ************************:***********************************

predicted       NFGSGWGFWVSPSLFITSTHVIPQGAKEFFGVPIKQIQVHKSGEFCRLRFPKPIRTDVTG
reference       NFGSGWGFWVSPSLFITSTHVIPQGTQEFFGVSIKQIQIHKSGEFCRLRFPKPIRTDVTG
                *************************::*****.*****:*********************

predicted       MILEEGAPEGTVVTLLIKRSTGELMPLAARMGTHATMKIQGRTVGGQMGMLLTGSNAKSM
reference       MILEEGAPEGTVATLLIKRPTGELMPLAARMGTHATMKIQGRTVGGQMGMLLTGSNAKSM
                ************.******.****************************************

predicted       DLGTTPGDCGCPYIYKRGNDYVVIGVHTAAARGGNTVICATQGGEGEATLEGGDSKGTYC
reference       DLGTTPGDCGCPYIYKRGNDYVVIGVHTAAARGGNTVICATQGSEGEATLEGGDNKGTYC
                *******************************************.**********.*****

predicted       GAPILGPGSAPKLSTKTKFWRSSTAPLPPGTYEPAYLGGKDPRVKGGPSLQQVMRDQLKP
reference       GAPILGPGSAPKLSTKTKFWRSSTAPLPPGTYEPAYLGGKDPRIKGGPSLQQVMRDQLKP
                *******************************************:****************

predicted       FTEPRGKPPKPSVLEAAKKTIINVLEQTIDPPEKWSFAQACASLDKTTSSGHPHHLRKND
reference       FTEPRGKQPKPSVLEAAKRTIINVLEQTIDPPQKWTFAQACASLDKTTSSGHPHHIRKNE
                ******* **********:*************:**:*******************:***:

predicted       CWNGESFTGKLADQASKANLMFEEGKNMTPVYTGALKDELVKTDKIYGKIKKRLLWGSDL
reference       CWNGDSFTGKLADQASKANLMFEEGKNMTPVYTGALKDELVKTDKIYGKIKKRLLWGSDL
                ****:*******************************************************

predicted       ATMIRCARAFGGLMDELKAHCVTLPIRVGMNMNEDGPIIFEKHSRYRYHYDADYSRWDST
reference       ATMIRCARAFGGLMDELKAHCVTLPVRVGMNMNEDGPIIFEKHSRYRYHYDADYSRWDST
                *************************:**********************************

predicted       QQRAVLAAALEIMVKFSSEPHLAQVVAEDLLSPSVVDVGDFTISINEGLPSGVPCTSQWN
reference       QQRAILAAALEIMVKFSPEPHLAQIVAEDLLSPSVMDVGDFKISINEGLPSGVPCTSQWN
                ****:************.******:**********:*****.******************

predicted       SIAHWLLTLCALSEVTNLSPDIIQANSLFSFYGDDEIVSTDIKLDPEKLTAKLKEYGLKP
reference       SIAHWLLTLCALSEVTDLSPDIVQANSLFSFYGDDEIVSTDIKLDPEKLTAKLKEYGLKP
                ****************:*****:*************************************

predicted       TRPDKTEGPLVISEDLDGLTFLRRTVTRDPAGWFGKLEQSSILRQMYWTRGPNHEDPSES
reference       TRPDKTEGPLIISEDLNGLTFLRRTVTRDPAGWFGKLEQSSILRQMYWTRGPNHEDPSET
                **********:*****:******************************************:

predicted       MIPHSQRPIQLMSLLGEAALHGPTFYSKISKLVIAELKEGGMDFYVPRQEPMFRWMRFSD
reference       MIPHSQRPTQLMSLLGEAALHGPAFYSKISKLVITELKEGGMDFYVPRQEPMFRWMRFSD
                ******** **************:**********:*************************

predicted       LSTWEGDRNLAPSFVNEDGVE
reference       LSTWEGDRNLAPSFVNEDGVE
                *********************

>7.1	3	5106
gaATGAAGATGGCGTCTAACGACGCTTCCGCTGCCGCTGTTGCTAACAGCAACAACGACA
CCGCAAAATCTTCAAGTGACAAAATGTTTTCTAGCATGGCTGTCACTTTTAAACGAGCCC
TCGGGGCGCGGCCTAAACAGCCCCCCCCGAGGGAAACACCACAAAGACCCCCACGACCAC
CTACTCCAGAACTGGTCAAAAAGATCCCTCCTCCCCCGCCCAACGGAGAGGATGAAGTAG
TGGTTTCTTATAGTGCCAAAGATGGCGTTTCCGGTTTACCTGAGCTTTCCACCGTCAGGC
AACCGGAAGAAACCAATACGGCCTTCAGTGTCCCTCCACTCAACCAGAGGGAGAATAGAG
ATGCTAAGGAACCACTGACTGGAACAATTCTGGAAATGTGGGATGGAGAAATCTACCATT
ATGGCCTGTATGTTGAGCGAGGTCTTGTGCTGGGTGGTGGCACACAACCACCAGCTGCCA
TAAGCCTCGCCAAGGTCGAACTAACACCACTCTCCTTGTTCTGGAGACCTGTGTACACTC
CCCCAGTACCTCATCTCTCCAGACACTCTCAAGAAATTACACGGAGAAACGTTTCCCTAC
ACAGCCTTTGACAACAATTGCTATGCCTTTTGTTGTTGGGTCCTGGATCTAAATGACTCG
TGGCTGAGTAGGAGAATGATCCAGAGAACAACTGGCTTCTTCAGACCCTACCAAGACTGG
AATAGGAAACCCCTCCCCACTATAGATGACTCCAAATTAAAGAAGGTAGCTAACATTTTC
CTGTGCGCCCTGTCTTCGCTATTCACCAGGCCCATAAAAGACATAATAGGAAAGCTAAGA
CCTCTCAACATCATCAACATCCTGGCTTCATGTGATTGGACTTTCGCAGGCATAGTGGAG
TCCTTGATACTCTTGGCAGAGCTCTTTGGAGTCTTCTGGACACCCCCAGATGTGTCTGCG
ATGATTGCCCCCTTACTCGGTGATTTCGAGTTACAAGGACCTGAGGACCTTGTAGTGGAG
CTCGTCCCTGTAGTAATGGGGGGAATTGGTTTGGTGCTGGGATTCACCAAAGAGAAGATT
GGAAAAATGTTGTCATCTGCTGCATCCACCTTGAGAGCTTGTAAAGATCTTGGTGCATAT
GGGCTAGAGATCYTAAAGTTAGTCATGAAGTGGTTCTTCCCGAAGAAAGAGGAGGCAAAT
GAACTGGMTATGGTGAGATCCATCGAGGATGCAGTACTGGACCTTGAGGCAATTGAAAAC
AACCATATGACCACCTTGCTCAAAGACAAAGACAGCCTGGCAACCTACATGAGAACCCTT
GACCTCGAGGAAGAGAAAGCCAGAAAACTCTCAACCAAGTCTGCTTCACCTGACATCGTG
GGCACAATCAACGCCCTTCTGGCGAGAATCGCCGCTGCACGCTCCCTGGTGCACCGAGCG
AAGGAGGAGCTTTCCAGCAGACCAAGACCTGTAGTCTTGATGATATCAGGCAGACCAGGG
ATAGGGAAGACCCACCTTGCTAGGGAAGTGGCTAAGAGAATCGCAGCCTCCCTCACAGGA
GACCAGCGTGTAGGCCTCATCCCACGCAATGGCGTCGATCACTGGGATGCGTACAAGGGG
GAGAGGGTCGTCCTATGGGACGACTATGGAATGAGCAATCCCATCCACGACGCCCTCAGG
CTGCAAGAACTCGCTGACACTTGCCCCCTCACTCTAAATTGTGACAGGATTGAGAATAAA
GGAAAGGTCTTTGACAGCGATGTCATCATTATCACTACTAATCTGGCCAACCCAGCACCA
CTGGACTATGTCAACTTTGAAGCGTGCTCGAGGCGCATCGATTTCCTCGTGTATGCAGAA
GCCCCCGAGGTCGAAAAGGCGAAGCGTGACTTCCCGGGCCAACCTGATATGTGGAAAAAC
GCTTTTAGTTCTGATTTCTCACACATAAAATTGGCACTGGCTCCACAAGGTGGCTTTGAT
AAGAACGGGAACACCCCACACGGGAAGGGCGTCATGAAGACTCTCACCACTGGCTCCCTC
ATTGCCCGGGCATCAGGGCTGCTCCATGAGAGATTGGATGAGTTTGAACTACAGGGCCCA
GCTCTTACCACCTTCAACTTTGACCGCAACAAAGTGCTTGCCTTCAGGCAGCTTGCTGCT
GAAAACAAATATGGGTTGATGGACACAATGAAAGTTGGGAGGCAGCTCAAGGATGTCAAA
ACCATGCCAGAACTTAAACAAGCACTCAAGAATATCTCAATCAAGAAGTGCCAGATTGTG
TATAGTGGTTGCACCTACACACTTGAGTCTGATGGCAAGGGCAATGTGAAAGTTGACAGA
GTTCAGAGCACCTCCGTACAGACCAACAATGAGCTGGCTGGCGCCCTGCACCATCTAAGG
TGCGCCAGAATCAGGTACTATGTCAAGTGTGTCCAGGAGGCCCTGTATTCTATCATCCAG
ATTGCTGGGGCTGCATTTGTCACCACGCGCATCATCAAGCGTGTGAACATTCAAGACTTA
TGGTCCAAGCCACAAGTGGAAAACACAGAGGAGGCTACCAACAAGGACGGGTGCCCAAAA
CCCAAAGATGATGAGGAGTTCGTCATTTCATCTGACGACATTAAAACTGAGGGTAAGAAA
GGGAAGAACAAGGCTGGCCGTGGCAAGAAGCACACAGCCTTCTCAAGTAAAGGTCTCAGT
GATGAAGAGTATGATGAGTACAAGAGAATTAGAGAGGAAAGGAATGGCAAGTACTCCATA
GAGGAGTACCTTCAGGACAGGGACAAATACTATGAGGAGGTGGCCATTGCCAGGGCGACC
GAGGAAGACTTCTGTGAAGAGGAGGAGGCCAAGATCCGGCAAAGGATCTTCAGACCAACA
AGGAAACAACGCAAGGAAGAAAGAGCTTCTCTCGGTTTAGTCACAGGTTCTGAAATTAGG
AAAAGAAACCCAGAAGACTTCAAGCCCAAGGGGAAACTATGGGCTGACGATGACAGAAGT
GTGGACTACAATGAGAAACTCAGTTTTGAGGCCCCACCAAGCATCTGGTCAAGGATAGTC
AACTTTGGCTCAGGTTGGGGTTTTTGGGTCTCCCCCAGCCTGTTCATAACATCAACCCAC
GTCATACCCCAAGGTGCAAAGGAGTTCTTTGGAGTCCCCATCAAACAAATTCAGGTACAC
AAGTCAGGCGAGTTCTGTCGCTTGAGGTTCCCAAAACCAATCAGGACTGATGTGACTGGC
ATGATCTTGGAAGAAGGTGCGCCCGAAGGCACCGTGGTCACACTACTCATCAAAAGGTCT
ACTGGAGAACTCATGCCCCTAGCAGCTAGAATGGGGACCCATGCAACCATGAAAATTCAA
GGGCGCACTGTTGGAGGTCAGATGGGTATGCTTCTGACAGGATCCAACGCCAAAAGCATG
GATCTAGGCACCACACCAGGTGATTGCGGCTGTCCCTACATCTACAAGAGAGGAAATGAC
TATGTGGTCATTGGAGTCCACACGGCTGCCGCTCGTGGGGGAAACACTGTCATATGTGCC
ACCCAGGGGGGTGAGGGGGAAGCTACACTTGAAGGTGGTGACAGTAAGGGAACATACTGT
GGTGCACCAATCCTAGGCCCAGGGAGTGCCCCAAAACTTAGCACCAAAACCAAATTCTGG
AGATCATCCACAGCACCACTCCCACCTGGCACCTATGAACCAGCCTACCTTGGTGGCAAG
GACCCCAGAGTCAAGGGTGGCCCCTCGTTGCAGCAAGTCATGAGGGACCAGCTGAAACCA
TTTACAGAGCCCAGGGGTAAGCCACCAAAGCCAAGTGTGTTAGAAGCTGCCAAGAAAACC
ATCATCAATGTCCTTGAACAAACAATTGACCCACCTGAGAAGTGGTCGTTCGCACAAGCT
TGCGCGTCCCTTGACAAGACCACTTCTAGCGGCCATCCGCACCACTTGCGGAAAAACGAC
TGCTGGAACGGGGAATCCTTCACAGGCAAGCTGGCAGACCAGGCTTCCAAGGCCAACCTG
ATGTTTGAAGAAGGGAAAAACATGACCCCAGTCTACACAGGTGCACTTAAGGATGAATTA
GTCAAAACTGACAAAATTTATGGTAAGATCAAGAAGAGGCTTCTCTGGGGCTCGGATTTA
GCAACCATGATCCGGTGTGCTCGAGCATTCGGAGGCCTAATGGATGAACTCAAAGCACAC
TGTGTCACACTTCCTATCAGAGTTGGTATGAATATGAATGAGGATGGCCCCATCATCTTC
GAGAAGCATTCCAGGTACAGATACCACTATGATGCTGATTACTCTCGGTGGGATTCAACA
CAACAGAGAGCCGTGCTGGCAGCTGCTCTAGAAATCATGGTTAAATTCTCCTCAGAACCA
CATTTGGCTCAGGTAGTCGCAGAAGACCTTCTTTCTCCTAGCGTGGTGGATGTGGGTGAC
TTCACAATATCAATCAACGAGGGTCTTCCCTCTGGGGTGCCCTGCACCTCCCAATGGAAC
TCCATCGCCCACTGGCTTCTCACTCTCTGTGCACTCTCCGAAGTTACAAATTTGTCTCCA
GACATCATACAGGCTAATTCTCTCTTCTCCTTCTATGGTGATGATGAAATTGTTAGTACA
GACATAAAATTAGACCCAGAGAAGTTGACAGCAAAGCTTAAGGAATATGGGTTGAAACCA
ACCCGCCCTGATAAAACTGAAGGACCTCTTGTTATTTCTGAAGACTTAGATGGTTTGACT
TTCCTGCGGAGAACTGTGACCCGCGACCCAGCTGGTTGGTTTGGAAAACTGGAGCAGAGC
TCAATACTCAGGCAAATGTACTGGACTAGGGGCCCCAACCATGAAGATCCATCTGAATCA
ATGATTCCACACTCTCAGAGACCCATACAATTGATGTCCTTACTGGGAGAGGCCGCACTC
CACGGCCCAACATTCTACAGTAAAATCAGCAAATTAGTCATTGCAGAGCTAAAAGAAGGT
GGTATGGATTTTTACGTGCCCAGGCAAGAGCCAATGTTCAGATGGATGAGATTCTCAGAT
CTGAGCACGTGGGAGGGCGATCGCAATCTGGCTCCCAGTTTTGTGAATGAAGATGGCGTC
GAATGAcgccaacccatctgatgggtccgcagccaacctcgtcccagaggtcaacaatga
ggttatggctttggagcccgttgtcggtgccgctattgcggcgcctgtagcgggccaaca
aaatgtaattgacccctggattagaaataattttgtacaagcccctggtggagagttcac
agtatcccctagaaacgctccaggtgaaatactatggagcgcgcccttaggccctgatct
gaatccctacctatctcatttggccagaatgtataatggttatgcaggtggctttgaagt
gcag

Length = 1699

Score =   344 bits (745), Expect(3) = 0.0
Identities = 142/158 (89%), Positives = 148/158 (93%)
Frame = +3

Query: 3    MKMASNDASAAAVANSNNDTAKSSSDKMFSSMAVTFKRALGARPKQPPPRETPQRPPRPP 182
            MKMASNDASAAAVANSNNDTAKSSSD + SSMAVTFKRALGARPKQPPPRE PQRPPRPP
Sbjct: 1    MKMASNDASAAAVANSNNDTAKSSSDGVLSSMAVTFKRALGARPKQPPPREIPQRPPRPP 60

Query: 183  TPELVKKIPPPPPNGEDEVVVSYSAKDGVSGLPELSTVRQPEETNTAFSVPPLNQRENRD 362
            TPEL+KK+PPPPPNGEDE VVSY+AK+GVSGLPELSTVRQP+E NTAFSVPPLNQRENRD
Sbjct: 61   TPELIKKVPPPPPNGEDEPVVSYNAKNGVSGLPELSTVRQPDENNTAFSVPPLNQRENRD 120

Query: 363  AKEPLTGTILEMWDGEIYHYGLYVERGLVLGGGTQPPA 476
            AKEPLTGTILEMWDGEIYHYGLYVERGLVLG    P A
Sbjct: 121  AKEPLTGTILEMWDGEIYHYGLYVERGLVLGVHKPPAA 158

Score =  64.3 bits (134), Expect(3) = 0.0
Identities = 26/29 (89%), Positives = 27/29 (93%)
Frame = +3

Query: 456  GGTQPPAAISLAKVELTPLSLFWRPVYTP 542
            G  +PPAAISLAKVELTPLSLFWRPVYTP
Sbjct: 151  GVHKPPAAISLAKVELTPLSLFWRPVYTP 179

------------------------------------------------------------
frameshifted from +3 to +1 between 303-780
   303 CCGGAAGAAACCAATACGGCCTTCAGTGTCCCTCCACTCAACCAGAGGGAGAATAGAGAT 362   
   363 GCTAAGGAACCACTGACTGGAACAATTCTGGAAATGTGGGATGGAGAAATCTACCATTAT 422   
   423 GGCCTGTATGTTGAGCGAGGTCTTGTGCTGGGTGGTGGCACACAACCACCAGCTGCCATA 482   
   483 AGCCTCGCCAAGGTCGAACTAACACCACTCTCCTTGTTCTGGAGACCTGTGTACACTCCC 542   
   543 CCAGTACCTCATCTCTCCAGACACTCTCAAGAAATTACACGGAGAAACGTTTCCCTACAC 602   
   603 AGCCTTTGACAACAATTGCTATGCCTTTTGTTGTTGGGTCCTGGATCTAAATGACTCGTG 662   
   663 GCTGAGTAGGAGAATGATCCAGAGAACAACTGGCTTCTTCAGACCCTACCAAGACTGGAA 722   
   723 TAGGAAACCCCTCCCCACTATAGATGACTCCAAATTAAAGAAGGTAGCTAACATTTTC   780   
 frame +3
   303 -P- e -E- t -N--T--A--F--S--V--P--P--L--N--Q--R--E--N--R--D- 362    |
   363 -A--K--E--P--L--T--G--T--I--L--E--M--W--D--G--E--I--Y--H--Y- 422    |
   423 -G--L--Y--V--E--R--G--L--V--L--G- g  g  t  q -P- p -A- a  i  482    |
   483  s  l  a  k  v  e  l  t  p  l  s  l  f  w  r  p  v  y  t  p  542   
   543  p  v  p  h  l  s  r  h  s  q  e  i  t  r  r  n  v  s  l  h  602   
   603  s  l  *  q  q  l  l  c  l  l  l  l  g  p  g  s  k  *  l  v  662   
   663  a  e  *  e  n  d  p  e  n  n  w  l  l  q  t  l  p  r  l  e  722   
   723  *  e  t -P- p  h  y  r  *  l  q  i -K- e  g  s  *  h  f     780   
 frame +1
   303   r  k  k  p  i  r  p  s  v -S- l  h  s  t  r  g -R- i  e  m 362   
   363   l  r  n  h  * -L- e  q  f  w  k  c  g  m  e  k  s  t  i  m 422   
   423   a  c  m  l  s -E- v  l  c  w  v  v  a -H- n  h  q  l  p  * 482   
   483   a  s  p  r  s  n  *  h  h  s  p  c  s  g  d  l  c  t  l -P 542   
   543 --Q--Y--L--I--S--P--D--T--L- k  k -L--H--G--E- t -F--P--Y--T 602    |
   603 --A--F--D--N--N--C--Y--A--F--C--C--W--V--L--D--L--N--D--S--W 662    |
   663 --L--S--R--R--M--I--Q--R--T--T--G--F--F--R--P--Y--Q--D--W--N 722    |
   723 --R--K--P--L--P--T- i -D--D--S--K--L--K--K--V--A--N--I--F-   780    |
 frame +2
   303    g  r  n  q  y  g  l  q  c  p  s  t  q  p  e  g  e  *  r   362   
   363 c  * -G- t  t  d  w  n  n  s  g  n  v  g  w  r  n -L- p  l   422   
   423 w  p  v  c  * -A- r -S- c -A- g  w  w  h -T- t  t -S- c  h   482   
   483 k  p  r  q  g  r  t  n  t  t  l  l  v  l  e  t  c  v  h  s   542   
   543 p  s  t  s  s  l  q  t  l  s  r -N- y  t  e  k  r  f  p  t   602   
   603 q  p -L- t  t  i  a  m  p  f  v  v  g  s  w  i  *  m  t  r   662   
   663 g  *  v  g  e  *  s -R- e  q -L- a  s  s -D- p  t -K- t  g   722   
   723 i  g  n  p  s  p -L- *  m  t  p  n  *  r  r  *  l  t  f      780   

reference sequence 100-258
PDENNTAFSVPPLNQRENRDAKEPLTGTILEMWDGEIYHYGLYVERGLVLGVHKPPAAIS
LAKVELTPLSLFWRPVYTPQYLISPDTLRRLHGESFPYTAFDNNCYAFCCWVLDLNDSWL
SRRMIQRTTGFFRPYQDWNRKPLPTMDDSKLKKVANIFL
------------------------------------------------------------

Score =  3534 bits (7708), Expect(3) = 0.0
Identities = 1448/1521 (95%), Positives = 1495/1521 (98%)
Frame = +1

Query: 541  PQYLISPDTLKKLHGETFPYTAFDNNCYAFCCWVLDLNDSWLSRRMIQRTTGFFRPYQDW 720
            PQYLISPDTL++LHGE+FPYTAFDNNCYAFCCWVLDLNDSWLSRRMIQRTTGFFRPYQDW
Sbjct: 179  PQYLISPDTLRRLHGESFPYTAFDNNCYAFCCWVLDLNDSWLSRRMIQRTTGFFRPYQDW 238

Query: 721  NRKPLPTIDDSKLKKVANIFLCALSSLFTRPIKDIIGKLRPLNIINILASCDWTFAGIVE 900
            NRKPLPT+DDSKLKKVANIFLCALSSLFTRPIKDIIGKL+PLNI+NILASCDWTFAGIVE
Sbjct: 239  NRKPLPTMDDSKLKKVANIFLCALSSLFTRPIKDIIGKLKPLNILNILASCDWTFAGIVE 298

Query: 901  SLILLAELFGVFWTPPDVSAMIAPLLGDFELQGPEDLVVELVPVVMGGIGLVLGFTKEKI 1080
            SLILLAELFGVFWTPPDVSAMIAPLLGD+ELQGPEDL VELVPVVMGGIGLVLGFTKEKI
Sbjct: 299  SLILLAELFGVFWTPPDVSAMIAPLLGDYELQGPEDLAVELVPVVMGGIGLVLGFTKEKI 358

Query: 1081 GKMLSSAASTLRACKDLGAYGLEILKLVMKWFFPKKEEANELXMVRSIEDAVLDLEAIEN 1260
            GKMLSSAASTLRACKDLGAYGLEILKLVMKWFFPKKEEA+EL MVRSIEDAVLDLEAIEN
Sbjct: 359  GKMLSSAASTLRACKDLGAYGLEILKLVMKWFFPKKEEASELAMVRSIEDAVLDLEAIEN 418

Query: 1261 NHMTTLLKDKDSLATYMRTLDLEEEKARKLSTKSASPDIVGTINALLARIAAARSLVHRA 1440
            NH+TTLLKDKDSLATYMRTLDLEEEKARKLSTKSASPDIVGTINALLARIAAARSLVHRA
Sbjct: 419  NHLTTLLKDKDSLATYMRTLDLEEEKARKLSTKSASPDIVGTINALLARIAAARSLVHRA 478

Query: 1441 KEELSSRPRPVVLMISGRPGIGKTHLAREVAKRIAASLTGDQRVGLIPRNGVDHWDAYKG 1620
            KEELSSRPRPVV+MISG+PGIGKTHLARE+AK+IA +LTGDQRVGLIPRNGVDHWDAYKG
Sbjct: 479  KEELSSRPRPVVVMISGKPGIGKTHLARELAKKIATTLTGDQRVGLIPRNGVDHWDAYKG 538

Query: 1621 ERVVLWDDYGMSNPIHDALRLQELADTCPLTLNCDRIENKGKVFDSDVIIITTNLANPAP 1800
            ERVVLWDDYGMSNPIHDALRLQELADTCPLTLNCDRIENKGKVFDSD IIITTNLANPAP
Sbjct: 539  ERVVLWDDYGMSNPIHDALRLQELADTCPLTLNCDRIENKGKVFDSDAIIITTNLANPAP 598

Query: 1801 LDYVNFEACSRRIDFLVYAEAPEVEKAKRDFPGQPDMWKNAFSSDFSHIKLALAPQGGFD 1980
            LDYVNFEACSRRIDFLVYAEAP+VEKAKRDFPGQPDMWKNAFS DFSHIKL LAPQGGFD
Sbjct: 599  LDYVNFEACSRRIDFLVYAEAPDVEKAKRDFPGQPDMWKNAFSPDFSHIKLMLAPQGGFD 658

Query: 1981 KNGNTPHGKGVMKTLTTGSLIARASGLLHERLDEFELQGPALTTFNFDRNKVLAFRQLAA 2160
            KNGNTPHGKGVMKTLT GSLIARASGLLHERLDE+ELQGPALTTFNFDRNKVLAFRQLAA
Sbjct: 659  KNGNTPHGKGVMKTLTIGSLIARASGLLHERLDEYELQGPALTTFNFDRNKVLAFRQLAA 718

Query: 2161 ENKYGLMDTMKVGRQLKDVKTMPELKQALKNISIKKCQIVYSGCTYTLESDGKGNVKVDR 2340
            ENKYGLMDTM+VG QLK V+TMPELKQALKNISIK+CQIVY G TYTLESDGKG+V+VDR
Sbjct: 719  ENKYGLMDTMRVGGQLKGVRTMPELKQALKNISIKRCQIVYGGSTYTLESDGKGSVRVDR 778

Query: 2341 VQSTSVQTNNELAGALHHLRCARIRYYVKCVQEALYSIIQIAGAAFVTTRIIKRVNIQDL 2520
            VQS +VQTNNELAGALHHLRCARIRYYVKCVQEALYSIIQIAGAAFVTTRI+KR+NIQDL
Sbjct: 779  VQSATVQTNNELAGALHHLRCARIRYYVKCVQEALYSIIQIAGAAFVTTRIVKRMNIQDL 838

Query: 2521 WSKPQVENTEEATNKDGCPKPKDDEEFVISSDDIKTEGKKGKNKAGRGKKHTAFSSKGLS 2700
            WSKPQ+E+TEEAT KDGCPKPKDDEEFV+SSDDIK EGKKGKNK GRGKKHTAFSSKGLS
Sbjct: 839  WSKPQLEDTEEATGKDGCPKPKDDEEFVVSSDDIKVEGKKGKNKTGRGKKHTAFSSKGLS 898

Query: 2701 DEEYDEYKRIREERNGKYSIEEYLQDRDKYYEEVAIARATEEDFCEEEEAKIRQRIFRPT 2880
            DEEYDEYKRIREERNGKYSIEEYLQDRDKYYEEVAIARATEEDFCEEEEAKIRQRIFRPT
Sbjct: 899  DEEYDEYKRIREERNGKYSIEEYLQDRDKYYEEVAIARATEEDFCEEEEAKIRQRIFRPT 958

Query: 2881 RKQRKEERASLGLVTGSEIRKRNPEDFKPKGKLWADDDRSVDYNEKLSFEAPPSIWSRIV 3060
            RKQRKEERASLGLVTGSEIRKRNP+DFKPKGKLWADDDRSVDYNEKLSFEAPPSIWSRIV
Sbjct: 959  RKQRKEERASLGLVTGSEIRKRNPDDFKPKGKLWADDDRSVDYNEKLSFEAPPSIWSRIV 1018

Query: 3061 NFGSGWGFWVSPSLFITSTHVIPQGAKEFFGVPIKQIQVHKSGEFCRLRFPKPIRTDVTG 3240
            NFGSGWGFWVSPSLFITSTHVIPQG +EFFGV IKQIQ+HKSGEFCRLRFPKPIRTDVTG
Sbjct: 1019 NFGSGWGFWVSPSLFITSTHVIPQGTQEFFGVSIKQIQIHKSGEFCRLRFPKPIRTDVTG 1078

Query: 3241 MILEEGAPEGTVVTLLIKRSTGELMPLAARMGTHATMKIQGRTVGGQMGMLLTGSNAKSM 3420
            MILEEGAPEGTV TLLIKR TGELMPLAARMGTHATMKIQGRTVGGQMGMLLTGSNAKSM
Sbjct: 1079 MILEEGAPEGTVATLLIKRPTGELMPLAARMGTHATMKIQGRTVGGQMGMLLTGSNAKSM 1138

Query: 3421 DLGTTPGDCGCPYIYKRGNDYVVIGVHTAAARGGNTVICATQGGEGEATLEGGDSKGTYC 3600
            DLGTTPGDCGCPYIYKRGNDYVVIGVHTAAARGGNTVICATQG EGEATLEGGD+KGTYC
Sbjct: 1139 DLGTTPGDCGCPYIYKRGNDYVVIGVHTAAARGGNTVICATQGSEGEATLEGGDNKGTYC 1198

Query: 3601 GAPILGPGSAPKLSTKTKFWRSSTAPLPPGTYEPAYLGGKDPRVKGGPSLQQVMRDQLKP 3780
            GAPILGPGSAPKLSTKTKFWRSSTAPLPPGTYEPAYLGGKDPR+KGGPSLQQVMRDQLKP
Sbjct: 1199 GAPILGPGSAPKLSTKTKFWRSSTAPLPPGTYEPAYLGGKDPRIKGGPSLQQVMRDQLKP 1258

Query: 3781 FTEPRGKPPKPSVLEAAKKTIINVLEQTIDPPEKWSFAQACASLDKTTSSGHPHHLRKND 3960
            FTEPRGK PKPSVLEAAK+TIINVLEQTIDPP+KW+FAQACASLDKTTSSGHPHH+RKN+
Sbjct: 1259 FTEPRGKQPKPSVLEAAKRTIINVLEQTIDPPQKWTFAQACASLDKTTSSGHPHHIRKNE 1318

Query: 3961 CWNGESFTGKLADQASKANLMFEEGKNMTPVYTGALKDELVKTDKIYGKIKKRLLWGSDL 4140
            CWNG+SFTGKLADQASKANLMFEEGKNMTPVYTGALKDELVKTDKIYGKIKKRLLWGSDL
Sbjct: 1319 CWNGDSFTGKLADQASKANLMFEEGKNMTPVYTGALKDELVKTDKIYGKIKKRLLWGSDL 1378

Query: 4141 ATMIRCARAFGGLMDELKAHCVTLPIRVGMNMNEDGPIIFEKHSRYRYHYDADYSRWDST 4320
            ATMIRCARAFGGLMDELKAHCVTLP+RVGMNMNEDGPIIFEKHSRYRYHYDADYSRWDST
Sbjct: 1379 ATMIRCARAFGGLMDELKAHCVTLPVRVGMNMNEDGPIIFEKHSRYRYHYDADYSRWDST 1438

Query: 4321 QQRAVLAAALEIMVKFSSEPHLAQVVAEDLLSPSVVDVGDFTISINEGLPSGVPCTSQWN 4500
            QQRA+LAAALEIMVKFS EPHLAQ+VAEDLLSPSV+DVGDF ISINEGLPSGVPCTSQWN
Sbjct: 1439 QQRAILAAALEIMVKFSPEPHLAQIVAEDLLSPSVMDVGDFKISINEGLPSGVPCTSQWN 1498

Query: 4501 SIAHWLLTLCALSEVTNLSPDIIQANSLFSFYGDDEIVSTDIKLDPEKLTAKLKEYGLKP 4680
            SIAHWLLTLCALSEVT+LSPDI+QANSLFSFYGDDEIVSTDIKLDPEKLTAKLKEYGLKP
Sbjct: 1499 SIAHWLLTLCALSEVTDLSPDIVQANSLFSFYGDDEIVSTDIKLDPEKLTAKLKEYGLKP 1558

Query: 4681 TRPDKTEGPLVISEDLDGLTFLRRTVTRDPAGWFGKLEQSSILRQMYWTRGPNHEDPSES 4860
            TRPDKTEGPL+ISEDL+GLTFLRRTVTRDPAGWFGKLEQSSILRQMYWTRGPNHEDPSE+
Sbjct: 1559 TRPDKTEGPLIISEDLNGLTFLRRTVTRDPAGWFGKLEQSSILRQMYWTRGPNHEDPSET 1618

Query: 4861 MIPHSQRPIQLMSLLGEAALHGPTFYSKISKLVIAELKEGGMDFYVPRQEPMFRWMRFSD 5040
            MIPHSQRP QLMSLLGEAALHGP FYSKISKLVI ELKEGGMDFYVPRQEPMFRWMRFSD
Sbjct: 1619 MIPHSQRPTQLMSLLGEAALHGPAFYSKISKLVITELKEGGMDFYVPRQEPMFRWMRFSD 1678

Query: 5041 LSTWEGDRNLAPSFVNEDGVE 5103
            LSTWEGDRNLAPSFVNEDGVE
Sbjct: 1679 LSTWEGDRNLAPSFVNEDGVE 1699


========================================================================================================================

gene_id            %id    %sim   %cov   %t5   %gap  %t3   start..stop      pep sz ref sz ref id            definition
8.1                85.0   89.6   10.9   88.9  0.0   0.2   <1..90           57     540    AAZ31396.2        VP1 | putative capsid protein VP1, C-terminal
                                                          89..172                                          
                    frameshift in genome at or near position 90..89 (+1=>+2)

CLUSTAL 2.1 multiple sequence alignment


predicted       ------------------------------------------------------------
reference       MKMASNDATPSDGSTANLVPEVNNEVMALEPVVGAAIAAPVAGQQNVIDPWIRNNFVQAP
                                                                            

predicted       ------------------------------------------------------------
reference       GGEFTVSPRNAPGEILWSAPLGPDLNPYLSHLARMYNGYAGGFEVQVILAGNAFTAGKII
                                                                            

predicted       ------------------------------------------------------------
reference       FAAVPPNFPTEVLSPSQVTMFPHIIVDVRQLEPVLIPLPDVRNNLYHYNQSNDPTIRLIA
                                                                            

predicted       ------------------------------------------------------------
reference       MLYTPLRANNAGDDVFTVSCRVLTRPSPDFDFIFLVPPTVESRTKPFSVPILTVEEMTNS
                                                                            

predicted       ------------------------------------------------------------
reference       RFPIPLEKLFTGPSSAFVVQPQNGRCTTDGVLLGTTQLSPVNICTFRGDVTHIAGTQNYT
                                                                            

predicted       ------------------------------------------------------------
reference       MNLASQNWNNYDPTEEIPAPLGTPDFVGRIQGVLTQTTRRDGSTRGHKATVSTGSVHFTP
                                                                            

predicted       ------------------------------------------------------------
reference       KLGSVQFSTDTSNDFETGQNTRFTPVGVVQDGSTTHQNEPQQWVLPDYSGRDSHNVHLAP
                                                                            

predicted       ------------------------------------------------------------
reference       AVAPTFPGEQLLFFRSTMPGCSGYPNMNLDCLLPQEWVQHFYQESAPAQSDVALLRFVNP
                                                                            

predicted       DTGRVLYECKLHKSGYVTVAHTGQHDLVIPPPNGYFRFDSWVNQFYTLAPHGK---RNGA
reference       DTGRVLFECKLHKSGYVTVAHTGQHDLVIPP-NGYFRFDSWVNQFYTLAPMGNGAGRRRA
                ******:************************ ****************** *:   *. *

predicted       -
reference       L

>8.1	1	172
GACACGGGTAGGGTCCTGTATGAGTGCAAACTTCATAAATCAGGCTATGTCACAGTGGCT
CACACCGGTCAGCATGATTTGGTCATCCCCCCCCAATGGCTATTTTAGGTTTGATTCATG
GGTTAATCAGTTCTACACGCTTGCCCCCCATGGGAAACGGAACGGGGCGTAGgcgcgcct
tataatggctggagctttctttgctgrattggcatctgatgtccttggctctggacttgg
ttccstaatcaatgctggggctggggccatcaaccaaaagattgatttkgaaaataatag
aaaaattgcascaagyttcyttccagtttagcagtaatstacaacaggcttcctttcaac
acgataaagagatgctccaagcacaaatggaggccaytaaaaagttgcaacaggaaataa
tgaaagccaaacaggcaatgctcctagaaggtggattctctgaaacagatgc

Length = 540

Score =  80.8 bits (170), Expect(2) = 4e-32
Identities = 31/35 (88%), Positives = 32/35 (91%)
Frame = +1

Query: 1   DTGRVLYECKLHKSGYVTVAHTGQHDLVIPPQWLF 105
           DTGRVL+ECKLHKSGYVTVAHTGQHDLVIPP   F
Sbjct: 481 DTGRVLFECKLHKSGYVTVAHTGQHDLVIPPNGYF 515

------------------------------------------------------------
frameshifted from +1 to +2 between 1-328
     1 GACACGGGTAGGGTCCTGTATGAGTGCAAACTTCATAAATCAGGCTATGTCACAGTGGCT 60    
    61 CACAcCGGTCAGCATGATTTGGTCATcCCCCCCCAATGGCTAtTTTAGGTTTGATTCATG 120   
   121 GGTTAATCAGTTCTACACGCTTGcCCCCCATGGGAAACGGAACGGGGCGTAGGCGCGCCT 180   
   181 TATAATGGCTGGAGCTTTCTTTGCTGRATTGGCATCTGATGTCCTTGGCTCTGGACTTGG 240   
   241 TTCCSTAATCAATGCTGGGGCTGGGGCCATCAACCAAAAGATTGATTTKGAAAATAATAG 300   
   301 aAAAATTGCASCAAGYTTCYTTCCAGTT                                 328   
 frame +1
     1  d -T--G--R--V--L- y -E--C--K--L--H--K--S--G--Y--V--T--V--A- 60     |
    61 -H--T--G--Q--H--D--L--V--I--P--P- q  w  l -F- *  v  *  f  m  120    |
   121  g  *  s  v  l  h  a  c -P- p  w  e  t  e  r  g  v  g -A- p  180   
   181  y  n  g  w  s  f  l  c  x  i  g  i  *  c  p  w  l  w  t  w  240   
   241  f  x  n  q  c  w  g  w  g  h  q  p  k  d  *  f  x  k  *  *  300   
   301  k  n  c  x  k  x  x  s  s                                   328   
 frame +2
     1   t  r  v  g  s  c  m  s  a  n  f  i  n  q  a  m  s  q  w  l 60    
    61   t  p  v  s  m  i  w  s  s -P--P--N--G--Y--F--R--F--D--S--W 120    |
   121 --V--N--Q--F--Y--T--L--A--P- h -G- k  r  n -G- a  *  a  r -L 180    |
   181 - i  m  a  g  a  f  f  a  x  l  a  s  d  v  l  g  s  g  l  g 240   
   241   s  x  i  n  a  g  a  g  a  i  n  q  k  i  d  x  e  n  n  r 300   
   301   k  i  a  x  s  f  x  p  v                                  328   
 frame +3
     1    h  g  *  g  p  v  *  v  q  t  s  *  i  r  l  c  h  s  g   60    
    61 s -H- r  s  a  *  f  g  h  p -P--P- m  a  i  l  g  l  i  h   120   
   121 g  l  i  s  s  t  r -L- p -P--M--G--N--G- t -G--R--R--R--A-- 180    |
   181 L- *  w  l  e  l  s  l  l  x  w  h  l  m  s  l  a  l  d  l   240   
   241 v  p  *  s  m  l  g  l  g  p  s  t  k  r  l  i  x  k  i  i   300   
   301 e  k  l  x  q  x  s  f  q                                    328   

reference sequence 481-540
TGRVLFECKLHKSGYVTVAHTGQHDLVIPPNGYFRFDSWVNQFYTLAPMGNGAGRRRAL
------------------------------------------------------------

Score =  60.2 bits (125), Expect(2) = 4e-32
Identities = 22/26 (84%), Positives = 22/26 (84%)
Frame = +2

Query: 89  PPNGYFRFDSWVNQFYTLAPHGKRNG 166
           PPNGYFRFDSWVNQFYTLAP G   G
Sbjct: 510 PPNGYFRFDSWVNQFYTLAPMGNGAG 535


========================================================================================================================

gene_id            %id    %sim   %cov   %t5   %gap  %t3   start..stop      pep sz ref sz ref id            definition
8.2                88.8   95.1   96.6   0.0   0.0   3.4   185..304         260    268    AEX91911.1        VP2 | putative capsid protein VP2, N-terminal
                                                          303..>964                                        
                    frameshift in genome at or near position 304..303 (+2=>+3)

CLUSTAL 2.1 multiple sequence alignment


predicted       MAGAFFAXLASDVLGSGLGSXINAGAGAINQKIDXENNRKKLXQXSFQFSSNXQQASFQH
reference       MAGAFFAGLASDVLGSGLGSLINAGAGAINQKVEFENNRK-LQQSSFQFSSSLQQASFQH
                ******* ************ ***********:: ***** * * ******. *******

predicted       DKEMLQAQMEAXKKLQQEIMKAKQAMLLEGGFSETDAARGAINAPMTKVLDWSGTRYWAP
reference       DKEMLQAQIEATKKLQQEMMRVKQAMLLEGGFSETDAARGAINAPMTKTLDWSGTRYWAP
                ********:** ******:*:.**************************.***********

predicted       DARTATYNAGRFSTPQPSGTLPGRINPRTPTPARGSSSTSSNASTATSIHSNQTVSTRLG
reference       DARTTTYNAGRFSTPQPSGALPGRANLRATVPARGSSSTSSNSSIATSVYSNQTTSTRLG
                ****:**************:**** * *:..***********:* ***::****.*****

predicted       STAGSGTNVSSLPSTARTRSWVEDQNRNLSPFMRGAHNISFVTPPSSRSSSQGTVSTVPK
reference       STAGSGTSVSSLPSTARTRSWVEDQNRNLSPFMRGAHNISFVTPPSSRSSSQGTVSTVPK
                *******.****************************************************

predicted       EVLDSWTGAFNTRRQPLFAH---------
reference       EVLDSWTGAFNTRRQPLFAHIRKRGESRV
                ********************

>8.2	185	962
gacacgggtagggtcctgtatgagtgcaaacttcataaatcaggctatgtcacagtggct
cacaccggtcagcatgatttggtcatccccccccaatggctattttaggtttgattcatg
ggttaatcagttctacacgcttgccccccatgggaaacggaacggggcgtaggcgcgcct
tataATGGCTGGAGCTTTCTTTGCTGRATTGGCATCTGATGTCCTTGGCTCTGGACTTGG
TTCCSTAATCAATGCTGGGGCTGGGGCCATCAACCAAAAGATTGATTTKGAAAATAATAG
AAAAATTGCASCAAGYTTCYTTCCAGTTTAGCAGTAATSTACAACAGGCTTCCTTTCAAC
ACGATAAAGAGATGCTCCAAGCACAAATGGAGGCCAYTAAAAAGTTGCAACAGGAAATAA
TGAAAGCCAAACAGGCAATGCTCCTAGAAGGTGGATTCTCTGAAACAGATGCAGCCCGTG
GGGCAATCAACGCCCCCATGACAAAGGTTTTGGAYTGGAGCGGAACAAGGTATTGGGCCC
CCGATGCTAGGACCGCAACATACAATGCAGGCCGCTTTTCCACCCCTCAACCTTCGGGGA
CGCTGCCAGGAAGAATCAATCCCAGGACTCCTACCCCCGCTCGGGGCTCCTCCAGCACAT
CTTCTAATGCTTCTACTGCTACTTCTATACATTCAAATCAAACTGTTTCAACGAGACTTG
GTTCTACAGCTGGTTCTGGTACCAATGTCTCGAGTCTCCCGTCAACTGCAAGGACTAGGA
GTTGGGTTGAGGATCAAAACAGAAATTTGTCACCTTTCATGAGGGGGGCTCATAACATAT
CGTTTGTCACCCCACCATCTAGCAGATCCTCTAGCCAAGGCACAGTCTCAACCGTGCCTA
AAGAAGTTTTGGACTCCTGGACTGGCGCTTTCAACACGCGCAGGCAGCCTCTCTTCGCTC
ACat

Length = 268

Score =  84.5 bits (178), Expect = 6e-21
Identities = 36/44 (81%), Positives = 39/44 (88%)
Frame = +2

Query: 185 MAGAFFAXLASDVLGSGLGSXINAGAGAINQKIDXENNRKIAXS 316
           MAGAFFA LASDVLGSGLGS INAGAGAINQK++ ENNRK+  S
Sbjct: 1   MAGAFFAGLASDVLGSGLGSLINAGAGAINQKVEFENNRKLQQS 44

------------------------------------------------------------
frameshifted from +2 to +3 between 77-497
    77 ATTTGGTCATcCCCCCCCAATGGCTAtTTTAGGTTTGATTCATGGGTTAATCAGTTCTAC 136   
   137 ACGCTTGcCCCCCATGGGAAACGGAACGGGGCGTAGGCGCGCCTTATAATGGCTGGAGCT 196   
   197 TTCTTTGCTGRATTGGCATCTGATGTCCTTGGCTCTGGACTTGGTTCCSTAATCAATGCT 256   
   257 GGGGCTGGGGCCATCAACCAAAAGATTGATTTKGAAAATAATAGaAAAATTGCASCAAGY 316   
   317 TTCYTTCCAGTTTAGCAGTAATSTACAACAGGCTTCCTTTCAACACGATAAAGAGATGCT 376   
   377 CCAAGCACAAATGGAGGCCAYTAAAAAGTTGCAACAGGAAATAATGAAAGCCAAACAGGC 436   
   437 AATGCTCCTAGAAGGTGGATTCTCTGAAACAGATGCAGCCCGTGGGGCAATCAACGCCCC 496   
   497 C                                                            497   
 frame +2
    77  i  w  s  s  p  p  n  g  y  f  r  f  d  s  w  v  n  q  f  y  136   
   137  t  l  a  p  h  g  k  r  n  g  a  *  a  r  l  i  m -A--G--A- 196    |
   197 -F--F--A- x -L--A--S--D--V--L--G--S--G--L--G--S- x -I--N--A- 256    |
   257 -G--A--G--A--I--N--Q--K- i  d  x -E--N--N--R--K- i  a  x -S- 316    |
   317  f  x  p  v  *  q  *  x  t  t  g  f  l  s  t  r  *  r  d  a  376   
   377  p  s  t  n  g  g  h  * -K- v  a  t  g  n  n  e  s  q  t  g  436   
   437  n  a  p  r  r  w  i  l  *  n  r  c  s  p  w  g  n  q  r -P- 496   
 frame +3
    77   f  g  h  p  p  p  m  a  i  l  g  l  i  h  g  l  i  s  s  t 136   
   137   r  l  p  p  m  g  n  g  t  g  r  r  r  a  l  *  w  l  e  l 196   
   197   s  l  l  x  w  h  l  m  s -L- a  l  d -L- v  p  *  s  m  l 256   
   257  -G- l -G- p  s  t  k  r  l  i  x  k  i  i  e -K--L- x -Q- x 316   
   317  -S--F--Q--F--S--S- n  x -Q--Q--A--S--F--Q--H--D--K--E--M--L 376    |
   377 --Q--A--Q- m -E--A- x -K--K--L--Q--Q--E- i -M- k  a -K--Q--A 436    |
   437 --M--L--L--E--G--G--F--S--E--T--D--A--A--R--G--A--I--N--A--P 496    |
   497 -                                                            497   
 frame +1
    77    l  v  i  p  p  q  w  l  f  *  v  *  f  m  g  *  s -V--L-  136   
   137 h  a  c  p  p  w  e  t  e  r -G- v -G--A- p  y  n  g  w  s - 196   
   197 F- l  c  x  i  g  i  *  c  p  w  l  w  t  w  f  x  n -Q- c   256   
   257 w  g  w  g -H- q  p  k  d  *  f  x  k  *  *  k  n  c  x  k   316   
   317 x  x  s  s  l  a -V- x  y  n  r -L- p  f  n  t  i  k  r  c   376   
   377 s  k  h  k  w  r  p  x  k  s  c  n  r  k  *  *  k  p  n  r   436   
   437 q  c  s  *  k  v  d  s  l  k  q  m  q  p  v  g  q  s  t  p   496   

reference sequence 1-104
AGAFFAGLASDVLGSGLGSLINAGAGAINQKVEFENNRKLQQSSFQFSSSLQQASFQHDK
EMLQAQIEATKKLQQEMMRVKQAMLLEGGFSETDAARGAINAPM
------------------------------------------------------------

Score =   469 bits (1019), Expect = e-137
Identities = 199/235 (84%), Positives = 211/235 (89%)
Frame = +3

Query: 258 GLGPSTKRLIXKIIEKLXQXSFQFSSNXQQASFQHDKEMLQAQMEAXKKLQQEIMKAKQA 437
           G G   +++  +   KL Q SFQFSS+ QQASFQHDKEMLQAQ+EA KKLQQE+M+ KQA
Sbjct: 25  GAGAINQKVEFENNRKLQQSSFQFSSSLQQASFQHDKEMLQAQIEATKKLQQEMMRVKQA 84

Query: 438 MLLEGGFSETDAARGAINAPMTKVLDWSGTRYWAPDARTATYNAGRFSTPQPSGTLPGRI 617
           MLLEGGFSETDAARGAINAPMTK LDWSGTRYWAPDART TYNAGRFSTPQPSG LPGR 
Sbjct: 85  MLLEGGFSETDAARGAINAPMTKTLDWSGTRYWAPDARTTTYNAGRFSTPQPSGALPGRA 144

Query: 618 NPRTPTPARGSSSTSSNASTATSIHSNQTVSTRLGSTAGSGTNVSSLPSTARTRSWVEDQ 797
           N R   PARGSSSTSSN+S ATS++SNQT STRLGSTAGSGT+VSSLPSTARTRSWVEDQ
Sbjct: 145 NLRATVPARGSSSTSSNSSIATSVYSNQTTSTRLGSTAGSGTSVSSLPSTARTRSWVEDQ 204

Query: 798 NRNLSPFMRGAHNISFVTPPSSRSSSQGTVSTVPKEVLDSWTGAFNTRRQPLFAH 962
           NRNLSPFMRGAHNISFVTPPSSRSSSQGTVSTVPKEVLDSWTGAFNTRRQPLFAH
Sbjct: 205 NRNLSPFMRGAHNISFVTPPSSRSSSQGTVSTVPKEVLDSWTGAFNTRRQPLFAH 259


========================================================================================================================

gene_id            %id    %sim   %cov   %t5   %gap  %t3   start..stop      pep sz ref sz ref id            definition
9.1                95.1   98.5   23.9   1.2   0.0   74.9  <1..39           406    1699   BAC98439.1        POL | putative nonstructural polyprotein, fragment
                                                          39..>1219                                        
                    frameshift in genome at or near position 39..39 (+1=>+3)
9.1.1              36.4   61.0   97.2   2.8   0.0   0.0   <1..39           309    398    NP_786945.1       putative protein p48, C-terminal
                                                          39..926                                          
9.1.2              46.4   81.2   25.9   0.0   0.0   74.1  927..>1217       97     363    NP_786946.1       putative NTPase, N-terminal

CLUSTAL 2.1 multiple sequence alignment


predicted       ---------------------KSSSDKMFSNMAVRRKGALGARPKQPPPREIPQRPPRPP
reference       MKMASNDASAAAAANSNNDTAKSSSDGVLSSMAVTFKRALGARPKQPPPREIPQRPPRPP
                                     ***** ::*.***  * **********************

predicted       TPELVKKIPPPPPNGEDEAVVSYSAKDGVSGLPELSTVRQPEETNTAFSVPPLNQRENRD
reference       TPELVKKIPPPPPNGEDEPVVSYSVKDGVSGLPELTTVRQPGETNTAFSVPPLNQRENRD
                ******************.*****.**********:***** ******************

predicted       AKEPLTGTILEMWDGEIYHYGLYVERGLVLGVHKPPAAISLAKVELTPLSLFWRPVYTPQ
reference       AKEPLTGTILEMWDGEIYHYGLYVERGLVLGVHKPPAAISLAKVELTPLSLFWRPVYTPQ
                ************************************************************

predicted       YLISPDTLKKLHGETFPYTAFDNNCYAFCCWVLDLNDSWLSRRMIQRTTGFFRPYQDWNR
reference       YLISPDTLRRLHGESFPYTAFDNNCYAFCCWVLDLNDSWLCRRMIQRTTGFFRPYQDWNR
                ********::****:*************************.*******************

predicted       KPLPTMDDSKLKKVANIFLCALSSLFTRPIKDIIGKLRPLNIINILASCDWTFAGIVESL
reference       KPLPTMDDSKLKKVANIFLCALSSLFTRPIKDIIGKLRPLNILNILASCDWTFAGIVESL
                ******************************************:*****************

predicted       ILLAELFGVFWTPPDVSAMIAPLLGDFELQGPEDLVVELVPVVMGGIGLVLGFTKEKIGK
reference       ILLAELFGVFWTPPDVSAMIAPLLGDYELQGPEDLAVELVPIVMGGIGLVLGFTKEKIGK
                **************************:********.*****:******************

predicted       MLSSAASTLRACKDLGAYGLEILKLVMKWFFPKKEEANELAMVRSIEDAVLDLEAIENNH
reference       MLSSAASTLRACKDLGAYGLEILKLVMKWFFPKKEEANELAMVRSIEDAVLDLEAIENNH
                ************************************************************

predicted       MTTLLKD-----------------------------------------------------
reference       MTALLKDKDSLATYMRTLDLEEEKARKLSTKSASPDIVGTINALLARIAAARSLVHRAKE
                **:****                                                     

predicted       ------------------------------------------------------------
reference       ELSSRPRPVVVMISGRPGIGKTHLARELAKRIAASLTGDQRVGLIPRNGVDHWDAYKGER
                                                                            

predicted       ------------------------------------------------------------
reference       VVLWDDYGMSNPIHDALRLQELADTCPLTLNCDRIENKGKVFDSDAIIITTNLANPAPLD
                                                                            

predicted       ------------------------------------------------------------
reference       YVNFEACSRRIDFLVYADAPEVEKAKRDFPGQPDMWKNAFSPDFSHIKLMLAPQGGFDKN
                                                                            

predicted       ------------------------------------------------------------
reference       GNTPHGKGVMKTLTTGSLIARASGLLHERLDEYELQGPTPTTFNFDRNKVLAFRQLAAEN
                                                                            

predicted       ------------------------------------------------------------
reference       KYGLMDTMRVGRQLKDVRTMPELKQALRNISIKSCQIVYGGCTYMLESDGKGDVKVDRVQ
                                                                            

predicted       ------------------------------------------------------------
reference       NATVQTNNELAGALHHLRCARIRYYVKCVQEALYSIIQIAGAAFVTTRIVKRMNIQDLWS
                                                                            

predicted       ------------------------------------------------------------
reference       KPQVEDTEETASKDGCPKPKDDDEFVVSSDDIKTEGKKGKNKSGRGKKHTAFSSKGLSDE
                                                                            

predicted       ------------------------------------------------------------
reference       EYDEYKRIREERNGKYSIEEYLQDRDKYYEEVAIARATEEDFCEEEEAKIRQRIFRPTRK
                                                                            

predicted       ------------------------------------------------------------
reference       QRKEERASLGLVTGSEIRKRNPDDFKPKGKLWADDDRSVDYNERLNFEAPPSIWSRIVNF
                                                                            

predicted       ------------------------------------------------------------
reference       GSGWGFWVSPSLFITSTHVIPQGAQEFFGVSIKQIQIHKSGEFCRLRFPKPIRTDVTGMI
                                                                            

predicted       ------------------------------------------------------------
reference       LEEGAPEGTVVTLLIKRPTGELMPLAARMGTHATMKIQGRTVGGQMGMLLTGSNAKSMDL
                                                                            

predicted       ------------------------------------------------------------
reference       GTTPGDCGCPYIYKRGNDYVVIGVHTAAARGGNTVICATQGSEGEATLEGGDNKGTYCGA
                                                                            

predicted       ------------------------------------------------------------
reference       PILGPGSAPKLSTKTKFWRSSTAPLPPGTYEPAYLGGKDPRVKGGPSLQQVMRDQLKPFT
                                                                            

predicted       ------------------------------------------------------------
reference       EPRGKPPKPSVLEAAKKTIINVLEQTIDPPQKWSFAQACASLDKTTSSGHPHHMRKNDCW
                                                                            

predicted       ------------------------------------------------------------
reference       NGESFTGKLADQASKANLMFEEGKNMTPVYTGALKDELVKTDKIYGRIKKRLLWGSDLAT
                                                                            

predicted       ------------------------------------------------------------
reference       MIRCARAFGGLMEELKAHCVTLPVRVGMNMNEDGPIIFERHSRYKYHYDADYSRWDSTQQ
                                                                            

predicted       ------------------------------------------------------------
reference       RAVLAAALEIMVKFSPEPHLAQKVAEDLLSPSVMDVGDFKISINEGLPSGVPCTSQWNSI
                                                                            

predicted       ------------------------------------------------------------
reference       AHWLLTLCALSEVTNLSPDIIQANSLFSFYGDDEIVSTDIKLDPEKLTAKLKEYGLKPTR
                                                                            

predicted       ------------------------------------------------------------
reference       PDKTEGPLVISEDLNGLTFLRRTVTRDPAGWFGKLEQSSILRQMYWTRGPNHEDPSETMI
                                                                            

predicted       ------------------------------------------------------------
reference       PHSQRPIQLMSLLGEAALHGPAFYSKISKLVIAELKEGGMDFYVPRQEPMFRWMRFSDLS
                                                                            

predicted       -------------------
reference       TWEGDRNLAPSFVNEDGVE

>9.1	1	1217
AAATCTTCAAGTGACAAAATGTTTTCTAACATGGCTGTAGAAGAAAGGGAGCCCTCGGGG
CGCGGCCTAAACAGCCCCCCCCGAGGGAAATACCACAAAGACCCCCACGACCACCTACTC
CAGAACTGGTCAAAAAGATCCCTCCTCCCCCGCCCAACGGAGAGGATGAAGCAGTGGTTT
CTTATAGTGCCAAAGATGGCGTTTCCGGTTTACCTGAGCTTTCCACCGTCAGGCAACCGG
AAGAAACCAATACGGCCTTCAGTGTCCCTCCACTCAACCAGAGGGAGAATAGAGATGCTA
AGGAACCACTGACTGGAACAATTCTGGAAATGTGGGATGGAGAAATCTACCATTATGGCC
TGTATGTTGAGCGAGGTCTTGTGCTGGGTGTGCACAAACCACCAGCTGCCATAAGCCTCG
CCAAGGTCGAACTAACACCACTCTCCTTGTTCTGGAGACCTGTGTACACTCCCCAGTACC
TCATCTCTCCAGATACTCTCAAGAAATTACACGGAGAAACGTTTCCCTACACAGCCTTTG
ACAACAATTGCTATGCCTTTTGTTGTTGGGTCCTGGATCTAAATGACTCGTGGCTGAGTA
GGAGAATGATCCAGAGAACAACTGGCTTCTTCAGACCCTACCAAGACTGGAATAGGAAAC
CCCTCCCCACTATGGATGATTCCAAATTAAAGAAGGTAGCTAACATATTCCTGTGCGCCC
TGTCTTCGCTATTCACCAGGCCCATAAAAGACATAATAGGAAAGCTAAGACCTCTCAACA
TCATCAACATCCTGGCTTCATGTGATTGGACTTTCGCAGGCATAGTGGAGTCCTTGATAC
TCTTGGCAGAGCTCTTTGGAGTCTTCTGGACACCCCCAGATGTGTCTGCGATGATTGCCC
CCTTACTCGGTGATTTCGAGTTACAAGGACCTGAGGACCTTGTAGTGGAGCTCGTCCCTG
TAGTAATGGGGGGAATTGGTTTGGTGCTGGGATTCACCAAAGAGAAGATTGGGAAAATGT
TGTCATCTGCTGCATCCACCTTGAGAGCTTGTAAAGATCTTGGTGCATATGGGCTAGAGA
TCCTAAAGTTAGTCATGAAGTGGTTCTTCCCGAAGAAAGAGGAGGCAAATGAACTGGCTA
TGGTGAGATCCATCGAGGATGCAGTACTGGACCTTGAGGCAATTGAAAACAACCATATGA
CCACCTTGCTCAAAGACaa

Length = 1699

Score =  25.4 bits (49), Expect(2) = 2e-04
Identities = 12/27 (44%), Positives = 15/27 (55%)
Frame = +1

Query: 1    KSSSDKMFSNMAVEEREPSGRGLNSPP 81
            KSSSD + S+MAV  +   G     PP
Sbjct: 22   KSSSDGVLSSMAVTFKRALGARPKQPP 48

------------------------------------------------------------
frameshifted from +1 to +3 between 1-284
     1 AAATCTTCAAGTGACAAAATGTTTTCTAACATGGCTGTAGAAGAAAGGGAGCCCTCGGGG 60    
    61 CGCGGCCTAAACAGCCCCCCCCGAGGGAAATACCACAAAGACCCCCACGACCACCTACTC 120   
   121 CAGAACTGGTCAAAAAGATCCCTCCTCCCCCGCCCAACGGAGAGGATGAAGCAGTGGTTT 180   
   181 CTTATAGTGCCAAAGATGGCGTTTCCGGTTTACCTGAGCTTTCCACCGTCAGGCAACCGG 240   
   241 AAGAAACCAATACGGCCTTCAGTGTCCCTCCACTCAACCAGAGG                 284   
 frame +1
     1  k -S--S- s  d  k  m  f -S- n  m  a  v  e  e -R- e  p  s  g  60    
    61 -R- g  l  n  s -P--P--R- g  k  y  h  k  d -P- h  d  h  l  l  120    |
   121  q  n  w  s -K- r  s  l  l -P- r  p  t -E- r  m  k  q  w  f  180   
   181  l  i -V- p  k  m  a  f  p  v  y  l  s  f  p  p  s  g  n  r  240   
   241  k  k  p  i  r  p -S--V- s  l  h  s  t -R-                   284   
 frame +2
     1   n  l  q  v  t  k  c  f  l  t  w  l  * -K- k  g  s  p  r  g 60    
    61   a  a  *  t  a -P- p -E- g  n  t  t  k  t  p  t  t -T- y  s 120   
   121   r  t  g  q  k  d -P- s  s -P- a  q  r  r  g  *  s  s  g  f 180   
   181   l  *  c  q  r  w  r  f  r  f  t  *  a  f  h -R--Q- a  t  g 240   
   241   r -N- q  y  g  l  q  c -P- s  t -Q- p -E-                  284   
 frame +3
     1    i  f  k  *  q  n  v  f  *  h  g  c  r  r -K- g -A--L--G-- 60     |
    61 A--R--P--K--Q--P--P--P--R--E--I--P--Q--R--P--P--R--P--P--T-- 120    |
   121 P--E--L--V--K--K--I--P--P--P--P--P--N--G--E--D--E- a -V--V-- 180    |
   181 S--Y--S- a -K--D--G--V--S--G--L--P--E--L- s -T--V--R--Q--P-  240    |
   241 e -E--T--N--T--A--F--S--V--P--P--L--N--Q--R-                 284    |

reference sequence 22-116
SSSDGVLSSMAVTFKRALGARPKQPPPREIPQRPPRPPTPELVKKIPPPPPNGEDEPVVS
YSVKDGVSGLPELTTVRQPGETNTAFSVPPLNQRE
------------------------------------------------------------

Score =   923 bits (2009), Expect = 0.0
Identities = 377/391 (96%), Positives = 384/391 (98%)
Frame = +3

Query: 45   KGALGARPKQPPPREIPQRPPRPPTPELVKKIPPPPPNGEDEAVVSYSAKDGVSGLPELS 224
            K ALGARPKQPPPREIPQRPPRPPTPELVKKIPPPPPNGEDE VVSYS KDGVSGLPEL+
Sbjct: 37   KRALGARPKQPPPREIPQRPPRPPTPELVKKIPPPPPNGEDEPVVSYSVKDGVSGLPELT 96

Query: 225  TVRQPEETNTAFSVPPLNQRENRDAKEPLTGTILEMWDGEIYHYGLYVERGLVLGVHKPP 404
            TVRQP ETNTAFSVPPLNQRENRDAKEPLTGTILEMWDGEIYHYGLYVERGLVLGVHKPP
Sbjct: 97   TVRQPGETNTAFSVPPLNQRENRDAKEPLTGTILEMWDGEIYHYGLYVERGLVLGVHKPP 156

Query: 405  AAISLAKVELTPLSLFWRPVYTPQYLISPDTLKKLHGETFPYTAFDNNCYAFCCWVLDLN 584
            AAISLAKVELTPLSLFWRPVYTPQYLISPDTL++LHGE+FPYTAFDNNCYAFCCWVLDLN
Sbjct: 157  AAISLAKVELTPLSLFWRPVYTPQYLISPDTLRRLHGESFPYTAFDNNCYAFCCWVLDLN 216

Query: 585  DSWLSRRMIQRTTGFFRPYQDWNRKPLPTMDDSKLKKVANIFLCALSSLFTRPIKDIIGK 764
            DSWL RRMIQRTTGFFRPYQDWNRKPLPTMDDSKLKKVANIFLCALSSLFTRPIKDIIGK
Sbjct: 217  DSWLCRRMIQRTTGFFRPYQDWNRKPLPTMDDSKLKKVANIFLCALSSLFTRPIKDIIGK 276

Query: 765  LRPLNIINILASCDWTFAGIVESLILLAELFGVFWTPPDVSAMIAPLLGDFELQGPEDLV 944
            LRPLNI+NILASCDWTFAGIVESLILLAELFGVFWTPPDVSAMIAPLLGD+ELQGPEDL 
Sbjct: 277  LRPLNILNILASCDWTFAGIVESLILLAELFGVFWTPPDVSAMIAPLLGDYELQGPEDLA 336

Query: 945  VELVPVVMGGIGLVLGFTKEKIGKMLSSAASTLRACKDLGAYGLEILKLVMKWFFPKKEE 1124
            VELVP+VMGGIGLVLGFTKEKIGKMLSSAASTLRACKDLGAYGLEILKLVMKWFFPKKEE
Sbjct: 337  VELVPIVMGGIGLVLGFTKEKIGKMLSSAASTLRACKDLGAYGLEILKLVMKWFFPKKEE 396

Query: 1125 ANELAMVRSIEDAVLDLEAIENNHMTTLLKD 1217
            ANELAMVRSIEDAVLDLEAIENNHMT LLKD
Sbjct: 397  ANELAMVRSIEDAVLDLEAIENNHMTALLKD 427


========================================================================================================================

gene_id            %id    %sim   %cov   %t5   %gap  %t3   start..stop      pep sz ref sz ref id            definition
25.1               94.9   98.7   100.0  0.0   0.0   0.0   5..1048          1801   1799   BAE43832.1        POL | nonstructural polyprotein
                                                          1048..1074                                       
                                                          1073..5407                                       
                    frameshifts in genome at or near positions 1048..1048 (+2=>+1) and 1074..1073 (+1=>+2)
25.1.1             87.5   96.5   100.0  0.0   0.0   0.0   5..1048          407    407    AFI08230_P37      protein p37
                                                          1048..1074                                       
                                                          1073..1222                                       
25.1.2             95.9   99.5   100.0  0.0   0.0   0.0   1223..2311       363    363    AFI08230_P40      NTPase
25.1.3             90.0   97.1   100.0  0.0   0.0   0.0   2312..2911       200    200    AFI08230_P20      protein p20
25.1.4             97.9   99.8   100.0  0.0   0.0   0.0   2912..3331       140    140    AFI08230_VPG      viral genome-linked protein
25.1.5             97.2   99.9   100.0  0.0   0.0   0.0   3332..3874       181    181    AFI08230_3CL      3C-like protease
25.1.6             96.3   99.3   100.0  0.0   0.0   0.0   3875..5404       510    510    AFI08230_POL      RNA-directed RNA polymerase

CLUSTAL 2.1 multiple sequence alignment


predicted       MMMASKDAIAVADVSNNNANTNNENIGSRLMARLRGRIGPQRGENTTKIKDANMALDLLR
reference       MMMASKDAIAVADVSNNNANTNNENIGSRLMARLRGRIGPQRGENTTKIKDANMALDLLR
                ************************************************************

predicted       RSQTPSPSRQDHPPKDQRDRPPRTAMEVRKTMGWDEEPRQQESTVKAWCDLAREEKEEIM
reference       RSQTPSPSRQDHPPKDQRDRPPRTAMEVRKTMGWDEEPRQQESTVKAWCDLAREEKEEIM
                ************************************************************

predicted       RNNEKLFDAGGVTPSTLPSTFERADPIDNPGEQQPVSWSASGGVDIGVNDLTTVRGPFWN
reference       RNNEKLFDAGGVAPAILPSTFERATPHESTDECQAVTWSASDGVDIGVDSLKTVRGPPWN
                ************:*: ******** * :...* *.*:****.******:.*.***** **

predicted       MCPLPPLDARNSGPAKEPLIGDMIEFYEGHIFHYAIYIGQGKTIGVHSPQAAFSIPRITI
reference       MCPLPPLEARNSGPAREPLIGDMVEFYEGHIFHYAIYIGQGKTIGVHSPQAAFSIPRITI
                *******:*******:*******:************************************

predicted       HPLVAWWRVCYVPTNQQRLTYDQLRELENEPWPYASITNNCYEFCCRVMALDDTWLERRL
reference       HPLVAWWRVCYTPTDQQRLTYDQLRELENEPWPYASITNNCYEFCCKVMALDDTWLQRKL
                ***********.**:*******************************:*********:*:*

predicted       VSTGKFNHPTQDWSQDTPDFHQDSKLEMVRDAVLSAINGLVSQPFKNIFLSKIKPFNMFL
reference       VTTGKFNHPTQEWSKDTPDFHQDSKLEMVRDAVLSAINGLVSQPFKNI-LSKIKPLN-LI
                *:*********:**:********************************* ******:* ::

predicted       NLLSNCDWTFMGVVELIVLLAELFDVFWTPPDISSFIASLLPEFHLQGPEDLARDLVPLV
reference       NLLSNCDWTFMGVVELIVLVAELFDVFWTPPDISSFIASLLPDFHLQGPEDLAKDLVPLI
                *******************:**********************:**********:*****:

predicted       LGGIGLAIGFTRDKVTKVMKSAVDGLRSATQLGQYGLEIFSIIKKYFFGGDQTEKTLRGI
reference       LGGIGLAIGFTRDKVTKVMKSAVDGLRSATQLGQYGLEIFSIIKKYFFGGDQTERTLRGI
                ******************************************************:*****

predicted       EDAVIDMEVLSSTNVTQLVKDKKLARTYMNVLDNEEEKARKLSVRSADPHIVTSVNNLIS
reference       EDAVIDMEVLSSTNVTQLVRDKKSAKAYMNILDIEEEKARKLSVRSADPHIVTSVNNLIS
                *******************:*** *::***:** **************************

predicted       RISMARSALAKAQAEMTSRPRPVVIMMCGPPGIGKTKAAEHLAGRLATEIRPGGKVGLVP
reference       RISMARSALAKAQAEMTSRIRPVVIMMCGPPGIGKTKAAEHLASRLATEIRPGGKVGLVP
                ******************* ***********************.****************

predicted       RESIDHWDGYHGEEVLLWDDYGMSKITEDCNKLQAIADTAPLSLNCDRIENKGMQFVSDA
reference       RESIDHWDGYHGEEVLLWDDYGMSKITEDCNKLQAIADTAPLSLNCDRIENKGMQFVSDA
                ************************************************************

predicted       IIITTNAPGPAPVDFVNLGPVCRRVDFLVYCSAPEIEQARRAHPGDTNAIKDLYKKDFSH
reference       IIITTNAPGPAPVDFVNLGPVCRRVDFLVYCSAPEIEQARRAHPGDTNAIKDLYKKDFSH
                ************************************************************

predicted       LKMDLAPQGGFDNQGNTPFGKGVMKPTTLNRLLIQATALTMERQDEFQLQGMVYNFDEDR
reference       LKMDLAPQGGFDNQGNTPFGKGVMKPTTLNRLLIQATALTMERQDEFQLQGMVYNFDEDR
                ************************************************************

predicted       VAAFTSLARANGLGLINMATLGKKLRNVKTMEGLRNALVGYKIGECDIIWNTRVYSIKSD
reference       VAAFTSLARANGLGLINMATLGKKLRNVKTMEGLRNALVGYRIEECDIIWNTRAYSIKSD
                *****************************************:* *********.******

predicted       GSTVTIKEKQAPISPQHQAICTATLALSRLRAARALAYASCLQSAVLSILQVAGSALVVS
reference       GKSVTIKEKQNQTSSQHQAVSTATLALSRLRAARAIAYASCLQSAVLSILQVAGSAVVVS
                *.:*******   *.****:.**************:********************:***

predicted       RAVKRMFGTRTEQPVLEGKHKEHNCRVHRAEAAGHGPIGHDGVIERYGLCESEQEEENEQ
reference       RAVKRMFGTSTEQPALEGGHKEHNCRVHRAQAAGHGPIGHDGVIERYGLCESEQEDESDQ
                ********* ****.*** ***********:************************:*.:*

predicted       TVELPTASKEGKNKGKTKKGRGRKSNFNAFSRRGLSDEEYEEYKKIREEKSGNYSIQEYL
reference       VVELPLANREGKNKGKTKKGRGRKSNFNAFSRRGLSDEEYEEYKKIREEKSGNYSIQEYL
                .**** *.:***************************************************

predicted       EDRQRYEEELAEVQAGGDGGIGETEAEIRHRVFYKSKSGMRKQRQEERRQLGLVSGSEIR
reference       EDRQRYEEELAEVQAGGDGGIGETEAEIRHRVFYKSKSGMRKQRQEERRQLGLVSGTEIR
                ********************************************************:***

predicted       KRKPIDWTPPKNDWSEDTRTVNYDEHISFEAPPSIWSRVVKFGSGWGFWVSSTVFITTTH
reference       KRKPIDWTPPKNDWSEDTRSVNYDEHISFEAPPSIWSRVVKFGSGWGFWVSSTVFITTTH
                *******************:****************************************

predicted       VIPPGAKEIFGESLSNVAIHRVGEFTQFRFSKKMRPDLTGMVLEEGCPEGTVCTIMIKRD
reference       VIPPGAKEIFGEALNNVAVHRVGEFTQFRFSKKMRPDLTGMVLEEGCSEGTVCTIMIKRD
                ************:*.***:****************************.************

predicted       SGELLPLAVRMGAVASMKIQGKLMHGQSGMLLTGANAKGMDLGTIPGDCGAPYVHKRGND
reference       SGELLPLAVRMGAVASMKIQGKLMHGQSGMLLTGANAKGMDLGTIPGDCGAPYVHKRGND
                ************************************************************

predicted       WVVCGVHAAATKSGNTVVCAIQGGDGEATLEGGGQNKGHYAGHPILRYGNGPSLSTKTKF
reference       WVVCGVHAAATKSGNTVVCAIQGGEGEATLEGGGQNKGHYAGHPILRYGNGPSLSTKTKF
                ************************:***********************************

predicted       WKSTPQPLPPGTYEPAYLGGRDPRVEGGPSLQQVLRDQLKPFAEPRGRLPEAGLLEAAVE
reference       WKSTPQPLPPGTYEPAYLGGRDPRVDGGPSLQQVLRDQLKPFAEPRGRLPEAGLLEAAVE
                *************************:**********************************

predicted       TVTNAIEQVMDTPVAWSYNDACMSLDKTTSSGHPHHKKKNDDWNGNSFVRELGDQAAHAN
reference       TVTNAIEQVMDTPVAWSFSDACMSLDKTTSSGHPHHKKKNDDWNGSSFVRELGDQAAHAN
                *****************:.**************************.**************

predicted       SMYELGKPMKPVYTAALKDELVKPDKVYTKIKKRLLWGADLGTVIRAARAFGPFCEAIKP
reference       NMYELGKSMKPVYTAALKDELVKPDKVYNKIKKRLLWGADLGTVIRAARAFGPFCEAIKP
                .******.********************.*******************************

predicted       HVIKLPIKVGMNAIEDGPLIYAEHSKYKFHYDADYTAWDSTQNREIMMESFNIMCKLTAN
reference       HVIKLPIKVGMNAIEDGPLIYAEHSKYKYHYDADYTAWDSTQNREIMMESFNIMCKLTAN
                ****************************:*******************************

predicted       PSLAAVVAQDLLSPSEMDVGDYVISVKDGLPSGFPCTSQVNSINHWILTLCALSEVTGLS
reference       PSLAAVVAQDLLSPSEMDVGDYVISVKDGLPSGFPCTSQVNSINHWILTLCALSEVTGLS
                ************************************************************

predicted       PDVIQSQSYFSFYGDDEIVSTDIEFDPIKLTQILKEYGLKPTRPDKTDGPIIVRQQVDGL
reference       PDVLQSQSYFSFYGDDEIVSTDVEFDPNKLTQVLKEYGLKPTRPDKTDGPIVVKQQVDGL
                ***:******************:**** ****:******************:*:******

predicted       VFLRRTISKDAIGYQGRLDRNSIERQLWWTRGPNHEDPFETLVPHSQRKVQLISLLGEAA
reference       VFLRRTISKDAIGYQGRLDRNSIERQLWWTRGPNHDDPFETLVPHSQRKVQLISLLGEAA
                ***********************************:************************

predicted       LHGEKFYRKIASRVIQEVKEGGLEIYIPGWQAMFRWMRFHDLSLWTGDRDLLPDYVNDDG
reference       LHGEKFYRKIASRVIQEVKEGGLEIYIPGWQAMFRWMRFHDLSLWTGDRDLLPDYVNDDG
                ************************************************************

predicted       V
reference       V
                *

>25.1	5	5407
gtgaATGATGATGGCGTCAAAAGACGCTATTGCCGTTGCTGATGTCAGCAATAACAATGC
TAACACCAACAATGAAAACATTGGGTCTCGCCTTATGGCGAGGCTCCGCGGACGTATAGG
TCCGCAGCGTGGTGAAAACACCACAAAAATAAAGGATGCCAATATGGCACTCGACCTTCT
TCGCCGGTCACAAACACCCTCCCCATCCCGGCAAGACCACCCCCCAAAAGACCAAAGAGA
TCGTCCACCGCGCACTGCTATGGAGGTGAGGAAGACAATGGGGTGGGATGAAGAGCCAAG
ACAGCAGGAGAGCACCGTTAAGGCGTGGTGCGACCTCGCAAGGGAGGAAAAAGAGGAGAT
AATGCGCAATAACGAGAAGCTCTTTGATGCCGGGGGAGTTACCCCTTCAACTCTGCCTAG
CACGTTTGAGAGGGCTGATCCAATTGACAACCCTGGTGAACAGCAACCAGTATCATGGTC
CGCCAGTGGTGGAGTCGATATTGGTGTCAATGACTTAACCACTGTTCGTGGCCCATTTTG
GAATATGTGCCCCCTTCCACCACTGGATGCCCGTAATAGCGGCCCCGCTAAGGAACCCCT
TATAGGAGACATGATAGAATTCTATGAAGGTCACATATTCCATTATGCCATCTATATTGG
ACAGGGTAAGACCATTGGAGTCCACTCACCGCAAGCGGCTTTCTCCATACCCAGAATAAC
TATTCATCCTCTAGTGGCTTGGTGGCGCGTGTGTTACGTTCCAACTAACCAGCAGCGCCT
TACCTACGACCAACTCAGAGAACTAGAGAATGAGCCATGGCCCTATGCTTCCATCACTAA
CAATTGCTATGAGTTTTGCTGTAGGGTGATGGCACTTGATGACACCTGGCTTGAGAGAAG
GTTAGTTAGCACTGGGAAGTTCAATCACCCCACACAAGATTGGTCACAAGATACCCCAGA
TTTTCATCAAGACTCAAAACTTGAGATGGTGAGGGACGCTGTGCTATCAGCTATTAATGG
CCTTGTGTCACAACCCTTCAAAAATATTTTTTGTCAAAGATCAAGCCATTTAATGTTTCT
CAATCTCTTATCAAACTGTGATTGGACTTTCATGGGAGTTGTGGAGTTGATTGTACTCCT
GGCAGAACTGTTTGATGTGTTTTGGACTCCACCAGACATTTCAAGTTTCATCGCCTCACT
ACTACCTGAGTTCCATTTACAGGGCCCAGAAGACCTAGCTAGAGACCTGGTCCCCCTCGT
TCTAGGTGGCATAGGTCTGGCAATTGGCTTCACGAGAGATAAGGTGACAAAGGTGATGAA
GAGCGCCGTTGATGGACTGCGGTCGGCAACACAGCTTGGGCAGTACGGGCTAGAAATATT
CTCAATTATTAAGAAATACTTCTTTGGTGGGGACCAAACAGAAAAGACCTTACGAGGCAT
AGAAGATGCAGTGATAGATATGGAGGTGTTATCTAGCACCAATGTGACACAACTAGTTAA
AGATAAGAAGTTGGCCAGAACATACATGAATGTGCTAGACAATGAAGAGGAAAAAGCAAG
AAAACTCTCAGTCCGTAGTGCTGACCCACACATAGTAACCTCAGTCAACAACCTAATATC
ACGTATATCTATGGCAAGGTCAGCCTTGGCTAAAGCTCAGGCTGAGATGACATCTCGCCC
ACGCCCAGTGGTTATAATGATGTGTGGCCCCCCTGGCATCGGAAAGACCAAGGCCGCCGA
ACACCTAGCCGGCCGGTTGGCCACTGAAATCAGACCAGGTGGCAAGGTTGGGCTCGTGCC
CCGTGAATCCATAGACCATTGGGACGGTTATCATGGTGAAGAGGTCCTGTTGTGGGATGA
CTACGGCATGTCAAAGATAACAGAAGATTGTAACAAGTTACAAGCCATTGCTGACACTGC
ACCACTGTCACTGAATTGTGACAGGATAGAGAACAAAGGCATGCAGTTCGTCTCTGATGC
AATAATTATAACAACCAATGCTCCTGGCCCAGCCCCAGTCGACTTTGTCAATTTAGGACC
CGTGTGCAGACGGGTAGATTTTCTAGTCTACTGTTCTGCGCCTGAAATTGAACAGGCACG
GAGGGCCCACCCAGGCGATACCAATGCTATAAAAGACTTGTATAAGAAAGACTTCTCACA
CCTAAAGATGGATCTGGCTCCACAGGGGGGCTTTGATAACCAGGGTAACACGCCCTTTGG
CAAGGGTGTGATGAAACCCACTACCCTTAACAGACTACTAATCCAAGCCACTGCGCTGAC
CATGGAAAGGCAAGATGAATTCCAACTCCAAGGCATGGTTTACAACTTTGATGAGGACAG
GGTGGCAGCATTCACCAGCTTGGCTCGTGCTAACGGGTTGGGGCTTATCAATATGGCAAC
TCTGGGCAAGAAACTAAGAAATGTTAAGACCATGGAGGGCCTGCGCAACGCACTGGTGGG
CTACAAAATAGGTGAGTGTGATATAATCTGGAACACCAGAGTGTATTCAATCAAAAGTGA
TGGTAGCACCGTTACAATTAAGGAAAAACAAGCTCCAATTTCACCTCAGCACCAAGCCAT
CTGCACAGCCACTCTTGCACTCTCTAGATTGCGGGCTGCTAGAGCTCTCGCGTACGCCTC
CTGCCTGCAAAGTGCAGTACTATCAATACTCCAGGTAGCTGGCTCTGCCCTAGTGGTGAG
CAGGGCTGTGAAACGCATGTTTGGCACACGCACTGAGCAACCCGTGTTAGAAGGTAAACA
TAAAGAACACAATTGCAGAGTGCATCGCGCAGAAGCGGCTGGTCATGGTCCCATTGGACA
TGATGGGGTCATTGAACGTTACGGTCTGTGTGAGAGTGAACAGGAAGAAGAAAACGAGCA
AACAGTTGAGCTACCCACTGCTAGCAAAGAAGGTAAGAACAAGGGTAAGACCAAGAAGGG
TCGTGGGCGAAAATCCAATTTCAACGCTTTCTCAAGACGTGGCCTTAGTGATGAGGAGTA
TGAGGAGTATAAAAAGATTAGAGAGGAGAAGAGTGGCAATTACAGCATCCAGGAGTATCT
TGAGGACCGCCAGCGCTATGAGGAAGAACTTGCTGAAGTGCAGGCTGGTGGGGATGGTGG
AATTGGTGAAACTGAAGCAGAGATTCGCCACCGAGTTTTCTATAAGTCAAAATCCGGTAT
GAGGAAACAACGCCAAGAAGAGCGGCGCCAGTTGGGCCTCGTGAGTGGCTCTGAGATCCG
CAAGCGCAAGCCTATAGACTGGACCCCCCCTAAGAATGACTGGTCAGAAGACACCAGAAC
TGTCAACTATGATGAACACATCAGTTTTGAGGCCCCACCTTCAATTTGGAGCAGAGTGGT
GAAGTTTGGCAGTGGCTGGGGTTTTTGGGTGAGCTCAACAGTGTTCATAACTACAACTCA
TGTTATACCACCTGGGGCTAAAGAAATCTTTGGTGAAAGCCTTAGCAATGTGGCCATCCA
CAGGGTTGGTGAGTTCACCCAATTCCGTTTCTCCAAAAAGATGAGACCTGACCTCACTGG
TATGGTTCTGGAAGAGGGCTGCCCAGAGGGAACAGTGTGCACCATAATGATTAAGAGGGA
TTCTGGTGAGCTACTGCCACTCGCCGTGCGCATGGGGGCAGTTGCTTCAATGAAGATTCA
AGGGAAGCTCATGCATGGTCAGTCGGGGATGCTGCTCACTGGTGCCAACGCTAAAGGCAT
GGACCTTGGCACCATACCTGGAGACTGTGGGGCACCCTATGTTCACAAGAGAGGAAATGA
TTGGGTGGTCTGTGGAGTTCATGCAGCTGCCACAAAATCGGGTAATACTGTGGTGTGTGC
CATACAGGGCGGTGATGGCGAAGCCACACTAGAGGGTGGCGGCCAAAATAAAGGTCACTA
TGCAGGGCACCCGATATTAAGGTATGGAAATGGCCCTTCACTGTCAACAAAGACAAAATT
CTGGAAGTCCACTCCTCAACCTTTGCCCCCCGGCACATATGAGCCAGCTTACCTTGGTGG
TAGAGACCCTAGGGTTGAGGGGGGCCCATCCTTACAGCAAGTGTTGAGAGACCAGCTGAA
ACCATTTGCTGAGCCCCGTGGCAGACTACCCGAAGCGGGTCTGTTGGAAGCTGCAGTTGA
GACAGTCACTAATGCAATTGAACAGGTCATGGACACACCAGTGGCATGGAGTTATAATGA
TGCTTGCATGTCTCTAGATAAAACAACCAGCTCCGGCCACCCCCACCACAAAAAGAAGAA
TGATGATTGGAATGGAAATTCATTTGTGAGAGAACTAGGGGACCAGGCGGCACATGCTAA
CAGCATGTATGAGCTTGGCAAGCCCATGAAACCTGTGTACACAGCAGCCCTCAAAGATGA
ATTAGTTAAACCAGACAAGGTGTACACTAAGATCAAAAAGAGACTACTATGGGGCGCAGA
CCTTGGTACTGTTATCCGTGCCGCTAGAGCTTTTGGACCGTTCTGTGAAGCTATAAAACC
CCATGTGATTAAATTGCCTATTAAGGTAGGTATGAATGCTATAGAGGATGGCCCTTTGAT
TTATGCAGAGCACTCCAAATACAAGTTTCACTACGATGCTGACTACACAGCTTGGGACTC
AACACAAAACAGGGAGATCATGATGGAGTCTTTCAATATTATGTGTAAACTCACAGCCAA
CCCTTCCTTGGCCGCAGTGGTGGCACAGGATCTGCTCTCCCCATCTGAAATGGACGTTGG
CGATTATGTGATCAGTGTTAAAGATGGCCTACCGTCCGGCTTTCCATGCACCTCACAAGT
GAACAGTATCAACCATTGGATCTTAACTCTATGTGCACTGTCAGAGGTTACTGGTCTGTC
TCCTGATGTGATACAGTCACAATCTTACTTTTCATTTTATGGTGATGATGAAATAGTCTC
AACAGACATAGAATTTGACCCAATCAAATTGACACAAATACTGAAGGAGTATGGCTTGAA
GCCCACAAGACCTGACAAAACTGATGGCCCAATTATTGTTAGGCAGCAGGTAGATGGTTT
GGTTTTCCTCCGGCGTACCATCTCTAAAGACGCCATTGGATACCAGGGACGACTCGACCG
CAATTCCATCGAAAGACAGCTTTGGTGGACCCGCGGGCCGAATCACGAAGATCCATTCGA
GACACTGGTCCCACACTCGCAGAGGAAGGTCCAACTGATATCCCTGCTGGGTGAAGCTGC
ACTCCATGGTGAAAAATTCTACAGAAAGATAGCCAGCAGGGTTATTCAGGAAGTTAAAGA
GGGGGGACTTGAAATCTACATCCCTGGTTGGCAGGCCATGTTCCGCTGGATGCGATTCCA
TGACTTGAGTCTGTGGACGGGAGACCGCGATCTCCTGCCCGATTATGTAAATGATGATGG
CGTCTAAggacgccccaacaaacatggatggcaccagtggtgccggccagctggtaccag
aggcaaatacagctgagcctatatcaatggagcctgtggctggggcagcgacagctgccg
cgaccgctggccaagttaatatgattgacccctggattatgaataattatgtacaagccc
ctcaaggtgaatttaccatatcgcctaacaacacaccaggtgatattttatttgatctgc
aattaggcccccatctcaatcccttcttgtcccatttggcccagatgtataatggttggg
ttg

Length = 1799

Score =   799 bits (1739), Expect(2) = 0.0
Identities = 320/348 (91%), Positives = 335/348 (96%)
Frame = +2

Query: 5    MMMASKDAIAVADVSNNNANTNNENIGSRLMARLRGRIGPQRGENTTKIKDANMALDLLR 184
            MMMASKDAIAVADVSNNNANTNNENIGSRLMARLRGRIGPQRGENTTKIKDANMALDLLR
Sbjct: 1    MMMASKDAIAVADVSNNNANTNNENIGSRLMARLRGRIGPQRGENTTKIKDANMALDLLR 60

Query: 185  RSQTPSPSRQDHPPKDQRDRPPRTAMEVRKTMGWDEEPRQQESTVKAWCDLAREEKEEIM 364
            RSQTPSPSRQDHPPKDQRDRPPRTAMEVRKTMGWDEEPRQQESTVKAWCDLAREEKEEIM
Sbjct: 61   RSQTPSPSRQDHPPKDQRDRPPRTAMEVRKTMGWDEEPRQQESTVKAWCDLAREEKEEIM 120

Query: 365  RNNEKLFDAGGVTPSTLPSTFERADPIDNPGEQQPVSWSASGGVDIGVNDLTTVRGPFWN 544
            RNNEKLFDAGGV P+ LPSTFERA P ++  E Q V+WSAS GVDIGV+ L TVRGP WN
Sbjct: 121  RNNEKLFDAGGVAPAILPSTFERATPHESTDECQAVTWSASDGVDIGVDSLKTVRGPPWN 180

Query: 545  MCPLPPLDARNSGPAKEPLIGDMIEFYEGHIFHYAIYIGQGKTIGVHSPQAAFSIPRITI 724
            MCPLPPL+ARNSGPA+EPLIGDM+EFYEGHIFHYAIYIGQGKTIGVHSPQAAFSIPRITI
Sbjct: 181  MCPLPPLEARNSGPAREPLIGDMVEFYEGHIFHYAIYIGQGKTIGVHSPQAAFSIPRITI 240

Query: 725  HPLVAWWRVCYVPTNQQRLTYDQLRELENEPWPYASITNNCYEFCCRVMALDDTWLERRL 904
            HPLVAWWRVCY PT+QQRLTYDQLRELENEPWPYASITNNCYEFCC+VMALDDTWL+R+L
Sbjct: 241  HPLVAWWRVCYTPTDQQRLTYDQLRELENEPWPYASITNNCYEFCCKVMALDDTWLQRKL 300

Query: 905  VSTGKFNHPTQDWSQDTPDFHQDSKLEMVRDAVLSAINGLVSQPFKNI 1048
            V+TGKFNHPTQ+WS+DTPDFHQDSKLEMVRDAVLSAINGLVSQPFKNI
Sbjct: 301  VTTGKFNHPTQEWSKDTPDFHQDSKLEMVRDAVLSAINGLVSQPFKNI 348

Score =  3354 bits (7314), Expect(2) = 0.0
Identities = 1383/1445 (95%), Positives = 1421/1445 (98%)
Frame = +2

Query: 1070 LMFLNLLSNCDWTFMGVVELIVLLAELFDVFWTPPDISSFIASLLPEFHLQGPEDLARDL 1249
            L  +NLLSNCDWTFMGVVELIVL+AELFDVFWTPPDISSFIASLLP+FHLQGPEDLA+DL
Sbjct: 355  LNLINLLSNCDWTFMGVVELIVLVAELFDVFWTPPDISSFIASLLPDFHLQGPEDLAKDL 414

Query: 1250 VPLVLGGIGLAIGFTRDKVTKVMKSAVDGLRSATQLGQYGLEIFSIIKKYFFGGDQTEKT 1429
            VPL+LGGIGLAIGFTRDKVTKVMKSAVDGLRSATQLGQYGLEIFSIIKKYFFGGDQTE+T
Sbjct: 415  VPLILGGIGLAIGFTRDKVTKVMKSAVDGLRSATQLGQYGLEIFSIIKKYFFGGDQTERT 474

Query: 1430 LRGIEDAVIDMEVLSSTNVTQLVKDKKLARTYMNVLDNEEEKARKLSVRSADPHIVTSVN 1609
            LRGIEDAVIDMEVLSSTNVTQLV+DKK A+ YMN+LD EEEKARKLSVRSADPHIVTSVN
Sbjct: 475  LRGIEDAVIDMEVLSSTNVTQLVRDKKSAKAYMNILDIEEEKARKLSVRSADPHIVTSVN 534

Query: 1610 NLISRISMARSALAKAQAEMTSRPRPVVIMMCGPPGIGKTKAAEHLAGRLATEIRPGGKV 1789
            NLISRISMARSALAKAQAEMTSR RPVVIMMCGPPGIGKTKAAEHLA RLATEIRPGGKV
Sbjct: 535  NLISRISMARSALAKAQAEMTSRIRPVVIMMCGPPGIGKTKAAEHLASRLATEIRPGGKV 594

Query: 1790 GLVPRESIDHWDGYHGEEVLLWDDYGMSKITEDCNKLQAIADTAPLSLNCDRIENKGMQF 1969
            GLVPRESIDHWDGYHGEEVLLWDDYGMSKITEDCNKLQAIADTAPLSLNCDRIENKGMQF
Sbjct: 595  GLVPRESIDHWDGYHGEEVLLWDDYGMSKITEDCNKLQAIADTAPLSLNCDRIENKGMQF 654

Query: 1970 VSDAIIITTNAPGPAPVDFVNLGPVCRRVDFLVYCSAPEIEQARRAHPGDTNAIKDLYKK 2149
            VSDAIIITTNAPGPAPVDFVNLGPVCRRVDFLVYCSAPEIEQARRAHPGDTNAIKDLYKK
Sbjct: 655  VSDAIIITTNAPGPAPVDFVNLGPVCRRVDFLVYCSAPEIEQARRAHPGDTNAIKDLYKK 714

Query: 2150 DFSHLKMDLAPQGGFDNQGNTPFGKGVMKPTTLNRLLIQATALTMERQDEFQLQGMVYNF 2329
            DFSHLKMDLAPQGGFDNQGNTPFGKGVMKPTTLNRLLIQATALTMERQDEFQLQGMVYNF
Sbjct: 715  DFSHLKMDLAPQGGFDNQGNTPFGKGVMKPTTLNRLLIQATALTMERQDEFQLQGMVYNF 774

Query: 2330 DEDRVAAFTSLARANGLGLINMATLGKKLRNVKTMEGLRNALVGYKIGECDIIWNTRVYS 2509
            DEDRVAAFTSLARANGLGLINMATLGKKLRNVKTMEGLRNALVGY+I ECDIIWNTR YS
Sbjct: 775  DEDRVAAFTSLARANGLGLINMATLGKKLRNVKTMEGLRNALVGYRIEECDIIWNTRAYS 834

Query: 2510 IKSDGSTVTIKEKQAPISPQHQAICTATLALSRLRAARALAYASCLQSAVLSILQVAGSA 2689
            IKSDG +VTIKEKQ   S QHQA+ TATLALSRLRAARA+AYASCLQSAVLSILQVAGSA
Sbjct: 835  IKSDGKSVTIKEKQNQTSSQHQAVSTATLALSRLRAARAIAYASCLQSAVLSILQVAGSA 894

Query: 2690 LVVSRAVKRMFGTRTEQPVLEGKHKEHNCRVHRAEAAGHGPIGHDGVIERYGLCESEQEE 2869
            +VVSRAVKRMFGT TEQP LEG HKEHNCRVHRA+AAGHGPIGHDGVIERYGLCESEQE+
Sbjct: 895  VVVSRAVKRMFGTSTEQPALEGGHKEHNCRVHRAQAAGHGPIGHDGVIERYGLCESEQED 954

Query: 2870 ENEQTVELPTASKEGKNKGKTKKGRGRKSNFNAFSRRGLSDEEYEEYKKIREEKSGNYSI 3049
            E++Q VELP A++EGKNKGKTKKGRGRKSNFNAFSRRGLSDEEYEEYKKIREEKSGNYSI
Sbjct: 955  ESDQVVELPLANREGKNKGKTKKGRGRKSNFNAFSRRGLSDEEYEEYKKIREEKSGNYSI 1014

Query: 3050 QEYLEDRQRYEEELAEVQAGGDGGIGETEAEIRHRVFYKSKSGMRKQRQEERRQLGLVSG 3229
            QEYLEDRQRYEEELAEVQAGGDGGIGETEAEIRHRVFYKSKSGMRKQRQEERRQLGLVSG
Sbjct: 1015 QEYLEDRQRYEEELAEVQAGGDGGIGETEAEIRHRVFYKSKSGMRKQRQEERRQLGLVSG 1074

Query: 3230 SEIRKRKPIDWTPPKNDWSEDTRTVNYDEHISFEAPPSIWSRVVKFGSGWGFWVSSTVFI 3409
            +EIRKRKPIDWTPPKNDWSEDTR+VNYDEHISFEAPPSIWSRVVKFGSGWGFWVSSTVFI
Sbjct: 1075 TEIRKRKPIDWTPPKNDWSEDTRSVNYDEHISFEAPPSIWSRVVKFGSGWGFWVSSTVFI 1134

Query: 3410 TTTHVIPPGAKEIFGESLSNVAIHRVGEFTQFRFSKKMRPDLTGMVLEEGCPEGTVCTIM 3589
            TTTHVIPPGAKEIFGE+L+NVA+HRVGEFTQFRFSKKMRPDLTGMVLEEGC EGTVCTIM
Sbjct: 1135 TTTHVIPPGAKEIFGEALNNVAVHRVGEFTQFRFSKKMRPDLTGMVLEEGCSEGTVCTIM 1194

Query: 3590 IKRDSGELLPLAVRMGAVASMKIQGKLMHGQSGMLLTGANAKGMDLGTIPGDCGAPYVHK 3769
            IKRDSGELLPLAVRMGAVASMKIQGKLMHGQSGMLLTGANAKGMDLGTIPGDCGAPYVHK
Sbjct: 1195 IKRDSGELLPLAVRMGAVASMKIQGKLMHGQSGMLLTGANAKGMDLGTIPGDCGAPYVHK 1254

Query: 3770 RGNDWVVCGVHAAATKSGNTVVCAIQGGDGEATLEGGGQNKGHYAGHPILRYGNGPSLST 3949
            RGNDWVVCGVHAAATKSGNTVVCAIQGG+GEATLEGGGQNKGHYAGHPILRYGNGPSLST
Sbjct: 1255 RGNDWVVCGVHAAATKSGNTVVCAIQGGEGEATLEGGGQNKGHYAGHPILRYGNGPSLST 1314

Query: 3950 KTKFWKSTPQPLPPGTYEPAYLGGRDPRVEGGPSLQQVLRDQLKPFAEPRGRLPEAGLLE 4129
            KTKFWKSTPQPLPPGTYEPAYLGGRDPRV+GGPSLQQVLRDQLKPFAEPRGRLPEAGLLE
Sbjct: 1315 KTKFWKSTPQPLPPGTYEPAYLGGRDPRVDGGPSLQQVLRDQLKPFAEPRGRLPEAGLLE 1374

Query: 4130 AAVETVTNAIEQVMDTPVAWSYNDACMSLDKTTSSGHPHHKKKNDDWNGNSFVRELGDQA 4309
            AAVETVTNAIEQVMDTPVAWS++DACMSLDKTTSSGHPHHKKKNDDWNG+SFVRELGDQA
Sbjct: 1375 AAVETVTNAIEQVMDTPVAWSFSDACMSLDKTTSSGHPHHKKKNDDWNGSSFVRELGDQA 1434

Query: 4310 AHANSMYELGKPMKPVYTAALKDELVKPDKVYTKIKKRLLWGADLGTVIRAARAFGPFCE 4489
            AHAN+MYELGK MKPVYTAALKDELVKPDKVY KIKKRLLWGADLGTVIRAARAFGPFCE
Sbjct: 1435 AHANNMYELGKSMKPVYTAALKDELVKPDKVYNKIKKRLLWGADLGTVIRAARAFGPFCE 1494

Query: 4490 AIKPHVIKLPIKVGMNAIEDGPLIYAEHSKYKFHYDADYTAWDSTQNREIMMESFNIMCK 4669
            AIKPHVIKLPIKVGMNAIEDGPLIYAEHSKYK+HYDADYTAWDSTQNREIMMESFNIMCK
Sbjct: 1495 AIKPHVIKLPIKVGMNAIEDGPLIYAEHSKYKYHYDADYTAWDSTQNREIMMESFNIMCK 1554

Query: 4670 LTANPSLAAVVAQDLLSPSEMDVGDYVISVKDGLPSGFPCTSQVNSINHWILTLCALSEV 4849
            LTANPSLAAVVAQDLLSPSEMDVGDYVISVKDGLPSGFPCTSQVNSINHWILTLCALSEV
Sbjct: 1555 LTANPSLAAVVAQDLLSPSEMDVGDYVISVKDGLPSGFPCTSQVNSINHWILTLCALSEV 1614

Query: 4850 TGLSPDVIQSQSYFSFYGDDEIVSTDIEFDPIKLTQILKEYGLKPTRPDKTDGPIIVRQQ 5029
            TGLSPDV+QSQSYFSFYGDDEIVSTD+EFDP KLTQ+LKEYGLKPTRPDKTDGPI+V+QQ
Sbjct: 1615 TGLSPDVLQSQSYFSFYGDDEIVSTDVEFDPNKLTQVLKEYGLKPTRPDKTDGPIVVKQQ 1674

Query: 5030 VDGLVFLRRTISKDAIGYQGRLDRNSIERQLWWTRGPNHEDPFETLVPHSQRKVQLISLL 5209
            VDGLVFLRRTISKDAIGYQGRLDRNSIERQLWWTRGPNH+DPFETLVPHSQRKVQLISLL
Sbjct: 1675 VDGLVFLRRTISKDAIGYQGRLDRNSIERQLWWTRGPNHDDPFETLVPHSQRKVQLISLL 1734

Query: 5210 GEAALHGEKFYRKIASRVIQEVKEGGLEIYIPGWQAMFRWMRFHDLSLWTGDRDLLPDYV 5389
            GEAALHGEKFYRKIASRVIQEVKEGGLEIYIPGWQAMFRWMRFHDLSLWTGDRDLLPDYV
Sbjct: 1735 GEAALHGEKFYRKIASRVIQEVKEGGLEIYIPGWQAMFRWMRFHDLSLWTGDRDLLPDYV 1794

Query: 5390 NDDGV 5404
            NDDGV
Sbjct: 1795 NDDGV 1799


